### ISSUE TITLE
Add an option to configure far's editor to create new text files in utf-8 charset

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#100]
Add an option to configure far's editor to create new text files in utf-8 charset, and another option - to assume utf-8 encoding by default then opening files (as it is done in far3).

Or also hardcode utf-8 as default encoding instead of 1251 or 866.

Really, who needs whose two on linux systems?

**Comment by volth** [comment]
Also \r\n-lineending
new files are created using it, then, if the newly created file is a shell-script it cannot be executed

**Comment by invy** [comment]
https://github.com/invy/far2l/tree/utf8editor

try this, replaced non relevant 'default ANSI in editor' to 'default UTF8'

**Comment by invy** [comment]
@volth 
https://github.com/invy/far2l/tree/linefeed

**Comment by invy** [comment]
Only one thing is missing now: automatically disabling BOM for new utf8 files and enabling it for all other Unicode encodings.

**Comment by elfmz** [comment]
why disabling BOM? does it breaks something? IMHO all apps who understand UTF8 also understand BOM

**Comment by invy** [comment]
Byte order mark is only relevant for. 2 or 4 byte encoding.for utf8 is no bom required.

**Comment by elfmz** [comment]
Many application use it for detecting UTF8. Even if under Linux its normally defaulted to UTF8 its better not to fall into Linux-chauvinism and allow non-Linux apps to detect UTF8 encoding in files that were created by far2l under Linux and copied outside while this doesn't cause any problems for Linux apps.

**Comment by volth** [comment]
It is only a reasonable default for new files: ```UTF8, no-BOM, \n-lineending.```
Unless the ESC plugin is ported and there is no option to do make these defaults dependend on file name and extention of the file.

This is Linux-centic for sure as ```1251, \r\n``` is Windows-centric and problematic for many types of files (e.g. Java or Perl sources which is are mostly ```UTF8, no-BOM, \n-lineending.``` on any OS)

**Comment by elfmz** [comment]
I'm not about 1251 \r\n, I'm about UTF8's BOM. Can you give some examples where UTF8 with BOM doesn't work but UTF8 without BOM works?

**Comment by invy** [comment]
> Many application use it for detecting UTF8. 
BOM only serves the purpose of identifying endianes. Those applications, which try to relay on BOM when detecting UTF8, are wrong, unless they don't have very serious reasons to do that.

**Comment by elfmz** [comment]
> Those applications, which try to rely on BOM when detecting UTF8, are wrong, unless they don't have very serious reasons to do that.
This doesn't mean that such application should not be supported. World is not an ideal.

**Comment by invy** [comment]
They are well supported, by using "Save As" dialog. (As also utf16/32 without bom)
But putting bom in utf8 should not be the default behavior for Far because it's rare use case and this is harmful for scripting languages.

**Comment by elfmz** [comment]
agree about harmful

**Comment by unxed** [comment]
agree about harmful

**Comment by unxed** [comment]
Can we close this as fixed now?

**Comment by invy** [comment]
Well, BOM in UTF8 files is still there. We can make another ticket for it.

**Comment by unxed** [comment]
Do we need this issue still open?

**Comment by invy** [comment]
apparently no, since everything is implemented
