### ISSUE TITLE
CPack uses invalid characters for the DEB package version number

### ISSUE THREAD

**Issue by Devoter** [elfmz/far2l#1004]
I built a program from `master` branch and created a .deb package via cpack, but cannot install it. Dpkg throws an error:

```
'Version' field value '2.3.210528_2e3f6fc0_alpha': invalid character in version number
```

I guess, cpack uses something like `git describe --tags --long --always --dirty`, but it is a wrong way.

**Comment by daemonserj** [comment]
Та же фигня :(

**Comment by elfmz** [comment]
There was really git hash etc, now i replaced that with.. gits commit count. Since its  number that typically monotonically grows up, so should work fine as unique version number for lazy developers :) Please confirm if its fixed now for you.

**Comment by Devoter** [comment]
I guess, the issue can be closed. Thanks for fixing my fix again.
