### ISSUE TITLE
Desktop notifications - enable/disable

### ISSUE THREAD

**Issue by KarelWintersky** [elfmz/far2l#1006]
Предлагаю добавить в interface settings чекбокс
```
[ ] Send desktop notifications
```
При отключенном чекбоксе **не** вызывать `/usr/local/share/far2l/notify.sh`

**Comment by elfmz** [comment]
так ведь есть же - F9/Options/Notifications settings (в самом низу)

**Comment by KarelWintersky** [comment]
Это было неочевидно...
