### ISSUE TITLE
Shift+F* key presses don't work over VNC, like SHIFT-F4 no New file Dialog

### ISSUE THREAD

**Issue by daemonserj** [elfmz/far2l#1010]
Popups Edit file dialog as for F4

**Comment by elfmz** [comment]
For this and other your SHIFT-related bugs: what system configuration? OS, used far2l backend (TTY or WX?)

**Comment by daemonserj** [comment]
Ubuntu 20.4, WX version

**Comment by elfmz** [comment]
Strange, i have same and from 1st look this works fine. So seems to need more details
1 Wayland/X11?
2 May be you have specific international/input settings?

**Comment by elfmz** [comment]
Also plz do following test, in terminal type: `export FAR2L_STD=-` then run far2l from it by `far2l` command. far2l will be launched with debug logging enabled, first try to press/release shift keys, you should see in terminal events like
```
ConsoleInput::Enqueue: # 0 10 10 DOWN
OnKeyUp: raw=ffe1 code=132 uni=0 ( ) ts=193548
ConsoleInput::Enqueue: # 0 10 0 UP
OnKeyDown: raw=ffe1 code=132 uni=0 ( ) ts=193660 [now=216035144]
ConsoleInput::Enqueue: # 0 10 10 DOWN
OnKeyUp: raw=ffe1 code=132 uni=0 ( ) ts=193772
ConsoleInput::Enqueue: # 0 10 0 UP
```
 - please copy that log lines here, or if you dont see them - tell that.
After that, try to press several times sequence of: Shift+F4 -> Esc. Report produced by that keypresses terminal log lines here too.

**Comment by daemonserj** [comment]
Versions:

ii  libva-wayland2:amd64                                             2.7.0-2                               amd64        Video Acceleration (VA) API for Linux -- Wayland runtime
ii  libwayland-bin                                                   1.18.0-1                              amd64        wayland compositor infrastructure - binary utilities
ii  libwayland-client0:amd64                                         1.18.0-1                              amd64        wayland compositor infrastructure - client library
ii  libwayland-cursor0:amd64                                         1.18.0-1                              amd64        wayland compositor infrastructure - cursor library
ii  libwayland-dev:amd64                                             1.18.0-1                              amd64        wayland compositor infrastructure - development files
ii  libwayland-egl1:amd64                                            1.18.0-1                              amd64        wayland compositor infrastructure - EGL library
ii  libwayland-server0:amd64                                         1.18.0-1                              amd64        wayland compositor infrastructure - server library
ii  xwayland                                                         2:1.20.9-2ubuntu1.2~20.04.2           amd64        Xwayland X server

ii  libwxbase3.0-0v5:amd64                                           3.0.4+dfsg-15build1                   amd64        wxBase library (runtime) - non-GUI support classes of wxWidgets toolkit
ii  libwxbase3.0-dev:amd64                                           3.0.4+dfsg-15build1                   amd64        wxBase library (development) - non-GUI support classes of wxWidgets toolkit
ii  libwxgtk3.0-gtk3-0v5:amd64                                       3.0.4+dfsg-15build1                   amd64        wxWidgets Cross-platform C++ GUI toolkit (GTK 3 runtime)
ii  libwxgtk3.0-gtk3-dev:amd64                                       3.0.4+dfsg-15build1                   amd64        wxWidgets Cross-platform C++ GUI toolkit (GTK 3 development)
ii  wx-common                                                        3.0.4+dfsg-15build1                   amd64        wxWidgets Cross-platform C++ GUI toolkit (common support files)
ii  wx3.0-headers                                                    3.0.4+dfsg-15build1                   all          wxWidgets Cross-platform C++ GUI toolkit (header files)

**Comment by daemonserj** [comment]
SHIFT only


OnKeyDown: raw=ffe1 code=132 uni=0 ( ) ts=161209852 [now=250547486]
ConsoleInput::Enqueue: # 0 10 30 DOWN
OnKeyUp: raw=ffe1 code=132 uni=0 ( ) ts=161210122
ConsoleInput::Enqueue: # 0 10 20 UP
OnKeyDown: raw=ffe1 code=132 uni=0 ( ) ts=161211376 [now=250549010]
ConsoleInput::Enqueue: # 0 10 30 DOWN
OnKeyUp: raw=ffe1 code=132 uni=0 ( ) ts=161211601
ConsoleInput::Enqueue: # 0 10 20 UP
OnKillFocus

**Comment by daemonserj** [comment]
SHIFT-F4




OnKeyDown: raw=ffe1 code=132 uni=0 ( ) ts=161245465 [now=250583098]
ConsoleInput::Enqueue: # 0 10 30 DOWN
OnKeyUp: raw=ffe1 code=132 uni=0 ( ) ts=161245885
ConsoleInput::Enqueue: # 0 10 20 UP
OnKeyDown: raw=ff7f code=16c uni=0 ( ) ts=161245886 [now=250583521]
ConsoleInput::Enqueue: # 0 90 20 DOWN
OnKeyUp: raw=ff7f code=16c uni=0 ( ) ts=161245886
ConsoleInput::Enqueue: # 0 90 20 UP
OnKeyDown: raw=ffc1 code=157 uni=0 ( ) ts=161245887 [now=250583522]
ConsoleInput::Enqueue: # 0 73 20 DOWN
OnChar: raw=ffc1 code=157 uni=0 ( ) ts=161245887 lke=1
OnKeyUp: raw=ffc1 code=157 uni=0 ( ) ts=161245887
ConsoleInput::Enqueue: # 0 73 20 UP
OnKeyDown: raw=ffe1 code=132 uni=0 ( ) ts=161245887 [now=250583522]
ConsoleInput::Enqueue: # 0 10 30 DOWN
OnKeyDown: raw=ff7f code=16c uni=0 ( ) ts=161245887 [now=250583522]
ConsoleInput::Enqueue: # 0 90 30 DOWN
OnKeyUp: raw=ff7f code=16c uni=0 ( ) ts=161245888
ConsoleInput::Enqueue: # 0 90 30 UP
OnKeyUp: raw=ffe1 code=132 uni=0 ( ) ts=161246155
ConsoleInput::Enqueue: # 0 10 20 UP

**Comment by daemonserj** [comment]
MORE SHIFT-F4
OnKeyDown: raw=ffe1 code=132 uni=0 ( ) ts=162164871 [now=251502506]
ConsoleInput::Enqueue: # 0 10 30 DOWN
OnKeyUp: raw=ffe1 code=132 uni=0 ( ) ts=162167016
ConsoleInput::Enqueue: # 0 10 0 UP
OnKeyDown: raw=ff7f code=16c uni=0 ( ) ts=162167018 [now=251504657]
ConsoleInput::Enqueue: # 0 90 20 DOWN
OnKeyUp: raw=ff7f code=16c uni=0 ( ) ts=162167018
ConsoleInput::Enqueue: # 0 90 20 UP
OnKeyDown: raw=ffc1 code=157 uni=0 ( ) ts=162167020 [now=251504659]
ConsoleInput::Enqueue: # 0 73 20 DOWN
OnChar: raw=ffc1 code=157 uni=0 ( ) ts=162167020 lke=1
OnKeyUp: raw=ffc1 code=157 uni=0 ( ) ts=162167020
ConsoleInput::Enqueue: # 0 73 20 UP
OnKeyDown: raw=ffe1 code=132 uni=0 ( ) ts=162167020 [now=251504661]
ConsoleInput::Enqueue: # 0 10 30 DOWN
OnKeyDown: raw=ff7f code=16c uni=0 ( ) ts=162167022 [now=251504661]
ConsoleInput::Enqueue: # 0 90 30 DOWN
OnKeyUp: raw=ff7f code=16c uni=0 ( ) ts=162167023
ConsoleInput::Enqueue: # 0 90 30 UP
OnKeyUp: raw=ffe1 code=132 uni=0 ( ) ts=162167863
ConsoleInput::Enqueue: # 0 10 20 UP
OnKeyDown: raw=ffe1 code=132 uni=0 ( ) ts=162178550 [now=251516184]
ConsoleInput::Enqueue: # 0 10 30 DOWN
OnKeyUp: raw=ffe1 code=132 uni=0 ( ) ts=162178836
ConsoleInput::Enqueue: # 0 10 20 UP
OnKeyDown: raw=ff7f code=16c uni=0 ( ) ts=162178836 [now=251516476]
ConsoleInput::Enqueue: # 0 90 20 DOWN
OnKeyUp: raw=ff7f code=16c uni=0 ( ) ts=162178837
ConsoleInput::Enqueue: # 0 90 20 UP
OnKeyDown: raw=ffc1 code=157 uni=0 ( ) ts=162178837 [now=251516477]
ConsoleInput::Enqueue: # 0 73 20 DOWN
OnChar: raw=ffc1 code=157 uni=0 ( ) ts=162178837 lke=1
OnKeyUp: raw=ffc1 code=157 uni=0 ( ) ts=162178837
ConsoleInput::Enqueue: # 0 73 20 UP
OnKeyDown: raw=ffe1 code=132 uni=0 ( ) ts=162178837 [now=251516478]
ConsoleInput::Enqueue: # 0 10 30 DOWN
OnKeyDown: raw=ff7f code=16c uni=0 ( ) ts=162178838 [now=251516478]
ConsoleInput::Enqueue: # 0 90 30 DOWN
OnKeyUp: raw=ff7f code=16c uni=0 ( ) ts=162178838
ConsoleInput::Enqueue: # 0 90 30 UP
OnKeyUp: raw=ffe1 code=132 uni=0 ( ) ts=162179064
ConsoleInput::Enqueue: # 0 10 20 UP

**Comment by elfmz** [comment]
Shift events are those with code=132, interesting that most of them on your system receives keyup before keydown of 'main' key. This doesnt happen on my Ubuntu, something specific to your system, May be there is some software running that can steal shift?) Any suggestions are ok.. Also try to use right shift instead (if you have it).

**Comment by daemonserj** [comment]
First. I did it thru VNC (TightVNC Windows 7)
Next I always do it by pressing right shift.
Last. I use wireless A4Tech keyboard.
Now I'll try to do left shift without VNC

**Comment by elfmz** [comment]
Ugh! That was really important :)
Whats VNC server is running then on Linux?

**Comment by daemonserj** [comment]
I checked it by direct connection, all things works well.
So VNC is the problem.
I use default Gnome VNC shipped with Ubuntu 20.4

**Comment by elfmz** [comment]
Can you check if in any other app Shift+F4 works as expected? To do not think much, try `sudo apt install doublecmd-gtk` - it handles Shift+F4/F4 in a similar way.
If it will work correct, i\ll try to play with VNC too, but few hours later

**Comment by daemonserj** [comment]
Same thing - no new file

**Comment by elfmz** [comment]
So basically it means that VNC doesnt pass SHift+F* combinations. Its not a far2l bug, but bug either of VNC server either of VNC client.
