### ISSUE TITLE
Ctrl-вниз в пользовательском меню полностью его очищает

### ISSUE THREAD

**Issue by KarelWintersky** [elfmz/far2l#1013]
И вообще, любые кнопки в меню кроме insert/delete приводят к непредсказуемым последствиям: элементы исчезают, меняются местами...

**Comment by KarelWintersky** [comment]
собственно, ctrl+вниз - которое в классическом FAR перемещает вниз пункт меню - нахрен удалило ВСЕ пункты меню. 

И никаких бэкапов разумеется FAR2L не делает :(((
пиздец.

**Comment by KarelWintersky** [comment]
@elfmz , wontfix ?

**Comment by elfmz** [comment]
it was closed by commit that fixes it

**Comment by KarelWintersky** [comment]
thanx
