### ISSUE TITLE
Usermenu - again

### ISSUE THREAD

**Issue by KarelWintersky** [elfmz/far2l#1016]
Вставка разделителя с помощью hotkey  `--` и  label `--` ломает к чертовой матери меню:

![изображение](https://user-images.githubusercontent.com/2164874/123442423-89b8a400-d5dd-11eb-89e7-ef976ec3d8bd.png)

И, разумеется, Ctrl-F4 совершенно ничего не делает. 

Если вставить пункт меню, например, с hotkey 1 label 1 - получается так:

![изображение](https://user-images.githubusercontent.com/2164874/123442599-b79de880-d5dd-11eb-8520-1bb202f59513.png)

То есть как бы разделитель исчезает - с концами.

`FAR2L, version 2.3.210622-f2a9b696-alpha (build 21/06/22-f2a9b696-alpha)`

user_menu.ini
```
[UserMenu/MainMenu/Item0]
Command0=1
HotKey=1
Label=1
Submenu=0

[UserMenu/MainMenu/Item0/Item0]
Command0=cd /var/www/foobar
HotKey=A
Label=47news v1 admin
Submenu=0

[UserMenu/MainMenu/Item0/Item1]
HotKey=--
Label=
Submenu=0

[UserMenu/MainMenu/Item2]
Command0=pulseaudio -k && sudo alsa force-reload && sleep 2 && pulseaudio -k && sudo alsa force-reload
HotKey=S
Label=Sound restart
Submenu=0


```

**Comment by KarelWintersky** [comment]
То есть выглядит так, как будто тут двухуровневое меню - но в подменю не попасть.

**Comment by elfmz** [comment]
> И, разумеется, Ctrl-F4 совершенно ничего не делает.
Судя по тому что он на скриншоте не упоминается в строке хелпа, а упоминается старый Alt+F4 - у вас старая версия без последнего коммита. Потому и Ctrl-F4  ничего не делает

**Comment by KarelWintersky** [comment]
Странно, мне казалось что я пересобирал FAR.

Ок. Пересобрал, запустил, нажал Ctrl-F4 и вижу, смотрите, новый (far3) формат сохранения меню:

![изображение](https://user-images.githubusercontent.com/2164874/123490556-fe5f0300-d61c-11eb-9849-b958f3e5924b.png)

И интерпретация ИЗ него работает. Может быть не хранить меню в старом "регфайловом" формате тогда?

**Comment by elfmz** [comment]
Да я тоже удивился, когда Ctrl+F4 нажал. А я все думал - что там за странный код преобразования из реестра / в реестр. Подумал - что-то не доделанное.

**Comment by KarelWintersky** [comment]
Лично на мой взгляд вот этот формат как на скрине тоже контринтуитивен. Возможно, в JSON было бы прозрачнее.

Что-то типа
```
[
{
    { type: item, title: "Sound restart", command: "...." },
    { type: submenu, title: "Goto", content: {
    ..... 
    }}
]
```

**Comment by KarelWintersky** [comment]
А почему за основу была взята версия 2.0 ?

**Comment by elfmz** [comment]
Потому что изначально мне хотелось максимально быстро сделать фар которым я смог бы пользоваться, так как сам переехал с винды под никсы и требовался инструмент. Я вначале честно пытался воспользоваться тем что было, но миднайт традиционно по юниксовски слишком суров, а wal/wcm командеры были глючными и весьма слабыми в плане функционала. Потому решил попробовать портировать фар. Вначале взял третий фар, и стал сделал враппер консольных АПИ, работающих под виндой - то есть чтото типа conemu но с прицелом под кроссплатформенность - получился фар который запускался под виндой, но не в консоли, а в wx-овском окошке. Потом добавил базовые виндовые апи - это все еще был фар3 и его собственный код практически не менялся на тот момент. Это все заняло гдето месяц вечерне-выходного кодописательства. Потом запустил это дело под линухом и обнаружил что самый большой геморрой еще только впереди - изменение кода самого фара для поддержки концептуальных различий в работе ФС и прочего. У фара 2 кода было меньше. Замечу что попытки абстрагироваться от ОСевого апи присутствовали и у фара2 и у фара3, в фаре3 их было больше, но абстрации те довольно странные - то есть вместо того чтоб абстрагировать семантику, они абстрагируют тупо синтакс. Нынче я за кодом фар3 слежу слабо, но вот ща пробежался и вижу ту же самую проблему - вот типа такого вот - https://github.com/FarGroup/FarManager/blob/master/far/qview.cpp#L395 - ведь этот os::reg::key::open с точки зрения портирования совершенно не отличаются от RegOpenKey. А кода, в плане тупого количества сттрок, повторюсь в фаре 2 было меньше. Потому я быстренько перескочил на фар2, подкостылил самые критические места до состояния 'опа, запустилось в убунте' и пришел на форум фара. Там форку оказались совершенно не рады, а самому переключаться назад на базу фар3 не были ни желания ни фактически возможности. Так что я просто стал постепенно допиливать то что уже работало - меня оно вполне устраивало. Не спорю что третий фар сильно круче по возможностям кастомизации скриптингом но, во-первых, как можно догадаться, я никогда особо не увлекался кастомизацией фара, во вторых, даже если откинуть свои нужды, - сама возможность кастомизации в линуксах не есть чтото что может сразить юзеров наповал. Тут и так все что можно кастомизируется, и наблюдается нехватка инструментов которые бы просто работали, без необходимости допиливания напильником и кувалдой. Потому лично мое мнение что отсутствие скриптинга не сильно большая проблема для большинства юзеров, хотя признаю что не для всех :)

**Comment by elfmz** [comment]
вроде подфиксил, проверяйте свою проблему

**Comment by KarelWintersky** [comment]
https://forum.farmanager.com/viewtopic.php?f=4&t=12466

Под far3w имеет место быть вот такая проблема. На far2l она тоже воспроизводится (хотя и в меньшей степени). 

Собственно, благодаря far2l я её и заметил. Сначала грешил на 2-ю версию, проверил в 3-ей... и нет... 

В общем, код копирования файлов настолько легаси, что чинить его никто не хочет.

**Comment by KarelWintersky** [comment]
@elfmz , аллилуйя. Работает. Но вы же понимаете что я еще что-нибудь найду? :)

**Comment by elfmz** [comment]
ну если чо мона и снова/пере открыть баг

**Comment by elfmz** [comment]
Кстати насчет копирования, а попробуйте зайдя в папку откуда копировать собирались, ввести "file:" - это приведет к открытию этой папки в плагине NetRocks и последующее F5 будет обрабатывать его копировщик. Скажите, воспроизводится ли проблема скорости копирования с его копировщиком.

**Comment by KarelWintersky** [comment]
@elfmz , нет, с NetRocks не воспроизводится. У его копировщика скорость более чем приемлемая. 

Но, детская болезнь времен far2w: 

https://forum.farmanager.com/viewtopic.php?f=4&t=12507

Такое впечатление, что основные тормоза при копировании - это крайне неоптимальная функция чтения оглавления каталога. Просто на локальных дисках мы этого не замечаем.

**Comment by elfmz** [comment]
попробуйте ветку optimize-file-io

**Comment by elfmz** [comment]
.. тока что дополнил эту ветку асинхронным заполнением auto-completion списка, должно решить проблему с медленным автодополнением

**Comment by elfmz** [comment]
ну крч оно уже в мастере

**Comment by KarelWintersky** [comment]
> попробуйте ветку optimize-file-io

не успел ;)

Хорошо что в мастере

**Comment by KarelWintersky** [comment]
> тока что дополнил эту ветку асинхронным заполнением auto-completion списка, должно решить проблему с медленным автодополнением

Решило. Работает мгновенно.

**Comment by elfmz** [comment]
а че со скоростью копирования 100500 файлов?

**Comment by KarelWintersky** [comment]
> а че со скоростью копирования 100500 файлов?

Стабильно невысокая. 
5000 файлов по 256 кб копируются на CIFS со скоростью (прогнозируемой)  3.1 Мб/с , примерно по 7-8 файлов в секунду (визуально).

FAR2L прогнозирует закончить за 6 минут.

Midnight Commander  прогнозировал 35 секунд и справился за минуту. После 4000 файлов скорость незначительно упала.

**Comment by KarelWintersky** [comment]
Кстати, он и удаляет с CIFS файлы неторопливо. 

Если через `file://` 

![изображение](https://user-images.githubusercontent.com/2164874/124491246-b6c63d00-ddbb-11eb-8c07-cca86f26c836.png)

**Comment by elfmz** [comment]
ох ну таки придется делать 5000 файлов..

**Comment by elfmz** [comment]
интересно кстати что у меня скорость сейчас копирования одного, но ~по 5 рублей~ большого файла в far2l раза в 2 быстрее чем mc

**Comment by elfmz** [comment]
Сделал 5000 мелких файлов в локальной директории, копировал на подмонтированную SMB шару, _без_ file, первое копирование провел миднайтом - 4:30, второе - фар2л - 4:15.
Клиент (где был мс и фар2л) убунта, сервер с самбой - старенький NAS. Потом попробую с виндовым компом, может на нем че проявится. Но пока фар2л явно не хуже). Удаление не засекал, но на глаз заняло примерно одинаковое время, и явно меньше двух минут.

**Comment by elfmz** [comment]
Через file: у меня кстати сейчас чуть медленне получается чем родным копировщиком фара - за 5 минут.

**Comment by elfmz** [comment]
Что за система? Мож вы с какими хитрыми опциями самбу монтируете?

**Comment by KarelWintersky** [comment]
```
for (( a = 1; a <5001 ; a++ )) do dd if=/dev/urandom of=$a.medium bs=256K count=1; done
for (( a = 1; a <5001 ; a++ )) do dd if=/dev/urandom of=$a.large bs=2M count=1; done
for (( a = 1; a <5001 ; a++ )) do touch $a.zero; done
```
Тестовые наборы я делал так.

**Comment by KarelWintersky** [comment]
> Что за система? Мож вы с какими хитрыми опциями самбу монтируете?

Клиент - Linux Mint 19.3 Cinnamon, ядро 5.4.0-74-generic
Сервер - Ubuntu 20.x 

Монтирую в fstab: 
```
//192.168.111.1/media           /mnt/BLACK_MEDIA        cifs    username=user,password=password,iocharset=utf8,file_mode=0777,dir_mode=0777,noserverino,uid=arris,gid=arris,noperm    	0       0
```

Настройки самбы не дефолтные, так что сейчас попробую сбросить все в дефолт.

**Comment by KarelWintersky** [comment]
Я закомментировал  в конфиге самбы: 
```
# read raw = yes
# write raw = yes
# use sendfile = true

# socket options = TCP_NODELAY IPTOS_LOWDELAY SO_RCVBUF=131072 SO_SNDBUF=131072

# min receivefile size = 16384
# aio read size = 16384
# aio write size = 16384
# write cache size = 524288
# getwd cache = yes
```
И стало только хуже.

**Comment by KarelWintersky** [comment]
Странное дело: 

Во-первых, копирование большого файла (8 гб) сейчас (вероятно через `file://` имплементацию, показывает нереально высокие скорости - 380 Мб/с

Во-вторых, прерывание копирования (не обязательно для этого файла, а вообще) требует повышения полномочий:

![изображение](https://user-images.githubusercontent.com/2164874/124605233-5cd57e00-de74-11eb-9ad9-14abae9ffd90.png)

**Comment by KarelWintersky** [comment]
кажется, самбу надо выкинуть на помойку и шарить папки по NFS %)

**Comment by KarelWintersky** [comment]
Смонтировал папку по NFS в режиме async.

FAR2L выдает просто заоблачную скорость копирования. За 30 секунд эти 5000 файлов по 256 кб - со свистом. 

В режиме `file://` примерно те же 30 секунд.

Странное поведение с копированием 8 гб файлов в обычном режиме сохраняется. После отмены копирования оно еще немало времени думает (вероятно реально пересылая данные на сервер, пока они не дойдут до условного залитого объема) 

Судя по всему, оно сначала читает максимум возможного в память (а оперативки у меня 32 гектара) и только потом пишет на диск. Но пишет с со скоростью гигабитной локалки. 

Just as planned, короче.

**Comment by elfmz** [comment]
Ну NFS это такая себе замена самбы. Там даже авторизации нету нормальной.
С полномасштабным виндовым компом в качестве самба сервера я пока не экспериментировал - занят другими делами.

**Comment by KarelWintersky** [comment]
Ну, у меня самба-сервер на линуксе (ubuntu 20). 

Я с него монтирую сетевые диски - либо CIFS (Самба), либо вот NFS. 

И если под линуксом с NFS все в порядке, то под виндой... короче, винда не умеет в UTF-8

**Comment by elfmz** [comment]
В целом с виндовым компом у меня тоже не воспроизводится, но удалось довести скорость удаления файлов 1-к-1 как у миднайта и еще кое что подкрутил в целом, может улучшит скорость на каких нить других конфигурациях. Это все пока в ветке optimize-file-io2

**Comment by KarelWintersky** [comment]
> Ну NFS это такая себе замена самбы. Там даже авторизации нету нормальной.

Ну... да, но... скажем так, настроенные файрволлы и прочее упрощают жизнь, но это не панацея. 

К тому же NFS под виндой (любой!) не понимает UTF-8, превращая имена в крокозябры. 

Завтра попробую ветку :) Спасибо!!!
