### ISSUE TITLE
Add handy multiuser profiles support

### ISSUE THREAD

**Issue by ariel777** [elfmz/far2l#1017]
Far (since v. ~1.6) has support -u <user>. It would be really helpful to support them here as well.
E.g., use case: 
Create few shortcuts with different user profiles for different domain, e.g.:
* -u home
* -u work
* -u projectA
* -u projectB
* -u hobby

Each of them could have a different colour schema, set of directory shortcuts, etc.

P.S.: thank you very much for this wonderful project and support for Mac OS! God bless you!

**Comment by elfmz** [comment]
implemented - check recent package under https://github.com/elfmz/far2l/releases/tag/v2021-06-30_alpha

**Comment by ariel777** [comment]
Thank you very much for so fast reaction.

I executed:
`/Applications/far2l.app/Contents/MacOS/far2l -u ll` and it showed me default (different layout) empty folder bookmarks.
It looks like working. A folder was created: `/Users/alex/.cache/far2l/custom/ll/`. I assigned a bookmark for a folder and it works. So it looked good so far.

When I tried to start far via the app - it crashed (possibly) on the shortcut for the bookmark.

Same when I start from iTerm:
`/Applications/far2l.app/Contents/MacOS/far2l -u l`
or
`/Applications/far2l.app/Contents/MacOS/far2l` 

E.g.:
`
System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGQUIT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Quit: 3
Termination Reason:    Namespace SIGNAL, Code 0x3
Terminating Process:   iTerm2 [9055]

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff684fddfa mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff684fe170 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff2e24a407 __CFRunLoopServiceMachPort + 247
3   com.apple.CoreFoundation      	0x00007fff2e248ec1 __CFRunLoopRun + 1329
4   com.apple.CoreFoundation      	0x00007fff2e248333 CFRunLoopRunSpecific + 466
`

I noticed that the far process survived. I could not restart far until I killed the process.

After that, it works fine (on start from far2l.app, and for starts from the command line). So no issues now. 

Unfortunately, I don't know how to create another application link (xyz.app) to start with a different profile - it would be nice instead of / in addition to the command line...

Thank you again for this update!

**Comment by elfmz** [comment]
Dont know if it will help with your problem (as i not an experienced Mac user), but beside of using -u argument this setting can be specified by environment variable FARSETTINGS, so
```
export FARSETTINGS=foo
far2l
```
..is equivalent for:
```
far2l -u FARSETTINGS
```
