### ISSUE TITLE
fedora 34

### ISSUE THREAD

**Issue by asmexcaliburwoods** [elfmz/far2l#1019]
крч на федоре хз как билдать с сырцов, некогда

```
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindwxWidgets.cmake:1025 (find_package_handle_standard_args)
  CMakeLists.txt:114 (find_package)
```

скоро перееду с федоры на убунту 18.04.х...

**Comment by elfmz** [comment]
очевидно не поставлены зависимости, как минимум wxWidgets, вроде оно ставится там так - yum install wxGTK-devel

**Comment by JaroslavBes** [comment]
Зависимости для fedora 33:
sudo dnf install xerces-c-devel libarchive-devel neon-devel libnfs-devel libsmbclient-devel openssl-devel libssh-devel uchardet-devel spdlog-devel pcre2-devel wxGTK3-devel cmake

**Comment by cmdorexe** [comment]
#1121 #647 #84

**Comment by tieugene** [comment]
https://copr.fedorainfracloud.org/coprs/polter/far2l/
Берем оттуда спек, подкручиваем немного (версия, название сырцов) - и
```bash
rpmbuild -ba far2l.spec
```
F35, 2.4.0 - собралось молча, без ошибок.
И без wx пока (толстое сильно, жаба давит ставить)

**Comment by unxed** [comment]
Проблема всё ещё актуальна?

**Comment by unxed** [comment]
> Зависимости для fedora 33:
> sudo dnf install xerces-c-devel libarchive-devel neon-devel libnfs-devel libsmbclient-devel openssl-devel libssh-devel uchardet-devel spdlog-devel pcre2-devel wxGTK3-devel cmake

Уже можно и без spdlog-devel.

**Comment by unxed** [comment]
btw, проблема всё ещё актуальна?

**Comment by tieugene** [comment]
> btw, проблема всё ещё актуальна?

Для Fedora 33 - нет. Потому что это уже седая древность.
Ну а раз @asmexcaliburwoods закрыл, то это уже к нему вопрос
