### ISSUE TITLE
Problems of launching console programs in an embedded terminal with Unicode characters (for example, cyrillic characters)

### ISSUE THREAD

**Issue by proffix4** [elfmz/far2l#1040]
When launching console programs (written in C) in the built-in terminal with the input of Unicode characters (for example, Cyrillic characters), deletion by the Backspace key does not work correctly. Entering the Cyrillic character (2 bytes) and pressing the the Backspace key on the screen, the character is cleared, but its second byte is not from the buffer and an incorrect input into the program is obtained. External terminals are able to correctly delete characters in Unicode. Please correct

**Comment by elfmz** [comment]
~Please descri~ пожалуйста опишите проблему подробнее. Я для проверки запустил в far2l nano, печатаю и удаляю по-русски - все происходит адекватно.
Воспроизводится ли у вас проблема в nano? И если нет - то в какой именно программе она воспроизводится? И под какой  именно ОС.

**Comment by proffix4** [comment]
с nano проблем нет. Проблема с программами на языке Си, когда в программе ввод с консоли. Проблема в ubuntu 18, Linux Mint 20.2. Как выглядит проблема подробней, описываю.
Вот программа:
```
#include <stdio.h>
#include <iostream>

using namespace std;

int main(int argc, char** argv) {
    int number1;
    float number2;

    /* Стиль С из  <stdio.h> */
    printf("Введите целое и вещественное число через пробел: ");
    scanf("%d %f", &number1, &number2);
    printf("number1 = %d, number2 = %f \n", number1, number2);
    puts("Спасибо!");
        
    /* Стиль С++ из  <iostream> */
    cout << "Введите еще число: ";
    cin >> number2;
    cout << "Вы ввели число " << number2 << endl;

    /* Создание задержки на экране. Стиль С++ из  <iostream> */
    cout << "\nНажмите Enter для завершения программы...\n";
    // Очистим ввод с клавиатуры и будем ожидать нажатие клавиши "Enter" 
    cin.ignore(); cin.get();

    return 0;
}
```

Если я введу цифру 1, пробел,  цифру 2 и букву "ю", а потом удалю эту букву "ю" и введу ".5", то будет на экране вот что:

```
Введите целое и вещественное число через пробел: 1 2.5
number1 = 1, number2 = 2.000000
Спасибо!
Введите еще число: Вы ввели число 0

Нажмите Enter для завершения программы...

```
а должно быть так, если бы не было лишней стертой буквы с 2 байтами кодировки:
```
Введите целое и вещественное число через пробел: 1 2.5
number1 = 1, number2 = 2.500000
Спасибо!
Введите еще число: 3
Вы ввели число 3

Нажмите Enter для завершения программы...
```

проблема в неправильном стирании символа с внутреннего буфера встроенного терминала: удаляется 1 байт, а символ был 2 байта, этот невидимый хвост потом идет в виде ввода. 
Эта проблема не позволяет также вводить текстовые данные на кириллице, если есть стирание символов, получается абра-кадабра. С латинскими буквами такого нет, поэтому мало кто это замечал.

Вот видео с проблемой: [https://drive.google.com/file/d/1RCaWSaSwI38sRrlHTZ1e26BMQCYbMosd/view?usp=sharing](url)

**Comment by proffix4** [comment]
программа собрана из исходников, на wxWidgets-3.1.5

**Comment by proffix4** [comment]
Спасибо большое, очень выручили ! Ваша программа - это самая главная программа для меня в любом linux, как far был в windows. Ещё раз спасибо !
