### ISSUE TITLE
File diff plugin

### ISSUE THREAD

**Issue by AlibekJ** [elfmz/far2l#1042]
A plugin for comparing files for Far Manager.

I am missing a plugin which would compare files in far. 
Basically, a wrapper for ```diff``` with some additional features.

Would love to see it working exactly like in Midnight Commander:
Select two files, press C-x C-d  or F9-c-o. Viewer visualizes the differences and allows merging changes between the files.
Screenshot: 
![Screenshot from 2021-07-26 15-56-51](https://user-images.githubusercontent.com/8142809/127050921-c09d26e1-0e95-497d-ac0b-69fc1a3608df.png)

**Comment by bigvax** [comment]
Я пользуюсь в Far Manager плагином VisualCompare.
Пока его не портировали в far2l, я сделал себе вот такой «костыль»:
Меню пользователя:
---
I use the VisualCompare plugin in Far Manager.
Until it was ported to far2l, I made myself menu like this:
User menu: 
```
a:  mcdiff !^!.! !#!.!
    mcdiff !^!/!.! !#!/!.!
v:  vimdiff !^!.! !#!.!
    vimdiff !^!/!.! !#!/!.!
m:  meld !^!.! !#!.!
    meld !^!/!.! !#!/!.!
k:  kdiff3 !^!.! !#!.!
    kdiff3 !^!/!.! !#!/!.!
s:  sdiff !^!.! !#!.!
    far2l /e - sdiff -iZbBWt !^!/!.! !#!/!.!
d:  diff !^!.! !#!.!
    far2l /e - diff -auiwBE !^!/!.! !#!/!.!

```
Ваш вариант первый - a:
Your first option - a:

**Comment by AlibekJ** [comment]
Hey @bigvax, thanks for the suggestion but I failed to find how can edit the User Menu.
Can you elaborate, please? Where exactly do I make the changes suggested?
Всё вроде облазил, но не смог найти как ввести предложенное вами. Пожалуйста, расскажите подробнее.

**Comment by bigvax** [comment]
F9 -> Команды -> Меню пользователя -> Главное -> Ctrl+F4
F9 -> Commands -> Edit user menu -> Main -> Ctrl+F4

вот как-то так

**Comment by ivanshatsky** [comment]
My menu to compare selected file with the selected file on a passive panel and with the same-named file on a passive panel:

```
:  Compare !.! with !#!/!.!
    mcdiff !.! !#!/!.!
:  Compare !.! with the same file
    mcdiff !.! !#!/!^!.!
```
