### ISSUE TITLE
NetRocks не работает на MacOS

### ISSUE THREAD

**Issue by molbo-mombecky** [elfmz/far2l#1052]
NetRocks не работает на MacOS Big Sur, что я не так делаю? 
Пробую sftp или scp и получаю "Operation failed  wrong protocol:" :(

**Comment by elfmz** [comment]
Как именно пробуете?
Как собран far2l - самосборный или dmg package отсюда? В первом случае - была ли установлена libssh?

**Comment by molbo-mombecky** [comment]
dmg отсюда: https://github.com/elfmz/far2l/releases/tag/v2021-06-30_alpha 
До этого сам собирал несколько раз, была таже проблема, но я это списал на мою криворукость.

**Comment by elfmz** [comment]
Любопытно, В комбобексе Create site connection/Protocol sftp присутствует?
Если да, то можете описать по шагам что вы делаете, или в идеале видео снять?

**Comment by molbo-mombecky** [comment]
В комбобоксе все протоколы присутствуют.
Как многолетний пользователь Far–a, делаю все как всегда. :) 
Я сейчас попробовал на другом Маке этот  dmg и на нем Netrocks, по крайней мере, позволяет мне создать site,  правда потом не соединяется, а просто "заходит внутрь".
Похоже я своими предыдущими экспериментами где-то что-то сломал у себя :( 
Знать бы где почистить :)

**Comment by elfmz** [comment]
хм забавно, пожалуй стоит добавить проверку на наличие прав  записи ~/.config

**Comment by elfmz** [comment]
еще кстати кое-что менее важное лежит в ~/.cache/far2l

**Comment by molbo-mombecky** [comment]
О, это как то, что мне было нужно, все ошибки там видны :) 
из `upgrade.sh.log`
`cp: /Users/user/.config/far2l/plugins: Permission denied`
Знать бы куда смотреть :)

**Comment by elfmz** [comment]
а как включать дебаг логи я тут вот написал - https://github.com/elfmz/far2l/wiki/Running-far2l-with-debug-logging-enabled

**Comment by elfmz** [comment]
ну раз все хорошо то закрываю..
