### ISSUE TITLE
make default choise in drive panel configurable

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#106]
Currently "/run/user/USERID" is selected by default.

It would be great to make this choise configurable. for example, to select "~" or "/" to be default choise if needed.

**Comment by unxed** [comment]
More advanced option is to make the whole list editable (using placeholders for variable values like USERID, for example).

**Comment by lieff** [comment]
А еще выбора там довольно много и каждый раз навигироваться по нему не очень удобно.
Может чтоит сделать хоткеи 1, 2, 3... по аналогии с C, D, E... в винде. Так уже запоминаешь какой хоткей куда жать и открываешь нужный мгновенно.

**Comment by elfmz** [comment]
Там сейчас тупо слегка пропаршенный вывод того что выдает df -T
С самого начала вместо df -T думал сделать промежуточный скрипт, который бы вызывал df -T ну и еще чего добавлял. И хоткеи расставлял. Но все руки не доходят

**Comment by unxed** [comment]
Вывод mount тоже может предложить много интересных вариантов.

**Comment by unxed** [comment]
Кстати, к вопросу о монтировании sftp через gvfs - вывод mount его покажет.

**Comment by unxed** [comment]
great work, thanks!
