### ISSUE TITLE
Cannot add/replace files in archives

### ISSUE THREAD

**Issue by polter-rnd** [elfmz/far2l#1068]
How to reproduce (on master, I am using [my rpm package](https://github.com/polter-rnd/far2l-rpm) for Fedora 34):

- Open zip/jar archive in far2l
- Add a file using Shift+F4, or edit existing one
- Save it (F2)
- See error message, file not added/replaced

![far2l_archive_edit](https://user-images.githubusercontent.com/6562863/131363231-4ffb7850-ad34-48d1-9d51-c08d91fceb51.png)

**Comment by elfmz** [comment]
Check now please.

**Comment by polter-rnd** [comment]
Thanks, it's working now! Updated my Fedora repo.
