### ISSUE TITLE
used disk space reported by far2l and reported by ncdu differs

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1071]
![Снимок экрана в 2021-09-07 13-16-09](https://user-images.githubusercontent.com/1151423/132328251-54d3faec-5d4d-402e-88c7-79c7db3d59bb.png)
![Снимок экрана в 2021-09-07 13-15-54](https://user-images.githubusercontent.com/1151423/132328254-38a03b5d-98c5-4011-8bc3-9248945d51e7.png)

**Comment by unxed** [comment]
~9 Gb used as reported by far2l, and ~4,7 Gb as reported by ncdu

**Comment by elfmz** [comment]
Far2l used space in CtrlQ window corresponds to filesystem statistics that can differ than just sum size of files due to FS structures, files clusterizations etc.
Better compare with output of df

**Comment by unxed** [comment]
df looks closer, ok
```
/# df                                                                                                                      ↑
Filesystem          1K-blocks    Used Available Use% Mounted on
udev                   996900       0    996900   0% /dev
tmpfs                  205020     772    204248   1% /run
/dev/sda1            57561340 4971304  49642964  10% /
tmpfs                 1025084       0   1025084   0% /dev/shm
tmpfs                    5120       0      5120   0% /run/lock
tmpfs                 1025084       0   1025084   0% /sys/fs/cgroup
tmpfs                 1025084       4   1025080   1% /tmp
tmpfs                 1025084       0   1025084   0% /var/tmp
tmpfs                  205016       0    205016   0% /run/user/0
```
