### ISSUE TITLE
NetRocks craches after last 2 commits

### ISSUE THREAD

**Issue by bouncyball-git** [elfmz/far2l#1087]
Crashes when accessing SFTP or SMB resource. FTP not affected.

🔥🔥🔥 21/09/28-658b7ae5-alpha
Signal 0B [0000000000000000] on 0000000061536949
0000000000000004 0000000000000005 00007F7870E3EF01 0000000000000000
0000000000000000 00007F7870E3EEB0 00007F7870E3EE28 00007F7870E3EEF0
00007F7870E3EE20 00007F7870E3EE88 00007F7870E3EE78 00007F785C0BF0B0
00007F7870E3EE48 456771F34C73DD00 0000000000000003 00007F7870E3EC78
00007F786030408F 0000000000010246 002B000000000033 0000000000000000
000000000000000D 0000000000000000 0000000000000000 00007F7870E3E880
000000000000000C 0000000000000020 0000000100000000 0000000000000000
00005556B6A16408 0000000000000000 000000000000000/ 0000000000000000
/usr/bin/far2l(+0x1a44e7)[0x5556b69b04e7]
/usr/lib/libpthread.so.0(+0x13870)[0x7f7877b6b870]
/usr/lib/far2l/Plugins/NetRocks/plug/NetRocks.far-plug-wide(+0x2808f)[0x7f786030408f]
[0x7f7870e3ef90]

far2l closes immediately.

Manjaro Linux
libpthread v2.33

**Comment by elfmz** [comment]
not repro for me, but:
1 make sure you made clean build (make clean && make -j ..) but not just make after pulling new changes 
2 if still after 1 it crashing - please provide NetRocks.far-plug-wide and far2l unstripped (with symbols) binaries

**Comment by bouncyball-git** [comment]
Thanks for reply. I used to build and install it from AUR. It's been so far so good until recent update.

I uninstalled package, cloned clean repo from git, built it manually and it crashed again.
The strange (and sad) thing is, when I compile it with Debug symbols it works?! (no crashes). Only Release build crashes.
Tried several times on my notebook and pc with Manjaro installed - same thing.

You can find all files [here](http://bouncyball.myweb.ge/git/)

**Comment by elfmz** [comment]
that binaries are newer than crashed in your log in 1st message, so now please provide crash log report from exactly same binaries

**Comment by elfmz** [comment]
check now please

**Comment by bouncyball-git** [comment]
Hey, sorry for delay.

It works NOW! :) Thank you!
