### ISSUE TITLE
Ubuntu make fails

### ISSUE THREAD

**Issue by johnrembo** [elfmz/far2l#1088]
Linux rembo-desktop 5.4.0-86-generic #97-Ubuntu SMP Fri Sep 17 19:19:40 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

[ 97%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/Protocol/Protocol.cpp.o
[ 97%] Linking CXX shared module ../install/Plugins/NetRocks/plug/NetRocks.far-plug-wide
[ 97%] Built target NetRocks
make: *** [Makefile:152: all] Ошибка 2

**Comment by elfmz** [comment]
Please provide full build log

**Comment by johnrembo** [comment]
Turns out that adding  -DPTYHON=yes to previous cmake caused the problem. Turning python off solved.
