### ISSUE TITLE
Editor menu is lost

### ISSUE THREAD

**Issue by kilttartan** [elfmz/far2l#1089]
There is no editor menu at the bottom of the screen after one of the previous updates

**Comment by elfmz** [comment]
Check /.config/far2l/settings/config.ini - what is under [Editor] / ShowKeyBar ?

**Comment by kilttartan** [comment]
It was zero. I've changed it to 1 and I got back my menu! Thank you!!

**Comment by elfmz** [comment]
Likely you suddenly have pressed Ctrl+B inside editor - this toggles that option. Bad that there is no visible UI settings for it, apparently need to add...

**Comment by kilttartan** [comment]
I am quite sure that! Surprisingly, but I never pressed it in previous years of using FAR manager. Actually, there is another issue about the editor menu. F7 "Search" button works great. But Ctrl-F7 "Search and Replace" is not. I use combination of Ctrl and mouse click. May be there is a way to fix it?
