### ISSUE TITLE
multiarc: tidy up obsolete archivers support

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1091]
Probably there is no such thing as ace32 on linux, there is only unace. Not sure if we need such exotic formats support at all; at least it can be implemented as custom format for those who need it.

As for arc, there is even no linux extractor! ha, lhz — all of them are actually dead, do we need to complicate interface by their support stuff, or it's better to free space for something that is indeed useful, like tar.xz, deb or rpm?

**Comment by elfmz** [comment]
but it doesnt require any efforts for support

**Comment by unxed** [comment]
Far2l was never actually able to even extract .ace or any of those listed formats on linux, can we call this "support"? Just finding a sample to test such extraction is pain :)

**Comment by elfmz** [comment]
`apt-cache search archive |grep -i ace
....
unace - extract, test and view .ace archives
unace-nonfree - extract, test and view .ace archives (non-free version)
`
.. though have to correct default command lines for ace format

**Comment by elfmz** [comment]
Also: lhasa - lzh archive decompressor

**Comment by unxed** [comment]
Let's at least remove creation/modification command lines that never worked and probably will never be — not to confuse users

As for extraction, ok, it still may be useful for someone

**Comment by unxed** [comment]
`unar` can be used for extraction of `.arc` archives:
https://packages.debian.org/ru/sid/unar

As for `.ha`, it seems to be removed from Ubuntu repos. Maybe it's sources can be incorporated in multiarc as done for 7z & unrar?
http://fileformats.archiveteam.org/wiki/HA#Software

**Comment by unxed** [comment]
Also, shouldn't lines like
`    /*Extract               */"lha x -a -c -d -m {-w%%W} %%a @%%lM",`
be switched to lhasa then?

**Comment by elfmz** [comment]
lhasa sets lha symlink that points to lhasa

**Comment by unxed** [comment]
> lhasa sets lha symlink that points to lhasa

The problem is user probably will not see "Command 'lha' not found, but can be installed with sudo apt install lhasa"-like suggestions on lha call if lhasa is not installed

**Comment by unxed** [comment]
probably proper .arc unpacker:
https://packages.debian.org/ru/bullseye/nomarch

**Comment by unxed** [comment]
there are some reports though that FreeARC supports some archives that nomarch does not: https://askubuntu.com/a/550539/894968

maybe the better way is to incorporate FreeARC for unpacking ARCs also

**Comment by unxed** [comment]
threre is also just arc-for-linux!
https://packages.debian.org/ru/bullseye/arc

but it's certainly not arc32 :)

**Comment by elfmz** [comment]
already changed to unar...

**Comment by elfmz** [comment]
..and to arc

**Comment by unxed** [comment]
Thanks! This issue can be considered «resolved» now. Will open a new one if come across something else in the multiarc that needs updating.

**Comment by unxed** [comment]
Btw, do we actually need arc in "add to archive" packers list? Guess 100% of its selections would be selection by a mistake. It even can not hold folder structure
