### ISSUE TITLE
far2l refuses to list files in arj archive

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1094]
sample attached
```
$ arj x ./test.arj
ARJ32 v 3.10, Copyright (c) 1998-2004, ARJ Software Russia.

Processing archive: ./test.arj
Archive created: 2021-10-04 09:43:42, modified: 2021-10-04 09:43:42
Extracting test.txt                    OK
     1 file(s)

$ ls
test.arj  test.txt
```
[test.tar.gz](https://github.com/elfmz/far2l/files/7275947/test.tar.gz)

**Comment by unxed** [comment]
![Screenshot from 2021-10-04 10-01-16](https://user-images.githubusercontent.com/1151423/135807274-01f3d0fd-4534-4401-8c85-92b75e8a39c0.png)

**Comment by elfmz** [comment]
its because test.txt has hidden attribute and you have hidden files not listed

**Comment by unxed** [comment]
Just created text file by far2l and added it to archive by command line arj. Wonder where the hidden attribute came from
