### ISSUE TITLE
Кодировка у плагинов

### ISSUE THREAD

**Issue by chodorenko** [elfmz/far2l#11]
Походу плагины считают что должно быть cp866 
http://screencloud.net/v/kNTv

**Comment by elfmz** [comment]
Забавно. Перевел русские lng/hlf плагинов в UTF8. Должно полегчать...

**Comment by elfmz** [comment]
молчание знак - 'пофикшено'

**Comment by chodorenko** [comment]
Сори что не ответил, не добрался, да , полегчало.
Правда плагин не работает , но ресурсы показывает нормально
