### ISSUE TITLE
Отсутствует cmake_minimum_required 

### ISSUE THREAD

**Issue by chodorenko** [elfmz/far2l#110]
в файлике far2l.git/trunk/far2l/CMakeLists.txt отсутствует cmake_minimum_required
при инициализации cmake  возникает ошибка

**Comment by chodorenko** [comment]
или вариант 2 в ридми не пралвьо указана команда  cmake -DCMAKE_BUILD_TYPE=Release ../far2l
где  ../far2l указывает не туда

**Comment by elfmz** [comment]
команда указана правильно, просто рассчитана на исполнение из директории, 'соседней' с деревом far2l

**Comment by chodorenko** [comment]
~/9> svn co https://github.com/elfmz/far2l.git
   A    far2l.git/trunk/utils/src/utils.cpp
   Checked out revision 508.
~/9> cd far2l.git/trunk/
~/9/far2l.git/trunk>  mkdir build
~/9/far2l.git/trunk> cd build
:~/9/far2l.git/trunk/build> cmake -DCMAKE_BUILD_TYPE=Release ../far2l


http://screencloud.net/v/k3Qi
так как же теперь билдить ?

**Comment by elfmz** [comment]
```
user@anonymous:~/foo$ git clone https://github.com/elfmz/far2l.git
Cloning into 'far2l'...
remote: Counting objects: 6695, done.
remote: Compressing objects: 100% (781/781), done.
remote: Total 6695 (delta 217), reused 0 (delta 0), pack-reused 5900
Receiving objects: 100% (6695/6695), 44.61 MiB | 1.70 MiB/s, done.
Resolving deltas: 100% (3820/3820), done.
Checking connectivity... done.
user@anonymous:~/foo$ ls
far2l
user@anonymous:~/foo$ mkdir build
user@anonymous:~/foo$ ls
build  far2l
user@anonymous:~/foo$ cd build
user@anonymous:~/foo/build$ cmake -DCMAKE_BUILD_TYPE=Release ../far2l
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'glib-2.0'
--   Found glib-2.0, version 2.48.1
-- Found wxWidgets: -L/usr/lib/x86_64-linux-gnu;-pthread;;;-lwx_baseu_net-3.0;-lwx_gtk2u_core-3.0;-lwx_baseu-3.0 (found version "3.0.2") 
-- generating headers and languages
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/foo/build
user@anonymous:~/foo/build$ make 
```

**Comment by chodorenko** [comment]
Понятно , те при использовании гита выгружается только дира far2l  а при использовании svn структура немного другая  отсюда и разночтения в путях 


тогда сталкиваетмся с другой ошибкой сборки

Scanning dependencies of target utils
[ 15%] Building CXX object utils/CMakeFiles/utils.dir/src/KeyFileHelper.cpp.o
c++: error: unrecognized command line option ‘-std=c++14’
c++: error: unrecognized command line option ‘-std=c++14’
utils/CMakeFiles/utils.dir/build.make:62: ошибка выполнения рецепта для цели «utils/CMakeFiles/utils.dir/src/KeyFileHelper.cpp.o»
make[2]: *** [utils/CMakeFiles/utils.dir/src/KeyFileHelper.cpp.o] Ошибка 1
CMakeFiles/Makefile2:312: ошибка выполнения рецепта для цели «utils/CMakeFiles/utils.dir/all»
make[1]: *** [utils/CMakeFiles/utils.dir/all] Ошибка 2
Makefile:83: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2

**Comment by elfmz** [comment]
видимо gcc стартоват, хотя если честно -std=c++14 там нафиг не нужен

**Comment by chodorenko** [comment]
gcc (SUSE Linux) 4.8.5

**Comment by lieff** [comment]
Вот о чем я и говорил, не у всех все такое сверх новое)

**Comment by chodorenko** [comment]
ну как бы это SuSE 42.1 Leap  актуальный дистр , я заменил эту опцию  на  -std=c++11 всё билдится как надо , вопрос нужна ли эта оптимизация ?

**Comment by elfmz** [comment]
-std=c++14 это не оптимизация я включение некоторых фич языка которые все равно тут не юзаются

**Comment by lieff** [comment]
Мм у меня в suse уже gcc6, там видимо альтернитывный есть более высокий, а по дефолту такой. Но таки да, мне кажется gcc 4.8 надо держать минимальным как миниум.

**Comment by chodorenko** [comment]
[ 49%] Building CXX object far2l/CMakeFiles/far2l.dir/vtshell.cpp.o
/home/chodorenko/9/far2l.git/trunk/far2l/vtshell.cpp:14:0: warning: "__USE_BSD" redefined [enabled by default]
 #define __USE_BSD
 ^
In file included from /usr/include/c++/4.8/x86_64-suse-linux/bits/os_defines.h:39:0,
                 from /usr/include/c++/4.8/x86_64-suse-linux/bits/c++config.h:2097,
                 from /usr/include/c++/4.8/new:39,
                 from /home/chodorenko/9/far2l.git/trunk/far2l/headers.hpp:36,
                 from /home/chodorenko/9/far2l.git/trunk/far2l/vtshell.cpp:1:
/usr/include/features.h:320:0: note: this is the location of the previous definition
 # define __USE_BSD 1
 ^
/home/chodorenko/9/far2l.git/trunk/far2l/vtshell.cpp:802:8: error: ‘unique_ptr’ in namespace ‘std’ does not name a type
 static std::unique_ptr<VTShell> g_vts;
        ^
/home/chodorenko/9/far2l.git/trunk/far2l/vtshell.cpp: In function ‘int VTShell_Execute(const char*, int (*)(int, char**))’:
/home/chodorenko/9/far2l.git/trunk/far2l/vtshell.cpp:808:7: error: ‘g_vts’ was not declared in this scope
  if (!g_vts)
       ^
/home/chodorenko/9/far2l.git/trunk/far2l/vtshell.cpp:813:7: error: ‘g_vts’ was not declared in this scope
   r = g_vts->ExecuteForkProc(cmd, fork_proc);
       ^
/home/chodorenko/9/far2l.git/trunk/far2l/vtshell.cpp:815:7: error: ‘g_vts’ was not declared in this scope
   r = g_vts->ExecuteCommand(cmd);
       ^
/home/chodorenko/9/far2l.git/trunk/far2l/vtshell.cpp:818:7: error: ‘g_vts’ was not declared in this scope
  if (!g_vts->IsOK()) {
       ^
far2l/CMakeFiles/far2l.dir/build.make:2870: ошибка выполнения рецепта для цели «far2l/CMakeFiles/far2l.dir/vtshell.cpp.o»
make[2]: *** [far2l/CMakeFiles/far2l.dir/vtshell.cpp.o] Ошибка 1
CMakeFiles/Makefile2:373: ошибка выполнения рецепта для цели «far2l/CMakeFiles/far2l.dir/all»
make[1]: *** [far2l/CMakeFiles/far2l.dir/all] Ошибка 2
Makefile:83: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2

Вот с этим не знаю что делать ? 
вообще хорошо бы какойто скайп/вибер/IRC группу чтобы не плодить месаги в тикетах

**Comment by lieff** [comment]
Попробуй #include <memory> добавить в этот сишник.

**Comment by lieff** [comment]
Можно в http://matrix.org/ канал создать

**Comment by chodorenko** [comment]
Прошу прощения я как бы совсем не прогер  чтобы понимать что именно надо заинклюдить

**Comment by elfmz** [comment]
такс, верните чистую версию с гита, но перед запуском cmake не удаляйте -std=c++14, а замените ее на -std=c++11

**Comment by chodorenko** [comment]
^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-c++11-narrowing" [enabled by default]
cc1plus: warning: unrecognized command line option "-Wno-c++11-narrowing" [enabled by default]
[ 49%] Building CXX object far2l/CMakeFiles/far2l.dir/vmenu.cpp.o
[ 49%] Building CXX object far2l/CMakeFiles/far2l.dir/xlat.cpp.o
[ 49%] Building CXX object far2l/CMakeFiles/far2l.dir/vtshell.cpp.o
/home/chodorenko/9/far2l.git/trunk/far2l/vtshell.cpp:14:0: warning: "__USE_BSD" redefined [enabled by default]
 #define __USE_BSD
 ^
In file included from /usr/include/c++/4.8/x86_64-suse-linux/bits/os_defines.h:39:0,
                 from /usr/include/c++/4.8/x86_64-suse-linux/bits/c++config.h:2097,
                 from /usr/include/c++/4.8/new:39,
                 from /home/chodorenko/9/far2l.git/trunk/far2l/headers.hpp:36,
                 from /home/chodorenko/9/far2l.git/trunk/far2l/vtshell.cpp:1:
/usr/include/features.h:320:0: note: this is the location of the previous definition
 # define __USE_BSD 1
 ^
/home/chodorenko/9/far2l.git/trunk/far2l/vtshell.cpp:802:8: error: ‘unique_ptr’ in namespace ‘std’ does not name a type
 static std::unique_ptr<VTShell> g_vts;
        ^
/home/chodorenko/9/far2l.git/trunk/far2l/vtshell.cpp: In function ‘int VTShell_Execute(const char*, int (*)(int, char**))’:
/home/chodorenko/9/far2l.git/trunk/far2l/vtshell.cpp:808:7: error: ‘g_vts’ was not declared in this scope
  if (!g_vts)
       ^
/home/chodorenko/9/far2l.git/trunk/far2l/vtshell.cpp:813:7: error: ‘g_vts’ was not declared in this scope
   r = g_vts->ExecuteForkProc(cmd, fork_proc);
       ^
/home/chodorenko/9/far2l.git/trunk/far2l/vtshell.cpp:815:7: error: ‘g_vts’ was not declared in this scope
   r = g_vts->ExecuteCommand(cmd);
       ^
/home/chodorenko/9/far2l.git/trunk/far2l/vtshell.cpp:818:7: error: ‘g_vts’ was not declared in this scope
  if (!g_vts->IsOK()) {
       ^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-c++11-narrowing" [enabled by default]
cc1plus: warning: unrecognized command line option "-Wno-c++11-narrowing" [enabled by default]
far2l/CMakeFiles/far2l.dir/build.make:2870: ошибка выполнения рецепта для цели «far2l/CMakeFiles/far2l.dir/vtshell.cpp.o»
make[2]: *** [far2l/CMakeFiles/far2l.dir/vtshell.cpp.o] Ошибка 1
CMakeFiles/Makefile2:373: ошибка выполнения рецепта для цели «far2l/CMakeFiles/far2l.dir/all»
make[1]: *** [far2l/CMakeFiles/far2l.dir/all] Ошибка 2
Makefile:83: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2

**Comment by elfmz** [comment]
ну чтож, приду домой добавлю #include <memory> мож в самом деле в нем дело

**Comment by invy** [comment]
1. Don't use SVN.
2. gcc 4.8 -  слишком старый.
3. -Wno-c++11-narrowing опция для clang'а, по хорошему надо бы начать различать каким компилятором собирается far (gcc или clang) и соответственно добавлять ее или нет.
4. error: ‘unique_ptr’ in namespace ‘std’ does not name a type. Ну не умеет антикварный компилятор современный c++. Используй gcc5 или свежий clang. Можно попробовать заменить c++11 на c++0x, но гарантии, что оно скомпилируется и будет потом работать адекватно - нету.

**Поставь свежий компилятор.**

**Comment by invy** [comment]
> -std=c++14 это не оптимизация я включение некоторых фич языка которые все равно тут не юзаются
Пока не юзаются. В c++14 добавили несколько приятных фич, от которых отказыватсья я не вижу смысла.

**Comment by invy** [comment]
> Вот о чем я и говорил, не у всех все такое сверх новое)
в suse вроде бы есть clang 3.7 который прекрасно умеет c++14 (в clang 3.4 уже было).

**Comment by chodorenko** [comment]
1. Я не поддерживаю вашего мнения о использовании SVN,  как говорится каждый использует то что ему удобно.
2. IMHO  должно билдиться тем что идёт из коробки , если в актуальных дистрибутивах при установке среды разработчика ставится gcc 4.8 то продукт должен его поддерживать или на этапе конфигурирования сказать "знаешь, мне нужен clang не ниже вот такой версии, поставь его пожалуйста".
3. Да Clang есть версии 3.7 возможно им можно собрать продукт, но мана как это сделать нету.


PS:  Если так относиться к пользователям и тестерам как Вы **invy** то можно остаться без тестеров прям на этапе разработки, что не совсем благоприятно скажется на качестве продукта и его перспективах. Мне кажется что это не в интересах этого продукта

**Comment by invy** [comment]
@chodorenko , я не понимаю ваших претензий. Я вам ответил локанично и по сути на ваши вопросы и сказал как решить проблемы.

1. Far2l разрабатывается с использованием git в качестве системы версионирования и размещен на **git**hub.

2. "Из коробки" с десктопными дистрибутивами **компилятор обычно вообще не поставляется.** В актуальных дистрибутивах давно GCC свежее 4.9. Но я в ридми наверное стоит написать.

3. Установить clang 3.7 и указать cmake дополнительно опции:
 -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang

**Comment by elfmz** [comment]
пробуйте ща.
только начинайте с чистого листа, то есть - с удаления старого билдкаталога и cmake

**Comment by invy** [comment]
В c++14 есть замечательная функция std::equals в виде:

```
template< class InputIt1, class InputIt2 >
bool equal( InputIt1 first1, InputIt1 last1, 
            InputIt2 first2, InputIt2 last2 );

bool equal( InputIt1 first1, InputIt1 last1, 
            InputIt2 first2, InputIt2 last2,
            BinaryPredicate p );
```

Отказываться от них как-то не хочется, т.к. ими моно великолепно заменить все старые сишные *cmp функции...

**Comment by chodorenko** [comment]
не понимаю почему , но он упрямо пытается искать инклюды тут /usr/bin/../lib64/gcc/x86_64-suse-linux/4.8/../../../../include/c++/4.8/cstdio

chodorenko@chodorenko-linux:~/9/build> cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release ../far2l.git/trunk/
-- The C compiler identification is Clang 3.7.0
-- The CXX compiler identification is Clang 3.7.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28")
-- checking for module 'glib-2.0'
--   found glib-2.0, version 2.44.1
-- Found wxWidgets: TRUE
-- generating headers and languages
-- Configuring done
-- Generating done
-- Build files have been written to: /home/chodorenko/9/build
chodorenko@chodorenko-linux:~/9/build> make
Scanning dependencies of target utils
[  1%] Building CXX object utils/CMakeFiles/utils.dir/src/KeyFileHelper.cpp.o
In file included from /home/chodorenko/9/far2l.git/trunk/utils/src/KeyFileHelper.cpp:1:
In file included from /home/chodorenko/9/far2l.git/trunk/utils/include/KeyFileHelper.h:2:
In file included from /usr/bin/../lib64/gcc/x86_64-suse-linux/4.8/../../../../include/c++/4.8/string:52:
In file included from /usr/bin/../lib64/gcc/x86_64-suse-linux/4.8/../../../../include/c++/4.8/bits/basic_string.h:2815:
In file included from /usr/bin/../lib64/gcc/x86_64-suse-linux/4.8/../../../../include/c++/4.8/ext/string_conversions.h:43:
/usr/bin/../lib64/gcc/x86_64-suse-linux/4.8/../../../../include/c++/4.8/cstdio:120:11: error: no member named 'gets' in the global namespace
  using ::gets;
        ~~^
1 error generated.
utils/CMakeFiles/utils.dir/build.make:62: ошибка выполнения рецепта для цели «utils/CMakeFiles/utils.dir/src/KeyFileHelper.cpp.o»
make[2]: *** [utils/CMakeFiles/utils.dir/src/KeyFileHelper.cpp.o] Ошибка 1
CMakeFiles/Makefile2:312: ошибка выполнения рецепта для цели «utils/CMakeFiles/utils.dir/all»
make[1]: *** [utils/CMakeFiles/utils.dir/all] Ошибка 2
Makefile:83: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2

**Comment by elfmz** [comment]
пфф, сишные *cmp работающие с указателями оно не заменит, т.к. не работает с указателями. Это во первых. А для стлных контейнеров реализовать самому этот equal при необходимости - плюнуть и растереть.

**Comment by chodorenko** [comment]
Уф, поборол, надо наверное какую то доку писать всё же что требуется или gcc 5+ или clang 3.6+
Кстати про гит http://screencloud.net/v/u7Jb так что можно пользоваться чем угодно 

Я не програмер но насколько помню *cmp это прямой указатель на память, как бы довольно стрёмное занятие.

**Comment by elfmz** [comment]
жизнь вообще стремная штука. От нее все умирают :(

**Comment by chodorenko** [comment]
Более того гарантия 100 % , ни одного бессмертного нам не известно :)
