### ISSUE TITLE
Wrap charset detection with libuchardet to [optional] standalone module

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1102]
For whose who run prebuilt far2l on shared hosting platforms and thus do not able to install dependencies. Every other needed libs are used from separate .so's now, so their absence will not prevent basic far2l from starting. The only thing left is uchardet

PS: Yes, there is "portable" build with all needed libs integrated, but it is highly experimental and may not work on some systems.

**Comment by elfmz** [comment]
I dont know what is portable build, but you always may copy libuchardet.so.0 into far2l directory and do export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/far2l/dir/path and it will load it from there

**Comment by elfmz** [comment]
BTW if 'basic' far2l worth using? Without colorer and NetRocks its must be smelling like Volkov Commander :)

**Comment by unxed** [comment]
> copy libuchardet.so.0 into far2l directory and do export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/far2l/dir/path

In 'portable build' I [use](https://github.com/unxed/far2l-deb/blob/master/portable/lxc-far2l-portable.sh) almost the same method, but using `patchelf --set-rpath` as LD_LIBRARY_PATH not worked for me for some reason. It works with almost all libs, excluding wx and libsmbclient which are for sure not mandatory for shared hostings. Also using `makeself` to pack all stuff in one runnable file for easy upload and usage.

> -DUCD=YES/NO

Forgot about this option, thanks!
