### ISSUE TITLE
[NetRocks] Remote file is not updated after editing with external editor using "file associations"

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1103]
0. Ставим ассоциацию nano !.! на *.txt

1. Создаем test.txt на sftp в netrocks

2. Открываем в nano по enter'у

3. Изменяем текст в файле, сохраняемся

4. Выходим из nano

5. Опа! Файл на sftp не обновился

**Comment by unxed** [comment]
> Так и не должен был

NOT A BUG тогда? Закрываем?

**Comment by elfmz** [comment]
ага
