### ISSUE TITLE
pasting problem from far2l ttyx to any other app 

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1127]
1. open gnome terminal
2. run far2l --tty (it needs to be built with ttyx broker)
3. open editor
4. type "test"
5. select word "test"
6. press ctrl+c
7. switch to another X app
8. try to paste (it will fail)
9. switch back to far2l
10. paste
11. switch to another X app
12. try to paste (it will success)

**Comment by elfmz** [comment]
I saw it but for me it quite sporadic and also it must be workaround simplier - just do very first Ctrl+C inside of far2l --tty twice (next works from first attempts)

**Comment by unxed** [comment]
Can far2l just _react_ on first ctrl-c twice for the first time in ttyx mode?))

**Comment by unxed** [comment]
duplicated / translated to current layout characters is tty echo
run `stty -echo && ./xkbcat -up` to see correct output
(so it looks like we still need to process terminal input to get correct alphanumeric chars in current keyboard layout)

**Comment by elfmz** [comment]
check if still repro now

**Comment by unxed** [comment]
Now fixed, thanks!

**Comment by unxed** [comment]
By the way, is the fact that vertical blocks copy-pasting do not work between the ttyx and wx far2l a bug or a feature?
