### ISSUE TITLE
padding problem in mounts

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1129]
69/109G line

![Снимок экрана от 2021-12-05 01-31-15](https://user-images.githubusercontent.com/1151423/144726519-08112833-95ee-42a4-9dee-84b8d74afcda.png)

**Comment by sxored** [comment]
a correction is suggested in the comments to the commit

https://github.com/elfmz/far2l/commit/9d9c367f83046157e29deb93d7465cb6dac82106#commitcomment-61391695

**Comment by elfmz** [comment]
done in completely different way (still some things need to be cleaned)

**Comment by sxored** [comment]
it is desirable to add one ( or two ) indent character ( space ) to the left

**Comment by elfmz** [comment]
on the left of what?

**Comment by elfmz** [comment]
ok now?

**Comment by unxed** [comment]
much better! it would be even better if "/" separator would be at the same position for every line :)

![изображение](https://user-images.githubusercontent.com/1151423/144764464-d4ffa02a-3a34-4f77-95ac-f71c7deb246d.png)

**Comment by elfmz** [comment]
best the enemy of the good, and it may consume some extra space

**Comment by unxed** [comment]
okay, let's leave it as is

**Comment by sxored** [comment]
two possible solution in this commit

https://github.com/elfmz/far2l/pull/1289/commits/65768cbe5373d5667bffe0c6ab08ecf0c2ffad9e

PR #1289

1) wide - use 5 symbols instead of 3 for numbers

2) not wide - use of some symbol ( not space ? ) for padding at left side of numbers

```
			if (wide == 1) {
				avail_ident = "";
				total_ident = "";
				avail_fraction = avail < 100 ? ( avail < 10 ? 3 : 2 ) : 1;
				total_fraction = total < 100 ? ( total < 10 ? 3 : 2 ) : 1;
			} else {
				avail_ident = avail < 100 ? ( avail < 10 ? "" : "_" ) : "";
				total_ident = total < 100 ? ( total < 10 ? "" : " " ) : "";
				avail_fraction = avail < 10 ? 1 : 0;
				total_fraction = total < 10 ? 1 : 0;
			}

			printf "%s\t%s%.*f%s %s%.*f%s %3s\t%8s\n", path, avail_ident, avail_fraction, avail, avail_units, total_ident, total_fraction, total, total_units, ...

```
