### ISSUE TITLE
"add to archive" action is not available in far2l using F11 plugin menu

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#113]

**Comment by elfmz** [comment]
Is it available in far/multiarc Windows?
Why its should be there is there is shift+f1?

**Comment by unxed** [comment]
available on windows, yes.
shift+f1 works, thanks

**Comment by elfmz** [comment]
latest windows far uses arclite plugin to handle archuves, in far2l I used older multiarc. They're different

**Comment by unxed** [comment]
ok, closing.
