### ISSUE TITLE
DEB package incomplete

### ISSUE THREAD

**Issue by SantjagoCorkez** [elfmz/far2l#1131]
Debian Bullseye,

Built with: `cmake -DUSEWX=yes -DCMAKE_BUILD_TYPE=Release -DPYTHON=yes -G Ninja ..`

Repo state:
```
commit 9d9c367f83046157e29deb93d7465cb6dac82106
Author: elfmz <fenix1905@tut.by>
Date:   Sun Dec 5 02:29:26 2021 +0300

    use separate units for avail/total sizes
```

cpack fails to build full-featured package:
```
$ cpack
CPack: Create package using DEB
CPack: Install projects
CPack: - Install project: far2l []
CPack: -   Install component: base
CPack: -   Install component: desktop
CPack: -   Install component: system
Python: preparing virtual environment
Error: [Errno 13] Permission denied: '/usr/local/lib/far2l'
Python: installing packages
ln: failed to create symbolic link '/usr/local/lib/far2l/far2l_askpass': No such file or directory
ln: failed to create symbolic link '/usr/local/lib/far2l/far2l_sudoapp': No such file or directory
CPack: Create package
CPack: - package: /home/andy/Projects/far2l/build/far2l_2.3.211205-9d9c367f-alpha_amd64.deb generated.
```

**Comment by alexmyczko** [comment]
on which version of debian is that?

**Comment by SantjagoCorkez** [comment]
First row of my report: `Debian Bullseye`

```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
```

**Comment by alexmyczko** [comment]
your `cpack` fails as it tries to do something on the system, and you're only user without permission to do so.

**Comment by SantjagoCorkez** [comment]
Since I haven't modified any line of the source code prior to building it, that means it's the project's source code which defines some actions which my operating system prohibits. Like unprivileged modification of `/usr/local/lib`. Seems it tries to commit these actions on live filesystem instead of a chroot sandbox as, for example, `dpkg` does.

**Comment by alexmyczko** [comment]
cpack is not the preferred way of creating debs. but debian source package, the official from debian.org. maybe close this issue?

**Comment by alexmyczko** [comment]
@unxed close this issue? too many open issues? or is there a plan to improve cpack debs?

**Comment by unxed** [comment]
Let's ask @elfmz. I do not have closing permissions.
