### ISSUE TITLE
Wrong Debian wxWidgets package name in README.md

### ISSUE THREAD

**Issue by vit1251** [elfmz/far2l#1138]
Since in Debian exists GTK 3 and GTK 2 maintiners in Debian provide two kind of packages.
You may make correction in instruction on new package name `libwxgtk3.0-gtk3-dev` for Debian system.

**Comment by elfmz** [comment]
libwxgtk3.0-gtk3-dev is mentioned in readme under 'In recent distributives'
however may be its time to mention it as first place..
