### ISSUE TITLE
new icon for far2l

### ISSUE THREAD

**Issue by bigvax** [elfmz/far2l#1139]
Я нарисовал новую иконку для проекта.
Возможно, ее можно использовать, если, конечно понравится авторам и комьюнити... ;)
**
I drew a new icon for the project.
Perhaps it can be used, if, of course, the authors and the community like it ...;) 

PS. Я, конечно, не художник - но как умею... ;)
I, of course, not an artist - but as I can ...;) 

![far2l](https://user-images.githubusercontent.com/284112/144777568-a8c670dd-20b7-437c-84cd-8c9603fc573f.png)
[far2l-icons.zip](https://github.com/elfmz/far2l/files/7657514/far2l-icons.zip)

**Comment by elfmz** [comment]
Ну. хотя это изначально и порт на линукс, сейчас он собирается и под мак и под бсд, так что иконка с пингвином не актуальна. Да и текущие иконки в целом вроде норм.

**Comment by bigvax** [comment]
OK
понял
