### ISSUE TITLE
cursor size issue

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1148]
1. open wx far2l
2. run bash
3. remember cursor size
4. run far2l --tty
5. exit it
6. cursor size will change to thinner one

**Comment by unxed** [comment]
another possible related issue is that cursor size is 1px by default in tty mode, but it's about 2 or 3 pixels height in wx mode

maybe we should make them equal?

**Comment by elfmz** [comment]
Unfortunately creators of vt510 terminal didnt give such choice 30 years ago - https://vt100.net/docs/vt510-rm/DECSCUSR.html 
But i guess some terminals may allow changing this as via their configuration UI
