### ISSUE TITLE
any plans to release for M1 processor?

### ISSUE THREAD

**Issue by progreccor** [elfmz/far2l#1152]
any plans to release for M1 processor?
планируется ли выпуск для процессоров M1?

**Comment by elfmz** [comment]
Its up to support M1 in MacPorts or Homebrew as far2l builds with them.
Although theoretically its possible to build all needed dependencies from sources instead of using libraries provided by MacPorts/Homebrew but as i'm not even a Mac user - its only if somebody else will do that.

**Comment by alexmyczko** [comment]
https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/far2l.rb

since they are only providing cask, they are not building it from source...

**Comment by horieva** [comment]
> https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/far2l.rb
> 
> since they are only providing cask, they are not building it from source...
> 
> you can start to create a source formulae with `brew create https://github.com/elfmz/far2l/archive/refs/tags/v_2.4.0.tar.gz`

Thank you. Can you explain how I can recompile that for m1? 

When I trying to do `brew create...` I see that: 

```
==> Downloading https://github.com/elfmz/far2l/archive/refs/tags/v_2.4.0.tar.gz
==> Downloading from https://codeload.github.com/elfmz/far2l/tar.gz/refs/tags/v_
                         -=O=-                                 #    #  #  #
Warning: Cannot verify integrity of '2fc6bed4fa863d80c74babc63900153e774b5046cb392b79f19f5c0a359dafb0--far2l-v_2.4.0.tar.gz'.
No checksum was provided for this resource.
For your reference, the checksum is:
  sha256 "a595f7f2b48aaf6cfd61c1539bb52207f8f985576ee928915f54b675666e9f88"
Please run `brew audit --new far2l` before submitting, thanks.
Editing /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/far2l.rb
Error: Failure while executing; `subl -w /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/far2l.rb` exited with 1.
```

Thank you!

**Comment by elfmz** [comment]
I've made experimental .dmg with a Universal binary, but since i dont have M1 mac - feel free to test if it really works:) See here - https://github.com/elfmz/far2l/issues/1499
