### ISSUE TITLE
vblocks not copy-pasted properly from ttyx to wx far2l

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1154]
also with ttyx -> putty4far2l-in-Wine
also with ttyx -> Far3-in-Wine

sometimes copy-pasting from far2l ttyx to far2l-in-putty4far2l crashes far2l-in-putty4far2l
could not determine in what specific circumstances this happens

**Comment by elfmz** [comment]
its (almost) by design

**Comment by unxed** [comment]
If vblock format not set, but clipboard contains array of strings of the same length, ask user "paste as usual or paste as vblock", ?

**Comment by elfmz** [comment]
Ask user all the time for a thing that is used extremely rarely? In an even more rare situation (wx far2l together with tty version)? Better document as limitation and may be fix later, as potentially it must be possible, just no idea how..

**Comment by unxed** [comment]
Don't get, why can't ttyx register the format for vertical blocks

**Comment by elfmz** [comment]
It can but i dont know how:)
I looked into wxwidget's implementation - they support different cli[board formats under GTK (wxWidgets-3.0.5/src/gtk/clipbord.c wxClipboard::DoIsSupported) but implementation for pure x11 wxWidgets-3.0.5/src/x11/clipbrd.cpp seems is not supporting this.
However GTK under X11 obviously internally uses X11's clipboard, so it must be possible theoretically, just very not sure that its a such useful scenario to spend time on it right now.

**Comment by unxed** [comment]
I guess the solution is inside `xclip` tool sources. It allows to specify ANY clipboard using -t switch.
List currently available formats:
xclip -o -selection clipboard -t TARGETS

https://github.com/astrand/xclip

**Comment by elfmz** [comment]
yep.. now it looks more feasible)
