### ISSUE TITLE
User and group list in file attribute 

### ISSUE THREAD

**Issue by ElderlyLinuxUser** [elfmz/far2l#1155]
Можно ли сделать выбор владельца и группы из списка в форме изменения атрибутов файла ?

![изображение](https://user-images.githubusercontent.com/96444123/146824914-ea5dc56c-1b69-466f-a965-c1baa19cfd11.png)

**Comment by unxed** [comment]
Закрываем?

**Comment by ElderlyLinuxUser** [comment]
> Закрываем?

Да.
