### ISSUE TITLE
python plugin fails to build on aarch64 (oracle linux)

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1164]
```
[ 99%] Generating _pyfar.cpp
Traceback (most recent call last):
  File "/home/opc/far2l/python/src/pythongen.py", line 43, in <module>
    ffi.cdef(data, packed=True)
  File "/usr/lib64/python3.6/site-packages/cffi/api.py", line 107, in cdef
    self._cdef(csource, override=override, packed=packed)
  File "/usr/lib64/python3.6/site-packages/cffi/api.py", line 121, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "/usr/lib64/python3.6/site-packages/cffi/cparser.py", line 315, in parse
    self._internal_parse(csource)
  File "/usr/lib64/python3.6/site-packages/cffi/cparser.py", line 338, in _internal_parse
    self._parse_decl(decl)
  File "/usr/lib64/python3.6/site-packages/cffi/cparser.py", line 437, in _parse_decl
    self._get_struct_union_enum_type('enum', node)
  File "/usr/lib64/python3.6/site-packages/cffi/cparser.py", line 706, in _get_struct_union_enum_typ
e
    tp = self._build_enum_type(explicit_name, type.values)
  File "/usr/lib64/python3.6/site-packages/cffi/cparser.py", line 845, in _build_enum_type
    nextenumvalue = self._parse_constant(enum.value)
  File "/usr/lib64/python3.6/site-packages/cffi/cparser.py", line 832, in _parse_constant
    "simple numeric constant" % exprnode.coord.line)
cffi.error.FFIError: :308: unsupported expression: expected a simple numeric constant
make[2]: *** [python/CMakeFiles/python.dir/build.make:74: python/_pyfar.cpp] Error 1
make[1]: *** [CMakeFiles/Makefile2:1203: python/CMakeFiles/python.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

**Comment by elfmz** [comment]
ping @m32

**Comment by m32** [comment]
Cant reproduce this error, fresh build:
[ 97%] Built target NetRocks-WebDAV
[ 97%] Generating _pyfar.cpp
generating /devel/far2l/build/python/_pyfar.cpp
Scanning dependencies of target python
[ 98%] Building CXX object python/CMakeFiles/python.dir/src/python.cpp.o
[ 98%] Building CXX object python/CMakeFiles/python.dir/_pyfar.cpp.o
[ 98%] Linking CXX shared module ../install/Plugins/python/plug/python.far-plug-wide
[ 98%] Built target python

It must be something like around line 308:
enum ... {
   KEY_PRNTSCRN = 1<<0,
...
}

**Comment by unxed** [comment]
Line 308 of what file? May I gather some other debug info somehow?

**Comment by elfmz** [comment]
First of all, try to build on completely fresh pulled repo (if it wasn't so)

**Comment by m32** [comment]
File "/home/opc/far2l/python/src/pythongen.py", line 43, in <module>
pythongen line 43: it parses farwin.h, farcolor.hpp, farkeys.hpp and plugin.hpp identical to installffi from pluginmanager.py, when pythongen fails then pluginmanager will fail too, adding print(fqname) before open will show which file is parsed

  File "/usr/lib64/python3.6/site-packages/cffi/cparser.py", line 832, in _parse_constant
    "simple numeric constant" % exprnode.coord.line)
cffi.error.FFIError: :308: unsupported expression: expected a simple numeric constant
308 is line number in parsed file

I have also build on fresh checkout - no errors

**Comment by unxed** [comment]
it is
/home/opc/far2l/python/configs/plug/far2l/farkeys.hpp
looks like "unsupported" is about expressions in enum values definitions.

temporary commented out such expressions, now it fails with
```
/home/opc/far2l/python/configs/plug/far2l/plugin.hpp
Traceback (most recent call last):
  File "/home/opc/far2l/python/src/pythongen.py", line 44, in <module>
    ffi.cdef(data, packed=True)
  File "/usr/lib64/python3.6/site-packages/cffi/api.py", line 107, in cdef
    self._cdef(csource, override=override, packed=packed)
  File "/usr/lib64/python3.6/site-packages/cffi/api.py", line 121, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "/usr/lib64/python3.6/site-packages/cffi/cparser.py", line 315, in parse
    self._internal_parse(csource)
  File "/usr/lib64/python3.6/site-packages/cffi/cparser.py", line 338, in _internal_parse
    self._parse_decl(decl)
  File "/usr/lib64/python3.6/site-packages/cffi/cparser.py", line 437, in _parse_decl
    self._get_struct_union_enum_type('enum', node)
  File "/usr/lib64/python3.6/site-packages/cffi/cparser.py", line 706, in _get_struct_union_enum_typ
e
    tp = self._build_enum_type(explicit_name, type.values)
  File "/usr/lib64/python3.6/site-packages/cffi/cparser.py", line 845, in _build_enum_type
    nextenumvalue = self._parse_constant(enum.value)
  File "/usr/lib64/python3.6/site-packages/cffi/cparser.py", line 790, in _parse_constant
    return int(s, 16)
ValueError: invalid literal for int() with base 16: '0x000000ffUL'
make[2]: *** [python/CMakeFiles/python.dir/build.make:74: python/_pyfar.cpp] Error 1
make[1]: *** [CMakeFiles/Makefile2:1203: python/CMakeFiles/python.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

**Comment by unxed** [comment]
```
$cat /etc/oracle-release
Oracle Linux Server release 8.4
$ uname -m
aarch64
```

**Comment by m32** [comment]
0x000000ffUL is invalid in python, should be 0x000000ff

**Comment by elfmz** [comment]
May remove that suffixes if it only reason of, dunno why they're there - they're useless in definition of enum's fields. However its then unclear why works for intel builds.

**Comment by unxed** [comment]
> May remove that suffixes if it only reason of, dunno why they're there - they're useless in definition of enum's fields. However its then unclear why works for intel builds.

Worked! Now:

```
[100%] Building CXX object python/CMakeFiles/python.dir/_pyfar.cpp.o
/home/opc/far2l/build/python/_pyfar.cpp: In function ‘int _cffi_const_a(long long unsigned int*)’:
/home/opc/far2l/build/python/_pyfar.cpp:1322:12: error: ‘a’ was not declared in this scope
   int n = (a) <= 0;
            ^
make[2]: *** [python/CMakeFiles/python.dir/build.make:94: python/CMakeFiles/python.dir/_pyfar.cpp.o]
 Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1204: python/CMakeFiles/python.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

**Comment by unxed** [comment]
So it looks like UL suffixes may safely be removed. But I don't know what to do with expressions in ENUMs

**Comment by elfmz** [comment]
can you try to replace the with ul suffixes? (lowercased) may be it will work (and will be safer change)

**Comment by unxed** [comment]
ValueError: invalid literal for int() with base 16: '0x000000fful'

**Comment by elfmz** [comment]
but why it works for intel? may be oracle linux has some older FFI of whatelse?

**Comment by elfmz** [comment]
while suffixes may be removed, removing complex expressions from farkeys.hpp is harder.. BTW regarding suffixes it seems it really was a bug there and fixed - https://foss.heptapod.net/pypy/cffi/-/issues/407

**Comment by unxed** [comment]
how do i check cffi version used by far2l?

**Comment by m32** [comment]
run this command in python/bin folder:
pip freeze |grep cffi
on ubuntu cffi=1.15.0

**Comment by unxed** [comment]
```
$ ./pip freeze |grep cffi
You are using pip version 9.0.3, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
cffi==1.11.5
```

**Comment by m32** [comment]
KEY_CTRLSHIFTA = (KEY_CTRL | KEY_SHIFT) + 'A' - this is quite a complicated expression and cffi works fine.

https://pypi.org/project/cffi has 1.15.0 for cffi on aarch64 for python >= 3.6 and one of them should be downloaded when far2l is built

Which version of Python is on your machine?

**Comment by unxed** [comment]
```
$ python --version
Python 3.6.8
cd far2l/build/install/Plugins/python/plug/python/bin
./python --version                                ↑
Python 3.6.8
./python3 --version                               ↑
Python 3.6.8
```

**Comment by unxed** [comment]
```
...build/install/Plugins/python/plug/python/bin$ ./pip show cffi                                   ↑
Name: cffi
Version: 1.11.5
Summary: Foreign Function Interface for Python calling C code.
Home-page: http://cffi.readthedocs.org
Author: Armin Rigo, Maciej Fijalkowski
Author-email: python-cffi@googlegroups.com
License: MIT
Location: /usr/lib64/python3.6/site-packages
Requires: pycparser
You are using pip version 9.0.3, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by unxed** [comment]
running
```
cd far2l/python/configs/plug/python/bin
./python -m pip install --upgrade pip
./python -m pip install --upgrade cffi
```
solved an issue with expressions in ENUMs for me

**Comment by elfmz** [comment]
What about UL suffixes? still making problems?

**Comment by unxed** [comment]
> What about UL suffixes? still making problems?

nope :)

**Comment by elfmz** [comment]
so issue resolved? however due to looked at that code, i've made old planned change - refactored python plugin build, and now it doesn't create intermediate stuff in sources tree, but instead putting all that stuff into build directory. Also i've made preprocessing of far2l's header files also during build, instead of having 'hard-commited' copies on git.
It all looks working, but it would be nice if @m32 would look at this change just in case...

**Comment by unxed** [comment]
tried a fresh git checkout... still errors if trying to build without cffi update by hands. maybe we should keep this issue open for anyone who will encounter the same error also?

**Comment by elfmz** [comment]
but i didnt fix it, for now it too complicated to eliminate that complex expressions, especially if this fixable just by updating python package

**Comment by unxed** [comment]
may python packages be updated somehow from build script?

**Comment by m32** [comment]
> so issue resolved? however due to looked at that code, i've made old planned change - refactored python plugin build, and now it doesn't create intermediate stuff in sources tree, but instead putting all that stuff into build directory. Also i've made preprocessing of far2l's header files also during build, instead of having 'hard-commited' copies on git. It all looks working, but it would be nice if @m32 would look at this change just in case...

there is still a file renaming in pluginmanager.py
for fname in ("farwin.h", "farcolor.h", "farkeys.h", "farplug-wide.h"):

i did the same, with pycpp (preprocessor) i automatically change the headers to one far2l.hh file. I added one _FAR_PYTHON_GEN variable to the preprocessor definition, but I'm still testing it.
one of the changes is in farkeys.hppL KEY_BRACKET = '[' not liked by cffi

INT_PTR - is hard coded for 64-bit systems, after this change fartty works on raspberry

> may python packages be updated somehow from build script?
yes, in another add_custom_command(TARGET python POST_BUILD COMMAND ...python -m pip install --upgrade ....)

**Comment by elfmz** [comment]
> there is still a file renaming in pluginmanager.py
This renaming works (i hope:)) in bounds of build dir, main concern were about changes in sources directory, that may be prohibited in some build systems.

I didnt know about pycpp, so invented own preprocessor in prebuild.sh, that fixup things like KEY_BRACKET = '[' hope i didnt miss anything.

> INT_PTR - is hard coded for 64-bit systems, after this change fartty works on raspberry
hm i didnt change farwin.h anyhow, so, as i understand need to add its preprocessing to fixup INT_PTR according to current bitness? or it should stay hardcoded as 64?

**Comment by m32** [comment]
The raspberry version of far2l works great but is (default) 32 bit. I would change to the appropriate version for the system and generate far2l-wide.h with preprocessor (cpp), without handwritten headers for python, hence the idea for an additional _FAR_PYTHON_GEN definition

**Comment by elfmz** [comment]
full autogeneration from WinCompat.h litle bit tricky, but some cornercut was possible and done..

**Comment by m32** [comment]
I did it by hand so i did it automagically :)

**Comment by elfmz** [comment]
but you broken 32 bits again:( or not?

**Comment by m32** [comment]
32/64 - I haven't touched that yet, in pythongen.py there is if True: for this task

**Comment by elfmz** [comment]
you may check if target bitness is 64 at prebuild.sh stage by
`echo $'#ifdef __LP64__\nTARGET64\n#endif' | $4 -E - | grep TARGET64`
(and for that need to return passing "${CMAKE_C_COMPILER}" as $4 again)

**Comment by elfmz** [comment]
-E invokes compiler in preprocessor mode, i.e. it doesnt compile, just processes macroses. See how it works:
```
$ echo $'#ifdef __LP64__\nTARGET64\n#endif' | gcc -E - | grep TARGET64
TARGET64
$ echo $'#ifdef __LP64__\nTARGET64\n#endif' | gcc -m32 -E - | grep TARGET64
$
```

**Comment by m32** [comment]
however, I prefer in python:
if ctypes.sizeof(ctypes.cint) == ctypes.sizeof(ctypes.void_p):
    # 32 bit platform
    pass
else:
    # 64 bit platform
    cpp.define("__LP64__")

**Comment by elfmz** [comment]
build system not always == target, sometimes its a cross-compilations :)

**Comment by elfmz** [comment]
..albeit im not sure that python plugin build fully OK for cross-compilation in other aspects..

**Comment by m32** [comment]
then we need python as cross compiler ? would be hard todo

**Comment by m32** [comment]
I also compile python4android at home, only problems and it's not stable

**Comment by m32** [comment]
How to find PATH_MAX and NAME_MAX in python - i have hardcoded defaults from sys/limits.h ?
Or maybe all the parameters of the platform should be calculated in the shell?

**Comment by elfmz** [comment]
in similar way, later i will add creating some incpy/target.h with that things obtained from gcc during configuration, but its tomorrow, its too late today already

**Comment by m32** [comment]
done in python #1173

**Comment by elfmz** [comment]
still, i prefer to make it in cross-compile-friendly, so see https://github.com/elfmz/far2l/commit/90b09cc0523f2a2996bc0f10c973fc0fe7143e08

**Comment by m32** [comment]
It's OK for me

**Comment by m32** [comment]
Looks finished to me.
@unxed

**Comment by unxed** [comment]
still
`cffi.error.FFIError: :307: unsupported expression: expected a simple numeric constant`
on fresh build folder if pip & cffi are not upgraded by hands

if it is not considered a problem, may close

**Comment by m32** [comment]
Maybe your python package cache is corrupted?
rm -rf ~/.cache/pip

**Comment by unxed** [comment]
tried ` rm -rf ~/.cache/pip` (and removed build/python after it), still errors

**Comment by elfmz** [comment]
check now plz

**Comment by unxed** [comment]
```
Cache entry deserialization failed, entry ignored
Collecting pip
  Using cached https://files.pythonhosted.org/packages/a4/6d/6463d49a933f547439d6b5b98b46af8742cc03
ae83543e4d7688c2420f8b/pip-21.3.1-py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 9.0.3
    Uninstalling pip-9.0.3:
      Successfully uninstalled pip-9.0.3
Successfully installed pip-21.3.1
Requirement already satisfied: cffi in /usr/lib64/python3.6/site-packages (1.11.5)
Collecting debugpy
  Using cached debugpy-1.5.1-py2.py3-none-any.whl (4.1 MB)
Collecting pcpp
  Using cached pcpp-1.30-py2.py3-none-any.whl (91 kB)
Requirement already satisfied: pycparser in /usr/lib/python3.6/site-packages (from cffi) (2.14)
Installing collected packages: pcpp, debugpy
Successfully installed debugpy-1.5.1 pcpp-1.30
WARNING: yacc table file version is out of date
Traceback (most recent call last):
  File "/home/opc/far2l/python/src/pythongen.py", line 71, in <module>
    from far2lcffi import ffi, cffi
  File "/home/opc/far2l/build/python/incpy/far2lcffi.py", line 3362, in <module>
  File "/usr/lib64/python3.6/site-packages/cffi/api.py", line 107, in cdef
    self._cdef(csource, override=override, packed=packed)
  File "/usr/lib64/python3.6/site-packages/cffi/api.py", line 121, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "/usr/lib64/python3.6/site-packages/cffi/cparser.py", line 315, in parse
    self._internal_parse(csource)
  File "/usr/lib64/python3.6/site-packages/cffi/cparser.py", line 338, in _internal_parse
    self._parse_decl(decl)
  File "/usr/lib64/python3.6/site-packages/cffi/cparser.py", line 437, in _parse_decl
    self._get_struct_union_enum_type('enum', node)
  File "/usr/lib64/python3.6/site-packages/cffi/cparser.py", line 706, in _get_struct_union_enum_ty
pe
    tp = self._build_enum_type(explicit_name, type.values)
  File "/usr/lib64/python3.6/site-packages/cffi/cparser.py", line 845, in _build_enum_type
    nextenumvalue = self._parse_constant(enum.value)
  File "/usr/lib64/python3.6/site-packages/cffi/cparser.py", line 790, in _parse_constant
    return int(s, 16)
ValueError: invalid literal for int() with base 16: '0x000000ffUL'
make[2]: *** [python/CMakeFiles/python.dir/build.make:80: python/incpy/far2lcffi.py] Error 1
make[1]: *** [CMakeFiles/Makefile2:1247: python/CMakeFiles/python.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

**Comment by unxed** [comment]
possibly
```
 	"$DST/python/bin/python" -m pip install --upgrade cffi
```
also needed (don't know, why)

**Comment by elfmz** [comment]
now?

**Comment by m32** [comment]
File "/usr/lib64/python3.6/site-packages/cffi/api.py", line 107, in cdef

It looks like you are not using virtualenv - python3-cffi is in system installed packages, which is outdated
sudo apt uninstall python3-cffi

**Comment by unxed** [comment]
Unfortunately I am not the only user of that aarch64 machine, so I am afraid to uninstall packages there

**Comment by m32** [comment]
Another option is virtualenv with no system packages:
$PYTHON -m venv "$DST/python"
