### ISSUE TITLE
incorrect sizing of some chars in gnome terminal

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1165]
gnome terminal renders some chars specially, so they overlap neighbour chars (for example, chars with codes 0-31). maybe we should introduce rendering option to replace such chars with proper-sized variants (␀, ␁, ␂, ␃, ␄ etc for example). such option may be made default for TTY* backends.

maybe it should be an viewer/editor option, not far2l-wide.

![изображение](https://user-images.githubusercontent.com/1151423/147874803-55a14b7d-870d-4632-9ce2-34cc42d2ce8b.png)

**Comment by unxed** [comment]
https://en.wikipedia.org/wiki/Control_Pictures

**Comment by elfmz** [comment]
there already bugs about mishandling UTF characters https://github.com/elfmz/far2l/issues/849 https://github.com/elfmz/far2l/issues/826 https://github.com/elfmz/far2l/issues/825 and likely some more, just need to search better

**Comment by elfmz** [comment]
BTW even gnome terminal renders many sequences buggy - at least in Ubuntu 18 - https://unicode-table.com/en/2192/:
![image](https://user-images.githubusercontent.com/20957349/147882228-c1653137-973f-460e-a014-02fbc8b1a182.png)

**Comment by elfmz** [comment]
ah i thought you wanted far2l to fix such problem, but nope, i dont think need to workaround gnome-teminal bugs, need to fix own at least:)
