### ISSUE TITLE
Could not compile anymore by default in Manjaro 21.2.1

### ISSUE THREAD

**Issue by R6ASfcdT** [elfmz/far2l#1168]
Build version: far2l-git r2576.8fe8bd8c-1

System info:
[some_name@pc ~]$ cat /etc/lsb-release 
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.2.1
DISTRIB_CODENAME=Qonos
DISTRIB_DESCRIPTION="Manjaro Linux"

[some_name@pc ~]$ inxi
CPU: quad core Intel Xeon E31280 (-MT MCP-) speed/min/max: 1604/1600/3900 MHz
Kernel: 5.10.89-1-MANJARO x86_64 Up: 25m Mem: 2744.8/24029.2 MiB (11.4%)
Storage: 3.18 TiB (61.4% used) Procs: 274 Shell: Bash inxi: 3.3.11

Error:
In file included from /var/tmp/pamac-build-some_name/far2l-git/src/far2l/far-gvfs/src/GvfsService.cpp:6:
/var/tmp/pamac-build-some_name/far2l-git/src/far2l/far-gvfs/src/UiCallbacks.h:5:10: fatal error: plugin.hpp: No such file or directory
    5 | #include <plugin.hpp>
      |          ^~~~~~~~~~~~

Attachment with full log:
[far2l_build.log](https://github.com/elfmz/far2l/files/7799417/far2l_build.log)

**Comment by elfmz** [comment]
its a build failure of far-gvfs that has different location: https://github.com/cycleg/far-gvfs
But it caused by recen changes in far2l repository - files were located at different places. Futhermore there will be more changes like this soon, cuz want to bring a little order to files locations and naming before switching to beta.
So once all such changes will be finalized - will need to make change at @cycleg 's far-gvfs

**Comment by elfmz** [comment]
Well, in recent commit i've created back directory with that old include files - but with symlinks to new files, just to fix compatibility. So please try now.

**Comment by cycleg** [comment]
Предлагаю добавить в главный проект переменные, указывающие на директории и библиотеки Far2l plugins SDK, например:
```
set(FAR2L_PLUGINS_INCLUDE_DIRS
    ${CMAKE_SOURCE_DIR}/far2l/far2sdk
    ${CMAKE_SOURCE_DIR}/WinPort
)
set(FAR2L_PLUGINS_LIBRARIES utils)
```

**Comment by elfmz** [comment]
Не уверен что это поможет, так как изменятся могут не только расположение, но и имена файлов, как и было только что.  Причины по которой они были переименованы/перемещены были довольно объективны, и давно хотелось это сделать и вроде других причин снова чтото перемещать не заметно.

**Comment by elfmz** [comment]
@R6ASfcdT is ok now?

**Comment by R6ASfcdT** [comment]
> @R6ASfcdT is ok now?

It's ok now.

Спасибо большое.
