### ISSUE TITLE
Far2l can't load Colorer plugin under Debian Bookworm

### ISSUE THREAD

**Issue by cycleg** [elfmz/far2l#1169]
При запуске Far2l выдает предупреждение, что не может загрузить SO "/lusr/local/lib/far2l/Plugins/colorer/plug/colorer.far-plug-wide", потому что якобы нет такого файла. На самом деле файл существует, но есть проблема с зависимостями. far2l подписывается на libfmt7 в "colorer/CMakeLists.txt":
```
if (fmt_FOUND)
    set(fmt_LIBRARY_OPTIONAL "${fmt_LIBRARY}")
    # add libfmt package into far2l dependencies if needed
    IF(PACKAGE_DEPENDENCIES)
        SET(PACKAGE_DEPENDENCIES "${PACKAGE_DEPENDENCIES}, libfmt7" PARENT_SCOPE)
    ELSE(PACKAGE_DEPENDENCIES)
        SET(PACKAGE_DEPENDENCIES "libfmt7" PARENT_SCOPE)
    ENDIF(PACKAGE_DEPENDENCIES)
else()
    set(fmt_LIBRARY_OPTIONAL "")
endif()
```
А компилируется с той, которую ему сватает пакет libfmt-dev. В Bookworm это уже libfmt8.

**Comment by elfmz** [comment]
а если так сделать, то работает?
```
    IF(PACKAGE_DEPENDENCIES)
        SET(PACKAGE_DEPENDENCIES "${PACKAGE_DEPENDENCIES}, libfmt${fmt_VERSION_MAJOR}" PARENT_SCOPE)
    ELSE(PACKAGE_DEPENDENCIES)
        SET(PACKAGE_DEPENDENCIES "libfmt${fmt_VERSION_MAJOR}" PARENT_SCOPE)
    ENDIF(PACKAGE_DEPENDENCIES)

```

**Comment by cycleg** [comment]
Отлично! Только я бы пихнул наименование зависимости в отдельную переменную, чтобы выражение "libfmt${fmt_VERSION_MAJOR}" было ровно в одном месте.

**Comment by elfmz** [comment]
да тут вообще лучше весь этот IF(PACKAGE_DEPENDENCIES) ... заменить на некий ADD_PACKAGE_DEPENDENCY

**Comment by Arkady23** [comment]
Где взять deb-пакет, что бы установить Far2l на чистый Debian? А не на Ubuntu c её ошибкой сжатия в формат zst? Для Ubuntu есть здесь https://launchpad.net/~far2l-team/+archive/ubuntu/ppa
