### ISSUE TITLE
MultiArc went into an endless loop

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#1174]
on a file called `innua03.part01.rar`, while only the next volume, `innua03.part02.rar` was present in the directory, but not `part03`.

In `MergeArchive -> DllVolChange`.

MacOS, macports, `RARDLL` is defined.

**Comment by singalen** [comment]
I'm afraid it still loops for me. `DllVolChange` returns `true`, even though the file with the next volume doesn't exist.

**Comment by elfmz** [comment]
hm, now it should show dialog: 
![image](https://user-images.githubusercontent.com/20957349/148120038-f5ace852-32ea-4b7d-a443-97248a72a60a.png)

**Comment by singalen** [comment]
My bad. After a clean rebuild, it's fine.
