### ISSUE TITLE
Crash on Mac pasting text from CLion

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#1176]
On today's `master`, 9dfa5898.

Console:
```
OpenClipboard
ClipboardAccess: bad magic (0x650000006b)
```
Stack:
![Screen Shot 2022-01-03 at 23 58 49](https://user-images.githubusercontent.com/151199/148027377-2ae4269d-c54d-41c8-839e-079a83361bdd.png)
(goes into `if (hdr->magic != CAH_ALLOCED_MAGIC)` branch)

**Comment by elfmz** [comment]
Does it happen only with clion? And always? I tried copying some stuff from Safari - no repro.
Also - did you make clean before building updated build? Sometimes cmake doesn't get that some stuff must be rebuilt and strange things happen then..

**Comment by elfmz** [comment]
also ive did some change, very unsure if it will help, but check please (with clean rebuild)

**Comment by singalen** [comment]
No longer happens. Thank you!
