### ISSUE TITLE
DeduceCodepages: unknown locale 'C.UTF-8' in WSL

### ISSUE THREAD

**Issue by russiandesman** [elfmz/far2l#1185]
Each launch in WSL starts from Subj message.
Can we add ```if (IsLocaleMatches(lc, "C")) { return Codepages{866, 1251}; }``` to DeduceCodepages() ?
Or maybe {437, 1252}...

BRs,
Denis.

**Comment by elfmz** [comment]
can you tell result of `echo $LANG` ?

**Comment by russiandesman** [comment]
Sure. It is C.UTF-8 on wsl
on my Xubuntu it is en_US.UTF-8 and far2l does not cry there.

**Comment by russiandesman** [comment]
Thanks a lot!

**Comment by unxed** [comment]
@zerochka отпишитесь здесь про
```
Last login: Wed Jan 19 21:51:39 on ttys002
/usr/local/Cellar/far2l/HEAD-c0d057c/bin/far2l ; exit;
MacBook-Air-Elena-2:~ zero$ /usr/local/Cellar/far2l/HEAD-c0d057c/bin/far2l ; exit;
DeduceCodepages: unknown locale 'UTF-8' 
```
при запуске

**Comment by elfmz** [comment]
..also added UTF8 to exclusions

**Comment by zerochka** [comment]
А что писать? Так всегда было. Запускаю  /usr/local/bin/far2l ( который закреплен в DOC) 
он симлинк на собранный бинарник из brew
/usr/local/bin/far2l -> ../Cellar/far2l/HEAD-c0d057c/bin/far2l

**Comment by zerochka** [comment]
> can you tell result of `echo $LANG` ?

у меня в этом месте пустота
