### ISSUE TITLE
backend type in window header

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1188]
А то, что бэкенд в заголовке окна показывается только для случая TTY|F под WX, а в GNOME Terminal, скажем, не показывается — это баг или фича?

**Comment by elfmz** [comment]
У меня показывается. Это far2l запущенные на одной и той же системе? Если нет - может у одного из них не дефолтовый F9/Options/Interface/Far window title addons: ?

**Comment by unxed** [comment]
Пробовал в разных комбинациях. И на локальной в GNOME Terminal, и на удалённой в GNOME Terminal, и на удалённой изнутри локального far2l в GNOME Terminal.

Бекенд кажет только TTY|F, и только когда этот TTY|F внутри wx-версии. Во всех остальных случаях бекенд не показывает.

`%Ver %User@%Host` везде

**Comment by unxed** [comment]
![изображение](https://user-images.githubusercontent.com/1151423/149093561-3b863fc7-0a40-497d-88cb-c5c3f7f1e7f2.png)
![изображение](https://user-images.githubusercontent.com/1151423/149093587-e14f2a85-57cc-401c-b26c-6009902727a9.png)

**Comment by elfmz** [comment]
![image](https://user-images.githubusercontent.com/20957349/149093780-edb6d48e-d046-4f40-b20b-b9b97b9a6575.png)

**Comment by elfmz** [comment]
> `%Ver %User@%Host` везде

Ну так там еще должен быть %Backend :))
![image](https://user-images.githubusercontent.com/20957349/149094190-fe2bc5a8-0f4f-46e9-bf0e-027caf67e128.png)

**Comment by elfmz** [comment]
Там просто был момент когда дефолтовое значение настройки не содержало подстроки Backend, а когда я ее добавил - то имя ключа настройки решил не менять. Так что те кто сохранил старые дефолтовую настройку (тот момент был не оч длинным) остались без Backend'а..

**Comment by unxed** [comment]
Всё так. Спасибо! Класс.

А убирание ревизии гита из заголовка не затруднит отлов ошибок ли?

**Comment by elfmz** [comment]
Ревизия не показывается только если версия собрана из тэга версии, при билде из промежуточных не тегированных комитов - ревизия будет показываться. Это вобщемто уже довольно давно так - начиная с 499d7a3e43e253823f24685ace1975a4b6604c81
