### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by nlime** [elfmz/far2l#1189]
Good afternoon! When building a package, writes an error

Build: with make:
cmake -DUSEWX=yes -DCMAKE_BUILD_TYPE=Release ..
make -j$(nproc --all)

![far](https://user-images.githubusercontent.com/59861893/149123484-a352131b-6883-4428-84db-a0bf6d177798.png)

**Comment by unxed** [comment]
Could you please make with -j1 and provide more long build log?
