### ISSUE TITLE
NetRocks: потеря sftp-соединения и странное поведение после этого

### ISSUE THREAD

**Issue by Katarn** [elfmz/far2l#1191]
Версия far2l - свежая, с пылу с жару из git. Для начала скриншот настроек:

```
╔══════════════════ SFTP protocol options ═══════════════╗
║ Authentication:       Private key file path:           ║
║ ~/.ssh/id_rsa                                          ║
║ Compression:          No compression                   ║
║ [ ] Custom subsystem request/exec:                     ║
║                                                        ║
║ Max read block size, bytes:                   32768    ║
║ Max write block size, bytes:                  32768    ║
║ Automatically retry connect, times:           2        ║
║ Connection timeout, seconds:                  20       ║
║ [x] Enable TCP_NODELAY option                          ║
║ [ ] Enable TCP_QUICKACK option                         ║
║ [ ] Use OpenSSH configuration files                    ║
╟────────────────────────────────────────────────────────╢
║                     { Ok } [ Cancel ]                  ║
╚════════════════════════════════════════════════════════╝
```

Теперь как воспроизвести:

1. Захожу на сервер.
2. Создаю файл с любым именем (Shift+F4).
3. Сохраняю (F2).
4. Ввожу любой текст в качестве содержимого файла.
5. Жду минут 5.
6. Нажимаю F2 чтобы его сохранить.
7. Ловлю следующее:

```
╔═══════════════════ Make directory error ════════════════════╗
║ Socket error: disconnected (-1)                             ║
║ Failed object: /var                                         ║
║ Failed site:   <sitename.ru>                                ║
╟─────────────────────────────────────────────────────────────╢
║ [ ] Remember my choice for current operation                ║
╟─────────────────────────────────────────────────────────────╢
║                { Retry } [ Skip ] [ Cancel ]                ║
╚═════════════════════════════════════════════════════════════╝
```

![изображение](https://user-images.githubusercontent.com/6339978/149222521-be7c14b3-56f6-48e2-ba23-eef52b285720.png)

И кроме того, почему Make directory? Внимание на каталог: `/var`, а я создавал файл в `/var/www`.

Пробую нажать на Retry, ожидая что far2l хотя бы автоматизирует реконнект и снова попробует сохранить файл. По крайней мере NetBox на винде так и поступает в редких случаях потери соединения.

```
╔═══════════════════ Make directory error ════════════════════╗
║ SFTP server: Failure (-1)                                   ║
║ Failed object: /var                                         ║
║ Failed site:   <sitename.ru>                                ║
╟─────────────────────────────────────────────────────────────╢
║ [ ] Remember my choice for current operation                ║
╟─────────────────────────────────────────────────────────────╢
║                { Retry } [ Skip ] [ Cancel ]                ║
╚═════════════════════════════════════════════════════════════╝
```

![изображение](https://user-images.githubusercontent.com/6339978/149222620-36400a24-8dda-4a99-8655-309b2b3c74f4.png)

Пробую ещё разок нажать по Retry. Получаю то же самое - Failure (-1), далее можно бесконечное количество раз нажимать на Retry, поведение зацикливается.

Если нажать Cancel и выйти из редактора без сохранения, тут же получу:

```
╔═══════════════════ Enum directory error ════════════════════╗
║ Socket error: disconnected                                  ║
║ Failed object: /var/www                                     ║
║ Failed site:   <sitename.ru>                                ║
╟─────────────────────────────────────────────────────────────╢
║ [ ] Remember my choice for current operation                ║
╟─────────────────────────────────────────────────────────────╢
║                { Retry } [ Skip ] [ Cancel ]                ║
╚═════════════════════════════════════════════════════════════╝
```

Тут каталог уже верно указан.

Я погуглил, настройки `TCP_NODELAY` и `TCP_QUICKACK` вроде как не относятся к поддержанию активным соединения. С этим же сервером в виндовом Far и NetBox соединение может держаться долго, часами, так что думаю на это влияют настройки клиента, не сервера. Но чего-то подходящего в настройках NetRocks не нашёл. Help!! ПАМАГИТИ!

**Comment by elfmz** [comment]
а ща?

**Comment by Katarn** [comment]
А ща я нажал на Retry и файл сохранился. Но прежде чем я нажал, это было ровно то же диалоговое окно с ошибкой с неверным каталогом, неверной проблемой (Make directory error). И я ожидал, что коннект будет поддерживаться, а не теряться. В NetBox для этого была отдельная настройка посылания сетевых пакетов раз в промежуток времени.

**Comment by elfmz** [comment]
Проблема как раз верная - он перед тем как файл записат, убеждается что директория куда файл пишется существует. Причем все директории пути, начиная с первого уровня.

**Comment by Katarn** [comment]
В сохранения по сети, логичнее же было бы проверять, что соединение активно, перед тем как начать проверять на пути?

**Comment by elfmz** [comment]
а как его проверишь, кроме того как сделать чтонить

**Comment by elfmz** [comment]
keep alive валидная фича, можно сделать

**Comment by Katarn** [comment]
> а как его проверишь, кроме того как сделать чтонить

Можно сделать листинг каталога, куда сохраняется файл. Тогда, если коннект прерван, получим, как на втором скрине: `Socket error: disconnected (-1)`.

Если получаем disconnected, то предлагаем сначала восстановить соединение - как более релевантный текст сообщения об ошибке, и повторяем попытку сохранения после этого.

**Comment by elfmz** [comment]
Добавил keepalive (в настройках подключения внизу - поставить ненулевое значение секунд), проверяйте

**Comment by Katarn** [comment]
Работает, да. Спасибо. Проверку на потерю соединения делать не будете? Из открытых вопросов по этому ишью только это и осталось.

**Comment by elfmz** [comment]
Так его нечем особо проверить кроме как попробовать чтото сделать, а каждый раз пробовать - на производительность может повлиять. Да и вообще раз уж произошла ошибка - значит надо ее показать.
Ну раз в целом проблема решена, то закрываю...
