### ISSUE TITLE
far2l ukr translate

### ISSUE THREAD

**Issue by cappelikan** [elfmz/far2l#1192]
[far2lukr.zip](https://github.com/elfmz/far2l/files/7860293/far2lukr.zip)

**Comment by elfmz** [comment]
Так тут только хелп. Основной интерфейс переводится через farlang.templ.m4, без добавки туда украинского один лишь хелп выбираться не будет. Или добавить пока украинский в farlang.templ.m4 но в виде русского/английского, а вы переведете?

**Comment by cappelikan** [comment]
[far2lukr.zip](https://github.com/elfmz/far2l/files/7875868/far2lukr.zip)
Посылаю полный Украинский перевод как помощь так и основной , огромная просьба просмотрите текст Ю может быть ряд терминов надо укоротить ?

**Comment by elfmz** [comment]
вмержил, там были проблемы - в основном отсутствующие 'переводы' пустых строк что пофиксилось тривиально, но было еще парочка пропущенных украинских переводов - я там подставил русские строки с upd: префиксом, так как в украинском я не силен

**Comment by cappelikan** [comment]
А можно ссылки на пропущенные ? я бы их подправил , и такой вопрос а есть
ли какой нибудь инструмент для редактирования m4 ну напримаер типа poedit ?


нд, 16 січ. 2022 р. о 19:24 elfmz ***@***.***> пише:

**Comment by elfmz** [comment]
upd:"Дальше"
upd:"&Средний                  LCtrl-2"
upd:"Этот модуль требует FAR более высокой версии" 
upd:"КодСтр"

**Comment by cappelikan** [comment]
upd:"Далі"
upd:"&Середній LCtrl-2"
upd:"Цей модуль потребує FAR більш високої версії"
upd:"КодСтор"

пн, 17 січ. 2022 р. о 01:24 elfmz ***@***.***> пише:

**Comment by elfmz** [comment]
Тут добавилась кой какая функциональность, в связи с чем появились новые непереведенные вещи, вот тут хелп - https://github.com/elfmz/far2l/commit/3c780ca2293c14e9cd0c4454266f87b636fa14d8 а тут интерфейс - https://github.com/elfmz/far2l/commit/027016eb33e9adeefa3eb20767c09d326f08f0f4. Я добавил все новое в украинский в русском виде.
Еще добавился файл xlat.ini который определяет транслитерацию пока только для русской раскладки, туда можно добавить и украинскую если нужно.
