### ISSUE TITLE
mention in readme different paste behavior of differen key combinatons in tty mode

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1193]
Pawel,
День добрый. В консольной версии при копипасте кода из броузера в новый файл, текст вставляется одной строкой, в графической версии и в mc - все ок. Есть какой-то секрет?

Иван,
Вы Ctrl+V используете, или Shift+Ins? там есть разница. в одном случае терминалка имитирует ввод с клавиатуры, в другом — сам far делает paste

Pawel,
да, похоже я делаю shift ins и это работает неправильно, а ctrl-v норм. спасибо 👍

Alexander,
Интересно. Такое бы внутри справки по F1 отметить

**Comment by elfmz** [comment]
Вообще это баг, вызванный тем что TTYX добавляет нажатый модификатор SHIFT ко всем типа нажатым кнопкам. Ну а SHIFT+Enter в редакторе работает совсем не так как простой Enter..
Добавил костылек..

**Comment by unxed** [comment]
> текст вставляется одной строкой

Это поправлено.

А вот то, что есть два Paste, терминалки и самого фара, и правда надо куда-то документировать, только вот куда?

**Comment by akruphi** [comment]
Документировано в середине многобуквенного (и из-за этого плохочитаемого) раздела помощи "FAR2L features - Getting Started" / "Особенности FAR2L - начало работы".

Это issue наверное можно закрывать.
