### ISSUE TITLE
please add another putty fork with far2l support to readme

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1195]
putty-nd

https://sourceforge.net/p/putty-nd/feature-requests/36/

(not sure if extensions support are added to that fork mainline branch, so its better to link to this issue with far2l-supporting .exe)

**Comment by dvlom99** [comment]
Повторно скачал, putty_nd7.10.zip. Дата, правда не очень свежая - 2021-08-07, но внутри есть слова про доработки касательно far2l и галочки в настройках. 

Проверил еще раз:
1. запускаю SSH-сессию в linux Mint, в ней стартую - far2l
2. по Shift-F4 создаю файл, в нем набираю строку 12345678901234567890
3. выделяю все 20 символов, нажимаю Ctrl-Ins и перемещаюсь на новую строку
4. по нажатию Shift-Ins в новую строку вставляется 2 символа - 12
5. переключаюсь в Windows и в Far-е вставляю содержимое буфера обмена в строку (последний символ - двойная кавычка) - 1256903478"

Что касается "Портит настройки SSH-порта оригинального PUTTY", то после запуска и завершения putty-nd, все мои настроенные сессии в оригинальном PUTTY получили порт - 22, хотя если запустить снова putty-nd, то там будут те, которые должны, отличные от 22-го.

**Comment by dvlom99** [comment]
А вот если скачать  отсюда - https://sourceforge.net/p/putty-nd/feature-requests/36/#2e84, то вроде буфер обмена работает нормально, без этих глюков. Но эта сборка появилась недавно. Я проверял выложенную в том треде раньше, и мне не удалось запустить программу, она сразу падала. Поэтому взял смотреть релиз.

Резюмирую, был не совсем прав. С порчей настроек обидно, но к Вам это отношения не имеет.

**Comment by elfmz** [comment]
Так я в целом не очень понимаю, оно вмержено или просто типа ПР висит? Если второе - надо подождать пока вмержат)

**Comment by unxed** [comment]
уже в readme
