### ISSUE TITLE
slow colorer background parsing

### ISSUE THREAD

**Issue by lieff** [elfmz/far2l#12]
При редактировании больших файлов вроде https://github.com/vurtun/nuklear/blob/master/nuklear.h , если сразу спозиционироваться в конец, можно ждать парсинга colorer вечно.
Предлагаю такое решение: https://github.com/lieff/far2l/commit/b712007a54a890a27996968c6489eee5cb876f87
Это быстро увеличивает объем парсинга до 10000 строк\итерацию. Время ожидания на nuklear.h сокращается до ~5 секунд. Если во время не завершенного процесса сдвинуть курсор, можно заметить залипание, но оно не большое.

**Comment by elfmz** [comment]
хм а тормозить не начинает ниче? я конечно понимаю что видимо этот код писался гденить в районе 2010го.. но требовать для работы минимум i5 не хотелось бы.. 
погоняю дома фикс на виртуалке там будет видно.. Вообще правильно было бы наверное этот time делать адаптивным, засекая иногда время работы clock'ом и уменьшая/увеличивая time, но это наверное слишком сложно..

**Comment by lieff** [comment]
Да, я тоже об этом подумал, правильно будет точно загрузить одно ядро. Иначе слишком мощный проц будет простаивать, увеличивая время ожидания, а слишком медленный приведет к большим залипам при нажатии клавиш.
Просто тут "idle" таск реализован в основном цикле, был бы отдельный тред, проблемы бы небыло.
Пока как воркароунд можно подобрать число более подходящее, на винде итерации видимо случались гораздо чаще, вот 100 теперь и не подходит.

**Comment by elfmz** [comment]
хмхмхм.. это уже интереснее, я думал оно и в винде так же было, а хочется чтоб было лучше)
значит нуна фиксить какой то баг..
Навскидку: в colorer' и в самом FAR местами юзается clock(), и судя по коду считается авторы полагались на то что он возвращает всегда миллисекунды. А он возвращает 1/CLOCKS_PER_SEC, причем в студии CLOCKS_PER_SEC 1000, а в линуксе - обычно 1000000

**Comment by lieff** [comment]
Ну там 100\итерация это максиум, а это мало как что ни рассчитывай. Sleep то там нет, а частота итераций снизилась, это основная проблема со старым лимитом.

**Comment by elfmz** [comment]
полагаю у этого кода уши растут из генерируемого far'ом KEY_IDLE, а в фаре слипов полно

**Comment by lieff** [comment]
Да, меньше 10мс не получится, если только там нет алгоритма компенсации вроде 1 раз 10мс, второй раз 0мс -> 5ms. В любом случае так мало спать и часто переключать контексты вредно, то то виндовый far2 под wine жрет проц ощутимо.
Думаю лимит 100 в любом случае прдется поднять, но возможно не так сильно, если разобраться с часторой итераций. Скажем более 60 итераций\сек не нужно для нормальной интерактивности и чтобы не грузить проц. Значит старый лимит даст 600строк\с что мало.

**Comment by elfmz** [comment]
ну да, но по любому гдето тут еще мой баг зарыт, раз появилась такая разница с частотой idle ивентов

**Comment by elfmz** [comment]
Вощем... Проверил у себя - действительно, ProcessEditorInputW с KEY_IDLE под виндой фаром раз в 10 чаще чем в линуксовом порте. Стал копать.. иии. Вкратце - это подводный граблебаг FAR'а:)
Подробнее - дело действительно в перекоцанных мною Sleep(1) на Sleep(10). Если вернуть Sleep(1) - то и под линуксом приходит все ок. Стало интересно, как же оно в винде работало, т.к. time slice в винде точно >=10msec, а значит спать в винде должно тоже по 10 мс, даже когда просишь 1.
Но по факту спит оно таки по одной мс. "Хм", подумал я, и закрыл все прилаги, кроме подопытного фара и еще кое чего по-мелочи. И тада - в виндовом фаре KEY_IDLE тоже стал приходить так же редко как в линуксовом.
Разгадка - есть такая ф-я - timeBeginPeriod. Вызвав ее например timeBeginPeriod(1) можно временно уменшить time slice шедулера до 1мсек. Временно - это значит до того как вызовешь timeEndPeriod(1) или как процесс выйдет и система сама все отменит, т.к. меньшее разрешение шедулера ухудшает его эффективность. И поэтому мсдн там в ремарках рекомендует минимизировать использование этой штуки.
Но поскольку рукожопость в мире процветает, то в зоопарке запущенных программ найдется ктото кому захочется мерять время с разрешением в 1мсек постоянно, потому в FAR'е, который запущен в среде зоопарка KEY_IDLE  приходят в 10 раз чаще чем в FAR'е, запущенном на чистой системе.
А я между прочим и раньше замечал что колорер иногда странно тупит с перерисовкой, но не придавал этому значения. Теперь все встало на свои места.

**Comment by lieff** [comment]
Чтобы сделать пул реквест, мне надо снова отменить подключение netbox и кореженье WinPort, гитхаб как оказалось не поддерживает cherry-pick) я собственно потому и сделал issue со ссылкой на коммит, я не сразу пул реквест.

**Comment by elfmz** [comment]
ну я думаю это не к спеху..
кстати насчет кореженья - я думаю я таки порасставляю потом по нетбоксу макрос WINPORT, т.к. уж больно велик риск конфликта символов - больно вкусные названия у виндовых функций, если в процесс загрузиться какая нить библиотека которая экпортирует чтонить с таким же именем - будут крайне неприятные проблемы..

**Comment by lieff** [comment]
по идее -Wl,--version-script=exports.def сделает так что из so гарантированно будут торчать тольео символы из .def, даже без -fvisibility=hidden
Файл следеюзего вида:
```
     {
    global:
      JNI_*;
      Java_*;
      local: *;
    };
```
Из so тогда будут торчать тольео JNI_* и Java_*

**Comment by elfmz** [comment]
не, я про то что если в FAR будет загружена .so-шка не нами скомпиленная.. а так, из системы чтото. И если она будет экспортировать, скажем, CloseHandle и будет еще какаято другая левая .so, которая будет линковаться на этот CloseHandle. Так вот, загрузившись в far2l, который будет так же экспортировать CloseHandle - та вторая будет юзать CloseHandle из far2l. Так уж в линуксе лоадер работает, это в винде (и OSX с ее mach-o) точно указано из какой длл должен прилинковаться каждый конкретный символ..

**Comment by lieff** [comment]
А netbox не будет линковаться с CloseHandle, он у него будет внутри статически слинкован и наружу не торчать. И far2l не нужно CloseHandle экспортировать. Так что пока экземпляры WinPort полностью независимы и не экспортируются все должно быть ок. Главное не передать handle из far2l в плагин и не сделать на нем CloseHandle() в плагине (между копиями WinPort).

**Comment by elfmz** [comment]
Так вот это вот неправильно. Во-первых каждому бинарнику таскать с собой общий код - не комильфо. Во-вторых проблемы не только с хэндлами. Первое на чем вылезут грабли - консольные API не будут работать в плагинах (а они их юзают частенько напрямую), потому что инстанс консоли только один - у фара. Плагин может конечно тогда инициализировать свою консоль - тогда вылезет еще одно окошко, с его личной консолью :)

**Comment by lieff** [comment]
Ну да, потому netbox еще далеко не готов, надо переводить часть winapi на те функции что far2l передает в таблице функций, другую часть на нативный linux, и оставшееся на, то чем можно пользоваться из плагинов, проблем с путаньем линковки между so вроде на данном этапе нет.

**Comment by elfmz** [comment]
Вощем мы посовещались и я [решил](https://github.com/elfmz/far2l/commit/3432db1cbfd882514e36d98a8b07afa4983e0847) :)
Немного громозко, зато надежно. И не нужно переколбашивать ни netbox, ни WinPort.

**Comment by elfmz** [comment]
И по поводу сабжа - тоже вкомитил [фикс ](https://github.com/elfmz/far2l/commit/09678c964bcbcb3e5bb4eac8d1c367b23e23df21)почти как ваш только ограничение time 1000, а не 10000. Соображения такие - раз замедлилось в 10 раз, то и лимит нужно поднять примерно так же.

**Comment by elfmz** [comment]
возвращаясь к нетбоксу - попробовал собрать и обнаружил пару проблем, возможно вы не заметили: хедеры в PluginSDK были не очень совместимые с тем что в far2l + по мелочи - добавил копирование .lng И проверку чтоб не падало в одном месте) теперь оно у меня тоже собралось и даже меню появилось.. но при попытке добавить сервер упало(

**Comment by elfmz** [comment]
завел issue для "всего": https://github.com/elfmz/far2l/issues/14
а эту закрою ибо зафикшено

**Comment by lieff** [comment]
Да, этот лимит тоже норм, на nuklear.h у меня 7 секунд.
Netbox у меня сервера добавняет, виснит при коннекте (как пока и должно быть). Только в поле private key file мусор, может поэтому крашится.
