### ISSUE TITLE
some keyboard shortcuts not working in panels on Gnome

### ISSUE THREAD

**Issue by v6flk1** [elfmz/far2l#1200]
shortcuts like Alt+F7 (Find), Alt+F8 (History) not working on Gnome. Pressing Alt+F7, for example, works as "move window" (default Gnome shortcut as i know )

Far2l builded with script "make_far2l_deb.sh". WX as backend
Gnome as GUI
Debian Bullseye

**Comment by elfmz** [comment]
There're 3 options available to resolve such problems:
1) Release shortcuts in gnome settings
2) Use Win+F7 instead of Alt+F7
3) F9/Options/Interface/Exclusively handle hotkeys that include: - check some modifiers that far2l will handle exclusively. I prefer setting right modifiers for that

**Comment by v6flk1** [comment]
Modification of Opt.2 work. Pressing Alt+Win+F7/F8 works as expected!

**Comment by elfmz** [comment]
dont need Alt in this case, just single Win treated as Alt, but together will work too.
