### ISSUE TITLE
Porting plugins written in Pascal

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1205]
Many Far Manager plugins were written in Pascal (like those https://github.com/MaxRusov/far-plugins). To port them to far2l, we need to port, build and run helloworld plugin first.

After applying some tricks I manged to build HelloWorld plugin from Far 2 sources tree with Free Pascal compiler (see https://github.com/unxed/far2l-fpc-helloworld). Unfortunately, it segfaults on start.

Maybe I am missing something. Any help is appreciated.

**Comment by elfmz** [comment]
at least, current far2l plugin-wide.h is not the same as Windows's one, i.e. need to adjust PluginW.pas to reflect all the changes in structs layout etc made in far2l.

**Comment by unxed** [comment]
thanks, will try to

btw, it segfaults at
```
  PluginMenuStrings[0]:= GetMsg(MTitle);
  pi.PluginMenuStrings:= @PluginMenuStrings;
```

with this two lines commented out, it at least loads normally

**Comment by unxed** [comment]
Странная штука. Если оно падает на GetMsg, логично предположить, что либо апи этой функции поменялся (но нет), либо в PluginStartupInfo какие-то изменения произошли (но нет).

**Comment by unxed** [comment]
Strange thing. If it falls on GetMsg, it is logical to assume that either the api of this function has changed (but it was not), or some changes have occurred in PluginStartupInfo (but they don't).

Updated PluginW.pas, still segfaults on GetMsg, stange thing.

**Comment by unxed** [comment]
Finally [made HelloWorld build and run](https://github.com/unxed/far2l-fpc-helloworld/commit/692e68a03e32dca9013e4dd4f913d9ef4f47555c).

WideChar is 16 bit in Free Pascal Compiler on Linux x16, so had to switch to UCS4Char. Also had to disable $PACKRECORDS compiler directive as it caused segfaults.

**Comment by unxed** [comment]
Ещё один вопрос нарисовался. Я тут пробую -mb-плагин сделать (а то уж больно всё грустно во фрипаскале с utf32, как выяснилось), а туда, в отличие от -wide, не приходят адреса функций в PluginStartupInfo. То есть, натурально, ModuleName видно, ModuleNumber видно, а в GetMsg, например — одни нули. И во всех остальных местах, где адреса функций должны лежать — тоже нули.

Отчего такое может быть?

**Comment by unxed** [comment]
Так, с этим тоже разобрался, MAX_PATH надо было поставить в 4096 и в паре мест Integer на IntPtr поменять. Теперь всё приходит ровно, однако всё равно вылетает, буду разбираться дальше.

**Comment by unxed** [comment]
Made mb version also as UTF32 is almost not supported by Free Pascal
