### ISSUE TITLE
unpacking some zip archives fails

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#121]
[list_ok_unpack_fails.zip](https://github.com/elfmz/far2l/files/500939/list_ok_unpack_fails.zip)
[test.zip](https://github.com/elfmz/far2l/files/500942/test.zip)
found the source of problem. see:

```
/home/unxed$ unzip -o  /home/unxed/Downloads/list_ok_unpack_fails.zip "проверка/*.*" -d . 
TIP: If you feel stuck - use Ctrl+Alt+C to terminate everything in this shell.            
Archive:  /home/unxed/Downloads/list_ok_unpack_fails.zip                                  
caution: filename not matched:  проверка/*.*                                              
/home/unxed$ unzip -o  /home/unxed/Downloads/list_ok_unpack_fails.zip "проверка/*" -d .   
Archive:  /home/unxed/Downloads/list_ok_unpack_fails.zip                                  
```

`*.*` does not mean "any file" on linux, so unzip can not find anything matching `*.*` in empty folder and skips extracting it.

`*.*` should be replaced by `*` on linux I guess

**Comment by unxed** [comment]
Changing "all files" mask in zip.cpp to "*" fixes this for test.zip, but the problem stil persists with list_ok_unpack_fails.zip

**Comment by unxed** [comment]
btw, I'm using unzip from
sudo add-apt-repository ppa:frol/zip-i18n
it goes well with 866 zip files, but seem to fail with utf8 ones

unzip bundled with ubuntu/mint works the opposite way
as I see, neither use platform flag to detect encoding (as multiarc does)

**Comment by unxed** [comment]
upd: unzip bundled with ubuntu also does show this error on _some_ archives like this one
[23-10-2012-b-fasi-eaep.zip](https://github.com/elfmz/far2l/files/501214/23-10-2012-b-fasi-eaep.zip)

**Comment by unxed** [comment]
related info
https://github.com/mate-desktop/engrampa/issues/5
http://linuxmd.net/forum/komandnaya-stroka-terminal/473-unzip-6-10c

**Comment by elfmz** [comment]
list_ok_unpack_fails.zip works fine (after *.* -> * change) with following unzip:

> user@ubuntu:~$ unzip
> UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.
> 
> Usage: unzip [-Z] [-opts[modifiers]] file[.zip] [list] [-x xlist] [-d exdir]
>   Default action is to extract files in list, except those in xlist, to exdir;
>   file[.zip] may be a wildcard.  -Z => ZipInfo mode ("unzip -Z" for usage).

I remembered that had some problems with some unzip (some files were not extracted - stupidly bypassed in list, even with english letters) then I installed some another zip package (that also has unzip utility :) ) and it worked much better

**Comment by unxed** [comment]
as I have discovered during some investigations, zip has worst i18n-support popular archiver format ever had. mash of non-compatible implementations, most assuming that there can be only one locale, only one code page, only one encoding of file names and only one method of storing file names inside archive.

giving it up for now, feeling a little bit tierd from all that stuff)
