### ISSUE TITLE
editor bug if free space is exhausted

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1238]
Bug in the editor: if storage device runs out of free space, when saving the file, the old version is deleted, but the new one is not saved.

**Comment by elfmz** [comment]
please check if approach tried at branch fileedit-avoid-data-loss works better for you

**Comment by unxed** [comment]
ой, сейчас нет такого диска, на котором бы место заканчивалось, под рукой, увы. я это словил давным-давно, записал в текстовой файлик чтобы не забыть, и только сейчас добрался до того чтобы перегнать его в тикет

**Comment by elfmz** [comment]
ну поскольку кой какие меры предприняты то закрываю...

**Comment by unxed** [comment]
лайк!

если снова всплывёт, новый тикет запилю
