### ISSUE TITLE
Редактор: пропадающие строки

### ISSUE THREAD

**Issue by volth** [elfmz/far2l#124]
Если вот [этот файл](https://gist.githubusercontent.com/volth/6a8cc22dbbb15d37f8e47adb03a0c04e/raw/0e7c2bc47725c923d43c68b181c347438c302f6c/farbug.txt) открыть в редакторе Far2L (по F4), пятая и шестая строки окажутся пустыми.

От включения/выключения колорера не зависит, во вьювере (по F3) бага нет.

**Comment by invy** [comment]
Подтверждаю, такое попадалось.
