### ISSUE TITLE
autocomplete works incorrectly with the piped commands

### ISSUE THREAD

**Issue by ivanshatsky** [elfmz/far2l#1245]
Looks like when a piped command is being typed at the command prompt, it should be processed by `VTCompletor` in some special way. As of now the following behavior artifacts are observed:

1. No space between the pipe char and the beginning of the next command:
![pipe_nospace](https://user-images.githubusercontent.com/17809980/153496685-058e6fa1-426a-4267-879b-e9e281a7fcb6.png)
![pipe_nospace2](https://user-images.githubusercontent.com/17809980/153496709-1b6d6ef5-e8eb-49df-b264-0b3e67884154.png)
Notice the
    - duplication of the typed command prefix;
    - an extra `ylist`/`yumlist` item (probably related to the first `yum list available` command);
    - duplication of `yyum`/`yumyum` items (probably related to the first command being `yum ... `).

2. A space present between the pipe char and the beginning of the next command:
![pipe_space](https://user-images.githubusercontent.com/17809980/153497422-495db695-fdbe-4120-a9e2-c19ec8ac66af.png)
![pipe_space2](https://user-images.githubusercontent.com/17809980/153497437-52db217d-77c3-4cf3-bc24-8a4717afecb6.png)
The typed command prefix not gets duplicated, however there are two extra items in the menu (`yavailable|`, `ylist` / `yumavailable|`, `yumlist`) and the `yum` item still gets duplicated.

Here are `vtc.log` files for all the four examples:
[vtc.log.nospace1.gz](https://github.com/elfmz/far2l/files/8044342/vtc.log.nospace1.gz)
[vtc.log.nospace2.gz](https://github.com/elfmz/far2l/files/8044343/vtc.log.nospace2.gz)
[vtc.log.space1.gz](https://github.com/elfmz/far2l/files/8044344/vtc.log.space1.gz)
[vtc.log.space2.gz](https://github.com/elfmz/far2l/files/8044345/vtc.log.space2.gz)

**Comment by elfmz** [comment]
check now for any remained issues pls..

**Comment by ivanshatsky** [comment]
Everything seems ok now, but...
Since the `yum` command is also available, shouldn't it be present in the menu too?
Just to differ from the situation when all the other menu items are available as the external commands, but `yum` itself is not?
![image](https://user-images.githubusercontent.com/17809980/153780268-688d38eb-7b6d-412f-934a-e04359edb25d.png)

**Comment by ivanshatsky** [comment]
@elfmz Digging further into this. I tried to check if I've been able to do it myself. Looks like I was completely misunderstand the whole logic. Taken my previous example, the `yum` item __is__ actually present in the "possibilities" menu, yet not shown due to completely other reasons (exact match with the input string), right? Ok, what if I still want to see if the exact `yum` option is available as a standalone command or not? If I want to see if I ever used an exact command typed at the command line or not (i.e. is it present at the command history or not)? I think this can be implemented with the additional option in the "Autocompletion options", say something like "Show exact match". What do you think about it?

Meanwhile I think the issue about piped commands should be considered as completed and closed. Maybe I should open another issue/feature request for this additional option.
