### ISSUE TITLE
Function Message places message lines on buttons

### ISSUE THREAD

**Issue by shmuz** [elfmz/far2l#1248]
На картинке внизу результат вызова Message. Переданные параметры: ItemsNumber=37, ButtonsNumber=6.
На картинке видно, что 27-я и далее строки сообщения уже попадают на кнопки.
Но ведь программа знает по параметрам, что кнопки начинаются с 32-й строки.
Предлагаю отбрасывать те строки, которые не влезают на экран, а не помещать их на кнопки.
На кнопки в данном примере нужно помещать строки, начиная от 32-й.

![Screenshot](https://user-images.githubusercontent.com/344558/153730041-8918d750-30d5-4ce8-b803-d534c6a393c6.png)

**Comment by elfmz** [comment]
Забавно, для воспроизводства бага я вставил такой код и у меня фар стал падать от него:
```
LPCWSTR items[] = {L"XXX1", L"XXX2", L"XXX3", L"XXX4", L"XXX5", L"XXX6", L"XXX7", L"XXX8",
		L"XXX9", L"XXX10", L"XXX11",L"XXX12",L"XXX13",L"XXX14",L"XXX15",L"XXX16",
		L"XXX17", L"XXX18", L"XXX19",L"XXX20",L"XXX21",L"XXX22",L"XXX23",L"XXX24",
		L"XXX25", L"XXX26", L"XXX27",L"XXX28",L"XXX29",L"XXX30",L"XXX31",L"XXX32",
		L"XXX33", L"XXX34", L"XXX35",L"XXX36",L"XXX37",L"XXX38",L"XXX39",L"XXX40"};
Message(MSG_WARNING,6, L"title", items, 40); 
```
крэш пофиксил, но после этого все еще именно в таком виде проблема не воспроизвелась - просто кнопки стали не видны так как оказались за экраном внизу. Для этого я таки сделал воркэраунд - теперь лишние первые (так проще) строки обрезаются чтоб все влазило на экран, но поскольку проблема у меня выглядела не так как у вас, то я не уверен что пофиксил то что надо..

**Comment by shmuz** [comment]
Насколько мне помнится, в Фаре внутри есть несколько вариантов ф-ции Message, отличающихся набором параметров (благо C++позволяет). Вы по-видимому тестировали один из них. Я же использую тот единственый вариант, который вынесен в API плагинов, и у него сигнатура отличается от той, которую вы показали.
На том варианте, что вызывается из плагинов, поведение именно такое, как я описал в начальном сообщении.

Лирическое отступление:
Если вы поставите себе пакет луафар из моей репозитории, все тестирования, связанные с API плагинов, упростятся на порядок, поскольку будет исключён этап компиляции. Естественно, если потребуется, окажу любую помощь.

**Comment by shmuz** [comment]
Сейчас поигрался с Message дополнительно, там видимо не один баг, а два или больше. Причём тупо связанные с арифметикой.

**Comment by elfmz** [comment]
Так то компиляция это не сложно, одна команда - собрать и запустить выглядит так: `make -j5 && ./install/far2l`
Функция там одна общая, просто имеет множество врапперов, которые стоит причесать. Плюс возможны ньюансы изза длины строк, а не только их количества.
Так а после моего ченжа с вашей проблемой никаких изменений не произошло.

**Comment by shmuz** [comment]
Если изменения делаются в Фаре, без компиляции не обойтись. Но я говорил о другом: о тестировании.
Например, хотим посмотреть поведение ф-ции Message, Я могу легко проверять её поведение с различными комбинациями количества строк, длины строк, количества кнопок и т.д. без единой компиляции.

А насчёт того, что изменений не произошло, это вопрос или утверждение? Уже можно проверять?

**Comment by elfmz** [comment]
Нужно проверять)

**Comment by elfmz** [comment]
Если проблема осталась, просьба накопипастить все строки которые выводятся, мне таки проще в плюсовом коде дебажить)

**Comment by shmuz** [comment]
Пока только собрал Фар, есть вопросы:
1. Почему-то по окончанию сборки Фар автоматически запустился  - так должно быть?
2. Когда я закрыл его по F10, в терминале появилось `Segmentation fault (core dumped)`

**Comment by elfmz** [comment]
Ну если вы собирали его с моей командой вышеуказанной `make -j5 && ./install/far2l` то она именно что собирает и потом запускает.
Segmentation fault - этого не должно быть - значит чтото упало при закрытии (у меня это не воспроизводится). Однако давайте по порядку, что там теперь с Message() ?

**Comment by shmuz** [comment]
Если по порядку, то вот картинка. Видим, что при количестве кнопок больше одной, проблема осталась.

![Clipboard](https://user-images.githubusercontent.com/344558/153869348-77ba5f57-bf8b-4c0f-8e3b-96e754e2165e.png)

**Comment by elfmz** [comment]
попробуйте закоментить эту строку - https://github.com/elfmz/far2l/blob/master/far2l/src/plug/plugapi.cpp#L1321

**Comment by shmuz** [comment]
Стало нормально, т.е так как я хотел.

**Comment by shmuz** [comment]
И всё-таки взвесьте возможность установки моего пакета. Там есть полезные утилиты, например макро-браузер, который покрывает бОльшую часть возможностей плагина MacroView, отсутствующего в far2l.

**Comment by elfmz** [comment]
Ну, просто как пользователю, мне нужна программа, а не IDE. А как программиста, меня С++ устраивает :)

**Comment by elfmz** [comment]
А что касается segment violation на выходе, то надо сделать так - запустить far2l под gdb написать в gdb run, спровоцировать крэш, и когда в gdb появится чтото типа поймали SIGSEGV за хвост - то надо там (в gdb) написать команду bt

**Comment by shmuz** [comment]
@unxed , у меня нет цели любыми путями уговорить людей устанавливать мой пакет. Он будет развиваться и будет успешным в любом случае (если здоровье не подведёт).

@elfmz , хозяин-барин, больше к вам с подобным предложением не обращаюсь.
По поводу segment violation - больше не повторялось.

**Comment by elfmz** [comment]
Да я не против луа вообще в принципе, как и не против питона) Пусть цветут 100 цветов, или как оно там.
Но я против массивной интеграции 'мимо' стандартного плагинового API. Но опять же, если есть объективные причины расширять этот апи - никаких проблем.
В 3м фаре как я понимаю когда-то было принято концептуальное решение заморозить весь нативный функционал и неограниченно выставить его в распоряжении скриптов. Подозреваю, что это сильно связало руки разработчикам собственно ядра - ведь теперь на каждое изменение раскладки какого нить диалога надо смотреть какие скрипты это сломает.

**Comment by shmuz** [comment]
Нет, никакого концептуального решения в разработке Фар3 не было. Знаю, о чём говорю, как один из активных разработчиков Фар3. А что было - решение заменить макроязык на Lua.

Далее - разработчики Фар3 могут свободно менять любые диалоги и вообще всё, что угодно, без всякой оглядки на скрипты. Что они не могут - это менять API плагинов, но ведь при этом сломаются все плагины, а не только луафар.

**Comment by unxed** [comment]
Я вот могу сказать, что меня удерживает от того, чтобы начать активно пользоваться: отсутствие сборки через cmake. Обычно плагин просто кладёшь в папку с исходниками far2l, добавляешь в `CMakeLists.txt` строчку типа `add_subdirectory (папка_плагина)`, и всё, он у тебя собирается вместе со всеми, просто и понятно.

Я бы, кстати, помог тестировать сборку с помощью cmake, если бы работа в этом направлении началась.

**Comment by elfmz** [comment]
Ну far2l поначалу тоже мэйкфайлами собирался, cmake потом добавили.

**Comment by shmuz** [comment]
> Лишние движения. Да ещё и три вместо одного

Ну три - это было раньше. А теперь достаточно из папки `_luafar_` запустить `make` без параметров, и всё будет собрано.

**Comment by shmuz** [comment]
@elfmz , спасибо.

**Comment by elfmz** [comment]
этот ченж спровоцировал небольшой рефакторинг, который вызвал уже парочку найденных крэшей, так что если что - не удивляйтесь, а жалуйтесь

**Comment by unxed** [comment]
Типа вот этого?
https://github.com/elfmz/far2l/discussions/1250

**Comment by elfmz** [comment]
да, очень похоже)
