### ISSUE TITLE
Commit hash not updated in console caption

### ISSUE THREAD

**Issue by shmuz** [elfmz/far2l#1251]
Собрал коммит a14bebee ввиду критических проблем в коммите 0d6fe10d.
Проблемы вроде ушли, но в заголовке консоли по-прежнему отображается хэш 0d6fe10d.

**Comment by elfmz** [comment]
если вначале сделать `make clean` - то обновиться

**Comment by shmuz** [comment]
OK, спасибо.

**Comment by elfmz** [comment]
зря закрыли, похоже make clean не помогает, а должен, так что реопну

**Comment by shmuz** [comment]
Да, вот только сейчас у меня закончился make clean && make - не помогло.
Наверное надо make -B

**Comment by shmuz** [comment]
make -B не помогло.
