### ISSUE TITLE
Free Pascal's Free Vision unicode test app is rendered incorrectly in far2l's VT

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1255]
Free Pascal's TUI framework, [Free Vision](https://wiki.freepascal.org/Free_Vision), has recently been [adopted to unicode](https://wiki.freepascal.org/Free_Vision#Unicode_version). It's test application, testuapp, is rendered perfectly in GNOME Terminal, but is rendered with annoying artifacts inside far2l's internal VT. Attaching screenshots and test app binary for amd64.

[testuapp.tar.gz](https://github.com/elfmz/far2l/files/8088542/testuapp.tar.gz)

GNOME Terminal:
![Снимок экрана от 2022-02-17 15-21-03](https://user-images.githubusercontent.com/1151423/154480852-cb045b4f-9e57-4ad0-b50a-0f8df5251729.png)

far2l wx:
![Снимок экрана от 2022-02-17 15-21-17](https://user-images.githubusercontent.com/1151423/154480876-4e0a24c7-52c4-40e6-a366-9124fd561d93.png)

far2l tty in GNOME Terminal:
![Снимок экрана от 2022-02-17 15-24-58](https://user-images.githubusercontent.com/1151423/154481362-a02c3378-1d91-459c-9a60-40407f8a0d9a.png)

**Comment by unxed** [comment]
How to build unicode test app from sources:

1. You need Ubuntu 22.04 as it needs fresh free pascal compiler.
2. `apt install fpc`
3. `git clone https://github.com/fpc/FPCSource.git`
4. `cd FPCSource/packages/fv/examples`
5. Replace Makefile.fpc with:
```
[target]
programs=testuapp

[compiler]
unitdir=../src
unitdir=../../rtl-console/src/unix
unitdir=../../rtl-unicode/src/inc
unitdir=../../rtl-extra/src/inc
includedir=../../rtl-console/src/inc

[require]
packages=fv

[default]
fpcdir=../../..
```
7. run `fpcmake`
8. run `make`

**Comment by elfmz** [comment]
Its just yet another example of second sentence of Known issues:
And essentially same bug as this, for example - https://github.com/elfmz/far2l/issues/825

**Comment by unxed** [comment]
Maybe some kind of podorozhnik is possible until proper solution is implemented? :)

**Comment by unxed** [comment]
> Its just yet another example of second sentence of Known issues: And essentially same bug as this, for example - #825

Perhaps it will be easier to fix this for the beginning only for VT than to redo the whole far2l at once?

**Comment by unxed** [comment]
With #1279 it looks much better:

![изображение](https://user-images.githubusercontent.com/1151423/155132698-01d3d307-b93f-4aa2-9d3d-e1e3e916023a.png)

**Comment by unxed** [comment]
Fixed unneeded spaces between CJK under TTY backend (PR is the same):

![изображение](https://user-images.githubusercontent.com/1151423/155197516-ce64b037-19bd-4bbb-a0b7-d44545e1a54d.png)

**Comment by unxed** [comment]
В ветке [str-visual](https://github.com/elfmz/far2l/tree/str-visual) стартовый экран этой аппы уже показывается нормально (иероглифы полноразмерные, ура!), но аппа не отзывается на клавиатуру. И есть мелкий баг отображения: внизу вместо «F1 По пъ́тя» показывается «F1 По птя», т.е. составной символ куда-то пропадает.

В мастере:
![image](https://user-images.githubusercontent.com/1151423/196954204-be7afecd-21b8-415f-b540-4811505360a9.png)

В str-visual:
![image](https://user-images.githubusercontent.com/1151423/196954296-f6f293d2-ccdf-44a3-b14a-e1225c8b2605.png)

**Comment by unxed** [comment]
После 36397c1 «птя» превратилось в «п тя», на клаву всё ещё не отзывается

![изображение](https://user-images.githubusercontent.com/1151423/197386069-eaea3f76-e1f3-47a9-9cfd-233d55c3b702.png)

**Comment by unxed** [comment]
Собрал бинарник, работающий в ubuntu 18
https://2g0.ru/tmp/testuapp

**Comment by unxed** [comment]
> но аппа не отзывается на клавиатуру

Это потому что вместо Alt+английская_буква прилетает Alt+русская буква, вне зависимости от клавиатурной раскладки. А там все работающие хоткеи на Alt+английских буквах сделаны. Вот и кажется, что зависло всё. Если назначить хоткеем завершения работы, скажем, F5, то он отрабатывает.

**Comment by unxed** [comment]
str-visual
![изображение](https://user-images.githubusercontent.com/1151423/197518371-c3ead370-094f-492b-b33c-a06d19ada35f.png)

master
![изображение](https://user-images.githubusercontent.com/1151423/197518419-3ae6e76d-3da0-457f-920c-e7b904842c4f.png)

vanilla gnome terminal
![изображение](https://user-images.githubusercontent.com/1151423/197518489-dc3f84a9-5eee-40a9-b814-4e5825f752ea.png)

**Comment by unxed** [comment]
В wx потестить пока не получается из-за бага с неработающими хоткеями Alt+английский именно в этой ветке. В str-visual почему-то всегда прилетает Alt+русская буква, вне зависимости от выбранной раскладки.

**Comment by unxed** [comment]
wx, str-visual

![изображение](https://user-images.githubusercontent.com/1151423/197537042-a26da501-95d2-4fca-9db7-9a9ee2944e88.png)
![изображение](https://user-images.githubusercontent.com/1151423/197537087-28bae1db-c14e-45d4-a081-8ef7617b0fe4.png)

**Comment by unxed** [comment]
Аппа только в ubuntu 22.04+ собирается, так что вот бинарник, он заработет везде.
https://2g0.ru/tmp/testuapp

**Comment by elfmz** [comment]
У меня в гномотерминале 18й и 20й убунт выглядит так:
![image](https://user-images.githubusercontent.com/20957349/197647294-29e4b510-12b3-4c56-adab-ce39ff410108.png)
то есть эти стрелки и квадратики он считает двойной ширины. В 22й надо полагать считают их уже одинарной ячейкой?

**Comment by unxed** [comment]
Ubuntu 22, по состоянию на 9edbc1f850f1269c5f6b7dba01cbcfea7f63d3b0

![изображение](https://user-images.githubusercontent.com/1151423/197652846-a7cb30d7-a93b-4663-b6ef-cf8be86c09c1.png)

**Comment by unxed** [comment]
Хотя от шрифта зависит! Вручную выбрал Ubuntu Mono (хз, какой он сам по дефолту берет), стало так:

![изображение](https://user-images.githubusercontent.com/1151423/197652992-b468d662-f8b6-4464-a136-30cf3b8fd5b6.png)

**Comment by unxed** [comment]
DejaVu Sans Mono, Liberation mono — норм
Ubuntu Mono, Noto Mono — вылезают

**Comment by elfmz** [comment]
closing as fixed
