### ISSUE TITLE
256 цветов

### ISSUE THREAD

**Issue by alexmihajlov** [elfmz/far2l#1259]
Можно ли добавить поддержку 256 цветов в far, из-за того, что far работает в 16 цветах - вим запущенный из-под far в качестве внешнего редактора, выглядит не очень, особенно если у него установлена цветовая схема.

**Comment by unxed** [comment]
Touch #914 #521 #440

**Comment by elfmz** [comment]
и https://github.com/elfmz/far2l/issues/901

**Comment by unxed** [comment]
В ветке str_visual, вроде бы, появилась поддержка true color цветов, но как ей пользоваться, пока не ясно, документацию бы!

**Comment by elfmz** [comment]
closing as implemented
