### ISSUE TITLE
Debugging of python plugins

### ISSUE THREAD

**Issue by axxie** [elfmz/far2l#1260]
## Description

While doing all the steps according to `read-udebug-en.txt`, I am not able to debug the python code.

Reproduced using the following steps:
1. typed `py:load udebug` into far2l command line
2. opened udebug settings, noted them
3. typed `py:debug` into far2l command line. Far2l hanged exactly as specified in the instruction
4. tried to attach from VS Code using the settings noted in item 2

## Expected result
The VS Code attaches to the far2l

## Actual result
The VS Code displays the following error: “connect ECONNREFUSED 127.0.0.1:5678”

## Additional context
I also tried to test the attach from VS Code by using the same module – debugpy. For that I used the following minimal script:

```python
import debugpy

debugpy.log_to('/tmp')
debugpy.listen(('localhost', 5678))
debugpy.wait_for_client()

print("Hello")
```

The script also hanged, but VS Code successfully attached to it.

The adapter logs between far2l and standalone script are identical up to the point where in far2l log there are the following records:
```
D+00000.446: Server[pid=6805] --> {
                 "pydevd_cmd_id": 129,
                 "seq": 8,
                 "type": "event",
                 "event": "terminated",
                 "body": {}
             }

D+00000.447: /handling #8 event "terminated" from Server[pid=6805]/
             Closing Server[pid=6805] message stream

D+00000.447: Exiting message loop for channel Server[pid=6805]: No more messages

I+00000.448: All debug servers disconnected; waiting for remaining sessions...

I+00000.448: All debug sessions have ended; exiting.

I+00000.449: Not logging to "<stderr>" anymore.
```

To me it looks like for some reason the server closes the session even before VS Code has any chance to attach to the adapter.

@m32, please take a look.

### Environment

- far2l: 2.4.0-b61e9e7
- OS: Ubuntu 20.04.3

**Comment by unxed** [comment]
@m32

**Comment by m32** [comment]
Unfortunately, the debugger has stopped working, for me it is exactly the same as you described.
It's handy for typing, I'll fix it in a few days. Now I have my own matters more important, a tree in front of our house has just been knocked over :(

**Comment by m32** [comment]
Oddly enough, socket is not opened (localhost, 5678) after debugpy.listen (5678) executes, but only when executed from far2l.

@elfmz  - do you remember the reported problem with far2l starting slowly due to python initialization ?

#undef THREADED_PYTHON
#ifdef THREADED_PYTHON
class PythonHolder: Threaded
#else
class PythonHolder
#endif
....

This solves the problem of debugging python scripts. Python needs to initialize within the main thread of the program :(

**Comment by m32** [comment]
@axxie try current version, for me debugpy works

**Comment by axxie** [comment]
@m32, confirmed, the issue is fixed.
Thank you!
