### ISSUE TITLE
rendering artifacts then running tty far2l inside wx far2l

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1266]
1. open far2l wx
2. run `far2l --tty` inside
3. open attched file in editor as UTF-8
[demo.txt](https://github.com/elfmz/far2l/files/8101882/demo.txt)
4. close it
5. you will see garbage in panel:
![image](https://user-images.githubusercontent.com/1151423/154796042-abef6342-2753-4c48-a633-4e42fe16c960.png)

**Comment by unxed** [comment]
looks like tty backend performs second escaping of 58826 char, and it breaks positioning and cause errors

**Comment by unxed** [comment]
Ещё одно проявление, похоже, этого же бага. Делаем:
```
sudo apt install -y lxc
sudo lxc-stop -n fp
sudo lxc-destroy -n fp
sudo lxc-create -t download -n fp -- --no-validate --force-cache -d ubuntu -r jammy -a amd64
sudo lxc-start -n fp -d
sudo lxc-attach -n fp
```
...и пытаемся набрать что-нибудь на русском.

**Comment by unxed** [comment]
The most simple reproduction:
`echo -e '\uE5CA'`
in far2l's VT

**Comment by elfmz** [comment]
closing as 15cc3bfdb4a08fc3b300b1cef7861ad8701958f1 fixes this
