### ISSUE TITLE
Amazon Linux 2 build error: error: expected unqualified-id before numeric constant

### ISSUE THREAD

**Issue by ecc256** [elfmz/far2l#1270]
Ребята,
Вот такая ошибка, подскажите куда копать?

```
[ 32%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/PathHelpers.cpp.o
In file included from /usr/lib/gcc/x86_64-redhat-linux/7/include/limits.h:194:0,
                 from /usr/lib/gcc/x86_64-redhat-linux/7/include/syslimits.h:7,
                 from /usr/lib/gcc/x86_64-redhat-linux/7/include/limits.h:34,
                 from /usr/include/xercesc/validators/common/Grammar.hpp:25,
                 from /usr/include/xercesc/parsers/XercesDOMParser.hpp:27,
                 from /home/ec2-user/far2l/colorer/src/Colorer-library/src/colorer/parsers/CatalogParser.cpp:1:
/usr/include/spdlog/fmt/bundled/format.h: In member function ‘void fmt::internal::ArgFormatterBase<Impl, Char>::visit_char(int)’:
/usr/include/spdlog/fmt/bundled/format.h:2198:24: error: expected unqualified-id before numeric constant
         const unsigned CHAR_WIDTH = 1;
                        ^
[ 32%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/SavedScreen.cpp.o
[ 32%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/sudo/sudo_common.cpp.o
[ 32%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/sudo/sudo_client.cpp.o
make[2]: *** [Colorer-library/src/CMakeFiles/colorer_lib.dir/colorer/parsers/CatalogParser.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 32%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/sudo/sudo_client_api.cpp.o
[ 33%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/sudo/sudo_dispatcher.cpp.o
[ 33%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/sudo/sudo_askpass.cpp.o
[ 33%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/sudo/sudo_askpass_ipc.cpp.o
[ 33%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/Backend/WinPortMain.cpp.o
[ 33%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/Backend/SudoAskpassImpl.cpp.o
make[1]: *** [Colorer-library/src/CMakeFiles/colorer_lib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 33%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/Backend/FSClipboardBackend.cpp.o
[ 33%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/Backend/TTY/TTYBackend.cpp.o
[ 34%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/Backend/TTY/TTYRevive.cpp.o
[ 34%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/Backend/TTY/TTYInput.cpp.o
[ 34%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/Backend/TTY/TTYInputSequenceParser.cpp.o
[ 34%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/Backend/TTY/TTYOutput.cpp.o
[ 34%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/Backend/TTY/TTYFar2lClipboardBackend.cpp.o
[ 34%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/Backend/TTY/TTYNegotiateFar2l.cpp.o
[ 35%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/Backend/TTY/TTYXGlue.cpp.o
[ 35%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/Backend/TTY/IsUnstableWidthChar.cpp.o
[ 35%] Linking CXX static library libWinPort.a
[ 35%] Built target WinPort
make: *** [all] Error 2
```

**Comment by unxed** [comment]
Это, наверное, надо отправить в багтрекер либы spdlog, в которой, собственно, ошибка.

**Comment by unxed** [comment]
https://github.com/gabime/spdlog

**Comment by ecc256** [comment]
Да блин.
Вот только на CentOS 7 все компилиться.
Проблема только на Amazon Linux 2...
На обоих стоит devtoolset-8-gcc
А как проверить, какой gcc подхватывает cmake3?

**Comment by ecc256** [comment]
Проверил
gcc --version
не отличается... почти:

[Amazon Linux 2]$ gcc --version
gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)

[Cent OS 7]$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)

**Comment by ecc256** [comment]
На обоих
```
yum list spdlog*
Installed Packages
spdlog-devel.x86_64 0.10.0-1.el7 @epe
```

**Comment by elfmz** [comment]
Seems this bug: https://github.com/fmtlib/fmt/issues/398
And fix is just rename variable name: https://github.com/fmtlib/fmt/commit/abbefd71666055daac9e14e78262620f9e845850

**Comment by ecc256** [comment]
Всё собралось обоими gcc
```
gcc --version
gcc (GCC) 7.3.1 20180712 (Red Hat 7.3.1-13)

scl enable devtoolset-8 bash
gcc --version
gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
```

Только вот какая засада:
Я собрал RPM на CentOS7
Поставил на Amazon Linux 2 - все отлично работало.

Сегодня удалил через yum remove

Скомпилил gcc на Amazon Linux 2 и поставил через make install
Но far2l не запускается...
Не запускается собранный обоими gcc...
Некоторое время висит на starting far2l и потом окно пропадает.
Как-то надо кеш почистить или что?
ЧЯДН?

-----------
Еще вопрос до кучи:
А можно ткнуть в доку, как NetRocks сконфигурить?
Нужен просто доступ к вагону серверов по sftp с логинами через ~/.ssh/config

**Comment by ecc256** [comment]
Вдогонку:
А как сделать undo для make install?
make uninstall / make remove - нэту...
make clean совсем другое делает...?
Просто вручную удалять?

**Comment by ecc256** [comment]
> Я собрал RPM на CentOS7
> Поставил на Amazon Linux 2 - все отлично работало.

Собрал RPM точно также "на свежем" Amazon Linux 2
Поставил - НЕ запускается точно также как и поставленный через make install
Снес, поставил RPM собранный на CentOS7 - всё работает!
ЧЯДН?

**Comment by elfmz** [comment]
Ну тут только дебажить а у меня нету под рукой Amazon Linux. Впрочем если не жалко можете выложить обе рпм-ки как будет время попробую поставить куданить и запустить под gdb.
и да - make uninstall нету - только руками удалять такое..

**Comment by unxed** [comment]
В текущей версии spdlog (а вместе с ней и fmt) — опциональные, можно собирать без них.

Можно закрывать?

**Comment by elfmz** [comment]
закрываю. если таки все еще актуально - fell free to reopen
