### ISSUE TITLE
add alpine build support (make backtrace optional and implement qsort_r)

### ISSUE THREAD

**Issue by hemnstill** [elfmz/far2l#1285]
`musl` does not implement `backtrace` method, this fix in `SafeMMap.cpp` should affect alpine too:

```
#ifndef __FreeBSD__ // todo: pass to linker -lexecinfo under BSD and then may remove this ifndef
    // using backtrace/backtrace_symbols_fd is in general now allowed by signal safety rules
    // but in general it works and its enough cuz other important info already written in
    // signal-safe manner by FDWriteSignalInfo
    void *bt[16];
    size_t bt_count = sizeof(bt) / sizeof(bt[0]);
    bt_count = backtrace(bt, bt_count);
    backtrace_symbols_fd(bt, bt_count, fd);
#endif
```
or make it optional, like `USEUCD`

also, [qsort_r ](https://github.com/noporpoise/sort_r) does not exists in musl package in ubuntu:20.04

im trying to build far2l on alpine linux: https://github.com/hemnstill/StandaloneTools/blob/master/far2l/build_musl.sh and run it on ubuntu and vice versa.

**Comment by elfmz** [comment]
Implemented workarounds, may test now..

**Comment by hemnstill** [comment]
its worked, tnx. 

[Why is there no __MUSL__ macro?](https://wiki.musl-libc.org/faq.html)

```
It’s a bug to assume a certain implementation has particular properties rather than testing. 
So far, every time somebody’s asked for this with a particular usage case in mind, the usage case was badly wrong, 
and would have broken support for the next release of musl. The official explanation: 
http://openwall.com/lists/musl/2013/03/29/13
```
finally it is compiled with the flag:

`cmake -DCMAKE_CXX_FLAGS="-D__MUSL__" ... `
