### ISSUE TITLE
can Alt+Del (Wipe File) be trusted under linux?

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#129]

**Comment by elfmz** [comment]
From first look yes. At least performs writings. Note that only after https://github.com/elfmz/far2l/commit/8f9489d2ad293579c45ec7477ec3eaa18c6e5067 writethrough was implemented so before this it could not be trusted.

**Comment by unxed** [comment]
do I need to apply any special settings for writethrough mode to be applied to wipe action?

**Comment by elfmz** [comment]
theoretically no
but I'd prefer not to be sure in anything until checked: create file on loopback partition, write some content, wipe-delete file, unmount partition and try to find that content in raw partition image.

**Comment by unxed** [comment]
done that. test pattern not found. thanks.
