### ISSUE TITLE
Мультипоточная сборка

### ISSUE THREAD

**Issue by chodorenko** [elfmz/far2l#13]
Понимаю что альфа , но наверное стоит рассмотреть возможность мультипоточной сборки 
make -j N 
Потому что потоки не синхронизированы и выдают ошибку так как остальные ресурсы ещё не готовы

А сборка в один поток занимает минут 5 что не очень интересно на многопроцессорной машине

**Comment by elfmz** [comment]
а сейчас?

**Comment by invy** [comment]
Надо переходить на cmake, с ним сборка значительно лучше, особенно если использовать ninja.

**Comment by elfmz** [comment]
за счет чего она там быстрее чем распараллеленный make?

**Comment by invy** [comment]
Во-первых ninja сам по себе быстрее make, т.к. там нету ничего "лишнего", во-вторых, видимо cmake лучше генерирует мэйкфайлы чем codelite.
На той неделе тестировал (сгенерированное cmake'ом):
ninja -j12  111,43s user 12,85s system 358% cpu 34,704 total
make -j12  124,48s user 13,59s system 342% cpu 40,297 total

**Comment by elfmz** [comment]
Т.е. на 10% быстрее.. Нее, не сейчас)

**Comment by chodorenko** [comment]
Теперь билдится в мультипотоке :)
