### ISSUE TITLE
XLat() не транслирует никогда

### ISSUE THREAD

**Issue by cycleg** [elfmz/far2l#1301]
Функция XLat() никогда ничего не оттранслирует из-за
https://github.com/elfmz/far2l/blob/040c03d9a32241c86abce04df7dfe29f7e848179/far2l/src/locale/xlat.cpp#L153
Если таблицы перекодирования допустимые, ничего делать не надо. :)

**Comment by shmuz** [comment]
Сейчас проверил: изменение условия на противоположное исправляет ситуацию.
@elfmz, нужен pull request или сами поправите?

(только вчера написал внешний модуль xlat для своих плагинов).

**Comment by cycleg** [comment]
[Третья в истории файла правка](https://github.com/elfmz/far2l/commit/027016eb33e9adeefa3eb20767c09d326f08f0f4#diff-3e7d13a22bb12709a3a6ed9511a2c1591ff70110d9759219aacc40075162ebd5L154) сломала транслитерацию.

**Comment by shmuz** [comment]
Однако качество преобразования не идеальное.
Взял файл changelog со смешанным русско-английским текстом (2850 строк), сделал двойное преобразование XLat и сравнил с исходным файлом. Результаты такие:
- far2l - более 500 различий
- Far3 - 35 различий
- мой модуль, написанный вчера - 1 различие
