### ISSUE TITLE
far2l GUI mode panel refresh "artefact" by directory change

### ISSUE THREAD

**Issue by AxleUnix** [elfmz/far2l#1303]
When running in Pop!os 21.10 (GUI mode), at times when changing directory, the file panel does not update. Ubuntu 21.04 does not have this problem.
![image](https://user-images.githubusercontent.com/31538296/160646006-efa6ad51-5eec-4b85-9327-baf2189398a7.png)

**Comment by dodo-16** [comment]
> Ubuntu 21.04 does not have this problem.

Да уж.
У меня таже фигня на Ubuntu 22.04 **arm64**.
Сначала думал, что просто тормозит "when changing directory", потом понял, что просто экран не обновляет.
Бегаю стрелкими по папке - текущй файл под курсором перерисовывывается.
У тоже самое в диалогах и настройках - частичная перерисовка...
И edit / view file тоже...
Единственный способ, переключить на другую прогу и назад.
Гемор короче.
Почему-то кажется, что far2l тут не причем, это фича ОС, а куда копать не понятно...

**Comment by dodo-16** [comment]
Собирал скриптом отсюда:
https://github.com/unxed/far2l-deb

**Comment by dodo-16** [comment]
Поставил far2l_2.4~ubuntu20.04_amd64.deb из https://github.com/unxed/far2l-deb
на Ubuntu 22.04 amd64.
Та же самая фигня:
> Сначала думал, что просто тормозит "when changing directory", потом понял, что просто экран не обновляет.
> Бегаю стрелкими по папке - текущй файл под курсором перерисовывывается.
> У тоже самое в диалогах и настройках - частичная перерисовка...
> И edit / view file тоже...
> Единственный способ, переключить на другую прогу и назад.


> Почему-то кажется, что far2l тут не причем, это фича ОС, а куда копать не понятно...

Что-то ума не приложу, куда копать...

**Comment by AxleUnix** [comment]
Seems like WxWidgets buggy using.

**Comment by dodo-16** [comment]
@AxleUnix,
Do you mean, recent WxWidgets changes on Ubuntu 21+ are incompatible with FAR?
Or it's something else?

I don't English all (от слова совсем), terribly sorry for bugs you may encounter reading my post.

**Comment by AxleUnix** [comment]
I suspect that there is code in the far2l that causes the rendering functionality to become unstable. And this effect manifests itself in different ways - different people on the same Linux versions may have different behavior.

**Comment by unxed** [comment]
Вот бы пошаговую инструкцию по воспроизведению.
Кстати, если с английским никак — пишите на русском, тут двуязычное сообщество.

**Comment by unxed** [comment]
> I don't English all

Пишите на русском, не страшно, здесь двуязычное сообщество

**Comment by izzylaif** [comment]
вот это отключи
![1](https://user-images.githubusercontent.com/9394529/180622350-d888c9c0-92d3-43c5-9bcd-70ec177dc3d7.jpg)

**Comment by dodo-16** [comment]
А она вроде как уже выключена и не активна:
![image](https://user-images.githubusercontent.com/49847430/180628196-2c985437-d17a-4010-b4a4-26d7907694aa.png)

**Comment by dodo-16** [comment]
Это я нажал редактировать на .bash_history и сразу ESC.
Если окно FAR чуть подвинуть, то всё сразу перерисуется.

**Comment by AxleUnix** [comment]
On Ubuntu 22.04 everything works great for me, but breaks on Pop!_OS 22.04.

**Comment by dodo-16** [comment]
>On Ubuntu 22.04 everything works great for me

Huh.
I run Ubuntu 22.04 on AWS, where do you run yours?
And what's exactly build too?

**Comment by izzylaif** [comment]
я так понимаю у всех gnome и xorg?
а нет глюка с тултипа в фурифоксе 100+, из серии что подсказка (с названием окна например) не пропадает пока мышкой на нее не наведешь?

**Comment by dodo-16** [comment]
>я так понимаю у всех gnome и xorg?

У меня да

>а нет глюка с тултипа в фурифоксе 100+, из серии что подсказка (с названием окна например) не пропадает пока мышкой на нее не наведешь?

У меня такие глюки в FireFox на винде, достают регулярно.
И кажется они уже года 2 как появились на винде, вот на Linux портировали!
Я на Ubuntu FF не использую, только Chrome...

**Comment by izzylaif** [comment]
накинь xfce в нём попробуй. если не будет проблем с отрисовкой - то это проблемы гнома.

**Comment by dodo-16** [comment]
Так в Ubuntu 20.04 всё пучком было, проблемы только в 22.04 появились...

Могу xfce попробовать, если подскажете, как его включить только для некоторых юзеров.
Я как-то не очень разбираюсь...

**Comment by unxed** [comment]
> > On Ubuntu 22.04 everything works great for me
> 
> Huh. I run Ubuntu 22.04 on AWS, where do you run yours? And what's exact FAR build too?

Вы через x forwarding far2l в gui режиме с AWS гоняете?

**Comment by algoritmiks** [comment]
На убунте 22.04 проблема не появляется.

**Comment by dodo-16** [comment]
>Вы через x forwarding far2l в gui режиме с AWS гоняете?

Через x-rdp (с win server 2019)
И повторю до кучи:

>Так в Ubuntu 20.04 всё пучком было, проблемы только в 22.04 появились...

**Comment by unxed** [comment]
а это точно не в x-rdp баг? попробуйте обычный x forwarding для сравнения

**Comment by dodo-16** [comment]
>попробуйте обычный x forwarding для сравнения

Поставил **Xming**, проверил на **xeyes**: _x-term/x-forwarding_ работает.
А **far2l** все равно запускается в текстовом режиме...
Как-то можно ему подсказать на x-term запуститься?

**Comment by algoritmiks** [comment]
> Не, ну везет же людям! Пишите хоть билд, ради приличия, что ли...

Такой билд

![image](https://user-images.githubusercontent.com/13331652/180948225-69383f9e-284b-4273-8e93-399669ebcc2a.png)

**Comment by s-kipnis** [comment]
Same bug in Ubuntu 22.04
Ctrl-PgUp
The screen is not updated properly, i.e. only parts of screen updated


![image](https://user-images.githubusercontent.com/1813286/184843519-d33881bf-8f1d-4012-b952-5194c07a5696.png)

**Comment by dodo-16** [comment]
@s-kipnis 
> Same bug in Ubuntu 22.04
> Ctrl-PgUp
> The screen is not updated properly, i.e. only parts of screen updated

How do connect to it?
I.e. "monitor to physical computer", RDP, [TigerVNC](http://tigervnc.org/), etc.?

**Comment by dodo-16** [comment]
@unxed 
> а это точно не в x-rdp баг? попробуйте обычный x forwarding для сравнения

C x-forwarding не вышло, если поскажете как проверю!
> Поставил Xming, проверил на xeyes: x-term/x-forwarding работает.
> А far2l все равно запускается в текстовом режиме...
> Как-то можно ему подсказать на x-term запуститься?

А с [TigerVNC](http://tigervnc.org/) тоже самое:
![image](https://user-images.githubusercontent.com/49847430/185545607-4395e428-5118-432a-8ade-6b9c95c76786.png)

А есть какая еще похожая программа сравнить, как будет отрисовываться?

**Comment by dodo-16** [comment]
> C x-forwarding не вышло, если поскажете как проверю!

x-forwarding "внезапно" заработал.
Запустил 
gnome-session &
Все x-* проги работают.
А вот far2l запускается, но его окна нигде не видно.
Запустил пару раз.
В процесах есть, окон нету...
Это окно terminal на X:
![image](https://user-images.githubusercontent.com/49847430/185639317-30193384-5d7c-46e3-bb70-2068fd3487de.png)

**Comment by elfmz** [comment]
а где найти этот pop!_os 21.10? здесь предлагают скачать 22.04 - https://pop.system76.com/  или проблема воспроизводится и с 22.04?
Кстати у меня в Ubuntu 22.04.01 amd64 поставленной со всеми дефолтами - все норм.

**Comment by elfmz** [comment]
и еще напишите плз результат `echo $XDG_SESSION_TYPE`

**Comment by s-kipnis** [comment]
Ubuntu 22.04 x64 in HyperV VM
x11 over xrdp

**Comment by elfmz** [comment]
Хм, в просто x11 проблем нет, а вот если через xrdp то тогда дааа - артефакты налицо.
Но даже не знаю, та ли самая это проблема как у топикстартера. Както слишком экзотично...

**Comment by dodo-16** [comment]
@elfmz 
> Хм, в просто x11 проблем нет, а вот если через xrdp то тогда дааа - артефакты налицо.
> Но даже не знаю, та ли самая это проблема как у топикстартера. Както слишком экзотично...

А что такое "просто x11"?
C **x-forwarding** "Ubuntu 22.04" -> "Win Server 2019 + Xming" совсем другая проблема:

> А вот far2l запускается, но его окна нигде не видно.
> Запустил пару раз.
> В процесах есть, окон нету...

Надо бы проверить **x-forwarding** "Ubuntu 22.04" -> "Ubuntu 22.04", но вот только непонятно, как этому "Ubuntu 22.04" присоедениться.

> и еще напишите плз результат echo $XDG_SESSION_TYPE

Если это вопрос ко мне, то "Win Server 2019 + Xming" на 
**ubuntu@docker-aarch64:~$ echo $XDG_SESSION_TYPE**
_tty_

**Comment by dodo-16** [comment]
@s-kipnis 

> Ubuntu 22.04 x64 in HyperV VM
> x11 over xrdp

1. A какой именно клиент?
2. А с Ubuntu **20.04** x64 [in HyperV VM] у вас всё пучком было?

**Comment by elfmz** [comment]
> А что такое "просто x11"?
Просто локальная десктопная x11 сессия (а не wayland, как нынче по дефолту запускается)

**Comment by dodo-16** [comment]
@elfmz 
> Такое ощущение что реммина (или xrdp сервер) откладывают перерисовку части окна на потом (дескать оптимизация чтоб слать много перерисовок за раз), но почемуто - забывают об этом.

Да, именно это и подумал сначала.
Или прога (far2l) как-то должна сказать (xrdp серверу?), ну я типа закончил перерисовывать, давай обновляй экран.
И м.б. там разные версии API есть, типа старый-добрый и новый-злой (тощий и вредный)?

Спросил тут давеча, но никто не ответил:
> А есть какая еще похожая программа сравнить, как будет отрисовываться?

**Comment by elfmz** [comment]
> > "Ubuntu 22.04 + remina xrdp" -> тот же самый "Ubuntu 22.04"
> > Именно так.
> Эта, а можно как-то **x-forwarding** изобразить с одной тачкой?

Во-первых xrdp это не x-forwarding
Во-вторых у меня это разные системы, но не вижу технических проблем подключить реммину к локалхосту, но чую что на экране будет мешанина из самоотображенных пикселей.

**Comment by dodo-16** [comment]
> Во-первых xrdp это не x-forwarding

Это-то понятно.

> Во-вторых у меня это разные системы, но не вижу технических проблем подключить реммину к локалхосту, но чую что на экране будет мешанина из самоотображенных пикселей.

Эт точно, как 2 зеркала напротив друг друга...

Имел ввиду, вы проверили xrdp, можно как-то x-forwarding тоже проверить на вашем сетапе?

**Comment by dodo-16** [comment]
> Во-вторых у меня это разные системы, но не вижу технических проблем подключить реммину к локалхосту, но чую что на экране будет мешанина из самоотображенных пикселей.

А если через реммину под другим юзером зайти?
По идее новая сессия со всеми причиндалами должна запуститься ведь...

**Comment by elfmz** [comment]
Забавный баг, удалось сделать код минимально воспроизводящий проблему - https://pastecode.io/s/tbx3y817
прога выводит окно и на каждое нажатие рисует на нем либо одну либо много строчек и меняет заголовок окна, примерно на 30..40м нажатии она "забывает" перерисоваться,  что явно реже чем с far2l, но важен сам факт.
А забавное в баге то, что если убрать смену заголовка окна - то проблема уходит. Явно проблема xrdp но можно поэкспериментировать над воркэаундом.. может заголовок с задержкой менять..

**Comment by elfmz** [comment]
допилил тестовый пример и теперь воспроизводится почти каждое нажатие кнопки - https://pastecode.io/s/6by2gbm3
что забавно - переключение фокуса вызывает повторную перерисовку - и тогда окно обновляется правильно

**Comment by elfmz** [comment]
@s-kipnis можете попробовать текущий мастер? я добавил дополнительную перерисовку через полсекунды в случаях когда проблема происходит, как минимум должно вылазить намного реже теперь, но вообще лучше бы это _они_ пофиксили сами: https://github.com/neutrinolabs/xrdp/issues/2361
@dodo-16 через x-forwarding по ssh работает у меня норм. Делаю так - подключаюсь с `ssh -X HOSTNAME` далее запускаю там far2l --notty и иксовый far2l запускается и работает с виду нормально. --notty тут добавил потому что без него запускается терминальная версия, а иксовая даже не пытается.

**Comment by s-kipnis** [comment]
Потестил, вроде как работает. Иногда видна визуальная задержка, но это мне лично не особо мешает.

**Comment by dodo-16** [comment]
> можете попробовать текущий мастер?

У меня разницы нет, возможно, что не ту ветку собираю:
**old**
![image](https://user-images.githubusercontent.com/49847430/189546113-ade50f66-d32d-4bda-a321-76d1111ef553.png)

**new**
![image](https://user-images.githubusercontent.com/49847430/189546124-8232fd9e-0e6d-4b9d-b541-1fb0e83f3c6b.png)


Собирал make_far2l_deb.sh, в котором
`git clone https://github.com/elfmz/far2l`

Проверял на win 2019 + Xming -> [x-forwarding] Ubuntu 22.04 [wayland = false]

> допилил тестовый пример и теперь воспроизводится почти каждое нажатие кнопки - https://pastecode.io/s/6by2gbm3

подскажите, как/чем его собрать, сам не силён.

> что забавно - переключение фокуса вызывает повторную перерисовку - и тогда окно обновляется правильно

Да на "Ubuntu 22.04" именно так и было

**Comment by elfmz** [comment]
ну так у вас же не xrdp а x-forwarding,
а можете вот этот вот if - https://github.com/elfmz/far2l/blob/master/WinPort/src/Backend/WX/wxMain.cpp#L998
поменять на `if (g_xrdp || g_remote) { ` ?

**Comment by dodo-16** [comment]
>поменять на if (g_xrdp || g_remote) {

Сейчас попробую...

**Comment by dodo-16** [comment]
Проверил, работает отлично!
Огромное спасибо!

А вот это не подскажете:
> допилил тестовый пример и теперь воспроизводится почти каждое нажатие кнопки - https://pastecode.io/s/6by2gbm3

подскажите, как/чем его собрать, сам не силён.

**Comment by elfmz** [comment]
интересно, надо полагать там тоже воспроизведется так что это менее важно, а можете рассказать подробнее что у вас подразумевается под '-> [x-forwarding] ' ? ssh -X или какой то особый клиент?

**Comment by elfmz** [comment]
Я тут поставил xming на винду, и с нее подключился putty с включенным X11 forwarding ии.. проблема не воспроизводится...
Может дело в том что все это крутится в пределах одной машины на виртуалках, а для воспроизведения нужно чтоб гдето чтото тормозило..

**Comment by dodo-16** [comment]
> s-kipnis
> Потестил, вроде как работает. Иногда видна визуальная задержка, но это мне лично не особо мешает.

Да тоже самое и тоже не мешает.

---
> elfmz
> что у вас подразумевается под '-> [x-forwarding] ' ? ssh -X или какой то особый клиент?

Да, просто ssh -X на Xming

-----
> Я тут поставил xming на винду, и с нее подключился putty с включенным X11 forwarding к той самой убунте ии.. проблема не воспроизводится...
> Может дело в том что все это крутится в пределах одной машины на виртуалках, а для воспроизведения нужно чтоб гдето чтото тормозило..

Не могу прокомментировать, у меня все тачки разные.
А дома просто dualboot.

**Comment by elfmz** [comment]
Есть подозрение что это ограничение иксов - не факт что можно в исксовой сессии одного юзера запустить приложение от имени другого юзера. Как минимум другому потребуется доступ к .Xauthority файлу который находится в домашней директории первого юзера.

**Comment by elfmz** [comment]
а баг закрываю, вроде же у всех уже кое как проблема решена..

**Comment by elfmz** [comment]
ссылка для истории: https://bugs.launchpad.net/ubuntu/+source/xwayland/+bug/2002456

**Comment by elfmz** [comment]
Было бы неплохо еслиб кого етот баг касается по этой ссылке пометили баг как affects you, чтоб на него внимание обратили...

**Comment by elfmz** [comment]
полагаю зарегаться и ткнуть сверху в 
![image](https://user-images.githubusercontent.com/20957349/211878070-7ebcd522-1347-4edd-a486-87fc396a8cc0.png)
