### ISSUE TITLE
Far can't edit files on GVFS-mounted FS

### ISSUE THREAD

**Issue by cycleg** [elfmz/far2l#1309]
Не удается сохранить файл, если он открыт на редактирование из панели, отображающей подмонтированную через GVFS файловую систему. При попытке сохранить файл выдается ошибка 95, "неподдерживаемая операция" (EOPNOTSUPP). При этом копирование файла обычным для Far образом (через панели) работает.
Проблема свойственна не только Far, аналогичное поведение демонстрирует, например, vi (тоже не может сохранить отредактированный файл). Дальнейшее изучение вывело на [застарелую проблему GVFS](https://gitlab.gnome.org/GNOME/gvfs/-/issues/249#note_326773).
Предлагается "объезд" через исправление FileEditor::SaveFile():
```
diff --git a/far2l/src/fileedit.cpp b/far2l/src/fileedit.cpp
index 72021e5f..5ef4935a 100644
--- a/far2l/src/fileedit.cpp
+++ b/far2l/src/fileedit.cpp
@@ -1999,7 +1999,7 @@ int FileEditor::SaveFile(const wchar_t *Name,int Ask, bool bSaveAs, int TextForm
                        try
                        {
                                File EditFile;
-                               if (!EditFile.Open(Name, GENERIC_WRITE, FILE_SHARE_READ, nullptr, OPEN_ALWAYS, FILE_ATTRIBUTE_ARCHIVE|FILE_FLAG_SEQUENTIAL_SCAN))
+                               if (!EditFile.Open(Name, GENERIC_WRITE, FILE_SHARE_READ, nullptr, CREATE_ALWAYS, FILE_ATTRIBUTE_ARCHIVE|FILE_FLAG_SEQUENTIAL_SCAN))
                                        throw WINPORT(GetLastError)();

                                if (!Flags.Check(FFILEEDIT_NEW))
```
Открывать файл `CREATE_ALWAYS` вместо `OPEN_ALWAYS`. В данном контексте это приемлемо.

**Comment by elfmz** [comment]
CREATE_ALWAYS перезаписывает файл что можно привести к потере данных если при записи нового содержимого закончится место на диске, нооо, можно в принципе сделать запасным вариантом или даже с проверкой на тип файловой системы

**Comment by elfmz** [comment]
сейчас норм работает?

**Comment by cycleg** [comment]
Сейчас работает правильно.
В задаче GVFS предлагали сохранение через временный файл. Дико неэффективно, конечно, но в контексте редактирования вряд ли кто-то будет работать с по-настоящему большими файлами, т.е. вариант IMHO рабочий. И оригинальное содержимое файла в любом случае не потеряется.

**Comment by elfmz** [comment]
С сохранением через временный файл куча подводных граблей с сохранением изначальных метасвойств файла - всякие там (extended) attributes, хардлинки и фиг знает что еще
