### ISSUE TITLE
ConfigWriter overwrites symlinks rather than their targets

### ISSUE THREAD

**Issue by shmuz** [elfmz/far2l#1312]
Пример:
- у меня `~/.config/far2l/settings/key_macros.ini` является симлинком на файл, расположенный в другом месте (в Git-репозитории)
- записываю с клавиатуры простейший макрос, назначаю на какую-либо клавишу
- вызываю с помощью плагина `MCMD_SAVEALL`
- в результате симлинк удалён, на его месте регулярный файл `key_macros.ini`

Мне кажется, что это нестандартное поведение. Ведь если выполнить `fopen(); fwrite(); fclose();` из Си-программы, то будет изменён именно таргет симлинка, а он сам останется на месте.

**Comment by elfmz** [comment]
fopen(); fwrite(); fclose(); не атомарно, то есть если гдето посередине write-а произойдет сбой - получится битый файл. Еще битый файл получится если писать будут двое. Потому KeyFileHelper пишет временную копию файла и делает rename, так что таки да - симлинк потеряется.
В принципе можно данный конкретный случай пофиксить путем проверки на то что файл - симлинк, и делать все записи в его (финальный) target.

**Comment by shmuz** [comment]
Если не трудно, сделайте. Не то, чтобы это было для меня критично, но весьма желательно.

**Comment by elfmz** [comment]
ок

**Comment by shmuz** [comment]
Спасибо, стало хорошо.

Воспользуюсь этим каналом, чтобы посоветоваться, ибо что-то застрял.
Я сейчас проверяю опцию использования LuaJIT вместо Lua.
После определённых усилий, оно заработало (всё 5 плагинов), но только при запуске из терминала.
Если запускаю ярлыком на десктопе, получаю (чего раньше не было)
![image](https://user-images.githubusercontent.com/344558/163379783-7dd4c111-ccf7-4a15-bfb6-f1b35704b313.png)
Что бы это могло быть? Используется GUI (не TTY) во всех случаях.

**Comment by elfmz** [comment]
Возможно при запуске из терминала и из ярлыка какието переменные окружения различаются.

**Comment by elfmz** [comment]
- а где именно прописывалась LD_LIBRARY_PATH?
 - а геишный шелл перезапускался после этого (например перелогином в сессию)?

**Comment by shmuz** [comment]
В `~/.bashrc` была добавлена строка `export LD_LIBRARY_PATH=/usr/local/lib`.
После запуска из ярлыка я проверял (прямо из Фара) при помощи `ldd`, что и `luafa2l.so`, и плагины видят LuaJIT. Это говорит о том, что не хватало чего-то ещё.

**Comment by elfmz** [comment]
Есть ньюанс - шелл который виден в фар2л - это отдельно работающий процесс баша, со своими переменными окружения, которые он очевидно вычитал из ~/.bashrc при своем запуске.
Я если честно точно не знаю, но очень не уверен что гуишный шелл получает переменные из .bashrc, еще меньше я уверен в том что он его перечитывает при его изменении (точнее я уверен что не перечитывает)
Такие вещи лучше в /etc/environment прописывать ну и геи перелогинивать, тут вам не винда, в которой эксплорер следит за ключом реестра чтоб если что поменяется в переменных профиля - сразу подчитать новые значения.

**Comment by shmuz** [comment]
Меня удивляло то, что из терминала работало, а с ярлыка на десктопе - нет. Вполне возможно, что надо было просто перелогиниться.
Ну так или иначе, LuaJIT работает. В Фар 3 он является частью дистрибутива с 2013 года. Но там проще - и LuaJIT, и LuaFAR лежат в папке Фара, юзеру не надо ничего устанавливать.

**Comment by elfmz** [comment]
В целом, если что - то я не против интегрировать его в виде плагина в основное дерево здесь, но - желательно после 2.4.1 которую сделаю после того как дополирую некоторые оставшиеся проблемы в BSD.
С луа я как наверное вы догадались особо не знаком, но касательно этого `Переустановил LuaJIT из /usr/local в /usr, и теперь работает с ярлыка тоже.` есть вопрос. Вот я делаю `apt-cache search luajit` и вижу
```
libluajit-5.1-2 - Just in time compiler for Lua - library version
libluajit-5.1-common - Just in time compiler for Lua - common files
libluajit-5.1-dev - Just in time compiler for Lua - development files

```
как я полагаю если я сделаю `apt install libluajit-5.1-2` то оно все само поставит как полагается, и все будет видно. А вы судя по цитате устанавливали эту либу руками? и собирали? А почему не из репозитория?

**Comment by shmuz** [comment]
> А вы судя по цитате устанавливали эту либу руками? и собирали? А почему не из репозитория?

Об этом подумал, но документ автора LuaJIT как бы взял верх у меня: https://luajit.org/install.html
Автор ничего не пишет об "обычной" установке типа `apt install`.

**Comment by elfmz** [comment]
Ну так то автор, он пишет как собрать и поставить то что он сделал - то есть исходники. А пакеты в репозиториях делают зачастую совсем другие люди, потому он про это и не написал. Разделение труда однако)
apt кстати тоже даалкео не вездесущ, а дебиановский пакетный менеджер, юзается соответственно в около-дебиановских линуксах. В более других дистрибах есть более другие пакетные менеджеры.

**Comment by shmuz** [comment]
Насчёт незнакомства с Lua, это легко исправляется. Язык очень небольшой для изучения. Основы можно охватить за 1 день.
Преимущество Lua для Фара в том, что можно на порядок быстрее получить какую-либо  функциональность (по сравнению с написанием плагина). Всегда возникают какие-либо мелкие (или не очень) хотелки, и для каждой из них плагин писать не будешь. А на Lua зачастую за полчаса можно это получить.

Вот пример из сегодняшнего дня: https://forum.farmanager.com/viewtopic.php?p=170348#p170348

**Comment by elfmz** [comment]
Насчет примера, я уже писал гдето в коментах что в линуксах в отличие от винды скриптование - это не киллерфича, а унылая обыденность. Если среднестатистическому линуксятнику захочется понасоздавать директорий, он не полезет в скриптинг фар2л-я, а накорябает в шелле чтонить такое:
```
for n in {1..100}; do
	mkdir $(cat /dev/urandom | tr -cd 'a-f0-9' | head -c 8)
done
```

**Comment by shmuz** [comment]
Ничего не имею против скриптования в шелле.
Но ведь Фар  - это визуализация, тем он и ценен.
Скрипты шелла не дают доступа к Far API, а LuaFAR имеет 100-процентный охват этого API.

**Comment by elfmz** [comment]
Ну, я когда пришел в линуксы в полный рост, а не в виде шелла на какой то железяке, и полез искать замену фара, то наткнулся на такое - https://habr.com/ru/post/218073/
Двухпанельник написанный целиком и полностью на скриптовом языке - js-е - скриптуй что угодно прям на лету. И где он теперь? Видимо не только в скриптах сила фара...

**Comment by shmuz** [comment]
> Видимо не только в скриптах сила фара...

Ну конечно не только в скриптах (да я этого и не говорил).
Я не агитирую, а просто пытаюсь объяснить причину популярности Lua в Фар3.
Всё имеет свою относительную ценность, и что для одного важно, для другого нет.

**Comment by elfmz** [comment]
Ну вобщем ето все лирика, а вот luajit надо из репов юзать - тут так принято. И что самое неприятное - надо по возможности поддерживать весь зоопарк версий либы (и ее конвигурационных опций), который встречается на потенциальных таргетах.

**Comment by shmuz** [comment]
На данном этапе, покуда у меня на Линуксе ноль пользователей (кстати, я к этому спокойно отношусь), это непринципиально. Но насколько я знаю LuaJIT, там нет кучи версий и кучи опций. Версия его 2.1-beta3 уже последние лет 5.

**Comment by elfmz** [comment]
Ну тогда тем более нет причин не юзать то что приходит из репозитория

**Comment by shmuz** [comment]
Да я собственно и не спорю с этим. Могу деинсталлировать и попробовать установить через apt install. Кстати Lua у меня именно так и установлен. (Сейчас есть опция в мейкфайле, юзер может выбрать, что он хочет: Lua или LuaJIT).

**Comment by elfmz** [comment]
а эта опция точно нужна? есть случаи когда lua предпочтительнее чем luajit?

**Comment by shmuz** [comment]
Эта опция для большинства юзеров точно не нужна, но она нужна мне для диагностики.

**Comment by shmuz** [comment]
`apt install` устанввливает LuaJIT версии 2017 года, что для меня не является приемлемым.

**Comment by shmuz** [comment]
@elfmz , хотелось бы поговорить на тему перевода системы макросов Far2L на такую, как в Far3 (основанную на Lua).
Ибо, несмотря на то, что я уже чувствую себя довольно уютно в Линуксе с Far2L, всё, что касается макросов, по сравнению с Far3, это далеко не то.

Я бы предпочёл сделать это в сотрудничестве с вами.

**Comment by shmuz** [comment]
@elfmz , поскольку вы не отвечаете, я начал эти работы самостоятельно на своём форке Far2L.
На мой взгляд, ещё не поздно избежать существования двух независимых версий.
Мы с вами составили бы маленькую команду, как говорится, одна голова хорошо, а две лучше.
У нас с вами знания в непересекающихся областях, и это тоже хорошо.
Я в любом случае отнесусь с уважением к вашему непринятию данного предложения,, но хотелось разъяснить суть предыдущего своего сообщения, и чтобы потом не говорили, что я не предлагал.
