### ISSUE TITLE
Unable to change font: Ubuntu 20.04

### ISSUE THREAD

**Issue by yuchdev** [elfmz/far2l#1313]
Version: `2.4.0-97668113`
Compiled from sources, packed and installed by `apt install far2l_2.4.0-97668113-beta_amd64.deb`
After the launch font looks like that

![Far2l font](https://raw.githubusercontent.com/yuchdev/Blog/master/images/windows-10/far-font.png)

Changing font or its size in `$HOME/.config/far2l/font` did not give any result

**Comment by elfmz** [comment]
F9/Options/Interface/Change font
