### ISSUE TITLE
tmp mount points in drive menu

### ISSUE THREAD

**Issue by izzylaif** [elfmz/far2l#1315]
После последнего апдейта, в списке "дисков" (по alt-f1 или alt-f2) стали появлятся точки монтирования из /tmp что несколько раздражает.
Можно ли как-то это отключить, или задать определенные пути где фар2л ищет точки монтирования?
![2](https://user-images.githubusercontent.com/9394529/164060433-cf583488-5323-472b-8ce7-c9484e57827b.jpg)

**Comment by dodo-16** [comment]
У меня вроде нет на FAR2L 2.4.0-f788d371-beta на Ubuntu 22.04 arm64:
Или есть? :-/

```
  ╔════════════════════════════ Location ═════════════════════════════╗
  ║  -                   /home/ubuntu │           │ Other panel       ║
  ║  ~                   /home/ubuntu │           │ Home              ║
  ║  /                              / │ 117G/124G │ ext4              ║
  ║                              /run │ 3.1G/3.1G │ tmpfs             ║
  ║                         /boot/efi │ _92M/ 97M │ vfat              ║
  ║    /home/ubuntu/thinclient_drives │ 0.0K/0.0K │ fuse.xrdp-chansrv ║
  ╟───────────────────────────── Plugins ─────────┴───────────────────╢
  ║     NetRocks                                                      ║
  ║     temporary                                                     ║
  ╚═════════════════════ Ins,Del,Shift-Del,F4,F9 ═════════════════════╝

```

**$ mount**
_/dev/nvme0n1p1 on / type ext4 (rw,relatime,discard,errors=remount-ro)
devtmpfs on /dev type devtmpfs (rw,relatime,size=8056548k,nr_inodes=2014137,mode=755,inode64)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,size=3231044k,nr_inodes=819200,mode=755,inode64)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k,inode64)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=1066)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
none on /run/credentials/systemd-sysusers.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
/var/lib/snapd/snaps/amazon-ssm-agent_5165.snap on /snap/amazon-ssm-agent/5165 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/amazon-ssm-agent_5657.snap on /snap/amazon-ssm-agent/5657 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/core18_2349.snap on /snap/core18/2349 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/core18_2406.snap on /snap/core18/2406 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/core20_1498.snap on /snap/core20/1498 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/lxd_22927.snap on /snap/lxd/22927 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/core20_1522.snap on /snap/core20/1522 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/snapd_15909.snap on /snap/snapd/15909 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/snapd_16019.snap on /snap/snapd/16019 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/dev/nvme0n1p15 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
tmpfs on /run/snapd/ns type tmpfs (rw,nosuid,nodev,size=3231044k,nr_inodes=819200,mode=755,inode64)
nsfs on /run/snapd/ns/lxd.mnt type nsfs (rw)
tmpfs on /run/user/1001 type tmpfs (rw,nosuid,nodev,relatime,size=1615520k,nr_inodes=403880,mode=700,uid=1001,gid=117,inode64)
tmpfs on /run/user/0 type tmpfs (rw,nosuid,nodev,relatime,size=1615520k,nr_inodes=403880,mode=700,inode64)_

**Comment by unxed** [comment]
/usr/lib/mounts.sh гляньте, там это определяется

**Comment by dodo-16** [comment]
> /usr/lib/mounts.sh гляньте, там это определяется

На Ubuntu 22.04 arm64 и amd64 нет такого:

**$ sudo ls -la /usr/lib/mounts.sh**
_ls: cannot access '/usr/lib/mounts.sh': No such file or directory_

Да вроде и не напрягает особо.

А вот по этому вопросу есть идеи, куда копать:
https://github.com/elfmz/far2l/issues/1303

Я бы видео сделал, только не знаю как.
Телефоном снимать не хочу...

**Comment by unxed** [comment]
/usr/lib/far2l/mounts.sh
, конечно

**Comment by izzylaif** [comment]
Со старым файлом действительно не показывает мусор в списке, с новым (который в два раза потолстел) - показывает.
Никак не могу понять что изменилось, а хотелось бы на случай будущих апдейтов
Цепляю оба файла
Старый (убрать .txt):
[mounts.sh.txt](https://github.com/elfmz/far2l/files/9174609/mounts.sh.txt)
Новый (убрать .txt):
[mounts.sh.txt](https://github.com/elfmz/far2l/files/9174612/mounts.sh.txt)

**Comment by sxored** [comment]
add this

```
-e " /tmp/\.\([a-z0-9\._]\+\)_\([a-zA-Z0-9\._]\+\) "
```

regex excludes these example mounted directories from final output of mounts.sh

```
/tmp/.veracrypt_aux_mnt1
```

and

```
/tmp/.mount_firefoMAvMq7
```

diff

```diff
@@ -76,7 +76,7 @@
 		FMT_COLUMN='cat'
 		if [ "$sysname" = "Linux" ]; then
 			MNT_TYPE=5
-			MNT_FILTER='grep -v -e " /proc\(/[\/a-z_]\+\)* " -e " /sys\(/[a-z_,]\+\)* " -e " /dev/\(pts\|hugepages\|mqueue\) " -e " /run/user/\([0-1]\+\)/doc " -e " /home/\([a-z0-9\._]\+\)/.cache/doc " -e " /var/lib/lxcfs "'
+			MNT_FILTER='grep -v -e " /proc\(/[\/a-z_]\+\)* " -e " /sys\(/[a-z_,]\+\)* " -e " /dev/\(pts\|hugepages\|mqueue\) " -e " /run/user/\([0-1]\+\)/doc " -e " /home/\([a-z0-9\._]\+\)/.cache/doc " -e " /var/lib/lxcfs " -e " /tmp/\.\([a-z0-9\._]\+\)_\([a-zA-Z0-9\._]\+\) "'
 			FT_HEADER='Filesystem Type 1K-blocks Used Available Use%% Mounted_on'
 			if [ "$timeout_coreutils" = "true" ]; then
 				FMT_COLUMN='column -t'
```

**Comment by izzylaif** [comment]
@elfmz это войдет в релиз или мне продолжать хранить старый файл как девственность?

**Comment by elfmz** [comment]
войдет) наверное

**Comment by izzylaif** [comment]
После последнего апдейта вообще пропал файл /usr/lib/far2l/mounts.sh и даже если его туда положить, программа игнорирует и все равно заполняет список alt-f1/f2 всяким мусором...

**Comment by elfmz** [comment]
Alt+F1/F2 -> F9 -> там исключения, добавьте туда /tmp/.* если больше проблем нету то позже вкомичу изменение дефолтовой строки

**Comment by izzylaif** [comment]
Отлично, работает!!
