### ISSUE TITLE
Copy from NTFS to BTRFS stuck

### ISSUE THREAD

**Issue by cmdorexe** [elfmz/far2l#1319]
I copied some profile from Windows11 from NTFS to BTRFS using far2l under the root user.
And I found that:
far2l stuck without the possibility for even sigill.
The main problem is copying system links which cannot be written to btrfs.
In this case, expecte to see a choice of actions in an exceptional situation.

`FAR2L, version 2.4.0-beta Linux x86_64
OS: Fedora Linux 35 (Workstation Edition) x86_64
Kernel: 5.17.5-200.fc35.x86_64
XDG_SESSION_TYPE=x11`

**Comment by cmdorexe** [comment]
Nautilus showing some error then it hapends.
![изображение](https://user-images.githubusercontent.com/15385426/167200576-db067b18-dd01-4aaa-a689-803d315ff889.png)

**Comment by elfmz** [comment]
can you prepare dir with minimal reproduction structure on ntfs and pack it with winrar so i'll able to (try to) reproduce this?

**Comment by cmdorexe** [comment]
Fedora 35 deprecated.
