### ISSUE TITLE
investigate if wxWidgets far build is wayland-aware

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#132]
all modern desktops are in progress of switching to wayland to replace X11.
upcoming fedora 25 is going to select it as default.
we should not ignore this fact.

**Comment by elfmz** [comment]
yes, although I didnt try it

**Comment by elfmz** [comment]
Ss I understand there'is no need to actually change far2l, just to use latest GTK and set wayland backend (just as I set broadway backend when experimenting with far2l-in-browser). Futhermore - I believe that will be done 'automatically' in those 'modern desktops'

**Comment by unxed** [comment]
Ok, closing.
