### ISSUE TITLE
Code table EBCDIC-CYRYLIC

### ISSUE THREAD

**Issue by pupupupupup** [elfmz/far2l#1327]
Добрый день!
В русском, изначально, продукте - отсутствует возможность смотреть/корректировать файлы в одной из русских кодировок -IBM880, ака  EBCDIC-CYRYLIC. Очень не хватает. В базовой EBCDIC - IBM EBCDIC International (500) отсутствует кирилица, есть IBM EBCDIC US Canada, IBM EBCDIC Hebrew, IBM EBCDIC Greek, IBM EBCDIC Arabic, есть даже IBM EBCDIC Latin 5 Turkish. А CYRYLIC нет...

Очень бы хотелось...
Заранее спасибо.

**Comment by shmuz** [comment]
Мне кажется, что это зависит от операционной системы, а не от приложения.
У меня на Windows 10 эта кодировка есть (под номером 20880), а на Linux Mint нету.

**Comment by unxed** [comment]
Рискну предположить, что её может не быть в файлах, которые импортировались из кодовой базы Wine. При этом, возможно, сейчас её уже туда добавили.

**Comment by pupupupupup** [comment]
Скорее всего, именно так. Но ведь это же непорядок!
(В смысле импорт статического состояния того, что меняется довольно часто)


сб, 28 мая 2022 г., 19:45 unxed ***@***.***>:

**Comment by unxed** [comment]
А как надо?

**Comment by pupupupupup** [comment]
Вообще, по хорошему, надо брать локаль из системы.

сб, 28 мая 2022 г., 20:07 unxed ***@***.***>:

**Comment by unxed** [comment]
В фаре совсем не так всё работает. У него внутреннее представление — UTF16, на входе и выходе оно конвертится из системной для Linux UTF-8 и обратно. В теории можно приделать поддержку любой другой системной кодировки, но на практике это пока никому не надо было.

А поддержка кодировок в редакторе-просмотрщике-etc — это отдельная история, там везде идёт перекодировка из одной из поддерживаемых кодировок во внутреннюю UTF16 и обратно. Так вот функции этой перекодировки можно брать из iconv (но оно медленно, и от этого отказались), или из Wine (как сейчас).

Как-то так. @elfmz поправит, если я не совсем точно описал что-то.

**Comment by elfmz** [comment]
CYRYLIC - это вроде как 880 (отсюда https://wutils.com/encodings/ibm880 ),  в вайне ее не было и все еще нету - https://github.com/wine-mirror/wine/tree/master/libs/wine а потому нету и в far2l так как преобразования кодовых страниц в far2l взято из вайна. Но при желании и знании кодов символов можно добавить, и заодно в вайн тоже) вот например греческий EBCDIC https://github.com/wine-mirror/wine/blob/master/libs/wine/c_875.c

**Comment by pupupupupup** [comment]
> CYRYLIC - это вроде как 880
Да, и именно она и нужна на просторах СССР.
>Но при желании и знании кодов символов можно добавить, и заодно в вайн тоже)
Я не понимаю, куда ее добавлять, чтобы ее увидел far. Очень нужна эта кодировка... Могу приложить таблицы преобразования cp880<->1251 и  cp880<->KOI8
https://disk.yandex.ru/d/5bLpslUT3Drvgw
Я был бы очень благодарен за решение (или хотя бы подсказку пути решения) этой проблемы.

**Comment by elfmz** [comment]
подсказка на самом деле написана шапке c_875.c:
`generated from https://download.microsoft.com/download/C/F/7/CF713A5E-9FBC-4FD6-9246-275F65C0E498/Windows Supported Code Page Data Files.zip:CodpageFiles/875.txt`
Я скачал этот самый Supported Code Page Data Files.zip - в нем 880.txt не нашлось зато нашлось 20880.txt у которого написано что он `CODEPAGE 20880          ;IBM EBCDIC Cyrillic`
Скрипт который генерит вышеупомянутые сорсы лежит в wine/tools/make_unicode и все бы ничего, но он качает кой чего с unicode.org а последний чойта в данный момент не доступен (фигасе). Ну, подождем - может оживет... Вроде же не мелкий сайтик - однодневка.

**Comment by pupupupupup** [comment]
> make_unicode
Я у себя на диске не нахожу подобного файла. Вине надо было как то ставить дополнительно (кроме app install wine)?
И да, http://unicode.org/ не отвечает. Ни из Питера, ни из Москвы, ни из Амстердама... Чудны дела твои, о великая сеть...

**Comment by elfmz** [comment]
надо исходники вайна скачать, ну если юникод очухается - попробую сгенерить файлик, а не очухается придется разбираться как генерилка работает... это будет дольше

**Comment by unxed** [comment]
http://unicode.org/ у меня открылся. Питер.

**Comment by unxed** [comment]
[wine.zip](https://github.com/elfmz/far2l/files/8803297/wine.zip)
Вот это дело разворачиваете в домашнюю папку, и скрипт ничего с unicode.org качать уже не будет. По идее :)

**Comment by unxed** [comment]
В скрипте `make_unicode` надо после строчки
`"CodpageFiles/20127.txt",`
добавить строчку
`"CodpageFiles/20880.txt",`

Скрипт отработал, только он генерит бинарные .nls файлы, а вовсе не исходники на c.

**Comment by unxed** [comment]
Для генерации .c надо брать более раннюю версию make_unicode. Отсюда, например:
https://github.com/wine-mirror/wine/tree/2087f38e8478ff8596a5a2038f8607aecfe2faa7/tools

**Comment by unxed** [comment]
1. Используем Wine ревизии [2087f38e8478ff8596a5a2038f8607aecfe2faa7](https://github.com/wine-mirror/wine/tree/2087f38e8478ff8596a5a2038f8607aecfe2faa7)
2. Берем файлик `20880.txt` из `Windows Supported Code Page Data Files.zip`
3. Оставляем только часть между строками `MBTABLE 256` и `WCTABLE 350`
4. Отрезаем каменты (`;` и далее)
5. Конвертим hex-значения в верхний регистр
6. Подсовываем в дерево исходников wine (где `tools/make_unicode`) по пути `data/20880__.txt`
7. Добавляем в `make_unicode` после строчки
```
[ 20866, "VENDORS/MISC/KOI8-R.TXT",           0, "Russian KOI8" ],
```
строчку
```
[ 20880, "20880__.txt",                       0, "IBM EBCDIC Cyrillic" ],
```
8. Запускаем `make_unicode`

Вуаля:

[c_20880.c.zip](https://github.com/elfmz/far2l/files/8804091/c_20880.c.zip)

**Comment by unxed** [comment]
Правда, при попытке собрать far с этим файликом, выбрать 20880 в редакторе, набрать `тест` и сохраниться, фар пишет "некоторые символы не поддерживаются", и потом сохраненный файл открывает криво, так что, боюсь, что-то я упустил в процессе, и надо дальше разбираться.

**Comment by unxed** [comment]
А вот iconv, кстати, в эту кодировку умеет, так что если прописать её в список поддерживаемых в iconv-ветке, то должно заработать.

**Comment by unxed** [comment]
В общем, вот на чём я остановился на данный момент. Почему фар со сгенерированной таким способом табличкой пишет файлы редактором правильно, а открывать не хочет — не понял пока.

[wine.tar.zip](https://github.com/elfmz/far2l/files/8804463/wine.tar.zip)

**Comment by elfmz** [comment]
Открывает вроде тоже нормально но есть ~баг~ ньюанс не связанный скорее всего с код страницей - если создать файл с такой кодировкой то он потом открывает его первый раз как UTF8, но если вручную выставить кодировку потом, то это выставление он уже запоминает и в след раз открывается нормально. Видимо при создании файла в редакторе почемуто не запоминается ассоциированная с ним кодировка.
Вобщем вкомитил, если таки есть какието другие косяки - пишите. А если все устраивает - то закрывайте баг)

**Comment by elfmz** [comment]
uchardet не детектит такие файлы кстати, видимо поэтому такой косяк с этой кодировкой. Хотя по идее должно запоминать и эвристику не запрашивать вообще,

**Comment by pupupupupup** [comment]
Огромнейшее спасибо! Откомилил, все заработало.От всех мэйнфреймщиков (бывших и новых) огромное спасибо!

**Comment by unxed** [comment]
@elfmz maybe we should replace
```
/* generated from http://www.unicode.org/Public/MAPPINGS/20880__.txt */
```
in `c_20880.c` to something like
```
/* generated from https://download.microsoft.com/download/C/F/7/CF713A5E-9FBC-4FD6-9246-275F65C0E498/Windows Supported Code Page Data Files.zip:CodpageFiles/20880.txt */
```

**Comment by elfmz** [comment]
..and break a commandment `/* DO NOT EDIT!! */` below?. OK..

**Comment by unxed** [comment]
> ..and break a commandment `/* DO NOT EDIT!! */` below?. OK..

maybe semi-manual nature of generation of that file should be noted somehow... by a link to this issue, for example?

**Comment by unxed** [comment]
> uchardet не детектит такие файлы кстати

https://gitlab.freedesktop.org/uchardet/uchardet/-/issues/29
