### ISSUE TITLE
Wrong rendering of combined diacritics

### ISSUE THREAD

**Issue by alk0** [elfmz/far2l#1329]
Tested on 2.4.0-78c2802c-beta Linux x86_64 (-DUSEWX=yes). "Normal" diacritic symbols (ó) are displayed properly, but combined diacritics (ó) cause all sorts of artifacts in viewing, editing, panels (if used as file names), dialogs, etc. I believe there was no such issue before… but can't say when "before".

![image](https://user-images.githubusercontent.com/10332037/176670565-e955e190-a799-4f4d-8841-7c555f9cb8fd.png)

(^ "Attención" typed in two different ways, as "o" + combined accent and as one symbol.)

Test file attached (TXT, UTF-8):

[test_accent.txt](https://github.com/elfmz/far2l/files/9019501/test_accent.txt)

**Comment by unxed** [comment]
long standing bug
https://github.com/elfmz/far2l/issues/1255
https://github.com/elfmz/far2l/issues/825

**Comment by alk0** [comment]
Ah, OK… Seems my memory serves me wrong, about "no such issue before". Just for the record — in my case (KDE, Konsole) TTY is not much better, accent marks are displaced, and there are remaining artifacts from the underlying file panel, when opening the file for viewing:

![image](https://user-images.githubusercontent.com/10332037/176832491-52eb9db9-e6c2-4fc6-a609-53ee35af45b2.png)

But in this case it's largely a terminal problem, it seems, not far2l's — `cat test_accent.txt` doesn't show it properly either.

(Totally irrelevant side note: it's spelled "Atención", with one 't', not "Attención", my bad.)

**Comment by unxed** [comment]
Maybe an issue in terminal's bug tracker should be opened also.

**Comment by unxed** [comment]
Also, you may try this patch: https://github.com/elfmz/far2l/pull/1279
Not an ideal solution, though, but makes things slightly better.

**Comment by unxed** [comment]
В ветке str-visual рендерится правильно, но есть мелкий баг в редакторе: если открыть приложенный к тикету тестовый файл, и стрелками поставить курсор на последнюю букву слова «Бирюлёво», а потом нажать вниз, курсор попадает не на ячейку ниже, а на ячейку ниже и сильно правее.

@elfmz

**Comment by unxed** [comment]
duplicates #213, #826

**Comment by elfmz** [comment]
closing as fixed
