### ISSUE TITLE
After updating Arch linux, it is not possible to build a package

### ISSUE THREAD

**Issue by Vyacheslav-S** [elfmz/far2l#1338]
After updating Arch linux, it is not possible to build a package.
With upgrade wxgtk3 auto-switch to wxwidgets-gtk3.

`Make Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindwxWidgets.cmake:984 (find_package_handle_standard_args)
  WinPort/src/Backend/WX/CMakeLists.txt:64 (find_package)
`
How can this problem be solved?

**Comment by Vyacheslav-S** [comment]
change in the PKGBUILD 39 line:
`/usr/bin/wx-config-gtk3`
to
`/usr/bin/wx-config`
After that, the package is complete without errors.

**Comment by graycrow** [comment]
@Vyacheslav-S: it works, thank you!

**Comment by R6ASfcdT** [comment]
@Vyacheslav-S Thx, I have resolved the same issue at manjaro system after last update.

**Comment by elfmz** [comment]
so, closing..
