### ISSUE TITLE
far2l doesn't preserve timestamps when copying/moving/renaming directories

### ISSUE THREAD

**Issue by SleepingCatSC** [elfmz/far2l#1341]
far2l doesn't preserve timestamps when copying/moving/renaming directories

Reproducible via:
Copying directory via F5/Shift+F5 menu
Moving/renaming directory via F6/Shift+F6 menu

Some alternatives:
cp utility has -pr attributes to preserve directory timestamps along with subdirectories
mv utility also preserves timestamps
Midnight Commander that has an option has an option "Preserve attributes" in F5/F6 menus
Original Far Manager has an option "Preserve all timestamps" in F5/F6 menus

File timestamps are preserved when copying a directory. It is a far2l specific issue and I hope that at some day it will be fixed :)

**Comment by dodo-16** [comment]
I would guess, it might be better to compare with **mv**, not **cp -pr**, no?
