### ISSUE TITLE
multiarc: several sudo-releated issues left

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#135]
1. decompressing files to root-owned folder fails
2. creating an archive in root-owned folder fails

**Comment by elfmz** [comment]
please provide scenario more exactly cuz for me both works

**Comment by unxed** [comment]
1. open far2l
2. create a folder in "/" called "test" by pressing F7 and entering sudo user password
3. go to this folder on left panel
4. select any zip archive on right panel and go into it
5. try to copy any file from zip archive to test folder
6. 
```

TIP: If you feel stuck - use Ctrl+Alt+C to terminate everything in this shell.  
Archive:  /home/unxed/Рабочий стол/temp/far2l.zip                               
error:  cannot create upd.sh                                                    
        Permission denied                                                       
```

**Comment by unxed** [comment]
1. open far2l
2. create a folder in "/" called "test" by pressing F7 and entering sudo user password
3. copy any file to this folder confirming elevated privileges usage
4. select this file on a panel and press shift+f1 to add it to archive (I have zip packer selected by default)
5. press enter to start creating an archive
6.

`Archiver reported exit code 2`

**Comment by unxed** [comment]
using lastest build from here

**Comment by elfmz** [comment]
aha, interesting that extracting to existing /root works fine (as I tried before), but to just created /test doesnt

**Comment by unxed** [comment]
```
drwxr-xr-x   2 root root  4096 окт 10 16:26 test
drwx------   8 root root  4096 окт  1 01:43 root
```

if it matters
