### ISSUE TITLE
When panels are off Del clears screen

### ISSUE THREAD

**Issue by i2van** [elfmz/far2l#1352]
1. Hide panels.
2. Type in command line.
3. Press `Del`

`Actual` Screen is cleaned.
`Expected` Symbol is deleted under caret.

`Del` also clears screen when command line is empty.

There is no macro for `Del`.

WSL2, Ubuntu 22.04, [VcXsrv Windows X Server](https://sourceforge.net/projects/vcxsrv/)

**Comment by shmuz** [comment]
On my installation Del works as expected (the screen is not cleared).

**Comment by i2van** [comment]
@shmuz Updated OS and Windows X Server used.

**Comment by shmuz** [comment]
@i2van
I'm using Linux Mint 20.3.
Regarding the X Server: I don't know how to find out (but I didn't change the OS defaults).

**Comment by elfmz** [comment]
May be you have such an entry in your key_macros.ini?

```
[KeyMacros/Shell/NumDel]
DisableOutput=0x1
Sequence=F8
```

**Comment by i2van** [comment]
I checked `~/.config/far2l/settings/key_macros.ini`, and there is no `Del` macro.

**Comment by unxed** [comment]
@elfmz WSL2-related issue. possibly should be checked also now

**Comment by i2van** [comment]
Not reproduced anymore.
