### ISSUE TITLE
Учитывание XDG_CACHE_HOME и XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by AlexFromChaos** [elfmz/far2l#1357]
Если у пользователя `.config` и `.cache` находятся не в `$HOME`, то far2l всё равно пытается использовать `~/.config` и `~/.cache`.
В частности, под директорию `$HOME/.cache/far2l/askpass_ipc`.

Необходимо проверять эти переменные среды по-хорошему. В коде на данный момент встречаются только отдельные упоминания XDG, типа `getenv("XDG_SESSION_TYPE)`.

Есть workaround с установкой переменной среды `FARSETTINGS`, но, судя по коду, far2l хардкодит субдиректории `.config` и `.cache` в ней и уже эти использует вместо `~/.config` и `~/.cache`. Не то чтобы с этим нельзя было жить, но перфекционизм нарушен.

Но не совсем понятно, как совместить чтение `XDG_CACHE_HOME`/`XDG_CONFIG_HOME` с кодом в `InProfileSubdir()`, который проверяет, что путь в `FARSETTINGS` начинается на '/' (или нет) и соответственно может менять результирующий путь.

**Comment by AlexFromChaos** [comment]
По идее, если есть явный путь к конфигу/кэшу far2l в `FARSETTINGS`, то `XDG_CACHE_HOME`/`XDG_CONFIG_HOME` нам вообще не надо трогать - путь задан пользователем явно. Но нюанс в том, что если `InProfileSubdir` видит относительный путь в `FARSETTINGS`, то считает, что это типа модификатор пути, который надо дописать к стандартному пути.

**Comment by shmuz** [comment]
Путь к конфигу/кэшу можно задать с командной строки при запуске. Из хелпа:
```
 -u <identity> OR </path/name>
      Allows to specify separate settings identity or FS location.
```

**Comment by AlexFromChaos** [comment]
Ну `FARSETTINGS` хотя бы удобнее, чем в ком. строке путь каждый раз указывать. Это хорошо, если far2l только с ярлычков запускать, но первый же запуск `./far2l` без параметров с шелла сразу напомнит, что конфиг "где-то там".

В целом тикет можно переформулировать просто как **far2l не учитывает XDG-пути**.

**Comment by unxed** [comment]
> в ком. строке путь каждый раз указывать
alias

Хотя поддерживать XDG, конечно, правильно.
