### ISSUE TITLE
Extremly destructive macros in WinCompat.h

### ISSUE THREAD

**Issue by cycleg** [elfmz/far2l#136]
В WinCompat.h имеется исключительно опасный, по-моему, макрос, [переопределяющий "nullptr" в "NULL"](https://github.com/elfmz/far2l/blob/master/WinPort/WinCompat.h#L1514). Из-за него компилятору мерещатся, например, кошмарные неоднозначности в элементарной инициализации unique_ptr вида `ptr(nullptr)`.

Предлагаю уничтожить макрос как классово чуждый.

**Comment by elfmz** [comment]
:) ок, если билдится. ща уже не вспомню чего я его туда добавил

**Comment by lieff** [comment]
Скорее всего до C++11 требовалось.

**Comment by invy** [comment]
Выкинуть надо.
