### ISSUE TITLE
в редакторе turbo не работают хоткеи с Alt

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1361]
В терминал wx-версии far2l (в tty версии всё норм). Раньше работали. Сложно сказать, в какой момент сломалось. Вместо обработки хоткеев в редакторе появляется русский символ соответствующей клавиши, вне зависимости от выбранной раскладки. В GNOME Terminal всё ок. Mint Linux Mint 21 Vanessa x64 Cinnamon.

Например, в меню выходит зайти только по F12, Alt+F не катит.

https://github.com/magiblot/turbo

Бесит, потому что turbo — единственный вменяемый редактор для консоли с правильно работающим переносом по словам. Если можно поправить, было бы здорово.

**Comment by unxed** [comment]
А, собственно, и в быстром поиске тоже с альтом только русские буквы печатаются.

**Comment by unxed** [comment]
Если закомментить #define WX_ALT_NONLATIN, становится ещё смешнее: в английской раскладке с альтом печатаются русские буквы, а в русской — английские.

Быстрому поиску это, с учётом трансляции раскладок, не особо мешает. А вот хоткеи с альтом в запущенных внутри фара приложениях — нужны.

**Comment by unxed** [comment]
Вот чего происходит:
```
OnKeyDown: raw=77 code=6c3 uni=446 (ц) ts=14222909 [now=1377063355]
ConsoleInput::Enqueue: ц 446 57 2 DOWN
OnChar: raw=77 code=77 uni=77 (w) ts=14222909 lke=1
OnKeyUp: raw=77 code=6c3 uni=446 (ц) ts=14223031
ConsoleInput::Enqueue: ц 446 57 2 UP
```

Т.е. на OnChar приходит правильный символ, латинский (вернее, соответствующий текущей раскладке).
А вот на KeyUp/KeyDown приходят всегда русские (или всегда из дефолтной раскладки, наверное).
В Enqueue, почему-то, уходит то, что пришло на KeyDown/Up, а не то, что в OnChar.

**Comment by unxed** [comment]
Соответственно, лечение выглядит так:
```
diff --git a/WinPort/src/Backend/WX/wxMain.cpp b/WinPort/src/Backend/WX/wxMain.cpp
index 6913bb65..f6e82056 100644
--- a/WinPort/src/Backend/WX/wxMain.cpp
+++ b/WinPort/src/Backend/WX/wxMain.cpp
@@ -1197,8 +1197,8 @@ void WinPortPanel::OnChar( wxKeyEvent& event )
 	}
 	fprintf(stderr, "\n");
 
-	if (event.GetUnicodeKey() != WXK_NONE && 
-		(!_last_keydown_enqueued || _key_tracker.LastKeydown().GetTimestamp() != event.GetTimestamp())) {
+	if (event.AltDown() || (event.GetUnicodeKey() != WXK_NONE && 
+		(!_last_keydown_enqueued || _key_tracker.LastKeydown().GetTimestamp() != event.GetTimestamp()))) {
 		INPUT_RECORD ir = {0};
 		ir.EventType = KEY_EVENT;
 		ir.Event.KeyEvent.wRepeatCount = 1;
```

Т.е. мы просто создаем дублирующий ивент с кодом символа на правильном языке для всех комбинаций с Alt.
Но это, конечно, костыль, и наверняка можно изящнее решить.

**Comment by elfmz** [comment]
У меня наблюдается следующее - на тестовой ubuntu 20 с каким то старым far2l все работало норм, после обновления far2l перестал работать в турбо alt+x если включена русская раскладка, если английская - то работает

**Comment by unxed** [comment]
> У меня наблюдается следующее - на тестовой ubuntu 20 с каким то старым far2l все работало норм, после обновления far2l перестал работать в турбо alt+x если включена русская раскладка, если английская - то работает

Кажется, на 20 так и было. А мой Mint 21 это Ubuntu 22.04. Бага растёт из wx'ов, похоже, которые в разных выпусках ведут себя чуть по разному.

Но можно её обойти, забирая код символа из OnChar, а не OnKeyUp/Down.

**Comment by unxed** [comment]
Конечно, как было в 20 (когда только в одной раскладке хоткеи работают) — тоже не идеально, но оно во всех терминалках так, увы. Хотя в перспективе тоже было бы клёво иметь отключаему опцию «слать Alt/Ctrl+буквы во встроенный терминал всегда в латинице, если не в режиме экстеншнов».

**Comment by elfmz** [comment]
Это похоже этот баг - https://github.com/elfmz/far2l/issues/1180 но в другой проекции так сказать.
Оно воспроизводилось в KDE если в списке раскладок первой была не английская. Но там Alt+ не был частью картинки. Тут похоже несколько сложнее все..
И это не особенность wx а особенность системы ввода в kde или еще гдето там. Типа решили - а чем это английский так особеннен что Alt+ всегда приходит с ним? И теперь Alt+ всегда приходит с символом из первого языка в списке... Ну это чисто мое предположение о причинах..

**Comment by elfmz** [comment]
Возможно можно спихнуьт на wx - типа чтоб они учитывали такое и транслировали результат GetUnicodeKey в адекватный текущей раскладке.. Вобщем какой то сферический трэш там с раскладками сделали в этих кедах..

**Comment by unxed** [comment]
В идеале хорошо бы чтоб wx'ы отдавали и в текущей раскладке, и в английской. Хотя бы потому что все хоткеи во всех аппах по дефолту именно английские. Как-то же там работал хак-с-меню в любых раскладках.

**Comment by elfmz** [comment]
ну может кеды были первой ласточкой, хз... есть идея костылька, потом попробую..

**Comment by elfmz** [comment]
вкомитил костылек в ветку debug-1361

**Comment by unxed** [comment]
этот починился, ура! зато сломался поиск по alt+букве на русской раскладке.

**Comment by unxed** [comment]
выглядит это так. похоже, на русской раскладке он onchar не кидает вообще.

```
Current client size: 1366 700 font 11 22
OnKeyDown: raw=ffe9 code=133 uni=0 ( ) ts=29139417 [now=1399022479]ConsoleInput::Enqueue: # 0 12 2 DOWN
OnKeyUp: raw=ffe9 code=133 uni=0 ( ) ts=29139514
ConsoleInput::Enqueue: # 0 12 0 UP
OnKeyUp: raw=ffe1 code=132 uni=0 ( ) ts=29139541 UNPAIRED
OnKeyDown: raw=ffe9 code=133 uni=0 ( ) ts=29140258 [now=1399023318]ConsoleInput::Enqueue: # 0 12 2 DOWN
OnKeyDown: raw=6db code=0 uni=448 (ш) ts=29140954 [now=1399024013] CHAR
OnKeyUp: raw=6db code=0 uni=448 (ш) ts=29141052 CHAR
OnKillFocus
ConsoleInput::Enqueue: # 0 12 0 UP
```

**Comment by DEF29** [comment]
Не подскажете как прикрутить turbo к far2l? Нет ли инструкции?

**Comment by unxed** [comment]
@elfmz а что если я предложу альтернативное решение: галка в настройках, при которой alt (ctrl, etc) + русские буквы будут автоматически транслироваться в латинские по xlats.ini?

**Comment by unxed** [comment]
В общем, да, причина была в выбранной по умолчанию раскладке. Похоже, где-то в wx происходит трансляция кода клавиши в символ не по текущей раскладке, а по дефолтной. Оформил отдельным тикетом (https://github.com/elfmz/far2l/issues/1374), а этот можно закрыть, наверное. Хотя идея опциональной трансляции русских символов в хоткеях в английские по xlats.ini заслуживает отдельного обсуждения, так что оставлю пока.

**Comment by unxed** [comment]
> а что если я предложу альтернативное решение

Not relevant any more since turbo support far2l extensions. See #1562.

**Comment by unxed** [comment]
as this is finally fixed, branch debug-1361 probably can be removed now

**Comment by unxed** [comment]
Ха, а проблемка-то с тем, что при дефолтной русской раскладке в системе wx всё ещё шлют в OnKeyUp/Down поле UnicodeKey в кириллице, даже если сейчас выбрана латиница (а вот в OnChar — уже шлют UnicodeKey в текущей раскладке, как положено) — так и осталась!

Но вот в свежих wx, собранных из мастера, уже не воспроизводится. Похоже, я её случайно починил вот тут:
https://github.com/wxWidgets/wxWidgets/commit/2c0f6a2aa0c8d0650d1f856aa279ce7495925c17
