### ISSUE TITLE
Netrocks: no match for method server host key algo

### ISSUE THREAD

**Issue by dmstek** [elfmz/far2l#1362]
When trying to connect to host tells:

**Connection - kex error : no match for method server host key algo: server [ssh-rsa,ssh-dss], client [ssh-ed25519,ecdsa**

Did not found a way to add algo for this host in Netrocks. So to do what you do for ssh in .ssh/config like

    HostkeyAlgorithms +ssh-rsa
    PubkeyAcceptedAlgorithms +ssh-rsa

**Comment by elfmz** [comment]
so try to enable checkbox Use OpenSSH configuration files in [ Protocol options ]

**Comment by dmstek** [comment]
> so try to enable checkbox Use OpenSSH configuration files in [ Protocol options ]
Yes, it was the first thing I tried. 

sftp user@192.168.1.7 from command line works, but same from netrocks do not, even that the checkbox is checked.

**Comment by elfmz** [comment]
if would be useful if you can tell how to force OpenSSH to use (only) ssh-rsa or may be what ssh server to use  for that

**Comment by dmstek** [comment]
> if would be useful if you can tell how to force OpenSSH server to use (only) ssh-rsa or may be what ssh server to use for that Specifying HostkeyAlgorithms ssh-rsa in sshd_config seems didnt change anything

Sure. You have to put in /home/user/.ssh/config this content

```
Host 192.168.41.7
    HostkeyAlgorithms +ssh-rsa
    PubkeyAcceptedAlgorithms +ssh-rsa
```

In this case it will use rsa.

So basically without it will be this:
```
ssh user@192.168.41.7
Unable to negotiate with 192.168.41.7 port 22: no matching host key type found. Their offer: ssh-rsa,ssh-dss
```

When you include it will be working:
```
ssh user@192.168.41.7
user@192.168.41.7's password: 
```

**Comment by dmstek** [comment]
Ah, sorry, I got it, you want to test so you want to restrict. Just install old version like OpenSSH_6.7p1, OpenSSL 0.9.8zg 11 Jun 2015 in virtual box and that will do it.

**Comment by elfmz** [comment]
there were bunch of research and changes around this, so small summary:
1 ssh_config is really parsed by libssh, futhermore it appeared that it was parsed regardless of the option 'Use OpenSSH configuration files' BUT libssh has limited support of openssh configs format, for instance it doesnt understand '+ssh-rsa' but understands simple 'ssh-rsa'
2 NetRocks options was extended so now its possible to specify per-site either specific config file either set supported hostkeys explicitly: 
![image](https://user-images.githubusercontent.com/20957349/213932575-78b67f5d-bc46-4b2d-bace-de1850fc9b7a.png)
So it seems it can be closed now - please check if its ok for you now,

**Comment by elfmz** [comment]
closing bug as probably resolved, if still not possible to connect - reopen
