### ISSUE TITLE
CJK characters rendered incorrectly

### ISSUE THREAD

**Issue by danfe** [elfmz/far2l#1365]
I think it got better with new version 2.4.1, yet it's still not quite right.  Typically CJK characters should be twice as wide compared to the Latin ones so that mixed text looks good.  I have a couple of Chinese-named files in my home directory, and this is how they're rendered in Midnight Commander:
![cjk-mc](https://user-images.githubusercontent.com/1132291/192566810-63dc40d7-5349-44e5-a9b5-3c231f369e18.png)

And this is with Far2L 2.4.1:
![cjk-far2l](https://user-images.githubusercontent.com/1132291/192566828-dc68a898-bb6e-4125-b178-0dc7337e42b5.png)

Apparently, Far is aware that CJK characters are special, but instead of making them occupy twice of the Latin width it scales them down so they become twice shorter.  Should not be hard to fix, I think. ;-)

**Comment by elfmz** [comment]
Its actually well known and not so easy to fix issue. There're already few similar bugs...

**Comment by elfmz** [comment]
closing as fixed

**Comment by danfe** [comment]
Thank you, I can confirm that mixed CJK/Latin text, including file names, is displayed correctly now.  Apparently fixed with commit 253a6b1 (for the record).
