### ISSUE TITLE
str-visual bugs left

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1372]
Накидаю сюда всё, что смог заметить. Возможно, эти баги и так известны. А, может, есть и неизвестные. Вдруг пригодится. Тестировалось на Mint 21 (= Ubuntu 22.04).

1. Если в редакторе [turbo](https://github.com/magiblot/turbo) открыть текстовый файл со строчкой «[😊]», и подвигать курсор вправо-влево из первой позиции, в какой-то момент ловится вот такое (не сразу, надо долго пробовать):
![Снимок экрана от 2022-10-24 11-01-45](https://user-images.githubusercontent.com/1151423/197466670-fe58dd88-67d9-48b5-8f0d-2d4c599c1d3a.png)
Что особенно странно, во встроенном редакторе это не воспроизводится.
Воспроизводится только в wx.

~~2. При попытке выделить «ъ́» в редакторе появляются артефакты.
Воспроизводится только в wx.~~

3. Эти иероглифы всё ещё рендерятся мелкими: 테스트대화상자
Воспроизводится только в wx.

4. Иероглифы рендерятся не по центру двойного знакоместа, а по левому краю, из-за чего возникает иллюзия несуществующего пробела справа, это сбивает с толку немного. gnome-terminal рендерит по центру (и, кажется, чуть крупнее).
Воспроизводится только в wx.

~~5. Символы «ℕℕ₀ℤℚℝℂ⊥≪⊤⇒A⇔→⊃☺» рендерятся обрезанными. Смайлик — символ с кодом 9786, гитхаб заменяет.
Воспроизводится только в wx.~~

~~6. Символ преключения на RTL-письменность (иврит, арабский, etc) не обрабатывается нормально. https://en.wikipedia.org/wiki/Right-to-left_mark (там по ссылке есть проверочная строка «I enjoyed staying -- באמת!‏ -- at his house.», на которой можно тестить).
Воспроизводится в wx (в tty работает, но не уверен, что правильно).~~

**Comment by unxed** [comment]
Ну и подборка связанных багов, чтоб потом закрывать пачкой проще было:
https://github.com/elfmz/far2l/issues/826
https://github.com/elfmz/far2l/issues/213
https://github.com/elfmz/far2l/issues/825
https://github.com/elfmz/far2l/issues/1255
https://github.com/elfmz/far2l/issues/1329
https://github.com/elfmz/far2l/issues/1333

**Comment by unxed** [comment]
Часть багов ушла, обновил список.

**Comment by unxed** [comment]
Часть багов ушла, обновил список (по состоянию на https://github.com/elfmz/far2l/commit/50b721b5846efcff3fc7ad08d0f93fc00ef06be3).

**Comment by elfmz** [comment]
3 - у меня не мелкие, 
было:
![image](https://user-images.githubusercontent.com/20957349/198867642-7a86e752-3e82-4475-9644-be19e8d7e268.png)
стало:
![image](https://user-images.githubusercontent.com/20957349/198867657-86e4e6f1-4ac2-4eff-b3c5-57e28250276d.png)

**Comment by elfmz** [comment]
6 - все еще в отдаленном будущем)

**Comment by elfmz** [comment]
5 у меня в гномтерминале они тоже корявые
![image](https://user-images.githubusercontent.com/20957349/198868125-d3e80eb5-cb31-4bb7-a2ee-1324c586fbbd.png)

**Comment by unxed** [comment]
6 видимо особенность шрифта? на Ubuntu Mono 16 так
![изображение](https://user-images.githubusercontent.com/1151423/198868673-f63e8e24-7375-4e5b-93c7-dc7adf37ffb0.png)

**Comment by unxed** [comment]
Поставил Liberation Mono, который в GNOME Terminal используется. 6 остался!

![изображение](https://user-images.githubusercontent.com/1151423/198868783-c51a27d2-4ffd-4020-8e86-90531cf8f026.png)

**Comment by unxed** [comment]
А вот 5 на Liberation Mono ушел, это особенность шрифта выходит, да

![изображение](https://user-images.githubusercontent.com/1151423/198868852-90a1ce01-d431-4f65-b815-581ff66f1d72.png)

**Comment by unxed** [comment]
> 6 - все еще в отдаленном будущем)

Пусть в отдельном тикете живет тогда, раз в отдаленном
https://github.com/elfmz/far2l/issues/1380

**Comment by unxed** [comment]
2 ушла. e1a1c2f5aac8de6e9d6d0b76e9aecae55bd44263

**Comment by elfmz** [comment]
В 3 иероглифы все же не мелкие а крупнее чем были, но - все еще недостаточно крупные) места вроде хватает чтоб отрисовать более крупным шрифтом но.. стандартный способ отрисовки без уменьшения размера шрифта рисует так что сверху остается здоровый отступ, в результате иероглиф вылезает снизу ниже строки.
Нужен какой то кастомный рендеринг или какая то магия чтоб точно определить положение видимой части иероглифа в заданном прямоугольнике вывода чтобы можно было его сдвинуть и нарисовать точно в строке. Пока средставами wx ничего не получается, вот сделал только чуть-чуть крупнее.

**Comment by unxed** [comment]
А как это гномовская и кдешная терминалки решают, может, в их код подсмотреть?

**Comment by elfmz** [comment]
у японцев и прочих иероглифопищущих кстати есть свой особый пробел двойной ширины UTF 0x3000 - '　'  так что по идее в реально японских текстах пробелы будут хорошо отличимы

**Comment by unxed** [comment]
Допускаю, что 3 и 4 уже можно считать вкусовщиной, да. По крайней мере, пока вопросов от носителей соответствующих языков нет

**Comment by unxed** [comment]
1 больше не воспроизводится. Закрываю.

Будут вопросы от носителей языков с иероглифической письменностью — новые тикеты сделают :)

**Comment by unxed** [comment]
Ещё один связанный тикет: #1385
