### ISSUE TITLE
Странная дефолтная цветовая схема, отсутствие чистых цветов

### ISSUE THREAD

**Issue by xintrea** [elfmz/far2l#1382]
Версия far2l: 2.4.1-ea8fdf19-beta
Сборка: из исходников master
ОС: Debian11 stable
Терминал: konsole

Запуск far2l сразу после инсталляции выглядит вот так:

![Снимок экрана от 2022-10-31 15-52-32](https://user-images.githubusercontent.com/769826/199012329-4b490abe-9939-4dcf-bc3e-551b20587afb.png)

Кроме того, в настройках невозможно выбрать "чистые" цвета, доступны только "подсвеченные":

![Снимок экрана от 2022-10-31 15-55-39](https://user-images.githubusercontent.com/769826/199012794-3adaab2e-a8ed-46f3-81ac-3bdd7e751120.png)

В результате все выглядит блекло, невозможно даже выбрать черный фон, потому что его просто нет.

**Comment by elfmz** [comment]
так это TTY версия, цвета в ней зависят от настроек терминала в котором работает far2l

**Comment by elfmz** [comment]
Вот как выглядит в гномтерминале убунты
![image](https://user-images.githubusercontent.com/20957349/199014535-5729a016-cc09-419c-b63e-45637d80de58.png)
а вот wx версия, дефолтовая палитра которой максимально приближена к классическим цветам виндовой консоли
![image](https://user-images.githubusercontent.com/20957349/199014774-fcd28df2-0943-4a1a-a0b7-00fff6fdf92e.png)

**Comment by xintrea** [comment]
> Вот как выглядит в гномтерминале убунты

Ну так, в гномтерминале как и в Konsole тоже не видны чистые цвета. При этом, к примеру, MC нормально работает, ему все цвета доступны.

Тут явно какая-то трабла с интерпретацией цветов в TTY.

**Comment by elfmz** [comment]
Что значит все цвета, цвета зависят от настроек терминала, терминал их переназначает как ему угодно. Вот видимо цветовая схема вашего терминала для миднайта подходит норм, а для far2l не норм. Идите в настройки терминала и поменяйте палитру цветов, вот в гномтерминале как оно выглядит, один и тот же far2l становится разных цветов в зависимости от настроек терминала:
![image](https://user-images.githubusercontent.com/20957349/199028260-837d2f78-e79d-4089-a248-8be4aac81a3c.png)
![image](https://user-images.githubusercontent.com/20957349/199028297-68e555a0-e1c3-4034-a786-8fdc09fdfbb0.png)
![image](https://user-images.githubusercontent.com/20957349/199028369-dc3aecb2-f2ce-4239-84dc-b26958ee44f5.png)

**Comment by elfmz** [comment]
На миднайт эти настройки к слову тоже имеют влияние:
![image](https://user-images.githubusercontent.com/20957349/199030939-cc2c8b1b-e3ce-4084-85b6-7be21ea31b08.png)
![image](https://user-images.githubusercontent.com/20957349/199031001-d49c4ae7-8f37-4829-b683-ad1960dc1d66.png)
![image](https://user-images.githubusercontent.com/20957349/199031085-21058f91-8804-40c7-b55d-45db84e37ed0.png)
просто базовые цвета испольщуемые миднайтом для своих элементов отличаются от far2l, и дефолтовые цветовые палитры терминала очевидно подогнаны так чтобы широко известные консольные апликухи в них хорошо смотрелись. Под far2l их не подгоняли.

**Comment by unxed** [comment]
Можно сделать для фара тему под миднайт 🤷🙂

**Comment by xintrea** [comment]
Поставил тему "Белый на черном" в Konsole, цвета стали нативными. Задачу можно закрывать.

**Comment by xintrea** [comment]
> Можно сделать для фара тему под миднайт
Что-то я не нашел в far2l интерфейса выбора тем.

**Comment by elfmz** [comment]
> Что-то я не нашел в far2l интерфейса выбора тем.
Вообще в wx версии far2l есть ~/.config/far2l/palette.txt где можно вручную задавать какими должны быть цвета, но вероятно unxed имел ввиду что можно в Options/Color повыбирать цвета точно такие же какие миднайт использует для аналогичных элементов своего интерфейса и тогда фар будет выглядеть точно как миднайт (в любых палитрах терминала)

**Comment by unxed** [comment]
В терминалах, оказывается, можно escape последовательностями выставлять цвета палитры. Например, чтобы tty far2l выглядел так же, как wx версия, можно [сделать так](https://github.com/elfmz/far2l/issues/1385#issuecomment-1304657386)
