### ISSUE TITLE
Truncated special files (in /proc, /sys/kernel etc) content when viewing them with far2l

### ISSUE THREAD

**Issue by TrNullFree** [elfmz/far2l#1384]
Special files (in /proc, /sys/kernel etc) content truncated when viewing them with far2l F3.
Shows only what fits on one screen. PgUp/PgDn, other navigation keys do not work.
MC shows them correctly.
FAR2L, version 2.4.1-ea8fdf19-beta Linux x86_64, Ubuntu 22.10 

Example
Try view (F3) file  /proc/modules.
On my system show only 52 lines instead of 149.

**Comment by elfmz** [comment]
Now viewer will pre-read up to 16 megs of content for such files, should be enough, right? (I had to set some sane limit otherwise it would hog all memory if some file like pipe will generate infinite stream)

**Comment by TrNullFree** [comment]
Works amazing. Thanks!
