### ISSUE TITLE
[str-visual] use palette from palette.ini in tty backend also

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1385]
Now, then truecolor is supported, we may also use palette from palette.ini in tty backend for consistent interface in both backends. May be as switchable option (to save tty traffic on slow connections).

**Comment by elfmz** [comment]
it will be used only for in-terminal apps, not for interface of far2l itself, and in case true color not used then old 16 color sequences will be used

**Comment by elfmz** [comment]
That means that in case using far2l TTY - terminal's palette settings will be used. It can be either hosting wx far2l palette.ini either some other terminal's color settings/ Not sure that need to complicate this with extra palette with extra overhead for it..

**Comment by unxed** [comment]
When displaying the far2l's interface, can we set two color values for the screen cells, both the old single-byte and the new RGB (based on palette.ini)? In that case tty backend will be able also to send both colors to terminal, so old 16-color terminals will show interface as it looks now, and more sophisticated and modern terminals will show interface just as it looks in wx.

**Comment by elfmz** [comment]
yes. The question is not if ts possible, but isnt its a unneeded complication that has significant traffic overhead .. But as option its possible..

**Comment by unxed** [comment]
Only as option, disabled by default, of course! And enabling it should show notification about traffic increase.

Its just an answer to complains why mc looks so fancy in tty, but far2l does not

**Comment by ivanshatsky** [comment]
This can be very helpfull in some scenarios (e.g. quick picture preview). I agreed this isn't needed for everyone and, if been realized, shoud be realized as an option, disabled by default.

**Comment by elfmz** [comment]
unxed about ability to redefine far2l's colors according to (yet undocumented) palette.ini file with using truccolor support introduced recently.
Pictures preview already fine (on that branch but will merge soon, looks its stable enough):
![image](https://user-images.githubusercontent.com/20957349/200127702-8ecb433f-c5f4-42b6-97ba-01c5f7682ff1.png)

**Comment by unxed** [comment]
Already noticed, great job! At the same time, in this ticket, I mean exactly the colors of far2l's interface itself.

**Comment by unxed** [comment]
Maybe we also should set image preview options depending on available color resolution, touch #901

**Comment by unxed** [comment]
Terminal's color palette of basic 16 colors [can also be changed](https://bbs.archlinux.org/viewtopic.php?pid=1557198#p1557198) via escape sequences. For example, this
`echo -ne "\e]4;3;#ff0000\a"`
changes color number 3 to red. It do work at least at gnome terminal.

Can far2l use this method to set its own color palette in tty mode?

**Comment by unxed** [comment]
For example, this script sets the default far2l's palette in terminal (NB, red and blue values are reversed here!):
```
#!/bin/bash
echo -ne "\e]4;0;#000000\a"
echo -ne "\e]4;1;#800000\a"
echo -ne "\e]4;2;#008000\a"
echo -ne "\e]4;3;#808000\a"
echo -ne "\e]4;4;#000080\a"
echo -ne "\e]4;5;#800080\a"
echo -ne "\e]4;6;#008080\a"
echo -ne "\e]4;7;#C0C0C0\a"
echo -ne "\e]4;8;#808080\a"
echo -ne "\e]4;9;#FF0000\a"
echo -ne "\e]4;10;#00FF00\a"
echo -ne "\e]4;11;#FFFF00\a"
echo -ne "\e]4;12;#0000FF\a"
echo -ne "\e]4;13;#FF00FF\a"
echo -ne "\e]4;14;#00FFFF\a"
echo -ne "\e]4;15;#FFFFFF\a"
```

**Comment by unxed** [comment]
For my "default_dark" theme to look nice in tty, run far2l via following wrapper script:
```
#!/bin/bash
echo -ne "\e]4;0;#080808\a"
echo -ne "\e]4;7;#C0C0C0\a"
echo -ne "\e]4;8;#121212\a"
far2l --tty
```

**Comment by elfmz** [comment]
I've used OSC4 approach thats not able to setup separate bk/fg so - c'est la vie.
BTW recent;y i added OSC4 also to in far2l's VT but extended it in obvious way: \e]4;3;#FORE;#BACK\a so when running far2l inside far2l both 'sides' of colors are applied from other side.

**Comment by unxed** [comment]
but in my example foreground and background palettes are the same

**Comment by elfmz** [comment]
then indeed strange.

**Comment by unxed** [comment]
afaik, some two RGB components are swapped in palette.ini format compared to OSC4 format. but do not remember exact ones

**Comment by unxed** [comment]
wx:

![изображение](https://user-images.githubusercontent.com/1151423/210668235-2db9d77a-fe1e-4e29-a66e-3b60a54c6e41.png)

gnome terminal:

![изображение](https://user-images.githubusercontent.com/1151423/210668254-919a6073-ea39-42c3-a002-82be0e9c0076.png)

palette.ini above

**Comment by unxed** [comment]
mint 21 cinnamon x64

**Comment by elfmz** [comment]
check now...

**Comment by unxed** [comment]
confirming fixed, thanks!

**Comment by unxed** [comment]
Looks like KDE's Konsole does not support OSC 4, am I right?

**Comment by unxed** [comment]
Touch #914
