### ISSUE TITLE
Теряется информация при копировании на smbfs

### ISSUE THREAD

**Issue by pupupupupup** [elfmz/far2l#1387]
Имеем серьезнейшую проблему с потерей данных.

К предыдущему тикету не подходит - не связано с размером файлов и засыпаниями NAS.

Дано. Убунта 22.04, SMBFS, на принимающей стороне NAS D-Link ShareCrnter (323), Current firmvare version 2.2
Места на диске мало, гиг этак 25. Копируем на него 28. Файлы копируются. Очень долго в конце, но копируются. При этом все, что не влезло - становится нулевой длины. Первый файл, который не поместился - усекается по длине. Все последующие получаются нулевой длины.
Отдельная тема (в этот раз не поймал) - когда не хватает места и под запись в оглавление. Тогда файловую операцию и не прервать.
Как будем ловить ситуацию? Я могу погонять у себя исполняемый файл с отладочной информацией, но собрать его сам в ближайшие дни не смогу - винигрет из GCC разных версий мне это не позволит.
Да, ФС на насе корректно отрабатывает недостаток места - при попытке копирования по cp - No space left on device

**Comment by elfmz** [comment]
а дело точно в far2l? нету ли бага в самбе на сервере изза которого он не сообщает об ошибке при нехватке места?

**Comment by elfmz** [comment]
хотя конечно иметь такой баг в самбе было бы стыдно для NASа.. пусть и старого

**Comment by pupupupupup** [comment]
mc, cp и оболочка копируют сообщают об отсутствии места. чуть позже сделаю
скриншоты.

сб, 5 нояб. 2022 г., 21:02 elfmz ***@***.***>:

**Comment by elfmz** [comment]
ну чтож, у меня как раз завалялся на антресолях DNS-325 воткну в него терабайтный винт и попробую занять все место, потому как с простыми дисками не воспроизводится

**Comment by elfmz** [comment]
Короче с самбой в данном случае возвращается ошибка при закрытии файлового дескриптора (close) а не при непосредственно записи (write) как происходит с другими фс, потому и не репортится.

**Comment by elfmz** [comment]
Это похоже баг в клиенте, а не сервере как я думал вначале. Так как NetRock'овый смб протокол (у него своя реализация на libsmbclient) нормально ловит ошибку записи на самбу

**Comment by pupupupupup** [comment]
Я так понимаю, что сегодня скачаный мастер с исправлениями на эту тему?

Стало еще хуже. Если раньше последний невместившийся файл был неправильной длины, а остальные - 0, то теперь все веселее.
Оригинальные файлы:
 310976 Andor.S01E00.WEBDL.720p.RGzsRutracker.mkv
4856280 Andor.S01E01.WEB-DL.2160p.RGzsRutracker.mkv
4340164 Andor.S01E02.WEB-DL.2160p.RGzsRutracker.mkv
4949924 Andor.S01E03.WEB-DL.2160p.RGzsRutracker.mkv
4789284 Andor.S01E04.WEB-DL.2160p.RGzsRutracker.mkv
4199060 Andor.S01E05.WEB-DL.2160p.RGzsRutracker.mkv
5444776 Andor.S01E06.WEB-DL.2160p.RGzsRutracker.mkv
5098376 Andor.S01E07.WEB-DL.2160p.RGzsRutracker.mkv

Битые файлы - 
      0 Andor.S01E00.WEBDL.720p.RGzsRutracker.mkv
4856832 Andor.S01E01.WEB-DL.2160p.RGzsRutracker.mkv
4340736 Andor.S01E02.WEB-DL.2160p.RGzsRutracker.mkv
4950016 Andor.S01E03.WEB-DL.2160p.RGzsRutracker.mkv
4790272 Andor.S01E04.WEB-DL.2160p.RGzsRutracker.mkv
  33792 Andor.S01E05.WEB-DL.2160p.RGzsRutracker.mkv
5445632 Andor.S01E06.WEB-DL.2160p.RGzsRutracker.mkv
   1024 Andor.S01E07.WEB-DL.2160p.RGzsRutracker.mkv

В результате 0, 5, 7 файлы биты. При чем по разному.

**Comment by elfmz** [comment]
у вас наверное опция Disable write cache была включена, там еще проверки надо было добавить, попробуйте сейчас.. если не поможет - попробуйте без Disable write cache

**Comment by elfmz** [comment]
...а вот на 22й убунте воспроизвелось. Чтож они там в самбе наворотили..

**Comment by elfmz** [comment]
а нет не воспроизвелось, это я старый far2l по ошибке запустил, с ним воспроизвелось) а с новым в текущей версии - все норм (возможно последний дофикс помог, но я несколько сомневаюсь в этом)

**Comment by pupupupupup** [comment]
Только что скачал версию, текущая ошибка исчезла, спасибо. Буду наюлюдать дальше.
