### ISSUE TITLE
putty with far2l extensions patch have problems with built-in VT after lastest far2l changes

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1389]
Steps to reproduce:

1. Download patched putty (https://github.com/unxed/putty4far2l)
2. Make connection to server
3. Run far2l
4. Run any command in far2l's built-in terminal (`echo 1` for example)
5. No output seen, Ctrl+C or ESC not working, terminal hangs

Has something changed in the extensions protocol?

**Comment by unxed** [comment]
Fixed in putty4far2l https://github.com/unxed/putty4far2l/commit/23cad487b9b154293579f8752db971ba8b88e7e0

**Comment by unxed** [comment]
Color bit detection sequence support added to putty4far2l:
https://github.com/unxed/putty4far2l/commit/24991b08a05162133b49d2ebbf837853b013f28e

**Comment by unxed** [comment]
Relevant kitty issue:
https://github.com/cyd01/KiTTY/issues/431

**Comment by elfmz** [comment]
Actually if it causes big problems it likely can be avoided, and relay only to TERM/TERMCOLOR variables.
FARTTY_INTERRACT_GET_COLOR_PALETTE was added cuz potentially there is possibility that TTY far2l running remote may go background and then will be reconnected but to far2l running with different 'visual ablities'
But however its anyway better for implementation to explicitly reject unknown codes, as they will be added from time to time..

**Comment by unxed** [comment]
>  But however its anyway better for implementation to explicitly reject unknown codes, as they will be added from time to time..

Behaving just like this since
https://github.com/unxed/putty4far2l/commit/23cad487b9b154293579f8752db971ba8b88e7e0
and
https://github.com/unxed/putty4far2l/commit/506b2c2e41cd6c7915e2af74e146921b20fda031
