### ISSUE TITLE
coloring artifacts with truemod

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1391]
1. open this file in editor
```
<?php

require_once('./demo.conf');

define('TEST', TRUE);

// Init session
init_session(TRUE);


// test

```

You see unneeded black background at random part of a file
![image](https://user-images.githubusercontent.com/1151423/200353438-f62d8ded-e125-4233-8bc6-c7d7db81c413.png)

2. Try to select and deselect line `init_session(TRUE);`
3. Try to type something below this line

**Comment by elfmz** [comment]
seems its only in TTY version, right? so its actually but in TTY backend's truecolor support but not colorer..

**Comment by unxed** [comment]
> seems its only in TTY version, right?

yep

**Comment by unxed** [comment]
thanks!
