### ISSUE TITLE
Broken "Infopanel settings" dialog

### ISSUE THREAD

**Issue by cycleg** [elfmz/far2l#140]
Его так ловко сплющило, что остались всего две кнопки, да и те не влезают.
![infopanelsettings](https://cloud.githubusercontent.com/assets/22474464/19411076/75bb2faa-930b-11e6-8283-d1ef34408efb.png)

**Comment by elfmz** [comment]
Его сплющило по той причине что настройки которые там были - были удалены по причине неподходящести для линукса. вобщемто и сам диалог можно удалить по той же причине, но вдруг он еще пригодится..
