### ISSUE TITLE
Не удаляются файлы с tmpfs

### ISSUE THREAD

**Issue by Katarn** [elfmz/far2l#1401]
Создаю такой диск в памяти:

```bash
mount -t tmpfs tmpfs -o size=1G /tmp
```

Копирую на него что-нибудь. Пытаюсь удалить, получаю:

```
╔══════════════════ Error ═══════════════════╗
║        Неизвестная ошибка 256 (256)        ║
║           Cannot delete the file           ║
║                  /tmp/123                  ║
╟────────────────────────────────────────────╢
║ { Retry } [ Skip ] [ Skip all ] [ Cancel ] ║
╚════════════════════════════════════════════╝
```

Такая же проблема если создать на этом диске файл напрямую (Shift+F4).

```bash
rm /tmp/123
```

Работает норм.

Far2l свежий, из мастера.

**Comment by elfmz** [comment]
Сделал в убунте `sudo mount -t tmpfs tmpfs -o size=1G /xxx` после чего скопировал и удалил файл - все сработало норм.
У вас проблема воспроизводится если монтировтать не /tmp а /чтотоеще? Может есть какие то особенности не упомянутые?

**Comment by elfmz** [comment]
Начнем с результата `cat /etc/mtab | grep '/tmp'` ?

**Comment by elfmz** [comment]
а что за система?

**Comment by Katarn** [comment]
Gentoo. И кстати, сейчас обнаружил, что именно под рутом не удаляется. Под обычным пользователем - без проблем.

**Comment by Katarn** [comment]
Так, всё. Это не от tmpfs зависит. Под рутом не удаляются любые файлы с любой ФС. Точнее так, F8 - ошибка 256, а Alt+Del - ошибки нет. Что-то с корзиной. Из нюансов о которых вспомнил - запускаю в режиме `--tty`.

**Comment by elfmz** [comment]
`gio trash -f -- ` в смысле у вас включена опция Options/System settings/Delete to recycle bin? а если ее выкл?

**Comment by Katarn** [comment]
> `Что-то с корзиной` в смысле у вас включена опция Options/System settings/Delete to recycle bin? а если ее выкл?

Верно. Если выключить, то удаляется без ошибок.

**Comment by elfmz** [comment]
хм у меня все еще работает норм даже с удалением в корзину
и тем не менее, что выдает у вас команда `gvfs-trash -f -- /tmp/ЧТОНИБУДЬ` будучи запущенной из рутового шелла?

**Comment by Katarn** [comment]
```bash
$ gvfs-trash -f -- /tmp/123
bash: gvfs-trash: команда не найдена
```

Погуглив, узнал что `gvfs-trash` в Gentoo уже выпилен как депрекейтед, заменён на `gio trash`.

```bash
$ gio trash -f -- /tmp/123
gio: file:///tmp/123: Не удалось удалить файл /tmp/123 в корзину, из-за ограничений файловой системы

$ cat /etc/mtab | grep tmp
/dev/sda5 /tmp ext4 rw,noatime,nodiratime,discard 0 0

$ touch /123
$ gio trash -f -- /123
gio: file:///123: Удаление в корзину на системных томах не поддерживается
```

Последнее сообщение можно словить если файл `123` создавать где угодно - в `/etc`, `/usr` и так далее, за исключением разве что `/home/.../...` и `/root`.

Возможно что дело и не в far2l, но если так, то, может, сделать обработку такой ситуации и удалять не в корзину? Предупредив предварительно пользователя.

**Comment by Katarn** [comment]
Кстати, обновился из мастера, теперь выводится сообщение "Удаление в корзину на системных томах не поддерживается". Половина проблемы решена. Не хватает кнопки типа "Удалить мимо корзины".

**Comment by elfmz** [comment]
добавил такую кнопку

**Comment by Katarn** [comment]
Работает, спасибо!

**Comment by Katarn** [comment]
Кажется работает не совсем правильно - если на этом диалоге нажать Esc, то диалог закрывается и появляется снова.
