### ISSUE TITLE
[tty] Alt+latin_letters not recognized under xterm

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1405]
under gnome terminal everything is ok

**Comment by elfmz** [comment]
Отсюда https://invisible-island.net/xterm/manpage/xterm.html#VT100-Widget-Resources:activeIcon
Получается следующее
- есть некие VT100 ресурсы которые можно включать и выключать, но как именно - я не нашел
- есть ресурс eightBitInput который по дефолту включен и который именно это и ломает

**Comment by elfmz** [comment]
о нашел: xterm -xrm '*eightBitInput: false'

**Comment by unxed** [comment]
т.е. проблема не на нашей стороне, wontfix?
но он же что-то шлёт на эти клавиши даже без этой опции. может, это можно как-то парсить?

**Comment by elfmz** [comment]
Шлет в виде обычных кодов выставляя старший бит. Нет никаких спецпризнаков что это Alt+кнопка, а не просто текст в кодировке UTF8 или еще какой то. Собственно это можно наблюдать если просто запустить xterm и понажимать alt+чтонить

**Comment by unxed** [comment]
тогда закрываю как wontfix
