### ISSUE TITLE
GetConsoleScreenBufferInfo

### ISSUE THREAD

**Issue by shmuz** [elfmz/far2l#1406]
В текущем far2l (сегодня делал pull и собирал) функция `GetConsoleScreenBufferInfo` возвращает `TRUE`, но в структуре `srWindow` все 4 члена заполнены нулями.
- Раньше нули были только в `Left` и `Top`, а теперь также в `Right` и `Bottom`.
- Естественно, использовать её в плагинах теперь не получается.
- В то же время, `ACTL_GETFARRECT` работает.
- Может я что-то делаю не так, и в прежних билдах Фара оно у меня случайно работало?

**Comment by elfmz** [comment]
Изменились системные структуры объявленные в WinCompat.h - бинарная совместимость сломана, надо все пересобирать с новыми хедерами
В частности в CONSOLE_SCREEN_BUFFER_INFO::wAttributes стал 64 бита (был 16), так же растолстели до 64 бит оба поля в CHAR_INFO...

**Comment by elfmz** [comment]
И да, все функции которые принимали 16 битные значения консольных аттрибутов в аргументах - принимают теперь 64х битные значения там же. Надо же было както туда запихать два 24хбитных RGB..

**Comment by shmuz** [comment]
ОК, спасибо, понятно. Я не пересобирал с новыми хедерами.

**Comment by unxed** [comment]
> И да, все функции которые принимали 16 битные значения консольных аттрибутов в аргументах - принимают теперь 64х битные значения там же. Надо же было както туда запихать два 24хбитных RGB..

Т.е. plugin api тоже изменился, выходит?

**Comment by unxed** [comment]
у меня там просто биндинг паскалевский лежит на гитхабе, просто как экспериментальный проект «могу ли я сделать биндинг plugin api для другого языка». там обновление хедеров не прокатит, там свои хедеры, надо руками править. вот бы знать, что конкретно и где поменялось.

**Comment by elfmz** [comment]
Сам по себе апи к far2l вроде не поменялся так как в нем вроде не юзаются ни CONSOLE_SCREEN_BUFFER_INFO ни CHAR_INFO. Точнее указатель на CHAR_INFO присутсвует в FarDialogItem в виде одного из вариантов использования Param, но я за все время ни разу не встречался с таким его использованием..
Поменялись именно WINPORT(...) функции которые используют CHAR_INFO, CONSOLE_SCREEN_BUFFER_INFO и прочие у которых WORD wAttributes гдето светится в аргументах - теперь там DWORD64 а не WORD.

**Comment by elfmz** [comment]
впрочем хотя существующие фаровские АПИ не поменялись, но были добавления - ECTL_ADDTRUECOLOR, ECTL_GETTRUECOLOR, StrCellsCount, StrSizeOfCells

**Comment by elfmz** [comment]
@shmuz вчера еще закомитил кое что чо может повлиять: https://github.com/elfmz/far2l/commit/064657f6638bfdc01122e92411a190e56d4c455d#diff-9d43b2a52caa04f89618ce27c413821954c3383fd2fdfc7205bca25586070e23L683
- оригинальный GUID был скопирован из виндовых хедеров, а под виндой long - это всегда 32 бита, в отличии от линукса где _обычно_ sizeof(long) == sizeof(void *)

**Comment by shmuz** [comment]
@elfmz  спасибо, надо будет проверить.
