### ISSUE TITLE
[improvement suggestion] make priviledges elevation dialog visually distinct when entering / confirming sudo passowrd.

### ISSUE THREAD

**Issue by dredkin** [elfmz/far2l#1408]
Now when asking for elevated rights, far2l has two types of the dialog:

1. Enter sudo password 
2. Confirm sudo password

But they look identically and you have to carefully read the message to make the right action: enter the pass or just press enter. It is inconvenient and may lead to confusion when the wrong action is undertaken.

I propose to make them visually distinct. Fore example, when showing "Confirm" dialog, use another background color - grey or green or something instead of black.

**Comment by akruphi** [comment]
+1 very useful suggestion

**Comment by elfmz** [comment]
check now if it feels better

**Comment by akruphi** [comment]
> check now if it feels better

Now, of course, it is better, but the differences in the confirmation dialog are still only in text (screenshots 1 and 2):
![1](https://user-images.githubusercontent.com/92621645/203026934-f1e92c1c-36bf-4ad3-b064-6a7daf02e8af.png)
![2](https://user-images.githubusercontent.com/92621645/203026996-e7ec9be7-1aeb-4b83-96d9-fe25b635adb0.png)
and it not prefect good for quickly recognize.

It would be better if the frame in the case when not required type password would be different, for example yellow or green (I made an example in GIMP, see the last pict):
![2+green](https://user-images.githubusercontent.com/92621645/203027050-b3e3bee5-58e7-4483-889d-044f4a012db7.png)

**Comment by elfmz** [comment]
May be yellow? Green is not very suitable for this kind of message IMHO..

**Comment by akruphi** [comment]
> May be yellow? Green is not very suitable for this kind of message IMHO..

YES! Yellow may be better.

**Comment by dredkin** [comment]
I agree that the different color would be good (just as I described). For me personally the choice of color is not important, I'd leave it to @elfmz .
BTW should I compile far from sources to check it or there are some binaries somewhere?

**Comment by elfmz** [comment]
now its yellow, so closed..
