### ISSUE TITLE
Unable to use "slash" key in macros

### ISSUE THREAD

**Issue by ivanshatsky** [elfmz/far2l#1410]
When a macro is being recorded using Ctrl+Shift+Dot, there is a possibility to assign it a key combination with the slash key (<kbd>/</kbd>), lets say <kbd>Ctrl</kbd>+<kbd>/</kbd>. In the "Press the desired key" dialog this key combination will be shown as `Ctrl/`, and after saving far2l settings it will appear in `key_macros.ini` file as `[KeyMacros/<area>/Ctrl/]` section. However this key combination will work only in the current session, and won't be recognized after restarting far2l.

One of the possible solutions can be renaming this key in the macro system, e.g. `ForwardSlash`.

**Comment by elfmz** [comment]
i have strong suspection that in original FAR2 there was same issue but with backslashes, but seems it was not hard to fix..

**Comment by ivanshatsky** [comment]
> i have strong suspection that in original FAR2 there was same issue but with backslashes

No (I explicitly tested it on Far 2 for Windows), because backslash key is referenced in a macro as `BackSlash` rather than `\` (see https://github.com/elfmz/far2l/blob/44a050763f98a08fa1f2c9f87ec8918be49ba526/far2l/src/console/keyboard.cpp#L278 vs https://github.com/elfmz/far2l/blob/44a050763f98a08fa1f2c9f87ec8918be49ba526/far2l/src/console/keyboard.cpp#L192), that's why I proposed to rename it to `ForwardSlash` (who knows what platforms far2l will be ported to and what special meaning will have forward slash character on those platforms).
