### ISSUE TITLE
Arrow keystroke repeating doesn't work in `notty` mode

### ISSUE THREAD

**Issue by asuiu** [elfmz/far2l#1411]
Can't get arrow, PgUp, PgDown keystrokes repeat working neither in panel view nor editor view while other keys repeating works fine (letters, tab, space, backspace, and etc.). 
It totally blocks navigation and editing. It doesn't work in editor, panels, and menu.

It perfectly works in `--tty` mode, but in `tty` mode don't work shortcuts like `Ctrl-Ins`, `Alt-Shift-Ins`.
Any idea?

- **Far version**: `far2l 2.4.1+git202211161837.d1fe7238~ubuntu22.04.1` installed from launchpad.
- **OS**: `Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux` - Ubuntu 22.04.1 LTS on WSL2/Windows 11

**Comment by asuiu** [comment]
Related issue: https://github.com/elfmz/far2l/issues/325
was fixed by a commit specific for MacOS. Maybe it can be replicated for WSL2?

**Comment by unxed** [comment]
See #1659

Check now, please!

**Comment by atolismesh** [comment]
Now it works! Thanks!
(WSL2, W11, Ubuntu 23.04)
