### ISSUE TITLE
Сборка для Haiku

### ISSUE THREAD

**Issue by Katarn** [elfmz/far2l#1413]
Категорически не хватает нормального файлового менеджера в этой ОС. Насколько я вижу, far2l достиг определенного уровня независимости от окружения в котором работает. Было бы хорошо портировать его на Haiku сделав еще более универсальным, чем оригинальный проект. В самой ОС уже есть поддержка wxWidgets, что должно облегчить дело.

**Comment by Katarn** [comment]
https://github.com/haikuports/haikuports/tree/master/app-misc/far есть даже патчи для запуска, но они несколько лет не обновлялись.

**Comment by elfmz** [comment]
Вот а почему их пулреквестом не заслали? Оно бы потиху поддерживалось, ну ломалось бы по мелочи конечно... А ща поди разберись что куда переехало

**Comment by zelenoviy** [comment]
Приветствую. На неделе планирую заслать пулреквест. Собрал со свежих сорцов, в целом запустился-работает. Из забавного - интерфейс обновляется только по "четным действиям", т.е. нажал клавишу - ничего не происходит, нажал второй раз - оба изменения отобразились, дальше так же, ну или мышой над окном терминала пошевилить =)
Если есть мысли в какую сторону посмотреть, буду благодарен.

**Comment by unxed** [comment]
Похожих проблем в прошлом не припоминаю. Что-то новенькое. Тут слишком много возможных причин, от проблем с буферизацией ввода и цепочкой обработки событий до ошибок в патчах адаптации под Хайку.

Первый вопрос, который возникает — у вас консольная версия, так? С xi или без? Скрин окна ответил бы на этот вопрос, там в заголовке это есть.

**Comment by unxed** [comment]
Ещё можно перед запуском фара сделать в терминале вот так:
export FAR2L_STD=far2l.log
И посмотреть в соседнем окне, падает ли в лог инфа о событии ввода после первого нажатия, когда интерфейс не обновляется.

**Comment by zelenoviy** [comment]
Ну очевидно что это какая то особенность/бага в терминале Хайку, осталось найти )

Консольная версия, без Xi, иксов в хайку вообще нету (ну как - есть в каком то смысле, но это ненативное).
>И посмотреть в соседнем окне, падает ли в лог инфа о событии ввода после первого нажатия

**Comment by zelenoviy** [comment]
![image](https://user-images.githubusercontent.com/10906622/204781430-76606b8d-4b5a-4ef7-a72a-67f0029623e1.png)

с мыши кстати управление вполне адекватное, F9 меню только не открыть, скрывается при движении мыши, пока закрыты все подменю, ну это мелочи

**Comment by unxed** [comment]
> нет, в логе сообщение появляется только после "четного" нажатия, сразу о двух

Вот и ответ, куда копать. Проблемка где-то между терминалом и обработкой ввода в tty бэкенде. Сейчас выложу небольшу программку, которая показывает, что приходит от терминала в приложение на каждое нажатие клавиши. Попробуйте скомпилировать и погонять в том же терминале, и сравните с поведением в каком-нибудь gnome terminal. Это может дать дополнительную информацию

**Comment by unxed** [comment]
Вот, попробуйте запустить эту штуку в том же терминале, и посмотреть, как она на разные кнопки реагирует. Если проблема с терминалом — мы об этом узнаем.

```
#include <termios.h> 
#include <assert.h>
#include <errno.h>
#include <signal.h>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <stdlib.h> 
#include <stdio.h> 
#include <unistd.h> 


int main()
{
    struct termios _ts = {};
	int _ts_r = tcgetattr(1, &_ts);
	if (_ts_r == 0) {
		struct termios ts_ne = _ts;
		//ts_ne.c_lflag &= ~(ECHO | ECHONL);
		cfmakeraw(&ts_ne);
		if (tcsetattr(1, TCSADRAIN, &ts_ne ) != 0) {
			perror("TTYBackend: tcsetattr");
		}
	}


//	fprintf(stderr, "\x1b[?66h");
//	fprintf(stderr, "\x1b[?1061h");
	fprintf(stderr, "\x1b[?1049h");
//	fprintf(stderr, "\x1b[?1060h");
	fprintf(stderr, "\x1b[?1000h");
	fprintf(stderr, "\x1b[?1001h");
	fprintf(stderr, "\x1b[?1002h");
//	fprintf(stderr, "\x1b[?1003h");
//	fprintf(stderr, "\x1b[?1051h");

	for (;;) {
		char ch = 0;
		if (read(0, &ch, 1) <= 0) break;
		if (ch <= 0x20 || ch == 0x7f) {
			if (ch == 0x1b) fprintf(stderr, " ");
			fprintf(stderr, "\\x%02x", (unsigned int)(unsigned char)ch);
		} else {
			fprintf(stderr, "%c", ch);
		}
		//if (ch == 0x0d) break;
	}
	fprintf(stderr, "\x1b[?1049l");
}
```

**Comment by zelenoviy** [comment]
![image](https://user-images.githubusercontent.com/10906622/204785566-b70f627a-22b4-497c-a316-9ec48e885850.png)

отображает сразу по нажатию
qwerty esc верх низ право лево пробелы потом мышю провел над терминалом
по enter вышел, и после выхода терминал ломается, не отображает вводимые символы, хотя вводит, вот последствия ввода-вывода ls до и после запуска теста
![image](https://user-images.githubusercontent.com/10906622/204788098-bdd58b7a-f56c-4061-a0ae-c635fced4041.png)

**Comment by unxed** [comment]
Любопытно. Терминал самого фара на такую же последовательность отдаёт вот такое:
```
qwerty \x1b \x1b[A \x1b[B \x1b[C \x1b[D\x20\x20\x20\x20 \x1b[MCV5 \x1b[MCX5 \x1b[MCW5
```
Но это едва ли похоже на причину обработки только чётных нажатий.

> после выхода терминал ломается

Поправил код утилитки, чтобы не ломался после выхода.

**Comment by unxed** [comment]
> отображает сразу по нажатию

Выходит, проблема, всё же, скорее, на стороне фара, чем на стороне терминала.

**Comment by zelenoviy** [comment]
в mc все нормально, запустил прям после фара, все ок

**Comment by zelenoviy** [comment]
>Поправил код утилитки, чтобы терминал не ломался после выхода.

поправилось, правда теперь после выхода терминал продолжает валить события от движения мыши над ним )
![image](https://user-images.githubusercontent.com/10906622/204793805-d712ba20-46ca-4f63-93c4-d6ef22039022.png)

**Comment by unxed** [comment]
А если раскомментировать эту строчку:
```
//fprintf(stderr, "ReaderThread: CHAR 0x%x\n", (unsigned char)c);
```
в `TTYBackend.cpp`
, повторить эксперимент и снова скинуть лог?

**Comment by unxed** [comment]
> правда теперь после выхода терминал продолжает валить события от движения мыши над ним

поправил это тоже

**Comment by unxed** [comment]
А если в `TTYBackend.cpp` после этой строчки:
```
//fprintf(stderr, "ReaderThread: CHAR 0x%x\n", (unsigned char)c);
```
дописать такое:
```
fprintf(stderr, "ReaderThread: ");
for (int i=0; i<rd; i++) { fprintf(stderr, "%c", buf[i]); }
fprintf(stderr, "\n");
```

, а потом повторить эксперимент и снова скинуть лог?

**Comment by zelenoviy** [comment]
возможно закоменченый код устарел? нету там переменной "c" 
сделал fprintf(stderr, "ReaderThread: CHAR %s\n", buf);
по первому нажатию ничего, по второму -

```
ReaderThread: CHAR AA
MapVirtualKey(0x26, 0x0)
ConsoleInput::Enqueue: # 0 26 100 DOWN
ConsoleInput::Enqueue: # 0 26 100 UP
MapVirtualKey(0x26, 0x0)
ConsoleInput::Enqueue: # 0 26 100 DOWN
ConsoleInput::Enqueue: # 0 26 100 UP
```

**Comment by zelenoviy** [comment]
воткнул отладку после select и  до/после read
после первого нажатия select отрабатывает, доходит до вызова read 
ssize_t rd = os_call_ssize(read, _stdin, (void*)buf, sizeof(buf));
и на нем висит до второго нажатия

первое нажатие

```
ReaderThread: SELECT 1
ReaderThread: read -> 

```
второе нажатие
```
ReaderThread: read <- 
ReaderThread: CHAR BB
MapVirtualKey(0x28, 0x0)
ConsoleInput::Enqueue: # 0 28 100 DOWN
ConsoleInput::Enqueue: # 0 28 100 UP
MapVirtualKey(0x28, 0x0)
ConsoleInput::Enqueue: # 0 28 100 DOWN
ConsoleInput::Enqueue: # 0 28 100 UP
```

**Comment by zelenoviy** [comment]
в общем опытным путем удалось выяснить - проблема вылезает при чтении больше одного символа в read после вызова tcsetattr(1, TCSADRAIN...)
в тестовой программе подтверждается

**Comment by zelenoviy** [comment]
в общем опытным путем удалось выяснить - проблема вылезает при чтении больше одного символа в read 
в тестовой программе подтверждается

		char buf[0x1000];
		if (read(0, (void*)buf, sizeof(buf)) <= 0) break;
read выходит только после ввода 4х (!?) символов
меняем sizeof(buf) на 1 - читает посимвольно нормально

убираем tcsetattr(1, TCSADRAIN...) в начале - read до нажатия enter не выходит, но консоль отображает символы

**Comment by unxed** [comment]
ну можно в качестве временного костыля читать по одному символу именно на haiku

**Comment by elfmz** [comment]
> воткнул отладку после select и до/после read
> после первого нажатия select отрабатывает, доходит до вызова read
> ssize_t rd = os_call_ssize(read, _stdin, (void*)buf, sizeof(buf));
> и на нем висит до второго нажатия

Похоже на баг в хайку.. Раз select вернулся то read не должен зависать.. Тем более что там явно есть что читать. По вашему описанию похоже что select каким о образом сбрасывает флаг читабельности у дескриптора TTY. Спасибо хоть данные не стирает из него... По идее можно написать минимизированную аппликуху и отлаживаться в ней.

**Comment by elfmz** [comment]
можно попробовать переделать на poll (если он есть в haiku) но чтото мне подсказывает что баг там гдето глубже чем реализация самого select

**Comment by zelenoviy** [comment]
не, селект не причем, баг да, гдето в TTY

```
#include <termios.h> 
#include <assert.h>
#include <errno.h>
#include <signal.h>
#include <fcntl.h>
#include <sys/ioctl.h>
#include <stdlib.h> 
#include <stdio.h> 
#include <unistd.h> 


int main()
{
    struct termios _ts = {};
	int _ts_r = tcgetattr(1, &_ts);
	if (_ts_r == 0) {
		struct termios ts_ne = _ts;
		//ts_ne.c_lflag &= ~(ECHO | ECHONL);
		cfmakeraw(&ts_ne);
		if (tcsetattr(1, TCSADRAIN , &ts_ne ) != 0) {
			perror("TTYBackend: tcsetattr");
		}
	}

	for (;;) {
		char buf[0x1000];
		if (read(0, (void*)buf, sizeof(buf)) <= 0) { 
		//if (read(0, (void*)buf, 1) <= 0) {   // <- так работает
			fprintf(stderr, "!ERROR \n");
			break;
		}
		
		fprintf(stderr, "!R: ");
		fprintf(stderr, "%s", buf);

		if (buf[0] == 0x0d) break;
    	if (buf[0] == 0x0a) break;
	}
	
    if (tcsetattr(1, TCSADRAIN, &_ts ) != 0) {
    	perror("TTYBackend: tcsetattr");
    }
}
```

**Comment by elfmz** [comment]
то есть читать надо именно посимвольно? ну в качестве костыля работающего только в haiku сойдет, но в целом это не очень хорошо для перфоманса..

**Comment by unxed** [comment]
> Спасибо, что помогли поразбираться, буду тикет оформлять

Велкам! Ну и PR ждём, да :)

**Comment by zelenoviy** [comment]
так, ну вроде разобрался, местный терминал инициализирует termios с [VMIN]   = 4 
отсюда и по 4 символа минимум в тесте, откуда правда 2 в фаре - непонятно пока...
вопрос - где в фаре правильно будет переопределить этот аттрибут (tcsetattr) ?

**Comment by elfmz** [comment]
По идее в far2l/utils/src/TTYRawMode.cpp сразу после cfmakeraw
Кстати, cfmakeraw это должен делать сам, ибо согласно https://linux.die.net/man/3/cfmakeraw:
`cfmakeraw() sets the terminal to something like the "raw" mode of the old Version 7 terminal driver: **input is available character by character**, echoing is disabled, and all special processing of terminal input and output characters is disabled. The terminal attributes are set as follows:`

**Comment by zelenoviy** [comment]
И то верно, и именно этого он не делает в хайку

**Comment by unxed** [comment]
> На неделе планирую заслать пулреквест.

Как там? ;) Обидно будет, если наработки опять потеряются.

**Comment by zelenoviy** [comment]
Неделька затягивается, но надежда ещё не пропала )

**Comment by elfmz** [comment]
вроде пулреквест вмержен - можно закрывать...
