### ISSUE TITLE
lintian warning: no-manual-page [usr/bin/far2l]

### ISSUE THREAD

**Issue by idamir** [elfmz/far2l#1418]
No man page.
[far2l.1.zip](https://github.com/elfmz/far2l/files/10067480/far2l.1.zip)
Attached is a draft converted from help message with rules to precess it.

`DATE_LANG=en_US.UTF-8`
`DATE_FORMAT=%B %Y`
`include date-of-man-include.am`

**Comment by elfmz** [comment]
Note that far2l historically has its own contextual help system, so full duplication it with man doesnt look feasible/senseful. 'stub' man page is actually possible, like your draft plus offer to run app and press F1 wherever in its TUI..

**Comment by idamir** [comment]
Про собственную контекстную помощь я в курсе. Фарой пользовался с 2000 года (1.70 beta) по 2021 год под разными версиями Windows.

Тогда попробую добавить man-заглушку в форме pr.
