### ISSUE TITLE
lintian warning: missing-license-paragraph-in-dep5-copyright public-domain [debian/copyright:209]

### ISSUE THREAD

**Issue by idamir** [elfmz/far2l#1419]

**Comment by elfmz** [comment]
Hm, line 209 is a 'License: public-domain' right? Then according to https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/ :
```
7.1.1. Public domain
The License short name public-domain does not refer to a set of license terms. There are some works which are not subject to copyright in any jurisdiction and therefore no license is required for any purpose covered by copyright law. This short name is an explicit declaration that the associated files are “in the public domain”.
```

**Comment by alexmyczko** [comment]
meanwhile far2l made it into debian

**Comment by elfmz** [comment]
so there is no issue? may close?

**Comment by alexmyczko** [comment]
https://udd.debian.org/lintian/?email1=&email2=&email3=&packages=far2l&ignpackages=&format=html&lt_error=on&lt_warning=on&lt_information=on&lt_pedantic=on&lintian_tag=#all

not in the pkg in debian

**Comment by idamir** [comment]
close
