### ISSUE TITLE
mc inside far2l's VT does not receive mouse events

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1427]
1. run far2l wx
2. run mc inside internal VT
3. try do make any action using mouse

compare with mc's behavior in GNOME Terminal

**Comment by unxed** [comment]
same problem with tty backend: mouse not working

info about xterm mouse tracking escape sequences:
https://stackoverflow.com/a/44170252

**Comment by elfmz** [comment]
yep it just not implemented.. still

**Comment by unxed** [comment]
confirming fixed
