### ISSUE TITLE
terminal-level pasting of multi-line text auto indent problem

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1429]
1. open far2l wx
2. open this file in editor
[demo.txt](https://github.com/elfmz/far2l/files/10086966/demo.txt)
3. copy entire content to clipboard
4. run `far2l --tty --nodetect`
5. open editor
6. press Shift+Ins
7. You will see
```
 Line 1
  Line 2
   Line 3
```
expected result:
```
 Line 1
 Line 2
 Line 3
```

How can it be fixed? For example, we can disable auto-indent feature if time between Enter and previous char received is less then typical delay between hand made key presses (only if we are in tty mode with neither ttyx nor far2l extensions available).

**Comment by elfmz** [comment]
funny solution: but may be revert old sending of \n chars but treat them specially in editor - like line feed that doesnt care about auto indentation?
But need to check that other significant text editing apps are OK about getting linefeeds... mcedit, as i understood, is ok..

**Comment by unxed** [comment]
Superseeded by #1430
