### ISSUE TITLE
Support "bracketed paste" in tty backend and internal VT

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1430]
1. open far2l wx
2. open this file in editor
[demo.txt](https://github.com/elfmz/far2l/files/10086966/demo.txt)
3. copy entire content to clipboard
4. run `far2l --tty --nodetect`
5. open editor
6. press Shift+Ins
7. You will see
```
 Line 1
  Line 2
   Line 3
```
expected result:
```
 Line 1
 Line 2
 Line 3
```

To fix that, we should enable "[bracketed paste](https://invisible-island.net/xterm/xterm-paste64.html)" mode to determine pastes and disable auto indent for them.
printf("\x1b[?2004h"); // enable
printf("\x1b[?2004l"); // disable

In "bracketed paste" mode pasted data will look like this:
```
 \x1b[200~content \x1b[201~
```

Works in GNOME Terminal, Konsole, iTerm2, Windows Terminal.

Related [wikipedia page](https://en.wikipedia.org/wiki/Bracketed-paste).

**Comment by elfmz** [comment]
wof so complicated (doge pic here), using \n instead of \r would be easier)

**Comment by unxed** [comment]
but guaranteed to work for almost everybody

**Comment by elfmz** [comment]
yep, but why that everybody didnt get such idea..

**Comment by unxed** [comment]
Anyway I appreciate any solution and will do as much testing as I can :)

**Comment by unxed** [comment]
turbo text editor fixed this without using bracketing. relevant commit:
https://github.com/magiblot/turbo/commit/125e749a42dbdb13479bf560a81

**Comment by elfmz** [comment]
timing solution is unreliable, bracketing looks better

**Comment by unxed** [comment]
one more advantage of bracketing is a possibility to seriously increase paste speed in editor: no need to do all event processing, encoding conversion and screen updating steps for each char, can just put everything inside brackets into editor's buffer and update screen one time. for other, non-editor controls common input processing scheme can be left.

**Comment by elfmz** [comment]
i dont think there is real problem with screen updates, TTY backend buffers them anyway

**Comment by unxed** [comment]
pasting 30kb this way takes 35 seconds even on local machine, maybe there is some other source of large delays

**Comment by unxed** [comment]
mc also uses bracketing:
https://midnight-commander.org/ticket/2661

**Comment by unxed** [comment]
> wof so complicated

Not so much, just 40 lines of code :) See #1432

**Comment by elfmz** [comment]
done
