### ISSUE TITLE
netrocks and dd-wrt router firmware ssh server

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1434]
Protocol used: scp (sftp is relatively hard to install on router)

Problems with NetRocks:
1) No list of remote files (copying a file from local to remote machine works ok, but list is still empty in NetRocks after copy)
2) Option "Working directory" not working (it is always home folder). Error message appears:
Query info fault - invalid option -- f
Failed object: /
Failed site: <scp:root@MY_IP>

mc (using "shell link" option) successfully shows file list of the root folder on same router.

SSH server on router: Dropbear server v2013.56

**Comment by elfmz** [comment]
What gives ls --help being executed in normal SSH?
PS There is a special case, similar to described by you. Thy change this: https://github.com/elfmz/far2l/blob/master/NetRocks/src/Protocol/SSH/ProtocolSCP.cpp#L634

**Comment by unxed** [comment]
> What gives ls --help being executed in normal SSH?

Nothing. Help is often excluded from embedded builds to save space, AFAIK

BTW, problem also happens with OpenWRT: https://askubuntu.com/a/1296334

**Comment by unxed** [comment]
Maybe it's better to detect Busybox by calling `busybox`?

**Comment by unxed** [comment]
changed to:
```
		ls_cmd.Execute("%s", "busybox");
		if (ls_cmd.Output().find("date") != std::string::npos
		  || ls_cmd.Error().find("date") != std::string::npos) {
```

works like a charm!

**Comment by elfmz** [comment]
Who knows what else busybox user may have...
`readlink /bin/sh` on that system gives busybox, i guess?

**Comment by unxed** [comment]
```
root@hascky:~# readlink /bin/sh
-sh: readlink: not found
```

May we just use both method of detection, `ls --help` and `busybox`?

**Comment by unxed** [comment]
```
root@myhost:~# strings $(which busybox) | grep \\\<BusyBox
syslogd started: BusyBox v1.21.0
BusyBox v1.21.0 (2013-04-01 09:26:04 CEST)
```

**Comment by elfmz** [comment]
what is printed by running busybox?

**Comment by unxed** [comment]
```
root@myhost:~# busybox
        [, [[, arp, ash, awk, basename, bash, cat, chmod, cmp, cp, cut, date, dc, dd, df, dirname, dmesg, dnsdomainname,
        du, echo, egrep, env, expr, false, fgrep, find, free, getopt, grep, gunzip, gzip, halt, head, hexdump, hostname,
        id, ifconfig, insmod, install, kill, killall, klogd, less, ln, logger, login, logread, ls, lsmod, md5sum, mkdir,
        mkfifo, mknod, more, mount, mv, nc, netstat, nslookup, pidof, ping, poweroff, printf, ps, pwd, reboot, rm, rmdir,
        rmmod, route, run-parts, rx, sed, sendmail, sh, sleep, sort, strings, stty, sync, syslogd, tail, tar, telnet,
        telnetd, test, time, top, touch, tr, traceroute, true, umount, uname, uniq, uptime, usleep, vconfig, vi, wc, wget,
        which, xargs, yes, zcat
```

**Comment by unxed** [comment]
oh, running "busybox" gives similar output on my ubuntu :(

may we just retry `ls` without `-f` if using `-f` fails?

**Comment by elfmz** [comment]
check commited approach.

**Comment by unxed** [comment]
works for me, great! but has risk of false positive detection if system has busybox installed, but it is not used as current shell

**Comment by unxed** [comment]
> if system has busybox installed, but it is not used as current shell

this can be detected by comparing output of `ls --help` and `busybox ls --help`. if result differs, busybox is installed, but not used as current shell

**Comment by elfmz** [comment]
-f needed mostly for performance reason (do not sort)

**Comment by unxed** [comment]
oh, I see `busybox` command working on ALL my ubuntu systems

**Comment by unxed** [comment]
```
root@myhost:~# ls -f 2>&1
ls: invalid option -- f
```

this looks to be the most reliable check

**Comment by unxed** [comment]
```
root@hascky:~# ls -f /somenonexistentfile7025193648
ls: invalid option -- f
```

this looks to be the most fast and reliable check

**Comment by elfmz** [comment]
wording 'invalid option' likely can be in other language or rephrased

**Comment by elfmz** [comment]
check now yet again..

**Comment by unxed** [comment]
still working!

**Comment by unxed** [comment]
another problem with scp on dd-wrt found: can not delete a file (empty folders are deleted ok; rm works on files ok also):

![изображение](https://user-images.githubusercontent.com/1151423/204111845-3e2e8acd-4975-4b17-be98-3de7cd5df6c7.png)

**Comment by unxed** [comment]
и ещё мелкий баг: после создания нового файла в редакторе по shift+f4 после выхода из редактора список сам не обновляется, надо ctrl+r делать

**Comment by elfmz** [comment]
а ща?

**Comment by unxed** [comment]
удаление и перемещение файлов починилось. а удаление папки с файлами (и даже пустой!) теперь даёт такое:
"invalid option -- d (255)"

баг с не-обновлением списка файлов при создании нового через shift+f4 пока остался

**Comment by elfmz** [comment]
что выдает на системе `rmdir --help; echo $?` ?

**Comment by unxed** [comment]
255

**Comment by unxed** [comment]
```
root@myhost:~# rmdir --help; echo $?
255
```

**Comment by elfmz** [comment]
ой блин.. могли бы хоть без ошибки завершится..

**Comment by unxed** [comment]
удаление починилось!

**Comment by unxed** [comment]
о, ещё смешное. scp->f7->esc-> Error: Success(0): Cannot create folder. если вместо esc нажать enter, то же самое.

**Comment by unxed** [comment]
> о, ещё смешное. scp->f7->esc-> Error: Success(0): Cannot create folder. если вместо esc нажать enter, то же самое.

починилось, спасибо! осталась штука с не-обновлением панели после создания файла в редакторе

**Comment by unxed** [comment]
ох, тут на другой версии dd-wrt на другом роутере снова те же проблемы. пустой список файлов, при попытке задать стартовую папку — «Query info failed - f»

far2l последний

**Comment by unxed** [comment]
на команду `busybox` этот роутер говорит `busybox: applet not found`

**Comment by elfmz** [comment]
what abous busybox --help?

**Comment by unxed** [comment]
> what abous busybox --help?

```
<scp:root@192.168.1.1>$ busybox --help
-help: applet not found
```

**Comment by unxed** [comment]
Может, галку в настройках протокола SCP сделать, что-нибудь вроде "embedded mode", при которой будет использоваться только простейший набор команд, гарантированно работающий везде?

**Comment by elfmz** [comment]
так имхо нет такого набора, гдето может быть unlink но может не быть rm гдето наоборот..

**Comment by unxed** [comment]
> так имхо нет такого набора, гдето может быть unlink но может не быть rm гдето наоборот..

Ну тогда это ещё одной проверкой поправить бы. Не хорошо если оно на современных *wrt прошивках не работает.

**Comment by unxed** [comment]
Для истории: допоправлено вот тут
https://github.com/elfmz/far2l/commit/5d7c6025158cfb0f6903a7f7c5b60b94df8e7f6e
