### ISSUE TITLE
multiarc custom.ini

### ISSUE THREAD

**Issue by Gravityzwell** [elfmz/far2l#144]
Can't figure out if multiarc custom.ini works, or where to put it. If not, is there any way to change the Format0 string of the existing archives?

**Comment by elfmz** [comment]
actually it never tested, if you have some working example config - I will be glad to check it:)

**Comment by Gravityzwell** [comment]
I've been using zpaq with Far for Windows:  https://github.com/zpaq/zpaq
or get if from ppa:
```
sudo sh -c 'echo "deb http://ppa.launchpad.net/abbat/zpaq-upstream/ubuntu/ xenial main" >> /etc/apt/sources.list'
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 315F92E2945B24D7
sudo apt-get update
sudo apt-get install zpaq-upstream
```
Here is a simple config. Adding is trickier, but possible. I'll figure out the syntax and post it if we get that far:
```
[zpaq]
TypeName=zpaq
ID=
IDPos=
IDOnly=0
Extension=zpaq
List=zpaq l %%AQS
Start="fragments,"
End=" files) shown"
Format0="- yyyy tt dd hh mm ss  zzzzzzzzzzz AAAAA nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn"
IgnoreString0="Zone.Identifier:$DATA"
Add=
AddRecurse=
Extract=zpaq x %%AQ "%%fS" -to "%%fSWA"
ExtractWithoutPath=zpaq x %%AQ "%%fS" -to "%%fSWA"
Test=
AllFilesMask="*"
```

**Comment by elfmz** [comment]
Was broken, now seems works.. at least for your case.
However ubuntu has some zpaq in the default repos.. but it doesn't work due to completely different output format not matching with you custom.ini

**Comment by Gravityzwell** [comment]
Great! Seems to work. I'll figure out the zpaq add and addrecurse syntax and post them in case anyone wants it. I have those working on Windows, but it's not the same.
