### ISSUE TITLE
Far's shell doesn't work in directories containing an apostrophe (')

### ISSUE THREAD

**Issue by alk0** [elfmz/far2l#1448]
First noticed on FAR2L, version 2.4.1-e9c8499f-beta Linux x86_64

Test case, from within far2l:
1. `mkdir a\'b` or `F7`, `a'b`
2. `cd a\'b` or `Enter` to enter the directory
3. `pwd` or _any shell command_ → no result whatsoever, the command just doesn't execute, silently

- To be more precise, it doesn't work if the path _contains_ an apostrophe (not necessarily the current directory itself).
- It also affects commands invoked via the user menu (F2) — they just do not execute.

**Comment by shmuz** [comment]
I fixed it on [my fork](https://github.com/shmuz/far2l/commit/6e1cb58eee29295615d3e413488ae5630ab2454a), hope that the fix was correct.

**Comment by elfmz** [comment]
@shmuz such fix will fix this but they it will reproduce with dir containing " character. Anyway thanks for spotting bug's root in code.

**Comment by shmuz** [comment]
Thanks for this info, (I thought that double quotes were illegal in file names).

**Comment by elfmz** [comment]
the only illegal character in names (on usual FS) in Linux is a '/'
