### ISSUE TITLE
Recent infopanel changes breaks OS X build

### ISSUE THREAD

**Issue by eliah** [elfmz/far2l#145]
After recent changes, starting from approximately fix #141 the code lost compatibility with OS X, and needs additional headers. Infopanel code is incompatible with the os x as well.

Quick and dirty solution attached.

[mac_os_x_headers_and_infopanel.diff.zip](https://github.com/elfmz/far2l/files/535578/mac_os_x_headers_and_infopanel.diff.zip)

**Comment by elfmz** [comment]
check if its ok now, there were minor conflicts..

**Comment by eliah** [comment]
Works like a charm now, thank you
