### ISSUE TITLE
Не работает сохранение размера экрана consolesize после закрытия окна на втором мониторе

### ISSUE THREAD

**Issue by sws33** [elfmz/far2l#1452]
Не работает сохранение размера экрана consolesize после закрытия окна на втором мониторе
Как проверить. На ноутбуке перейти на второй (внешний) монитор, поменять размер окна far2lin, сохранить настройки по shift-f9, выйти и снова запустить far2lin. Произойдёт сброс размера окна на размер по умолчанию. Но основном мониторе такой эффект не наблюдается.

**Comment by elfmz** [comment]
Closing as likely is fixed now, reopen if still reproducible. Also note that window size/state is not saved automatically but only when saving settings (pressing Shift+F9)
