### ISSUE TITLE
В последних сборках с launchpad что-то с отрисовкой

### ISSUE THREAD

**Issue by dimentiyinfo** [elfmz/far2l#1453]
Здравствуйте

В сборках с launchpad последних дней плохо работает отрисовка (в ряде случаев нужно подвигать окно, чтобы отрисовался новый экранный буфер)

Ubuntu 22.04, могу видео прислать если надо

**Comment by elfmz** [comment]
А какой была последняя версия в которой было норм? Там ничего в последнее время такого не менялось..
Убунта эта сконфигурена с xorg или wayland? (И нельзя ли попробовать другой вариант?)

**Comment by dimentiyinfo** [comment]
На основной рабочей станции / far2l 2.4.1-e9c8499-beta , всё нормально, обновления избегаю
На виртуалке far2l 2.4.1-0c3eaa7-beta, глюки

Ubuntu 22.04 xorg в обоих случаях, wayland включать не могу из-за проблем с ним

**Comment by elfmz** [comment]
Еще страннее так как действительно вроде в последние 2 недели ничего такого не менялось. А что именно и когда не отрисовывается?

**Comment by TrNullFree** [comment]
I had the same issue with the same version of Ubuntu.
In my case, this was fixed by updating the Nvidia drivers.

**Comment by dimentiyinfo** [comment]
У меня не nvidia и вообще виртуалка.
Но нельзя исключать, что проблема вызвана не обновлением far2l, а обновлением системы.

Видео:
https://disk.yandex.ru/i/FXUL6lo16kgU9Q

Характерно, что при запуске чего-либо в консоли (сборка и т.д.) ни разу проблем не наблюдалось, глюки в моём случае именно с отрисовкой собственно [частей] far2l.

**Comment by elfmz** [comment]
очень похоже на это - https://github.com/elfmz/far2l/issues/1303
нету ли тут какого нибудь ремоут доступа или все локально?

**Comment by dimentiyinfo** [comment]
Это локально запущенная kvm виртуалка, окно стандартного virtual machine manager-а. Т.е. сущносто просто "экран"

> #1303
"by directory change" -> вообще в разных случаях это происходит.
Может из диалога копирования отрисоваться только одно поле ввода, например...

**Comment by dimentiyinfo** [comment]
Почитал там камменты

> Если окно FAR чуть подвинуть, то всё сразу перерисуется.

Один в один проблема, да

**Comment by elfmz** [comment]
Ну там проблема была вызвана тем что если момент обновления содержимого окна и его заголовки совпадают во времени то возникает такой упс.. была сделана минимальная тестовая апликуха, но корневая причина так и не найдена, виноват толи xrdp, толи wxwidgets, толи иксы.. Был сделан простой воркэраунд в виде доп перерисовки через полсекунды после проблемного сценария _если_ работаем в удаленном десктопе. Удаленность определяется по наличию переменной окружения SSH_CONNECTION и если она равна не 127.0.0.* или localhost либо по наличию переменной окружения XRDP_SESSION. Если подскажете какими переменными можно продетектить ваш сценарий можно добавить и его. Хотя больше интересно что такого случилось что баг начал воспроизводится у вас. Там в тех дебрях вообще ничего не менялось со стороны far2l в этом промежутке версий..

**Comment by dimentiyinfo** [comment]
Провёл смертельный номер, обновил систему и far2l на хост машине - проблема не проявляется.
Т.е. можно предположить с некоторой вероятностью, что связь с "виртуальностью" экрана может иметь место

**Comment by elfmz** [comment]
можете привести результат printenv изнутри far2l где баг происходит? Все что считаете приватным - можете оттуда убрать, интересует нечто что укажет что это окно отображающее нечто из виртуалки. Может сами заметите чтото там..

**Comment by dimentiyinfo** [comment]
[printenv.txt](https://github.com/elfmz/far2l/files/10269347/printenv.txt)

**Comment by dimentiyinfo** [comment]
Это просто в консоли.
Или нужно прямо изнутри far2l? )

**Comment by elfmz** [comment]
Ну если эта просто консоль запущена так же внутри KVM и видна в виде окошка - то тоже норм. Но чета ничего особенного тут не видно:( Видимо таки надо копать дальше вглубь оригинального бага, может это какой то косяк в wx

**Comment by elfmz** [comment]
Вроде ща должно стать норм. Если можете - попробуйте собрать текущий мастер. А нет - то хотябы сообщите как оно будет после того как на launchpad появится нечто после последнего коммита..

**Comment by unxed** [comment]
Сборки для LTS-версий Ubuntu обновились в ppa до eb58f8a5, можно тестить. А для не-LTS там не обновляются регулярно в любом случае.

**Comment by dimentiyinfo** [comment]
Спасибо, работает

> костыль подравнял

Смотрится конечно необычно - отрисовка иногда "запаздывает" немного ;)
Но это всё уже детали.
