### ISSUE TITLE
[viewer] Weird (?) line wrapping

### ISSUE THREAD

**Issue by alk0** [elfmz/far2l#1454]
First noticed on 2.4.1-0c3eaa7c-beta

When viewing (F3) any file with wrapping (F2) enabled, lines are getting wrapped seemingly _by words_, but the beginning of the wrapped word is duplicated on the previous line. Both GUI and TTY modes are affected. Hard to explain, but easy to see when you try. Is it a bug or a feature? I would say… in practice it can easily become _very_ confusing :(

![image](https://user-images.githubusercontent.com/10332037/209225801-b553dbcd-7b56-412d-8e04-8a4adb101017.png)

**Comment by elfmz** [comment]
Word wrapping is toggled by ShiftF2, but its really buggy when enabled, thanks

**Comment by shmuz** [comment]
This problem doesn't show in far2.4-20220504-b9b6ab3f, so it must be introduced later.

**Comment by alk0** [comment]
Oh, I didn't know/totally forgot that I can just disable it for now. Thanks for reminding!
