### ISSUE TITLE
Location selector settings should allow to filter out (do not show) some user configurable mount points

### ISSUE THREAD

**Issue by alexandrustinov** [elfmz/far2l#1458]
Location selector (Alt+F1, Alt+F2) by default shows all the mounted drives, including snapd mounts, /boot, nfs pipes and so on non-user stuff.
For some configs the screen could be unusable (see my example below).

Kindly please allow to filter out some drives, simplistic regexp expression should be pretty enough for that, I think.

For an example, my Location selector looks next way at the moment:

    ~                                     /home/user
                                                /run
    /                                              /
                                                /tmp
                                               /home
                     /var/lib/snapd/snap/core18/2654
                     /var/lib/snapd/snap/core20/1738
                     /var/lib/snapd/snap/core18/2667
                      /var/lib/snapd/snap/core22/444
                          /var/lib/snapd/snap/bare/5
                      /var/lib/snapd/snap/core22/469
                      /var/lib/snapd/snap/core/14399
                     /var/lib/snapd/snap/freecad/245
                        /var/lib/snapd/snap/cups/872
             /var/lib/snapd/snap/gnome-3-28-1804/161
                        /var/lib/snapd/snap/cups/836
          /var/lib/snapd/snap/gtk-common-themes/1535
                  /var/lib/snapd/snap/inkscape/10512
    /var/lib/snapd/snap/kde…-5-91-qt-5-15-3-core20/1
                        /var/lib/snapd/snap/krita/77
    /var/lib/snapd/snap/kde…-5-96-qt-5-15-5-core20/7
                  /var/lib/snapd/snap/micropolis/153
     /var/lib/snapd/snap/microsoft-todo-unofficial/4
     /var/lib/snapd/snap/microsoft-todo-unofficial/6
              /var/lib/snapd/snap/onenote-desktop/17
                     /var/lib/snapd/snap/snapd/17883
                     /var/lib/snapd/snap/solitaire/5
                                               /boot
                             /var/lib/nfs/rpc_pipefs

**Comment by elfmz** [comment]
Just press F9 in that menu.

**Comment by alexandrustinov** [comment]
Ah yes, indeed. It is not available in release 2.4.1, but the option looks just perfect in master, thank you a lot. 

Kindly please consider to include ;/var/lib/* into the default exclusion list as well.

**Comment by alexandrustinov** [comment]
In addition to that - is it possible to align the numbers in columns by right side, like it was done in Far3? Just for perfection :)


    ╔════════ Change drive ═════════╗
    ║  C: fixed   │ 47.4 G │ 17.8 G ║
    ║  G: network │ 3.64 T │  183 G ║
    ╟─────────────┴────────┴────────╢
    ║  2  NetBox                    ║
    ║  3  network                   ║
    ║  0  Process list              ║
    ║  1  temporary                 ║
    ╚═══ Del Shift+Del F3 F4 F9 ════╝

**Comment by sxored** [comment]
> In addition to that - is it possible to align the numbers in columns by right side, like it was done in Far3? Just for perfection :)
> 
> ```
> ╔════════ Change drive ═════════╗
> ║  C: fixed   │ 47.4 G │ 17.8 G ║
> ║  G: network │ 3.64 T │  183 G ║
> ╟─────────────┴────────┴────────╢
> ║  2  NetBox                    ║
> ║  3  network                   ║
> ║  0  Process list              ║
> ║  1  temporary                 ║
> ╚═══ Del Shift+Del F3 F4 F9 ════╝
> ```

See here

https://github.com/elfmz/far2l/issues/1379#issuecomment-1369286923

and there

https://github.com/elfmz/far2l/issues/1478#issue-1526083424
