### ISSUE TITLE
OnInterract_ClipboardSetData does not null-terminate data before calling SetClipboardData

### ISSUE THREAD

**Issue by magiblot** [elfmz/far2l#1460]
Hi,

`SetClipboardData` receives a null-terminated string. However, `OnInterract_ClipboardSetData` does not call `SetClipboardData` with a null-terminated string; instead, it passes directly the data received from the `FARTTY_INTERRACT_CLIP_SETDATA` event, which if I understood correctly, does not have to be null-terminated. Therefore, garbage may be added at the end of the clipboard contents.

https://github.com/elfmz/far2l/blob/262a932fad09523f55a969ea48ec45ce00b7f269/far2l/src/vt/VTFar2lExtensios.cpp#L361-L381

Cheers.

**Comment by magiblot** [comment]
Mhm, Far2l does answer `FARTTY_INTERRACT_CLIP_GETDATA` requests with a null-terminated string, so I guess this is the expected behaviour. I think this should be explained in `FarTTY.h`, though.

Yet, the code I mentioned has a bug anyway because if the string provided by the client is not null-terminated then Far2l runs into undefined behaviour.

**Comment by elfmz** [comment]
Its not one-to-one works as Windows clipboard, and actuall allocation size being tracked and obtained by ClipboardSize. So if setter 'forgot' to set finalized NULL character then 'getter' can live with that if will take into account size reported by ClipboardSize, like here: https://github.com/elfmz/far2l/blob/master/far2l/src/clipboard.cpp#L245
However it makes sense to protect also those 'getters' who do not do such check by appending 4 more zero bytes (sizeof wchar_t) to data allocated with ClipboardAlloc
Force adding zeroes directly in OnInterract_ClipboardSetData is something that i like less as this will do kind of custom processing of data in a more-or-less generic logic and also if considering 'chained' multiple sessions that it will add many useless extra zeroes

**Comment by magiblot** [comment]
I mean, the problem that I had with this is that if the client does not provide a null-terminated string, then the X11 clipboard (which Far2l updates through the wxWidgets backend) is sometimes left with garbage at the end.

**Comment by magiblot** [comment]
Here it is. The result of `ClipboardSize` is not checked when setting the clipboard data through the xwWidgets API.

https://github.com/elfmz/far2l/blob/5ab97bbb16ba5b991e589bc1414f5cfd83c2d3a6/WinPort/src/Backend/WX/wxClipboardBackend.cpp#L181-L194

**Comment by elfmz** [comment]
Yes you're right, same issue may happen here.. I will do something with that

**Comment by elfmz** [comment]
Is it better now?

**Comment by unxed** [comment]
Also probably a typo in file name: it should be `VTFar2lExtensions.cpp`, not `VTFar2lExtensios.cpp`

**Comment by magiblot** [comment]
> Is it better now?

Yes, it now works out-of-the-box. Thank you very much!
