### ISSUE TITLE
FARTTY_INTERRACT_CLIP_GETDATA specification does not match actual behaviour

### ISSUE THREAD

**Issue by magiblot** [elfmz/far2l#1461]
According to [FarTTY.h](https://github.com/elfmz/far2l/blob/980fe693b66a8533ab47c12fbcf6641a2c71bd12/WinPort/FarTTY.h#L197-L206), the response to a `FARTTY_INTERRACT_CLIP_GETDATA` event is like this:

```
  int8_t (1 - success, 0 - failure, -1 - clipboard wasn't open)
  uint32_t (size of data)
  data of specified size
  uint64_t OPTIONAL (clipboard data ID, only if server reported FARTTY_FEATCLIP_DATA_ID)
```

However, as of current [master](980fe693b66a8533ab47c12fbcf6641a2c71bd12), when the request succeeds, the response sent back by Far2l is like this:

```
  uint32_t (size of data)
  data of specified size
  uint64_t (clipboard data ID)
```

That is, it does not have the success byte.
For example, in a situation where the clipboard contained the string `"VTFar2lExtensios.cpp"`, Far2l replied with `"\033_far2lm2rmDT0lsYxWVEZhcjJsRXh0ZW5zaW9zLmNwcAAVAAAAog==\a"` (the request ID was `0xA2`).

Is this an actual issue or did I understand the specification wrong?

**Comment by elfmz** [comment]
specification was written after implementation and in this case is wrong, should be:
```
  uint32_t (0 - on failure, -1 - clipboard wasn't open, other value - size of data - on success)
  data of specified size
  uint64_t OPTIONAL (clipboard data ID, only if server reported FARTTY_FEATCLIP_DATA_ID)

```
