### ISSUE TITLE
.m3u file support is broken

### ISSUE THREAD

**Issue by alexandrustinov** [elfmz/far2l#1462]
1) Far2L opens m3u as Archive by &lt;Enter&gt; or &lt;Ctrl&gt;+&lt;PgDn&gt; keystrokes, that's really cool feature.
But after editing (copy/delete/etc) of the .m3u file it becomes broken/damaged - the #EXTM3U format is being replaced by #mtree format. VLC (VideoLan player) is not able to play such  #mtree files at all.

Kindly please consider  saving the .m3u files according to the format: https://en.wikipedia.org/wiki/M3U

2) Also it would be great to disable opening .m3u file as Archive using &lt;Enter> keystroke by default.
Technically the .m3u is not Archive, it's just playlist and should be handled by Gnome shell like any other regular file with registered  extension.  
It's ok to override the handing using File-&gt;File associations, but it has some screen flickering effect: Far2L tries to show the result of command line execution. 
&lt;Shift&gt;+&lt;Enter&gt; also is an option, but it's a bit unusual when you are migrating from Far3/Windows

**Comment by alexandrustinov** [comment]
Update - it might be not Far2L issue, M3U file editing support could be side effect of libarchive or something else below.
Is it possible to disable handing of  the .M3U files by MultiArc plugin? As well as other such extensions?

**Comment by izzylaif** [comment]
> Update - it might be not Far2L issue, M3U file editing support could be side effect of libarchive or something else below. Is it possible to disable handing of the .M3U files by MultiArc plugin? As well as other such extensions?

да, задай добавь (insert) в Commands - File associations команду для этого расширения *.3u например xdg-open !.!

**Comment by alexandrustinov** [comment]
It works properly with libarchive.x86_64.3.5.3-4.el9 and far 2.6.0-2024-03-10-94a898de-beta, closing
