### ISSUE TITLE
Execute command line in separate terminal using by Shift+Enter

### ISSUE THREAD

**Issue by alexandrustinov** [elfmz/far2l#1463]
Far3/Windows initially had very nice feature - it allows to execute entered command line in separate terminal window (CMD.EXE) by Shift+Enter keystroke.
For an example - you can type `ping -t localhost`  then press Shift+Enter and the ping result will be shown in separate window.

Kindly please implement the same. The specific terminal execution command line itself should be configurable, as far as we are not tied to CMD.EXE only.

Though execution of either gnome-terminal or Xfce-terminal or xterm with respective predefined settings also might be wise, taking into account their availability and currently running system session (Gnome, KDE, XFce, etc).

**Comment by elfmz** [comment]
BTW `/bin/ping localhost` Shift+Enter runs xterm, simple ping not recognized, its true issue

**Comment by alexandrustinov** [comment]
confirmed, works fine now
