### ISSUE TITLE
far2l starts with enormous windows size and does not take into account ~/.config/far2l/consolesize  on HiDPI screens

### ISSUE THREAD

**Issue by alexandrustinov** [elfmz/far2l#1464]
1) Issue shows itself on HiDPI screens (4k), you can reproduce using  Desktop -> Display settings -> 200%
On startup far2l creates window with 480 columns and 90 rows (at least twice as desktop size), and it seems it does not take into account settings from ~/.config/far2l/consolesize. 
The issue might be related to last one: https://github.com/elfmz/far2l/issues/1457

2) With 100% scale another visible effect happens (Wayland session) - far2l starts with two black bands at right and bottom sides of the window (see attached screenshot), but after 1-2 seconds the entire layout auto resizes properly. 
It's not a big issue, just a bit annoying flickering effect, but I suppose it's related to ~/.config/far2l/consolesize settings.

![Screenshot from 2023-01-04 23-48-29](https://user-images.githubusercontent.com/6079363/210671681-7968a3cd-b6a5-4f13-be62-d32d152459d2.png)

3) Also it would be nice to save ~/.config/far2l/consolesize on Save Setup / Shift+F9 only. I can resize window of running application due various reasons, for large text or long file names, but such sporadic cases should not affect the default window size for new application instances. 
Otherwise I will have to resize the window size back manually on next application start, or encode shell script  in .desktop file which will return the consolesize file settings automatically, before application start, but all that is not not expected application behavior.

**Comment by elfmz** [comment]
i wasnt able to reproduce, but anyway plz check how it behaves now, as all code related to window state persistence had been just rewritten.

**Comment by elfmz** [comment]
Also note that consolesize is not any more. Now window size and pos and state saved into winstate at same place.

**Comment by alexandrustinov** [comment]
Still the same (I just updated from master), it takes near 1 sec on startup between "small" and normal layout, I even able to take screenshot during the delay

you can see the relayout transition on screenshot below:

![Screenshot from 2023-01-05 12-34-09](https://user-images.githubusercontent.com/6079363/210781727-d24bf4c3-4c8a-4521-8e7a-da34400c1c00.png)
 
![image](https://user-images.githubusercontent.com/6079363/210781906-12392804-0b31-4501-ac41-7291ba3e340b.png)

**Comment by alexandrustinov** [comment]
it seems that the "enormous size" issue is seems gone with new "winstate" settings.
but the "two black bands at right and bottom with visible flickering relayout on startup" - is still present.
issue shows itself in "initially maximized mode" and in "normal, nonmaximized" modes

see the transition below (next two images for "initially non-maximized" mode):

![Screenshot from 2023-01-05 12-41-18](https://user-images.githubusercontent.com/6079363/210782645-7ee32fba-89fa-4886-99b0-1a672803e2c6.png)

to 

![Screenshot from 2023-01-05 12-42-03](https://user-images.githubusercontent.com/6079363/210782708-b1bf0500-8c59-449f-8946-d0b64ae8863c.png)

**Comment by elfmz** [comment]
its half second but not one second... also check now - must be better but still not ideal

**Comment by alexandrustinov** [comment]
Just checked master - it's much, much better now. I'd say outstanding. Both HiDPI (200%) and normal  (100%) scale works just perfectly fine with Normal and Maximized startup.

Just one minor visible effect remains when we perform Save Settings (Shift+F9) in Maximized Mode (Alt+F9) in HiDPI, then change Desktop to Normal DPI and then trying to start Far2L once again (with saved HiDPI settings before) - then the re-layout effect on startup remains visible. It finally performs properly... and it can be easily fixed using Save Settings once again.

I'd leave that as is, case when user constantly changes DPI of main screen is very rare, excepting Laptop in 1080 mode and external screen in 4K, it is not big deal there: even for such cases user most of time runs in 4K mode and probably will never notice that effect.

**Comment by elfmz** [comment]
closing then..
