### ISSUE TITLE
Поломалось копирование через scp на сервер

### ISSUE THREAD

**Issue by sws33** [elfmz/far2l#1469]
В NetRocks поломалось копирование файлов через scp на сервер. Ошибка - 
scp push error - SCP: Warning: status code 1 received: scp 
Проблемный объект (имя файла на локальном комп.)

**Comment by elfmz** [comment]
Гм у меня все работает как и работало - с dropbear сервером так точно.
Что у вас за сервер? Можете посмотреть логи с его стороны что ему не нравится? Ну и банальности проверить - что не работает в том числе с чисто латинскими именами файлов, что места на диске хватает, что права есть и т.п...

**Comment by sws33** [comment]
> Что у вас за сервер? 
обычный выделенный сервер последний debian

**Comment by unxed** [comment]
> обычный выделенный сервер последний стабильный debian

рискну предположить, что имелось в виду, какая именно программа используется в качестве SSH сервера

**Comment by unxed** [comment]
К слову об SCP. Я всё удивлялся, а как это так mc умудряется работать с ЛЮБЫМ ssh сервером, на котором крутится неизвестно какой набор стандартных команд? Оказывается, вот как: существует стандартизированный протокол для такого, называется Files transferred over Shell protocol (FISH):

https://en.wikipedia.org/wiki/Files_transferred_over_shell_protocol

**Comment by unxed** [comment]
@sws33 а что команда `sshd -V` на сервере говорит?

**Comment by sws33** [comment]
> Гм у меня все работает как и работало - с dropbear сервером так точно. Что у вас за сервер? Можете посмотреть логи с его стороны что ему не нравится? Ну и банальности проверить - что не работает в том числе с чисто латинскими именами файлов, что места на диске хватает, что права есть и т.п...

Разобрался. Вспомнил, что перед этим полностью удалял samba с клиентского компьютера и, видимо, зацепил какой-то из этих пакетов, которые был в зависимости от lin2far:

libsmbclient libsmbclient-dev samba-libs

Проблема решилась, когда компилировал свежий релиз v2.5.0 BETA. Тогда подтянулись недостающие зависимости и сейчас копирование на сервер заработал, как обычно, т.е. на отлично. Спасибо за прогу -- она супер, после mc, как глоток свежего воздуха! :) 

Пользуясь случаем хочу спросить - на сколько безопасно сохранять пермонетно пароль для доступа по ssh (NetRocks)? Пароли хранятся в открытом доступе или, может, как-то, где-то шифруются?

**Comment by elfmz** [comment]
> на сколько безопасно сохранять пермонетно пароль для доступа по ssh (NetRocks)?
небезопасно, легкая обфускация там есть, но понимающие как она работает и имеющие полный доступ к ФС разобфуцируют

**Comment by sws33** [comment]
У меня опять перестал работать NetRocks. Поработал один день (один раз) и перестал. Не могу редактировать файл на сервере или скопировать файл на сервер. Та же ошибка - scp при попытке редактирования по F4:

Pull file error - ssh_scp_pull_request  called under invalid
Проблемый объект - файл на сервере
Проблемный сайт - мой сервер

Скриншот- https://imgur.com/a/PPQRTeB

Логи на сервер и клиенте чистые - ничего нет. Может я не туда смотрю? 
tail -20 /var/log/syslog

**Comment by sws33** [comment]
См. выше

**Comment by sws33** [comment]
Проблема решилась неожиданным образом. Что я тольк не делал, доустановливал пакеты, перекомпилировал lin2far - ничего не помогало. Потом просто создал новое соединение абсолютно с теми же параметрами и... заработало! :) Совет может кому-то пригодится на будущее... Почему так приозошло - я не знаю...
