### ISSUE TITLE
Замедленный старт far2l

### ISSUE THREAD

**Issue by ElderlyLinuxUser** [elfmz/far2l#1474]
В последних сборках far2l периодически наблюдается замедленный старт приложения (отрисовка окна с панелями )

 Kernel: 5.4.0-136-generic Desktop: MATE 1.26.0 
Linux Mint 20.3 Una base: Ubuntu 20.04 focal 

https://user-images.githubusercontent.com/96444123/211213401-e5496482-ca9a-405b-8b03-8b724e0fcbe9.mp4

https://user-images.githubusercontent.com/96444123/211213414-255db15d-c9c2-4055-8697-96b169f0de04.mp4

**Comment by elfmz** [comment]
Это под Wayland или XOrg? ( `echo $XDG_SESSION_TYPE` )

**Comment by ElderlyLinuxUser** [comment]
> 

x11

**Comment by elfmz** [comment]
можете проверить как оно после последнего коммита?

**Comment by ElderlyLinuxUser** [comment]
На сборке c26b914 изменений не увидел.
Проверял на том же ноуте. 
Эффект при старте полностью как на видео 2 возникает примерно в три-пять раз реже чем как на видео 1.

**Comment by unxed** [comment]
Сборка старая слишком, надо на 76219039243d5c367e7724323faa5d859dedc6c6 пробовать

**Comment by unxed** [comment]
>  Linux Mint 20.3 Una base: Ubuntu 20.04 focal

Хм, в Mint вэйленда по идее никакого не должно быть.

**Comment by elfmz** [comment]
Ну не знаю как насчет минта, но в 20й убунте Xwayland работает.
Впрочем то что виноват Xwayland - это тоже предположение. Баг может быть и в window manager'е или еще гдето. Я честно говоря не очень в курсе что и кем там отрисовывается..

**Comment by unxed** [comment]
Так в убунте по умолчанию gnome, у которого по умолчанию wayland, а в минте cinnamon или mate, где поддержку wayland ещё только пилят.

**Comment by unxed** [comment]
У меня mint с cinnamon, проблема не наблюдается.

**Comment by elfmz** [comment]
`ps aux |grep wayland` ниче не выдает?

**Comment by elfmz** [comment]
Проблема не то чтобы стабильно наблюдаема была. Во всяком случае та что в 22й убунте я воспроизвел - происходит в случае когда обработчик отрисовки работает примерно 10мсек времени. Поэтому то сразу на голом Х11 и GTK не воспроизводилось - на чистом Х11 рисовалка занимает 1 мсек.

**Comment by unxed** [comment]
> `ps aux |grep wayland` ниче не выдает?

только сам греп с параметром вэйленд. у меня cinnamon, но в mate (который у топикстартера) поддержка вэйланда не готова пока что тоже.

**Comment by elfmz** [comment]
Ну фиг его знает. Может не изза вэйланда а может етот баг - вообще чтото другое...
@ElderlyLinuxUser а что у вас говорит `ps aux |grep wayland` ?
И как насчет проверить сборку из более свежих исходников?

**Comment by ElderlyLinuxUser** [comment]
Говорит практически тоже самое, что и у unxed
![2023-01-11_21-47](https://user-images.githubusercontent.com/96444123/211892450-b21226eb-e199-4e3e-a877-28ecd35452d0.png)

Вечером обновилось сборка до FAR2L 2.4.1-9b5cf7a-beta GUI, эффект с задержкой также наблюдается.

ЗЫ. Обновляется из репозитория, если предполагалась проверка с самостоятельной компиляцией из исходников, то пока  провести такую проверку не могу.

**Comment by elfmz** [comment]
9b5cf7a это достаточно свежая версия..

**Comment by elfmz** [comment]
А ессли во время такой задержки ткнуть клавиши курсора вниз (если успеете) - будет видно ускорение перерисовки 
 выделения директории в списке относительно остальной части панелей?

**Comment by ElderlyLinuxUser** [comment]
> А ессли во время такой задержки ткнуть клавиши курсора вниз (если успеете) - будет видно ускорение перерисовки выделения директории в списке относительно остальной части панелей?

Попробовал. Я бы сказал, что изменений в скорости отрисовки не заметно

**Comment by elfmz** [comment]
А если запустить с 'чистыми' настройками, например так - `far2l -u test` ? (это будет запуск с отдельным профилем настроек с именем test)

**Comment by ElderlyLinuxUser** [comment]
> 



> А если запустить с 'чистыми' настройками, например так - `far2l -u test` ? (это будет запуск с отдельным профилем настроек с именем test)

Попробовал так тоже. К сожалению, я бы сказал что эффект остается (пробовал test, test1, test2). Неудобство в том, что запускается в мелком окне, и не так очевидно, как в более крупном. Нет ключа для задания сразу размера окна, в котором запускать ?

**Comment by elfmz** [comment]
а в целом при работе не наблюдается очевидных лагов прорисовки?

**Comment by ElderlyLinuxUser** [comment]
> а в целом при работе не наблюдается очевидных лагов прорисовки?

На такое пока не наткнулся. Если есть предложения как это проверить дополнительно, то могу попробовать.

**Comment by elfmz** [comment]
Подправил кое что, надеюсь угадал и если в этом было дело то должно стать получше. Проверьте как сможете после  99c19d2

**Comment by ElderlyLinuxUser** [comment]
> Подправил кое что, надеюсь угадал и если в этом было дело то должно стать получше. Проверьте как сможете после [99c19d2](https://github.com/elfmz/far2l/commit/99c19d265e8210f25eb7aee5b91648d4eb047e75)

На сборке FAR2L 2.4.1-99c19d2-beta GUI, к сожалению, эффект остается

**Comment by elfmz** [comment]
а можете сделать следующее?:
скачать приаттаченную к этому сообщению far2l_gui.so распаковав ее из архива
```
cd /usr/lib/far2l
mv far2l_gui.so far2l_gui.so.bak
cp ...путь_к_far2l_gui.so_из_сообщения ./
```
[far2l_gui.zip](https://github.com/elfmz/far2l/files/10410391/far2l_gui.zip)

**Comment by elfmz** [comment]
Поставил в виртуалку mint 20.3 проапдейтил так что его ядро стало таким же как у вас, даже панельку сделал сверху - однако существенных различий в скорости первоначальной прорисовки не вижу между текущей версией и версией из начала декабря. У вас помимо far2l точно ничего не менялось?
Но все же я кое что еще подоптимизировал, почти вслепую.. Проверьте плз билд >= 06aa0a69a2171d81ce297042d0bd016b4d738302

**Comment by elfmz** [comment]
Нашел тут еще одно подозрительное место. Но там изменения были в серене ноября. Когда у вас примерно появились тормоза?

**Comment by unxed** [comment]
> Поставил в виртуалку mint 20.3

Именно с MATE? Есть подозрение, что тут DE может влиять больше, чем дистрибутив как таковой, а Mint есть и с MATE, и с Cinnamon, и с Xfce.

**Comment by elfmz** [comment]
именно MATE, скачанная исошка зовется linuxmint-20.3-mate-64bit.iso

**Comment by elfmz** [comment]
Я тут обнаружил на одной з систем что целых полсекунды первой прорисовки тратится на подбор шрифта для рисования вот этой вот стрелочки  (которая символ комбобокса справа) в конце комстроки:
![image](https://user-images.githubusercontent.com/20957349/212399103-e290a830-1cb9-445d-b507-abb5adba063c.png)
и 12 ноября был код который сделал этот подбор еще медленнее (зато лучше размер подбираться стал).. Сейчас подумываю сделать кастомну отрисовку  этой стрелочки...

**Comment by ElderlyLinuxUser** [comment]
> Поставил в виртуалку mint 20.3 проапдейтил так что его ядро стало таким же как у вас, даже панельку сделал сверху - однако существенных различий в скорости первоначальной прорисовки не вижу между текущей версией и версией из начала декабря. У вас помимо far2l точно ничего не менялось?

На ноуте текущая версия mint 20.3 обновлялась с предыдущих версий ( кажется начиная с 19, но сейчас уже точно не вспомню  ), может быть залипла какая-нибудь версия используемых far2l библиотек ?

**Comment by ElderlyLinuxUser** [comment]
Завтра гляну на десктопе, там вроде переустанавливал систему сразу на mint 20.3, когда диск менял

**Comment by unxed** [comment]
> кастомну отрисовку

Звучит как красивое решение! Только, наверное, тогда надо все стрелочки во все стороны рисовать кастомно, чтобы консистентно смотрелись интерфейсы TUI приложений, работающих под far2l

**Comment by elfmz** [comment]
Еще есть вариант проще - поменять стрелочки на ▾ ▴ - они вроде не full-width считаются там где ↑ ↓ - fullwidth..

**Comment by elfmz** [comment]
![image](https://user-images.githubusercontent.com/20957349/212405567-42fc190e-e7fb-40be-a9fe-ab58248e938b.png)

**Comment by unxed** [comment]
> Еще есть вариант проще - поменять стрелочки на ▾ ▴ - они вроде не full-width считаются там где ↑ ↓ - fullwidth..

ага, можно и так! кстати, просьба. можно, пожалуйста, убирать эту стрелочку (и пробелы перед ней) при копировании экрана в буфер обмена по Ctrl+O -> F4? она не несёт никакого смысла, только пачкает вставку истории команд сюда на гитхаб, например

**Comment by elfmz** [comment]
628df09 


> можно и так! кстати, просьба. можно, пожалуйста, убирать эту стрелочку (и пробелы перед ней) при копировании экрана в буфер

Но ведь эта стрелочка - часть гуя (то есть туя), ее низзя так просто взять и убрать)...

**Comment by ElderlyLinuxUser** [comment]
> Завтра гляну на десктопе, там вроде переустанавливал систему сразу на mint 20.3, когда диск менял

Посмотрел на десктопе на сборке FAR2L 2.4.1-23c39d3-beta GUI задержек нет

**Comment by elfmz** [comment]
А на ноуте?

**Comment by ElderlyLinuxUser** [comment]
> А на ноуте?

О, на этой сборке на ноуте тоже стало нормально

**Comment by elfmz** [comment]
ну значит закрываю..
