### ISSUE TITLE
far2l window is de-maximized when running far2l --tty inside far2l wx

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1477]
1. remove winstate file
2. run far2l wx (will open maximized)
3. run far2l --tty inside
4. window will be de-maximized

Linux Mint 21 Vanessa, Cinnamon, x64

**Comment by elfmz** [comment]
not reproducible. Actually on step 2 far2l opened not maximized

**Comment by unxed** [comment]
oh, forgot about my Alt+F9 macro on startup:
```
[KeyMacros/Shell/CtrlR]
DisableOutput=0x1
NoSendKeysToPlugins=0x1
RunAfterFARStart=0x1
Sequence=AltF9
```

No when we have --maximize option can just use it instead

so not-a-but, closing
