### ISSUE TITLE
Счётчик процентов при удалении переваливает за 100%

### ISSUE THREAD

**Issue by xlo1911** [elfmz/far2l#1479]
![image](https://user-images.githubusercontent.com/48625494/211423617-c2f6b552-b302-43e6-b89a-10707d045d64.png)

Доходило до 113%, но заскринить не получилось.

Удалял каталоги с большим количеством файлов (rsync копия домашнего каталога).

FAR2L, version 2.4.1-d13619ce-beta Linux x86_64

![image](https://user-images.githubusercontent.com/48625494/211424389-c9e798b3-75d4-4739-a245-ee109caad8f4.png)

**Comment by elfmz** [comment]
А там не могли ли файлы создаваться в процессе удаления?

**Comment by exkrexpexfex** [comment]
Вероятно, удаляемый каталог содержал довольно много ссылок. Можно успеть увидеть проблему на вот таком тестовом каталоге
```
#!/bin/bash
for i in {1..10000} 
do 
mkdir -p ./test0/$i 
touch  ./test0/$i/$i
ln -s  ../$i ./test0/$i/sym
done
```
Поправил в PR
