### ISSUE TITLE
[FarColorer] keyboard shortcuts not work

### ISSUE THREAD

**Issue by akruphi** [elfmz/far2l#1480]
In Editor Plugin **FarColorer** Help (Editor->F11->FarColorer->F1) mentions about **keyboard shortcuts** `Alt-L`, `Alt-[`, `Alt-]` etc for quickly work with symbol pairs. But these keyboard shortcuts don't actually work.

**Comment by elfmz** [comment]
FAR3's colorer has no such shortcuts in help...

**Comment by ctapmex** [comment]
Alt-L, Alt-[, Alt-] - отсылка на макросы, которые шли в поставке farcolorer. В far2l этого нет. Можно удалить из help
