### ISSUE TITLE
intro text is cut on start

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1481]
1. run far2l wx maximized
2. press Ctrl+O
3. intro text (black letters on cyan background) will be cut at right:
![изображение](https://user-images.githubusercontent.com/1151423/212472331-f9d235a9-0648-42f2-af48-40b01f65d3c0.png)

Linux Mint, DE is Cinnamon

**Comment by elfmz** [comment]
No repro in ubuntu or mint mate.. Reproducible only if start nonmaximized (and rather small so text truncated 'naturally') and then maximize..

**Comment by unxed** [comment]
reproduces for me even with clean .config/far2l folder

https://user-images.githubusercontent.com/1151423/212474316-6fb838b3-8061-439d-9edb-f65001ec3caf.mp4

**Comment by unxed** [comment]
still reproduces

**Comment by unxed** [comment]
![Снимок экрана от 2023-01-14 15-17-43](https://user-images.githubusercontent.com/1151423/212476529-84eeb4be-b91f-4bf5-8dbf-f1ae3414d704.png)

**Comment by unxed** [comment]
not reproduced any more, closing
