### ISSUE TITLE
[Bug] Размер окна сбрасывается

### ISSUE THREAD

**Issue by FazziCLAY** [elfmz/far2l#1483]
# Баг
При запуске программы она открывается с минимальным размером окна, а не с предыдущим сохранённым, около 2 недель назад всё работало хорошо, после апдейта нет

![image](https://user-images.githubusercontent.com/68351787/213250172-f14905a6-e9da-4b5a-9351-ba168410eb60.png)
# Текущая версия
![image](https://user-images.githubusercontent.com/68351787/213250500-7d19fdce-3093-4f0b-a083-d42562348d88.png)

**Comment by elfmz** [comment]
1 размер окна нынче сохраняется при нажатии Shift+F9
2 если не помогает - расскажите больше о своей системе

**Comment by FazziCLAY** [comment]
не помогает
uname --all
`Linux fazzi-pc 5.15.0-58-generic #64~20.04.1-Ubuntu SMP Fri Jan 6 16:42:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

Linux lubuntu
```
LXQt Desktop Toolbox - Technical Info<p>
  LXQt About Version:     0.14.1
  LXQt Version:           0.14.1
  Qt:                     5.12.8
  Build type:             Release
  System Configuration:   /etc/xdg
  Share Directory:        /usr/share/lxqt
  Translations:           /usr/share/Lubuntu/lxqt/translations<br>
/usr/local/share/lxqt/translations<br>
/usr/share/lxqt/translations<br>
/var/lib/snapd/desktop/lxqt/translations


User Directories
  Xdg Data Home:          /home/fazzi/.local/share
  Xdg Config Home:        /home/fazzi/.config
  Xdg Data Dirs:          /usr/share/Lubuntu:/usr/local/share:/usr/share:/var/lib/snapd/desktop
  Xdg Cache Home:         /home/fazzi/.cache
  Xdg Runtime Home:       /run/user/1000
  Xdg Autostart Dirs:     /etc/xdg/xdg-Lubuntu/autostart<br>
/etc/xdg/autostart<br>
/etc/autostart<br>
/usr/share/autostart
  Xdg Autostart Home:     /home/fazzi/.config/autostart

```

**Comment by elfmz** [comment]
попробуйте теперь

**Comment by FazziCLAY** [comment]
Всё исправлено, спасибо
Удачи <3
