### ISSUE TITLE
kex error no match for method kex algos [ssh-rsa, ssh-dss]

### ISSUE THREAD

**Issue by pafnuteus** [elfmz/far2l#1484]
После апгрэйда до 2.5.0 при подключении в NetRocks к одному из хостов, который в предыдущей версии работал без проблем, стала возникать ошибка соединения.

<img width="1282" alt="Screenshot 2023-01-20 at 21 37 45" src="https://user-images.githubusercontent.com/13152284/213859979-9f2fbb0c-88ce-405c-bce0-e2300e02a116.png">

Откат до предыдущей версии устраняет проблему.

**Comment by elfmz** [comment]
попробуйте воркэраунд описанный тут: https://github.com/elfmz/far2l/discussions/1364#discussioncomment-4741879

**Comment by pafnuteus** [comment]
Спасибо, заработало! Можно, наверное, закрыть тикет?

**Comment by elfmz** [comment]
Не пусть  повисит пока. Надо наверное сделать человеческую настройку для этого, тогда и закрыть можно будет

**Comment by elfmz** [comment]
настройку сделал - 684f8c400c355f6e2c8afc85cd21ad553ceffd11
будет в след релизе, ну или руками собирайте мастер если что..

**Comment by pafnuteus** [comment]
Спасибо! поэтому я сразу не стал тикет открывать, спросил в телеге. Странно, что сразу не дали ссылку на воркэраунд.
