### ISSUE TITLE
Debian: migrate wxWidgets from 3.0 to 3.2

### ISSUE THREAD

**Issue by cycleg** [elfmz/far2l#1485]
В Debian Bookwork мигрировали с wxWidgets 3.0 на 3.2. Пакеты 3.0 уже вывели из репозитория. Надо мигрировать и far2l. Для этого достаточно обновить зависимости в deb-пакете.
Зависимость для сборки теперь пакет libwxgtk3.2-dev.

**Comment by elfmz** [comment]
#1486 вмержил - я так понимаю баг можно закрыть?

**Comment by cycleg** [comment]
Полагаю, да. Можно еще про зависимость для сборки куда-нибудь вписать.
