### ISSUE TITLE
AppImage

### ISSUE THREAD

**Issue by izzylaif** [elfmz/far2l#1488]
Уже поднималась тема лет 5 назад.
Как насчет выпускать на странице проекта официальные AppImage с фаром?
Если кто не знает, AppImage могут использовать как системные home/config папки, так и свои собственные в той же папке что и сам AppImage
В отличии от флатпаков-снапов и прочего, работают не в песочнице и не требуют закачки сотен метров непонятнего чего для своей работы.
Может быть кто-нибудь возьмется за это дело.

**Comment by izzylaif** [comment]
Вот тут человек пытается https://github.com/area-of-dev/Far2l.AppImage

**Comment by elfmz** [comment]
dup https://github.com/elfmz/far2l/issues/263
