### ISSUE TITLE
shorten "/home/USER/PATH" to "~/PATH" in command prompt

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1492]
...to save screen space for user typed commands. bash also does this.

**Comment by unxed** [comment]
Может, возможность задавать там имя пользователя и хоста добавить, чтоб совсем как в баше сделать можно было?
(хотя мне, в принципе, вполне ок и как сейчас :)

**Comment by elfmz** [comment]
так то там можно уже прямо сейчас написать все что угодно, в том числе хоть имя пользователя, хоть кличку собаки)

**Comment by unxed** [comment]
не, ну в смысле чтоб подставлялось то имя, под которым фар запущен
