### ISSUE TITLE
netrocks/sftp: not working via tmate

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1493]
https://tmate.io/

If compression is enabled, you see
![изображение](https://user-images.githubusercontent.com/1151423/215353545-74bc779e-db04-454f-8efd-a2ee81ce3ee4.png)

If it is disabled, you see
![изображение](https://user-images.githubusercontent.com/1151423/215353147-8e5a6f7a-28d4-4292-a823-00bab48ea18b.png)

**Comment by elfmz** [comment]
does it support this at all? does sftp command line works?

**Comment by unxed** [comment]
yes, in gnome terminal connection with `ssh` console tool work fine. also scp protocol in netrocks gives same errors and it does not require sftp server at all.

**Comment by elfmz** [comment]
But i mean sftp console tool, but not just ssh: https://linux.die.net/man/1/sftp

**Comment by unxed** [comment]
```
unxed@rcnb:~$ sftp T5CXLwBzZVGTUrLLEdZuKuBbE@lon1.tmate.io
Connection to lon1.tmate.io closed by remote host.
Connection closed
```

Okay, let's forget about SFTP. The same problem persists then I try to use SCP instead.

**Comment by elfmz** [comment]
Same question - what about scp command line tool? https://linux.die.net/man/1/scp

**Comment by unxed** [comment]
```

**Comment by unxed** [comment]
```
unxed@rcnb:~$ scp tSgRaxcYbTWqhUWxAEabgyK7X@lon1.tmate.io:/1.txt 2.txt
Invalid command
```

**Comment by elfmz** [comment]
So, its a tmate's limitation.. Potentially its possible to write some plain-shell commands implementation, that would transfer files using `cat` and other tricks (likely specific to particular shell) but it will not be sftp/scp anymore..

**Comment by unxed** [comment]
https://github.com/elfmz/far2l/issues/1819
