### ISSUE TITLE
[feature request] Хоткеи для управления окном

### ISSUE THREAD

**Issue by Alex895** [elfmz/far2l#1495]
Можно ли добавить в MacOS в окно far стандартные хоткеи, для управления окном ?
![Screenshot_2023-02-01 15 27 22_QMgvfw](https://user-images.githubusercontent.com/23402084/216050547-87d9017f-36a2-4acf-a70b-5a90df90a274.png)

**Comment by Vitalley** [comment]
Давно просил, но почему-то не хотят добавлять. Ещё просил верхнее меню продублировать, на Макбуках будет очень полезно, экран маленький и в Фаре не все помещаются.

**Comment by elfmz** [comment]
ну парочка добавлена - https://github.com/elfmz/far2l/discussions/1359
про Cmd+M никто не писал, вот его и нет..
