### ISSUE TITLE
MacOS + Samba: incorrect total and free space values

### ISSUE THREAD

**Issue by aburdukov** [elfmz/far2l#1496]
Far2L 2.5.0 beta, MacOS Ventura + connected Samba share.

What is shown in MacOS (these are correct values):
<img width="374" alt="image" src="https://user-images.githubusercontent.com/71703650/216854285-f7260f87-5217-4ecb-b4ee-ac03086a859e.png">
What is shown in Far2L:
<img width="591" alt="image" src="https://user-images.githubusercontent.com/71703650/216854347-fcb60024-6004-4d5d-b66a-a357e89ea620.png">

As you can see Far2L shows incorrect approx. 4Tb free space on Samba share instead of correct approx. 74.5Tb.
Total bytes are also incorrect (0.9Tb instead of 75Tb)

**Comment by elfmz** [comment]
Can you build from current master? There is high chance that is was just fixed, but i don't have such disk to check.

**Comment by aburdukov** [comment]
Confirmed. It is fixed in master:
<img width="835" alt="image" src="https://user-images.githubusercontent.com/71703650/233892131-842bed36-7e69-4327-90c1-caf077c00d11.png">
So, closing it.
