### ISSUE TITLE
Add Universal 2 binary to future releases

### ISSUE THREAD

**Issue by yurikoles** [elfmz/far2l#1499]
According to [CMake discussion](https://discourse.cmake.org/t/how-do-i-build-cmake-from-source-as-universal-arm64-and-x86-64-binary-on-mac/5862), the following option should do the trick: `-DCMAKE_OSX_ARCHITECTURES=x86_64;arm64`, maybe also `-DCMAKE_OSX_DEPLOYMENT_TARGET=11`, because Universal 2 Binary is available since Big Sur (11). 

I can't verify it myself due to #1498.

**Comment by elfmz** [comment]
It was merged and i was able to pack universal package:
[far2l-2.5.0-92cfd145-beta.z01.zip](https://github.com/elfmz/far2l/files/10950948/far2l-2.5.0-92cfd145-beta.z01.zip)
[far2l-2.5.0-92cfd145-beta.z02.zip](https://github.com/elfmz/far2l/files/10950951/far2l-2.5.0-92cfd145-beta.z02.zip)
[far2l-2.5.0-92cfd145-beta.zip](https://github.com/elfmz/far2l/files/10950952/far2l-2.5.0-92cfd145-beta.zip)

**Comment by horieva** [comment]
I can check, but I can't open that archives. :(

<img width="315" alt="CleanShot 2023-03-12 at 16 54 51@2x" src="https://user-images.githubusercontent.com/90963491/224552687-905edf8a-5628-4947-8f16-a8ea9d9264ed.png">

<img width="505" alt="CleanShot 2023-03-12 at 16 55 10@2x" src="https://user-images.githubusercontent.com/90963491/224552703-f1709273-cee4-4f85-81a3-d0fe23b3f59a.png">

**Comment by elfmz** [comment]
Lets try another way, here re files, download them and concatenate using cat command in terminal: `cat ./far2l-2.5.0-92cfd145-beta.1.zip ./far2l-2.5.0-92cfd145-beta.2.zip ./far2l-2.5.0-92cfd145-beta.3.zip > ./far2l-2.5.0-92cfd145-beta.dmg`
that will produce .dmg file with sha256sum d58d25449db7900e62a2c6421a317d7cfc2078a57dae2ed9135fc11e0bad4ffb 

[far2l-2.5.0-92cfd145-beta.1.zip](https://github.com/elfmz/far2l/files/10951237/far2l-2.5.0-92cfd145-beta.1.zip)
[far2l-2.5.0-92cfd145-beta.2.zip](https://github.com/elfmz/far2l/files/10951238/far2l-2.5.0-92cfd145-beta.2.zip)
[far2l-2.5.0-92cfd145-beta.3.zip](https://github.com/elfmz/far2l/files/10951239/far2l-2.5.0-92cfd145-beta.3.zip)

PS All this husstle cuz github doesnt allow >25megs attachements

**Comment by horieva** [comment]
At first look it all works great. I can't do screenshot of the FAR window because when I press Shift + Option + Cmd or Shift + Ctrl + Cmd FAR hides blue panels, lol. :)

<img width="1083" alt="CleanShot 2023-03-12 at 17 32 01@2x" src="https://user-images.githubusercontent.com/90963491/224555091-54909ff5-b294-4135-8a51-7a2e984e049a.png">

**Comment by elfmz** [comment]
ok, cool that it works, next release will include 'official' version built in such way

**Comment by progreccor** [comment]
I have tested this release
Looks like it works fine
<img width="1651" alt="Снимок экрана 2023-03-14 в 10 07 45" src="https://user-images.githubusercontent.com/3103677/224922747-8273e641-1201-4b78-a66c-3f20276948d5.png">

**Comment by elfmz** [comment]
Its a feature - under Windows FAR Ctrl+Alt+Shift also hides temporarily panels.

**Comment by progreccor** [comment]
> @progreccor do you have some thing like me? I mean hide two panels when I press opt(ctrl)+cmd+shift?

Yes, it's very handy

**Comment by yurikoles** [comment]
It seems that Universal 2 binary is being shipped starting from release [2.5.1](https://github.com/elfmz/far2l/releases/tag/v_2.5.1).
