### ISSUE TITLE
Refactoring: remove unnecessary libraries from plugins

### ISSUE THREAD

**Issue by invy** [elfmz/far2l#15]
Cleanup plugins by removing unnecessary libraries, which could (and should) be managed by system package manager:
1.  multiarc: libpcre (use c++ regex)
2. colorer: zlib
3.  netbox: putty (replace with openssh, because it would be great if far could pickup ssh keys from ~/.ssh)

Have I missed anything?

**Comment by unxed** [comment]
All those now use system libraries. Do we still need to keep this issue open?
