### ISSUE TITLE
far console scrolling

### ISSUE THREAD

**Issue by invy** [elfmz/far2l#150]
it should be possible to scroll console in ctrl+o mode.

**Comment by eliah** [comment]
A nice lifehack is available there — press `F4` when in `ctrl+o` mode to scroll the console buffer in the edit mode. At least, it works this way under OS X

**Comment by unxed** [comment]
system clock is appended to console output using this workaround. guess it should not.

drwxr-xr-x  2 unxed unxed   4096 окт 12 18:20 s2                                       20:29
drwxr-xr-x  5 unxed unxed   4096 окт 14 11:17 s3fav
drwxr-xr-x  9 unxed unxed   4096 окт 14 11:15 s4
drwxr-xr-x  4 unxed unxed   4096 окт 14 12:00 s5
drwxr-xr-x  2 unxed unxed   4096 окт 14 15:16 s7

**Comment by invy** [comment]
I'd prefer scrolling anyway.

**Comment by lingvoboard** [comment]
Возможности проскроллировать очень не хватает.
Например без неё сложно пользоваться пакетным менеджером yaourt на Arch Linux (если выводится длинный список)

![](https://s27.postimg.org/6w8o7fv6b/far.png)

На этом скриншоте виден только конец списка.
Нужно ввести номер опции для продолжения. 
В этой ситуации F4 не работает.

**Comment by elfmz** [comment]
на всякий случай прокомментирую голосом: теперь, если нажать Ctrl+Shift+F4 _во_время_ исполнения чего либо в консоли - то эдитор откроется историей. Ctrl+Shift+F3 откроет, соответственно, viewer.
ЗЫ Вот бы еще этот viewer научить отображать в цвете ANSI графику, тогда история будет вполне полноценной. Сейчас, аттрибуты цвета, понятное дело, опускаются..

**Comment by unxed** [comment]
А контент обновляется по мере получения нового вывода от исполняющегося процесса?
Или мне стоит воспользоваться приборчиком для закатывания губ?

**Comment by unxed** [comment]
Проверил. Не обновляется. Более того, процесс фризится на время работы вьюера. Мне не показалось, так и должно быть?

**Comment by elfmz** [comment]
Контент не обновляется, процесс не фризится, по кр мере насколько там хватает буфера псевдотерминала.
Честно говоря меня всегда бесило что в стандартных терминалах контент убегает, когда я его внимательно разглядываю. Так что такое разделение режимом работы/просмотра истории имеет еще и немножечко личные корни:). Хотя главное конечно - что так было проще всего в имплементации.

**Comment by unxed** [comment]
> Честно говоря меня всегда бесило что в стандартных терминалах контент убегает, когда я его внимательно разглядываю.

Да, есть такое. Но

> насколько там хватает буфера псевдотерминала

а что потом? ;-)

**Comment by elfmz** [comment]
зафризиться.. наверное)

**Comment by unxed** [comment]
А сколько там буфер? Это настраивается?

**Comment by elfmz** [comment]
хз, сходу найти не удалось, но можно предположить что такой же как дефолтовый буфер у пайпов, а он у них 64кб.

**Comment by elfmz** [comment]
вот, сделал чтоб по мышескроллу активировался вьювер.
Основная комбинация - Ctrl+Shift+ScrollUp - она работает везде, даже из панелей (вначале хотел убрать но потом показалось что полезно ведь).
А во время работы в консоли чего нить можно и просто скроллить.

**Comment by elfmz** [comment]
ну, раз скорллинг есть, то можно закрывать...

**Comment by evil-shrike** [comment]
Hi, currently nothing can be scrolled, Ctrl+Shift+ScrollUp does nothing.
How to see the console history in ctrl-O mode?

**Comment by elfmz** [comment]
Just checked specially - still all works for me. In ctrl+O, if nothing is executed you can use:
F4
Ctrl+Shift+F4
F3
Ctrl+Shift+F3
Ctrl+Shift+ScrollUp
If some command being executed then only Ctrl+Shift+ combinations are working for F-keys.  But working. All that opens editor or viewer that subsequently allows scrolling by their usual ways.

**Comment by evil-shrike** [comment]
Combinations with F4/F3 work well, thanks!
Only Ctrl+Shift+ScrollUp isn't working for me

**Comment by bbest1** [comment]
In my case F3/F4 does not worked. Only worked :
**editor:<"some command"**
