### ISSUE TITLE
clear command line when deleting command from history with shift+del

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1504]
Sometimes I need to remove some command from history. So I start typing it, when selecting it from suggestions list and pressing Shift+Del. The problem is that deleted command still stay in command line, so if I accidentally press Enter after deletion, it is executed one more time and appears in history again. So can we clear command line after deleting command from history?

**Comment by elfmz** [comment]
Changing command line to selected item looks more logical (and simplier to implement), so is it ok now?

**Comment by unxed** [comment]
Much better now, thanks!
