### ISSUE TITLE
portable version

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1505]
I'm developing a [fully-portable far2l version](https://github.com/unxed/far2l-deb/tree/master/portable), able to run at as old systems as Debian 7 (already working!).

To achieve this, I bundle all required dependent .so in special folder together with loader (ld-linux-x86-64.so.2) compatible with libc used. After it I am patching all executables to modify rpath and interpreter path correspondingly.

The problem is, while rpath (path to libraries) can be relative, interpreter path can not. You can't tell the kernel to search for loader in folder relative to the path the program is running from. It always searches relative to the current folder.

So if I set loader to something like "./lib/ld-linux-x86-64.so.2", everything work perfectly if you start far2l from it's own folder.

The problem comes when user is trying to use sudo or multiarc so far2l has to call itself. As user may be in random folder at that time, kernel starts searching for the loader from user's current folder, not from far2l's folder, and can not find it.

So, can I please ask to make far2l change current folder to the folder of far2l's executable before making sudo app or multiarc calls? Also all parameters to those calls using relative paths should use absolute paths instead.

**Comment by unxed** [comment]
For sudo solution looks like this:
```
diff --git a/WinPort/src/sudo/sudo_client.cpp b/WinPort/src/sudo/sudo_client.cpp
--- a/WinPort/src/sudo/sudo_client.cpp
+++ b/WinPort/src/sudo/sudo_client.cpp
@@ -151,6 +151,7 @@ namespace Sudo
 				perror("chdir");
 			//if process doesn't have terminal then sudo caches password per parent pid
 			//so don't use intermediate shell for running it!
+			chdir(getenv("FARHOME"));
 			r = execlp("sudo", "-n", "-A", "-k", g_sudo_app.c_str(), ipc.c_str(), NULL);
 //			r = execlp(g_sudo_app.c_str(), g_sudo_app.c_str(), ipc.c_str(), NULL);
 			perror("execl");

```

**Comment by elfmz** [comment]
Isn't $ORIGIN is what you need?
https://docs.oracle.com/cd/E19957-01/806-0641/appendixc-16/index.html

**Comment by unxed** [comment]
You can only use $ORIGIN rpath only. You can't use $ORIGIN in interpreter path, as Linux Kernel does not understand it.

**Comment by elfmz** [comment]
Check if its ok now

**Comment by unxed** [comment]
Both sudo and multiarc now working like a charm, thanks!

**Comment by unxed** [comment]
There is also another very strange bug that only appears in portable environment. On Ubuntu 18.04, the NetRocks FTP client does not connect by hostname (gives "PipeIPCRecver read(0)" error), but connects by IP. In the same time, NetRocks SFTP client connects by hostname normally. On other tested distros (Debian 7, CentOS 6, Ubuntu 16.04, Mint 21) bug does not reproduce. Do you have any ideas what could be wrong?

**Comment by elfmz** [comment]
а если включить логи `export FAR2L_STD=-` ? может чтото интересное напечатается? типа что либа какаято не нашлась изза чего процесс брокера упал (PipeIPCRecver намекает на это)

**Comment by unxed** [comment]
> а если включить логи export FAR2L_STD=- ? может чтото интересное напечатается? типа что либа какаято не нашлась изза чего процесс брокера упал (PipeIPCRecver намекает на это)

Разобрался, спасибо! Правда, я так дебажил не NetRocks FTP, а FarFTP, который вообще вылетал в portable (предположил, что генезис ошибки общий). Выяснилось вот что.

libc при определении хоста по имени смотрит в файл /etc/nsswitch.conf, а он на разных системах разный. На системе, где собиралась portable (ubuntu 16.04) он выглядит так:
```
...
hosts:          files dns
...
```
А на 18.04, где FTP не работает — так:
```
...
hosts:          files mdns4_minimal [NOTFOUND=return] dns
...
```
В итоге libc при попытке разрешения имени хоста пытается динамически загрузить `libnss_mdns.so.2`, которой в 16.04 нет вообще, ну и предсказуемо падает на этом.
Добавил в сборочный скрипт `apt install libnss-mdns` — падать перестало.

**Comment by unxed** [comment]
Still problem with sudo then trying to add some file to archive in root folder.
1. Create empty file in / using editor (it will prompt for password, that works ok).
2. Try to add this file to .tar.gz using multiarc
![изображение](https://user-images.githubusercontent.com/1151423/219902401-d0e20a2c-037c-4fb2-956d-0c1fdd4b5d3d.png)
The file /tmp/selfgz632028/far2l_askpass exists and links to far2l binary:
```
/$ ls -la /tmp/selfgz632028/far2l_askpass
lrwxrwxrwx 1 unxed unxed 5 фев 18 16:10 /tmp/selfgz632028/far2l_askpass -> far2l
```
So "no such file" refers to loader, not binary itself. We probably need to cd to far2l's dir not only for sudoapp, but for askpass also.

**Comment by elfmz** [comment]
askpass is started by sudo, and sudo sets its directory to /usr/bin so its out of far2l's control.
However you may replace far2l_askpass symlink with a shell script that will cd to far2l's dir and then do `exec -a far2l_askpass ./far2l $*`

**Comment by unxed** [comment]
`sudo` have `-D` switch to change the working directory before running command, maybe to use it is better approach?

**Comment by unxed** [comment]
Working. Thanks!
