### ISSUE TITLE
Автодополнение в консоли ведет себя по разному в GUI и в терминале

### ISSUE THREAD

**Issue by dvlom99** [elfmz/far2l#1506]
Far2l по разному ведет себя в версии GUI-версии и в терминальной при попытке набрать в консоли, команду "cat /proc/mdstat" с использованием автодополнения по клавише \<Tab\>: 
$cat /pr\<Tab\>md\<Tab\>
GUI-версия отрабатывает штатно, терминальная версия после нажатия второго \<Tab\> в консоль ничего по \<Tab\> не выводит.

Версия: version 2.5.0-87d0139-beta Linux x86_64
OS: Linux Mint, Cinnamon, 21.1

**Comment by elfmz** [comment]
Похоже что дело не в том терминальная версия или гуевая, а в последовательности нажатия включая всякие не буквенные кнопки. Вобщем вкомитил предположительный фикс, проверьте как сможете текущий мастер.

**Comment by dvlom99** [comment]
Да, похоже. Сегодня и GUI-версия (старая) с автодополнением по второму \<Tab\> не сработала ни разу.

В версии https://github.com/elfmz/far2l/commit/b8bd6a3ac70da97bf30f622136532b633550165a автодополнение заработало. Спасибо.
