### ISSUE TITLE
Нет множественно отмены переноса/копирования

### ISSUE THREAD

**Issue by Vitalley** [elfmz/far2l#1508]
При копировании/переносе файлов и защищенном от записи носителе нужно отменять по каждому одному файлу.
<img width="1082" alt="Снимок экрана 2023-02-19 в 11 43 31" src="https://user-images.githubusercontent.com/29605653/220459579-2e07a66a-0da8-4e2d-9bdb-7fbc03f4d4cd.png">

**Comment by elfmz** [comment]
Но ведь если тут нажать отмена - то появляется второй диалог в котором повторное нажатие отмены таки отменяет операцию для всех файлов:
![Screenshot_20230225_232103](https://user-images.githubusercontent.com/20957349/221377964-136f7d10-46da-44f0-8325-510bcaac1aec.png)
