### ISSUE TITLE
when macro call don't work DisableOutput=0x1 ? 

### ISSUE THREAD

**Issue by Zeroes1** [elfmz/far2l#1510]
Far2l v2.5

проблема через SSH и напрямую в консоли сервера Ubuntu 20+

есть макрос
[KeyMacros/Shell/Alt0]
DisableOutput=0x1
Sequence=F9 Enter Up Enter / c d Space t m p Enter

после его выполнения
если нажать CtrlO (скрыть панели) 
под панелями работающего FAR2L видим визуальную прорисовку панелей предыдущего состояния FAR2L?

т.е. судя по всему несмотря на заданный параметр DisableOutput=0x1 FAR2L не скрывает прорисовку панелей в каких - то 
случаях? [предполагаю кусок при выполнении c d Space t m p Enter]

воспроизведение проблемы 100%

см. скриншот, на нём я частично поднял панели по CtrlUp после выполнения макроса
![sshot-2](https://user-images.githubusercontent.com/11919060/220591871-af193ef0-fac8-4067-ab61-c77beda0f7c8.png)

**Comment by elfmz** [comment]
Actually it works, if change it to DisableOutput=0x0 then there is no panels left.
DisableOutput=0x1 (its by default BTW) prevents painting that is required to restore terminal screen

**Comment by Zeroes1** [comment]
Да, спасибо это помогает. я просто думал что логика такая же как в FAR1-2-3 Win.
