### ISSUE TITLE
when try F3 on some pic - get some troubles [SSH only]

### ISSUE THREAD

**Issue by Zeroes1** [elfmz/far2l#1513]
Far2l 2.4 и 2.5

работает по SSH с kubuntu 22.10
через putty4far2l или Bitvise SSH
последние версии

на некоторых png файлах если жмём F3 в панели
происходит открытие файла во вювере с активацией поиска и глюком - нельзя этот диалог закрыть

я так понял это что то связано с фичей просмотр картинок по SSH? 

100% воспроизведение

пример файла на котором 100% проблема: mm_flash_01.png
![mm_flash_01](https://user-images.githubusercontent.com/11919060/221451709-73751e46-e9b1-4da0-912d-a172ec69db83.png)

**Comment by Zeroes1** [comment]
![sshot-8](https://user-images.githubusercontent.com/11919060/221451868-80f891ea-9996-42a5-be77-be2585f96984.png)
вот такой диалог появляется сразу и нельзя его закрыть по ESC или нажатию мышкой на отмену

**Comment by Zeroes1** [comment]
пример проблемного GiF
тут появляется автоматически поиск но хоть выйти получается
![005](https://user-images.githubusercontent.com/11919060/221453641-e2f5a816-14ba-425f-9aa7-ecaf7ffdebca.gif)

**Comment by Zeroes1** [comment]
ессно когда делаем просмотр не по SSH проблемы - нет

**Comment by unxed** [comment]
@elfmz можете, пожалуйста, глянуть, не ломается ли в фаре попытка распарсить некорректный UTF-8 на последовательности 05 DB 81 ?

**Comment by unxed** [comment]
Hm, `echo -n -e '\x05\xdb\x81'` reproduces bug even in plain bash in vanilla putty, without far2l. "PuTTY" line also being pasted.
So probably upstream bug? Not sure.

**Comment by elfmz** [comment]
regardless of if its putty issue or not - raw 05 character should not be written to output, i have a suspection about this, will check (and fix if confirm) later

**Comment by unxed** [comment]
Minor problem while viewing whose files remains: `»` scrolling char is shown where it should not be while scrolling is disabled.

![изображение](https://user-images.githubusercontent.com/1151423/221719161-d065b8cc-cf94-45e1-bf3a-6d0ddd3acc89.png)
