### ISSUE TITLE
MacOS does not recognize keys on the numeric keypad on full external keyboard

### ISSUE THREAD

**Issue by mortihead** [elfmz/far2l#1514]
MacOS Ventura 13.2.1
Far2l 2.5.0-be7a3156
Подключена полноразмерная клавиатура
far2l не понимает включен numlock или выключен 
- всегда считает что на numpad’e - home, end и стрелки.
При запуске в терминале —tty - все нормально, цифры печатаются при включенном нумлоке и стрелки при выключенном.
----
Full size keyboard connected
Far2l not understand whether numlock is on or off
- always considers that on numpad'e - home, end and arrows.
When you run in the terminal -tty - everything is fine, the numbers are printed when the numlock is on and arrows when it is off.

**Comment by singalen** [comment]
Last time I checked, MacOS didn't support NumLock at all. How does it work in other editors?
