### ISSUE TITLE
trouble set hotkey for menu F11

### ISSUE THREAD

**Issue by Zeroes1** [elfmz/far2l#1516]
FAR2L, version 2.5.0-c08ff72-beta Linux x86_64
воспроизводимость 100%

для пунктов меню по F11

-Advanced compare
+Calculator
-Case conversion
+NetRocks
+Temporary Panel

там где позиция -
если назначить хоткей он не будет виден по факту и не будет срабатывать (но он назначен - виден при повторном 
назначении)

если будет задан хоткей хоть на одном из пунктов где + то будет видны хоткеи ВСЕ в меню!

на русском тоже самое:
если заданы хоткеи только для
преобразование регистра
расширенное сравнение

они будут не видны и не будут срабатывать.

**Comment by elfmz** [comment]
хм похоже не дофиксил, теперь иногда работает иногда нет..
