### ISSUE TITLE
Preserve file permissions while copying

### ISSUE THREAD

**Issue by sorcodiv** [elfmz/far2l#1518]
Существует ли возможность сохранения прав доступа к файлам при копировании?

Ситуация: копирую файл в корень web-сервера.
Права исходного файла:
-rw-r--r-- 1 root root 1259 Sep  3  2020 README
Права на файл после копирования в far:
-rw------- 1 root root 1259 Sep  3  2020 README
Изменение опций копирования на результат не влияет:
[x] Copy files access mode
[x] Copy extended attributes

При этом если копировать в mc с опцией [x] Preserve attributes, то права выставляются как требуется:
-rw-r--r-- 1 root root 1259 Sep  3  2020 README

Версии ПО:
linux debian 11.6 x86_64 cli, putty4far2l 0.76 (build on 2023-01-06)
far version 2.5.0-c08ff72 (build on 2023-02-19)

**Comment by elfmz** [comment]
что выдает команда umask на системе?

**Comment by sorcodiv** [comment]
0022

**Comment by elfmz** [comment]
ну в целом понятно, что это изза нее.. хотя разница между терминалом и фар2л непонятна, но в принципе непринципиальна, если думать о том как это пофиксить..

**Comment by sorcodiv** [comment]
Похоже проблема в использовании [portable-сборки](https://github.com/unxed/far2l-deb/tree/master/portable). Если распаковать portable, то поведение становится ожидаемым - права выставляются корректно. Т.е. проблема скорее всего в упаковщике [makeself](https://github.com/megastep/makeself).
Спасибо!

**Comment by sorcodiv** [comment]
да, в первой же строке создаваемого makeself скрипта указано:
ORIG_UMASK=`umask`
if test "n" = n; then
    umask 077
fi

**Comment by elfmz** [comment]
но тем не менее наверное я это пофиксил (в текущем мастере)
