### ISSUE TITLE
Garbled russian characters in the help

### ISSUE THREAD

**Issue by eliah** [elfmz/far2l#152]
Same issue as #146, but this time it's about help files

![garbled_chars_in_ru_help](https://cloud.githubusercontent.com/assets/2249849/19511453/f6506ca2-95ef-11e6-92f0-5ecd12a67178.png)

**Comment by elfmz** [comment]
fixed by https://github.com/elfmz/far2l/commit/8786b22de826c59ff10499949dd3cb19facf94da
