### ISSUE TITLE
add alternative clipboard access methods in non-x11 environments

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1520]
...if far2l extensions are not available.

**WSL**:
```
    cat | /mnt/c/Windows/System32/clip.exe
    /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe Get-Clipboard | sed 's/\r//'
```
Probably calling just by names should be enough:
```
    cat | clip
    powershell Get-Clipboard | sed 's/\r//'
```

**Cygwin**:
```
    cat > /dev/clipboard
    cat /dev/clipboard
```

**MacOS**:
```
    cat | pbcopy
    pbpaste
```

**Wayland**:
```
    cat | wl-copy
    wl-paste

```

Sources:
https://gist.github.com/RichardBronosky/56d8f614fab2bacdd8b048fb58d0c0c7#file-cb
https://stackoverflow.com/a/60849508/1020550

**Comment by unxed** [comment]
Сюда же: можно сделать опцию в настройках «use custom copy/paste command line tools», чтобы можно было вручную прописать те инстурменты, что есть и работают на твоей системе, если штатный доступ к буферу обмена почему-то не работает. Решило бы проблемы типа #1350 хотя бы временно.

**Comment by spvkgn** [comment]
Еще такое есть https://github.com/Slackadays/Clipboard

**Comment by unxed** [comment]
CScript-based solution for WSL (better when PowerShell):

https://github.com/magiblot/tvision/commit/518821829f1b1fc4dfe148b37e740a266c15d177

**Comment by unxed** [comment]
После https://github.com/elfmz/far2l/issues/1658#issuecomment-1546638648 можно закрывать.
