### ISSUE TITLE
Unsuccessful removing of files for Mac OS

### ISSUE THREAD

**Issue by Sanchoyzer** [elfmz/far2l#1521]
Hey. I've been using Far2l for several years and want to report one annoying bug. The "remove" action (F8) has no effect.

Test environments:
1. Mac OS 11.5, Far2l 2.3 alpha
2. Mac OS 13.2, Far2l 2.5 beta

Reproducing:
1. Select a file
2. Click F8
3. Select "move" in the "remove" dialog 
<img width="699" alt="pic" src="https://user-images.githubusercontent.com/412738/222766753-504d1e34-8e77-4a05-9a57-87652a9b6527.png">

4. ...
5. The dialog is closed, but the file still exists. This file will be removed successfully if I execute in cmd "rm" command

I want to send some logs for finding the bug, but I need to figure out where to find them.

**Comment by elfmz** [comment]
its because you have enabled delete to recycle bin and it not (yet) implemented well for macos..

**Comment by elfmz** [comment]
if you can build from sources (current master) - then please check if its fixed for you (delete to recycle bin) otherwise you may turn off F9/Options/System/Delete to recycle bin for now..

**Comment by Sanchoyzer** [comment]
I tried, and it seems that it's ok for a file, but it failed with a folder:

<img width="863" alt="pic2" src="https://user-images.githubusercontent.com/412738/222842437-63a31217-5692-427f-bc8b-ea7de0165440.png">

"No recycle bin" works fine

**Comment by elfmz** [comment]
try current sources, on my test macos it now also works for directories too..

**Comment by Sanchoyzer** [comment]
Fantastic, it works! Thanks a lot; it was my pain
