### ISSUE TITLE
Wanna press Ctrl+~ to get home

### ISSUE THREAD

**Issue by czaerlag** [elfmz/far2l#1538]
Would be very nice to have a hotkey to quickly change the current directory to the current user's home.
I guess it should be Ctrl+~, similar to Ctrl+\ that takes me to the file system root.
Looks like a trifle, but I dream of it every day! )

**Comment by shmuz** [comment]
Use Folder shortcuts (accessible from the Commands menu).
You can assign 10 folders of your choice to RCtrl+0 ... RCtrl+9.
This feature is described in details in Far Help (select Commands -> Folder shortcuts then press F1).

**Comment by akruphi** [comment]
I agree that this will be very useful features.
Similar suggestion was in [#1220](https://github.com/elfmz/far2l/issues/1220#issuecomment-1025227168).

**Comment by elfmz** [comment]
is ~ always on ` key in all sane layouts? if so i guess it makes sense to create Ctrl+` hotkey otherwise not sure

**Comment by akruphi** [comment]
> is ~ always on `` key in all sane layouts? if so i guess it makes sense to create Ctrl+` hotkey otherwise not sure

In my practice the \`  and ~ located in 1 key in standard US-layout. In https://en.wikipedia.org/wiki/List_of_QWERTY_keyboard_language_variants I see very different situations for regional layouts, and in some situations ~ may be in other key then \`, but I hope that it is not problem if in help will be clearly write 
Change to the home directory   Ctrl+\`

Also in Alt+F1/F2 panel please to ~ add shortcut key \` or if not possible set 2 shortcuts to locations change to \` may be more useful (not sure it discussion).

**Comment by czaerlag** [comment]
> is ~ always on `` key in all sane layouts?
Well, I guess English layout is common for most of keyboards. On my English/Russian keyboard "~" and "`" are on the leftmost key in the first row. (And, by the way, backslash in English layout changes for forward slash in Russian layout, but the hotkey works in both).
> if so i guess it makes sense to create Ctrl+`
Yes, that's what I meant

**Comment by czaerlag** [comment]
> is ~ always on `` key in all sane layouts?

Well, I guess English layout is common for most of keyboards. On my English/Russian keyboard ~ and `` are on the leftmost key in the first row. (And, by the way, backslash in English layout changes for forward slash in Russian layout, but the hotkey works in both).

> if so i guess it makes sense to create Ctrl+`

Yes, that's what I meant

**Comment by czaerlag** [comment]
Thanks a lot! )
But. On my keyboard the hotkey works well in English layout, but does not work when switched into Russian.
The Ctrl+\ works in both, though "\\" in English changes for "/" in Russian, as well as "`" in English changes for "ё" in Russian.
