### ISSUE TITLE
can not change directory to ~/.wine/dosdevices/c: (or z:)

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#155]
![far2](https://cloud.githubusercontent.com/assets/1151423/19536681/a284e902-9655-11e6-916d-0001f1ebba05.png)
![far22](https://cloud.githubusercontent.com/assets/1151423/19536682/a29ac90c-9655-11e6-99d0-1eb251d93506.png)

**Comment by elfmz** [comment]
..just vague memories about prvious life

**Comment by elfmz** [comment]
check now, I've fixes handling dirs like C:, but dont want to install wine to check exact case

**Comment by unxed** [comment]
building

**Comment by unxed** [comment]
confirming fixed.
