### ISSUE TITLE
tabs pasting problem

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1558]
1. put string
```
				if (!FirstSave || m_editor->IsFileChanged() || apiGetFileAttributes(strFullFileName) != INVALID_FILE_ATTRIBUTES)
```
into the clipboard
2. enable "expend newly entered tabs to spaces" option
3. paste this line to new file opened in editor
4. first tab will be replaced to spaces

**Comment by elfmz** [comment]
In my case no tabs are expanded - all are pasted as tabs, however if choose expand all tabs to spaces - then all are expanded, that looks as correct behavior..

**Comment by unxed** [comment]
important detail: bug is only reproduced is .editorconfig file with certain settings exists in the current folder. so the right steps to reproduce is

1. create new folder
2. create `.editorconfig` file in it with the following content:
```
[*]
indent_style = space
indent_size = 2
```
3. create new file in editor in this folder
4. put string
```
				if (!FirstSave || m_editor->IsFileChanged() || apiGetFileAttributes(strFullFileName) != INVALID_FILE_ATTRIBUTES)
```
input the clipboard
5. paste it to editor
6. under wx, first one of 4 leading tabs will be replaced to 2 spaces. under ttyxi, first one of 4 leading tabs will be replaced to 2 spaces if paste using ctrl+v. if paste using shift+ins, all leading tabs disappear.

**Comment by unxed** [comment]
In vertical block mode all tabs are converted to spaces in such cases, not just the first one.

**Comment by unxed** [comment]
The bug disappears if `Auto indent` is disabled.

**Comment by unxed** [comment]
The problem is here:

```
				if (EdOpt.AutoIndent)		// первый символ вставим так, чтобы
				{							// сработал автоотступ
					// ProcessKey(UseDecodeTable?TableSet.DecodeTable[(unsigned)ClipText[I]]:ClipText[I]); //BUGBUG
					ProcessKey(ClipText[I]);	// BUGBUG
					I++;
					StartPos = CurLine->GetCurPos();

					if (StartPos)
						StartPos--;
				}
```

**Comment by unxed** [comment]
Ой, там с поведением вставки вообще куча странного обнаружилась!

Пример: при включённом Auto indent, если попробовать вставить из буфера единственный символ, поставив курсор во вторую позицию пустой строки в режиме T4, то символ вставится в первую позицию, а после него вставится таб. ПАЧИМУ?!

Ещё пример: в режиме T4 копируем в буфер символ таба, ставим курсор в 5 позицию пустой строки, вставляем. Пустые места занимаются 4 пробелами, а не табом. Это, кстати, происходит и если просто курсор в 5 позицию пустой строки в режиме T4 поставить и попробовать набрать что-нибудь.
