### ISSUE TITLE
home folder size calculated incorrectly

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#156]
![far2](https://cloud.githubusercontent.com/assets/1151423/19538529/24b0e55a-965d-11e6-8e8c-687d1eee48db.png)

my /home/unxed shown as 400G (on a 100G partition)
guess ~/Desktop size is calculated multiple times:

as /home/unxed/Desktop
as /home/unxed/.wine/dosdevices/c:/users/Desktop
as /home/unxed/.wine/dosdevices/z:/home/unxed/Desktop
same with documents, images, videos. etc

wine's wrappers (like PlayOnLinux) also maintain their own wineprefixes with similar simlinked folders

guess simlinks should be excluded from recursive size calculation

another issue is "cluster size" showing random value.

**Comment by unxed** [comment]
my /home/unxed shown as 400G (on a 100G partition)
guess /home/Desktop size is calculated multiple times:

as /home/unxed/Desktop
as /home/unxed/.wine/dosdevices/c:/users/Desktop
as /home/unxed/.wine/dosdevices/z:/home/unxed/Desktop
same with documents, images, videos. etc

**Comment by unxed** [comment]
guess simlinks should be excluded from recursive size calculation

**Comment by unxed** [comment]
quick and possibly dirty fix included
[dirinfo.zip](https://github.com/elfmz/far2l/files/545523/dirinfo.zip)

btw, total size still slightly differs from du. needs investigation.

**Comment by unxed** [comment]
made some experiments. du shows 1-byte file taking 4 bytes on disk, far shows actual size.

**Comment by unxed** [comment]
btw, this code gives different results as "Real file size" from time to time
![far1](https://cloud.githubusercontent.com/assets/1151423/19616662/c64f2fb4-9821-11e6-87dc-57cf3d10867a.png)
![far3](https://cloud.githubusercontent.com/assets/1151423/19616663/c6537fe2-9821-11e6-930d-e17455cfc757.png)

**Comment by unxed** [comment]
Fixed "real file size", sources attached.
[dirinfo.zip](https://github.com/elfmz/far2l/files/545584/dirinfo.zip)
![far2](https://cloud.githubusercontent.com/assets/1151423/19616700/e860ce72-9822-11e6-93e0-b6dbacf1eea4.png)

**Comment by elfmz** [comment]
There is option 'Settings/scan symbolic links' that fixes that. I checked behaviour of Windows FAR3 on such symlinks structure - it also has same 'issue'.
So there is question - if its bug at all? There is recursion guard code, but this is not actually recursion.
