### ISSUE TITLE
Help F7 not show in key bar in Help

### ISSUE THREAD

**Issue by akruphi** [elfmz/far2l#1561]
Values `HelpF7` present in `far2l/bootstrap/scripts/farlang.templ.m4` but really not show in key bar in Help (key **F7** really working). Why?
It will fully close #1321 

Similar with `HelpShiftF3`, `HelpShiftF7` which mentioned in `farlang.templ.m4` but not show in key bar and not really working.

**Comment by elfmz** [comment]
fixed F7, but ShiftF3 ShiftF7 not implemented and they seems not function under FAR3 either, i even dont know what they suppose to do
