### ISSUE TITLE
chafa don't show anything in far2l --tty (konsole)

### ISSUE THREAD

**Issue by Guest007** [elfmz/far2l#1578]
Попробовал использовать `chafa` для быстрого просмотра изображений, но оказалось, что в из запущенного в Konsole `far2l --tty` изображение отсутствует. Ни при запуске из ком.строки, ни по F3 -> F5. Кстати, после F3 -> F5 просто какие-то ESC-последовательности вместо того, что видно в WX (см. скриншот)
Проверял в WX версии, в текстовом терминале (вне GUI-сессии), из Kitty и из штатной консоли (Konsole). Проблемы только при запуске в комбинации `far2l --tty` + `konsole`. В самой Konsole `chafa` работает нормально.

![изображение](https://user-images.githubusercontent.com/147067/228902179-4c647dba-b3fd-4251-8f61-8e20c546d3fb.png)

**Comment by elfmz** [comment]
А какая версия konsole и вообще что за система? В kubuntu 22 вроде все ништяк:
![Screenshot_20230401_172302](https://user-images.githubusercontent.com/20957349/229294935-3a81baf2-0583-499f-bd99-cbf796534c53.png)

**Comment by Guest007** [comment]
Manjaro
![image](https://user-images.githubusercontent.com/147067/229509354-f4ce58b4-02eb-4cdf-a29d-1f9d6b6db6a6.png)

**Comment by atolismesh** [comment]
Воспроизводится 100%, как описал автор issue.  Manjaro KDE Rolling update.

**Comment by Guest007** [comment]
Внутренний терминал far2l (неважно, gui или tty) работает только с `chafa -f symbols`. Варианты iterm, kitty, sixels  не выводят картинку. KDE'шный `konsole`, к примеру, выводит во всех вариантах output format (хотя все они немного отличаются).
Видимо в GUI варианте `chafa` автоматически понимает и выводит в формате `-f symbols`. А для `far2l --tty` в `konsole` (в Mandjaro по крайней мере) `chafa` автоматически пытается выводить в формате `-f sixels`.
Проблема решается принудительным указанием `-f symbols` для `chafa` в `view.sh`
