### ISSUE TITLE
Settings Configuration View Import Export

### ISSUE THREAD

**Issue by Gravityzwell** [elfmz/far2l#159]
Is there any way to import/export settings to a text file? Wine uses flat text files for registry hives (human readable). What is the directory tree + binary files approach (non human readable) that f2l uses?

**Comment by elfmz** [comment]
everything in ~/.far2l. registry in hku/hklm subfolders. format is not 'very binary', the only issue that strings stored as hex-values of chars. this is because it was easiest way due to uniform (same format for all possible registry types)

**Comment by Gravityzwell** [comment]
Right, it's a directory tree with files containing strings of hex-values :)

I suppose I could have figured that out (but I didn't). With that clear, I can at least decode macro's, etc., to see what they are and change them if I want.

**Comment by Gravityzwell** [comment]
Any plans to serialize settings a different way? 

If not, and if I decided to try, do you approve of:
https://github.com/kimkulling/openddl-parser
http://openddl.org/

**Comment by elfmz** [comment]
looks redundant, but not very bad:)
and do yuo want to make whole registry in single file? current approach in some degree more reliable for corruption than single file..

**Comment by Gravityzwell** [comment]
At first I thought the serializer should have explicit types. But now I realize it should not. The app will know if it's pulling or writing a string, and the user should not able to change that (to an int).

So a leaner serializer makes sense, preferably no extra libraries.

Personally I prefer one file (better for the user). The app can write first to a temp, then if successful, replace the original. Also, if necessary, the last X versions can be saved, like config.001 config.002, etc. Lots of apps save settings to a single file and get along fine.

**Comment by elfmz** [comment]
The situation complicated by fact that registry shared across different processes (we don't want to limit to single instance of far) while there is no separate 'flush' point in code. Any 'write' should be immediately be visible for other readers.
Right approach to put everything into single file is to use db, that is actually done in far3. And still it produced there some concurrency-related bugs. And even in far3 (more exactly - in plugins) code still not completely migrated to db. Registry&sqlite coexist there.

**Comment by Gravityzwell** [comment]
So maybe not "one" file. Anything "history" should be separate in my opinion. I dislike Total Commander's INI that has the main settings, plus previous directories, previous searches, etc., all in one file. Thus comparing what really changed for base settings is complicated by the history.

If the user did not explicity change a setting via an option menu, and still something is written, then that's "history", and should be separate.

**Comment by unxed** [comment]
what about using dconf for registry storage as it is often done by native linux software?
it is the same hierarched key-value storage as windows registry and can be accessed by simply invoking "gsettings" command line utility to read or write data.

**Comment by elfmz** [comment]
is there dconf on osx?

**Comment by unxed** [comment]
is there gvfs-trash on osx?

> dconf mostly targets Free Software operating systems. It will theoretically run on Mac OS but there isn't much point to that (since Mac OS applications want to store preferences in plist files).
https://developer.gnome.org/dconf/unstable/dconf-overview.html

btw, if cross-platform approach is needed, sqlite can be preferred choise as it is done in far3

**Comment by elfmz** [comment]
Oh.. I also thought about putting sqlite inside of registry API.. Nice idea, but since me rather lazy and pragmatic likely I'll just make v-* files more human readable :)

**Comment by unxed** [comment]
gsettings output can be considered human-readable, btw.
`
unxed@rs ~ $ gsettings get org.mate.caja.desktop font
'Noto Sans 10'
`

**Comment by unxed** [comment]
btw, how concurrent writes to registry files by different instances of far are handled currently?

**Comment by unxed** [comment]
k-Software/k-Far2/k-Colors/k-Highlight/k-Group0/v-DateAfter

DateAfter
3:\0\0\0\0\0\0\0\0

not sure if it can be considered human-readable (if not a bug)
what does format "3" actually means?

**Comment by unxed** [comment]
https://github.com/Maximus5/FarPlugins/tree/master/RegEditor

may porting this plugin be a solution for making registry edition more user-friendly?

**Comment by Alter-1** [comment]
Perl script for .REG import
supports Unicode regedit5 and manual charset specification for Regedit4  (1251 is used be default)
has Far 1.x migration option
requires iconv utility
https://alter.org.ua/soft/linux/far2l_reg
[Far2lRestore.pl.gz](https://github.com/elfmz/far2l/files/2976867/Far2lRestore.pl.gz)

**Comment by alexmyczko** [comment]
> Is there dconf on osx? 
> Using command line here is bad idea. This will kill performance.
> 

they have `defaults` which also exist with GNUstep

**Comment by unxed** [comment]
far2l actually already switched to .ini files as configuration storage format.
