### ISSUE TITLE
can not change charset if .editorconfig file present

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1592]
Try to change file encoding of any file in far2l's source tree in editor using F8 or Shift-F8.

**Comment by unxed** [comment]
Probably it's a feature, not a bug! accident charset change hurts! Probably we don't need fixing it, but just documenting it. Or, at lease, we may show some confirmation box before charset change in such cases. And, anyway, tab mode and size should behave the same way as charset.

**Comment by akruphi** [comment]
PR with code of warnings was merged. This issue may be closed.
