### ISSUE TITLE
navigation errors then "options"-"interface settings"-"use ctrl+pageup to change drive" option is disabled

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#160]

**Comment by unxed** [comment]
may be removed, actually

**Comment by elfmz** [comment]
hm. For me it looks working. You navigated to root (/) pressing ctrl+pgup shows drives menu, just like in Windows FAR when navigated to doort of any drive

**Comment by unxed** [comment]
well, with this option turned off I get Error 2 then trying to navigate to /bin/ after pressing Ctrl+PgUp. Looks like Far2l changes current dir to nowhere in that case. Is it expected behavour?

**Comment by elfmz** [comment]
aha, then its not non working option but nonworking something else then this option is off)
