### ISSUE TITLE
Autocompletion issue

### ISSUE THREAD

**Issue by spvkgn** [elfmz/far2l#1606]
Создать в пустой директории например `mkdir -p 'a b' 'b a'`
При `cd` (без ./) автодополнение по двойному Tab выводит такое:
![Снимок экрана в 2023-04-11 16-03-35-crop](https://user-images.githubusercontent.com/4147135/231142629-c96624e0-bbf2-4d62-b853-797529cca218.png)
Upd: при `ls` то же самое.

**Comment by TrNullFree** [comment]
I think this issue has the same roots as #1417.

Also, if you try to put file or directory name containing space char(s) into command line by pressing Ctrl-Enter, Ctrl-F,   it  will contain back slash (\) before space char.

**Comment by spvkgn** [comment]
Хм…
![Снимок экрана в 2023-05-28 20-02-14-crop](https://github.com/elfmz/far2l/assets/4147135/32a30e41-94ea-41f6-b056-ac2c09ba2582)

**Comment by atolismesh** [comment]
Плюсую 
UP

**Comment by elfmz** [comment]
проверяйте, должно пофикиться...

**Comment by akruphi** [comment]
@elfmz у меня данный глюк с автодополнением кучей вариантов с ♪ больше не воспроизводтся :+1:

**Comment by atolismesh** [comment]
@elfmz теперь тестовый пример с "cd   a b" работает корректно. 
Но появился новый глюк с autocompletion: 
Если набрать в ком строке просто  одиночный символ a или b или c и нажать двойной Tab, то получим много "мусора" в ком строке: 
![image](https://github.com/elfmz/far2l/assets/130924690/1ff7b2fb-74d4-4466-bb34-0188cb1c11a9)

**Comment by spvkgn** [comment]
@elfmz Возможно ли вместо ковычек экранирование пробелов ? Иначе получается, что имена директорий с пробелами будут впереди остальных:

<details>
<summary>Details</summary>

![Снимок экрана в 2023-06-25 13-41-27-crop](https://github.com/elfmz/far2l/assets/4147135/d296be61-2fd5-4b56-819f-8efdb2c862ea) ![Снимок экрана в 2023-06-25 13-42-17-crop](https://github.com/elfmz/far2l/assets/4147135/858e3cd3-2d5a-4938-be1e-2e1f98944220)


</details>

**Comment by akruphi** [comment]
Посмотрел. У меня также после проверок автодополнения far2l по Tab в `.bash_history` появляется мусор
```
true jkJHYvgT
```

**Comment by elfmz** [comment]
а сейчас?

**Comment by atolismesh** [comment]
@elfmz Теперь одна буква отрабатывает правильно, мусор в .bash_history не появляется!

**Comment by atolismesh** [comment]
Осталась небольшая неконсистентность с тестовым примером "a b": 
если сделать cd в каталог "a b" 

<details>
<summary>Details</summary>

![image](https://github.com/elfmz/far2l/assets/130924690/79e4f3cb-6477-471a-ab23-9aa59052820d)

</details>

и в нем еще раз сделать cd .. Tab Tab то будет выгладеть так: 

<details>
<summary>Details</summary>

![image](https://github.com/elfmz/far2l/assets/130924690/e6fe989e-3a6a-45eb-9c75-d4774e928700)

</details>

Т.е. вместо  `cd "./a b"`  опять бэкслэш  `cd ./a\ b`  перед пробелом.

**Comment by elfmz** [comment]
а если написать cd ".. то закроется со слэшем как полагается.. просто тогда оно предлагает вариант сообразно уже напечатанному

**Comment by atolismesh** [comment]
@elfmz Да, забавно получается - если нажать TabTab, то с бэклешем; если TabTabTabTab - то в кавычках. 
Вопрос снимаю

**Comment by elfmz** [comment]
так что, можно закрывать?

**Comment by spvkgn** [comment]
@elfmz https://github.com/elfmz/far2l/issues/1606#issuecomment-1605948079

**Comment by elfmz** [comment]
ну все же в к

> Возможно ли вместо ковычек экранирование пробелов ? Иначе получается, что имена директорий с пробелами впереди остальных:

Все же с кавычками проще читается имхо. А чтоб порядок был норм, просто сортировку сделал до закавычивания...

**Comment by elfmz** [comment]
ну раз никто не против такого решения, то закрываю
