### ISSUE TITLE
Навигация в стиле lynx

### ISSUE THREAD

**Issue by dvlom99** [elfmz/far2l#1611]
До недавней "починки" действия комбинации "Ctrl+PgDn" над симликами использовал макросы на клавиши "Left" и "Right" - "Ctrl+PgUp" и "Ctrl+PgDn", соответственно, и вполне успешно "ходил" по дереву каталогов и архивам, не боясь что-нибудь случайно запустить. Теперь с симлинка на каталог по "Ctrl+PgDn" попадаю не внутрь каталога, а на сам каталог, что приводит к ..., не приводит оно ни к чему хорошему.

Подскажите, может есть еще какая клавиатурная комбинация, которая одинаково ведет себя и на каталогах и на симлинках на каталоги для входа внутрь них, и при этом это не "Enter"?

**Comment by elfmz** [comment]
как вариант, можно сделать недавнюю новую фичу - настраиваемой

**Comment by dvlom99** [comment]
Да, настройка поведения по нажатию "Ctrl+PgDn" над симлинком не помешает, если другие варианты не рассматривать. 

Может быть для п.1 из #1587 сменить клавиатурную комбинацию? А для "Ctrl+PgDn" оставить старое поведение. Мне кажется, что оно более логичное - это движение внутрь активного объекта панели.

**Comment by akruphi** [comment]
В настоящий момент в помощи ("Команды управления панелями - сервисные команды") написано про различное поведение **Ctrl-[Shift-]PgDn** для архивов (у себя я это в far2l-gui не наблюдаю - что с **Shift**, что без, а также по **Enter** проваливаюсь в архив на панели far2l - в помощи атавизм windows версии или?).

Как вариант решения - можно для symlinks сделать переход только по **Ctrl-Shift-PgDn** как действие требующее большего осмысления, чем короткое **Ctrl-PgDn**. Хотя вопрос насколько в терминалах будет ловится **Ctrl-Shift-PgDn**.

**Comment by ivanshatsky** [comment]
Согласен на **Ctrl-Shift-PgDn**, тем более что те, кто захотят использовать более простую комбинацию **Ctrl-PgDn**, насколько я понимаю, легко смогут себе её намакросить. И этот же макрос снимет вопросы с отлавливанием такой комбинации в терминалах.

**Comment by dvlom99** [comment]
Отличню.
Про **Ctrl+Shift+PgDn** не знал... Предлагаю эту комбинацию для "старого" поведения, т.е. для входа в каталог, куда указывает симлинк. Соответственно, если симлинк указывает на файл, то по этой комбинации мы должны попытаться открыть его как архив, безусловно.

По **Ctrl+PgDn** - переход в каталог, где находится каталог, куда указывает наш симлинк, если я правильно понял изначальную идею. Кстати, а зачем это бывает нужно?

**Comment by elfmz** [comment]
сделал чтоб Ctrl+PgDn работал по старому, а по новому - Ctrl+Shift+PgDn

**Comment by akruphi** [comment]
> сделал чтоб Ctrl+PgDn работал по старому, а по новому - Ctrl+Shift+PgDn

Возможно для симметрии имеет смысл продублировать **Ctrl-PgUp** комбинацией **Ctrl-Shift-PgUp**.

Теперь думаю как это изменение в **помощи** по **F1** внятнее отразить, чтобы про фичу пользователи знали.
Вопрос к @elfmz: описанное в помощи про архивы поведение **Ctrl-[Shift-]PgDn** актуально (у меня никак не проявляется) или атавизм и из справки это убирать? (я про строки 624-631 в  `far2l/bootstrap/scripts/FarEng.hlf.m4` и строки 633-640 в `far2l/bootstrap/scripts/FarRus.hlf.m4`)

Также просьба к @elfmz, если есть время, заглянуть в #1598 - буду благодарен за любые указания на неточности в черновике wiki.

**Comment by elfmz** [comment]
> Возможно для симметрии имеет смысл продублировать **Ctrl-PgUp** комбинацией **Ctrl-Shift-PgUp**.

Типа чтоб возвращался с запоминанием в свою дополнительную историю директорий? Можно..

**Comment by elfmz** [comment]
..можно щупать

**Comment by elfmz** [comment]
Есть еще идея по Ctrl+Shif+PgUp проводить 'отмотку' истории переходов в директории которая по Alt+F12, а не только симлинков. Правда пока не очень понятно как эта отмотка должна взаимодействовать с самой историей.

**Comment by akruphi** [comment]
> ..можно щупать

Интересно получилось. Сейчас, если перейти на symlink по **Ctrl-Shift-PgDn** и затем походить по каталогам, то нажатие **Ctrl-Shift-PgUp** вернёт к symlink. Не интуитивно, но логично. Думаю далее усложнять тут логику не стоит - уже на грани запутанности.

@elfmz правильно ли я понимаю, что то что в помощи написано про архивы по Ctrl-Shift-PgDn уже не актуально и сейчас логика клавиш исчерпывается следующим:
* Ctrl-PgDn — Смена каталога, вход в архив
* Ctrl-Shift-PgDn — аналогично Ctrl-PgDn + для symlink переход к его расположению
* Ctrl-PgUp — Перейти в каталог уровнем выше (из корня в меню точек монтирования / файловых плагинов)
* Ctrl-Shift-PgUp — если ранее был переход по Ctrl-Shift-PgDn на symlink, то возврат к symlink
?

Отловил баг: если в каталоге symlink на `.` то нажатие на нём просто **Ctrl-PgDn** смешает каталоги вглубь вместо того, что остаться в текущем каталоге. Например, у меня symlink `/bin/X11 ->.` и трехкратное нажатие на нём либо **Enter**, либо **Ctrl-PgDn** даёт внутри far2l несуществующий текущий каталог `/bin/X11/X11/X11` (и т.д.) Интересно, что такой же баг присущ и файловой оболочке GNOME, но как-то это некорректно - я за то, чтобы пофиксить.

**Comment by elfmz** [comment]
> не очень понял логику `EnableAssoc` в `ProcessEnter()`

Логика там простая - если shift не был нажат, то вначале пытаемся открыть файл через 'свои' ассоциации вызовом ProcessLocalFileTypes. То есть в принципе работать должно с архивами как описано. Если конечно там чтото не сломалось.

**Comment by atolismesh** [comment]
А как быть тем кто уже начал этим активно пользоваться и у кого переключание раскладки клавиатуры идет через Ctrl+Shift? 
Ctrl-Shift-PgDn в таком случае не работает.....

**Comment by dvlom99** [comment]
> Отловил баг: если в каталоге symlink на `.` то нажатие на нём просто **Ctrl-PgDn** смешает каталоги вглубь вместо того, что остаться в текущем каталоге. Например, у меня symlink `/bin/X11 ->.`

@akruphi :  Также ведет себя Midnight Commander в режиме навигации в стиле lynx при нажатии конопки **Right**.

**Comment by akruphi** [comment]
> А как быть тем кто уже начал этим активно пользоваться и у кого переключание раскладки клавиатуры идет через Ctrl+Shift? Ctrl-Shift-PgDn в таком случае не работает.....

Совсем уж конкретная комбинация мне не принципиальна - главное нам потом это **чётко документировать в помощи**.

@atolismesh : вариант быстрого решения проблемы без серьёзных раздумий и выбора: кроме **Ctrl-Shift-PgDn** продублировать через **Ctrl-Alt-PgDn** (как **Ctrl-Shift**,  так и **Ctrl-Alt** через gnome-tweaks можно выбрать переключатель языка, при дублировании двумя комбинациями милосердны к пользователям обоих типов переключения).

**Comment by atolismesh** [comment]
@akruphi 
> кроме Ctrl-Shift-PgDn продублировать через Ctrl-Alt-PgDn 

Норм. 
Если совсем будет раздражать, то можно у себя патчить перед сборкой и возвращать Ctrl+PgDn.

@elfmz 
> как вариант, можно сделать недавнюю новую фичу - настраиваемой 

Так было бы совсем хорошо

**Comment by atolismesh** [comment]
> вполне успешно "ходил" по дереву каталогов

Ctrl+T не подходит?

**Comment by dvlom99** [comment]
> Ctrl+T не подходит?

Не подходит.

**Comment by dvlom99** [comment]
@elfmz Наверное, тикет можно закрыть?

**Comment by akruphi** [comment]
> @elfmz Наверное, тикет можно закрыть?

@dvlom99 пока не решён поднятый @atolismesh вопрос про недоступность комбинаций **Ctrl-Shift** при его переключении языка наверное рано закрывать. Или @atolismesh уже намакросил себе альтернативу через ~/.config/far2l/settings/key_macros.ini и больше не претендует на изменения в коде?

**Comment by atolismesh** [comment]
@akruphi @elfmz 
Да, можно закрывать. 
Я себе намакросил.
