### ISSUE TITLE
[Netrocks] SCP/SFTP and busybox strange behaviour 

### ISSUE THREAD

**Issue by atolismesh** [elfmz/far2l#1617]
При входе через [Netrocks] SCP/SFTP  в OpenWrt c dropbear, busybox , по умолчанию попадем в home каталог пользователя (/root). 
Чтобы из него выйти в корневой каталог, приходится набирать команду 
```
cd /
``` 
Ctrl+PgUp или Enter на ".." выбрасывают обратно в Netrocks, а не в родительский каталог ("/").
Просьба поправить, чтобы переход был в родительский каталог ("/").

**Comment by elfmz** [comment]
В свойствах соединения укажите Working directory: /
