### ISSUE TITLE
define a scipt which will be executed before Far manager starts

### ISSUE THREAD

**Issue by danilagalimov** [elfmz/far2l#1619]
I have the system variable defined in ~/.zprofile file, I would like that Far can execute this file before start. It seems that it is not possible during current design.

**Comment by elfmz** [comment]
whats the purpose of that?

**Comment by danilagalimov** [comment]
The purpose for example, is to define the variables which are defined in the profile script when I start the terminal (i.e. PATH and so on), but are NOT defined when Far is started, so I cannot execute the same commands in the terminal and in Far manager.

**Comment by danilagalimov** [comment]
Current example:
In my .zprofile there is a line:
`eval "$(/opt/homebrew/bin/brew shellenv)"`
which sets up all of the variables and PATH so I can use brew application.

When I start the terminal, everything works as expected, but when I start Far - no brew apps can be started without explicit path. Of course, I can copy-paste this line in the Far manager so the variables will be defined in Far as well, but I will have to repeat this action every time Far is closed and opened again.

**Comment by danilagalimov** [comment]
It also seems that for some reason /Applications/far2l.app/Contents/MacOS/open.sh  is not executed at all (or I didn't find the way to get it executed).

**Comment by elfmz** [comment]
open.sh cannot be used for what you need. Its used when you open a document for example

**Comment by elfmz** [comment]
BTW there is /etc/paths and  /etc/paths.d under MacOS and both are handled by far2l. And they're looking more correct place for setting PATH as they're shell independent

**Comment by danilagalimov** [comment]
For brew it won't work since the paths are dynamic, not hardcoded. For example, if you run 
`/opt/homebrew/bin/brew shellenv` (which is actually run from .zprofile) it will give you this:

```
export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";
```

So it is not something which should be hardcoded in etc/paths.

**Comment by elfmz** [comment]
It doesn't work as expected in any case as any environment changes that done via spawning process do not affect far2l itself as its a separate process. If you run source ~./profile in the command prompt - it still affects only shell behind that prompt but not far2l itself.

**Comment by danilagalimov** [comment]
But since my variable changes are saved in any consequent command executions, I assume that Far uses the **single** shell instance to launch all of the commands, right? 
So I need to execute the command in the scope of this shared shell instance.

**Comment by danilagalimov** [comment]
Sorry, of course I used `~/.zprofile`, it was just a copy-paste error.

**Comment by atolismesh** [comment]
zsh does not use the ~/.zprofile  file by default. Only if invoked as login shell.
You need to modify and use the ~/.zshrc and ~/.bashrc files

**Comment by elfmz** [comment]
i can suggest to create file like ~/.config/far2l/env which may have lines like
NAME=VARIABLE or event shell expandable things like
NAME=$(some command)
but not arbitrary script

**Comment by danilagalimov** [comment]
@atolismesh , yes, I'm trying to use `zsh ~/.zprofile` as a command or even `source ~/.zprofile` as a command.

**Comment by danilagalimov** [comment]
@elfmz , environment file sounds great, but how it will execute something like `eval "$(/opt/homebrew/bin/brew shellenv)"` ?

**Comment by atolismesh** [comment]
![image](https://user-images.githubusercontent.com/130924690/234117613-b8e701e1-dd69-4c86-9089-8b4604ec2ef6.png)
Did you try set shell to /bin/zsh in far2l "Command line settings"?

**Comment by atolismesh** [comment]
Try execute
```
eval "$(/opt/homebrew/bin/brew shellenv)"  ; your_command
```

**Comment by danilagalimov** [comment]
You mean as a shell?

**Comment by danilagalimov** [comment]
If if execute `eval "$(/opt/homebrew/bin/brew shellenv)"` in the Far command prompt, then everything is ok from this point (unless you execute "exit" command and shell is re-launched).

**Comment by atolismesh** [comment]
From far2l command line

**Comment by danilagalimov** [comment]
From command prompt it is working fine

**Comment by danilagalimov** [comment]
It seems that I've used function with incorrect flags.

Anyway, I've changed the approach to execute the command on every new shell spawn and this works perfectly fine for me:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/118568661/234423943-79a9922b-7be0-4896-82b1-69dc9a5e6314.png">
[Add_ability_to_execute_a_startup_script_1.patch](https://github.com/elfmz/far2l/files/11327373/Add_ability_to_execute_a_startup_script_1.patch)

**Comment by elfmz** [comment]
I checked on my test MacOS and changing /etc/zshrc works so don't see need to add this extra option

**Comment by danilagalimov** [comment]
Yes, you can change `/etc/zshrc` and/or `/etc/zprofile`, but I think it might be the useful feature to get some command executed in the shell in case you need it.

**Comment by elfmz** [comment]
Potentially its possible to 'fix' 'Use shell option' so it will be possible to specify extra arguments, for instance `bash --init-file /path/to/your/rcfile` and that file will be used instead of default one, is it looks ok for such purpose? Currently it doesnt work as whole option's string treated as single command argument.

**Comment by danilagalimov** [comment]
Yes, I think it should work, let me try it

**Comment by elfmz** [comment]
Don't forget to invoke original rcfile from yours

**Comment by danilagalimov** [comment]
For some reason it doesn't work at all.
I've tried using `/bin/zsh -i source ~/.profile` as command line settings, but in this case any command is just not executed. `/bin/zsh source ~/.profile` Doesn't work either

**Comment by elfmz** [comment]
zsh doesnt have --init-file - like argument, so two ways possible:
1) Use bash but not zsh, by specifying Shell: `bash --init-file ~/bashrc.far2l -i` note that -i must be after --init-file otherwise it doesn't work
2) Run 'double' shell,  `sh -c ". ~/far.rc; zsh -i"`
where ~/far.rc does all needed env preinitialization, like:
```
export SOMEWHAT=WHATEVER
export SOMETHINSELSE=WHATEVERELSE
```

**Comment by danilagalimov** [comment]
Actually, I just tried to use zsh in the login mode (/bin/zsh -l) an it does what I need - starts zsh and executes ~/.zprofile file, so it works this way.

**Comment by elfmz** [comment]
so closing then - there're now several ways at least possible
