### ISSUE TITLE
[Netrocks] SCP/SFTP Attributes dialog does not work with files

### ISSUE THREAD

**Issue by atolismesh** [elfmz/far2l#1622]
При нажатии Ctrl-A (Show\Change Attributes) на любом файле в [Netrocks] SCP/SFTP появляется окно с предложением поменять атрибуты текущего каталога, а не файла. 
FAR2L, version 2.5.0-e4ce7184-beta Linux x86_64.

![image](https://user-images.githubusercontent.com/130924690/232625418-5f0562e0-e948-494a-864b-2cd07498bd03.png)

Если в этом окне нажать F1, то получаем ошибку: 
![image](https://user-images.githubusercontent.com/130924690/232626403-80f8c5e4-ef07-4030-933c-a423348dbf13.png)

**Comment by elfmz** [comment]
Дословный перевод - 'Редактировать режим файлов и директорий в:'
и путь ниже - директория, в котором находятся файлы, которые имеются ввиду..

**Comment by atolismesh** [comment]
Я хочу поменять атрибуты файла ("При нажатии Ctrl-A (Show\Change Attributes) на любом файле "), а не дает. Вместо этого предлагает поменять атрибуты директории и всех файлов и директорий в нем.

**Comment by elfmz** [comment]
Слова 'всех' тут нету. Хотя согласен что не помешает как минимум написать 'selected files and directories' 
(ну просто было лень делать различные фразы для одного файла, одной директории, или нескольких выделенных объектов)
В целом, работает именно для выделенного объекта/объектов в указанной директории.

**Comment by akruphi** [comment]
@elfmz тут было бы полезно сверху, например, после строки с директорией добавить строку примерно такого вида:
* `affected on file: ????.???` - для случая, когда нет выделения, но курсор на файле
* `affected on directory: ????.???` - для случая, когда нет выделения, но курсор на каталоге
* `affected on NN selected files` - для случая, когда выделен хотя бы один файл
* `affected on MM selected directories & NN selected files` - для случая, когда среди выделенных и файлы и каталоги

Всё остальное тут уже Netrocks'ом отлично показывается: если выделить файл или группу файлов, то Ctrl-A правильно показывает их текущие выставленные атрибуты  и `?`  если они разные :+1:  и если текущий или среди выделенных каталог, то присутствует галочка [x] Recursive :+1: .

**Comment by atolismesh** [comment]
@akruphi 
Спасибо!

**Comment by atolismesh** [comment]
@elfmz Спасибо!
