### ISSUE TITLE
[keys bugs] Ctrl+ symbol

### ISSUE THREAD

**Issue by akruphi** [elfmz/far2l#1625]
В **far2l-gui** при русской раскладке левый **LCtrl+буквенные клавиши** работают все; а для правого **RCtrl** часть работают (**+A**, **+E**, **+X**, **+Y** и т.п. даже свежий на home **+\`**), но не работают правый **RCtrl+O**, **+L**, **+Q**, **+P**, **+B**, **+U** (только панели дергаются).

В **tty** случае (стандартный gnome-terminal `far2l --tty --ee`) при любой раскладке **RCtrl+O**, **+L**, **+Q**, **+P**, **+B**, **+U** работает. Зато напрочь не работает на home любой **LCtrl+\`** или **RCtrl+\`** даже при eng раскладке.

@unxed если будет возможность, плиз, посмотреть как в других терминалах реагирует.

**Comment by ElderlyLinuxUser** [comment]
Точно не работает RCtrl-O на русской раскладке. Far2l-gui 2.5.0-291c660

**Comment by unxed** [comment]
Это происходит от того, что клавиатурные события при RightControl+русских_буквах приходят дажды. Просто на +A, +E, +X, +Y это не видно (на самом деле, если вы присмотритесь, там на два шага истории команд RightCtrl+E/X работают в русской раскладке).

Исправляется это заменой строчки
```
		|| (dwMods & (RIGHT_CTRL_PRESSED | LEFT_ALT_PRESSED)) != 0
```
на
```
		|| (dwMods & (LEFT_ALT_PRESSED)) != 0
```

в `void WinPortPanel::OnKeyDown( wxKeyEvent& event )`, но я не уверен, что такая замена ничего нигде не сломает. Возможно, это дополнительное условие нужно было в каких-то старых версиях wxWidgets, а сейчас не требуется? Я просто не помню уже, откуда там условие именно на правый контрол. Необходима консультация @elfmz

**Comment by akruphi** [comment]
> Исправляется это заменой строчки
> 		|| (dwMods & (RIGHT_CTRL_PRESSED | LEFT_ALT_PRESSED)) != 0

Спасибо. Судя по истории строка https://github.com/elfmz/far2l/blob/65b964c97a2f278394a04fffdd06d7d1d35beedc/WinPort/src/Backend/WX/wxMain.cpp#L1158 менялась в рамках #954 Тут действительно лучше подождать опытного взгляда @elfmz

**Comment by unxed** [comment]
Конкретный коммит вот, но я всё равно пока не понимаю, зачем там условие на правый Control
https://github.com/elfmz/far2l/pull/954/commits/0eff390a0dc9816ce39aa06cecddaca31a6ff719

**Comment by sirburpalot** [comment]
На macOS баг не проявляется.

**Comment by elfmz** [comment]
а если сделать так:
```
@@ -1160,7 +1160,7 @@ void WinPortPanel::OnKeyDown( wxKeyEvent& event )
        }

 #ifdef WX_ALT_NONLATIN
-       if (alt_nonlatin_workaround) {
+       else if (alt_nonlatin_workaround) {
                OnChar(event);
        }
 #endif
```
2 @unxed  - тот воркэраунд что под WX_ALT_NONLATIN не ломается ли при этом? если все норм то так выглядит правильнее и RCtrl+O работать начинает

**Comment by unxed** [comment]
>  #ifdef WX_ALT_NONLATIN

я вот как раз прямо ща то же самое пробую! только ещё проверку на osx добавил, т.к. на маке баг, кажется, не проявляется, а значит, трогать ничего не надо.

**Comment by unxed** [comment]
а, стоп, нет, не то же самое. прочитал невнимательно. ща переделаю

**Comment by unxed** [comment]
> +       else if (alt_nonlatin_workaround) {

не, это баг почему-то не лечит. а вот мой вариант, который в #1633 — лечит

**Comment by unxed** [comment]
partial в названии PR — это в том смысле, что проблему Ctrl+` в tty он не устраняет

**Comment by elfmz** [comment]
else точно не лечит? у меня лечит - как минимум RCtrl+O RCtrl+L начинают работать так как избавляет от дублирующего события из OnChar. Вопрос ли в том все ли работает под if (alt_nonlatin_workaround)  как должно было работать

**Comment by unxed** [comment]
сейчас ещё раз перепроверю

**Comment by unxed** [comment]
Перепроверил. Ошибка всё ещё на месте. Но меня смущает разница в номерах строк. У меня это изменение выглядит так:

```
diff --git a/WinPort/src/Backend/WX/wxMain.cpp b/WinPort/src/Backend/WX/wxMain.cpp
--- a/WinPort/src/Backend/WX/wxMain.cpp
+++ b/WinPort/src/Backend/WX/wxMain.cpp
@@ -1175,7 +1175,7 @@ void WinPortPanel::OnKeyDown( wxKeyEvent& event )
 	}
 
 #ifdef WX_ALT_NONLATIN
-	if (alt_nonlatin_workaround) {
+	else if (alt_nonlatin_workaround) {
 		OnChar(event);
 	}
 #endif

```

Т.е. строчка 1175, а у вас — 1160. Вы точно никаких других изменений не вносили?

**Comment by elfmz** [comment]
действительно у меня была более ранняя версия, которая осталась от предыдущей дихотомии.. Все же мне не оч нравится меня условие наугад, ведь чтонибудь другое обязательно сломается) чуть позже подебажу..

**Comment by unxed** [comment]
Проверил, работает. Alt+буквы (и русские, и латинские) тоже работают норм. Но нифига себе какое усложнение потребовалось!

**Comment by unxed** [comment]
Так, теперь осталось LeftCtrl+` и RightCtrl+` починить под TTYXI. Это я сам не возьмусь, я там пока не до конца понимаю логику куска, который всякие такие сложные комбинации заставляет работать.

**Comment by unxed** [comment]
Так, теперь осталось Left/RightCtrl+` починить под TTYXI. Это я сам не возьмусь, я там пока не до конца понимаю логику куска, который всякие такие сложные комбинации заставляет работать.

**Comment by unxed** [comment]
Ещё, по поводу wxConsoleInputShim. wVirtualKeyCode не идентифицирует клавишу однозначно (как минимум, в случае Ctrl, Alt и Shift). Использовать его в качестве индекса точно норм?

**Comment by elfmz** [comment]
Ну в данном случае интересны буквенные клавиши, так как на них вешаются хоткеи в менюшке в WinPortFrame::OnShow

**Comment by elfmz** [comment]
Кстати после этого изменения наверное можно убрать #ifndef WX_ALT_NONLATIN здесь:
![image](https://user-images.githubusercontent.com/20957349/234133879-e87d78e0-d358-473b-8613-1d33c57f4c15.png)

**Comment by unxed** [comment]
> Кстати после этого изменения наверное можно убрать #ifndef WX_ALT_NONLATIN здесь:

Тоже об этом подумал.

**Comment by akruphi** [comment]
@elfmz спасибо огромное. Считаю, что плодить дальнейшие костыли и излишне утяжелять код ради одной комбинации клавиш вредно - чёткая логика кода и компактность программы перевешивают полезность частной комбинации Ctrl+`.
Issue закрываю, т.к. основная проблема с RCtrl блестяще решена.

**Comment by unxed** [comment]
> но тогда будет проблема с апликухами внутри far2l которых Ctrl+Space чтото важное делает

Такая проблема возникает не только здесь. Скажем, в поддержке клавиатурных расширений терминала iTerm2 я трактую правый Option (версия Alt на маках) как правый Control, т.к. правый Control есть не на всех клавиатурах, а Command использовать нельзя, он занят хоткеями самого терминала. А правый Alt в far2l всё равно не используется.

Но вот если под far2l запустить другую аппу, которой зачем-нибудь нужен правый Alt, и которая понимает какой-нибудь из продвинутых клавиатурных режимов терминала, которые умеет far2l, будет проблема.

Возможно, для таких случаев надо сделать так, чтобы все клавиатурные сочетания, приходящие в far2l, передавались во встроенный терминал без изменений, а вот перед обработкой в самом far2l проходили через некий слой трансляции, где можно было бы задать кастомные правила, повышающие юзабилити на конкретных платформах. Например, «если мы работаем на маках и в консоли, транслировать правый Alt в правый Control» или «если мы работаем в TTY без Xi, транслировать Ctrl+Space в Ctrl+`» и т.д.
