### ISSUE TITLE
[Feature request] Exclude command from history when it starts with a space

### ISSUE THREAD

**Issue by spvkgn** [elfmz/far2l#1626]
Было бы неплохо добавить аналогичную возможность как это реализовано в bash и т.д.
Например как здесь: https://github.com/VPROFi/far2l/commit/a6ae6755dd7daaeed8e4ab94bc38ed18794b8811

**Comment by elfmz** [comment]
Options/Auto complete settings/добавить в конце пробел звездочка:
![image](https://user-images.githubusercontent.com/20957349/233470661-40d1e2d1-f5a0-4501-8080-4c435ebf08a2.png)

**Comment by elfmz** [comment]
а нет, не работает - пробел срезается и получается просто звездочка)
но можно это пофиксить..

**Comment by elfmz** [comment]
Вобщем дофикшивать не нужно, просто пробел звездочку надо в кавычки взять.
Добавил это дополнение в дефолтовое значение настройки, но для тех у кого сохранилось уже старое значение надо руками подправить:
![image](https://user-images.githubusercontent.com/20957349/233869254-6496c9a5-6a18-43fc-a7c1-58d5fae83de5.png)

**Comment by akruphi** [comment]
@elfmz однако фича влияющая на историю в диалоге с названием "AutoComplete settings" совсем не интуитивно понятно. Может переименовать в "AutoComplete & History settings" ?
