### ISSUE TITLE
Can't switch between editor windows using Ctrl+Tab if terminal output opened in additional editor window

### ISSUE THREAD

**Issue by atolismesh** [elfmz/far2l#1635]
Can't switch between editor windows using Ctrl+Tab if terminal output opened in additional editor windows

FAR2L, version 2.5.0-8475933a-beta Linux x86_64

Если открыть несколько файлов на редактирование в far2l, то  можно переключаться между окнами редакторами по Ctrl-Tab. 
Если открыть вывод терминала far2l на редактирование через Ctrl-O F4, то пропадает возможность переключиться между окнами редакторами по Ctrl-Tab. Если в этом окне нажать F12 - список окон (Screens) отображается (без окна редактирования вывода терминала), но преключиться в другое окно не дает.

Мне кажется, что раньше такая возможнось была (руки помнят).

Просьба добавть/восстановить возможность переключения по Ctrl-Tab/Ctrl-Shift-Tab

**Comment by akruphi** [comment]
Проверил и в Windows. Корни такого поведения в том, что в far2 окно терминала по **Ctrl-O** не считается отдельным экраном, а идёт как панели (см. по **F12**), соответственно и открытое в нём по **F3** или **F4** тоже не есть отдельный экран.
В far3 же окно консоли идёт сразу в **F12** как отдельное с именем Desktop.

Я за то, чтобы изменить в far2l такое поведение a la far3.

**Comment by atolismesh** [comment]
> В far3 же окно консоли идёт сразу в **F12** как отдельное с именем Desktop.

Я бы все-таки назвал его "Terminal" - на на всех системах есть GUI с Desktop.

**Comment by elfmz** [comment]
Такой возможности не было, по той причине что редактор запущенный в таком режиме не модальный, то есть он запускается и дальше работает сам по себе. Такой режим непригоден для вызова из работающей консоли по Ctrl+Shift+F4, но в принципе его можно включить для редактора открытого по F4 не в момент исполнения команды..

**Comment by akruphi** [comment]
@elfmz спасибо за модальность редактора. Просьба и для просмотрщика по **F3** модальность навесить (я себя приучил если что не планирую изменять, то в это редактором не лезть мало ли пальцем случайно не ту клавишу задену).

**Comment by atolismesh** [comment]
@elfmz спасибо за модальность редактора. Протестировал - супер, как хотел. 
Про F3 @akruphi  - поддерживаю!

**Comment by elfmz** [comment]
можно тестить и F3..

**Comment by akruphi** [comment]
> можно тестить и F3..
Всё замечательно. @elfmz большое спасибо

**Comment by atolismesh** [comment]
Протестировано. Все отдлично! Спасибо.
Имя окна  в списке по F12 всетаки для красоты желательно поменять.
