### ISSUE TITLE
"cluster size" in quick view on folder shows random values (affecting "real files size" and "files slack") due to uninitialized variable usage

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#164]
some details and possible solutions here: https://github.com/elfmz/far2l/issues/156#issuecomment-255505217

uninitialized variable: https://github.com/elfmz/far2l/blob/master/far2l/dirinfo.cpp#L116

**Comment by elfmz** [comment]
fixed by https://github.com/elfmz/far2l/commit/d81151c24761a359247320c9118c23ee9ec74ef7
