### ISSUE TITLE
[multiarc 7z] 7z don't extract files date

### ISSUE THREAD

**Issue by akruphi** [elfmz/far2l#1644]
Only **7z archive** after extract file don't set correct date (file have extracting date).
With ZIP or RAR no such problem.
If in multiarc Command lines remove `^` before `7z` (use system 7zip  instead of build-in) all extract with date (the parameter `-mtm` also not working in build-in).
In https://github.com/elfmz/far2l/blob/master/multiarc/src/formats/7z/7zMain.c#L647 date recovery code located inside `#ifdef USE_WINDOWS_FILE`

**Comment by elfmz** [comment]
Thanks for pointing place to fix, should work now for files, but not directories as later are seems just created from files paths. Not sure if its important/fixable though.

**Comment by akruphi** [comment]
> Thanks for pointing place to fix, should work now for files, but not directories as later are seems just created from files paths. Not sure if its important/fixable though.

Thank you for quick correction (I will transfer your thanks to the tg-chat, where during the discussion was advise about code location, it was not my discovery).

In _Ubuntu_ (by _Archive Manager_) and in _Windows_ (by _far3_ or _standalone 7z 22.01 x64_)  **directory timestamps extracted correctly**. If it possible and not extremely hard please make in far2l extract directory with timestamps.
