### ISSUE TITLE
"files size" differs from "du -bs" results in quick view on folder

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#165]
not sure if it can be considered bug or feature, but this behavour causes confusion at least

![far2](https://cloud.githubusercontent.com/assets/1151423/19621027/d2f9efa4-9891-11e6-8f8a-606402a5cef6.png)

**Comment by unxed** [comment]
test folder included to reproduce this easily

[test.zip](https://github.com/elfmz/far2l/files/545899/test.zip)

![far2](https://cloud.githubusercontent.com/assets/1151423/19621046/4d0fa7ca-9892-11e6-98d6-6f9a3e5db11b.png)

**Comment by elfmz** [comment]
far doesn't care about directory (own node) size reported by stat, that explain case when size in far less than in du
case when du's size less than far's more intresting. I guess du doesn't follow symlinks. Uncheck correspoding option in system settings and see if /home/unxed size will drop to <= du' report

**Comment by unxed** [comment]
unchecked "options"-"system settings"-"scan symbolic links"

got completely wrong result. at least, my "desktop" folder takes 55Gb and it is not a symbolic link

![far2](https://cloud.githubusercontent.com/assets/1151423/19621320/e2af582a-9897-11e6-8847-149df0e46074.png)

**Comment by unxed** [comment]
> far doesn't care about directory (own node) size reported by stat, that explain case when size in far less than in du

is this behavour can be considered expected? should be documented somehow at least, I guess.

**Comment by unxed** [comment]
re-checked with d81151c24761a359247320c9118c23ee9ec74ef7
you can reproduce this with your own "build" folder

![far2](https://cloud.githubusercontent.com/assets/1151423/19621910/5d7e2060-98a5-11e6-8c8e-0a1c68994859.png)

**Comment by elfmz** [comment]
I know. its again related to symlinks

**Comment by unxed** [comment]
found the reason of home folder size difference.
it's a copy of "/bin" (full of symlinks) located inside /home/unxed/.local/share/Trash/files
(used it to test file copying progress time indicator)

so, to reprocude
1. mkdir ~/temp
2. copy /bin to /temp/bin with far
3. delete to recycle bin /temp with far
4. compare trash folder size calculated by far's quick view panel and "du -bs" results for that folder

**Comment by unxed** [comment]
far's quick view still shows ~/.wine taking 55G, but it really takes about 800M, and 55G is my desktop folder size. not sure if it matters.

**Comment by elfmz** [comment]
du -bs doesn't include size of objects pointed by symlinks, not sure whats wrog with your desktop die, for me disabled symlinks gives almost same size as du -bs

**Comment by unxed** [comment]
almost? :)

**Comment by unxed** [comment]
cleared trash folder correctly and retested
can't imagine problems that my ~ can have to be shown as 3Gb instead of 59Gb with symlinks disabled

![far2](https://cloud.githubusercontent.com/assets/1151423/19622107/f42ee102-98aa-11e6-9a01-256ad7ff500d.png)

**Comment by unxed** [comment]
reproduced.

the magic is, with "follow symlinks" option turned off, size of directories having symlinkes pointing to them is not included in calculation

to reproduce:
1. disable "follow symlinks" option
2. mkdir ~/temp
3. mkdir ~/temp/a
4. copy something to ~/temp/a
5. ln -s ~/temp/a ~/temp/b
6. press ctrl+q on ~/temp
7. you WILL NOT see the size of the files you copied on step 4

sample included 

[temp.zip](https://github.com/elfmz/far2l/files/546009/temp.zip)

**Comment by unxed** [comment]
still, even with "scan symbolic links", far's "files size" is slightly greater then du -bs
investigating

**Comment by unxed** [comment]
![far2](https://cloud.githubusercontent.com/assets/1151423/19622266/a51d9b40-98ae-11e6-8290-cb8e98a7cb6b.png)

**Comment by elfmz** [comment]
whats inside of dosdevices?

**Comment by unxed** [comment]
```
/home/unxed/.wine/dosdevices$ ls -la                                                       ↑
TIP: If you feel stuck - use Ctrl+Alt+C to terminate everything in this shell.
итого 8
drwxr-xr-x 2 unxed unxed 4096 окт 14 20:32 .
drwxr-xr-x 4 unxed unxed 4096 окт 22 23:26 ..
lrwxrwxrwx 1 unxed unxed   10 сен 30 14:22 c: -> ../drive_c
lrwxrwxrwx 1 unxed unxed    8 сен 30 14:50 d:: -> /dev/sdb
lrwxrwxrwx 1 unxed unxed    9 окт  1 08:23 e:: -> /dev/sdb1
lrwxrwxrwx 1 unxed unxed    8 окт 14 15:16 f:: -> /dev/sdc
lrwxrwxrwx 1 unxed unxed    9 окт 14 15:17 g:: -> /dev/sdc1
lrwxrwxrwx 1 unxed unxed    1 сен 30 14:22 z: -> /
/home/unxed/.wine/dosdevices$                                                              ↑


```

**Comment by elfmz** [comment]
also about scenario with lost size disabled symlinks - was it checked before or after recent commit https://github.com/elfmz/far2l/commit/76ca1d0e119bb9c2ba8036d059d994335e579402 ?

**Comment by elfmz** [comment]
and what size shows far per each that file if enter dosdevices in ctrl+3 mode?

**Comment by unxed** [comment]
before. seems that 76ca1d0 fixed it.

**Comment by unxed** [comment]
![far2](https://cloud.githubusercontent.com/assets/1151423/19622335/40dd11e0-98b0-11e6-8846-f28e40c2720e.png)

**Comment by elfmz** [comment]
..and if select them

**Comment by unxed** [comment]
![far2](https://cloud.githubusercontent.com/assets/1151423/19622351/a1aba5ea-98b0-11e6-8562-a36414f8945d.png)
![far22](https://cloud.githubusercontent.com/assets/1151423/19622350/a1aac5f8-98b0-11e6-8217-bea83c9be0ac.png)

**Comment by unxed** [comment]
![far2](https://cloud.githubusercontent.com/assets/1151423/19622360/de8d4298-98b0-11e6-9722-c35d767b2028.png)
![far22](https://cloud.githubusercontent.com/assets/1151423/19622359/de8d5206-98b0-11e6-962d-66c877123b0f.png)

**Comment by elfmz** [comment]
I meant selected with ins to see their size in status area.. Anyway, check with recent changes

**Comment by unxed** [comment]
building

**Comment by unxed** [comment]
![far2](https://cloud.githubusercontent.com/assets/1151423/19622395/9d4e73c8-98b1-11e6-8e1f-e4cf7f5c1a45.png)
![Uploading far22.png…]()

**Comment by elfmz** [comment]
..and now?

**Comment by unxed** [comment]
fixed with dosdevices, .wine and whole ~ in "no symbolic links scan" mode, YEAH :)
btw, does "scan symbolic links" option really need to be enabled by default?

**Comment by elfmz** [comment]
Don't know.. it was so in original version..
however there is small difference in profile's size between far2l and du.. Its because far creates temp file when buildir dir tree.. not sure why. and of course that file in ~/.far2l/tmp

**Comment by unxed** [comment]
59 411 034 356
for ~ in "no symbolic links scan" mode

59 411 212 209
for ~ in "scan symbolic links" mode

unxed@rs ~ $ sudo du -bs ~
59411034356	/home/unxed

- can it be considered correct? it still does not clear for me how "scan symbolic links" option works :)

**Comment by elfmz** [comment]
looks good..
Scan symbolic links mean that it will resolve symlinks found in directory and include its target into total size. This mean  that if symlinks points to file - the size of that file will be added to calculated total size. If symlink points ot directory - this directory will be added to recursive enumeration. There're also additional moments:
1) There is recursion guard, that checks if symlink target points to any scanned path or to some parent level (I added this) of scanned directory. In this case scan will not follow symlink even if symlink scan enabled.
2) There is also check for same files scan by device/inode identifiers (also my 'invention'). This excludes same files from being checked if there not recursive symlinks that points to same files. Also this prevents size of file that has more than one name (beside of symlinks there'is different beast called hardlinks!) to be added more than once.
Bugs here where caused by:
1) In windows directory size always 0 and original far don't care about that field for directories. Not sure if that is correct, since nobody ever promised on Windows that reported for directories size is zero. Futhermore I'm not sure that its true for all possible filesystems including networking/3rd party encrypted containers etc.
2) symlink object has its own size

**Comment by unxed** [comment]
Thanks for detailed explanation!
