### ISSUE TITLE
far2l window does not open when run under Windows 11 wslg in detach/background mode: "far2l &" 

### ISSUE THREAD

**Issue by atolismesh** [elfmz/far2l#1655]
1. Окно far2l GUI не открывается при запуске под Windows 11 wslg в режиме отсоединения «far2l &» 
Процесс far2l уходит в состояние stopped. 
Если после этого набрать команду fg, то окно открывается.

2. Если просто запустить far2l, то окно открывается, но командная строка bash не "освобождается".  

Другие GUI программы типа gedit запускаются нормально и командную строку bash "освобождают".

FAR2L, version 2.5.0-2661ab9f-beta Linux x86_64, собран под wslg Ubuntu 22.04.2

WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1635

**Comment by elfmz** [comment]
а если сделать nohup far2l & ?

**Comment by atolismesh** [comment]
Так запускается, окно открывается, командная строка bash "освобождается"

**Comment by atolismesh** [comment]
Но при запуске 
`nohup far2l &`
другая проблема (и под wsl и под обычным linux) - при нажатии Tab в команднойстроке  при убранных панелях far2l уходит в остояние stopped.

**Comment by elfmz** [comment]
Ща уже можно запускать и без nohup но с ключом --notty: `far2l --notty &` проблема с зависающием автодополнением тоже должна уйти

**Comment by atolismesh** [comment]
Спасибо! Проверил, проблемы решены.
