### ISSUE TITLE
Clipboard not yet working in Windows11 wslg GUI 

### ISSUE THREAD

**Issue by atolismesh** [elfmz/far2l#1658]
Clipboard пока еще не работает под wslg в Windows 11 совместно с far2l GUI и Ubuntu 22.04.2.

Выделяем, копируем текст (Ctrl+Ins) в far2l GUI и пытаемся вставить его в любое приложение в Windows или другое приложение, запущенное под wsl. Ничего не происходит - текст не вставляется, либо вставляется текст который уже был в clipboard Windows. 

Выделяем, копируем текст  в Windows и пытаемся вставить его в far2l  GUI. Текст вставляется.  

Внутри far2l GUI все копируется/вставляется, но в других окнах wsl и Windows содержимое clipboard не меняется. 
При этом в far2l GUI вставляется содержимое из Windows clipboard. 
Т.е. работает в одну сторону.

При таком запуске far2l, как описано в #1350 ,  
```
GDK_BACKEND=x11 far2l 
```
clipboard начинает работать в обе стороны, но визуально окна far2l выгладят, мягко говоря, плохо. 

FAR2L, version 2.5.0-2661ab9f-beta Linux x86_64

libwxgtk3.0-gtk3-dev/jammy,now 3.0.5.1+dfsg-4 amd64 

WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.1635

**Comment by unxed** [comment]
Стоит, наверное, скрин кинуть окна, которое "выглядит плохо"

**Comment by atolismesh** [comment]
Вид окна при запуске с GDK_BACKEND=x11:
<img width="565" alt="image" src="https://user-images.githubusercontent.com/130924690/235300208-899caddb-a912-4a71-856c-3135e1a8cb03.png">


Стандартный вид окна: 
<img width="460" alt="image" src="https://user-images.githubusercontent.com/130924690/235300128-b8080485-0f94-4e02-ae5c-28678dd9a69e.png">

**Comment by elfmz** [comment]
Если ктото расскажет как запустить wsl в десятке которая работает внутри виртуалбокса то шансы на скорый фикс всех wsl-related проблем сильно вырастут. Пока все выглядит так что это невозможно :( https://superuser.com/questions/1631558/unable-to-install-wsl-on-windows-10-running-inside-virtual-box

**Comment by unxed** [comment]
Спросил в чате, там человек 200, кто-нибудь знает, может.

**Comment by unxed** [comment]
А вот этот совет не работает? https://askubuntu.com/a/1320858/894968  Типа VMWare 16 вместо VirtualBox использовать. Там вроде простая версия на одну виртуалку — бесплатная.

**Comment by atolismesh** [comment]
По идее чек бокс в VirtualBox nested vt-x, —nested-hw-virt on должны сработать. Главное, чтобы CPU и BIOS поддерживали. Завтра проверю, где-то у меня был образ с Windows 11 + wsl2.
cat /proc/cpuinfo | grep -i vmx что выдает ?

**Comment by atolismesh** [comment]
MS has ready to use VM for VirtualBox https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/ 
It includes W11, WSL2, Ubuntu installed for WSL2

**Comment by elfmz** [comment]
чекбокс есть таск манагер говорит что виртуализация есть wsl не работает:
![image](https://user-images.githubusercontent.com/20957349/235378587-3d2e9976-6fdd-47a6-a2bd-180c44763f38.png)
проблема как я понимаю в этом https://forums.virtualbox.org/viewtopic.php?t=101609 
Спасибо, попробую скачать готовую виртуалку авось таки заработает..

**Comment by atolismesh** [comment]
Нее - "таск манагер говорит что виртуализация есть" .
Это другаф виртуализация - vt-d. А для nested virtualization должна быть еще в BIOS включена vt-x (или vmx)

**Comment by elfmz** [comment]
![image](https://user-images.githubusercontent.com/20957349/235378712-d67713a8-ace3-49cf-9ea4-3afd5e38fe40.png)

**Comment by atolismesh** [comment]
cat /proc/cpuinfo | grep -i vmx

**Comment by elfmz** [comment]
пустота

**Comment by elfmz** [comment]
в биосе SVM COU Virtualization - Enabled

**Comment by atolismesh** [comment]
У меня cat /proc/cpuinfo | grep -i vmx так: 
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl `vmx` est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap avx512ifma clflushopt intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm md_clear flush_l1d arch_capabilities
`vmx flags`	: vnmi preemption_timer posted_intr invvpid ept_x_only ept_ad ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid unrestricted_guest vapic_reg vid ple pml ept_mode_based_exec tsc_scaling

**Comment by atolismesh** [comment]
Технология vmx довольно старая - где-то должна включаться

**Comment by elfmz** [comment]
У меня 'vmx flags:' вообще нету в /proc/cpuinfo :-/
это ноут может залочили както, в биосе вроде все перерыл ничего кроме уже включенного SVM CPU Virtualization интересного там нету

**Comment by atolismesh** [comment]
осталось надеятся, что образ с MS все-таки запустится.

**Comment by elfmz** [comment]
у меня под рукой еще есть комп на i7 3770 могу там еще попробоать)

**Comment by atolismesh** [comment]
По идее там в процессоре должны быть доступны все эти VT-****

**Comment by elfmz** [comment]
ну штож, на старичке 3770 вроде все поднялось

**Comment by unxed** [comment]
О, класс! Было бы интересно глянуть, насколько комфортный UX в Windows Terminal с win32-input-mode и OSC52 в итоге получился. Вроде люди в чате норм пользуются, а я вот сам не пробовал пока.

**Comment by atolismesh** [comment]
Супер!

**Comment by unxed** [comment]
@elfmz если прямо никак не получится завести clipboard под Wayland в WSLg, можно попробовать workaround отсюда:
#1520
```
cat | /mnt/c/Windows/System32/clip.exe
/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe Get-Clipboard | sed 's/\r//'
```

**Comment by unxed** [comment]
https://github.com/elfmz/far2l/issues/1350#issuecomment-1443347317

Вот эту проблемку тоже можно этим способом решить, наверное, кстати.

**Comment by i2van** [comment]
Клипбоард перестал работать после обновления WSL (работал 2 версии до того). Не работает копирование в обе стороны вообще.

**Comment by elfmz** [comment]
Ага, то есть то что оно у меня не работает вообще с самого начала - это норма..

**Comment by unxed** [comment]
Вроде в соседнем тикете писали, что с Audacity работает, а она тоже на wx сделана

**Comment by unxed** [comment]
А этот баг с тестовой аппой проявляется только а виндовом вэйленде, или в чистой убунту на вэйленде тоже?

**Comment by elfmz** [comment]
В ванильной убунте 22 с вэйландом все работает адекватно.

**Comment by unxed** [comment]
И копипаста из/в Телеграмм даже?

**Comment by elfmz** [comment]
кхе, у меня там нет телеграмма, но копипаста из/в gedit там работает норм а под wsl - не работает

**Comment by elfmz** [comment]
а еще у меня с этим самым wsl периодически пропадает курсор мышки, но это уже такие мелочи.. и вообще возможно баг виртуалки

**Comment by unxed** [comment]
Судя по тому, что [вот тут](https://github.com/elfmz/far2l/issues/1350) пишут, надо проверить именно эти конкретные аппы: Telegram, Firefox, QtCreator, Konsole. В первой вообще должна на работать копипаста, в остальных должна портиться кодировка.

**Comment by elfmz** [comment]
Я думаю это совершенно разные проблемы.

**Comment by elfmz** [comment]
с файрфоксом все ок

**Comment by atolismesh** [comment]
> wsl периодически пропадает курсор мышки
Довольно часто пользуюсь - не пропадал. А вот под витуалкой - да, даже без wsl. Плюс там какие-то в разных виртуалках сочетания клавиш, которые отключат мышь или курсор. Возможно причина в этом.

**Comment by atolismesh** [comment]
> В ванильной убунте 22 с вэйландом все работает адекватно.

> Вроде в соседнем тикете писали, что с Audacity работает, а она тоже на wx сделана

Писал про это здесь: https://github.com/elfmz/far2l/issues/1350#issuecomment-1529933514
С Телеграмом (В ванильной убунте 22 с вэйландом) копировалось в одну сторону. Gedit, audacity(на wx) - в обе.

**Comment by elfmz** [comment]
Короче пока сделал такой воркэраунд, можно сделать `~/.config/far2l/clipboard` с chmod +x и следующим содержимым:
```
if [ "$1" = "set" ]; then
	CONTENT=$(cat)
	echo "Clipboard content to set: $CONTENT"
else
	echo 'Clipboard content to get'
fi

```
ну только вместо echo надо чтото что будет доставать/вставлять данные в клипборд

**Comment by elfmz** [comment]
запостил баг в wx: https://github.com/wxWidgets/wxWidgets/issues/23544 хотя чтото мне подсказывает тут надо фиксить wslg..

**Comment by elfmz** [comment]
Похожие проблемы
https://github.com/microsoft/wslg/issues/15
https://github.com/microsoft/wslg/issues/1044

**Comment by unxed** [comment]
> ну только вместо echo надо чтото что будет доставать/вставлять данные в клипборд

Примеры команд для работы с клипбордом — в #1520

В частности, под wslg можно попробовать вот это:
```
if [ "$1" = "set" ]; then
    cat | /mnt/c/Windows/System32/clip.exe
elif [ "$1" = "get" ]; then
    /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe Get-Clipboard | sed 's/\r//'
fi
```

**Comment by elfmz** [comment]
В принципе работает, хотя и некисло тормозит у меня в виртуалке. cat кстати не нужен, так работает тоже:
```
if [ "$1" = "set" ]; then
    /mnt/c/Windows/System32/clip.exe
elif [ "$1" = "get" ]; then
    /mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe Get-Clipboard | sed 's/\r//'
fi
```

**Comment by i2van** [comment]
С `pwsh`:

```bash
#!/bin/bash

if [ "$1" = "set" ]
then
    /mnt/c/Windows/System32/clip.exe
else
    pwsh -Command Get-Clipboard
fi
```

**Comment by i2van** [comment]
> `pwsh -Command Get-Clipboard` чета ничего не делает (и да - я его установил)

.NET установлен? Что `which pwsh` выводит (версия 6+)?

```
$ which pwsh
/usr/bin/pwsh

$ dotnet --version
7.0.203

$ pwsh --version
PowerShell 7.3.4
```

**Comment by unxed** [comment]
Это можно закрывать? Или планируются попытки придумать какой-то ещё workaround?

**Comment by Artyom17** [comment]
Cпасибо за подсказку с GDK_BACKEND=x11 far2l , я готов пожертвовать видом окна, лишь бы клипборд работал.

**Comment by unxed** [comment]
По поводу буфера обмена и Wayland. Начиная с Убунту 24.04 можно будет гонять `far2l --nodetect` под [kitty](https://github.com/kovidgoyal/kitty/) и работать с буфером обмена через [OSC52](https://github.com/elfmz/far2l/issues/1422).

Regarding the clipboard and Wayland. Starting from Ubuntu 24.04 it will be possible to run `far2l --nodetect` under [kitty](https://github.com/kovidgoyal/kitty/) and work with the clipboard via [OSC52](https://github.com/elfmz/far2l/issues/1422).

**Comment by unxed** [comment]
Workaround 1:
https://github.com/elfmz/far2l/issues/1350#issuecomment-1492587632

Workaround 2:
Use Windows Terminal or any other OSC52-supporting and TTY or TTY|X far2l backend. Don't forget to enable OSC52 in far2l in Options -> Interface settings.

Workaround 3:
ssh to WSL using https://github.com/cyd01/KiTTY and use far2l inside

Workaround 4:
https://github.com/elfmz/far2l/issues/1658#issuecomment-1546638648

**Comment by unxed** [comment]
А можете, пожалуйста, собрать у себя в WSLg wxWidgets и проверить, работает ли Copy/Paste между Telegram и вот этой тестовой приложухой:
https://docs.wxwidgets.org/3.2/page_samples.html#page_samples_clipboard
?

Спасибо!

**Comment by unxed** [comment]
А можете, пожалуйста, собрать у себя в WSLg wxWidgets и проверить, работает ли Copy/Paste между Telegram и вот этой тестовой приложухой:
https://docs.wxwidgets.org/3.2/page_samples.html#page_samples_text
?

Спасибо!

**Comment by atolismesh** [comment]
> собрать у себя в WSLg wxWidgets и проверить, работает ли Copy/Paste между Telegram и вот этой тестовой приложухой

Проверил программу "text" из wxWidgets под WSLg + Ubuntu 23.10. 
Копирование между "text" и "Telegram (linux)" не работает в обе стороны. 
Копирование между "text" и "far2l GUI"  не работает в обе стороны.
Копирование между "text" и "far2l GUI с GDK_BACKEND=x11"  не работает в обе стороны.
Копирование между "Telegram (linux)" и "far2l GUI с GDK_BACKEND=x11"  не работает в обе стороны.

**Comment by unxed** [comment]
вот эта штука по идее должна решать проблему
https://github.com/elfmz/far2l/pull/2070

**Comment by atolismesh** [comment]
Проверил под native Ubuntu 23.10 + Wayland. 
```
export WXTRACE="clipboard"
FAR2L_STD=~/far2l.log ./far2l --notty 
```
Копирование из телеграмма в fa2l gui заработало: 
```
OpenClipboard
13:43:48: Trace: (clipboard) Checking if format UTF8_STRING is available
13:43:48: Trace: (clipboard) Received available formats for clipboard CLIPBOARD
13:43:48: Trace: (clipboard)   text/plain
13:43:48: Trace: (clipboard)   text/plain;charset=utf-8
13:43:48: Trace: (clipboard) Checking if format STRING is available
13:43:48: Trace: (clipboard) Received available formats for clipboard CLIPBOARD
13:43:48: Trace: (clipboard)   text/plain
13:43:48: Trace: (clipboard)   text/plain;charset=utf-8
13:43:48: Trace: (clipboard) GetData(): format not found
13:43:48: Trace: (clipboard) Checking if format text/plain;charset=utf-8 is available
13:43:48: Trace: (clipboard) Received available formats for clipboard CLIPBOARD
13:43:48: Trace: (clipboard)   text/plain
13:43:48: Trace: (clipboard)   text/plain;charset=utf-8
13:43:48: Trace: (clipboard) Requesting format text/plain;charset=utf-8
13:43:48: Trace: (clipboard) Received selection text/plain;charset=utf-8, len=304
OnClipboardGetData(13) - found MIME-compatible text format
CloseClipboard without data

```
Копирование из  fa2l gui в телеграмм заработало: 
```SetClipboardData: format=13 len=296
13:45:05: Trace: (clipboard) Adding support for text/plain;charset=utf-8
13:45:05: Trace: (clipboard) Adding support for STRING
13:45:05: Trace: (clipboard) Adding support for UTF8_STRING
wxTheClipboard->SetData - OK
13:45:05: Trace: (clipboard) Clipboard data requested
13:45:05: Trace: (clipboard) clipboard data in format text/plain;charset=utf-8, GtkSelectionData is target=text/plain;charset=utf-8 type=ATOM selection=CLIPBOARD timestamp=0
13:45:05: Trace: (clipboard) Valid clipboard data of size 73 found


OpenClipboard
13:45:08: Trace: (clipboard) Checking if format UTF8_STRING is available
13:45:08: Trace: (clipboard) Received available formats for clipboard CLIPBOARD
13:45:08: Trace: (clipboard)   TIMESTAMP
13:45:08: Trace: (clipboard)   TARGETS
13:45:08: Trace: (clipboard)   MULTIPLE
13:45:08: Trace: (clipboard)   TIMESTAMP
13:45:08: Trace: (clipboard)   text/plain;charset=utf-8
13:45:08: Trace: (clipboard)   STRING
13:45:08: Trace: (clipboard)   UTF8_STRING
13:45:08: Trace: (clipboard) Requesting format UTF8_STRING
13:45:08: Trace: (clipboard) Clipboard data requested
13:45:08: Trace: (clipboard) clipboard data in format UTF8_STRING, GtkSelectionData is target=UTF8_STRING type=NONE selection=CLIPBOARD timestamp=0
13:45:08: Trace: (clipboard) Valid clipboard data of size 73 found
13:45:08: Trace: (clipboard) Received selection UTF8_STRING, len=73
OnClipboardGetData(13) - found wx-compatible text format
13:45:08: Trace: (clipboard) Checking if format FAR_VerticalBlock_Unicode is available
13:45:08: Trace: (clipboard) Received available formats for clipboard CLIPBOARD
13:45:08: Trace: (clipboard)   TIMESTAMP
13:45:08: Trace: (clipboard)   TARGETS
13:45:08: Trace: (clipboard)   MULTIPLE
13:45:08: Trace: (clipboard)   TIMESTAMP
13:45:08: Trace: (clipboard)   text/plain;charset=utf-8
13:45:08: Trace: (clipboard)   STRING
13:45:08: Trace: (clipboard)   UTF8_STRING
CloseClipboard without data
```

**Comment by unxed** [comment]
В wslg фикса из #2070 может быть недостаточно, там у некоторых вообще каждая аппа в своей отдельной клипбордной песочнице живёт, судя по сообщениям. В этом ещё надо разбираться.

**Comment by atolismesh** [comment]
Результаты проверки #2070 под wslg (как переписывались с @unxed в телеграм группе).
```
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3296

Ubuntu 23.10
```
Копирование из телеграма в far2l GUI работает, пока не скопируешь что-нибудь в самом far2l. После этого в far2l копируется только то, что было до этого помещено в clipboard в самом far2l 
Прикладываю полный лог тестирования.
[far2l_wayl.3.log](https://github.com/elfmz/far2l/files/14624684/far2l_wayl.3.log)

До 19:15:00 делал копирование из Telegram, gedit, терминала в far2l .
После этого скопировал в far2l текст в редакторе far2l  .  После этого в far2l копируется только то, что было до этого помещено в clipboard в самом far2l. А вот между Telegram и  терминалом и gedit все прекрасно продолжает копироваться в обе стороны.

Если в far2l что-то скопировать в clipboard, то в терминала wl-paste -l выдает "TIMESTAMP"

**Comment by unxed** [comment]
> All-in-one

@i2van а можете, пожалуйста, переписать этот скрипт так, чтоб путь к установке Windows определялся автоматически, а не использовался захардкоженный?

**Comment by i2van** [comment]
> > All-in-one
> 
> @i2van а можете, пожалуйста, переписать этот скрипт так, чтоб путь к установке Windows определялся автоматически, а не использовался захардкоженный?

Для этого надо [получить доступ к env vars Windows](https://stackoverflow.com/questions/43794915/is-there-a-way-to-get-access-to-windows-environment-variables-in-wsl), затем преобразовать их из Windows path (c:\.. )в Unix path (/..). Это того не стоит. К тому же копи-пейст сейчас прекрасно работает на master бранче, проверено в Win 10 WSL2 Ubuntu 22.04.4 LTS FAR2L, version 2.6.0-2024-03-17-8ce5b109-beta Linux x86_64

**Comment by unxed** [comment]
А, ну с x11 работает, да. С Вэйлендом вот в одну сторону только

**Comment by atolismesh** [comment]
> а можете, пожалуйста, переписать этот скрипт так, чтоб путь к установке Windows определялся автоматически, а не использовался захардкоженный?

Он вот так тоже работает из-под wsl:
```
#!/bin/bash

case "$1" in
get)
    powershell.exe -Command Get-Clipboard
;;
set)
   echo "$2" | clip.exe
;;
"")
    (far2l --clipboard=$(readlink -f $0) >/dev/null 2>&1 &)
;;
esac
```

**Comment by unxed** [comment]
Btw, as clipboard works ok under Wayland on native setups now in #2053), this seems to be wslg bug:
https://github.com/microsoft/wslg/issues/1216

**Comment by unxed** [comment]
1. В чате [жалуются](https://t.me/far2l_ru/16544), что решение на Powershell работает только на запись клипборда.
2. [Вот тут](https://github.com/elfmz/far2l/issues/1520#issuecomment-1742120226) — возможные причины и решение (включающее случай, когда powershell'а и вовсе нет). Надо только адаптировать его под нас.

[atolismesh](https://github.com/atolismesh)

**Comment by unxed** [comment]
Also possible solution:
https://github.com/microsoft/terminal/issues/280#issuecomment-1728298632

**Comment by atolismesh** [comment]
@i2van  @unxed  

Вообще-то автором был @i2van 
Посмотрел, поправил.
```
#!/bin/bash

case "$1" in
get)
    powershell.exe -Command Get-Clipboard
;;
set)
   CONTENT=$(cat) 
   echo "$CONTENT" | clip.exe
   echo "$2"
;;
"")
    (far2l --clipboard=$(readlink -f $0) >/dev/null 2>&1 &)
;;
esac

```

**Comment by unxed** [comment]
Спасибо, супер! Вот думаю, а не применять ли этот скрипт автоматически под wslg. А то там с буфером по ходу проблемы не только под вэйлендом, но и под иксами (многострочный текст не пролезает у людей).

Powershell в нынешней Винде из коробки есть? Если нет, надо ещё ветку кода на CScript добавить как запасной вариант.

**Comment by atolismesh** [comment]
Пришло на ум более универсальное решение для WSL
Запускаем cscript.exe; если его не находим, то более медленный powershell.exe.
Для этого

Создаем в $HOME/.config/far2l/  файл getclipboard.vbs с содержимым:

`WScript.StdOut.Write CreateObject("HTMLFile").ParentWindow.ClipboardData.GetData("Text")
`
И скрипт под него: 
```
#!/bin/sh

case "$1" in
get)
     if command -v cscript.exe >/dev/null 2>&1; then 
        cscript.exe //Nologo \\\\wsl.localhost\\$WSL_DISTRO_NAME\\$HOME\\.config\\far2l\\getclipboard.vbs 
     else
     	powershell.exe -Command Get-Clipboard
     fi

;;
set)
    CONTENT=$(cat)
    echo "$CONTENT" | clip.exe
    echo "$CONTENT"
;;
"")
    (far2l --clipboard=$(readlink -f $0) >/dev/null 2>&1 &)
;;
esac

```

**Comment by unxed** [comment]
А сделай PRом сюда, пожалуйста:
https://github.com/unxed/far2l/tree/minor-fix

**Comment by atolismesh** [comment]
Issue resolved by #2080

**Comment by unxed** [comment]
Перепроверьте ещё раз, пожалуйста

@i2van @Artyom17 @Zeroes1 @atolismesh

**Comment by unxed** [comment]
После недавних исправлений проблемы с буфером обмена под Wayland должны были уйти. У кого они оставались, перепроверьте, пожалуйста.

After recent fixes, problems with the clipboard under Wayland should have gone away. Whoever had them, please check now.

**Comment by unxed** [comment]
После недавних исправлений проблемы с буфером обмена под Wayland должны были уйти. У кого они оставались, перепроверьте, пожалуйста.

After recent fixes, problems with the clipboard under Wayland should have gone away. Whoever had them, please check now.

@i2van @Artyom17 @Zeroes1 @atolismesh

**Comment by unxed** [comment]
Там ещё в wsl[g] обнаружились проблемы с кодировками при работе с буфером обмена. Поправили. У кого такое было, перепроверьте, пожалуйста, на свежем мастере.

In wsl[g] were discovered problems with encodings when working with the clipboard.  They are now fixed.  If anyone has had such problems, please check again in recent master.

**Comment by harvestor** [comment]
В **$PATH** ubuntu добавляется **%PATH%** из Windows, что приводило к некритичным, но раздражающим глюкам при запуске QtCreator.
Отключил замусоривание **$PATH** в **/etc/wsl.conf**:
```
[interop]
appendWindowsPath=false
```
В результате буфер обмена в **far2l** и **far2m** перестал работать (и копирование в буфер, и вставка из буфера). А в других gui-прогах (fsearch, qtcreator) проблемы не было.
Путём научного тыка определил что не хватало в **$PATH** только **/mnt/c/Windows/system32**, а остальное не нужно.
В итоге просто добавил в **/home/user/.profile**:
```
export PATH="$PATH:/mnt/c/Windows/system32"
```
На этом проблему посчитал решённой. Буфер обмена в far2l и far2m починился.
Версии:

- far2l 2.6.5-2025-08-31-a973195-beta

- far2m 2.6.0-2025-09-09-4f72f58-beta

**Comment by unxed** [comment]
@akruphi в wiki это добавить, может? @Dazzar56 или может на уровне фара обойти как-то? Это надо кому-то, у кого винда есть

**Comment by akruphi** [comment]
> [@akruphi](https://github.com/akruphi) в wiki это добавить, может? 

Добавил в общую кучу в https://github.com/akruphi/far2l/wiki#clipboard_wsl
