### ISSUE TITLE
root-owned files deleted to trash by far can not be removed from trash using GUI tools

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#166]

**Comment by elfmz** [comment]
no repro. Ubuntu 16.04 LTS/Gnome shell:
1) Using far2l with delete to recycle bin on: deleted some files from /root directory (all were root-owned)
2) Opened Accessories Files (thats Nautilus), navigated to Trash, found deleted files there, right clicked on them chosen Delete - they disappeared.

However its possible that some other DE has bugs in that functionality. far2l just invoked gvfs-trash system utility to delete files to trash. If that files owned by root - gvfs-trash invoked via sudo. So you can try how gvfs-trash works for you without far2l and if issue there - open bug for your DE.

**Comment by unxed** [comment]
https://github.com/mate-desktop/caja/issues/668

**Comment by unxed** [comment]
> This is another longstanding issue, not sure this ever worked in GNOME 2 either.

nice :)
