### ISSUE TITLE
Command line autocomplete 

### ISSUE THREAD

**Issue by atolismesh** [elfmz/far2l#1660]
Сломался autocomplete в командной строке.

Имеем в корне файловой системы директории начинающиеся на m:  /mnt, /media
Набираем в командной строке 
`/m` 
после этого нажимаем Tab.
Должны получить в результате autocomplete /mnt, /media, 
а получаем несуществующие /mmnt, /mmedia 
<img width="193" alt="image" src="https://user-images.githubusercontent.com/130924690/235317976-f345b69e-be8f-4164-bf0f-99d26634eaff.png">

Воспроизводится под Linux  и wsl.
FAR2L, version 2.5.0-2661ab9f-beta Linux x86_64

**Comment by elfmz** [comment]
а разве конкретно такой вариант раньше работал нормально?

**Comment by atolismesh** [comment]
Вроде работал. Autocomplet-ом часто пользуюсь. 
Особенно  cd ~/....

**Comment by elfmz** [comment]
а сейчас?

**Comment by atolismesh** [comment]
Проверил, исправлено. Спасибо!
