### ISSUE TITLE
Add support for highilghting specialized UNIX file types

### ISSUE THREAD

**Issue by sirburpalot** [elfmz/far2l#1662]
The following UNIX file types are not currently supported in file highlighting groups:
- block special;
- character special;
- socket;
- pipe.

Adding support for these would bring far2l to greater feature parity with Midnight Commander.

**Comment by elfmz** [comment]
Are that should be different groups? Or one for all such 'irregular' files? one is easier :)

**Comment by sirburpalot** [comment]
Should be different groups, yes.
