### ISSUE TITLE
Symlink problems: 1) Ctrl-Shift-PgDn do not work for symlink with relative path in nested symlink directory; 2) not equal info for nested symlink

### ISSUE THREAD

**Issue by akruphi** [elfmz/far2l#1667]
1) Now after #1587 & #1611 **Ctrl-Shift-PgDn** give error for long symlink path:

![image](https://user-images.githubusercontent.com/92621645/235688296-b6e35ca9-0bde-412c-bafd-0bfdfeca5029.png)

This ^^^ screenshot for `/bin/a5toa4` which is symlink to `/usr/share/texlive/texmf-dist/scripts/pfarrei/a5toa4.tlu`.

2) Different information about nested symlinks.
For example: `/usr/bin/c99` are symlink to `/etc/alternatives/c99`, which symlink to `/usr/bin/c99-gcc`
and for `/usr/bin/c99` in bottom far2l show first target, but in **Ctrl-A** dialog show final target.
My opinion: in **Ctrl-A** also should show first target.

![image](https://user-images.githubusercontent.com/92621645/235691845-9b36abaf-573f-4604-96f5-beffa7d930c5.png)

**Comment by elfmz** [comment]
what says `readlink /bin/a5toa4` ?

**Comment by akruphi** [comment]
> what says `readlink /bin/a5toa4` ?

`../share/texlive/texmf-dist/scripts/pfarrei/a5toa4.tlu`

It's really with relative in path, I'm shocked.

And from symlink `/usr/bin/a5toa4` **Ctrl-Shift-PgDn** correctly jump to target, but from `/bin` (which is symlink to `/usr/bin/`) the symlink `/bin/a5toa4` by **Ctrl-Shift-PgDn** give Error, but in far2l **F3** or `cat a5toa4` processed this file correctly. Strange situation.

**Comment by elfmz** [comment]
I'm confused, if /bin/a5toa4 points to ../share/texlive/texmf-dist/scripts/pfarrei/a5toa4.tlu then how it can lead to /usr/share/texlive/texmf-dist/scripts/pfarrei/a5toa4.tlu?

**Comment by akruphi** [comment]
> I'm confused, if /bin/a5toa4 points to ../share/texlive/texmf-dist/scripts/pfarrei/a5toa4.tlu then how it can lead to /usr/share/texlive/texmf-dist/scripts/pfarrei/a5toa4.tlu?

Now it simultaneously simple and strange (amazing Linux):
1. Source file: `/usr/share/texlive/texmf-dist/scripts/pfarrei/a5toa4.tlu`
2. Directory `/usr/bin` with the simlink `/usr/bin/a5toa4` which target to `../share/texlive/texmf-dist/scripts/pfarrei/a5toa4.tlu` (with **relative in path!**).
and from `/usr/bin/a5toa4` **Ctrl-Shift-PgDn** work correctly to source.
3. Also in my Ubuntu 22.04.2 I have directory `/bin` which is symlink to `/usr/bin` but inside `/bin/a5toa4` stay **relative path** and far2l's **Ctrl-Shift-PgDn** on `/bin/a5toa4` give error. 
    But for `/bin/a5toa4` both far2l **F3** and `cat` give correct source file.

I think it is not a common situation and not need use much efforts to fix it up to perfect.

---

About information about nested symlinks: thank you for correction dialog field, but may be usefull in **Ctrl-A** have 2 fields (if it not hard):
* Symlink to:
* Final Real file:

**Comment by elfmz** [comment]
Didn't want to overload dialog with extra control, so did some alternative solution - check it please

**Comment by akruphi** [comment]
> Didn't want to overload dialog with extra control, so did some alternative solution - check it please

Thank you. Your solution 
![изображение](https://user-images.githubusercontent.com/92621645/236145449-e4d771c6-e146-4f34-a79c-b4a7053f45e5.png)
are **elegant**!

Now during recursive clicking by Space or Enter or mouse **not clearly** what **variant selected**.
Simple improvement:  in `[ Symlink: ]` during clicking also change description a la
```
[Smlnk trgt]:
[Smlnk finl]: or [Smlnk real]:
[Smlnk type]:
``` 
Here for width economy may be use `Smlnk` instead full word `Symlink`.

Better improvement: (if it not hard to realize here) not only change label but make popup menu, in which will select and **explanation** (all **Space**, **Enter**, **Ctrl-Up/Down** not change but open popup):
```
Smlnk trgt↓:
 ┌───────────────────────────────────────────────┐
 │ Smlnk trgt - path to symlink 1st target       │
 │ Smlnk finl - path to Final Real file          │
 │ Smlnk type - Final Real file type description │
 └───────────────────────────────────────────────┘
``` 
----

Also global improvement idea: now in far2l dialogs all popup menu open by only **mouse** or **Ctrl-Up/Down**, but often it is not intuitive and some terminals may trap Ctrl+arrows or may have mouse problems. May be add **Space** (if popup field not editable) or/and **Enter** to expand such popup in all far2l?

**Comment by elfmz** [comment]
IMHO no need for abbreviation, Symlink: -> Real: -> Info: should be enough verbose
Regarding hotkeys better to use macroses, unless there is strict need

**Comment by akruphi** [comment]
> IMHO no need for abbreviation, Symlink: -> Real: -> Info: should be enough verbose Regarding hotkeys better to use macroses, unless there is strict need

I agree with both. Only the simplest clear indication information type in symlink field in Ctrl-A dialog.

**Comment by akruphi** [comment]
Thank you. Now perfect balance between understanding and compactness.
