### ISSUE TITLE
Manjaro KDE-Wayland: не работает Alt-Tab из приложения

### ISSUE THREAD

**Issue by Release** [elfmz/far2l#1684]
Операционная система: Manjaro Linux 
Версия KDE Plasma: 5.27.4
Версия KDE Frameworks: 5.105.0
Версия Qt: 5.15.9
Версия ядра: 6.3.0-1-MANJARO (64-бита)
Графическая платформа: Wayland

Невозможно переключиться на другое приложение с помощью клавиатуры при активном окне Far2l.
Обратно на Far2l переключение работает.

**Comment by akruphi** [comment]
В Wayland у Вас перехватывается только **Alt-Tab**? **Win-Tab** работает?

Решается ли проблема запуском far2l через **xWayland** (подробности в [рус-вики](https://github.com/akruphi/far2l/wiki#wayland)).

Также, если не сложно, проверьте на Вашей системе при запуске в чистом Wayland имеется ли проблема с частичной кривой работой буфера обмена между far2l и telegram-desktop как в https://github.com/elfmz/far2l/issues/1350#issuecomment-1529933514

**Comment by elfmz** [comment]
Такое может быть если отмечен левый Альт в Options/Input settings:
![image](https://github.com/elfmz/far2l/assets/20957349/dba226f5-93bb-4eed-9927-d6f7b71886f5)

**Comment by Release** [comment]
> Такое может быть если отмечен левый Альт в Options/Input settings:

Спасибо. Действительно, проверил в настройках, была задана эксклюзивная обработка для правого Alt. Но удивительно, что в x11 это не мешает переключению на другие приложения. Я по этому и открыл тему.

> Решается ли проблема запуском far2l через **xWayland**?

Думаю, уже нет смысла проверять, раз проблема решилась через настройки.

Что касается telegram-desktop, то у меня нет его. Если появится время (и желание), установлю и проверю как работает обмен между ними.
