### ISSUE TITLE
Ctrl+Left/Right doesn't work in command line

### ISSUE THREAD

**Issue by danilagalimov** [elfmz/far2l#1685]
Type something in command line and Press Ctrl+O to hide the pannels.
Try to use Ctrl + Left or Ctrl+Right to navigate between words.
It works in Windows version.

**Comment by akruphi** [comment]
In my Ubuntu 22.04.2 in far2l-gui and in terminal `far2l --tty` keys **Ctr+Left** and **Ctrl+Right** work properly for jumping between words in command line for both situation visible or hidden panels (`FAR2L version 2.5.0-12b9e9e`).

**Comment by danilagalimov** [comment]
Yes, it looks like it is some issue with Karabiner-elements, without it it also works
