### ISSUE TITLE
define beta development stage criteria

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#169]
for not being eternal alpha

should those criteries cover usability only or aslo source code quality (eliminating winport shim [if even needed], code refactoring, etc)?

as for me, I am already using far2l in production environment and see no _critical_ issues except for already fixed ones

**Comment by invy** [comment]
Go through all open issues, identify show-stoppers and put them to the milestone called 'beta'.

**Comment by elfmz** [comment]
actually there're couple big things that need to be done and that may produce degradations: first is https://github.com/elfmz/far2l/issues/88 second is not listed. So better don't hurry, especially there is no need to hurry.

**Comment by unxed** [comment]
just want to be able to do `apt install far2l` ;)

**Comment by unxed** [comment]
is #88 actual show stopper for the beta stage?
application seems to be fullly usable even without this feature.

**Comment by invy** [comment]
'beta' name is completely irrelevant for being able to put far2l into repos. The only thing you need, is that far correctly behaves when installs/uninstalls, all it's dependencies are satisfied by the packages comming into repos and somebody needs to maintain package. Having package, which install it into 'opt' is not enough for repository, that's why I've actually created the: #84

**Comment by unxed** [comment]
answered in #84

**Comment by unxed** [comment]
About #88:
> but since me rather lazy and pragmatic
Lazy and pragmatic guy will never start implementing feature which he personnaly do not plan to use ;)
Should it be defined as show stopper then?

**Comment by elfmz** [comment]
https://github.com/elfmz/far2l/issues/183 remembered me that informative error messages are missing and thats really important problem

**Comment by unxed** [comment]
Still, in my oppinion, any kind of unimplemented features should not be considered beta/release blockers.

Had some thoughts about semantic beta/release criteries. My proposal:

Beta: no open issues related to crashes/segfaults/data loss (even potential).
Current blockers: #119 #125

Release: no open issue releated to undefined/confusing/unexpected/undocumented behavour
Current blockers: #183 #180 #173 #172 #171 #170 #147 #118 #115

That do you think about this approach?

**Comment by elfmz** [comment]
IMHO two numbers + date-hash is enough. See at initial far - it has useless 0 between constant and counter.  
Actually version itself rather useless thing unless required to track compatibility between components. And for this two numbers again is enough.

**Comment by unxed** [comment]
Actual critereas of the beta stage are still not trivial :)

**Comment by elfmz** [comment]
Ну по мне так вобщем то все с виду ок, за исключением хелпа - он местами не адекватен текущему функционалу, а еще иногда просто глючит.. Но поскольку мне хелп как старому юзеру фара не нужен, то отсутствует мотивация его допиливать(

**Comment by unxed** [comment]
С хелпом аналогично :) Сейчас будет смешное предложение запилить телеметрию и посмотреть, сколько людей его хотя бы раз использовал </irony>. А вот если эту мысль направить в более трезвое русло, помогла бы кнопка "report incorrect help" где-нибудь внутри интерфейса хелпа, а то весь шерстить долго, а поправить несколько локальных косяков - быстро :)

В любом случае, как по мне, кривой хелп простителен для беты.

А вот как быть с разными штуками, которые в этом тикете мелькают (от наличия винпорта как такового до жирного и курсива в терминале)? Оказалось не таким уж критичным?

По ходу, таки нужны именно формальные критерии "критичного". Например, `никаких "вылетает", "зависает" и "портит данные пользователя" для беты`.

**Comment by elfmz** [comment]
> запилить телеметрию

свят-свят

**Comment by elfmz** [comment]
ну, как в целом же можно делать бету. или еще рано и гдето есть еще ужас-ужас?

**Comment by unxed** [comment]
Ну я-то давно в продакшне использую :) Данные не терял ни разу.

**Comment by ziceptor** [comment]
Бета - не релиз, пространство для манёвров останется. Можно переводить.

**Comment by elfmz** [comment]
ну гденить в начале января можно бету сделать если ужас-ужас не найдется...

**Comment by unxed** [comment]
ну, если отсутствие поддержки «широких символов» в tty (#1179) у нас не блокер, то, по идее, можно, да?

**Comment by elfmz** [comment]
ага

**Comment by unxed** [comment]
https://github.com/elfmz/far2l/commit/3159e2101b077dbb6418d649cf21b42a3c79bbc5

**Comment by unxed** [comment]
А то, что бэкенд в заголовке окна показывается только для случая TTY|F под WX, а в GNOME Terminal, скажем, не показывается — это баг или фича?

**Comment by unxed** [comment]
https://www.opennet.ru/opennews/art.shtml?num=56492

**Comment by unxed** [comment]
One more announce

https://habr.com/ru/news/t/645475/
