### ISSUE TITLE
Paste from the Klipper does not work in built-in editor

### ISSUE THREAD

**Issue by Mayar** [elfmz/far2l#1692]
Klipper -- KDE clipboard manager.
When I switch to another coped item in Klipper the paste does not work. Without switching, everything is fine.

**Comment by unxed** [comment]
Do this bug reproduce with other wxWidgets-based apps, like Audacity (you can use it's Edit->Metadata window for pasting experiments, for example)?

**Comment by unxed** [comment]
Do this bug reproduce with other wxWidgets-based apps, like Audacity (you can use it's Edit->Metadata window for pasting experiments, for example)? If so, it's probably a wxWidgets bug and should be filed to https://github.com/wxWidgets/wxWidgets

**Comment by Mayar** [comment]
Now I have changed the distribution from Debian to Kubuntu. Everything is fine on Kubuntu.

Поменял дистрибутив с Debian на Kubuntu. На Kubuntu все в порядке.
