### ISSUE TITLE
far2l fails to open file from archive with xdg-open

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#170]
to reproduce

1. create some text file
2. open it from far2l (by pressing enter) to confirm xdg-open opens it correctly
3. add it to .zip archive
4. navigate into this zip archive with far2l
5. try to open archived text file (by pressing enter).

console output:
`$ unzip -j -o  /home/unxed/Загрузки/1.zip "1.txt"  `
`Archive:  /home/unxed/Загрузки/1.zip               `
` extracting: 1.txt                                 `
`$ xdg-open /home/unxed/.far2l/tmp/FTM3683.tmp/1.txt`

...and nothing happens

**Comment by cycleg** [comment]
In d2df042cc17ce6e6daadb55012f870a4dc8d52fb xdg-open doesn't run at all.

**Comment by elfmz** [comment]
its run, just its start removed from output
root of problem is due to its unknown when to delete temporary extracted from archive file. xdg-open exits immediately. May be someone knows way how to wait until file will be closed?

**Comment by unxed** [comment]
> May be someone knows way how to wait until file will be closed by any other app that works with it?

What about situation then file is updated by user and saved in the same place? Maybe file checksum can be compared to archived one to save changed files to some "backup" folder in the user's profile for changes not to be lost?

**Comment by elfmz** [comment]
Its still unknown when outer application closed file or not.
Saving of file just due to it was changed without ensuring that its editing actually finished is very risky - file can be in inconsistent state so saved copy will be damaged.
