### ISSUE TITLE
false parameter inherit?

### ISSUE THREAD

**Issue by Zeroes1** [elfmz/far2l#1703]
Ложное наследование параметров?

1)  запускаю ./far2l -u Zeroes
запустился 
теперь опять запускаю не выходя из экземпляра FAR
./far2l

он запускается и он наследует ВСЁ от предыдущего
цвета настройки e.t.c

2) запустил ./far2l
без юзера

в нём запустил ./far2l - u Zeroes
и настройки взялись все от юзера, а не дефолтное. те тут не унаследовалось от предыдущего.

получается 1ый случай с ошибкой реализации?

**Comment by akruphi** [comment]
При запуске с `-u` создаётся переменная окружения `FARSETTINGS`, которая потом наследуется.
Возможным решением проблемы @Zeroes1 является создавать `FARSETTINGS` даже без явного `-u` и прописывать в него дефолтный путь `~/.config/far2l` ?

**Comment by elfmz** [comment]
Ну да, но я бы не сказал что это ошибка, поведение вроде логичное, хотя и не специально запланированное.

**Comment by elfmz** [comment]
кроме того возможны ситуации когда такого поведение прям желательное - к примеру запуск редактора через far2l -e - если парентовый far2l работает под спецюзером то логично чтоб 'редакторный' тоже под ним запускался

**Comment by Zeroes1** [comment]
закрываем? те это фича

кому надо делаем shell скрипт
так
FARSETTINGS=
./far2m

или так
