### ISSUE TITLE
[NetRocks] disable file modification time update per host

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1708]
Some servers do not allow user to change file times even if writing to such file is allowed:
![изображение](https://github.com/elfmz/far2l/assets/1151423/02947b45-e5d2-4434-abe5-6adf75af95f8)

It would be great to have an option to disable updating file times completely for such hosts in NetRocks host settings.

**Comment by unxed** [comment]
Switching to SCP solves the problem, but on any remote file save in editor I need another unneeded confirmation request:

![изображение](https://github.com/elfmz/far2l/assets/1151423/8ff4877e-4472-417e-929a-fb49af40438c)

**Comment by elfmz** [comment]
added option to silently ignore errors from such operation, please check if it works for you

**Comment by unxed** [comment]
"Set file times error" window now gone, thanks! But if I save a remote file in editor two or more times, unneeded confirmation dialog still appears:
![изображение](https://github.com/elfmz/far2l/assets/1151423/d56e31bb-358b-47d6-9ea4-c4cb8f3a619a)

**Comment by unxed** [comment]
Okay, let "unneeded confirmation dialog" be a separate issue:
https://github.com/elfmz/far2l/issues/1730
