### ISSUE TITLE
far2ledit symlink is broken

### ISSUE THREAD

**Issue by spvkgn** [elfmz/far2l#1710]
После https://github.com/elfmz/far2l/commit/39f5982e0193e6193ab0ed72c626f3fc7a9d39e7
```
$ ll -1 /usr/bin/far2l*
/usr/bin/far2l*
/usr/bin/far2ledit -> /bin/far2l
```
Было:
```
$ ll -1 /usr/bin/far2l*
/usr/bin/far2l*
/usr/bin/far2ledit -> far2l*
```

**Comment by unxed** [comment]
А у меня со старой версией вообще не собиралось на одной из систем, CMake ругался что симлинк ссылается на папку. Видимо, влияет то, в какой папке лежат исходники, а в какой идёт сборка, и кто из них как в кого вложен.

**Comment by spvkgn** [comment]
@unxed СMake 3.22 собирает без проблем

**Comment by unxed** [comment]
Ну простите, а на убунту 18.04 не собирает, не помню, какой кмейк там. И это поддерживаемый дистр, ломать сборку под ним нельзя. Значит, надо ещё какое-то искать решение

**Comment by spvkgn** [comment]
> надо ещё какое-то искать решение

Как вариант, добавить опцию чтобы при `far2l -e` открывался новый файл. Тогда и симлинк не нужен будет.

**Comment by unxed** [comment]
А как так вообще получается, что абсолютно идентичный создаёт far2l_sudoapp, а far2ledit не создаёт?

**Comment by unxed** [comment]
А как так вообще получается, что абсолютно идентичный код создаёт far2l_sudoapp, а far2ledit не создаёт?

**Comment by akruphi** [comment]
> Как вариант, добавить опцию чтобы при `far2l -e` открывался новый файл. Тогда возможно симлинк не нужен будет.

Унифицировать поведения c `far2l -e` неплохо, но как несколько месяцев назад в тг-канале разъяснял @ivanshatsky :
```
Для большинства программ достаточно указать EDITOR="far2l -e"
Но бывают исключения
mc например не использует при вызове редактора ключ -e и в итоге просто запускает фар
Других таких исключений не знаю, но допускаю, что они могут быть
Поэтому на far2l можно сделать симлинк с именем far2ledit,
и прописывать в переменной его, так он будет работать
редактором без дополнительных ключей
```
Поэтому лучше не закапывать идею #1223 про **far2ledit** (к тому же в этом случае сразу у пользователей аналогии с **mcedit**), а всё-таки понять как готовить **CMakeLists.txt**.

---

> на убунту 18.04 не собирает, не помню, какой кмейк там

Там похоже cmake  `3.10.2-1ubuntu2.18.04.2`

> СMake 3.22 собирает без проблем

Интересно что поменялось между 3.10 и 3.22 ?

---

> А как так вообще получается, что абсолютно идентичный код создаёт far2l_sudoapp, а far2ledit не создаёт?

@unxed код не идентичный - в строках 557 и 558 разный DESTINATION:
```
install(FILES "${PROJECT_BINARY_DIR}/far2l_sudoapp" DESTINATION "lib/far2l" COMPONENT system)
install(FILES "${PROJECT_BINARY_DIR}/far2ledit" DESTINATION "bin" COMPONENT base)
```

возможно в этом причина, что получающийся relative path в symlink некорректен.

**Comment by spvkgn** [comment]
> Интересно что поменялось между 3.10 и 3.22 ?

https://gitlab.kitware.com/cmake/cmake/-/issues/22159

**Comment by spvkgn** [comment]
> Интересно что поменялось между 3.10 и 3.22 ?

https://gitlab.kitware.com/cmake/cmake/-/issues/22159

Как workaround, можно создать симлинки не в корне build-директории, а в поддиректории.
