### ISSUE TITLE
Regression in command line autocomplete function

### ISSUE THREAD

**Issue by ivanshatsky** [elfmz/far2l#1720]
This menu is appeared after pressing `Tab` key twice (look at the first items):
![image](https://github.com/elfmz/far2l/assets/17809980/991bee0b-e56d-4962-86ff-1bce0d496b7c)
Not sure what exact build shows this regression, but it is quite a new one.

**Comment by ivanshatsky** [comment]
Some more additional information.
`true <somestring>` command begin to appear in the `bash` history, which was not subject to happen before the latest updates (git commit hash below isn't reflect an actual far2l build):

```
...
  849  [ 2023-06-21 ~ 16:40:47 ] cd ../far2l.build.20230620.f927558/
  850  [ 2023-06-21 ~ 16:40:52 ] make
  853  [ 2023-06-21 ~ 16:49:26 ] ~/far2l.build.20230620.f927558/install/far2l
  854  [ 2023-06-21 ~ 22:07:18 ] true jkJHYvgT
  855  [ 2023-06-22 ~ 09:05:01 ] ~/far2l.build.20230620.f927558/install/far2l
  856  [ 2023-06-22 ~ 11:57:05 ] true jkJHYvgT
  857  [ 2023-06-22 ~ 11:57:23 ] far
  858  [ 2023-06-22 ~ 11:57:52 ] true jkJHYvgT
  859  [ 2023-06-22 ~ 11:57:44 ] ~/far2l.build.20230620.f927558/install/far2l
  860  [ 2023-06-22 ~ 12:47:53 ] history
```

Here are latest `vtc_inputrc` and `vtc.log`:
[vtc.zip](https://github.com/elfmz/far2l/files/11834098/vtc.zip)

**Comment by akruphi** [comment]
Dup https://github.com/elfmz/far2l/issues/1606#issuecomment-1566170188

**Comment by elfmz** [comment]
exactly this issue was not reproduced for me, but check how it looks now..

**Comment by elfmz** [comment]
may close?

**Comment by ivanshatsky** [comment]
Sorry for the late response. Yes, everything seems ok now. Closing.
