### ISSUE TITLE
Please extend archive support

### ISSUE THREAD

**Issue by danilagalimov** [elfmz/far2l#1722]
Currently if you press F4 on the file in the archive, it is opened for editing, but any changes are discarded.

Also it is not possible to delete file from the archive or copy file into archive.

Please add this

**Comment by akruphi** [comment]
I my system Ubuntu 22.04 far2l 2.5.1-f927558e all actions F4, F5, F8 work with files in archives as expected. I tested with zip & 7z. May be @danilagalimov have problem with multiarc or launching archives from command line.

**Comment by danilagalimov** [comment]
this is really strange, now it works for me, let me do some more checks

**Comment by elfmz** [comment]
may be some specific archive format or archive's file was unwriteable?

**Comment by danilagalimov** [comment]
I was trying to edit firefox extensions, xpi files, which are actually zip files renamed. It was possible to extract files, but not edit: editing file just saved the file, pressing F8 didn't do anything, pressing F5 from different panel didn't do anything.
Now everything works perfectly.

Can it be due to simultaneous far execution? Usually I run 2 or more copies of Far for the same user. Is it possible that some far's temporary files/lock clashes in this scenario?

**Comment by elfmz** [comment]
No it should work, unless you will modify same file within two copies of far2l, then, of course, last save will win.

**Comment by danilagalimov** [comment]
Was not able to reproduce, closing
