### ISSUE TITLE
[FR] "Same folder" feature

### ISSUE THREAD

**Issue by Allineer** [elfmz/far2l#1724]
Requesting the "Same Folder" feature from the classic Far.

Or it's exists and I missing it?

<img width="571" alt="image" src="https://github.com/elfmz/far2l/assets/1168049/b2cba7c5-a5e3-45e7-8406-1c03bf22d69c">

Thanks!

**Comment by elfmz** [comment]
![image](https://github.com/elfmz/far2l/assets/20957349/a06e09f8-cea9-45f1-b5ec-7ced0346625c)

**Comment by Allineer** [comment]
Sorry and Thanks!

ЗЫ: Я тупой :'(
