### ISSUE TITLE
some .tar.gz archives can not be opened correctly by multiarc

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#173]
just try https://servo-builds.s3.amazonaws.com/nightly/linux/servo-latest.tar.gz

**Comment by unxed** [comment]
another problem with .tgz: openes, but contents can not be copied
sample: https://scan.coverity.com/download/cxx/linux64
![2016-10-27 05-48-34](https://cloud.githubusercontent.com/assets/1151423/19752890/3a053f8a-9c09-11e6-8610-db889d034fca.png)

**Comment by elfmz** [comment]
tried servo-latest.tar.gz - its opened normally - both extract of file inside and F3 of it

https://scan.coverity.com/download/cxx/linux64 - doesn't download (may be I looked at it too late and its already expired?)

**Comment by unxed** [comment]
![_002](https://cloud.githubusercontent.com/assets/1151423/20095791/ffd616be-a5b7-11e6-904e-2ca53ea57d89.png)
![_003](https://cloud.githubusercontent.com/assets/1151423/20095792/ffd6424c-a5b7-11e6-8347-e4e6949273a6.png)

**Comment by lieff** [comment]
Похоже у него установлен бит FNAME и сохранено оригинальное имя
http://www.zlib.org/rfc-gzip.html#file-format
Фар его и показывает, так что вроде как поведение верное.
Вот то что он дальше не может войти без разрешения .tar уже не очень хорошо, хотя я не знаю насколько надежно tar можно определить без расширения.

**Comment by unxed** [comment]
хм, т.е. это engrampa/7zip у меня капризничает, показывая servo вместо wb?

**Comment by lieff** [comment]
Они сразу открыли еще и tar, на tar.gz и tgz многие так делают. У фара же изначальное поведение войти сначала в gz (при этом в отсутствии бита от имени отрезается .gz или tgz заменяется на tar). В общем как я виже идеальное решение это пара настроек "автоматически открывать tar", "показывать реальное имя файла в gzip" и починить вход в tar, если в реальном имени нет расширения .tar. Минимальное решение только починить вход в tar.
