### ISSUE TITLE
error building far2l versions 2.5.0 and 2.5.1 on centos 7.9.2009

### ISSUE THREAD

**Issue by zhurkin** [elfmz/far2l#1737]
Hi ! Error building far2l versions 2.5.0 and 2.5.1 on centos 7. Version 2.4.1 builds without any problems. 

gmake[2]: *** [multiarc/CMakeFiles/multiarc.dir/src/formats/7z/C/AesOpt.c.o] Error 1
gmake[1]: *** [multiarc/CMakeFiles/multiarc.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 87%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/UI/Activities/ConfirmOverwrite.cpp.o
[ 87%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/UI/Activities/ConfirmChangeMode.cpp.o
[ 88%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/UI/Activities/SimpleOperationProgress.cpp.o
[ 88%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/UI/Activities/ComplexOperationProgress.cpp.o
[ 88%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/UI/Activities/AbortOperationRequest.cpp.o
[ 88%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/UI/Activities/InteractiveLogin.cpp.o
[ 88%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/UI/Activities/ConfirmNewServerIdentity.cpp.o
[ 88%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/UI/Activities/WhatOnError.cpp.o
[ 88%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/UI/Activities/BackgroundTasksUI.cpp.o
[ 89%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/Op/Utils/ProgressStateUpdate.cpp.o
[ 89%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/Op/Utils/Enumer.cpp.o
[ 89%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/Op/Utils/IOBuffer.cpp.o
[ 89%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/Op/OpBase.cpp.o
[ 89%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/Op/OpConnect.cpp.o
[ 89%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/Op/OpCheckDirectory.cpp.o
[ 89%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/Op/OpChangeMode.cpp.o
[ 90%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/Op/OpEnumDirectory.cpp.o
[ 90%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/Op/OpXfer.cpp.o
[ 90%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/Op/OpRemove.cpp.o
[ 90%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/Op/OpMakeDirectory.cpp.o
[ 90%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/Op/OpExecute.cpp.o
[ 90%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/Protocol/SplitLocationSpecification.cpp.o
[ 90%] Building CXX object NetRocks/CMakeFiles/NetRocks.dir/src/Protocol/Protocol.cpp.o
[ 91%] Linking CXX shared module ../install/Plugins/NetRocks/plug/NetRocks.far-plug-wide
[ 91%] Built target NetRocks
gmake: *** [all] Error 2

Name        : neon-devel
Arch        : x86_64
Version     : 0.30.0
Release     : 4.el7
Size        : 183 k
Repo        : installed
From repo   : base
Summary     : Development libraries and C header files for the neon library
URL         : http://www.webdav.org/neon/
License     : LGPLv2+ and GPLv2+
Description : The development library for the C language HTTP and WebDAV client library.

**Comment by akruphi** [comment]
In https://github.com/elfmz/far2l/issues/647#issuecomment-1310838699 was steps for CentOS 7. If it not working in your case, may be @ivanshatsky can give detail explain.

**Comment by zhurkin** [comment]
> In [#647 (comment)](https://github.com/elfmz/far2l/issues/647#issuecomment-1310838699) was steps for CentOS 7. If it not working in your case, may be @ivanshatsky can give detail explain.

As I wrote, it works on 2.4.1 , but from version 2.5.0 there is an error.  I can assume that you need a newer development package neon-devel

**Comment by elfmz** [comment]
can you show more build log? it seems actual issue details somewhere above your output

**Comment by akruphi** [comment]
Solution for old GCC <4.9 from #1762 was merged.

**Comment by unxed** [comment]
Can be closed now?

**Comment by elfmz** [comment]
Closing as likely fixed, reopen if its not.. And attach full build log then please.
