### ISSUE TITLE
far2l gets confused with username when creating archive

### ISSUE THREAD

**Issue by atolismesh** [elfmz/far2l#1745]
При попытке заархивировать (ShftF1) любой файл, находящийся в каталоге принадлежащем root (например /usr/lib/firmware), но доступного другим на чтение, происходит запрос пароля (Enter sudo password). Если отказаться от ввода пароля, то архив не создается и в терминал выводится сообщение об "Exception: error -30" и далее нечитаемые символы. Если ввести пароль, а в качестве места расположения архива указать любой каталог относительно $HOME (~/), то far2l пытается создать архив в $HOME каталоге пользователя root, а не текущего, что является неожиданным. 

far2l актуальный:  2.5.1-13c09193-beta Linux x86_64 (Ubuntu 23.04 GNOME)

Просьба исправить. В первую очередь, чтобы не запрашивался пароль (Enter sudo password).

**Comment by akruphi** [comment]
Здесь похоже сразу для записи используются права каталога из которого берутся файлы. По уму, если для архива указан путь в другой каталог, хорошо бы сначала проверять права и просить sudo только если действительно прав не хватает.

**Comment by elfmz** [comment]
Вообщето sudo в данном конкретном случае нужен хотябы для того чтоб читать файлы которые архивируются. Поэтому команда архиватора запускается через sudo с текущей директорией принадлежащей root. Без sudo она просто не запустится там.
Как интерпретировать ~ вопрос конечно хороший, вроде бы в логично что в home обычного юзера. С другой стороны возможно ктото считает иначе, и тогда архивация туда по умолчанию будет секурити проблемой... Вобщем, если это не прям ужас-ужас какое неудобство, я бы предпочел оставить как есть.

**Comment by akruphi** [comment]
> Вообщето sudo в данном конкретном случае нужен хотябы для того чтоб читать файлы которые архивируются. 

У меня в Ubuntu 22.04.2 файлы из приведённого @atolismesh в качестве примера каталога `/usr/lib/firmware` имеют o=r, т.е. позволяют себя читать всем без sudo, а вот права записи в каталог ни у кого кроме root нет. Соответственно sudo лишь на уровне записи и если сам файл архива имеет путь в другой каталог с правом записи, то и sudo не нужен.
