### ISSUE TITLE
issues with registry storage after 874a206

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#175]
~/.far2l/HKU/c/k-Software/k-Far2/k-Colors/k-Highlight/k-Group0/v-DateAfter

```
DateAfter
3:\0\0\0\0\0\0\0\0
```

not sure if it can be considered human-readable (if not a bug)
what does format "3" actually means?
others, like DWORD or SZ (Zero-terminated String, yep?) seems to be much more self-documenting.

~/.far2l/HKU/c/k-Software/k-Far2/k-SavedFolderHistory/v-Times

even contains binary data after "3:". is it ok?

samples included
[reg_samples.zip](https://github.com/elfmz/far2l/files/549289/reg_samples.zip)

**Comment by elfmz** [comment]
3 is REG_BINARY
ok, will add definition for that, but it will not be reable. Its binary

**Comment by unxed** [comment]
maybe it's better to store binaries as hex values to maintain consistency between v-* files (if it will not cause performance loss)

**Comment by elfmz** [comment]
what you mean under consistency?

**Comment by unxed** [comment]
all others v-* are text files

**Comment by elfmz** [comment]
thats also text file. \0 - is just an escaped 'special' character. There're several such chars that escaped: \r \n \0 and \\. Same escaping applied to string values, is caller will decide to include such character into storted string.
And vice-verse: if this hex value would contain some character not from escaped list - it would look just as some string.

**Comment by elfmz** [comment]
However, in Windows registry type of value has no meaning for kernel. For registry itself type is just another 4 bytes stored in value. All the rules, like REG_SZ must be null-terminated string - just a 'recommendation'. Thats why SZ values in my implementation commonly finalized by \0.

**Comment by elfmz** [comment]
anyway.. using hex values for REG_BINARY not bad idea.. just not sure if it will help much, bytes are not human readable, even if written as numbers..

**Comment by unxed** [comment]
MULTI_SZ also not very human readable without special tools or preprocessing ;)
