### ISSUE TITLE
[MacOS] far2l died while watching a directory with a constantly updated file

### ISSUE THREAD

**Issue by HughHoyland** [elfmz/far2l#1751]
far2l had a directory open on one panel, in which one file was written into, at approximately 2Mb/s speed.

After 10 minutes, far2l became unresponsive. I take it as it wasn't able to handle all the "file changed" notifications it received.

**Comment by elfmz** [comment]
Does it happen always or was just a single case? If it reproducible, can you do:
open terminal and type there `export FAR2L_STD=/some/path/to/far2l.log`
run far2l from that terminal and reproduce issue
collect that far2l,log and show it. Actualy only last few tens of lines will be interesting, but save it all just in case.

**Comment by HughHoyland** [comment]
I've been running a test for half an hour now, but It didn't reproduce 8(((
I'll come back if it does, will make sure to attach a debugger next time.
