### ISSUE TITLE
far2l on macos asks twice for every folder on external drive

### ISSUE THREAD

**Issue by abcdenis** [elfmz/far2l#1754]
Everything was fine on 2.5.0 .
After update to 2.5.1 FAR asks twice per every folder I visit on external drive ("far2l want to access external drive").
Rolled back to 2.5.0

macos 12.6.7

**Comment by extesy** [comment]
Same problem, far2l asks for permissions to access most folders, even though it has a full disk access permission.

**Comment by progreccor** [comment]
@elfmz any solutions?
------
реально каждый раз спрашивает разрешения на доступ

**Comment by akruphi** [comment]
Advice from https://t.me/far2l_ru/11082:
```
sudo codesign --force --deep --sign - /Applications/far2l.app
```

**Comment by elfmz** [comment]
видимо для этого надо сертификат, которого у меня никогда не было для мака, а говорят на 2.5.0 проблемы не было..

**Comment by unxed** [comment]
Модет, есть какие-то зонтичные организации, готовые подписывать всякий опенсорс своим сертификатом?

**Comment by elfmz** [comment]
ну для начала надо както определить что дело именно  в этом, у меня вот не репродьюситься, так что видимо причина какаято плавающая, какаято настройка в info.plist или типа того, но я не большой спец в макосе(

**Comment by StupichevAV** [comment]
Добрый день! В Info.plist вижу вот такие два ключа. В одном ключе стоят вопросы, а в другом ключ пустой.
![01](https://github.com/elfmz/far2l/assets/97597559/ceb4f169-c79b-4766-bb58-e88588bcd9e8)
![02](https://github.com/elfmz/far2l/assets/97597559/7ff75bd5-c9e9-4874-bf8b-ce8d630e9251)

**Comment by progreccor** [comment]
> Advice from https://t.me/far2l_ru/11082:
> 
> ```
> sudo codesign --force --deep --sign - /Applications/far2l.app
> ```

this solution help me

это решение у меня работает (macos ventura 13.5.2 M1 processor)

**Comment by StupichevAV** [comment]
Спасибо. В этот раз мне тоже помогло.

**Comment by akruphi** [comment]
Имеет ли смысл инфу про
```
sudo codesign --force --deep --sign - /Applications/far2l.app
```
в far2l в помощь по **F1** в раздел **FAR2L features - Getting Started** дописать или @elfmz сделает более кардинальное решение?

**Comment by progreccor** [comment]
не знаю имеет ли значение или нет, но сейчас заметил следующую вещь – переносил все программы на новый компьютер, где еще не был установлен FAR и вот там при каждом запуске у меня появлялось окошко выбора шрифтов. Т.е. похоже дело в том, что какие-то данные не записываются в какие-то места хранения.
То же самое и с запросами на допуск к папкам.
После того как выполнил команду 
```
sudo codesign --force --deep --sign - /Applications/far2l.app
```

все стало нормально

**Comment by vyuzhanin** [comment]
> Имеет ли смысл инфу про
> 
> ```
> sudo codesign --force --deep --sign - /Applications/far2l.app
> ```
> 
> в far2l в помощь по **F1** в раздел **FAR2L features - Getting Started** дописать или @elfmz сделает более кардинальное решение?

На сколько я знаю, что бы подписать DMG, надо иметь Developer ID certificate, который входит в платную подписку Apple Developer. $100/yr.

**Comment by elfmz** [comment]
can anyone with such an issue try to install this package and see what happen? Attached files are not zip but parts of dmg, merge them by `cat ./far2l-2.5.2-beta-dmg1.zip ./far2l-2.5.2-beta-dmg2.zip ./far2l-2.5.2-beta-dmg3.zip > ./far2l-2.5.2-beta.dmg` to get original dmg with
$ sha256sum ./far2l-2.5.2-beta.dmg
29f136850eefa345d0fd22bc492cd2ced699b2a86d883e677f2134174de7b294

[far2l-2.5.2-beta-dmg3.zip](https://github.com/elfmz/far2l/files/13197616/far2l-2.5.2-beta-dmg3.zip)
[far2l-2.5.2-beta-dmg1.zip](https://github.com/elfmz/far2l/files/13197614/far2l-2.5.2-beta-dmg1.zip)
[far2l-2.5.2-beta-dmg2.zip](https://github.com/elfmz/far2l/files/13197615/far2l-2.5.2-beta-dmg2.zip)

**Comment by marx-freedom** [comment]
macOS Sonoma, m1, far 2.5.2-beta (что в brew было) - тоже каждый раз спрашивал разрешение по два раза. Помогло запустить codesign как пишут выше.

**Comment by progreccor** [comment]
> Так я не про версию из brew, а вот инсталлер который в предыдущем сообщении приаттачил в трех частях (так как гитхаб ограничивает размер одного аттача в 25мб) Он подписан самоподписанным сертификатом.

если я делал как выше подпись - мне надо как то ее отменить чтобы проверить новый инсталлер?

**Comment by progreccor** [comment]
> can anyone with such an issue try to install this package and see what happen? Attached files are not zip but parts of dmg, merge them by `cat ./far2l-2.5.2-beta-dmg1.zip ./far2l-2.5.2-beta-dmg2.zip ./far2l-2.5.2-beta-dmg3.zip > ./far2l-2.5.2-beta.dmg` to get original dmg with $ sha256sum ./far2l-2.5.2-beta.dmg 29f136850eefa345d0fd22bc492cd2ced699b2a86d883e677f2134174de7b294
> 
> [far2l-2.5.2-beta-dmg3.zip](https://github.com/elfmz/far2l/files/13197616/far2l-2.5.2-beta-dmg3.zip) [far2l-2.5.2-beta-dmg1.zip](https://github.com/elfmz/far2l/files/13197614/far2l-2.5.2-beta-dmg1.zip) [far2l-2.5.2-beta-dmg2.zip](https://github.com/elfmz/far2l/files/13197615/far2l-2.5.2-beta-dmg2.zip)
> 
> here is installer signed with self-signed certificate. Not sure if this will work, but can try.

так, я проверил работу новой версии - она один раз спросила про доступ и все ок.
То есть работает корректно, второй раз больше вопросов не задает. Все как и должно быть.
У меня Sonoma 14.1 на макбук m2 pro

**Comment by elfmz** [comment]
Супер, спасибо. Сделаю пожалуй на днях оф.релизик с такой подписью раз работает.

**Comment by elfmz** [comment]
Can close with recently released binaries?

**Comment by progreccor** [comment]
it is ok on my side.
I think that issue can be closed&
Tested beta 2.53 - it is worked ok
