### ISSUE TITLE
Mouse doesn't work when coming from Windows Terminal

### ISSUE THREAD

**Issue by vb0** [elfmz/far2l#1759]
Clicks don't register in far2l but type some # sequences. Mouse works when coming from the same terminal with Midnight Commander (in fact it works even in mc started in far2l's shell). Mouse works in far2l when coming from other terminals (like for example hterm) but hterm can't type ctrl+enter or ctrl+alt+0, etc.  

Tried multiple versions of far2l (up to master), multiple Windows Terminal (up to Preview) and multiple machines.   

It might be some straightforward setting I'm missing in WT (or far2l?) but I've wasted quite a bit of time on this without luck.

**Comment by akruphi** [comment]
https://github.com/elfmz/far2l/issues/1591#issuecomment-1530124142
https://github.com/microsoft/terminal/issues/15083

**Comment by vb0** [comment]
Thank you @akruphi

**Comment by unxed** [comment]
Touch #2423
