### ISSUE TITLE
data pasted to clipboard from far (especially, by shift-del in far's editor) are cleared on far's close

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#176]
to reproduce:

1. open far
2. open some text file in far's editor
3. cut some text with shift-del
4. close far
5. try to paste text anywhere

same behavour with native far running under wine

**Comment by unxed** [comment]
not sure if it is far's bug as libreoffice writer, for example, behaves the same way

**Comment by unxed** [comment]
still a little bit annoying situation :)

**Comment by elfmz** [comment]
This how clipboard works. There's workarounds however: http://askubuntu.com/questions/143659/gedit-clears-contents-of-clipboard-on-exit-how-to-keep-it
Also from by [another link](https://wiki.ubuntu.com/ClipboardPersistence) there is description, from wich it looks its possible (or planned to be possible), however while I'm using wx - I limited by its functionality. And [there is method](http://docs.wxwidgets.org/3.1/classwx_clipboard.html#a10997196ffd3b2cf8d823033f291f932) that should fix that problem, and WinPort uses it. However somewhy its marked as not implemented for Linux :)

**Comment by unxed** [comment]
`sudo apt-get install parcellite`
fixed this problem for me, thanks.
