### ISSUE TITLE
Fedora EPEL Release.

### ISSUE THREAD

**Issue by cmdorexe** [elfmz/far2l#1760]
Прошу разработчика добавить учётную запись на https://accounts.fedoraproject.org, с привязкой к github аккаунту.
Дальше напишу запрос на создание группы, и запрос на спонсора.

**Comment by elfmz** [comment]
Зарегался там как elfmz и в настройках профиля указал:
![image](https://github.com/elfmz/far2l/assets/20957349/d6abbda4-b781-41cd-a8c3-579322c15c2e)
.. это и есть привязка к github аккаунту? Что она делает кроме просто указания акаунта в профиле? Оно ведь даже никак не проверило правда ли это мой гитхаб акаунт..

**Comment by cmdorexe** [comment]
Ну как-бы да. Дальше просто в переписке будет фигурировать, что-бы вопросов было меньше.

**Comment by elfmz** [comment]
на значит закрываю

**Comment by unxed** [comment]
А за этой перепиской сторонний наблюдатель как-то поглядывать может? Чтобы статус процесса понимать. Если да, оставьте здесь ссылочку, пожалуйста!

**Comment by cmdorexe** [comment]
Запрос на ревью пакета готов:

**Comment by cmdorexe** [comment]
@elfmz мы неуспеваем в 39 релиз, если не рассмотрят до 7-го августа. Думаю стоит до зимы отложить, и предлагать уже новую версию.
