### ISSUE TITLE
far2l on macOS keys 23456 not working (Czech keyboard)

### ISSUE THREAD

**Issue by jan-klimes** [elfmz/far2l#1773]
First thanks for FAR2L for Mac!
When I press numbers 23456 - no numbers are pressed. Other numbers and  Neither in far command line neither in dialog boxes.
Problem is when I use Czech (Česká) keyboard in MacOS. With English keyboard it works probably well.

I tried more prebuild versions and MacOS 12.3.1 and also newer MacOS. All have the same trouble.
Thanks for your time and attention!
Jan

**Comment by unxed** [comment]
In wxMain.cpp, in function onChar, before line

```
ir.Event.KeyEvent.uChar.UnicodeChar = event.GetUnicodeKey();
```

Add:

````
int lkc = _key_tracker.LastKeydown().GetKeyCode();
if ((uni >= 48) && (uni <= 57) && (lkc < WXK_NUMPAD0 || lkc > WXK_NUMPAD9)
  && (lkc < WXK_NUMPAD_SPACE || lkc > WXK_NUMPAD_DIVIDE))
{
  ir.Event.KeyEvent.wVirtualKeyCode = uni;
}
#endif
```

This should help.

Reference: far2l char, from here and above:
https://t.me/far2l_ru/33273

**Comment by jan-klimes** [comment]
Thank for your reply - I would be very excited if you try to correct it for next build. I am not so good at cpp to be able to repair it.

**Comment by unxed** [comment]
#2604

**Comment by jan-klimes** [comment]
Many thanks! I installed release from last week and WORKS WELL!!!
AGAIN: THANK YOU
Jan
