### ISSUE TITLE
[NetRocks] FTP not working in Ubuntu 14.04 if far2l is built without any dependences

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1775]
Issue discovered on Ubuntu 14.04

1. Install Ubuntu 14.04, cmake, pkg-config, g++, git
2. Build far2l using
```
cmake -DUSEWX=no -DUSEUCD=no -DCOLORER=no -DCMAKE_BUILD_TYPE=Release ..
```
2. Try to connect to any FTP server in NetRocks.

![изображение](https://github.com/elfmz/far2l/assets/1151423/3d0b907a-f9a1-42f3-9b9b-1709f6bd3da4)

**Comment by unxed** [comment]
Also reproduces on 16.04

**Comment by unxed** [comment]
And even on 18.04

**Comment by elfmz** [comment]
are you sure it due to specific dependencies but not specific FTP server?

**Comment by unxed** [comment]
tested with
https://dlptest.com/ftp-test/
and
https://www.wftpserver.com/onlinedemo.htm
