### ISSUE TITLE
junk before prompt after exit from far2l 2.5.1 at Ubuntu 22.04 and Debian

### ISSUE THREAD

**Issue by lokapal** [elfmz/far2l#1787]
far2l 2.5.1 was successfully compiled at both Ubuntu 22.04 and Debian 10 without WX and/or X11. The same behaviour observed:
```
root@srv25:~# far2l


;0;4;2;6;1;5;3;7;8;12;10;14;9;13;11;15root@srv25:~# 
```
The second string appears after exit from far2l. As far as I remember far2l 2.4 was free of this glitch. Terminal SecureCRT 8.3-8.7, Emulation Xterm, Color mode ANSI with 256color.
Far2l itself seems working correctly.

**Comment by akruphi** [comment]
> Probably it should be mentioned in docs/readme/website?! Or turned off by default?

Draft info added in #1792 in help section `FAR2L features - Getting Started` in paragraph `Special options for configuring FAR2L running in terminal emulators`. @lokapal please give feedback  if this information is not enough or may be give advice with clearer and shorter text.
