### ISSUE TITLE
При вызове редактора (F4) FAR зависает с надписью FarColorer: Reloading schema library

### ISSUE THREAD

**Issue by mihmig** [elfmz/far2l#1788]
Ubuntu 22.04
Сборка со значениями по-умолчанию.
![photo_2023-08-02_13-30-04](https://github.com/elfmz/far2l/assets/4863752/10b468a0-82e2-4d8e-9a46-859bf661ec24)

**Comment by elfmz** [comment]
не дубль ли этого?
https://github.com/elfmz/far2l/issues/1752

**Comment by SapozhnikUA** [comment]
Имею аналогичную проблему уже несколько лет.
Изначально на ubuntu 18.04  работало, потом "поломалось" 
Ubuntu обновил до 20 - все также не работало
Сейчас на абсолютно новом компе,  Ubuntu 23.04  и свежеустановленный far2l и также наглухо зависает до полного закрытия окна. 

Но!!! 
Зависание происходит если я использую его в терминале PUTTY
Если открываю в терминале в родной GUI то Сolorer нормально работает. 

Пс. К сожалению, я не линуксоид, а только вынужденный пользователь, которому очень нужен far :)  

![image](https://github.com/elfmz/far2l/assets/48523324/51d36459-82f7-4c4e-a6f0-a60d14f72a52)

**Comment by unxed** [comment]
Ну там да, был баг, в свежих putty4far2l поправлено

**Comment by mihmig** [comment]
В свежей версии KÎTTY - 0.76.1.13 @ 17/09/2023-17:11:48(GMT)
проблема исчезла. Баг можно закрывать.
