### ISSUE TITLE
[Netrocks] Timestamp without milliseconds: problems with compare

### ISSUE THREAD

**Issue by akruphi** [elfmz/far2l#1793]
Now the comparison (by `F9 -> Commands -> Compare folders`) local ext4 directory & Netrocks sftp / scp directory select waste files in local directory. In both local & Netrocks sides command `stat` show for file equivalent timestamp with equal milliseconds. It seems that Netrocks use timestamp precision up to seconds, because if on local side I set in file modify millisecound to 000 the comparison will work properly.

**Comment by elfmz** [comment]
somewhy libssh returns timestamps without milliseconds, so workarounded by forcing OPIF_COMPAREFATTIME flag that makes FAR to compare with up to one second granularity.

**Comment by unxed** [comment]
Maybe we should send an issue to libssh on that?
