### ISSUE TITLE
notify in system tray if error while copying has happened

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1794]
Currently, if you copy several thousand files and encounter errors during the process, you have to switch to the far2l window periodically to check if an error has occurred. This is very annoying. It would be beneficial to receive system notifications not only upon completion of copying, but also in every situation that requires user action during the copying/moving process.

**Comment by unxed** [comment]
Great, thanks, !

Am I correct in understanding that error notifications will now appear not only when copying, but also during other long operations (moving, searching for files, etc.)?

**Comment by akruphi** [comment]
May be also add additional to toggle it in F9->Options->Notifications settings ?
