### ISSUE TITLE
Far2l crashes on builds with D_FORTIFY_SOURCE=3 

### ISSUE THREAD

**Issue by icesvz** [elfmz/far2l#1798]
Far2l crashes on Fedora 38 in some cases (when creating new site connection in netrocks plugin, when working in command line).   This happens because in F38 the build flags include D_FORTIFY_SOURCE=3  https://fedoraproject.org/wiki/Changes/Add_FORTIFY_SOURCE=3_to_distribution_build_flags  

The workaround is to use D_FORTIFY_SOURCE=2 (or less?) the test build with D_FORTIFY_SOURCE=2  works fine

**Comment by elfmz** [comment]
Can you provide crash log record from ~/.config/far2l/crash.log together with related binary (that is crashed) with symbols?
I'm asking cuz in my Ubuntu adding -D_FORTIFY_SOURCE=3 to compilation flags doesn't cause crashes

**Comment by icesvz** [comment]
theres no crash.log   :|   coredump + build + debug here https://disk.yandex.ru/d/2BnOwqiiwewJgg

**Comment by elfmz** [comment]
check now please

**Comment by icesvz** [comment]
bug fixed. test builds (gui, tty) works fine with D_FORTIFY_SOURCE=3  for now

**Comment by icesvz** [comment]
### THANK YOU!
