### ISSUE TITLE
two file search panels

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1799]
mc recently added a feature to support panelization buffers for both file panels, which, for example, allows you to panelize the results of two different searches in the panels. far2l can not do it for now. Very sad. Can it be implemented in far2l also?

https://www.opennet.ru/opennews/art.shtml?num=59597
>  Добавлена поддержка буферов панелизации для обеих файловых панелей, что, например, позволяет панелизировать результаты двух разных операций поиска в панелях.

**Comment by elfmz** [comment]
Не очень понятно о чем речь, если что в фаре можно в результатах поиска нажать кнопочку [Panel] и эти результаты отобразятся на временной панели. Потом можно перейти на другую панель запустить поиск оттуда и снова проделать тоже самое. И будут две панели с результатами двух разных поисков.

**Comment by unxed** [comment]
Хм, интересно, у меня раньше не работало такое раньше. При попытке перекинуть результаты второго поиска на вторую панель то ли результаты поиска на первой панели изменялись, то ли ещё что-то глючило. Сейчас навскидку воспроизвести не смог, так что закрою пока. Переоткрою, если словлю такое снова.

**Comment by elfmz** [comment]
ну глюки конечно возможны, но нужен тесткейс тогда
