### ISSUE TITLE
Shift+Enter doesn't work as expected.

### ISSUE THREAD

**Issue by invy** [elfmz/far2l#180]
In windows version of far if you press shift+enter far starts selected scripts in the new terminal (and in the new process). Far2l doesn't.

**Comment by SerjCh** [comment]
And.. Shift+Enter on folder Far for Windows opens explorer with this folder, far2l doesn't. May be need to implement settings for this? Open with selected program for folders & files.

**Comment by unxed** [comment]
I use "caja ." in usermenu for this. Also two keypresses: "F2"," c".

**Comment by elfmz** [comment]
Check if this solution ok.
Also note that its now possible to open dir in DE with shift + enter. type . then shift+enter opens current dir.

**Comment by invy** [comment]
created script in /tmp, called 1.sh, set executable permissions, tried to execute with shift+enter, didn't work.

**Comment by elfmz** [comment]
put ping google,com inside of  script and try again

**Comment by invy** [comment]
ok, thanks, my fault. what kind of terminal app is actually started?

**Comment by elfmz** [comment]
xterm, to change - see open.sh

**Comment by invy** [comment]
ah, ok, if it's configurable it's great.

**Comment by invy** [comment]
Starting new command with shift+enter is not starting it in new terminal/process

**Comment by elfmz** [comment]
aha, also noticed that.. will fix later
