### ISSUE TITLE
problem building on Ubuntu 22.04

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1802]
```
[ 70%] Linking CXX shared module ../install/Plugins/colorer/plug/colorer.far-plug-wide
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/libxerces-c.so: invalid string offset 537053994 >= 4
54617 for section `.dynstr'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/libxerces-c.so: error adding symbols: file format no
t recognized
collect2: error: ld returned 1 exit status
make[2]: *** [colorer/CMakeFiles/colorer.dir/build.make:198: install/Plugins/colorer/plug/colorer.far-plug-wide] Error 1
make[1]: *** [CMakeFiles/Makefile2:873: colorer/CMakeFiles/colorer.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by elfmz** [comment]
I'm now on Ubuntu 22.04 and all good, have you tried full reconf/rebuild after rm'ing build dir ?

**Comment by elfmz** [comment]
Just read log more carefully, it complains about /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/libxerces-c.so that is system installed library, could it be that file is corrupted? Can you apt remove/apt install back and retry then?

**Comment by unxed** [comment]
did apt reinstall already(

**Comment by akruphi** [comment]
@unxed I now build last far2l from git in my `Ubuntu 22.04.3` with `gcc / g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0`. No problem.

**Comment by unxed** [comment]
вот только что сделал полное обновление дистра, ошибка та же. сам удивлён

**Comment by elfmz** [comment]
can you share that /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/libxerces-c.so ?

**Comment by elfmz** [comment]
same for me
