### ISSUE TITLE
far2l 2.5.1 doesn't fill screen properly at Ubuntu 22.04 in screen and/or in TrueColor terminal

### ISSUE THREAD

**Issue by lokapal** [elfmz/far2l#1804]
![far251](https://github.com/elfmz/far2l/assets/6469161/842427a7-631d-4b2c-a059-7d2089445dfb)
Screen virtual terminal manager: Screen version 4.09.00 (GNU) 30-Jan-22
FAR2L, version 2.5.1-beta Linux x86_64
Ubuntu 22.04.3, kernel 5.19.0-50-generic
compiled in terminal-only version without WX.
Terminal: SecureCRT 8.7.3 x64 build 2279, emulation Xterm, Color mode "ANSI with 256color", keyboard "Xterm"
Consolas 12pt font, UTF-8, Unicode graphics characters.
The same bugs are observed in TrueColor mode WITHOUT screen (look at fig.2).
![far251_2](https://github.com/elfmz/far2l/assets/6469161/767da086-94be-4d09-972d-5085f8936b66)

**Comment by elfmz** [comment]
check current master please

**Comment by elfmz** [comment]
Also noted that screen version 4.09 (from apt under Ubuntu 22) doesn't support true color, so to avoid coloring artifacts where true color is used need to run far2l with true color support disabled by --norgb argument

**Comment by unxed** [comment]
Кстати ещё под tmux какие-то глюки были

**Comment by elfmz** [comment]
у меня все работает вроде под tmux

**Comment by elfmz** [comment]
closing since fix is there, reopen if anything still buggy

**Comment by sxored** [comment]
thanks for the fix !

far2l started working as expected under "screen" program

there is an another issue with wrong colors under "tmux" program
