### ISSUE TITLE
Use UTF-8 code page by default in Find File settings

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1812]
On most modern Linux, Mac and BSD systems, the vast majority of content is encoded in UTF8. The use of other encodings is rather exotic. At the same time, the cost of transcoding, which is not necessary for most users, could be avoided if, by default, the search went only in UTF8 encoding.

**Comment by unxed** [comment]
Also .editorconfig setting for the current folder may be added as default option (if none, use UTF8).

**Comment by elfmz** [comment]
By default its a 'Standard code pages' that includes UTF8: https://github.com/elfmz/far2l/blob/master/far2l/src/findfile.cpp#L480C25-L480C25

**Comment by elfmz** [comment]
so, may close?

**Comment by unxed** [comment]
It was about not wasting computing resources by default on checking in several encodings at once. So that only UTF8 is selected by default. And the option "UTF8 and other popular" could be enabled manually if required.

**Comment by elfmz** [comment]
Note that in far2l's file search implementation when you search latin only characters then having UTF8 alongside with set of other single-byte codepages that results in same bytes sequence doesn't bring-in performance impact.

**Comment by unxed** [comment]
And what if search for Cyrillic strong?

**Comment by elfmz** [comment]
far2l completes search for 'превед' substring in 1.5 seconds, mc - 27 seconds. While time increase for far2l is expected (codepage conversion takes its price here), but not sure why mc became much slower. Changing search text to 'преведмедвед' doesn't change numbers either

**Comment by elfmz** [comment]
A also in the past have compared full text search with some other file managers, and found that far2l is fastest one :) especially when working on SSD, where it uses multithreaded text scan. Comparative results could be achieved by running something like `find | xargs -N 16 grep ...`
