### ISSUE TITLE
rclone support in netrocks

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1816]
Users continue to suffer without cloud services support in far2l's netrocks. And suddenly I saw this:
https://rclone.org/commands/rclone_serve_ftp/

It turns out that rclone itself can work as FTP server, giving "proxy" access to a remote host.

It would be great to add to netrocks the ability to automatically launch rclone with the necessary parameters, and only then connect via FTP. So that everything is configured in one place — in netrocks itself.

**Comment by phanex** [comment]
It could be super! 
I see it in the following way:
The user opens netrocks and adds a remote. 
In the drop-down, he chooses rclone.
In the connection address, he enters the existing remote name + optionally a path.
...
Magic!

**Comment by elfmz** [comment]
There is similar option for 'file' protocol. It can be extended to all protocols, is it looks ok?

**Comment by elfmz** [comment]
May try out on branch nr-improvements

**Comment by phanex** [comment]
So did I understand right? It will be possible to do following:

1. I choose ftp.
2. I have an option to execute command in the protocol settings. 
3. I write my connection data such as remote name and if needed working directory.
4. In the protocol settings, I am using variables like $HOST and so on.
And then everything works.

**Comment by phanex** [comment]
It would be also great if there were another command in protocol options, like "execute on closing a connection". To stop rclone server afterwards.

**Comment by elfmz** [comment]
Note that there can be multiple far2l having same connection opened, also even single far2l may have multiple time opened same connection (background copying or browsing same connection on both panels) so connect/disconnect scripts must then have some kind of reference counting.. (that ideally would be good to be resilient to abnormal process termination..)

**Comment by atolismesh** [comment]
> May try out on branch nr-improvements.

Can't compile this branch - 
```
far2l/NetRocks/src/Protocol/ProtocolInitCommand.cpp:47:37: error: ‘time’ was not declared in this scope

  47 |                 time_t time_limit = time(NULL) + std::max(3, protocol_options.GetInt("CommandTimeLimit", 30));
     |                                     ^~~~
```

**Comment by elfmz** [comment]
> Can't compile this branch -

fixed, try now

**Comment by atolismesh** [comment]
It'll be great! 
As I know, `rclone serve` can be deinit only by `kill`

**Comment by atolismesh** [comment]
`rclone serve sftp remote: --user $USER --pass $PASS & `
works great, as expected!

**Comment by atolismesh** [comment]
Sorry, but after second try, got errors: 
Error - Error: flag needs an argument: --pass◙Usage:◙  rclone serve sftp remote:path [f  
Variables $USER and may be other not substituted to values

**Comment by atolismesh** [comment]
Stable errors: 
╔═══════════════════════════════════════ Operation failed ════════════════════════════════════════╗
║ Timeout - <5>NOTICE: Loaded 1 authorized keys from "/home/user/.ssh/authorized_keys"◙<5>NOTICE ║
║                         SFTP server listening on 127.0.0.1:2022◙ (110)                          ║
╟─────────────────────────────────────────────────────────────────────────────────────────────────╢
║                                             { Ok }                                              ║
╚═════════════════════════════════════════════════════════════════════════════════════════════════╝

rclone correctly started sftp server.
But netrocks do not try to connect it.

**Comment by atolismesh** [comment]
May be it is  waiting for the rclone process exit?

**Comment by elfmz** [comment]
Yes, command is expected to (quickly) exit.
I suggest to write shell script and run it, cause:
 & is not handled properly in this command line (it doesn't run shell, just specified command)
 $USER etc are also not handled in command line, but should be expandable as env expressions withing script. Its not good idea to pass sensitive info like credentials via command line as then any unprivileged user may then run ps aux and see all that info.

**Comment by atolismesh** [comment]
It was my first idea. 
But it didn't work.
But adding redirects to the script made a trick:

```
#!/bin/bash
rclone -vv serve sftp gdrive: --user $USER --pass $PASSWORD  >/dev/null 2>&1 &
```

Now it seems to work as expected.

**Comment by elfmz** [comment]
Added support for 'deinit' command and added way to do shared init/deinit across different NetRocks connection instances: just do `if [ "$SINGULAR" = 1 ]; then ... ` in your init/deinit scripts

**Comment by atolismesh** [comment]
Do you have any idea how to 'deinit' right rclone process?

**Comment by elfmz** [comment]
if you can identify it by command line, then
`ps aux | awk ' { if (...) { system("kill "$2); }; }'`

**Comment by atolismesh** [comment]
Может лучше сохранять в NetRocks PID запущенного rclone? 
А сам PID получать как exitcode запущенного 'init' скрипта? 
Тогда точно не промахнемся с kill. 
Т.е. в скрипте использовать следующую конструкцию: 
```
#!/bin/bash
rclone  serve sftp gdrive: --user $USER --pass $PASSWORD  >/dev/null 2>&1 &
exit $! 

```

**Comment by atolismesh** [comment]
Или так - отлавливать в NetRocks последнюю выведенную в скрипте строку и сохранять ее в $NRPID, а затем в deinit скрипте делать kill $NRPID: 

```
#!/bin/bash
rclone  serve sftp gdrive: --user $USER --pass $PASSWORD  >/dev/null 2>&1 &
echo $!
exit  
```

**Comment by unxed** [comment]
Я не понял, можно, наконец, через фар в облака ходить, не выкачивая содержимое целиком?

**Comment by atolismesh** [comment]
Да, конечно! rclone не выкачивает ничего - только отображает в виде виртуальной файловой системы

**Comment by unxed** [comment]
А как там какой-нибудь Яндекс.Диск цепануть теперь? Вместо gdrive что-то другое писать?

**Comment by elfmz** [comment]
Добавил переменную $STORAGE которая указывает на уникальный для данного конекшена путь в который можно положить PID а потом в deinit вычитать его. И удалить, чтож мусор не оставялть.
И вмержил все в мастер

**Comment by unxed** [comment]
А можно, пожалуйста, сделать какой-нибудь Wizard, куда просто логин и пароль от Яндекса/ДругихСервисов говоришь, и он всё настраивает и прописывает? Это ж не сложно должно быть, давайте пожалеем пользователей :)

**Comment by elfmz** [comment]
Так rclone сам по себе такой визард. Просто консольный
![image](https://github.com/elfmz/far2l/assets/20957349/e84dd72c-e69a-464e-91c7-6d79e84a9b9f)

**Comment by unxed** [comment]
| Extra environment variables available for command process: |
| $HOST $PORT $USER $PASSWORD $DIRECTORY                     |

— забыта $STORAGE

**Comment by unxed** [comment]
> Так rclone сам по себе такой визард. Просто консольный

ну блин, требовать от пользователя писать скрипты его запуска просто чтоб стянуть файл из облака? то есть конечно оч классно что оно появилось для тех, кто в состоянии разобраться)) теперь для всех остальных бы

**Comment by unxed** [comment]
может, можно сделать штатные шаблоны этих скриптов хотя бы для яндекса и гугла? там же только логин и пароль меняется, я правильно понимаю?

**Comment by atolismesh** [comment]
> Добавил переменную $STORAGE

So, init script for sftp + rclone now looks like:
```
#!/bin/bash
rclone  serve sftp remote: --user $USER --pass $PASSWORD  >/dev/null 2>&1 &
echo $! >$STORAGE

```
Simple deinit script looks like: 
```
#!/bin/bash
if [ "$SINGULAR" = 1 ] && [ -r $STORAGE]; then kill $(< $STORAGE) ; fi  

```
Right?

**Comment by elfmz** [comment]
1 need to check for `if [ "$SINGULAR" = 1 ] ` also in init otherwise second subsequent opens of connection will launch another rclone 
2 also to `unlink $STORAGE` in deinit to not leave uneeded files

**Comment by unxed** [comment]
Why sftp? Is encryption really needed within localhost? Also FTP is built in far2l without any additional dependencies.

**Comment by atolismesh** [comment]
> Why sftp?

1. It just an example
2. ubuntu 23.04 repository has rclone 1.6.0-dev package missing ftp serve support
3. current rclone 1.6.3 from rclone.org has bug in ftp serve server - ftp dir/ls command do not output year in dates

**Comment by elfmz** [comment]
I'd also add that ftp has poor symlinks support, so if some cloud supports them, this support would be lost in such translation

**Comment by atolismesh** [comment]
> 1 need to check for `if [ "$SINGULAR" = 1 ] ` a


init script for sftp + rclone now looks like:
```
#!/bin/bash
if [ "$SINGULAR" = 1 ] ; then 
	rclone  serve sftp remote: --user $USER --pass $PASSWORD  >/dev/null 2>&1 &
	echo $! >$STORAGE
fi

```
Simple deinit script looks like: 
```
#!/bin/bash
if [ "$SINGULAR" = 1 ] && [ -r $STORAGE ]; then 
	kill $(< $STORAGE) 
	unlink $STORAGE
fi  

```

**Comment by elfmz** [comment]
almost ok, but better to take $STORAGE into quotes everywhere as theoretically home directory (where $STORAGE usually located in) may contain spaces

**Comment by atolismesh** [comment]
> better to take $STORAGE into quotes

Thanks!
II remembered this but forgot to fix it
Fixed in script above

**Comment by elfmz** [comment]
BTW does it really needs /bin/bash ? from first look should work with /bin/sh

**Comment by atolismesh** [comment]
> BTW does it really needs /bin/bash

As I remember, sh do not support $(<  
So: 

Init script for sftp + rclone for **sh** looks like:
```
#!/bin/sh
if [ "$SINGULAR" = 1 ] ; then 
	rclone  serve sftp remote: --user "$USER" --pass "$PASSWORD"  >/dev/null 2>&1 &
	echo $! >"$STORAGE"
fi

```
Simple deinit script for **sh** looks like: 
```
#!/bin/sh
if [ "$SINGULAR" = 1 ] && [ -r "$STORAGE" ]; then 
	kill $(cat "$STORAGE") 
	unlink "$STORAGE"
fi  

```

**Comment by unxed** [comment]
Has it been tested?

**Comment by unxed** [comment]
Can we close an issue now?

**Comment by phanex** [comment]
[atolismesh](https://github.com/atolismesh), может лучше так:

> rclone  serve sftp **$HOST**: --user $USER --pass $PASSWORD  >/dev/null 2>&1 &
Ну, чтобы делать строку универсальной, а название ремоты писать прямо в параметрах соединения? Или я сильно туплю?

**Comment by atolismesh** [comment]
@phanex 
$HOST здесь не подходит, так как это адрес хоста, на котором запускается rclone serve. В большинстве случаев это localhost. 

Я для универсальности использую $EXTRA 

`rclone serve sftp "$EXTRA": --user "$USER" --pass "$PASSWORD" --addr :"$PORT"`

**Comment by unxed** [comment]
native implementation to be discussed in #1861

**Comment by LihacheFF** [comment]
Привет.
Как подключить облачное хранилище Terabox   (terabox.com) в far2l?
Спасибо

**Comment by unxed** [comment]
Надо сначала чтоб в rclone поддержку этого хранилища добавили. Если чаще лайкать и писать что нужна такая поддержка по ссылочкам, вероятность что сделают может стать выше (а может и не стать, но и лайкнуть же не трудно!). 

We first need to add support for this storage provider to rclone. If you like more often and write that such support is needed via links, the likelihood that they will do so may become higher (or it may not be, but it’s not difficult to like!).

https://github.com/rclone/rclone/issues/7496

https://forum.rclone.org/t/degoo-terabox-jiocloud-mediafire-support-rclone/35974/2
https://forum.rclone.org/t/can-rclone-add-support-for-terabox/29807/4

**Comment by unxed** [comment]
Коллеги, я одну штуку не понял. Скрипты для rclone нужно прописать в "Command to execute on connect"? То есть эта команда ДО соединения выполняется?

Тогда бы "on" заменить на "before", а то не интуитивно очень.

**Comment by unxed** [comment]
Пошаговая инструкция для использованя в NetRocks примерно любого протокола (Amazon S3, etc):
1. Устанавливаем rclone:
```
sudo apt install rclone
```
2. Настраиваем подключение, запоминаем его имя (name):
```
rclone config
```
3. Создаем в домашней папке два скрипта:
```
nr_rclone_up.sh
```
```
#!/bin/sh
if [ "$SINGULAR" = 1 ] ; then 
	rclone  serve sftp $EXTRA: --user "$USER" --pass "$PASSWORD"  >/dev/null 2>&1 &
	sleep 3
	echo $! >"$STORAGE"
fi
```
```
nr_rclone_down.sh
```
```
#!/bin/sh
if [ "$SINGULAR" = 1 ] && [ -r "$STORAGE" ]; then 
	kill $(cat "$STORAGE") 
	unlink "$STORAGE"
fi  
```
4. Ставим им право на выполнение:
```
chmod +x nr_rclone*
```
5. Создаем новое соединение в NetRocks.
Протокол: `sftp`
Хост: `localhost`
Порт: `2022`
Режим входа: сохраненный пароль (saved password)
Имя пользователя: `1111` (любое не пустое, на самом деле)
Пароль: `1111` (любой не пустой, на самом деле)
Идём в Extra options
Command to execute on connect: `~/nr_rclone_up.sh`
Command to execute on disconnect: `~/nr_rclone_down.sh`
Extra string passed to command: имя (name) вашего соединения rclone с шага 2

Сохраняем всё. Подключаемся. Пользуемся.

PS: Для быстрых соединений sleep 3 можно заменить на 2 или 1. Для медленных — увеличить.

**Comment by atolismesh** [comment]
`rclone serve sftp "$EXTRA": --user "$USER" --pass "$PASSWORD" --addr :"$PORT" >/dev/null 2>&1 &`

**Comment by peterazmanov** [comment]
Are there any advantages to this approach over `rclone mount` which mounts cloud storage as a FUSE file system?

**Comment by phanex** [comment]
> Are there any advantages to this approach over `rclone mount` which mounts cloud storage as a FUSE file system?
For me, this is a no-brainer. There is no need to have FUSE installed to do mount and unmount a remote. It's very useful to be able to access a remote from time to time without any strings attached.
