### ISSUE TITLE
is it possible to remove this dash line after each command on terminal? see images below

### ISSUE THREAD

**Issue by lucasfellipe3g** [elfmz/far2l#1817]
hello, i'm using far2l and I would like to know if it's possible to remove this green dash line after each command on terminal:

<img width="2056" alt="CleanShot 2023-08-30 at 14 06 41@2x" src="https://github.com/elfmz/far2l/assets/128543119/188c02c2-2c00-4e8d-beac-c7877d082348">

**Comment by elfmz** [comment]
no, there is no such setting for now
