### ISSUE TITLE
When folder deleted outside, and u're in subfolder of this folder, clicking on ".." will produce "Error 2"

### ISSUE THREAD

**Issue by SerjCh** [elfmz/far2l#183]
subj

![screenshot from 2016-10-26 09-52-18](https://cloud.githubusercontent.com/assets/19835749/19716050/2cbde522-9b62-11e6-91b5-0b433b33d281.png)

**Comment by elfmz** [comment]
IMHO this is rather expected

**Comment by SerjCh** [comment]
Far 3 also, but differ messages
![screenshot from 2016-10-26 14-14-22](https://cloud.githubusercontent.com/assets/19835749/19724009/96c5ec66-9b86-11e6-9d0a-a21c7373ad6b.png)

**Comment by elfmz** [comment]
absent error messages - is different story..

**Comment by unxed** [comment]
> subj
> 
> ![screenshot from 2016-10-26 09-52-18](https://cloud.githubusercontent.com/assets/19835749/19716050/2cbde522-9b62-11e6-91b5-0b433b33d281.png)

Not reproduced any more. May be closed now?
