### ISSUE TITLE
Title of List in dialogs now broken

### ISSUE THREAD

**Issue by akruphi** [elfmz/far2l#1831]
Свойства плагина https://github.com/VPROFi/processes/
при сборке на far2l 2.5.0 показывают заголовки Aviable и Selected у списков - вот скриншот от автора плагина:
![изображение](https://github.com/elfmz/far2l/assets/92621645/90f7694e-7c91-4027-8f60-3245ff529d66)

У меня при сборке в текущей версии этих заголовков нет :cry::
![изображение](https://github.com/elfmz/far2l/assets/92621645/48d2e6b1-44be-46f4-b370-03240e5e9817)

Заголовки списков создаются строками 481...485 https://github.com/VPROFi/processes/blob/0bc4ad2d430613d75d9bf1dd8bfe7371650eca44/src/plugincfg.cpp#L481

Хорошо было бы это как-то пофиксить.

**Comment by VPROFi** [comment]
По багу - появился тут:
https://github.com/elfmz/far2l/commit/6cfc080c58f7c9d0d4c9b33e941c3d75dad77c26#diff-390c8eeded1bd9475b28f5f6c9f3fb0f5e1b8dfea38d66ad236d119d63ba686dR1679

```c
~/projects/processes/vendor/far2l/far2l/src$ git diff
diff --git a/far2l/src/vmenu.cpp b/far2l/src/vmenu.cpp
index 2220ec84..7642f155 100644
--- a/far2l/src/vmenu.cpp
+++ b/far2l/src/vmenu.cpp
@@ -1722,7 +1722,7 @@ void VMenu::ShowMenu(bool IsParent, bool ForceFrameRedraw)
                if (BoxType != NO_BOX)
                        Box(X1, Y1, X2, Y2, Colors[VMenuColorBox], BoxType);

-//             DrawTitles();
+               DrawTitles();
        }

        wchar_t BoxChar[2] = {0};
```
