### ISSUE TITLE
Default link type

### ISSUE THREAD

**Issue by KarelWintersky** [elfmz/far2l#1833]
![image](https://github.com/elfmz/far2l/assets/2164874/03c4e384-b1fb-45e7-9b81-f84abfb21f98)

в этом окне диалога Link type **всегда** по умолчанию `hard link`, но я всегда использую `symlink`. 

Переключаться не очень удобно. Хотелось бы иметь где-нибудь в настройках опцию "тип ссылки по умолчанию".

`about:config` в far2l же нет?

**Comment by akruphi** [comment]
`far:config` позавчера добавлен в far2l (но пока без редактирования параметров). Теперь черновые `far:config` и `far:about` есть.

Насколько я знаю отдельного параметра, чтобы выбирать предлагается по умолчанию hard link / symbolic link сейчас в far2l не существует.

**Comment by KarelWintersky** [comment]
> Насколько я знаю отдельного параметра, чтобы выбирать предлагается по умолчанию hard link / symbolic link сейчас в far2l не существует.

Примите как feature request ;-)

**Comment by akruphi** [comment]
Спасибо за идею. Реализовано. Проверяйте юзабельность и понятность, что это теперь настраиваемо и где.
