### ISSUE TITLE
exclude from history when command starts with a space

### ISSUE THREAD

**Issue by VPROFi** [elfmz/far2l#1838]
In the Linux command line, when you specify a space before a command, it is not placed in the command history.  I suggest implementing something like this in far2l - add check ```!strStr.Begins(L' ')``` in file ./far2l/src/cmdline.cpp 
```c

			// addition to the option, exclude from history when command starts with a space
			if (!(Opt.ExcludeCmdHistory&EXCLUDECMDHISTORY_NOTCMDLINE) && !strStr.Begins(L' '))
				CtrlObject->CmdHistory->AddToHistory(strStr);

```
https://github.com/VPROFi/far2l/blob/master/far2l/src/cmdline.cpp#L477

**Comment by unxed** [comment]
dup https://github.com/elfmz/far2l/issues/1626 ?

**Comment by akruphi** [comment]
It work in far2l for **Interface/Completion.Exceptions** with current default parameter `git*reset*--hard;*://*:*@*;" *"` where " *" (in quotes space and asterisk) exclude such commands

**Comment by VPROFi** [comment]
> dup #1626 ?

is bash [default behavior](https://github.com/bminor/bash/blob/master/bashhist.c#L688) space - cmd should be discarded. In far2l - it is not "default behavior". I am agree with [akruphi](https://github.com/akruphi)(https://github.com/elfmz/far2l/issues/1626#issuecomment-1520354682) - " совсем не интуитивно понятно"

```c
/* Check LINE against what HISTCONTROL says to do.  Returns 1 if the line
   should be saved; 0 if it should be discarded. */
static int
check_history_control (line)
     char *line;
{
...
  /* ignorespace or ignoreboth */
  if ((history_control & HC_IGNSPACE) && *line == ' ')
    return 0;
...
```
