### ISSUE TITLE
[NetRocks] [SHELL] running script causes hang

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1855]
running such script on remote system causes hang
```
#!/bin/bash
cd far2l/far2l
echo
git pull
echo
read -p "Press any key..."
```

https://github.com/elfmz/far2l/issues/1819#issuecomment-1733007207

**Comment by unxed** [comment]
Теперь по Ctrl+C по крайней мере прервать можно, ура!

Так понимаю, лучше не сделать? @elfmz

**Comment by elfmz** [comment]
ага
