### ISSUE TITLE
[NetRocks] [SHELL] remote far2l window size problem

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1856]
![изображение](https://github.com/elfmz/far2l/assets/1151423/88ff826a-7cf1-4712-8ca8-20dae61970aa)
https://github.com/elfmz/far2l/issues/1819#issuecomment-1732657591

**Comment by elfmz** [comment]
Ну в текущей реализации это не пофиксить иначе кроме как передавать размер терминала через far2l extensions

**Comment by unxed** [comment]
Меня оно не парит, сама возможность гонять так фар это имхо несколько надуманный и экстремальный юзкейс, так что утяжелять ради него протокол экстеншнов, который уже много где используется, я б не стал. А тикет тогда пусть пока будет, кому-то эта проблема будет мешать — отпишется. Ну или надо документировать это как известное ограничение, а тикет закрыть, чтоб совсем красиво :)

**Comment by elfmz** [comment]
да норм че пусть будет

**Comment by unxed** [comment]
Работает, и вполне отзывчиво! Фантастика, конечно :)

**Comment by elfmz** [comment]
я тут поменял способ детекта far2l в этом случае, если что надо пересобирать far2l с обоих сторон ща чтоб экстеншены работали

**Comment by unxed** [comment]
ага, я уже :)
