### ISSUE TITLE
[NetRocks] [SHELL] can not run mc

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1859]
https://github.com/elfmz/far2l/issues/1819#issuecomment-1733414479
```
<shell:unxed@runcity.org>$ mc
The TERM environment variable is unset!
```

**Comment by elfmz** [comment]
ну если определить TERM=vt100 то оно работает, но так, что наверное лучше пусть не работает вообще)

**Comment by unxed** [comment]
Фарчик вот работает (я в полном восторге), трико в маленьком размере и без экстеншнов.

**Comment by unxed** [comment]
Аххаха надо в mc тикет написать: Чего это вы не работаете под протоколом вашего же изобретения!

**Comment by unxed** [comment]
> Фарчик вот работает (я в полном восторге), только в маленьком размере и без экстеншнов.

Но пользоваться даже так можно, потому что OSC52 — работает.

**Comment by elfmz** [comment]
Ну fish mc-я и fish far2-я это строго говоря две совершенно разные рыбины. И кстати в mc в Shell link исполнять команды низзя

**Comment by unxed** [comment]
Да я понимаю! Очень кстати бесило что нельзя. В полном восторге, что у нас можно.

**Comment by unxed** [comment]
А ему не даёт работать та же проблема, из-за которой скрипт, ожидающий ввода, виснет? Или там что-то другое?

**Comment by unxed** [comment]
Ой, тут интересное. Попробовал там всякое.

С TERM=vt100 получаем чбшный mc и половина кнопок не работают.
А вот с TERM=xterm уже вполне юзабельно (хотя тоже не во всё окошко работает).

Но это под gui-версией far2l. А вот если из-под телефонного JuiceSSH запустить консольный far2l, и оттуда по shell куда-то, и там mc — тогда стрелки и F1-F10 не работают и навреняка много чего ещё. Всякие квадратные скобки и заглавные латинские буквы в консоль сыпятся.

Оочень странно.

**Comment by elfmz** [comment]
После последнего коммита желающие могут запустить так: `TERM=xterm mc` или отдельно export TERM=xterm и потом mc.. Так что формально баг можно прикрыть, но тока все равно оно не юзабельно

**Comment by unxed** [comment]
а у меня после последнего коммита отвалились экстеншны, хотя версия на сервере и клиенте одна и та же, последняя

**Comment by elfmz** [comment]
ребилд был чистый? если нет то скорее всего не подхватился remote.sh

**Comment by unxed** [comment]
помогло, спасибо!

**Comment by unxed** [comment]
> А вот если из-под телефонного JuiceSSH запустить консольный far2l, и оттуда по shell куда-то, и там mc — тогда стрелки и F1-F10 не работают и навреняка много чего ещё. Всякие квадратные скобки и заглавные латинские буквы в консоль сыпятся.

Это пока не выглядит стоящим времени. Если кому-то будет мешать на реальных задачах — переоткроем.
