### ISSUE TITLE
Change Codepage for Ctrl-Z (make description) from 866 to utf8

### ISSUE THREAD

**Issue by sws33** [elfmz/far2l#1870]
Описание файлов по  Ctrl-Z делаются в кодовой странице 866 по умолчанию. Сделайте пожалуйста в utf8 или выбор кодовой страницы в настройках. Смотрел настройки, не нашёл, как можно поменять.

**Comment by akruphi** [comment]
Настройка на UTF8 уже есть, но по учмолчанию она выкл.
См. Options->File descriptions->Save in UTF8
![изображение](https://github.com/elfmz/far2l/assets/92621645/e86501ed-350a-42a8-b2d5-7920b7502383)
