### ISSUE TITLE
10 second delay on start when launched from desktop shortcut

### ISSUE THREAD

**Issue by alk0** [elfmz/far2l#1875]
Manjaro/Arch, KDE, clean build, wx.
First noticed on beefe74e, last checked without having this issue was f9b63e4. Haven't tested anything in between yet.

There's a 10 second delay when launching far2l using a desktop shortcut (of any kind, including newly created one with nothing but 'far2l' in it).
No delay when launching from the terminal.
No delay when launching in terminal (--tty).

Any ideas about what can cause it?

**Comment by elfmz** [comment]
Can you check if it reproducible now for you?

**Comment by alk0** [comment]
No, same delay. Let me try a clean build to be sure, it will take some 15-20 minutes (slow machine).

**Comment by alk0** [comment]
Fresh `git clone`, fresh build — **NO** delay.

**Comment by elfmz** [comment]
ok closing them
