### ISSUE TITLE
Подключение через FISH протокол -- пустой результат

### ISSUE THREAD

**Issue by MichaelKochanov** [elfmz/far2l#1879]
При подключении к старой железке с BusyBox пустой список файлов, хотя из командной строки тут же ls, например выполняется
[far2l.log](https://github.com/elfmz/far2l/files/12805141/far2l.log)
[nr-shell.log](https://github.com/elfmz/far2l/files/12805142/nr-shell.log)
BusyBox v1.11.2 (2015-04-06 14:24:36 PDT) built-in shell (ash)

**Comment by elfmz** [comment]
можете проверить как с текущим мастером?

**Comment by MichaelKochanov** [comment]
Да теперь все работает! 
Прошу прощения, что долго не отвечал, вне зоны доступа был неделю...
