### ISSUE TITLE
Каждый запуск запрашивается доступ к папкам в домашке пользователя

### ISSUE THREAD

**Issue by valdemar1977** [elfmz/far2l#1880]
При каждом запуске far2l появляется окно с сообщением что необходимо предоставить доступ к папке загрузки и папке документы, хотя в настройках безопасности приложению предоставлен доступ к диску. ventura 13.6 far2l 2.5.2 установлен через brew

**Comment by akruphi** [comment]
Вроде бы говорят, что помогает совет https://github.com/elfmz/far2l/issues/1754#issuecomment-1695426363

**Comment by valdemar1977** [comment]
> Вроде бы говорят, что помогает совет [#1754 (comment)](https://github.com/elfmz/far2l/issues/1754#issuecomment-1695426363)

спасибо, работает.
