### ISSUE TITLE
MultiArc issue

### ISSUE THREAD

**Issue by shmuz** [elfmz/far2l#1884]
- создаёте папку foo, а в ней папку bar
- создаёте папку bar рядом с папкой foo
- становитесь на папку bar (которая рядом с foo), нажимаете ShiftF1, выбираете архиватор 7Z, создаёте архив bar.7z
- становитесь на bar.7z, нажимаете Enter
Видите внутри архива и bar, и foo, причём foo отображается без даты и времени

**Comment by elfmz** [comment]
У меня не воспроизводится.
Но - вопрос: а bar.7z если его открыть другим архиватором - тоже содержит bar и foo? Если да - можно расшарить такой bar.7z?

**Comment by shmuz** [comment]
Если архиватор TAR или TARGZ или ZIP - не воспроизводится.
С 7Z воспроизводится 100%.
Сейчас снова проверил со свежим билдом far2l.
Файл приложен (дополнительно завёрнут в zip, так как 7z здесь не дают прикрепить).
[bar.7z.zip](https://github.com/elfmz/far2l/files/12902406/bar.7z.zip)

**Comment by shmuz** [comment]
Чтобы не было недопонимания, структура папок такова:
```
├───bar
└───foo
    └───bar
```
Архивируем тот bar, который рядом с  foo (не тот, который внутри foo).
Хорошо заметно, если эта структура папок лежит в $HOME, то видно, как при архивации наяинают сканироваться все папки, входящие в $HOME, на предмет нахождения в них bar.

**Comment by akruphi** [comment]
Данная ошибка воспроизводится, если при такой структуре каталогов в командной строке запустить
```
7z a -y -r bar_arc bar
```
и внутри bar_arc получаем как раз описанное выше.
Если же указать без `-r`
```
7z a -y bar_arc bar
```
то получается архив как и должно быть.

Возможно решением будет в строке 287 и 288 в файле
[`far2l/multiarc/src/formats/7z/7z.cpp`](https://github.com/elfmz/far2l/blob/fd31c691fdac729416a09ece79398f369719048b/multiarc/src/formats/7z/7z.cpp#L287)
убрать `-r`, но тут не уверен - я не очень понимаю сходу нюансы ключей 7z.

Проявлялось на 7z, который у меня стоит из стандартной репы Ubuntu 22.04.3:
```
7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02
```

**Comment by elfmz** [comment]
А да воспроизвелось, я не делал вложенный bar просто вначале
Почитал man 7z, увидел забавное про ключик -r
![image](https://github.com/elfmz/far2l/assets/20957349/fd133d15-fc94-4502-9bf4-9ec7cdecddea)
учитывая что без -r работает вроде нормально и рекурсивно все добавляет, возможно он и вправду не нужен.

**Comment by elfmz** [comment]
Ключик убрал, но теперь надо будет пойти в настройки мультиарка/Command lines/7z и сделать Reset

**Comment by akruphi** [comment]
> Ключик убрал, но теперь надо будет пойти в настройки мультиарка/Command lines/7z и сделать Reset

Даже Reset не потребовался. Пересобрал. Закрыл старый far2l. Открыл пересобранный - в настройках уже вариант без -r

**Comment by elfmz** [comment]
ну если старые командлайны не сохранялись то Reset не нужен

**Comment by elfmz** [comment]
вобщем закрываю
