### ISSUE TITLE
MultiArc opens a text file as an archive

### ISSUE THREAD

**Issue by shmuz** [elfmz/far2l#1887]
Обычно на моём Linux Mint (в том числе и в фаре) при нажатии Enter на файле с расширением .txt данный файл открывается редактором xed.
Ассоциация на файлы *.txt в фаре не выставлена.
Но вот приложенный файл почему-то открывается мультиарком как архив.
Наверное это неправильно.
[CMakeLists.txt](https://github.com/elfmz/far2l/files/12907492/CMakeLists.txt)

**Comment by unxed** [comment]
Ха, у меня тоже Mint. Лучше, наверное, сказать, какой: Cinnamon, MATE, или может вообще Debian Edition?

**Comment by unxed** [comment]
У меня на Cinnamon воспроизводится впрочем.

**Comment by shmuz** [comment]
Рискну предположить, что это не зависит ни от Mint, ни от Cinnamon, а только от MultiArc.

**Comment by elfmz** [comment]
это libarchive поддерживает очень много форматов, иногда весьма экзотичных

**Comment by shmuz** [comment]
Теперь поведение такое:
1. Данный файл уже не открывается как архив, но мультиарк блокирует вызов редактора xed, то есть при нажатии Enter как бы ничего не происходит.
2. Если выгрузить мультиарк и снова загрузить, то при нажатии Enter на данном файле получаем крэш.

![image](https://github.com/elfmz/far2l/assets/344558/95724ae6-e2a3-4757-bbba-7c8ed502cdbd)

**Comment by elfmz** [comment]
а сейчас?

**Comment by shmuz** [comment]
Сейчас открытие редактора xed не блокируется, стало нормально.
Что же касается 2-го пункта (крэш), то это осталось.

**Comment by elfmz** [comment]
А 'выгрузить мультиарк' - это как? А то я не очень опытный пользователь FAR'а..

**Comment by shmuz** [comment]
FARAPIPLUGINSCONTROL   PluginsControl;
Естественно, вызывать из другог плагина, (не из мультиарка), можно из фара - как кому удобнее.

**Comment by elfmz** [comment]
а раньше оно работало в похожем сценарии? есть подозрение что мои последние изменения тут не причем

**Comment by shmuz** [comment]
Это трудно определить. Сейчас взял билд от 8-го августа, этот билд открывает тестовый файл как архив.
После выгрузки и загрузки ьультиарк - тоже открывает как архив.

**Comment by elfmz** [comment]
Вобщем, прикол в том что dlclose не выгружает библиотеку мультиарка, и вследствии забытого обнуления указателя на объект тот оставался мусорным для следующего инстанса плагина и все это падало. В интернетах говорят что для это нормально: https://stackoverflow.com/questions/24467404/dlclose-doesnt-really-unload-shared-object-no-matter-how-many-times-it-is-call
Вроде этого обнуления там никогда и не было, как оно могло работать - хз.

**Comment by elfmz** [comment]
сейчас вроде починил если что

**Comment by shmuz** [comment]
Да, падения прекратились. Спасибо.
