### ISSUE TITLE
interface is disturbed in WezTerm

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#1889]
1. run
far2l --tty --nodetect=x
in [WezTerm](https://github.com/wez/wezterm)

2. press Ctrl+O two times

3. open any short file in viewer or editor

**Comment by unxed** [comment]
![изображение](https://github.com/elfmz/far2l/assets/1151423/ec69bff1-825d-47ce-a44f-e0b5928912e9)

**Comment by sirburpalot** [comment]
Same problem here. The UI looks normal immediately after launching far2l, but becomes corrupted after performing any action that clears the screen, like pressing Ctrl+O or viewing a file using F3.

![image](https://github.com/elfmz/far2l/assets/1429516/d67d84b7-f140-4ef0-9c52-6cd62e60f47a)

**Comment by unxed** [comment]
I discovered an interesting pattern. The interface seems to break when trying to print a line off the screen. Like here (far2l after ctrl+o in gnome terminal and wezterm, see `Copyri`

![Снимок экрана от 2024-03-20 21-57-25](https://github.com/elfmz/far2l/assets/1151423/25d4312d-4774-45ef-8133-be36cdfa66b1)

**Comment by unxed** [comment]
Also please note the position of ArrowUp char. It should be printed int the end of a line, but in WezTerm it is in the beginning

![изображение](https://github.com/elfmz/far2l/assets/1151423/69711ac1-f0b8-4797-ae61-4f3065cf93e2)

**Comment by unxed** [comment]
Implemented workaround on our side:
https://github.com/elfmz/far2l/pull/2089/files
