### ISSUE TITLE
Licensing clarity

### ISSUE THREAD

**Issue by techtonik** [elfmz/far2l#19]
I noticed that there is no `LICENSE` file that is present in standard Far3 repository. This is a license violation that can lead to termination of `far2l` project o GitHub.

To avoid "license deadlock" and make it more useful for upstream, the original BSD code pieces could be kept separated from GPLv2 both in headers and in top level LICENSE file.

**Comment by elfmz** [comment]
Original FAR has modified BSD licence that is convertible to GNU/GPL
And since far2l now has a GPL code inside its simplier to make everything to be GPL instead of marking code GPL/BSD piece-by-piece.

**Comment by techtonik** [comment]
@elfmz the fact that BSD is compatible with GPL doesn't mean that you can replace it. Also, GPLed code can't be merged back to upstream, so clarification is needed.

**Comment by elfmz** [comment]
see: https://en.wikipedia.org/wiki/License_compatibility :
>  Many of the most common free software licenses, especially the permissive licenses, such as the original MIT/X license, BSD licenses (in the three-clause and two-clause forms, though not the original four-clause form), MPL 2.0, and LGPL, are GPL-compatible. That is, their code can be combined with a program under the GPL without conflict and **the new combination would have the GPL applied to the whole (not the other license**).

**Comment by elfmz** [comment]
However partial licensing is impossible: GPL restricts this cuz according to its 2.b the work that contains any GPL part must be whole GPL'ed. Thats why GPL called viral license :)
Also of course code that was originally written by BSD license still available under BSD license - just take it from original project.

**Comment by techtonik** [comment]
Right, partial licensing is impossible when code is distributed, but keeping BSD and GPL sources clearly separated still allows to merge BSD changes back on the source level. So getting back LICENSE file and making wineguts more like a library may help to port Far completely in the long run. )

**Comment by elfmz** [comment]
Once again: 
1) there is no legal problem in switching from modified BSD to GPL for existing code
2) there is problem in not switching from BSD and trying to use it together with GPL code
so best thing for 'long run' is either to don't use GPL either switch to it completely. Sad but true.

**Comment by lieff** [comment]
Насколько я еще знаю, автор в любое время может может начать распространять под другой лицензией, и даже под двумя одновременно.
https://habrahabr.ru/post/243091/
```
Обратите внимание на важный момент: если у вас достаточно прав на произведение, то вы можете распространять его под разными лицензиями (в том числе, одновременно). Например, на вашем сайте вы можете распространять программу бесплатно под свободной лицензией, а в каком-либо магазине приложений она может продаваться за деньги под их стандартной лицензией.

Также Вы можете сменить лицензию в любое время: например, сегодня у вас на сайте программа была бесплатной под свободной лицензией, а завтра она платная и с закрытыми исходниками. Но в этом случае вы не можете заставить пользователей, скачавших программу ранее, следовать нормам новой лицензии. Это логично, ведь они получили программу по другому договору. 
```

**Comment by techtonik** [comment]
> 2) there is problem in not switching from BSD and trying to use it together with GPL code

Yes, that requires extra overhead to [keep 'em separated](https://www.youtube.com/watch?v=1jOk8dk-qaU). 

> However I can add additional readme in far2l dir and mention there that this particular code was initially BSD.

That would be awesome, but maybe it needs separate LICENSE file, because when files are modified, they become infected with new clauses and are no longer can be used as stated in their headers.

> But this will not change anything, except wasting of another 5 minutes of my lifetime.

Debian has very strict policy towards licensing, so if you want somebody to package it, it maybe better to think about it before it is not too late. =)

**Comment by techtonik** [comment]
> Насколько я еще знаю, автор в любое время может начать распространять под другой лицензией, и даже под двумя одновременно.

Yes. But if you develop open source project and accept pull requests. you need agreement from every contributor.

**Comment by techtonik** [comment]
I must say that I don't insist - it is up to you when you decide to close this bug report.

**Comment by techtonik** [comment]
Yea, as I thought - removing LICENSE file is violation of a copyright law, so your fork is illegal.  =) https://opensource.stackexchange.com/questions/4424/remove-bsd-license-file-while-importing-code-into-gpl-project/4425#4425
