### ISSUE TITLE
feature request: add an option to show non-printable characters (like spaces) in viewer/editor 

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#190]
and, possibly, in the other parts of far's interface (as separate option)

this will ease determenation between empty lines and lines, beginning with lots of spaces (in viewer/editor), for example

non-printable characters cat be show as some placeholder character (user-configurable if possible)

**Comment by elfmz** [comment]
There is such option for editor - F9/Options/Editor settings/Show white space
.oO(feeling like a necroposter)..

**Comment by unxed** [comment]
Cool, it works, thanks, closing.
