### ISSUE TITLE
Files highlighting: расширения в разном регистре

### ISSUE THREAD

**Issue by c1on** [elfmz/far2l#1903]
Не выделяются цветом файлы с расширениями, отличными от уже указанного регистром символов.

Например, если перечислены `*.jpg,*.JPG,*.png,*.PNG` файлы с расширениями JPG и PNG выделены цветом не будут.
В то же время, если перечислены `*.jPg,*.JPG,*.jpg`, в директории, содержащей файлы со всеми тремя "расширениями", цветом будут выделены только с `jPg`.
В любой комбинации расширений, различающихся только регистром символов, цветом будет выделено только первое по счёту.

FAR2L, version 2.5.2-fb3b0943-beta Linux x86_64

**Comment by akruphi** [comment]
Подтверждаю. Также проявляется в поиске по Alt+F7. Похоже, если подряд перечислены расширения различающиеся только регистром, то кушается лишь первый, а остальные отбрасываются.

**Comment by elfmz** [comment]
вроде зафиксил, хотя надо подумать о том чтобы сделать опциональное регистронезависимое сравнение

**Comment by akruphi** [comment]
Насколько теперь по **Alt-F7** актуальна галочка `[ ] Case sensitive`?

**Comment by elfmz** [comment]
Эта галочка влияет (и всегда влияла) только на поиск подстроки в файле. На сравнение имен файлов у нее нет влияния.
