### ISSUE TITLE
[Feature request] Поддержка glob и regexp при групповой пометке

### ISSUE THREAD

**Issue by dayfuaim** [elfmz/far2l#1912]
Сейчас (v2.5.3-beta), если нужно выделить, например, файлы с несколькими расширениями, нужно их все выписать через запятую, хотя есть GLOB `*.{ext1,ext2,ext3}`, да и regexp был бы удобнее: `\.ext[1-3]$`.

Пожалуйста, сделайте такую возможность. :)

**Comment by spnethw** [comment]
> да и regexp был бы удобнее: `\.ext[1-3]$`.

Во многих диалогах, наряду с классическими масками, регулярные выражения можно использовать уже давно — см. разделы помощи "Маски файлов" и "Регулярные выражения".

>    В масках можно использовать регулярные выражения, при этом текст регулярного выражения
> должен быть окружён символами /.
> 
>    Пример:
>    /(eng|rus)/i  файлы, имена которых содержат строки “eng” или “rus”,
>                  регистр символов не учитывается.

Для вашего случая:` /\.ext[1-3]$/`

**Comment by dayfuaim** [comment]
> Во многих диалогах, наряду с классическими масками, регулярные выражения можно использовать уже давно — см. разделы помощи "Маски файлов" и "Регулярные выражения".
> 
> > В масках можно использовать регулярные выражения, при этом текст регулярного выражения
> > должен быть окружён символами /.
>
> Для вашего случая:` /\.ext[1-3]$/`

Спасибо огромное.
Будем использовать. :)
