### ISSUE TITLE
Shift+Enter does not work

### ISSUE THREAD

**Issue by faerot** [elfmz/far2l#1913]
In Windows Far Shift+Enter allowed to launch command or an executable in separate console. Looks like far2l does not have this feature.
My naive way of implementing it:
If $DESKTOP_SESSION is present, then check if /etc/alternatives/x-terminal-emulator exists. If it exsts, then launch:
/etc/alternatives/x-terminal-emulator -e './file_under_cursor' &
This should work under Ubuntu. Maybe there some other different/better ways.

**Comment by faerot** [comment]
I could make a fix if someone would point me to a proper place in the source code where this should be handled

**Comment by akruphi** [comment]
For run by Enter / Shift+Enter see about
https://github.com/elfmz/far2l/blob/972f6b1880354f738dcf704e3581e6809432991a/far2l/src/cmdline.cpp#L495
and inside function `CmdExecute` in
https://github.com/elfmz/far2l/blob/972f6b1880354f738dcf704e3581e6809432991a/far2l/src/execute.cpp#L411

**Comment by akruphi** [comment]
For Shift+Enter the flag `SeparateWindow` is now ignored in `ProcessOSCommands`
https://github.com/elfmz/far2l/blob/972f6b1880354f738dcf704e3581e6809432991a/far2l/src/execute_oscmd.cpp#L97

It is only processed in `ExecuteA`
https://github.com/elfmz/far2l/blob/972f6b1880354f738dcf704e3581e6809432991a/far2l/src/execute.cpp#L363
for run non-shell executable.

**Comment by faerot** [comment]
I have added these lines after ```EXEC_TERM=xterm``` and Shift+Enter now working under Ubuntu
```bash
if ( [ ! -z "$DESKTOP_SESSION" ] && [ -x /etc/alternatives/x-terminal-emulator ] ); then
    EXEC_TERM=/etc/alternatives/x-terminal-emulator
fi
```
[open.sh.zip](https://github.com/elfmz/far2l/files/13618527/open.sh.zip)

Fixed open.sh attached for your convenience
Maybe someone from the devs would apply it in the repository?
