### ISSUE TITLE
Работа с FTP-сервером, поднятом на IIS

### ISSUE THREAD

**Issue by lionsoft** [elfmz/far2l#1915]
Столкнулся со следующей проблемой: при попытке подключится через NetRocks (v/1.0 & FAR2l 2.5.2) к FTP-серверу поднятом на IIS (Windows) (пассивный режим) зависает на получении списка файлов директории (в настройках FTP-сервера стоит настройка отдавать список файлов в формате LINUX). 
С тем же самым сервером и в то же самое время NetBox работает без проблем.

**Comment by unxed** [comment]
А FarFTP плагин если собрать, с ним работает?

**Comment by lionsoft** [comment]
Не знаю. Я использую стандартную установку far2l из репозитория Ubuntu 23.10 - все настройки по умолчанию:

**Comment by lionsoft** [comment]
Не знаю. Не пробовал. Даже не знаю, что это за плагин. Filezilla, если что - работает.
Я использую стандартную установку far2l из репозитория Ubuntu 23.10 (всё по умолчанию, простой FTP, порт 21, пассивный режим).

**Comment by lionsoft** [comment]
Всё оказалось намного интереснее. Когда я подключился через мобильный интернет - то всё подключилось без проблем.

Может быть есть какой-нибудь протокол работы NetRocks, чтобы посмотреть в чём разница обмена данными по сравнению с NetBox или Filezilla?

**Comment by akruphi** [comment]
Как включить логи см. в https://github.com/elfmz/far2l/wiki/Running-far2l-with-debug-logging-enabled

В ubuntu 23.10 версия far2l от конца весны и только консольная TTY|Xi. По мне GUI удобнее, хотя на NetRocks это отражаться не должно. Попробуйте текущую версию (взятую из официального репозитария) снести и поставить наиболее свежий far2l из https://launchpad.net/~far2l-team/+archive/ubuntu/ppa

**Comment by lionsoft** [comment]
Обновил far до последней версии `2.5.3.660ca38-beta` - ничего не поменялось. Версия NetRocks осталась `1.0`

Для включения логов выполнил команды:

**Comment by lionsoft** [comment]
Включил протокол. Нашёл разницу.
Вот протокол, когда всё работает:

```

**Comment by lionsoft** [comment]
И да, проблема не в том, что это FTP-сервер на IIS, а именно проблема конкретно с этим сервером. С другими FTP-серверами работает нормально.

**Comment by elfmz** [comment]
проверься как ща плз

**Comment by lionsoft** [comment]
обновил `far2l` - заработало! Спасибо.

**Comment by lionsoft** [comment]
обновил `far2l` - заработало! Спасибо.
