### ISSUE TITLE
Не корректно отображается размер папки по Ctrl + Q

### ISSUE THREAD

**Issue by shubaly-oleg** [elfmz/far2l#1917]
Не корректно отображается размер папки по Ctrl + Q
FAR2L 2.5.3-660ca38-beta GUI
Ubuntu 23.10
Скрины во вложениях.
![Screenshot 1](https://github.com/elfmz/far2l/assets/16194564/82860d53-5635-44cc-9028-8753a6f25e8b)
![Screenshot 2](https://github.com/elfmz/far2l/assets/16194564/3a1751d2-c4c4-40bf-aff9-40b9b0837826)

**Comment by default-writer** [comment]
А мне кажется, у тебя проблемы, потому что у всех всё работает.

**Comment by default-writer** [comment]
![image](https://github.com/elfmz/far2l/assets/383256/29054f16-d79d-4751-b962-5349ad44af0e)
![image](https://github.com/elfmz/far2l/assets/383256/b082fb00-631c-4e52-8971-b2eb51967435)

in general, foder size for folder with single file with size of 4 bytes:

files size = file size + cluster size

**Comment by default-writer** [comment]
> Не корректно отображается размер папки по Ctrl + Q FAR2L 2.5.3-660ca38-beta GUI Ubuntu 23.10 Скрины во вложениях. ![Screenshot 1](https://user-images.githubusercontent.com/16194564/284321005-82860d53-5635-44cc-9028-8753a6f25e8b.png) ![Screenshot 2](https://user-images.githubusercontent.com/16194564/284321066-3a1751d2-c4c4-40bf-aff9-40b9b0837826.png)

files size = file size + cluster size

**Comment by elfmz** [comment]
Дело в том что в CtrlQ добавляется и размер самой директории (хотя в Folders count он не учитывается) от того эти дополнительные 4кб

**Comment by elfmz** [comment]
Сложно сказать надо ли включать размер корневой директории, но если что в настройках есть опция которая позволяет вообще не включать размер директорий в CtrlQ - Use only file size in estimation:
![image](https://github.com/elfmz/far2l/assets/20957349/3dc9bd7d-7ff5-4308-bed3-775068ebc572)

**Comment by shubaly-oleg** [comment]
Спасибо!

нд, 17 груд. 2023 р. о 23:25 elfmz ***@***.***> пише:
