### ISSUE TITLE
Switching encoding breaks syntax highlighting

### ISSUE THREAD

**Issue by faerot** [elfmz/far2l#1918]
When switching from 1-byte encoding to utf-8 in editor, it jumps scroll to the beginning of the file and breaks syntax highlight:

![изображение](https://github.com/elfmz/far2l/assets/5680342/28cd4c07-37f9-4330-b2d0-6235a1a71c49)

Happens both in GUI and in TTY

**Comment by akruphi** [comment]
This is a real inconvenience with Colorer also for me.

Workaround: far2l remembers the codepage for recently opened files, so after changing the encoding it is enough to close and reopen the file.
