### ISSUE TITLE
consider using PackPack technology to build .deb and .rpm packages

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#193]
https://github.com/packpack/packpack

> PackPack is a simple tool to build RPM and Debian packages from git repositories:
> - Fast reproducible builds using Docker containers
> - Semantic versioning based on annotated git tags
> - Support for all major Linux distributions as targets

> PackPack works best with GitHub, Travis CI and PackageCloud:
> - Push your code to GitHub
> - Build packages using Travis CI
> - Host repositories on PackageCloud
>

**Comment by elfmz** [comment]
..PackageCloud wants money

**Comment by cycleg** [comment]
CPack же! Вот вариант для сборки DEB-пакета, со строки 71.

[CMakeLists.txt](https://github.com/elfmz/far2l/files/577867/CMakeLists.txt)

В таком виде с пакетом есть две проблемы:

1. Зависимости от других пакетов (CPACK_DEBIAN_PACKAGE_DEPENDS). Сейчас указаны почти от балды. Это надо пилить под реальные зависимости far и конкретные выпуски ОС.
2. Те символические ссылки, которые делаются сейчас через `install(CODE`. По уму их создание и удаление нужно поместить в соответствующие пакетные сценарии. Например, для DEB это будут "postinst" и "prerm".

Ну и нужно делать выбор генератора пакета в зависимости от целевой ОС. В этом сценарии такого нет: жестко прописан DEB, строки 114-119.

**Comment by unxed** [comment]
Наверное, про CPack лучше в #84, а этот закрыть?

**Comment by cycleg** [comment]
О, проглядел. Скопировал свой комментарий туда.

**Comment by unxed** [comment]
> PackageCloud wants money

WONTFIX
