### ISSUE TITLE
Feature: Alt+F1/F2 -> F9

### ISSUE THREAD

**Issue by izzylaif** [elfmz/far2l#1933]
Можно ли добавить помимо exceptions еще и обязательный include?
Btw рач монтирует съемные диски и прочие флешки в /run/media/ЮЗЕРНЕЙМ/имя_флешки/
при текущей строке исключается весь /run что правильно потому что там куча мусора, но флешки тоже выпадают

**Comment by spnethw** [comment]
Наверное, это будет излишним усложнением функционала.
Вариант решения: убрать из исключений `/run/*` и явно добавить в исключения мешающий "мусор" типа `/run/user/*`

**Comment by izzylaif** [comment]
> Наверное, это будет излишним усложнением функционала.

Согласен. Но тогда не очень понятно как выйти из следующей ситуации.
На раче захардкожены следующие точки монтирования:
- стационарные диски монтируются в /mnt как у нормальных людей, и в фаре они видны по Alt-F1/2
- однако сменные диски (usb флешки и тп) монтируются в /run/media/[пользователь] и разумеется путь разный для каждого юзера

В Фаре сейчас в F9 стоят исключения на /run;/run/*; и если эти исключения убрать, по Alt-F1/2 виден вообще весь мусор что есть в run например run/user/100 и тп

Как сделать так, чтобы флешки монтированные в /run/media/[user] таки были видны причем вне зависимости от текущего пользователя?
может какой-то симлинк?

**Comment by spnethw** [comment]
@izzylaif можно закрыть, наверное?

**Comment by izzylaif** [comment]
> @izzylaif можно закрыть, наверное?

Да.
Для истории, 
дефолт
`/System/*;/proc;/proc/*;/sys;/sys/*;/dev;/dev/*;/run;/run/*;/tmp;/snap;/snap/*;/private;/private/*;/var/lib/lxcfs;/var/snap/*;/var/spool/cron;/tmp/.*`
наговнякал 
`/run;/run/user;/run/user/*;/home;/home/*;/boot;/boot/*;/System/*;/proc;/proc/*;/sys;/sys/*;/dev;/dev/*;/tmp;/snap;/snap/*;/private;/private/*;/var/lib/lxcfs;/var/snap/*;/var/spool/cron;/tmp/.*`
вроде попустило
