### ISSUE TITLE
Highlighting in plugin panels

### ISSUE THREAD

**Issue by shmuz** [elfmz/far2l#1939]
Если панельный плагин не устанавливает флаг `OPIF_USEHIGHLIGHTING`, то независимо от текущего значения опции "Highlight files" файлы должны быть раскрашены по умолчанию (так, как при сброшенной опции "Highlight files").
Так оно когда-то и было, но с определённого момента стало так, как на картинке ниже.

Чтобы это повторить (на примере плагина  TmpPanel), нужно в файле TmpClass.cpp закомментировать добавление `OPIF_USEHIGHLIGHTING`, сохранить файл и пересобрать плагин.

![image](https://github.com/elfmz/far2l/assets/344558/39873c5c-ef7e-42fd-a52b-07378e96baf0)

**Comment by elfmz** [comment]
А сейчас нормально стало?

**Comment by shmuz** [comment]
Да, сейчас хорошо.
