### ISSUE TITLE
Перезапись файлов без предупреждения, хотя в настройках указано "Спросить"

### ISSUE THREAD

**Issue by msukhov** [elfmz/far2l#1943]
Файл перезаписывается без предупреждения, если у пользователя есть права на запись файла. То есть настройка "Спросить" не учитывается в данном случае, хотя логично было бы учитывать.

Версия 2.5.3-beta Linux x86_64
![0001](https://github.com/elfmz/far2l/assets/6313693/db0949a9-d160-43db-9b5d-af8ed197093f)
![0002](https://github.com/elfmz/far2l/assets/6313693/a84ec2f0-9fba-4191-961c-3a4bedf0b5a9)

**Comment by akruphi** [comment]
Это наблюдается если глобально в F9->Options->Confirmations выключены предупреждения для
`
[ ] Copy
`
согласно обработке условия в https://github.com/elfmz/far2l/blob/75078455c7b943ce9f4acd8e973b4f51910281c1/far2l/src/copy.cpp#L2995

Такое же поведение у виндовского far3.

Это действительно не интуитивно :exploding_head:.

Возможно при глобальном выключении предупреждений в исходном окне копирования в выборе **Already existing files** принудительно ставить **Overwrite** и не позволять его менять?
Как Вы за такой вариант проясняющего костыля или есть более удачные идеи?

**Comment by msukhov** [comment]
По-моему да, так логичнее будет. Другого более удачного варианта пока не могу придумать.

**Comment by akruphi** [comment]
Код с таким костылём приняли в master. @msukhov, проверяйте насколько теперь это более внятно.

**Comment by elfmz** [comment]
ну я закрою, если что переоткрыть всегда можно
