### ISSUE TITLE
NetRocks sites list - editor stopped working

### ISSUE THREAD

**Issue by atolismesh** [elfmz/far2l#1949]
far2l - latest build on Ubuntu 23.10 (Manjaro, Debian ...)  2.5.3-2024-01-02-ddf183b0-beta Linux x86_64
Перестал работать вызов редактора в списке сайтов NetRocks.
При нажатии F4 (на клавиатуре или мышкой) ничего не происходит.
Должен открываться редактор соединения. 
Просьба поправить.

**Comment by unxed** [comment]
У меня тоже

**Comment by atolismesh** [comment]
@elfmz 
git bisect показывает, что 
6c46c58788763c899feeaa996446ab13f3d58d84 is the first bad commit
commit 6c46c58788763c899feeaa996446ab13f3d58d84
Author: elfmz <fenix1905@tut.by>
Date:   Tue Jan 2 16:20:38 2024 +0300

    redefine EXTENDED_KEY_BASE to accomodate UTF32 chars range (touch #1947)

**Comment by unxed** [comment]
В FTP плагине тоже F4 не работает. А вот в tmppanel работает.
