### ISSUE TITLE
is there any way to hide/ignore some files on the screen, like .DS_Store?

### ISSUE THREAD

**Issue by lucasfellipe3g** [elfmz/far2l#1950]
hello!

i would like if is there any way to hide/ignore some files on the screen, like .DS_Store?

for example:

![CleanShot 2024-01-02 at 17 46 51@2x](https://github.com/elfmz/far2l/assets/128543119/0bc60477-5d32-450f-8bb9-107087d1effa)

hide/ignore .DS_Store file. thanks!

**Comment by atolismesh** [comment]
Ctrl+H ?

**Comment by lucasfellipe3g** [comment]
interesting, thanks!!! but I wanted something to hide only some file types. is there any way?

**Comment by lucasfellipe3g** [comment]
> You can use F9->Commands->**File panel filter Ctrl-I**. By **Ins** add new filter with mask `*.DS_Store`, then in **Filters menu** by gray (numpad) minus **-** activate it for _not processing_ such files in panels, then by **Enter** apply changes (details see in help by **F1**).
> 
> Do not forget F9->Options->**Save setup Shift-F9** to save it for new far2l launches.

oh, thank u so much!
