### ISSUE TITLE
NetRocks - please make displaying of symbolic links like in the local file system

### ISSUE THREAD

**Issue by atolismesh** [elfmz/far2l#1952]
NetRocks - сделайте пожалуйста отображение симлинков в нижней статус панели и при нажатии Ctrl-A, как при отображении локальных файлов. Чтобы было видно, куда ссылается симлинк.
Сейчас в NetRocks симлинки при соединении scp:, shell:, etc  обображаются как 
![image](https://github.com/elfmz/far2l/assets/130924690/5d0cab6c-3c04-4789-bb7d-479563312fe5)
а в локальной FS как 
localtime -> /usr/share/zoneinfo/.....

**Comment by elfmz** [comment]
проблемка в том что во многих протоколах это замедлит отображение директорий с симлинками..

**Comment by akruphi** [comment]
Также в NetRocks по Ctrl-A отдельной строкой хорошо бы показывать текущее значение симлинка (редактирование как в локальном Ctrl-A не обязательно, вполне будет удобно только показывать на что ссылается симлинк).

**Comment by elfmz** [comment]
хотя можно расширить плагиновый апи, добавив ф-ю типа GetLinkTargetW и вызывать ее по мере необходимости (при навигации курсором) тогда тормоза будут тоже... по мере необходимости

**Comment by shmuz** [comment]
> хотя можно расширить плагиновый апи

А уже имеющаяся функция `FSF.GetReparsePointInfo` не подойдёт?

**Comment by elfmz** [comment]
Так она же так сказать не в ту сторону работает. Надо чтобы фар спрашивал плагина о том куда смотрит симлинк.

**Comment by atolismesh** [comment]
Мне запомнилось, что когда начинали с добавлением fish/shell в NetRocks, был вариант когда в remote.sh вызывался `ls -a -l` и симлинки передавались с хоста.

**Comment by elfmz** [comment]
Ну речь не просто про тормоза, а про то что когда открываешь дир с 10000 файлов то есть разница - откроется на 3 сек или за 5 например.
Кроме того, в стандартном плагиновом апи нету возможности указывать путь симлинка в листинге, так что по любому расширять надо.

**Comment by unxed** [comment]
Делать выключенной по умолчанию?

**Comment by elfmz** [comment]
Не надо настроек, вобщем добавил GetLinkTargetW - вроде работает

**Comment by atolismesh** [comment]
Yes! Работает и в shell и в scp.	
Это магия!
Спасибо!

**Comment by elfmz** [comment]
про ctrl-a чет забыл, но думаю получится

**Comment by akruphi** [comment]
С нетерпением жду Ctrl+A - внизу панели часто длинные цели симлинков не помещаются и прокручиваемое поле в Ctrl+A тут предпочтительнее.

Также, после добавления fish/shell, в помощи NetRocks имеет смысл везде увеличить версию с
```
       Version 1.0
Copyright (C) 2019 elfmz
```
на **2.0** или хотя бы **1.1**.

**Comment by atolismesh** [comment]
Ctrl+A проверил (scp:, shell:). 
Супер! Спасибо
