### ISSUE TITLE
how to remove this * from the `n` character?

### ISSUE THREAD

**Issue by lucasfellipe3g** [elfmz/far2l#1954]
how to remove this * from the `n` character? i don't know how i did it
![CleanShot 2024-01-03 at 20 59 10](https://github.com/elfmz/far2l/assets/128543119/9ebfbd6b-e844-4f3c-951a-df9684baed45)

**Comment by lucasfellipe3g** [comment]
in fact, some files are missing...

![CleanShot 2024-01-03 at 21 44 14](https://github.com/elfmz/far2l/assets/128543119/11885786-e5b8-4f8d-baac-3f2e561e6cf8)

**Comment by akruphi** [comment]
Asterisk * is marker that filter Ctrl-I applied in this panel.

If in Filters menu you mark items by **+** that only files appropriate with **+** filters shown in panel.
If in Filters menu you mark items by **-** in panel will be shown all files NOT satisfying these filters.
