### ISSUE TITLE
Editor Status Bar nonsignificant bug: attributes symbol (H) show only if cursor after end of line

### ISSUE THREAD

**Issue by akruphi** [elfmz/far2l#1956]
Для начинающихся с точки файлов в редакторе в строке статуса символ H показывается только,  если курсор за концом строки. При наличии же кода символа, символ атрибута файла похоже затирается.

Не критично, но как-то неаккуратно это, к тому же в windows и в far2 и в far3 такого бага нет.

Однако из кода, начиная с https://github.com/elfmz/far2l/blob/ff3ada067f010e15e01c7a56ae512f592db882b3/far2l/src/fileedit.cpp#L2264 сходу не соображу почему это происходит.

**Comment by elfmz** [comment]
Сейчас норм? (ну на предмет не поломалось ли что тоже стоит посмотреть внимательно)

**Comment by akruphi** [comment]
Ого! Какой большой фикс потребовался!
Вроде всё основное работает адекватно, но при включенных часах код символа теперь впритык к времени. Хорошо бы при возможности разделить основной текст строки статуса и часы двумя-тремя пробелами.

**Comment by elfmz** [comment]
Фикс большой просто чтоб уменьшить количество зарардкоденных констант. Пробел добавил

**Comment by akruphi** [comment]
Спасибо большое.

Теперь забавный пробел между основным статусом и часами
![изображение](https://github.com/elfmz/far2l/assets/92621645/5cd5cecf-14d8-4af4-9d44-eef36fcb542f)
но возможно это полезная фича - сразу выделять часы в отличии от сплошной строки виндовских прорадителей.

**Comment by elfmz** [comment]
я уже исправил эту фичу), хотя тоже была мысль что можно оставить такой разделитель

**Comment by akruphi** [comment]
Теперь часы слишком близко к коду символа и их быстро взглядом не выделишь.
![изображение](https://github.com/elfmz/far2l/assets/92621645/6d5545f2-a264-44cc-8ed1-9f871c1ac3b3)

Специально залез на старую windows виртуальку с far2 посмотреть какие там интервалы - там разделитель основной части статуса и часов 7 символов:
![изображение](https://github.com/elfmz/far2l/assets/92621645/0f1d729e-ef2f-45d3-8b14-941481773d84)

В far2l хорошо бы тоже хотя бы 5 символов.

**Comment by elfmz** [comment]
затратно както, уж лучше разделителем каким нить в самом деле особенным

**Comment by akruphi** [comment]
> затратно както, уж лучше разделителем каким нить в самом деле особенным

Ну в windows far3 разделителями всё как-то излишне обложено
![изображение](https://github.com/elfmz/far2l/assets/92621645/c4ff272e-a970-46e2-baec-6805d3927bd1)
хотя идея поставить `|` между основным статусом будет неплохим итогом.

**Comment by elfmz** [comment]
Ну вот ща вернул 'фичу', но в более культурном виде, как оно?

**Comment by akruphi** [comment]
Норм. Спасибо большое.
Сорри, что отвлёк на этот слабозначащий баг со строкой статуса так много усилий.
