### ISSUE TITLE
Errors after Far close

### ISSUE THREAD

**Issue by SerjCh** [elfmz/far2l#196]
![screenshot from 2016-11-08 00-09-12](https://cloud.githubusercontent.com/assets/19835749/20078162/261a7ba0-a548-11e6-8435-3d3379599682.png)

![screenshot from 2016-10-27 15-51-07](https://cloud.githubusercontent.com/assets/19835749/20078201/4a1bab82-a548-11e6-8a6a-b9b78a6ea2c5.png)

**Comment by elfmz** [comment]
is it something new (degradation) or was before?
also is it reproducible?

**Comment by SerjCh** [comment]
first screen - current
second - old (27.10)
sometimes happens, dunno how to reproduce

**Comment by elfmz** [comment]
also what did you use to close far2l - window's close button or F10?

**Comment by SerjCh** [comment]
F10 mostly, this not often happens

**Comment by elfmz** [comment]
check with recent changes - see if it will happen again or not (during reasonable time)

**Comment by SerjCh** [comment]
w/o autoindent plugin i'm not using far2l constantly yet :) but will try to check sometimes

**Comment by unxed** [comment]
> w/o SimpleIndent plugin i'm not using far2l constantly yet :)

f1cf80db1b47682a57138a89b0f347d0ca6721ca

**Comment by elfmz** [comment]
reopen if still repro with latest..
