### ISSUE TITLE
Copy/Paste for vertical blocks not working in editor when using PuTTY

### ISSUE THREAD

**Issue by faerot** [elfmz/far2l#1965]
When connected remotely, blocks selected using Alt+Arrows in editor does not copy text for some reason. Blocks selected with Shift+Arrows work fine. The same version works fine under Ubuntu when using directly both in normal mode and in forced --tty mode.

I am using patched version PuTTY-far2l-SCE-x64-0.78.5

**Comment by akruphi** [comment]
May be this issue you should write in https://github.com/ivanshatsky/putty4far2l/ ?

**Comment by unxed** [comment]
known problem. I'm not sure I understand exactly how to fix it

**Comment by faerot** [comment]
Tried "normal" PuTTY and it works there. Looks like it's a problem with PuTTY fork then, sorry. Resubmitted there.
