### ISSUE TITLE
Систематические падения при переключении кодировки в редакторе при выделенном тексте

### ISSUE THREAD

**Issue by ru-vsu-cs-course1** [elfmz/far2l#1968]
При попытке переключить кодировку в редакторе по F8 при каком-то выделенном тексте far2l падает.
Но не всегда, каждый второй/третий раз.
Ошибка воспроизводится, как минимум в 2-х системах (Ubuntu 20, LXC-контейнер на другой машине с Debian 10) на разных сборках (собранная из исходников, установленная с ppa, скачанная portable).
![изображение](https://github.com/elfmz/far2l/assets/63755490/1261e02e-2747-4f7c-afb0-e176a9085dad)
Cтабильно воспроизводится, если открыть любой файл и чередовать нажатия Ctrl+A и F8.

**Comment by elfmz** [comment]
полагаю пофикшено? закрываю
