### ISSUE TITLE
How to change the color of the directories?

### ISSUE THREAD

**Issue by pommesfritz123** [elfmz/far2l#1969]
Hello dear friends,

I want to change the white color of the directories in far2l on linux into the same color as the common files are (a kind of blue).
Please tell me, how this is possible.
Maybe a single entry-change in an .ini-file could help?!

Thanks in advance!

Best regards,
pommesfritz123

**Comment by akruphi** [comment]
F9->**Options**->**Files highlighting and sort groups**, then select items with `D+` (directory) and inside each you can change colors (usually only change in 1, others 2..8 has default colors "black on black").

**Comment by pommesfritz123** [comment]
Thank you a lot, pal!
It worked perfectly!
Have a nice day!
