### ISSUE TITLE
Need to use password to get home directory

### ISSUE THREAD

**Issue by SerjCh** [elfmz/far2l#197]
![screenshot from 2016-11-08 12-01-43](https://cloud.githubusercontent.com/assets/19835749/20094716/2b8c49fc-a5ab-11e6-811b-35e89b18d5fa.png)

**Comment by elfmz** [comment]
what mean 'get home directory'?

**Comment by SerjCh** [comment]
if just go to my home directory /home/serj/, or store settings that home will be default on the left/right panel

**Comment by unxed** [comment]
![_002](https://cloud.githubusercontent.com/assets/1151423/20095784/f8407d86-a5b7-11e6-808f-a28c2c47b2bc.png)
![_003](https://cloud.githubusercontent.com/assets/1151423/20095783/f8405126-a5b7-11e6-93c8-7bdeffaea8c6.png)

**Comment by elfmz** [comment]
hm. strange. can you open terminal and enter/ls it without sudo there?

**Comment by SerjCh** [comment]
`l -la
ls: cannot access '.gvfs': Permission denied
d?????????   ? ?    ?        ?            ? .gvfs/`
may be this? sudo ls all ok

**Comment by elfmz** [comment]
may be.. interesing how to reproduce it. May be its a symlink that can't be queried, not sure how to create such link, but if it cannot be queried without far2l - then requesting root is logical, otherwise it would be 'unknown' entry in file list.

**Comment by SerjCh** [comment]
yep, that's it, i rebooted & rm -rf ~/.gvfs, all ok now
