### ISSUE TITLE
вставляется лишний символ \

### ISSUE THREAD

**Issue by beliytip** [elfmz/far2l#1972]
При использовании клавиш ctrl+j или shift+enter  имена файлов и папок в которых есть пробелы вставляются с символом '\'.  Например имя файла  "read me file.txt" вставится  как "./read\ me\ file.txt".

**Comment by akruphi** [comment]
Это фича (к сожалению не настраиваемая). Так экранируются специальные символы (не только пробелы), что бы в командной строке bash они понялись.

Для копирования в буфер обмена без добавления экранирования используйте имя файла - **Ctrl-Ins**, полный путь - **Ctrl-Alt-Ins**.
