### ISSUE TITLE
far2l does not start properly on i386 (was: build problems on i386)

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#198]
```
[ 72%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/APISynch.cpp.o
/home/unxed/far2l/far2l/WinPort/src/APIRegistry.cpp: In function ‘LONG RegValueDeserialize(const string&, const string&, LPDWORD, LPBYTE, LPDWORD)’:
/home/unxed/far2l/far2l/WinPort/src/APIRegistry.cpp:272:2: error: static assertion failed: bad DWORD64 size
  static_assert(sizeof(DWORD64) == sizeof(long unsigned int ), "bad DWORD64 size");
  ^
/home/unxed/far2l/far2l/WinPort/src/APIRegistry.cpp: In function ‘void RegValueSerialize(std::ofstream&, DWORD, const BYTE*, DWORD)’:
/home/unxed/far2l/far2l/WinPort/src/APIRegistry.cpp:348:2: error: static assertion failed: bad DWORD64 size
  static_assert(sizeof(DWORD64) == sizeof(long unsigned int ), "bad DWORD64 size");
  ^
At global scope:

```

**Comment by elfmz** [comment]
how its now?

**Comment by unxed** [comment]
now builds, but refuses to work:
![_001](https://cloud.githubusercontent.com/assets/1151423/20117280/e7e52e38-a610-11e6-8f40-355a23e90742.png)

and that's all

**Comment by unxed** [comment]
console log:

`g_strFarModuleName='/home/unxed/far2l/build/install/far2l' (argv[0]='./far2l')
WinPortInitRegistry: OK 
InitializeFont: used Ubuntu Mono 16
Font 11 x 21: 'Ubuntu Mono' - monospaced stable
OnInitialized: client size = 394 x 404
OnConsoleResized client size: 880 525
CheckForResizePending
Current client size: 880 525 font 11 21
OnKillFocus
OnKillFocus
GenerateConsoleCtrlEvent(2) - exiting
`

**Comment by unxed** [comment]
:)

![_001](https://cloud.githubusercontent.com/assets/1151423/20117648/8cd6d4e0-a612-11e6-82d9-df23c5deaf36.png)

**Comment by elfmz** [comment]
looks like missing or empty .lng files

**Comment by unxed** [comment]
.lng's are present. looks like usual. sample:
[lng.zip](https://github.com/elfmz/far2l/files/579440/lng.zip)

**Comment by elfmz** [comment]
strange, some time ago I used it on rpi that is arm, besides of 32 bit..

**Comment by unxed** [comment]
may I do something to help figure out the reason?

**Comment by elfmz** [comment]
did you cross-compile for i386 or compiled it natively? If first - how you fixed glib compilation = I can't compile due to some problem with glib (even having installed apt-get install libglib2.0-dev:i386) :
[  0%] Building CXX object utils/CMakeFiles/utils.dir/src/KeyFileHelper.cpp.o
In file included from /usr/include/glib-2.0/glib/galloca.h:32:0,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /home/user/projects/far2l/utils/src/KeyFileHelper.cpp:6:
/usr/include/glib-2.0/glib/gtypes.h:32:24: fatal error: glibconfig.h: No such file or directory
compilation terminated.

**Comment by unxed** [comment]
native, in virtualbox VM

**Comment by unxed** [comment]
confirming working.
