### ISSUE TITLE
Files and folders in RAR and 7z archives are erroneously highlighted as char devices

### ISSUE THREAD

**Issue by sirburpalot** [elfmz/far2l#1980]
How to reproduce the issue for 7z archives:

```
touch 1 2 3
7z a test.7z 1 2 3
```
<img width="1114" alt="Screenshot 2024-01-27 at 22 19 31" src="https://github.com/elfmz/far2l/assets/1429516/0d718f5e-4df1-4d64-94f5-209b1434dac4">

In order to reproduce the issue for RAR archives, you need an archive created on Win32 or MS-DOS, as opposed to UNIX. Here's an example of an affected archive: https://github.com/ssokolow/rar-test-files/raw/master/build/testfile.rar3.rar

**Comment by akruphi** [comment]
С 7z исправилось.

Для RAR не пофикшено: 
![изображение](https://github.com/elfmz/far2l/assets/92621645/16b12b88-23bf-4eed-921c-18f8e76278ee)
