### ISSUE TITLE
Advanced Compare Crash

### ISSUE THREAD

**Issue by akruphi** [elfmz/far2l#1982]
На свежей версии 2.5.3-2024-01-28-9a7fbddd вызов `F11 - Advanced compare` приводит к PANIC PANIC PANIC.

**Comment by elfmz** [comment]
у меня не падает, может там не все пересобралось? make clean не помогает?

**Comment by akruphi** [comment]
PANIC PANIC PANIC не сразу при вызове плагина, а уже при попытке произвести сравнения.

Собиралось на чистую в пустой каталог build. Сейчас пересобрал (снова на чистую) последнюю 2.5.3-2024-01-28-4899c276 - падает при попытке произвести сравнения любых каталогов.

**Comment by elfmz** [comment]
А ну да..
```
	HANDLE hConOut = CreateFile(_T("CONOUT$"), GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING, 0, NULL);
	CONSOLE_SCREEN_BUFFER_INFO csbiNfo;
	if (GetConsoleScreenBufferInfo(hConOut, &csbiNfo)) {

```

**Comment by elfmz** [comment]
ща все норм стало?

**Comment by akruphi** [comment]
А зачем там вообще `hConInp` и `hConOut`?

**Comment by elfmz** [comment]
Ну в оригинальной виндовой версии открывали хэндл на консоль и с ней работали.
В WinPort все по другому - до недавнего времени этот хэндл игнорировался, а теперь используется.

**Comment by akruphi** [comment]
Судя по коду `hConOut` сейчас вообще не нужен, а `hConInp` лишь для сравнения на `INVALID_HANDLE_VALUE`.

**Comment by elfmz** [comment]
ну я просто минимально поменял
