### ISSUE TITLE
Mouse event codes

### ISSUE THREAD

**Issue by garciaaa** [elfmz/far2l#1984]
This strange and rare problem appeared only under Far2L, i succesfully tried several terminal programs with no errors.
Error occured in python TUI application, when it started from Far (Linux Mint, Cinnamon). You need to click mouse on TUI control (possibly several times) that prodices this python error:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 4: invalid start byte
```
Numbers may vary.
Here is that popular crossplatform python TUI framework used: [Textual](https://textual.textualize.io/)
It have "linux_drive.py" module, for input handling, that imports "codecs" standard module and tries to deal with mouse events buffer with utf-8 codec. It works everywhere instead of Far.

This minimal example can be used to reproduce (installing "textual" python package required):
```
from textual.app import App
from textual.widgets import Button

class MyApp(App):
    def compose(self):
        yield Button()

MyApp().run()
```
No wonder I couldn't find any mention of such a bug in Textual rep, but it is strange, that other TUI app with mouse have no problem with Far2l. Or i just can't find any mention?

**Comment by elfmz** [comment]
Its because python requests mouse events reporting in a format that far2l doesnt support, instead far2l sends what it supports, but python doesnt support that :)
![image](https://github.com/elfmz/far2l/assets/20957349/e14cd79a-3827-4587-aaf4-1a31a1373b05)
here SET_SGR_EXT_MODE_MOUSE is what far2l is missing

**Comment by garciaaa** [comment]
Так, я так понял это XTerm-овские escape команды, которые переключают вывод событий мыши на "расширенный" режим? То есть, единственный правильный путь чтобы все работало - выдернуть реализацию такого вывода из XTerm и засунуть в far2l VT?
Такое не планируется? Я глянул в XTerm - там вроде немного (функции MouseLimit, EmitMousePosition, EmitMousePositionSeparator, EndExtend, EmitButtonCode, EditorButton (?). Не достаточно ли в VT добавить детекцию новых опций и скопипастить условия вывода и сам расширенный вывод из XTerm в VTMouse::OnInputMouse? Сильно не бейте, просто фар - моя IDE-ха для маленьких проектов

**Comment by elfmz** [comment]
> Такое не планируется?

Сделаю, чо. Вроде несложно.

**Comment by elfmz** [comment]
проверяйте..

**Comment by garciaaa** [comment]
Это был самый быстрый багфикс за всю историю наблюдений. Все заработало вроде. Far2l становится для меня вещью, без которой я уже не могу.
