### ISSUE TITLE
dereference symlinks in bottom panel as mc does

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#199]
![_004](https://cloud.githubusercontent.com/assets/1151423/20116717/6fc12760-a60e-11e6-951a-d7e6797ddabc.png)
![_005](https://cloud.githubusercontent.com/assets/1151423/20116716/6fbf99ea-a60e-11e6-9fde-0249c01df7d3.png)

**Comment by elfmz** [comment]
implemented in https://github.com/elfmz/far2l/commit/d8f2af21a911a4cd32b9c65897842c66bc8c30d3
