### ISSUE TITLE
Colorer schemes update

### ISSUE THREAD

**Issue by akruphi** [elfmz/far2l#1994]
https://github.com/colorer/Colorer-schemes was recently updated.

Please update it in far2l.

**Comment by elfmz** [comment]
..if it will appear compatible with current far2l's colorer version

**Comment by elfmz** [comment]
Обновил, если есть что проверить что там было пофикшено - проверяйте. Все несколько осложнилось тем что в самом far2l были свои личные изменения в базе колорера.

**Comment by akruphi** [comment]
Спасибо.
А с чем связаны накопившиеся расхождения far2l и Colorer-schemes? Если было что-то полезное, то их может в Colorer-schemes заслать?

**Comment by elfmz** [comment]
Во-первых были добавлены много ключевых слов. Надо кстати проверить вдруг их добавили и в свежие схемы колорера и убрать дубликаты...
Во-вторых была добавлена своя true-color схема, так как ни одна из имеющихся не устраивала.

**Comment by ctapmex** [comment]
вчера залил классный PR по поддержке bash/sh скриптов. Для far2l точно надо

**Comment by ctapmex** [comment]
залил в основную ветку большую часть изменений из схем far2l. Что не трогал

- изменения лицензий. 
- пометку nullptr в c++ отдельным цветом
- hrd . даже если его и залить, то он не будет default
