### ISSUE TITLE
F7 dialog in Help defective now

### ISSUE THREAD

**Issue by akruphi** [elfmz/far2l#1995]
F7 dialog in Help defective now
![изображение](https://github.com/elfmz/far2l/assets/92621645/c97dc3cb-f915-4ba2-9b59-705ff03805c1)

**Comment by shmuz** [comment]
На всякий случай:
https://github.com/shmuz/far2m/commit/9ff52922944a2f980f3b327bd932d0d92ddfc16f
https://github.com/shmuz/far2m/commit/cd1437abd8ce485d012b585bf7f322b485b5039e
https://github.com/shmuz/far2m/commit/0faa9cbdd3f47520cfb6811c131ab6700456b777

**Comment by akruphi** [comment]
Спасибо @shmuz за советы по исправлениям из far2m - очень помогли при осмыслении. В итоге в #1997 вроде получилось сделать не настолько сильно искажая логику изначальной идеи far в этом коде.
