### ISSUE TITLE
When NetRocks SCP opened on both panels sorts stop working like Ctrl+F5, Ctrl-F6

### ISSUE THREAD

**Issue by LanThrusteR** [elfmz/far2l#2000]
A bug: 
If you open NetBricks on both panels sorts like Ctrl+F5, Ctrl-F6 name, size stop working. You need at least one panel pointing to a local file system for the sorts to work.

**Comment by elfmz** [comment]
Not reproduced for me.. Need more details

**Comment by LanThrusteR** [comment]
> Not reproduced for me.. Need more details

1. Open SCP connections on both panels left and right
2. Press Ctrl+F3 : the sort by name works -> OK
3. Press Ctrl+F4 : the sort by extension works -> OK
4. Press Ctrl + F5 : the sort by extension is not working
5. Press Ctrl + F6 : the sort by size is not working

Ctrl + F5 & Ctrl + F6 are both ignored by Far2l (but works in Far under wine)
