### ISSUE TITLE
Ctrl+"\" behaviour

### ISSUE THREAD

**Issue by abcdenis** [elfmz/far2l#2010]
Hi,

Ctrl+"\\" on windows change pannel's current directory to the root of current drive.
On macos it goes to the root of system what is not useful.

It will be nice to have an option to control target dir of Ctl+\ shortcut:
- root of the system ("/")
- root of the current physical drive, e.g. "/Volume/NAME/"

Thank you.

**Comment by atolismesh** [comment]
I'am completely against it. 
I use this shortcut all the time.

@abcdenis 
You can change to the root of  physical drive using Alt+F1/F2

**Comment by faerot** [comment]
I use Ctrl+\ to go to root often too, very useful.

**Comment by dodo-16** [comment]
Опа на!
Тока заметил, что Ctrl+~ домой идёт!
День не зря пропал! 😸

**Comment by randolf** [comment]
> I use Ctrl+\ to go to root often too, very useful.

Me too.

**Comment by abcdenis** [comment]
Был FAR под винду с вполне определённым поведением.
Поведение изменилось при портировании под мак.
Все привыкли.
Тем, кто не привык, было бы удобнее старое виндовое поведение.
Можно ли сделать настройку вместо того, чтобы "мне нравится как сейчас, менять нельзя"?
Чтобы можно было поставить галочку или написать в конфиг, и Ctrl+\ ходил не в рут, а в корень текущего диска?
Спасибо.

**Comment by akruphi** [comment]
> Поведение изменилось при портировании
>  и Ctrl+\ ходил не в рут, а в корень текущего диска?

В отличии в DOS/Windows файловые системы unix/linux/mac не оперируют понятиями диск (см. https://ru.wikipedia.org/wiki/FHS ). На уровне простых вызовов перехода по файловой системе, например, консольной командой `cd /` переход в корень файловой системы и нет быстрого способа перейти именно к точке монтирования текущего "диска".

Для определения раздела монтирования текущего каталога в командной строке можно извратится через `df .` или `findmnt --target .`, но я не знаю, чтобы такое делалось за 1-2 команды системных вызовов из C++.

Поясните ваши use-cases перехода именно к точке монтирования раздела текущего каталога в рамках логики файловой системы *nix, когда такое полезно?

**Comment by spnethw** [comment]
Как упомянул [akruphi](https://github.com/akruphi), определить точку монтирования текущего каталога позволяют  df или findmnt. Поэтому можно, например, добавить в меню что-то типа
`cd "$(findmnt --noheadings --output TARGET --target .)"`
и назначить через макрос на этот пункт удобное кнопкосочетание (то же Ctrl-\\).

**Comment by abcdenis** [comment]
@akruphi 
Цель - использовать опыт, приобретенный ранее, не думая над этим.
У меня такие же внешние диски, как и на винде, поэтому я бы ожидал, что FAR будет работать аналогично - независимо от рассуждений о философии Юникса.

@spnethw 
Вот видите, а все говорят, что это не нужно :)

**Comment by akruphi** [comment]
Спасибо @spnethw за реализацию. Утянул ссылкой в https://github.com/akruphi/far2l/wiki почти в самый конец раздела Полезности.

**Comment by spnethw** [comment]
@abcdenis можно закрыть, наверное?

**Comment by abcdenis** [comment]
Да, конечно. 
Хотя мне лично галка в настройках бы не помешала.

**Comment by akruphi** [comment]
Теперь быстрый переход к точке монтирования по Ctrl-Alt-\ внутри far2l.
