### ISSUE TITLE
No octal File Permissions in NetRocks SCP

### ISSUE THREAD

**Issue by LanThrusteR** [elfmz/far2l#2011]
The file permissions dialog: 

1. Doesn't allow to set file permissions in octet like 0777
2. No quick search in Owner/Group drop-down - (the box doesn't accept key search/no quick filter) 

The idea is to find users/group in the drop-down lists fast. And be able to setup file permissions fast via octets.

**Comment by akruphi** [comment]
>     2. No quick search in Owner/Group drop-down - (the box doesn't accept key search/no quick filter)
> 
> The idea is to find users/group in the drop-down lists fast.

NetRocks dialog **Confirm change mode** has not Owner/Group drop-down.

If you about **Attributes** dialog in regular local directories, inside each drop-down lists after **Ctrl+Down** you can toggle to Filtering mode by **Ctrl-Alt-F** (see talks about it in #1971 and #2017 )
