### ISSUE TITLE
Suggesion: change Ctrl+Alt+F to just Ctrl+F

### ISSUE THREAD

**Issue by faerot** [elfmz/far2l#2014]
Now that I have learned about Ctrl+Alt+F in dialogs I am using it all the time, and it is awesome, however 3 keys feels like unnecessarily long hotkey. Is it possible to change search mode hotkey in dialogs from Ctrl+Alt+F to simply Ctrl+F? It would be easier to use and Ctrl+Alt+F will still work for those who don't know about the change.
Alternatively, maybe make this options somewhere? Since from my understanding this cannot be solved with macros.

**Comment by shmuz** [comment]
> Since from my understanding this cannot be solved with macros.
```
[KeyMacros/Menu/CtrlF]
DisableOutput=0x1
Sequence=CtrlAltF
```
