### ISSUE TITLE
FAR window size grows after saving setup

### ISSUE THREAD

**Issue by sharpMouse** [elfmz/far2l#2015]
After every setup saving, in the next launch of FAR in GUI mode via Ubuntu Dock, its window size increases slightly in both directions (until it reaches fullscreen). 

Please fix it.

System: Ubuntu 20.04. GNOME 3.36, Wayland session.

**Comment by atolismesh** [comment]
What version of far2l are you using?
This issue has already been fixed in #1654

**Comment by sharpMouse** [comment]
FAR2L, version 2.5.3-c8858b0-beta Linux x86_64

**Comment by atolismesh** [comment]
It's a bit strange, because the FAR2L version string from 13 Nov 2023 includes a date and looks like
FAR2L, version 2.6.0-2024-02-20-01956d09-beta Linux x86_64.
However, your commit "c8858b0" is dated 4 Feb 24.

And the issue I mentioned was fixed on 18 Jul 2023.

**Comment by sharpMouse** [comment]
I got it from "ppa:far2l-team/ppa".

**Comment by sharpMouse** [comment]
Now it's ok.
Thank you for help.
