### ISSUE TITLE
Inconsistent Macro behavior in dialogs

### ISSUE THREAD

**Issue by faerot** [elfmz/far2l#2017]
I have created the following macro to be able to enable Ctrl+Alt+F fast search in file attributes:
```
[KeyMacros/Dialog/CtrlDown]
DisableOutput=0x1
Sequence=CtrlDown CtrlAltF
```
However, it does not work every second time. 
When I select owner here:
![изображение](https://github.com/elfmz/far2l/assets/5680342/60f190c5-fc9c-4e77-8fc9-1dab4c63ce72)

And press Ctrl+Down, the menu opens with search mode enabled:

![изображение](https://github.com/elfmz/far2l/assets/5680342/0bcde766-1baf-4ae3-92d1-dd5667a6585e)

HOWEVER, if I press Esc and then press Ctrl+Down again, it opens WITHOUT search mode enabled:

![изображение](https://github.com/elfmz/far2l/assets/5680342/a9f89b3b-ed3d-4d0a-b069-36ccfe5ef22b)

When I press Esc and then Ctrl+Down again, it opens with search mode again, then without it, then with it, enabling it every other time.
This behavior is observed on per gui item, i.e. if I press Ctrl+Down on owner first and then switch to group and press Ctrl+Down on group, both work as expected, but if afterwards I switch back to owner and press Ctrl+Down for the second time, it opens without search mode.

**Comment by akruphi** [comment]
> However, it does not work every second time.

In dialog in each drop-down list far2l remember filtering state up to dialog close.

Your macros open drop-down list and toggle it to filtering mode, then after reopen this list it toggle off filtering mode.

**Comment by faerot** [comment]
Is it possible to solve it then? Is there an option to disable "remember filtering state"?

**Comment by shmuz** [comment]
> Is it possible to solve it then? Is there an option to disable "remember filtering state"?

I've just made a [commit](https://github.com/shmuz/far2m/commit/faddf56eac1cf5620ec87e8def7515a66ae1e13b) on far2m that prevents such remembering (just in case).

**Comment by faerot** [comment]
Awesome! Hopefully it will be merged upstream.

**Comment by akruphi** [comment]
> Awesome! Hopefully it will be merged upstream.

In far2l master now.
