### ISSUE TITLE
Netrocks ssh-rsa

### ISSUE THREAD

**Issue by Nikit** [elfmz/far2l#2018]
How to enable this algorithm on Netrocks?  

Enabling in sshd config doesn't help: https://unix.stackexchange.com/a/725731/483038
Manually, next is working for me: `ssh -oHostKeyAlgorithms=+ssh-rsa user@IP.IP.IP.IP`

**Comment by dodo-16** [comment]
Может из-за [этого](https://github.com/elfmz/far2l/issues/1978#issuecomment-1913282869)?

**Comment by akruphi** [comment]
> Я вроде раньше спрашивал, где можно логи Netrocks посмотреть (и как их включить). 

Про логи см. в https://github.com/elfmz/far2l/wiki/Running-far2l-with-debug-logging-enabled

**Comment by atolismesh** [comment]
1. Чтобы ssh-rsa заработал в SCP, SFTP, нужно в  свойствах соединения добавить его в Protocol Options:
![image](https://github.com/elfmz/far2l/assets/130924690/00b47229-dee8-4084-aaeb-4891198171e0)
2. Чтобы ssh-rsa заработал в shell, нужно стандартно донастроить ~/.ssh/config, добавив строчки типа:
Host 192.168.0.* 192.168.22.*
    HostkeyAlgorithms +ssh-rsa
    PubkeyAcceptedAlgorithms +ssh-rsa

3.  Либо, чтобы ssh-rsa заработал в shell, нужно как запасной вариант  поправить файл /usr/local/share/far2l/Plugins/NetRocks/plug/SHELL/ways.ini

**Comment by Nikit** [comment]
> Чтобы ssh-rsa заработал в SCP, SFTP, нужно в свойствах соединения добавить его в Protocol Options:

Спасибо! Так заработало — непонятки с терминологией.
