### ISSUE TITLE
problem with unzip

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#202]
![_002](https://cloud.githubusercontent.com/assets/1151423/20219357/1c292868-a83a-11e6-92fe-5e8176ff29af.png)

(don't worry about password on a screenshot, it's already expired :)

[PS_OUT.zip](https://github.com/elfmz/far2l/files/586050/PS_OUT.zip)

**Comment by elfmz** [comment]
for me works?
![image](https://cloud.githubusercontent.com/assets/20957349/20226785/8dde757e-a85a-11e6-83d5-688132e2bcbc.png)
..what I missed?
unzip: 
![image](https://cloud.githubusercontent.com/assets/20957349/20226810/ad11b488-a85a-11e6-9b4f-3ba64aa20ca9.png)

**Comment by unxed** [comment]
I found out that it happens if unpacking to folder owned by root, like /usr/local/share/ca-certificates/
