### ISSUE TITLE
How can I open a file with Far Manager editor using command line without launching a new instance of Far?

### ISSUE THREAD

**Issue by dodo-16** [elfmz/far2l#2021]
А как-то можно [тоже самое](https://superuser.com/questions/1774392/how-can-i-open-a-file-with-far-manager-editor-using-command-line-without-launchi
) у нас замутить? 😊 
Вот эта [гадость](https://discussions.apple.com/thread/8521818?=undefined&previousThread=8274655021&sortBy=best) достала просто конкретно уже... 😞

**Comment by akruphi** [comment]
В far2l с сентября присутствуют `edit:` и `view:` (см. в справке раздел "Special commands"), но работающие только в командной строке. А вам желательно их в меню (которое по F2) и в File associations прикрутить?

**Comment by dodo-16** [comment]
> но работающие только в командной строке. 

У меня что-то нету 2.5.2-beta Linux x86_64 под МАК ОС, 
Наверное только в 2.5.3?

> А вам желательно их в меню (которое по F2) и в File associations прикрутить?

Только в File associations.

**Comment by dodo-16** [comment]
Однако собрал 2.6.0-2024-02-22:
```
╔═══════════════════════════════════════════════ Help - FAR2L ════════════════════════════════════════════════╗
║                                          File and archive manager                                           ║
║                                2.6.0-2024-02-22-3fce1dfb-beta Darwin arm64                                  ║
║                   ©1996-2000 Eugene Roshal, ©2000-2016 FAR Group, ©2016-2024 FAR People                     ║
╟─────────────────────────────────────────────────────────────────────────────────────────────────────────────╢
```
Но вот справке раздел "Special commands" не могу найти...
Где он там примерно должен быть?
Или его уже переименовали?

**Comment by akruphi** [comment]
Я вчера сделал commit, который реализует ваше пожелание и позволяет использовать эти команды в User menu, File associations & Apply Command. Он пока висит непринятым среди https://github.com/elfmz/far2l/pull/2020

> Однако собрал 2.6.0-2024-02-22:
> 
> Но вот справке раздел "Special commands" не могу найти... Где он там примерно должен быть? Или его уже переименовали?

**F1** -> (если не на главной помощи то ещё и **Shift+F1** для перехода главную) -> "Help file index" и получаете в алфавитном порядке все разделы помощи. Также внутри справки по **F7** работает поиск.

Однако быстрее в командной строке вбить `far:about` Enter и уже оттуда по **F1**.

**Comment by akruphi** [comment]
Замержено в мастер. Пересобирайте far2l и проверяйте как оно работает.
