### ISSUE TITLE
Parentheses are not escaped when expanding !& special symbol

### ISSUE THREAD

**Issue by spnethw** [elfmz/far2l#2027]
Из tg-чата:
_при использовании метасимвола !& , для получения списка отмеченных файлов, если в именах файлов есть скобки - они не экранируются. Соответственно, при попытке использовать этот список в качестве параметра в команде - выдается ошибка из-за неэкранированных скобок. 
При использовании метасимвола !.! скобки экранируются._

добавлю, что !& и !.! ещё и в обработке пробелов различаются — первый берёт строку с пробелами в кавычки, второй экранирует пробелы.

**Comment by shmuz** [comment]
На всякий случай: https://github.com/shmuz/far2m/commit/3210b75a77bf51bec05b09c333a527fd67cc11f4

**Comment by elfmz** [comment]
пофикшено?

**Comment by spnethw** [comment]
> пофикшено?

пофикшено!!
