### ISSUE TITLE
make hotkeys independent of current keyboard layout

### ISSUE THREAD

**Issue by spnethw** [elfmz/far2l#2028]
С tg-чата:

_Можно ли сделать так, чтобы хоткеи не зависели от текущего языка? В частности, ctrl-`, который возвращает в домашний каталог._

У меня, например, при русской раскладке Ctrl-` не срабатывает, в командную строку "ё" пишет (far2l GUI, Arch, x11, KDE Plasma).

**Comment by sharpMouse** [comment]
Добавлю, как автор из tg-чата.

У меня Ctrl-` букву "ё" не пишет, но и не срабатывает, пока включена русская раскладка. 

Ubuntu 20.04, GNOME 3.36, Wayland, far2l GUI.

**Comment by sharpMouse** [comment]
Данный эффект не зависит от того, был ли запуск чистый или через env GDK_BACKEND=x11.

**Comment by akruphi** [comment]
У меня в Ubuntu 22.04 x11 GUI Ctrl+` и Ctrl+ё дают одинаковый эффект как и надо. Так, что тут именно особенность реализации клавиатуры+языков Wayland, возможно конкретной реализации Wayland.

Напомню, что под Wayland ещё и проблема буфера обмена https://github.com/elfmz/far2l/issues/1350#issuecomment-1443347317 , но этот глюк который по отзывам в тг-чате проявляется не на всех Wayland, т.е. тут странная привязка к конкретной реализации Wayland.

**Comment by akruphi** [comment]
@spnethw и @sharpMouse а какой у Вас язык первый в системе? У меня En, а Ru как второй и проблем с хоткеями нет при любой включенной раскладке нет. Может от порядка языков зависит? :exploding_head:

**Comment by sharpMouse** [comment]
>какой у Вас язык первый в системе?
English.
 
Кстати, теперь работает )) Версия 2.6.0, GUI.
 
 
—
Reply to this email directly,  view it on GitHub , or  unsubscribe .
You are receiving this because you were mentioned. Message ID:  <elfmz/far2l/issues/2028/2004517691 @ github . com>  
 

С уважением,
Василий Старостин.

**Comment by unxed** [comment]
Есть похожий баг, проявляющийся до сих пор. Но здесь же не о нём речь шла?
https://github.com/elfmz/far2l/issues/2124

**Comment by spnethw** [comment]
> > Кстати, теперь работает )) Версия 2.6.0, GUI.
> 
> Т.е. можно тикет закрывать?

Ну, у меня баг не ушёл. И откуда у него уши растут, непонятно.

**Comment by unxed** [comment]
Интересно как. У вас графическая версия же? Проверил ща на Mint 21.3, не воспроизводится.

У вас, кстати, иксы или вейленд?

**Comment by unxed** [comment]
Ещё может быть дело в версии wx. Там правили это

**Comment by spnethw** [comment]
Arch / x11 / KDE Plasma 6,  wxwidgets-gtk3 3.2.4

**Comment by unxed** [comment]
А другие шорткаты с Ctrl+буквами срабатывают в русской раскладке?

**Comment by spnethw** [comment]
Вроде бы только с ```ё```.

**Comment by unxed** [comment]
Поскольку у меня KDE под рукой нету, проблема рискует отложиться до никогда. Поэтому такое предложение: соберите у себя wxWidgets (это несложно) и демо keyboard (это тоже), запустите, нажмите `Ctrl`+`ё` в русской раскладке, и скиньте скрин (и ещё скрин окна где установленные в системе языки, чтоб их порядок видеть).

Потому что есть у меня предположение, что баг — в апстриме.

**Comment by spnethw** [comment]
Нажимается Ctrl-`, включена английская раскладка:

```event          key     KeyCode mod   UnicodeKey    RawKeyCode RawKeyFlags
   Hook         CONTROL   308   C---    0 (U+0000)    65507    0x00000025
   Hook             '`'    96   C---   96 (U+0060)       96    0x00000031
  KeyUp             '`'    96   C---   96 (U+0060)       96    0x00000031
  KeyUp         CONTROL   308   ----    0 (U+0000)    65507    0x00000025
```

Нажимается Ctrl-`, включена русская раскладка:
```event          key     KeyCode mod   UnicodeKey    RawKeyCode RawKeyFlags
   Hook         CONTROL   308   C---    0 (U+0000)    65507    0x00000025
   Hook             '`'    96   C---   96 (U+0060)     1699    0x00000031
  KeyUp             '`'    96   C---   96 (U+0060)     1699    0x00000031
  KeyUp         CONTROL   308   ----    0 (U+0000)    65507    0x00000025
```

Если в меню File приложения Keyboard выставить галочки "Skip CHAR_HOOK event" и "Skip KEY_DOWN event", вывод дополняется ещё несколькими строками.
При включенной английской раскладке:
```event          key     KeyCode mod   UnicodeKey    RawKeyCode RawKeyFlags
   Hook         CONTROL   308   C---    0 (U+0000)    65507    0x00000025
KeyDown         CONTROL   308   C---    0 (U+0000)    65507    0x00000025
   Hook             '`'    96   C---   96 (U+0060)       96    0x00000031
KeyDown             '`'    96   C---   96 (U+0060)       96    0x00000031
   Char             '`'    96   C---   96 (U+0060)       96    0x00000031
  KeyUp             '`'    96   C---   96 (U+0060)       96    0x00000031
  KeyUp         CONTROL   308   ----    0 (U+0000)    65507    0x00000025
```

При включенной русской раскладке:
```event          key     KeyCode mod   UnicodeKey    RawKeyCode RawKeyFlags
   Hook         CONTROL   308   C---    0 (U+0000)    65507    0x00000025
KeyDown         CONTROL   308   C---    0 (U+0000)    65507    0x00000025
   Hook             '`'    96   C---   96 (U+0060)     1699    0x00000031
KeyDown             '`'    96   C---   96 (U+0060)     1699    0x00000031
   Char             'ё'     0   C--- 1105 (U+0451)     1699    0x00000031
  KeyUp             '`'    96   C---   96 (U+0060)     1699    0x00000031
  KeyUp         CONTROL   308   ----    0 (U+0000)    65507    0x00000025
```

wxWidgets-3.2.4, та же, что и в системе, собиралось вручную по инструкции с офсайта.

**Comment by unxed** [comment]
Ой как интересно! Будто бы far2l хватает Char вместо KeyDown тут. Но да, проблема на нашей стороне. Дальше надо в код смотреть, это я прям ща не готов, но позже можно.
