### ISSUE TITLE
Add optional case-insensitive comparison of file masks

### ISSUE THREAD

**Issue by spnethw** [elfmz/far2l#2029]
Хорошо бы добавить опциональную возможность регистронезависимого сравнения имён файлов.
Пригодилось бы во многих диалогах -- и в пометке, и в настройках раскраски, и в поиске _(как это сделано в Midnight Commander,  например)._

Скажем, сейчас маски в настройках раскраски, предлагаемые "из коробки", не учитывают, что архив или исполняемый файл могут иметь расширения в верхнем регистре, и не подсвечивают их нужным образом. А такие имена не редкость, особенно для файлов, перекочевавших из Windows или DOS. 

Приходится каждый раз шаманить с регулярными выражениями, это, конечно, workaround, но регистронезависимый чекбокс сильно облегчил бы жизнь.

**Comment by elfmz** [comment]
Один общий чекбокс в настройках на все диалоги с масками пойдет? А то много их слишком, загромождать..

**Comment by spnethw** [comment]
Ну в идеале, конечно, хотелось бы иметь независимые чекбоксы хотя бы в трёх перечисленных выше кейсах.
Но если малой кровью, то да, хотя бы опцию в настройках такую предусмотреть.

**Comment by akruphi** [comment]
Учет регистра при **Сравнении папок** и пометке по **Gray+**/**-** теперь настраивается в `F9->Параметры->Настройки панели->[x] Учитывать регистр при сравнении или пометке`. Насколько объединение этих двух случаев в один чекбокс удобно? 

Для поиска наверное стоит свой отдельный чекбок уже внутри диалога по **Alt+F7** или как?

**Comment by spnethw** [comment]
> Насколько объединение этих двух случаев в один чекбокс удобно?

Могу говорить только за себя — мне это неудобств не доставляет (просто потому, что для сравнения папок обычно использую плагин Advanced Compare).
Хотя, конечно, семантически это разные операции, так что раздельные чекбоксы были бы логичнее.

Если наберётся достаточное кол-во операций с опциями для (не)учитывания регистра, можно потом вообще чекбоксы эти вынести в отдельный диалог настроек.




> Для поиска наверное стоит свой отдельный чекбок уже внутри диалога по **Alt+F7** или как?

Ну, в mc в поиске две отдельные галочки для этого, наверное, можно как-то по аналогии.

![изображение](https://github.com/elfmz/far2l/assets/161581982/2001060d-abd1-4ece-9904-99c18d707854)

**Comment by akruphi** [comment]
> Ну, в mc в поиске две отдельные галочки для этого, наверное, можно как-то по аналогии.

В mc визуально логично - левая колонка имя/маска, правая - содержимое.

В far примерно также, но напрашиваются 2 варианта размещения дополнительного пункта `[ ] Case sensitive (file mask)`:  
* **позиция 1** - сразу под маской 
* **позиция 2** - сверху второй колонки параметров (где вроде галочки именно по области поиска). 
 
Какой вариант вабрать?

![image](https://github.com/elfmz/far2l/assets/92621645/396c2d85-10de-4b1c-8054-ac72c39b40d3)

И как (пере|по)именовать две похожих галочки:
* текущая про текст: `[ ] Case sensitive (text)`
* новая: `[ ] Case sensitive (file mask)` или более коротко `[ ] Case sensitive (mask)` ?

**Comment by spnethw** [comment]
> * **позиция 1** - сразу под маской
>     * **позиция 2** - сверху второй колонки параметров (где вроде галочки именно по области поиска).
> Какой вариант вабрать?

**позиция 2**, имхо, будет смотреться более элегантно; но это только имхо.

> И как (пере|по)именовать две похожих галочки

`[ ] Case sensitive (text)` и `[ ] Case sensitive (mask)` , наверное. Возможно только, не "text", а "pattern"?

**Comment by akruphi** [comment]
Сравнения и пометкак #2261 и поиск файлов из #2265 вмержены. Выявляйте странности на файлах поименованных на разных языках.

Сейчас в **Compare folders** честный выбор вызова `StrCmp` или `StrCmpI` и они работают как ожидается.

А вот в **FindFile** и пометке **Gray+**/**Gray-** закодил тупую логику - перед сравнением приводится и маска и имя файла к нижнему регистру. Однако, если для ASCII это вроде всегда работает, то для русских имён похоже не работает, например у меня `*проект*.*` находит и оба файла и **проект**, и **Проект** при любом положении галочки.

К тому же судя по Notes из https://en.cppreference.com/w/cpp/string/wide/towlower встречаются языки, где нет однозначности приведения к другому регистру.

В общем как-то полукостыльно работает. Ищутся идеи как улучшить.

**Comment by spnethw** [comment]
Похоже, дело не в языке.  В таком виде оно и для ASCII толком не работает, по маске `*Algo*`, например, со включённой галкой **"Учитывать регистр"**, находит файлы

```
Advance algorithms.Hastad.ps
Advanced Algorithms.ps
algoritms.zip
```
Но для расширений, как будто, срабатывает нормально, и пока не до конца разобрался, почему. 🤔

Основной процессинг, видимо, производится в [CmpName_Body](https://github.com/elfmz/far2l/blob/64af534152606d99d4a4376fa6fc26b9c321f4e6/far2l/src/mix/processname.cpp#L172), и она там внутри себя кастует всё к верхнему регистру.

Думаю, можно было бы перенести логику регистро(не)зависимого сличения с маской в саму [CmpName_Body](https://github.com/elfmz/far2l/blob/64af534152606d99d4a4376fa6fc26b9c321f4e6/far2l/src/mix/processname.cpp#L172).

Ну, скажем, в строке https://github.com/elfmz/far2l/blob/64af534152606d99d4a4376fa6fc26b9c321f4e6/far2l/src/mix/processname.cpp#L257
при сравнении с учётом регистра делать проверку:
```cpp
if (patternc != stringc)
```

Но её функция-враппер [CmpName](https://github.com/elfmz/far2l/blob/64af534152606d99d4a4376fa6fc26b9c321f4e6/far2l/src/mix/processname.cpp#L266) используется ещё в ряде мест (не в очень большом, но всё же), это нужно переделывать сигнатуры и все вызовы. 👀

@elfmz

**Comment by spnethw** [comment]
Тогда, видимо, нужно будет, как минимум, модифицировать сигнатуры _(добавить в параметры какой-нибудь "bool IgnoreCase=true")_ :

- [CFileMask::Compare()](https://github.com/elfmz/far2l/blob/64af534152606d99d4a4376fa6fc26b9c321f4e6/far2l/src/filemask/CFileMask.hpp#L57)
- [FileMasksProcessor::Compare()](https://github.com/elfmz/far2l/blob/64af534152606d99d4a4376fa6fc26b9c321f4e6/far2l/src/filemask/FileMasksProcessor.hpp#L56)
- [CmpName()](https://github.com/elfmz/far2l/blob/64af534152606d99d4a4376fa6fc26b9c321f4e6/far2l/src/mix/processname.cpp#L266)
- [CmpName_Body()](https://github.com/elfmz/far2l/blob/64af534152606d99d4a4376fa6fc26b9c321f4e6/far2l/src/mix/processname.cpp#L172)

ну и скорректировать, где понадобится, их вызовы. 👀

**Comment by spnethw** [comment]
И есть ещё одна трабла в текущем варианте кода: в масках ведь могут задаваться и регулярные выражения.
Если галочка "Учитывать регистр" снята, то они будут принудительно кастованы к нижнему регистру, в результате может поменяться их смысл.
Типа:
` \I   - не буква`
вдруг становится
` \i   - буква`

**Comment by spnethw** [comment]
Дальнейшие обсуждения в https://github.com/elfmz/far2l/issues/2275.
