### ISSUE TITLE
far2l fails to connect to FTP

### ISSUE THREAD

**Issue by shmuz** [elfmz/far2l#2034]
Даю с командной строки `ftp://test.rebex.net/`
Ввожу `anonymous` как username и как password.
Получаю:
```
╔═══════════════════ Enum directory error ════════════════════╗
║ 550 No such directory.                                      ║
║ Failed object: /                                            ║
║ Failed site:   ftp:anonymous@test.rebex.net                 ║
╟─────────────────────────────────────────────────────────────╢
║ [ ] Remember my choice for current operation                ║
╟─────────────────────────────────────────────────────────────╢
║                { Retry } [ Skip ] [ Cancel ]                ║
╚═════════════════════════════════════════════════════════════╝
```
В Фар3 соединение происходит.

**Comment by spnethw** [comment]
Заходит, вроде, если создать соединение и в настройках протокола выбрать "Команда листинга директории: LIST" вместо "LIST -la".

**Comment by shmuz** [comment]
@spnethw,  попробовал как вы посоветовали, получаю
```
╔═══════════════ Operation failed ═══════════════╗
║ gethostbyname('ftp://test.rebex.net/') errno=0 ║
╟────────────────────────────────────────────────╢
║                     { Ok }                     ║
╚════════════════════════════════════════════════╝
```

**Comment by spnethw** [comment]
Не воспроиз... ааа... так это... имя сервера просто "test.rebex.net", в таком виде он не резолвит, видимо.

**Comment by elfmz** [comment]
На самом деле проблема изначальная в LIST -la а gethostbyname - потому что в Hostname указали имя с префиксом протокола, тут такое не поддерживается - имя отдельно, протокол - отдельно.
Но сделать автодетект команды листинга по дефолту - не рокетсаенс..

**Comment by shmuz** [comment]
Работает, спасибо.
Не буду открывать ещё один тикет, выскажу пожелание здесь:
В Фар3 при нажатии Enter на файле панели плагина, файл открывается либо по ассоциации, прописанной в Фаре, либо, если нет ассоциации - приложением ОС для данного типа файла.
Для FTP-сайта, отображаемого far2l, нажатие Enter на TXT или PNG файле выдаёт ошибку:
```
╔═ Operation failed ═╗
║                    ║
╟────────────────────╢
║       { Ok }       ║
╚════════════════════╝
```

**Comment by unxed** [comment]
touch #1085

**Comment by elfmz** [comment]
> Для FTP-сайта, отображаемого far2l, нажатие Enter на TXT или PNG файле выдаёт ошибку:

ну тут просто фундаментальная проблема - для протоколов поверх ssh - sftp, scp, shell - нажатие ентера исполняет файл на той стороне. Для других протоколов такое невозможно. В принципе можно сделать чтоб для ssh-based работало так, а для ftp и прочих -сяк. Но это както не консистно. Пока можно пойти в F9/Plugins configuration/NetRocks options и отключить там '<ENTER> to execute files remotely when possible'

**Comment by shmuz** [comment]
ОК, понятно.

**Comment by shmuz** [comment]
> Пока можно пойти в F9/Plugins configuration/NetRocks options и отключить там ' to execute files remotely when possible'

Попробовал. Кажется, там есть проблема: временный файл автоудаляется примерно через 5 секунд. Например, нажимаю Enter на PNG-файле, запускается Xviewer, показывает картинку, которая через примерно 5 сек. исчезает. Также проверил пропадание файла и в случае TXT-файла.
