### ISSUE TITLE
Import new Colorer schemes for shell POSIX and shell bash

### ISSUE THREAD

**Issue by spnethw** [elfmz/far2l#2046]
Включить бы новые схемки для POSIX/bash shell в стандартную поставку far2l.
С ними синтаксис разбирается намного корректнее и полнее.

https://github.com/elfmz/far2l/issues/1994#issuecomment-1945373278

**Comment by akruphi** [comment]
Also see https://github.com/elfmz/far2l/issues/822#issuecomment-1975223390 about make Colorer compatible with upstream.

**Comment by unxed** [comment]
Closing?
