### ISSUE TITLE
[RU] Не работают хоткеи для "Folder Shortcuts"

### ISSUE THREAD

**Issue by dimentiyinfo** [elfmz/far2l#205]
Приветствую.

Ubuntu 16.04lts (x64).
Не работают хоткеи для быстрого перемещения к избранным папкам.
Правый Ctrl воспринимается как левый Ctrl и вместо перемещения получается смена режима отображения.

Спасибо за то, что вы делаете.

**Comment by unxed** [comment]
> Спасибо за то, что вы делаете.

И от меня.

**Comment by elfmz** [comment]
с правым контролом [наверно не судьба](http://docs.wxwidgets.org/3.1/classwx_keyboard_state.html#ab0488a268111109cb6ff0ebd09e91ad1):

> This function doesn't distinguish between right and left control keys

.. поменял на ctrl+alt+0..9

**Comment by elfmz** [comment]
а хотя вроде судьба.. wxKeyEvent::GetRawKeyFlags() вроде выдает то что нужно, но нужно проверить что работает не только у меня)

**Comment by dimentiyinfo** [comment]
Проверил, у меня работает.
Сенькс!

**Comment by vasmedv** [comment]
Здравствуйте. У меня Ubuntu 18.04lts (x64). Не работает создание folder shortcuts по клавишам ctrl+shift+number. Также не работает смена директории по rightCtrl+number. По ctrl+alt+number смена каталога работает. Если в файле /usr/share/X11/xkb/symbols/pc 
закоментировать строку "modifier_map Control{ Control_L, Control_R };", то rightCtrl начинает работать смена каталога, но перестает добавляться в буфер обмена по ctrl+insert (например в firefox) и переход в начало/конец слова по ctrl+left/right. Подскажите, как то можно оживить rightCtrl безболезненно?
