### ISSUE TITLE
Migrate from pcre to pcre2 library

### ISSUE THREAD

**Issue by atolismesh** [elfmz/far2l#2052]
Сейчас существует зависимость far2l multiarc от библиотеки pcre. 
Многоие дистрибутивы перестали ее поддержтивать (для примера https://fedoraproject.org/wiki/Changes/PcreDeprecation, OpenWRT) и перешли на pcre2.

> Upstream stopped supporting the old 'pcre' package. The 8.45 is marked as a final release and nothing else will be added/fixed in it. This may lead to some unresolved CVEs, which would have to be resolved by the maintainers. Unfortunately, due to our limited capacity, we wouldn't have the time and experience to solve this by ourselves, so we need to deprecate this package. After the deprecation is done, the very next step would be starting the [retirement change](https://fedoraproject.org/wiki/PcreRetirement), so the package is removed from Fedora entirely.
> 
> The new 'pcre2' package is out for more than 7 years now and most of the packages have already been ported to its redefined API. [Mail](https://lists.exim.org/lurker/message/20150105.162835.0666407a.en.html) about the changes in the pcre2.
> 

Соответственно на этих дистрибутивах становится проблематично собирать far2l с MultiArc.
Желательно перейти на pcre2.

**Comment by ctapmex** [comment]
полное исправление в https://github.com/elfmz/far2l/pull/2516

**Comment by spnethw** [comment]
Видимо, можно закрыть?

https://github.com/elfmz/far2l/pull/2516#issuecomment-2509639314

**Comment by unxed** [comment]
Думаю, да
