### ISSUE TITLE
Commit a9f42a7 (VT: improve...) breaks application in MacOS X

### ISSUE THREAD

**Issue by eliah** [elfmz/far2l#206]
After commit a9f42a7083f9756c8817d45f31c7432d3a34f928 (VT: improve responsiveness in case of massive screen output ) in MacOS X Far hangs right after start. Panels are shown properly, but far does not react nether to any keys, mouse clicks nor to menu actions, and cursor blinks in the top left corner of the window.

**Comment by elfmz** [comment]
does it works now?
