### ISSUE TITLE
Weird bug after canceling Privilege elevation and subsequent Retry attempt

### ISSUE THREAD

**Issue by spnethw** [elfmz/far2l#2060]
1. запускаем far2l под ограниченным юзером.
2. пытаемся войти в чужую папку (скажем, в /root).
3. на запрос повышения привилегий давим Esc.
4. оно ругается, что отказано в доступе.
5. если на этом шаге выбрать "повторить", то всё проглючивает.

В командной строке папка меняется на /root, но в панели показывается содержимое корня /.
При любых телодвижениях запрашивает пароль sudo.
Но даже если его правильно ввести, то содержимое панели остаётся в корне /.
А при попытке войти в любую папку перед ней ещё подставляется /root.

**Comment by shmuz** [comment]
Если это убрать, то глюк пропадает.
https://github.com/elfmz/far2l/blob/3a39598014aa0799ead619727173bd089933a9fc/far2l/src/mix/cvtname.cpp#L318C1-L323C3
