### ISSUE TITLE
far2l executes $FARHOME/open.sh after clicking on a broken symbolic link leading to unexpected consequences

### ISSUE THREAD

**Issue by spnethw** [elfmz/far2l#2067]
Если ткнуть по битой символической ссылке, то far2l сначала выдаёт ошибку:

```
╔══════════ Open error 2 ═══════════╗
║ Нет такого файла или каталога (2) ║
║       Ошибка открытия файла       ║
║      /home/testuser/test/symlink  ║
╟───────────────────────────────────╢
║              { OK }               ║
╚═══════════════════════════════════╝
```

после чего дёргает $FARHOME/open.sh с аргументами "exec" и "имя-символической-ссылки",
что приводит к неожиданным последствиям, в моём случае -- к запуску браузера через xdg-open с именем ссылки в адресной строке.

Лог:
```
ExecuteA: SeparateWindow=1 DirectRun=1 WaitForIdle=0 Silent=0 RunAs=0 CmdStr='symlink'
ExecClassifier('symlink', 1) - stat error 2
farExecuteA:('"/usr/share/far2l/open.sh" exec symlink', 0x3): r=0

```

**Comment by akruphi** [comment]
У меня в Ubuntu 22.04 в подобной ситуации ничего не открывается.

Лог для битого симлинка:
```
ExecuteA: SeparateWindow=1 DirectRun=1 WaitForIdle=0 Silent=0 RunAs=0 CmdStr='testsym'
ExecClassifier('testsym', 1) - stat error 2
farExecuteA:('"/usr/lib/far2l/open.sh" exec testsym', 0x3): r=0
FSNotify: watching 1 entries for '/tmp/u_tmp'
CommandLine::ShowBackground: done
gio: file:///tmp/u_tmp/testsym: No application is registered as handling this file
```
@spnethw интересно, у Вас в логе после `farExecuteA:` какие ещё строчки.

**Comment by akruphi** [comment]
> Вопрос в том, зачем тут вообще open.sh управление передаётся?..

Ну симлинки имеют права запуска, поэтому автоматически и дергается open.sh. Но действительно после определения, что файл ошибочный дальше дергать open.sh уже не стоит.

**Comment by akruphi** [comment]
Наверное решением будет уже в `ExecuteA(` из execute.cpp при создании экземпляра `ExecClassifier ec(CmdStr, DirectRun);` как-то получать инфу об ошибке и дальше не обрабатывать.
