### ISSUE TITLE
Suggestion: replace control characters with dots when viewing a binary file in the terminal

### ISSUE THREAD

**Issue by spnethw** [elfmz/far2l#2068]
При просмотре бинарных файлов в терминале начинаются визуальные артефакты и звуковые сигналы, а при особо удачном раскладе терминал может вообще зависнуть.
Что если поступать так же, как mc: определив работу под TTY-бэкендом, показывать такие файлы, заменяя все управляющие символы на точки "." ?

**Comment by unxed** [comment]
По крайней мере, в качестве настраиваемой бекенд-специфической опции, да.

**Comment by unxed** [comment]
По идее, опция `-a` должна отключать отображение управляющих символов. Но у меня всё равно при просмотре бинарных файлов «кваканье» (от `\a`, который `BEEP`, видимо).

**Comment by unxed** [comment]
Dup #2084

**Comment by akruphi** [comment]
Можно закрывать после #2107 и закрытия #2084 ?

**Comment by spnethw** [comment]
Пожалуй, да. Ещё есть, что добивать, но сейчас стало намного лучше.

**Comment by unxed** [comment]
По оставшемуся — вот:
#2132
