### ISSUE TITLE
Не сохраняются атрибуты файлов при копировании с запросом на повышение прав

### ISSUE THREAD

**Issue by dvlom99** [elfmz/far2l#2069]
Здравствуйте!

FAR2L, version 2.6.0-2024-03-12-3a39598-beta Linux x86_64, Linux Mint 21.3

Столкнулся с проблемой, что при копировании структуры файлов и каталогов рядового пользователя в каталог, куда для копирования требуется повышениe прав, копирование производится (после ввода пароля пользователя в окне запроса far2l), но:
1) у файлов - меняются дата\время модификации, владелец, права доступа (если файл был в корне каталога - источника)
2) у каталогов - меняется владелец.

"Copy file access mode" - включен в диалоге копирования.

Пример, каталог источник:
```shell
/tmp/dir_user$ ls -lAR
.:
итого 4
drwxrwxr-x 3 lom lom 32 мар  6 09:42 dir1
drwx------ 2 lom lom 19 мар  2 09:15 dir2
-rwxrwxr-x 1 lom lom  3 мар  3 09:15 file3

./dir1:
итого 4
drwxrwx--- 2 lom lom 6 мар  4 09:42 dir11
-rw-r--r-- 1 lom lom 5 мар  1 09:15 file1

./dir1/dir11:
итого 0

./dir2:
итого 4
-rw------- 1 lom lom 10 мар  2 09:15 file2
``` 

Результат копирования:
```shell
/tmp/dir_root$ sudo ls -lAR
.:
итого 4
drwxrwxr-x 3 root root 32 мар  6 09:42 dir1
drwx------ 2 root root 19 мар  2 09:15 dir2
-rwxr-xr-x 1 root root  3 мар 14 09:50 file3

./dir1:
итого 4
drwxrwx--- 2 root root 6 мар  4 09:42 dir11
-rw-r--r-- 1 root root 5 мар 14 09:50 file1

./dir1/dir11:
итого 0

./dir2:
итого 4
-rw------- 1 root root 10 мар 14 09:50 file2
```

**Comment by akruphi** [comment]
Такое поведение согласуется с консольным `cp`, который не сохраняет владельца/группу без `--preserve=ownership`.

В far2l `[x] Copy files access mode` соответствует `chmod`. 

Хорошо бы добавить отдельный выбор `[ ] Copy ownership/group`, но для сохранения владельца нужен `chown`, который требует sudo - пока вообще не понимаю как это сделать аккуратно в рамках текущих наворотов внутри `copy.cpp`.

**Comment by dvlom99** [comment]
> Такое поведение согласуется с консольным `cp`, который не сохраняет владельца/группу без `--preserve=ownership`, а копии делаются под текущим пользователем/группой.
> 
Если интуитивно, то не согласуется с учетом наличия настроек вида `[x] Copy files access mode`. 

> В far2l `[x] Copy files access mode` соответствует `chmod`.
> 
Файлы, которые копируются не в составе каталогов теряют в правах:
было: -rwxrwxr-x 1 lom lom  3 мар  3 09:15 file3
стало: -rwxr-xr-x 1 root root  3 мар 14 09:50 file3

> Хорошо бы добавить отдельный выбор `[ ] Copy ownership/group`, но для сохранения владельца нужен `chown`, который требует sudo - пока вообще не понимаю как это сделать аккуратно в рамках текущих наворотов внутри `copy.cpp`.
>
Тут есть еще одно направления для спасения атрибутов - дата\время модификации файлов. Можно пойти тем же путем - добавить отдельный выбор `[x] Preserve timestamp`...
Возможно, для подавляющего большинства ситуаций достаточно будет только одной настройки вместо 3-х упомянутых выше - `[x] Preserve attributes`

**Comment by akruphi** [comment]
> Файлы, которые копируются не в составе каталогов теряют в правах

Проверил копируя разное из `/etc` в отдельный каталог у себя в ~.

В случаях, когда не нужен sudo, но есть права на чтение файла, то у меня копируется с сохранением исходных mod и timestamps (но не с полной точностью по долям секунды - точность долей секунды 2-3 знака).

Даже в случае, когда владелец не я, прав на чтение нет и потребовался sudo, то после копирования файл имел права и дату (также точность долей секунды 2-3 знака) равные исходным.

У меня единственное что не сохраняется, это owner/group.

Проверяю на последнем far2l из master: `2.6.0-2024-03-24-0eea3cc6 GUI` под Ubuntu 22.04.4

Давайте детальнее разбираться, когда при включенном `[x] Copy files access mode` у Вас не копируются права и даты. Если удастся такое регулярно повторить, то станет проще искать где лечить.

**Comment by dvlom99** [comment]
Права теряются в случае, если файлы копируются в каталог, куда требуется повышение прав, чтобы скопировать. Т.е. случай, когда sudo нужен. У меня такое поведение достигается в следующем случае, проверил еще раз:

Eсть каталоги:
`drwxr-xr-x 2 root root  6 мар 29 09:15 test1`
`drwxrwxr-x 2 lom  lom  46 мар 29 09:03 test2`
первый - пуст, 
второй содержит файлы: 
`-rw-rw-r-- 1 lom lom  646195 июн 23  2023 MNL-1166.pdf`
`-rw-rw-r-- 1 lom lom 1889862 июн 23  2023 MNL-1273.pdf`

В `FAR2L, version 2.6.0-2024-03-24-0eea3cc-beta Linux x86_64, GUI, Linux Mint 21.3 Virginia` в одной панели открываю каталог `test1`, в другой - `test2`. В `test2` выделяю оба файла, нажимаю `<F5>`, открывается окно с параметрами копирования, в котором параметр `[x] Copy files access mode` включен. Далее нажимаю `<Enter>`, появляется красное окно ввода пароля пользователя. После ввода пароля происходит копирование. В результате в каталоге `test1` появились 2 файла:
`-rw-r--r-- 1 root root  646195 мар 29 09:43 MNL-1166.pdf `
`-rw-r--r-- 1 root root 1889862 мар 29 09:43 MNL-1273.pdf`

**Comment by akruphi** [comment]
> Права теряются в случае, если файлы копируются в каталог, куда требуется повышение прав, чтобы скопировать. Т.е. случай, когда sudo нужен.

Спасибо. Повторяется. Ключевым оказалось **КУДА требуется повышение прав**. Действительно в таком случае не только создаётся от root root, но и mod сбивается и время на момент копирования.

**Comment by spnethw** [comment]
> Спасибо. Повторяется. Ключевым оказалось КУДА требуется повышение прав. Действительно в таком случае не только создаётся от root root, но и mod сбивается и время на момент копирования.

Причиной несохранения исходных прав доступа, похоже, является вот [эта проверка](https://github.com/elfmz/far2l/blob/7d275f4a3fd49560ef06526ea0202f49b7694d9b/far2l/src/copy.cpp#L2627-L2629), а точнее вот эта её часть:
```cpp
(g_umask & _SrcData.dwUnixMode) != 0)
```
Когда происходит эскалация привилегий (sudo_app), мы начинаем работать от рута. А у root может быть более строгая umask _(например, 0022),_ нежели у пользователя _(например, 0002)._ Копирование ориентируется на пользовательскую umask, видит, что вызов [_DestFile.Chmod()](https://github.com/elfmz/far2l/blob/7d275f4a3fd49560ef06526ea0202f49b7694d9b/far2l/src/copy.cpp#L2629) "необязателен" и не обновляет права.   g_umask [инициализируется](https://github.com/elfmz/far2l/blob/7d275f4a3fd49560ef06526ea0202f49b7694d9b/far2l/src/main.cpp#L760-L761) в main.cpp, видимо надо где-то в другом месте.

А что касается времени, оно устанавливается [здесь](https://github.com/elfmz/far2l/blob/7d275f4a3fd49560ef06526ea0202f49b7694d9b/far2l/src/copy.cpp#L2631):
```cpp
_DestFile.SetTime(nullptr, nullptr, &_SrcData.ftLastWriteTime, nullptr);
```
Причём копируется только время последней модификации,  а время изменения статуса и время последнего доступа не задаются (причём, похоже, если их указать, они всё равно игнорируются). В принципе, это согласуется с поведением midnight commander при копировании.

**Comment by spnethw** [comment]
Ну да,  выглядит логично... 
При копировании с повышением привилегий фактическое [открытие](https://github.com/elfmz/far2l/blob/7d275f4a3fd49560ef06526ea0202f49b7694d9b/WinPort/src/sudo/sudo_dispatcher.cpp#L96) файла для записи происходит из-под far2l_sudoapp, запущенном от рута. В этот момент, понятно, актуальна umask рута. Файловый дескриптор открытого файла [передаётся](https://github.com/elfmz/far2l/blob/7d275f4a3fd49560ef06526ea0202f49b7694d9b/WinPort/src/sudo/sudo_dispatcher.cpp#L99) через сокет и [принимается](https://github.com/elfmz/far2l/blob/7d275f4a3fd49560ef06526ea0202f49b7694d9b/WinPort/src/sudo/sudo_client_api.cpp#L214) уже на стороне пользовательского процесса far2l, в котором, естественно, своя пользовательская umask.
Именно из-за несоответствия ожидаемой и фактической umask и теряются иногда права.

**Comment by spnethw** [comment]
А со временем такая история. Для скопированного файла устанавливается оно [здесь](https://github.com/elfmz/far2l/blob/7d275f4a3fd49560ef06526ea0202f49b7694d9b/far2l/src/copy.cpp#L2631):
```cpp
_DestFile.SetTime(nullptr, nullptr, &_SrcData.ftLastWriteTime, nullptr);
```
В поле __SrcData.ftLastWriteTime_ на этот момент -- вполне себе валидная временная метка исходного файла, поэтому "портится" оно не тут.  Метод [File::SetTime()](https://github.com/elfmz/far2l/blob/7d275f4a3fd49560ef06526ea0202f49b7694d9b/far2l/src/farwinapi.cpp#L192) дёргает функцию [SetFileTimeEx()](https://github.com/elfmz/far2l/blob/7d275f4a3fd49560ef06526ea0202f49b7694d9b/far2l/src/farwinapi.cpp#L810), а та, в свою очередь, обращается к [WINPORT(SetFileTime)()](https://github.com/elfmz/far2l/blob/7d275f4a3fd49560ef06526ea0202f49b7694d9b/WinPort/src/APIFiles.cpp#L525). 

И уже в ней вызов [os_call_int()](https://github.com/elfmz/far2l/blob/7d275f4a3fd49560ef06526ea0202f49b7694d9b/WinPort/src/APIFiles.cpp#L541)
```cpp
auto r = os_call_int(sdc_futimens, wph->fd, (const struct timespec *)ts);
```
завершается неудачей с кодом ошибки **EPERM** _"Operation not permitted"._
