### ISSUE TITLE
I can't see any of newly ported plugins in "plugin manager".

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#207]
All files seems to be built ok. That am I doing wrong?

**Comment by unxed** [comment]
![_032](https://cloud.githubusercontent.com/assets/1151423/20408583/2c7fd24c-ad27-11e6-9ac3-4df3a57355f0.png)

**Comment by elfmz** [comment]
thats editor plugins, open in editor any file and then press F11

**Comment by unxed** [comment]
working, great. thankns, thanks, thanks)
