### ISSUE TITLE
Suggestion: improve heuristic detection of UTF-32 encoding

### ISSUE THREAD

**Issue by spnethw** [elfmz/far2l#2076]
В настоящее время у связки [GetFileFormatByHeuristics](https://github.com/elfmz/far2l/blob/3a39598014aa0799ead619727173bd089933a9fc/far2l/src/filestr.cpp#L717) + [EstimateEncodingValidity](https://github.com/elfmz/far2l/blob/3a39598014aa0799ead619727173bd089933a9fc/far2l/src/filestr.cpp#L691) есть проблемы с детектом UTF-32.
Невозможно отличить UTF-32BE от UTF-16BE, а UTF-32LE от UTF-16LE, поскольку переменная [out](https://github.com/elfmz/far2l/blob/3a39598014aa0799ead619727173bd089933a9fc/far2l/src/filestr.cpp#L701) _(счётчик пробельных символов, табуляций и переводов строк)_ на выходе и в том, и в другом случае будет иметь одинаковое значение.
В результате никто не выиграет, анализ будет [передан](https://github.com/elfmz/far2l/blob/3a39598014aa0799ead619727173bd089933a9fc/far2l/src/filestr.cpp#L751) uchardet, а она, в свою очередь, также зафейлится и вернёт результат "ASCII", если в файле нет BOM.

<details><summary>Первоначальный вариант решения</summary>

Сначала возникла мысль при [переборе](https://github.com/elfmz/far2l/blob/3a39598014aa0799ead619727173bd089933a9fc/far2l/src/filestr.cpp#L702) символов из буфера в функции EstimateEncodingValidity сразу вернуть управление с результатом 0, если мы наткнулись на нуль-символ '\0'.
Потому что фактически UTF-32 файл, просмотренный в UTF-16 кодировке, выглядит так же, за исключением того, что все символы написаны вразбивку через '\0'.

В то же время, нуль-символ является валидным символом в Unicode. И хотя его поддержка в far2l ограничена _(например, невозможность вставки строк, содержащих его, в редакторе)_, совсем его сбрасывать со счетов не хотелось бы.
В результате родилась такая идея: в функции EstimateEncodingValidity, помимо пробелов/табуляций/переводов строк, подсчитывать также отдельно количество встретившихся нуль-символов.
Если их число будет равно или превысит половину общего числа символов, скорее всего мы имеем дело с неправильной _(UTF-16 вместо UTF-32)_ кодировкой.
Вместе с этим кодировка определится верно и для файлов, содержащих нуль-символы как часть текста.

Предлагаю такой вариант изменений _(указаны стрелочкой)_  в функцию [EstimateEncodingValidity](https://github.com/elfmz/far2l/blob/3a39598014aa0799ead619727173bd089933a9fc/far2l/src/filestr.cpp#L691):

```cpp
template <class T>
size_t EstimateEncodingValidity(bool rev, const void *buf, size_t size)
{
    /// if text in given codepage contains only valid unicode characters then
    /// return count of well-known control characters widely used in texts
    /// like '\r' '\n' '\t' ' '
    const size_t count = size / sizeof(T);
    if (count * sizeof(T) != size) {	// expecting aligned size
        return 0;
    }
    const T *data = (const T *)buf;
    size_t out = 0;
    size_t null_characters_count=0;                 // <===============


    for (size_t i = 0; i < count; ++i) {
        T v = rev ? RevBytes(data[i]) : data[i];
        if (v == (T)'\r' || v == (T)'\n' || v == (T)'\t' || v == (T)' ') {
            ++out;
        }
        if (!WCHAR_IS_VALID(v)) {	// may be try to transcode?
            return 0;
        }

        if (v == (T)'\0') ++null_characters_count;  // <===============

    }


    if(null_characters_count>=count/2) return 0;    // <===============


    if (out < count / 32) {		// too few controls for normal text
        return 0;
    }
    return out;
}
```
</details>

Решение от https://github.com/shmuz/far2m/commit/3f453c4505a88bdc3e5412a89c7e06ca33a388fe

**Comment by shmuz** [comment]
Предлагаю взглянуть и на [это решение](https://github.com/shmuz/far2m/commit/3f453c4505a88bdc3e5412a89c7e06ca33a388fe) (вроде работает).

**Comment by spnethw** [comment]
> Предлагаю взглянуть и на [это решение](https://github.com/shmuz/far2m/commit/3f453c4505a88bdc3e5412a89c7e06ca33a388fe) (вроде работает).

Хм, прогнал на ряде тестов, похоже, действительно робит.
Наверное, стоит отдать предпочтение вашему варианту, а мой оставить про запас.
