### ISSUE TITLE
feature request: consider symbol code 96 a quote

### ISSUE THREAD

**Issue by igorklopov** [elfmz/far2l#208]
Since ES6 has Template Literals (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) - it will be great to mark content yellow between \`these quotes\`. Unmarking yellow inside ${this} is optional thou.

**Comment by unxed** [comment]
This should be posted here https://github.com/colorer/Colorer-schemes

far2l just imports color schemes from this project
