### ISSUE TITLE
Right-click-and-drag for files selecting is buggy in TTY

### ISSUE THREAD

**Issue by spnethw** [elfmz/far2l#2086]
Подглючивает выделение файлов/папок правой кнопкой мыши.
Просто щелчок — всё ок, выделяется/снимается, как надо.
А вот щелчок + протяжка по списку — уже проблемы: любое движение мышки, пока мы находимся на одном и том же файле, приводит к инверсии выделения.
Что в свою очередь часто влечёт пропуски в выделенном.
В GUI такого не наблюдается, только в терминалах.

UPD: судя по всему, инверсия происходит при горизонтальном перемещении курсора мыши с одного знакоместа на другое; во всяком случае, для моноширинных шрифтов.

https://github.com/elfmz/far2l/assets/161581982/f231dcf4-5be7-4fb0-a164-69fb88d6d3df

**Comment by spnethw** [comment]
> It seems that constant button presses are being sent. The same thing is happening with checkboxes and other elements

Да, с чекбоксами и левым кликом та же петрушка. Но там хотя бы оно особо не мешает, как в случае с выделением.
А ноги, видимо, из одного места растут.

**Comment by Dazzar56** [comment]
Pretty straightforward fix in #2109.
We just save pressed state for button until release command received from terminal.

Оказалось, что TTY бекэнд не знал, что кнопка удерживается, а терминалы тупо продолжают слать команды нажатия, пока кнопка не отпущена. Теперь мы это учитываем и сохраняем нажатое состояние кнопки.
