### ISSUE TITLE
Ubuntu 24.04 LTS preparations

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#2088]
On April 25, Ubuntu 24.04 LTS is released, the first LTS version of Ubuntu with far2l in the repositories. I would like the UX of new users to be the best. Therefore, I propose to solve some problems in the near future, and then try to send a new version to Debian/Ubuntu. But even if this does not work out, at least we will be able to offer those who want to try the bug-free version to use the ppa. Here are some  bugs that look like they need attention.

UPD: **I myself believe that for Ubuntu we need to focus on [input delays](https://github.com/elfmz/far2l/issues/2041) in the default terminal under [Wayland](https://github.com/elfmz/far2l/issues/2158). This does not allow you to use the program normally, and this has already been fixed in [2.6.1](https://github.com/elfmz/far2l/releases/tag/v_2.6.1). However, there are other bugs that can be fixed if possible.**

1. Fix mouse in Windows Terminal (PR is ready)
https://github.com/elfmz/far2l/issues/2072
DONE

2. Make clipboard work out of the box under WSL
https://github.com/elfmz/far2l/issues/1658
DONE

3. Import fresh colorer schemes
https://github.com/elfmz/far2l/issues/2046
DONE

4. Fix privelege elevation bug
https://github.com/elfmz/far2l/issues/2060
DONE

5. Fix uchardet (#2075, #2076, #2078)
https://github.com/elfmz/far2l/pull/2111
DONE

6. Fix redraws after sudo
https://github.com/elfmz/far2l/issues/2047
DONE

7. Fix unneeded open.sh call
https://github.com/elfmz/far2l/issues/2067
DONE

8. Fix binary files view problems under TTY backend
https://github.com/elfmz/far2l/issues/2084
https://github.com/elfmz/far2l/pull/2107
https://github.com/elfmz/far2l/issues/2136
DONE

9. Fix interface in WezTerm on our side
https://github.com/elfmz/far2l/issues/1889
DONE

10. File attributes are not saved when copying with an elevation request
https://github.com/elfmz/far2l/issues/2069
DONE

@elfmz @alexmyczko

**Comment by akruphi** [comment]
@alexmyczko it will be excellent if in upcoming release you can split debs by tiny, ... wx as was suggested in https://salsa.debian.org/debian/far2l/-/merge_requests/1

**Comment by unxed** [comment]
Also it would be nice to add some kind of workaround for
https://github.com/elfmz/far2l/issues/1889
on our side before April

**Comment by akruphi** [comment]
@alexmyczko please give advice about here elfmz **far2l release deadline** that you can time to prepare and put debs in Debian (I hope may be debs will have split versions now) and then we have enough time to request a freeze exception in Ubuntu via https://wiki.ubuntu.com/FreezeExceptionProcess#FeatureFreeze_for_new_upstream_versions 

Is the **diff of the Upstream ChangeLog**  required or only recommended for start https://wiki.ubuntu.com/FreezeExceptionProcess#FeatureFreeze_for_new_upstream_versions or enough only describe **state the reason**?

**Comment by alexmyczko** [comment]
i really do not think anything will make it into ubuntu 24.04. your best option is PPA. please either use debian. please make a new release. debian will update to that, debian can do backports for debian stable. from that you can feed your PPA, or simply switch to debian.

sorry for no better news

**Comment by unxed** [comment]
@elfmz а можно релизик свежий выпустить? Есть идея попробовать в Ubuntu таки пропихнуть версию без задержек ввода. А то там же Wayland по умолчанию.

**Comment by unxed** [comment]
> please make a new release

@alexmyczko done!

**Comment by akruphi** [comment]
It seems we will no longer be able to push the latest version of far2l into the Ubuntu 24.04 release, because it stage **Final Freeze** now: https://lists.ubuntu.com/archives/ubuntu-devel-announce/2024-April/001348.html

We will can try adding it latter as **backports**
https://wiki.ubuntu.com/UbuntuBackports
but first it is necessary that development 24.10 will be open and new far2l version will be in 24.10.

**Comment by unxed** [comment]
One simple command to fix input delays on Ubuntu 24.04:
`sudo sed -i '/^\[daemon\]/a DefaultSession=gnome-xorg.desktop' /etc/gdm3/custom.conf`

and reboot.

See also: #2041, https://askubuntu.com/a/1464319/894968

**Comment by unxed** [comment]
https://bugs.launchpad.net/ubuntu/+source/far2l/+bug/2063919

**Comment by unxed** [comment]
Closing as all issues are solved now.
