### ISSUE TITLE
"Compare folders" and "Advansed compare" not case-sensitive

### ISSUE THREAD

**Issue by Black-Semargl** [elfmz/far2l#2115]
Здраствуйте!

FAR2L, version 2.6.0-2024-03-24-0eea3cc-beta Linux x86_64

Если на одной панели файлы например
IMG_1210.MP4
IMG_1210.mp4

А на другой только 
IMG_1210.mp4

То "сравнение папок" не видит между папками разницы
А "расширенное сравнение" выделяет все три, хотя надо только **IMG_1210.MP4**

**Comment by akruphi** [comment]
Учет регистра при **Сравнении папок** и пометке по **Gray+**/**-** теперь настраивается в `F9->Параметры->Настройки панели->[x] Учитывать регистр при сравнении или пометке`.
