### ISSUE TITLE
Wrong diacritic marks presentation in cyrillic file names - MacOS X

### ISSUE THREAD

**Issue by eliah** [elfmz/far2l#213]
Cyrillic file names with diacritic marks are represented incorrectly in Far (MacOS X), despite being absolutely correct in the file system. Not a very bad bug, but a bit annoying.

![chachlyklion](https://cloud.githubusercontent.com/assets/2249849/20555935/a93ead7e-b175-11e6-8173-6a90da153e02.png)

**Comment by strim** [comment]
Did anybody resolve that? WxWidget issue?

**Comment by unxed** [comment]
https://github.com/magiblot/tvision/issues/26#issuecomment-719964250

A story about how diacritics were fixed in another TUI framework.

**Comment by unxed** [comment]
duplicates #1329, #826

**Comment by elfmz** [comment]
closing as fixed
