### ISSUE TITLE
--nodetect=xi does not work from FAR2L_ARGS

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#2139]
Just `--nodetect` still do.

**Comment by unxed** [comment]
Looks like `-set:Interface.OSC52ClipSet=1` is not working in FAR2L_ARGS also.

**Comment by akruphi** [comment]
> Looks like `-set:Interface.OSC52ClipSet=1` is not working in FAR2L_ARGS also.

**FAR2L_ARGS** don't affect on `-set` because it processed in **WinPort/src/Backend/WinPortMain.cpp** and work only with FAR2L backend-specific options (started with`--`) as described in `far2l --help` and in help "Command line switches" by **F1**.
