### ISSUE TITLE
Восстановление позиции на панелях при старте FAR2L

### ISSUE THREAD

**Issue by Zeroes1** [elfmz/far2l#2142]
Добавить возможность восстановления позиционирования на файловых элементах на панелях при запуске FAR

[это было не реализовано в FAR2, в FAR3 уже работает]

по ShiftF9 или при авто сохранении данные фиксируются уже в значениях:

Panel/Right.CurFile
Panel/Left.CurFile

**Comment by spnethw** [comment]
Так ведь... вроде, восстанавливается?

**~/.config/far2l/settings/panel.ini**  :

```
[Panel/Left]
CurFile=..
Folder=...

[Panel/Right]
CurFile=..
Folder=...```

**Comment by Zeroes1** [comment]
Восстанавливается только если [x] Auto save setup
но если [ ] Auto save setup и мы вручную сохраняем конфигурацию по Shift-F9
то восстанавливаются только каталоги, курсор на обоих панелях стоит на ..

**Comment by Zeroes1** [comment]
Пример исправления этой же ситуации для FAR2M
https://github.com/shmuz/far2m/commit/24c2569028a6e22807cb0d072b20ab571650546d
