### ISSUE TITLE
far2l --tty key macros

### ISSUE THREAD

**Issue by m32** [elfmz/far2l#2145]
in key_macros.ini I have the entry:
[KeyMacros/Shell/Ctrl/]
DisableOutput=0x1
FilePanels=0x1
PluginPanels=0x1
Sequence=F9 c d

a nice shortcut to quickly change the directory in the gui version works without problems - in the tty version it doesn't work :(

**Comment by Zeroes1** [comment]
should work, may be lang interface another [and hotkeys different] ?

**Comment by shmuz** [comment]
The problem is when in TTY `Ctrl/` is pressed the TTY back end translates that as `CtrlDivide`.
In the meantime (until the problem is fixed) you can add another macro identical to your macro above  with the only difference in the first line: `[KeyMacros/Shell/CtrlDivide]`.

**Comment by m32** [comment]
@shmuz 

thx
