### ISSUE TITLE
consider using meson as build system

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#216]
meson is build system GNOME is now switching to
can far2l benefit from it?

it is said to be very fast at least
http://mesonbuild.com/
http://www.phoronix.com/scan.php?page=news_item&px=Wayland-Meson-Build-Sys-Patches

**Comment by elfmz** [comment]
- build system can't be faster that compiler it uses beneath
- some people in the world still use osx..

**Comment by unxed** [comment]
ok, closing so far
