### ISSUE TITLE
32-bit failed to build

### ISSUE THREAD

**Issue by spvkgn** [elfmz/far2l#2164]
[build log](https://code.launchpad.net/~far2l-team/+archive/ubuntu/ppa/+build/28097488/+files/buildlog_ubuntu-bionic-i386.far2l_0+git202404152138.d6cc2178~ubuntu18.04.1_BUILDING.txt.gz)

**Comment by spnethw** [comment]
"(size_t)33" наверное надо


https://github.com/elfmz/far2l/blob/d6cc2178f0252c46873dd222d9cc47f2694ab167/far2l/src/pick_color.cpp#L370
https://github.com/elfmz/far2l/blob/d6cc2178f0252c46873dd222d9cc47f2694ab167/far2l/src/pick_color.cpp#L374
