### ISSUE TITLE
Multiarc: format submenu drop selection

### ISSUE THREAD

**Issue by cycleg** [elfmz/far2l#217]
Подменю выбора формата для редактирования архивных команд не запоминает текущий выбранный формат и после диалога сбрасывается на первый пункт. Это происходит из-за [некорректного сравнения двух строк](https://github.com/elfmz/far2l/blob/df3bf10115f8ec087148b0e8af8622730445363e/multiarc/src/ArcProc.cpp#L248). Правильно "**!** strcasecmp(ArcFormat,Format)".

Интересно, что этой ошибки нет даже в [самом древнем публично доступном коде multiarc](https://sourceforge.net/p/farmanager/code/291/tree/plugins/multiarc/trunk/ArcProc.cpp#l257), который удалось разыскать.

**Comment by elfmz** [comment]
а это я наверно накосячил. дрогнувшая рука стерла восклицательный знак:)
