### ISSUE TITLE
Regarding files highlighting masks: use regexps instead of globs?

### ISSUE THREAD

**Issue by spnethw** [elfmz/far2l#2170]
Уже упоминал об этой проблеме в https://github.com/elfmz/far2l/issues/2029.
Вопрос снова возник в связи с добавлением большого количества новых масок в подсветку.
Может быть, стоит сделать их регэкспами по умолчанию?

У себя я, например, делаю примерно так:
```/^.*\.(?:sh|py|pl|cmd|exe|bat|com)$/i```

Едва ли не половина файлов, с которыми сталкиваюсь, имеет расширения в верхнем регистре: .MP3, .FLAC, .DOCX, .EXE, .ZIP и т.д. Естественно, они не подсвечиваются.

![изображение](https://github.com/elfmz/far2l/assets/161581982/98112bee-0773-44ce-915d-1924d8c3724f)

**Comment by elfmz** [comment]
Регэкспы долго парсятся, когда открываешь директорию с 100500 (в буквальном смысле) файлов это будет ботлнек, хотя опционально можно конечно
С регистронезависимым сравнением вопрос открыт, опция будет, когда нибудь...

**Comment by spnethw** [comment]
> Регэкспы долго парсятся, когда открываешь директорию с 100500 (в буквальном смысле) файлов это будет ботлнек, хотя опционально можно конечно С регистронезависимым сравнением вопрос открыт, опция будет, когда нибудь...

Не поленился, набросал генератор рандомных имён файлов с заданными расширениями и провёл замеры.
1 млн. файлов в директории, имена рандомные [A-Za-z0-9\s]{1,20}, расширения из текущего списка подсветки, половина в верхнем, половина в нижнем регистре.

Среднее время от входа в директорию до отображения содержимого при использовании классичеческих масок 10.28 сек, при использовании регэкспов 10.59 сек.

**Comment by akruphi** [comment]
Немного слабодвижущаяся тема про far2l на разных embedded (https://github.com/spvkgn/far2l-openwrt , https://github.com/spvkgn/far2l-termux и прочая экзотика). Так вот там это будет критично. Моё мнение - надо кодить галочку "регистронезависимое сравнение" и использовать по дефолту её.

**Comment by shmuz** [comment]
В far2m маски файлов для раскраски являются case insensitive (в большинстве случаев это то что нужно).
Если у пользователя есть какие то особые файлы, где это не годится - поставит регексп.

**Comment by spnethw** [comment]
Может, тогда малой кровью можно это решение перетащить из far2m?

**Comment by spnethw** [comment]
Апдейт. 
Не обратил внимания, что замеры проводил на debug-сборке far2l, перезамерил в тех же условиях на release-версии.
Ситуация в корне изменилась.
В 1 и 2 случае время при использовании масок и при использовании регэкспов стало примерно одинаковым, в рамках погрешности.
В 3 случае (1 млн. файлов с именами 255 символов) — процессинг масок стал даже меньше, чем регэкспов (10 секунд vs 8 секунд).
Такие дела.

**Comment by spnethw** [comment]
Провёл ещё один тест. 

Увеличил кол-во файлов в директории до: **1.5 млн.**
Общая длина каждого имени файла, включая расширение: **255 символов.**
Имена файлов: **рандомные** из набора символов **[A-Za-z0-9\s]** и **[:punct:]**, за вычетом прямого слэша.
Проверялось на: расширениях, предлагаемых для раскраски по дефолту в текущей версии (и коммите) far2l.

После нескольких замеров среднее время от входа в директорию до отображения содержимого:
при использовании **масок** — **16 сек.**,
при использовании регэкспов — **15 сек.**

far2l собирался в release-версию.

**Comment by spnethw** [comment]
Не актуально после https://github.com/elfmz/far2l/pull/2267, пока закрываю.
