### ISSUE TITLE
Files highlighting marks symbols by default: remove or change with mc tradition

### ISSUE THREAD

**Issue by akruphi** [elfmz/far2l#2172]
After PR #2152 from @anta999 new defaults for **Files highlighting and sort groups** not good: some files has not left mark, but other has mark symbol and in panel **left real symbol of filename** not always **aligned uniformly**.
![image](https://github.com/elfmz/far2l/assets/92621645/ab677bf7-8b3d-49ab-b7a1-a98ad3d1c1f4)

Please @anta999 either add even a space mark to everyone (it may be difficult because marks can additive), or remove any default mark symbols.

Давайте обсудим как лучше поступить в этом случае. Возможно, если уж делать символы в схемах по умолчанию, то стоит следовать **традициям mc**
![image](https://github.com/elfmz/far2l/assets/92621645/2a2307b6-670e-43e0-9614-aad5ecd369c3)
и `ls -F`
![image](https://github.com/elfmz/far2l/assets/92621645/55fb0ef0-637c-46b8-9748-dfad0796d493)
т.е.:
 > В mc символ типа файла один из тех, которые могут быть отображены командой ls -F : звёздочка - для выполняемых файлов, слэш - для каталогов, знак '@' - для ссылок, знак '=' - для сокетов, знак '-' - для символьных устройств, знак '+' - для блочных устройств, знак '|' - для каналов данных, знак '~' - для символических ссылок к каталогам и восклицательный знак для пустых символических ссылок (ссылок, которые ни на что не указывают).

И придумывать новые символы маркеров только для случаев, когда нет устаканенных символов.

**Comment by spnethw** [comment]
> Please @anta999 either add even a space mark to everyone (it may be difficult because marks can additive), or remove any default mark symbols.

Хм, а как быть, если меток у файла будет несколько? Выравнивать на несколько пробелов?
В доработанной модели подсветки маркеры могут "суммироваться", скажем для музыкальных файлов может добавляться метка ♪ и т.д.

**Comment by spnethw** [comment]
> Вообще, чтобы не перегружать визуал, по дефолту я бы оставил только одну единственную метку — для символических ссылок.

О неочевидных причинах.

В предложенном дефолте помечаются символом « файлы, имеющие больше одной жесткой ссылки.
И я был немного озадачен, когда на примонтированном NTFS-диске добрая половина файлов была с таким значком, другая половина без.

Ларчик открывался просто, всё дело в коротких 8.3 именах, которые Windows создаёт на NTFS в дополнение к длинным именам. Они не отображаются, но работают как хардлинки и учитываются тем же ls или stat.
_(Причём если создать имя с длинным файлом из-под Linux, парное 8.3 ему не будет создано, для таких файлов число хардлинков будет 1.)_

Это немного раздражает.

**Comment by spnethw** [comment]
> У меня так видит NTFS

Вероятно, зависит от версии Windows и того, была ли отключена/включена эта функциональность вручную.
Гугл говорит:

Since Windows 8 and Windows Server 2012 **newly formatted volumes** will have [8.3 name generation disabled by default](https://ss64.com/nt/syntax-filenames.html).

**Comment by spnethw** [comment]
> У меня так видит NTFS

@anta999
Присмотрелся к скрину повнимательнее, на нём ведь тоже файлы с "длинными" (не вписывающимися в 8.3) именами
```
appverifui.dll
DumpStack.log
DumpStack.log.tmp
VeePNService.log
```
отмечены значком `«`

**Comment by akruphi** [comment]
@anta999 присоединяйтесь к дружному русскоязычному телеграм-чату https://t.me/far2l_ru в нём можно оперативнее обсуждать, не захломляя issue промежуточными высказываниями

**Comment by akruphi** [comment]
Done in https://github.com/elfmz/far2l/pull/2388 (thanks @anta999 for global checkbox in https://github.com/elfmz/far2l/pull/2380 )
