### ISSUE TITLE
Consider switching (back?) to codecvt as an alternative to iconv and Wine charset routines

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#2186]
As we now welcome the use of C++17 code in far2l (see https://github.com/elfmz/far2l/pull/2177#issuecomment-2082069388), maybe it's time for us to try using codecvt as [an alternative to iconv and Wine charset routines](https://github.com/elfmz/far2l/issues/733)?

**Comment by elfmz** [comment]
1 what this will improve
2 need to evaluate performance, i remember iconv performance was poor comparing to WinPort's

**Comment by unxed** [comment]
1. Binary size for embedded devices; volume of code to support (and keep synced with upstream 
2. 👍

**Comment by elfmz** [comment]
Это еще вопрос окажется ли он меньше, потому что любит STL код инстанциировать в бинарнике 
И еще момент, я дико стесняюсь, но я прогуглил час и так и не понял как этим codecvt сконвертить произвольный CP,.. в UTF32. везде приводят UTF8<->UTF32 что не интересно - так как у far2l для этого не вайн используется а модифицированная ww898, которая и шустрая шопесец, и никаких таблиц перекодировки в себе не содержит.
Кроме того заглянул в последние исходники виндового фара - там до сих пор WideCharToMultiByte MultiByteToWideChar. А видя любовь ихних разработчиков ко всему новому в мире С++, надо полагать у них были причины все равно юзать винапи для этого.
