### ISSUE TITLE
ability to use far editor as default

### ISSUE THREAD

**Issue by mogadanez** [elfmz/far2l#219]
for git commits for example

**Comment by unxed** [comment]
yep, something like "far2l --edit FILENAME"

**Comment by volth** [comment]
I think, the editor and the viewer should be separated out to its own processes and executable files (```far2l-editor``` and ```far2l-viewer```).

Besides the nice feature of launching them without ```far2l``` this would allow us to use external editors (e.g. radare2 for the binaries) as the native editors without blocking ```far2l```, keeping the ability to press ```Alt-Tab``` to see the blue panels and the windows of the other editors.

**Comment by lingvoboard** [comment]
Any available text viewer for Linux (not GUI) can handle UTF-16.
Therefore far2l-viewer is a good idea.

В своё время тщетно искал вьюер (не GUI) для просмотра тестовых файлов в кодировке UTF-16, не нашёл.
Родной вьюер Midnight Commander-а не умеет работать с UTF-16. Приходится открывать иногда огромные файлы в редакторе, чтобы просто посмотреть.
Поэтому заиметь far2l-viewer было бы очень круто.

"far2l /v file.txt" не устраивает тем, что каждый раз надо растягивать окно вручную, изначально оно маленькое и размер не запоминается, нет ключа --maximise или --geometry=GEOMETRY.

**Comment by volth** [comment]
а ```far2l-viewer``` получится GUI (ну, чтобы esc по два раза не нажимать, перехватывать одиночные нажания на shift, alt и ctrl, ... - те же причины почему ```far2l``` GUI)

**Comment by elfmz** [comment]
use far2l /e file
