### ISSUE TITLE
Far doesn't open/execute files, containing whitespaces

### ISSUE THREAD

**Issue by invy** [elfmz/far2l#22]
When trying to open or execute files, containing whitespaces, far says for example:
"2 2.sh: command not found"

**Comment by lieff** [comment]
How about now?

**Comment by invy** [comment]
No problem with whitespaces, but check for other characters like braces and so on. The same is also for utf8, eventually you need to escape it.

**Comment by lieff** [comment]
And now?

**Comment by invy** [comment]
nope, not working.
 d d 0 DOWNt::Enqueue: 
 d d 0 UPput::Enqueue: 
CommandLine::SaveBackground: done
farExecuteA:('./1\ (\ 2\ ).sh', 0x0, (nil)): r=256
WinPortFSNotify('/tmp/1/1 1') - watching
CommandLine::ShowBackground: done
OnKeyUp: d d 0 249225070
OnKeyDown: d d 0 249225136
OnChar: d d 0 249225136 _lk_ts=249225136 _lk_enqueued=0
 d d 0 DOWNt::Enqueue: 
 d d 0 UPput::Enqueue: 
ExplodeCmdLine('"1 ( 2 ).sh"') -> '"1' '(' '2' ').sh"' 
ExecClassifier('1 ( 2 ).sh') - script
CommandLine::ShowBackground: done
VT: ioctl(TIOCSCTTY): Operation not permitted
OnKeyUp: d d 0 249225199
CommandLine::SaveBackground: done
farExecuteA:('./1\ (\ 2\ ).sh', 0x0, (nil)): r=256
WinPortFSNotify('/tmp/1/1 1') - watching
CommandLine::ShowBackground: done

**Comment by lieff** [comment]
Something not right. I've check last sources and result is:
```
ExplodeCmdLine('"1 ( 2 ).sh"') -> '"1' '(' '2' ').sh"' 
ExecClassifier('1 ( 2 ).sh') - unknown: 65 63 68 6f assumed executable
CommandLine::ShowBackground: done
VT: ioctl(TIOCSCTTY): Operation not permitted
CommandLine::SaveBackground: done
farExecuteA:(''./1 ( 2 ).sh'', 0x0, (nil)): r=0
WinPortFSNotify('/home/lion/github') - watching
CommandLine::ShowBackground: done
OnKeyUp: 0 172 0 11302411
ConsoleInput::Enqueue:  0 d 0 UP
```
'./1\ (\ 2\ ).sh' is wrong

**Comment by invy** [comment]
Hm. Rebuilt and retested. Seems ok now.
