### ISSUE TITLE
Colorer не компиляется

### ISSUE THREAD

**Issue by volth** [elfmz/far2l#220]
попробовал собрать far на другом дистрибутиве линукса, в Colorer обнаружились две ошибки компилятора по поводу небезопасного использования fprintf.

/home/demo/hello/far2l/colorer/src/shared/colorer/viewer/ConsoleTools.cpp:
In member function ‘void ConsoleTools::forward()’:
[/home/demo/hello/far2l/colorer/src/shared/colorer/viewer/ConsoleTools.cpp:311:47](https://github.com/elfmz/far2l/blob/4198cd582fefc14665555e1a344f8d486cffcde3/colorer/src/shared/colorer/viewer/ConsoleTools.cpp#L311):
error: format not a string literal and no format arguments
[-Werror=format-security]
     fprintf(stderr, e.getMessage()->getChars());
                                               ^
/home/demo/hello/far2l/colorer/src/shared/colorer/viewer/ConsoleTools.cpp:
In member function ‘void ConsoleTools::genOutput(bool)’:
[/home/demo/hello/far2l/colorer/src/shared/colorer/viewer/ConsoleTools.cpp:365:49](https://github.com/elfmz/far2l/blob/4198cd582fefc14665555e1a344f8d486cffcde3/colorer/src/shared/colorer/viewer/ConsoleTools.cpp#L365):
error: format not a string literal and no format arguments
[-Werror=format-security]
       fprintf(stderr, e.getMessage()->getChars());

**Comment by lieff** [comment]
Классика https://github.com/elfmz/far2l/pull/221

**Comment by elfmz** [comment]
вмержил, закрываю..
