### ISSUE TITLE
Separate proxy per NetRocks connection like in Far3 windows

### ISSUE THREAD

**Issue by Yoskaldyr** [elfmz/far2l#2200]
Is it possible to specify separate proxy for each NetRocks connection (the same as in Far3 for windows)?
In windows in Far3 I have almost the same connections (the same host/user/password/key) that differs only by proxy settings. How can I get the same behavior?

**Comment by elfmz** [comment]
NetRocks supports proxy in general by tsock with custom (own) configuration file, and that tsock config has a way to specify different proxies depending on target IP address.. Really not very user friendly, but may be if its really important may add more 'native' proxy support or more user-friendly configurator for tsock...

**Comment by Yoskaldyr** [comment]
> NetRocks supports proxy in general by tsock with custom (own) configuration file, and that tsock config has a way to specify different proxies depending on target IP address.. Really not very user friendly, but may be if its really important may add more 'native' proxy support or more user-friendly configurator for tsock...

the main issue that I have a lot of different servers with the same local ip addresses. And the same server with different uplinks (and different proxy ip addresses). And sometimes proxy can be unavailable, so I have to change it. And if it will be in separate file it will be far away from good usability :(

P.S. Fedora doesn't have tsocks package (even in third party repo)

**Comment by elfmz** [comment]
does it have proxychains package?

**Comment by Yoskaldyr** [comment]
> does it have proxychains package?

yes, proxychains-ng package exists

**Comment by elfmz** [comment]
Added support for proxychains also now proxifiers configuration is per-site (there is button added at bottom of Site settings dialog) - so please check if it works for you.

**Comment by Yoskaldyr** [comment]
I use binary package. I will check the latest version slightly later when I build it by self

**Comment by Yoskaldyr** [comment]
Rebuilt. Everything is working fine with proxychains 👍
