### ISSUE TITLE
Disable GNOME keyboard shortcuts for GTK version (Alt-F2 etc.)

### ISSUE THREAD

**Issue by Yoskaldyr** [elfmz/far2l#2210]
Almost all programs where keyboard shortcuts are the same with global shortcuts, disable global system shortcuts.

Right now when I use gui/gtk version of far2l I can't use Alt-F2 / Alt-F6 / etc. combinations in far, because of global keyboard shortcuts.

far2l version - latest master. System Fedora 40, gnome wayland.

**Comment by spnethw** [comment]
Options | Input settings - "Exclusively handle hotkeys..."  ?

> **Exclusively handle hotkeys that include**
> This options allows to choose control keys using which in hotkey combination will cause FAR2L to capture keyboard input exclusively, thus preventing other application from interfering with FAR2L hotkeys that contains such control key. Note that this options works only in GUI backend mode.

**Comment by Yoskaldyr** [comment]
I didn't know that the GTK and TTY versions have different options
