### ISSUE TITLE
far не запускается из каталога с именем bin

### ISSUE THREAD

**Issue by volth** [elfmz/far2l#222]
как воспроизвести: после билда переименовать каталог install в bin и попробовать запустить far2l оттуда
```
cp -dpR install bin
bin/far2l
```

с другими именами каталогов проблемы нет, только с bin.

похоже на регрессию, с версией far от 2016-Sep-29 этой проблемы нет.

**Comment by volth** [comment]
вот с [этого коммита](https://github.com/elfmz/far2l/commit/7314ecb7ab2c50721c494cd5a93ad62fedb0f3c6) баг появился

**Comment by elfmz** [comment]
это изза логики, которая позволяет фару быть размазанным по ФС, как обсуждалось тут https://github.com/elfmz/far2l/issues/84
то есть если far2l обнаруживает себя в bin, то считает, что остальные файлы нужно искать в lib и share относительно родительского каталога самого bin.

**Comment by elfmz** [comment]
В принципе можно конечно было бы сделать некий файл-признак работы в неразмазанном состоянии. Просто думалось мне, что запуск из bin подразумевает адекватную инсталляцию, а не копирование всего инсталл фолдера в bin.

**Comment by volth** [comment]
не, [там именно баг](https://github.com/elfmz/far2l/commit/7314ecb7ab2c50721c494cd5a93ad62fedb0f3c6#diff-09ca1a086195d5a0522877babf847ddcR369).
если far в bin, то CutToSlash не делается и g_strFarPath присваивается ".../share/far2l", хотя там должен быть путь к каталогу, а не к исполняемому файлу far2l

**Comment by volth** [comment]
да, зачем всё это - я пытаюсь собрать far под nixos, там исполняемые файлы оказываются в "/nix/store/${sha256}-far2l-${version}/bin"; и вот этот bin на конце есть всегда.

**Comment by elfmz** [comment]
не, это именно фича :)
если бинарник far2l лежит в /nix/store/${sha256}-far2l-${version}/bin то стало быть плагины нужно положить в /nix/store/${sha256}-far2l-${version}/lib/far2l/Plugins ну и рядышком far2l_sudoapp, far2l_askpass и файлы данных в /nix/store/${sha256}-far2l-${version}/share/far2l/
Такая структура покатит в nixos?

**Comment by volth** [comment]
1. g_strFarPath используется как имя каталога, например [тут](https://github.com/elfmz/far2l/blob/34edb8c914cb83614269e65e4e473656878347a6/far2l/panel.cpp#L1532), а если каталог оканчивается на bin, там оказывается имя файла (.../bin/far2l).

2. для nix пока ничего делать на надо - там 100500 проблем с фаром, эта сама мелкая.

3. фар не запускается из каталога bin даже без плагинов

**Comment by elfmz** [comment]
TranslateFarString<TranslateInstallPath_Bin2Share> превращает путь к бинарнику типа "/usr/bin/far2l" в путь к директории "/usr/share/far2l" где и ожидается увидеть файлы, на которые указывает g_strFarPath, потому CutToSlash делать не нужно.

**Comment by volth** [comment]
а, ok.

**Comment by volth** [comment]
> к бинарнику типа "/usr/bin/far2l" в путь к директории "/usr/share/far2l"

в принципе, это баг.
т.к. это привязка к тому что бинарник будет называется ```far2l``` (в том же nixos возможна ситуация:  бинарник переименован в ```.far2l-wrapped``` а на его месте будет bash-cкрипт)

**Comment by elfmz** [comment]
ну так не надо так его называть просто

**Comment by volth** [comment]
а его там не переименовывают явно.
там можно написать ```wrapProrgam $out/bin/far2l --set FAR2L_STD /tmp/far2l```, чтобы фар вёл лог.
а он после этого перестаёт работаеть, т.к. under the hood это переименование бинарника в ```.far2l-wrapped```
