### ISSUE TITLE
macOS compilation error

### ISSUE THREAD

**Issue by mad-rain** [elfmz/far2l#2230]
Hi!

Unable to compile far2l on latest macOS (14.5 (23F79)):

[ 28%] Building CXX object Colorer-library/src/CMakeFiles/colorer_lib.dir/colorer/parsers/ParserFactoryImpl.cpp.o
[ 28%] Building CXX object Colorer-library/src/CMakeFiles/colorer_lib.dir/colorer/parsers/SchemeNode.cpp.o
[ 28%] Building CXX object Colorer-library/src/CMakeFiles/colorer_lib.dir/colorer/parsers/TextParser.cpp.o
[ 28%] Building CXX object Colorer-library/src/CMakeFiles/colorer_lib.dir/colorer/parsers/TextParserHelpers.cpp.o
In file included from /Users/someone/_far2/far2l/colorer/src/Colorer-library/src/colorer/parsers/CatalogParser.cpp:3:
/Users/someone/_far2/far2l/colorer/src/Colorer-library/src/colorer/base/XmlTagDefs.h:18:13: error: array initializer must be an initializer list
const XMLCh catTagCatalog[] = u"catalog\0";
            ^
/Users/someone/_far2/far2l/colorer/src/Colorer-library/src/colorer/base/XmlTagDefs.h:19:13: error: array initializer must be an initializer list
const XMLCh catTagHrcSets[] = u"hrc-sets\0";
            ^
/Users/someone/_far2/far2l/colorer/src/Colorer-library/src/colorer/base/XmlTagDefs.h:20:13: error: array initializer must be an initializer list
const XMLCh catTagLocation[] = u"location\0";
            ^
/Users/someone/_far2/far2l/colorer/src/Colorer-library/src/colorer/base/XmlTagDefs.h:21:13: error: array initializer must be an initializer list
const XMLCh catLocationAttrLink[] = u"link\0";

--

$ clang++ -v
Apple clang version 15.0.0 (clang-1500.3.9.4)
Target: x86_64-apple-darwin23.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

Xcode Version 15.4 (15F31d)

macports:
xercesc3                       @3.2.4          textproc/xercesc3

**Comment by ctapmex** [comment]
which version/commit  far2l used ?
latest build on macso 14 arm https://github.com/elfmz/far2l/actions/runs/9148654886/job/25151429059

**Comment by ctapmex** [comment]
I don't have a mac handy. But I think the reason is the XMLCh type. Search in xerces-c port for a file with a name similar to Xerces_autoconf_config.php . Need a line
starting with `#define XERCES_XMLCH_T`

**Comment by mad-rain** [comment]
Here it is:

#define XERCES_XMLCH_T uint16_t

If I replace uint16_t with char16_t then I get this:

Undefined symbols for architecture x86_64:
  "xercesc_3_2::InputSource::setEncoding(char16_t const*)", referenced from:
      vtable for LocalFileXmlInputSource in libcolorer.a[37](LocalFileXmlInputSource.cpp.o)
      vtable for XmlInputSource in libcolorer.a[39](XmlInputSource.cpp.o)
  "xercesc_3_2::InputSource::setPublicId(char16_t const*)", referenced from:
      vtable for LocalFileXmlInputSource in libcolorer.a[37](LocalFileXmlInputSource.cpp.o)
      vtable for XmlInputSource in libcolorer.a[39](XmlInputSource.cpp.o)
  "xercesc_3_2::InputSource::setSystemId(char16_t const*)", referenced from:
      vtable for LocalFileXmlInputSource in libcolorer.a[37](LocalFileXmlInputSource.cpp.o)
      vtable for XmlInputSource in libcolorer.a[39](XmlInputSource.cpp.o)
...

**Comment by ctapmex** [comment]
replacing the type definition will not help here.
can you use the brew package to build?

at all(?) platforms xerces-c packages use char16_t for XMLCh.
I can fix this error, but the code will look very ugly. All the contents of the lines are of this type
`const XMLCh catTagCatalog[] = u"catalog\0";`
will be `const XMLCh catTagCatalog[] = {chLatin_c, chLatin_a, chLatin_t, chLatin_a, chLatin_l, chLatin_o, chLatin_g, chNull};`

**Comment by rampitec** [comment]
I had the same problem. It is macports, remove /opt/local/bin from PATH and use brew instead.

**Comment by rampitec** [comment]
> $ port MacPorts 2.9.3

Yep. This is the problem. Homebrew work for latest far2l, macports do not.

**Comment by mad-rain** [comment]
> replacing the type definition will not help here. can you use the brew package to build?
> 
> at all(?) platforms xerces-c packages use char16_t for XMLCh. I can fix this error, but the code will look very ugly. All the contents of the lines are of this type `const XMLCh catTagCatalog[] = u"catalog\0";` will be `const XMLCh catTagCatalog[] = {chLatin_c, chLatin_a, chLatin_t, chLatin_a, chLatin_l, chLatin_o, chLatin_g, chNull};`

It could be fixed like this:

const XMLCh *catTagCatalog = (const XMLCh *) u"catalog\0";
or
auto catTagCatalog = (const XMLCh *) u"catalog\0";

**Comment by elfmz** [comment]
some crutches were inserted, check now plz

**Comment by ctapmex** [comment]
@elfmz  
https://github.com/elfmz/far2l/commit/cfb1387f39a63cee9ae46235846613275d011ec6
why? okay with XMLCh, why change the rest? especially `optional'. this changes the logic of work, and moves away from upstream colorer.

maybe we'll roll it back, and I'll fix it in my own way?

**Comment by elfmz** [comment]
there is no C++17 in ElCapitan, not sure i can get it there, but people wants that old MacOS, prev time i've tried to abandon it rather quickly caused complains: https://github.com/elfmz/far2l/issues/2156

**Comment by elfmz** [comment]
It must be possible to add thin 'wrapper' header for needed stuff, also its needed not only for colorer, here another example: https://github.com/elfmz/far2l/blob/master/far2l/src/mix/RegExp.hpp#L49
That wrapper can be part of far2l only project, making ther sources compatible

**Comment by ctapmex** [comment]
that's why it was started https://github.com/elfmz/far2l/issues/2106 . We need to fix what we are focusing on. 
I suggest we roll it back anyway. I will use https://github.com/akrzemi1/Optional or an analog

**Comment by elfmz** [comment]
will do after release

**Comment by ctapmex** [comment]
which version gcc/clang on ElCapitan ?

**Comment by elfmz** [comment]
Its not a plain gcc/clang - its an Apple's own clone of clang (Apple uses its in XCode and invested into it rather lot):

```
$ c++ --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

$ c++ --std=c++17 -c test.cpp -o test.o
error: invalid value 'c++17' in '--std=c++17'

```

**Comment by elfmz** [comment]
Кстати а вы не находите что код с unique_ptr выглядит както проще)
![image](https://github.com/user-attachments/assets/7402fd84-8f94-4b7c-a626-f47707bea970)
и нету неявной зависимости на область валидности ссылок на элементы внутриunordered_map. Да я знаю что они остаются валидными, но ведь это знать надо:)

**Comment by rampitec** [comment]
> Кстати а вы не находите что код с unique_ptr выглядит както проще) ![image](https://private-user-images.githubusercontent.com/20957349/348977934-7402fd84-8f94-4b7c-a626-f47707bea970.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMTUwMDIsIm5iZiI6MTcyMTExNDcwMiwicGF0aCI6Ii8yMDk1NzM0OS8zNDg5Nzc5MzQtNzQwMmZkODQtOGY5NC00YjdjLWE2MjYtZjQ3NzA3YmVhOTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA3MjUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMjg0NWIxZmViYWE1YTI5MTAyYzVlZWFjMmRjNDg1Y2U1MzYwY2NhMDI0MThhYWQ4ZjRlYjY3YzY2NjA5MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0Dg8Yd1b5HbDwzMv0XBHf1xWlzvYmX3ywhcblRJh-6I) и нету неявной зависимости на область валидности ссылок на элементы внутриunordered_map. Да я знаю что они остаются валидными, но ведь это знать надо:)

Я не знаю, я привык. Но однако же "чума на оба ваши дома", мне голый C кажется проще и понятнее, особенно в отладчике. А как человек, котрый компилятор пишет по роду деятельности, я вообще в ужасе, что мне это все надо упрощать до голого интегрального типа. Не далее как сегодня продирался через все эти темплеты в отладчике, чтобы понять, что мы таки сумели это все убрать в простые 64 бита. Ужас, блин. Я понимаю, что оно так читается чуть лучше в исходнике, но вот лично я перестаю исхолник понимать. В среднем 30 лет разработки в C++ и 20 лет писания компилятора под C++ привели меня к мысли, что он не нужен.

**Comment by ctapmex** [comment]
> Кстати а вы не находите что код с unique_ptr выглядит както проще)

оно всегда проще, но надо вспомнить какой смысл я закладывал в это использование. 

> its an Apple's own clone of clang (Apple uses its in XCode and invested into it rather lot):

это и плохо. как тестировать на совместимость ?  вчера поставил ванильный clang 8, и код без этих изменений собрался на ubuntu 18.04.
выставить ограничение c++14?

**Comment by elfmz** [comment]
Да, самая большая разница между программирвоанием под винду и под юникс вовсе не в том что в винде CreateFile(), а в юниксе open(), а в том, что под виндой у тебя уютный компилятор любимой версии и унифицированное окружение, а юниксы - зоопарк окружений, причем твой проект собирают вооще другие люди с большинством из которых ты ваще никак не знаком, под железо которое ты никогда не брал в свои руки...

**Comment by elfmz** [comment]
> оно всегда проще, но надо вспомнить какой смысл я закладывал в это использование.

дык юзание unique_ptr в качестве optional вполне стандартная практика, они имеют свои различия в сематике, но не так чтобы optional must have.
https://stackoverflow.com/questions/44856701/what-to-use-stdoptional-or-stdunique-ptr

**Comment by ctapmex** [comment]
в изменении нет исправления c++17 на с++14  в  cmake - локально правил для сборки, или все же clang  проглатил это?

**Comment by elfmz** [comment]
Больше ничего не менял, очень даже может быть что там еще и cmake старый, который не понимает CXX_STANDARD 17
Это самое.. не надо ща переколбашивать сам колорер на C++11/14 надо взвесить и решить переходить на С++17 или нет. Что касается ElCapitan - возможно таки я смогу гдето найти xcode более свежей версии но не настолько свежей чтоб отказываться работать на ней. Это один фактор. Второй - остальные юзера, помниться както уже пытались включить какой то более свежий стандарт, но оказалась что в актуальном raspbian gcc идущий из репозитория на тот момент не поддерживал его. Можно както все актуальные вещи прошерстить и если все норм - то лично я не против С++ в принципе. Просто другое дело что в колорере в тех изменениях что я поправил я не заметил прям такой насущной необходимости его использовать. Понимаю там в виндовом фаре теперь 90% кода со строками работают на string_view что хорошо для перфоманса, а в колорере string_view только в одном месте замечен и то как альтернатива строковым литералам. Хотя это странновата - как раз таки колорер по идее должен заниматься всяким парсингом, для ускорения которого string_view и был придуман.

**Comment by ctapmex** [comment]
если указать жестко с++14 на gcc, то из кода colorer выбывают 

- std::string_view 
- std::optional (возможо действительно лишнее использование)
- std::size
- structured bindings
- std::filesystem  (уже есть враппер)

это то, что всплыло в ошибках сборки. возможно глубже что-то еще есть.

по поддержке с++17 в xcode тут неплохо расписано https://cibuildwheel.pypa.io/en/stable/cpp_standards/

**Comment by unxed** [comment]
@rampitec а приходите к нам в чят по far2l! Вас там очень не хватает.

https://t.me/far2l_ru

@elfmz приходите тоже! Я там на модерации, атмосфера здоровая, токсичности нет.

**Comment by ctapmex** [comment]
I suggest closing it, fixed a long time ago.

**Comment by unxed** [comment]
> there is no C++17 in ElCapitan, not sure i can get it there, but people wants that old MacOS, prev time i've tried to abandon it rather quickly caused complains: [#2156](https://github.com/elfmz/far2l/issues/2156)

Are we still limited in std::filesystem usage? ElCaptain do not receive security updates since 2018!

I don't think we should restrict the use of a convenient tool just so someone can stay on an insecure, unsupported system longer. Besides, no one is stopping you from continuing to use the current version.

UPD: colorer has header only std::filesystem polyfill, so not a problem any more:
https://github.com/elfmz/far2l/blob/master/colorer/src/Colorer-library/src/colorer/platform/filesystem.hpp

**Comment by unxed** [comment]
btw, colorer is using header only std::filesystem polyfill:
https://github.com/elfmz/far2l/blob/master/colorer/src/Colorer-library/src/colorer/platform/filesystem.hpp
