### ISSUE TITLE
Под ubuntu 24 собранный пакет не устанавливается, надо добавить libnfs14

### ISSUE THREAD

**Issue by daemonserj** [elfmz/far2l#2235]
Под ubuntu 24 собранный пакет не устанавливается.
Похоже в конфиг надо добавить libnfs14

Следующие пакеты имеют неудовлетворённые зависимости:
 far2l : Зависит: libnfs11 но он не может быть установлен или
                         libnfs12 но он не может быть установлен или
                         libnfs13 но он не может быть установлен

**Comment by atolismesh** [comment]
Прочитайте README.MD
Надо ставить libnfs-dev.
После этого cmake и apt сами найдут нужную версию

libnfs-dev/noble,now 5.0.2-1build1 amd64 [installed]
libnfs14/noble,now 5.0.2-1build1 amd64 [installed,automatic]
