### ISSUE TITLE
Clipboard problem in Wayland - doesn't copy clipboard content from Far2l into other applications

### ISSUE THREAD

**Issue by alexeyda** [elfmz/far2l#2238]
I can copy clipboard content from applications info Far2L, but cannot copy from Far2L into another applications.
It looks that the next screenshot is the source of the problem:
<img width="328" alt="image" src="https://github.com/elfmz/far2l/assets/7303443/f424fd38-1510-420b-b189-57b5bc63487a">

My current configuration is:
KDE Neon 22.04.
Plasma 6.0.4
Wayland

Here is the printenv output from far2l: [env.txt](https://github.com/elfmz/far2l/files/15447222/env.txt)

<img width="549" alt="image" src="https://github.com/elfmz/far2l/assets/7303443/25dc67a1-db57-43d7-8e50-2b78256f48c8">

**Update**: printenv with x11 settings:  [env-x11.txt](https://github.com/elfmz/far2l/files/15447248/env-x11.txt)
**Update2**: I can copy clipboard content to Firefox 126.0 (64-bit), but not to Chrome (Version 125.0.6422.112 (Official Build) (64-bit)), nor to Telegram

**Update3**:
```
jank@creator:~/.config$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=cs_CZ.UTF-8
LC_TIME=cs_CZ.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=cs_CZ.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=cs_CZ.UTF-8
LC_NAME=cs_CZ.UTF-8
LC_ADDRESS=cs_CZ.UTF-8
LC_TELEPHONE=cs_CZ.UTF-8
LC_MEASUREMENT=cs_CZ.UTF-8
LC_IDENTIFICATION=cs_CZ.UTF-8
LC_ALL=
```
**Update4**: Скрин Far2L
![image](https://github.com/elfmz/far2l/assets/7303443/ebb9758a-fc9f-4ef0-aa12-93e24d97715f)

**Update5**
>wx-config --version-full 
>3.0.5.0

**Comment by unxed** [comment]
Not reproducing in plasma 6.0.5:
https://t.me/far2l_ru/22365

**Comment by alexeyda** [comment]
> Not reproducing in plasma 6.0.5: https://t.me/far2l_ru/22365
The same (not correct) behaviour for me in Plasma 6.0.5

**Comment by unxed** [comment]
Проблема, похоже, в том, что far2l в некоторых окружениях выставляет тип контента `UTF8_STRING` вместо `text/plain;charset=utf-8`:

![изображение](https://github.com/elfmz/far2l/assets/1151423/45597f6b-d7f9-4ff3-8c9e-9039f87a28c4)
Источник: https://t.me/far2l_ru/22271

Ещё один пример:
https://github.com/elfmz/far2l/pull/2070#issuecomment-2201112446

**Comment by unxed** [comment]
Definitely an upstream issue:

https://github.com/wxWidgets/wxWidgets/issues/24701

**Comment by unxed** [comment]
Fixed in staging:
https://launchpad.net/~far2l-team/+archive/ubuntu/staging

**Comment by unxed** [comment]
Всё ещё вылезает на некоторых системах, пишут. Изучаю

**Comment by elfmz** [comment]
падает вроде изза wxTheClipboard->Flush();

**Comment by unxed** [comment]
вот я как раз Flush дописал в конец OnClipboardSetData и падать перестало, всё заработало как надо

**Comment by elfmz** [comment]
да в конце OnClipboardSetData он не падает, но смысл в нем там? Flush() типа персистит состояние клипборада на текущий момент, а данные в клипборд реально заносятся в OnClipboardClose, и вот после этого Flush валит систему.

**Comment by unxed** [comment]
а, ок)

от меня что-то ещё надо тогда?

**Comment by unxed** [comment]
Перепроверил. Да, если закомментить Flush всюду, всё тоже работает как надо.

**Comment by unxed** [comment]
Закинул в wx, там уже пусть разбираются, где оно сломано дальше по цепочке :)

https://github.com/wxWidgets/wxWidgets/issues/24707

**Comment by elfmz** [comment]
Чисто по поведению и глядя в код wxClipboard::Flush ( https://github.com/wxWidgets/wxWidgets/blob/master/src/gtk/clipbrd.cpp#L620 ) - думаю что проблема не в wx
