### ISSUE TITLE
не любой permission denied это повод показывать sudo-диалог

### ISSUE THREAD

**Issue by volth** [elfmz/far2l#224]
например:
```
$ mkdir xxx
$ touch xxx/yyy                                                
$ chmod 555 xxx/.                                              
$ rm xxx/yyy                                                   
rm: cannot remove 'xxx/yyy': Permission denied                                      
```
если файл ```xxx/yyy``` попробовать удалить в far2l, он спросит sudo пароль.

полный перечень таких ситуаций я привести не могу, и на этот случайно наткнулся.

**Comment by volth** [comment]
при заходе в каталог ```/proc/self/map_files``` зачем-то спрашивает sudo-пароль; можно нажать escape.

**Comment by volth** [comment]
при сохранении (F2 в редакторе) readonly-файла (права 444) тоже зачем-то спрашивается sudo-пароль.
при удалении такого файла пароль не спрашивается.

**Comment by elfmz** [comment]
А что предлагаете автоматом менять мод на время операции? А вдруг этот мод поставили специально, чтоб по пьяни конфиг не испортить.

**Comment by volth** [comment]
![ro-overwrite](https://cloud.githubusercontent.com/assets/508305/21294939/601c31f4-c541-11e6-9f78-7cd191cee67f.png)

**Comment by volth** [comment]
ещё м.б. случаи когда получение sudo-привилегий ничего не даст (попытка удаления файла на cdrom, например), тогда тоже не надо пароль спрашивать.

**Comment by elfmz** [comment]
cdrom'а нету под рукой, но сдается мне код ошибки там будет EROFS и от него sudo не вылезет

**Comment by elfmz** [comment]
ну вот кое чего сделал..
по поводу /proc/self/mapfiles - похоже без рутового доступа там нельзя сделать stat/readlink на элементы. А это нужно для корректного отображения списка

**Comment by volth** [comment]
ещё один вариант read-only: ```chattr +i file``` и такой файл не удалить пока не сделано ```chattr -i file```.
при попытке удалить такой файл sudo-попап появляется даже если far2l запущет под root.

**Comment by elfmz** [comment]
снятие/установка +i все равно sudo требует (неохота возиться с capabilities)
но оно действительно не обрабатывалось как следует, что пофикшено

**Comment by elfmz** [comment]
думаю можно закрыть, переоткрывайте если еще где вылезет
