### ISSUE TITLE
Strange line breaks and missing whitespaces in the viewer

### ISSUE THREAD

**Issue by dstd** [elfmz/far2l#2246]
Steps to reproduce:
1. Take the file https://github.com/elfmz/far2l/blob/master/far2l/src/vmenu.cpp 
3. Open it in the viewer 
4. Search for `::setselectpos`, scroll up - the text that will appear on the screen looks ugly, [image 1]
5. Press F6 to switch into the editor, the code will look good now, [image 2]
6. Press F6 to switch back into the viewer, now the text is displayed correctly either, [image 3]
7. Scroll up - the text that appears is again with bad indentation and wrapped with empty lines

Tried on [far2l-2.6.1_hotfix1-beta-MacOS-11.2-universal.dmg], both in GUI-backend and in TTY-backend.
I thought (and encountered it before) that it's due to UTF-8 view mode, but on vmenu.cpp it happens with ANSI codepage too.

Image 1:
![image](https://github.com/elfmz/far2l/assets/1444844/05cc0be3-8252-4862-9871-d5eb98fcde9e)

Image 2:
![image](https://github.com/elfmz/far2l/assets/1444844/aa2dcae7-49d9-43b9-a2c9-557fc5adb5de)

Image 3:
![image](https://github.com/elfmz/far2l/assets/1444844/67fd3a25-9c03-433c-8179-1e32fbd822c6)

**Comment by akruphi** [comment]
Such line breaks are not reproduced for me in `2.6.1-2024-06-04-51cf4e3d` in Ubuntu. 

But after each switching by **F6** top line in editor/viewer windows changing and for some position in viewer starting inside line (beginning part of line initially out of windows and during scroll show as separate line). May be really position detection or transfer top visible line is not quite correct.

**Comment by spnethw** [comment]
Well, I think I was able to reproduce this bug. 
The necessary condition for me is "wrap type: words" (Shift-F2, "WWrap").

**Comment by spnethw** [comment]
Maybe the problem is somewhere in these lines.
https://github.com/elfmz/far2l/blob/51cf4e3db9869658fe54671701063d66a92b6d32/far2l/src/viewer.cpp#L2081-L2109

**Comment by elfmz** [comment]
check now please

**Comment by spnethw** [comment]
Looks better, but something is buggy.

![изображение](https://github.com/elfmz/far2l/assets/161581982/9275b23b-21db-46f8-937b-0894e5830cc3)

Also, now there are one extr spaces at the beginning of each line while scrolling up.
![изображение](https://github.com/elfmz/far2l/assets/161581982/39c7019c-3b69-4eea-9d86-d9c35ac82a3c)

**Comment by dstd** [comment]
> Which wrap mode are you using? Can you change it to another _(Wrap, Unwrap in my case)_ and try again? will the bug happen then?

@spnethw, tried your suggestion – yep, it only happens in WWrap mode. In other modes all seems to work fine.

**Comment by dstd** [comment]
> check now please

I'm sorry, but I have no ability to build an app by myself right now :(

**Comment by dstd** [comment]
> check now please

@elfmz I'm sorry, but I have no ability to build an app by myself right now :(

**Comment by elfmz** [comment]
@spnethw what about now?
