### ISSUE TITLE
Prevent crash on editing /swapfile

### ISSUE THREAD

**Issue by shmuz** [elfmz/far2l#2262]
Если выйти в корень диска и нажать F4 на /swapfile, то после ввода пароля происходит PANIC PANIC PANIC.
Это у меня на Mint 21.3 (у другого пользователя на Ubuntu 22.04 это не воспроизвелось).
В far2m это вылечилось так: https://github.com/shmuz/far2m/commit/c565289d318fd68d92855814cd3dbc4465691896.

**Comment by shmuz** [comment]
Дополню. Это не обязательно должен быть /swapfile,
Это может быть файл в любом месте, достаточно большого размера (например 500 МБ) и у которого нет read permission для пользователя, чтобы фар вывел диалог sudo.
После нажатия на файле F4 и ввода правильного пароля - падаем.

**Comment by elfmz** [comment]
Ну проблема там в том первый CheckForEscSilent вызываался до Editor::EditorShowMsg, который выставляет параметры для этой pre-redraw штуки, порядок видимо изменился на неправильный в ходе какогто рефакторинга.. ЗЫ Надо бы эту pre-redraw переделать на чтото более вменяемое.
