### ISSUE TITLE
i'm trying to install Far on Astra Linux.

### ISSUE THREAD

**Issue by AlexKuha** [elfmz/far2l#2264]
Got this gui 

![image](https://github.com/elfmz/far2l/assets/96182300/a5ef45b8-1249-4eaa-b70a-11f25ace1fcf)

What to change for normal font?
Sorry if this is not a normal place to ask

tnx

**Comment by akruphi** [comment]
In my Ubuntu 22.04 I use font `Ubuntu Mono Regular` and has not such problems. You can change font by **F9**->**Options**->**Interface**->**Change font** to any appropriate mono font.
