### ISSUE TITLE
ошибки линковки плагинов

### ISSUE THREAD

**Issue by volth** [elfmz/far2l#227]
1. вот [тут](https://github.com/elfmz/far2l/blob/9018aa0e4a300e3b2cfca90505be8cbbb0c81f4f/farftp/src/fUtils.cpp#L488) вызывается функция ```FP_CopyToClipboard``` определённая в файле [fstd_ClpS.cpp](https://github.com/elfmz/far2l/blob/9018aa0e4a300e3b2cfca90505be8cbbb0c81f4f/farftp/src/FStdLib/FARStdlib/fstd_ClpS.cpp) который ещё не портирован с Windows и не включён в сборку.

2. [тут](https://github.com/elfmz/far2l/blob/9018aa0e4a300e3b2cfca90505be8cbbb0c81f4f/multiarc/src/formats/zip/zip.cpp#L265) вызыватся функция ```GetArcItem``` которая объявлена в [fmt.hpp](https://github.com/elfmz/far2l/blob/9018aa0e4a300e3b2cfca90505be8cbbb0c81f4f/multiarc/src/fmt.hpp#L83) однако её нигде нет. Возможно, там должно быть ```ZIP_GetArcItem```.

3. в плагине multiarc [вот тут](https://github.com/elfmz/far2l/blob/9018aa0e4a300e3b2cfca90505be8cbbb0c81f4f/multiarc/src/ArcProc.cpp#L319) нужно или добавить SHAREDSYMBOL (по сути export "C") в начало строки или сделать эту функцию не экспортируемой, т.к. сейчас получается, что .so экспортирует две функции: одна с именем ```Configure``` и вторая с ```_Z9Configurei``` и без адреса.

На Linix Mint эти плагины с отсутсвующими функциями как-то запускались, а на nixos нет.

**Comment by elfmz** [comment]
3. я конечно это поправлю, но .so не должна экспортировать то что не SHAREDSYMBOL, _export задефайнена в пустой макрос, а экспорт всех не-static функций задавлен этим вот:
set(CMAKE_CXX_VISIBILITY_PRESET hidden)
set(CMAKE_C_VISIBILITY_PRESET hidden)
что включает опцию -fvisibility=hidden

**Comment by volth** [comment]
"я конечно это поправлю, но .so не должна экспортировать то что не SHAREDSYMBOL"

Может и не должна, но экспортирует. 
Даже если собирать на Linux Mint (можете посмотреть с помощью ```nm -g file.so```

**Comment by lieff** [comment]
Ндежнее скрывать экспорты -Wl,--version-script=so.exports и файлом вида:
```
 {
global:
  JNI_*;
  Java_*;
  local: *;
};```
Тогда точно ничего лишнего торчать не будет.
