### ISSUE TITLE
Plugin Colorer crashes

### ISSUE THREAD

**Issue by shmuz** [elfmz/far2l#2277]
При обычной работе не падает, а в следующем сценарии падает вместе с фаром:
1. Открыть в редакторе фара любой файл и закрыть
2. Выгрузить плагин (`PCTL_UNLOADPLUGIN`)
3. Загрузить плагин (`PCTL_FORCEDLOADPLUGIN`)
4.  Выгрузить плагин (`PCTL_UNLOADPLUGIN`) - падение

Лечится добавлением в конец функции `ExitFARW` строчки `editorSet = nullptr;`.
Почему плагин не выгружается из памяти командой `PCTL_UNLOADPLUGIN` это другой вопрос, его не исследовал.

**Comment by ctapmex** [comment]
>Почему плагин не выгружается из памяти командой PCTL_UNLOADPLUGIN это другой вопрос, его не исследовал.

это интересный момент. По коду все действия делаются , и модуль закрывается. Но всё равно попадаем на старую память

**Comment by elfmz** [comment]
полагаю пофикшено? закрываю
