### ISSUE TITLE
переименование каталогов содержащих симлинки

### ISSUE THREAD

**Issue by volth** [elfmz/far2l#228]
делаем каталог с файлом и симлинком на этот файл:
![mkdir](https://cloud.githubusercontent.com/assets/508305/21300757/da6f51fe-c59e-11e6-8c50-8db2c7129baa.png)

переменовываем этот каталог:
![f6](https://cloud.githubusercontent.com/assets/508305/21300762/e9ae929c-c59e-11e6-87df-a3dd9c06fa71.png)

получаем ошибку:
![f6-err](https://cloud.githubusercontent.com/assets/508305/21300766/f0bbe38c-c59e-11e6-86f4-b4b929175659.png)

**Comment by lieff** [comment]
Кстати а почему оно вообще смотрит на то что внутри? На винде переименование каталога, если он при этом не переносится на другой диск, происходит моментально сколько бы файлов там ни было, и внутрь не смотрит.

**Comment by elfmz** [comment]
а потому что баги еще есть.. буду фиксить
