### ISSUE TITLE
Far2l Summer Release Date before Ubuntu 24.10 Debian Import Freeze

### ISSUE THREAD

**Issue by akruphi** [elfmz/far2l#2280]
**Ubuntu 24.10 Debian Import Freeze** will be **August 15** (https://discourse.ubuntu.com/t/oracular-oriole-release-schedule/36460).

@elfmz and @alexmyczko tell your opinion about appropriate date far2l release.

@alexmyczko how many days your need to try prepare from new release the separate debs for each backend as suggested in https://salsa.debian.org/debian/far2l/-/merge_requests/1 ? If release will be **July 31** will it be enough days for your to guaranteed put debs in Debian before August 15 or your need more days?

---
Some not resolved important issues yet:
#2088 UPD: COMPLETE
#2158
#2157
#2275 UPD: temporary done
#2238 ~UPD: COMPLETE~ ~UPD2: regression detected (waiting fixes from @unxed )~ UPD3: FIXED :fire: 

@unxed @spnethw @shmuz @ctapmex please write your opinion and links to other important issues.

**Comment by alexmyczko** [comment]
if you can release by 12th of July I will have some time to do the split as merge requested and finally be done. sorry for postponing it so long...

**Comment by unxed** [comment]
Closed #2088 as complete. Made PR with a fix for #2238. The last Wayland issue remaining, #1695, is not reproducing in my test setups. Remaining unicode and viewer issues probably still need a lot of work to be done, let's postpone.

**Comment by unxed** [comment]
> if you can release by 13th of July

@elfmz

**Comment by alexmyczko** [comment]
swiss airplane did not arrive because of some rain drops, thus I was stuck in the duty free store at WAW since yesterday, they were only be able to find a new plane for me tomorrow. I will hopefully get home tomorrow where I can do something...

**Comment by alexmyczko** [comment]
@akruphi will the planned for 31 July release drop the BETA letters? I wish it would release 24 July, it would give me some time to prepare, build, and test...

**Comment by akruphi** [comment]
> I wish it would release 24 July

Wow!!! @alexmyczko gives additional time until **24 July**!!!

@elfmz if it possible please look at the following issues:
#2263 
#2283 
#2257

**Comment by alexmyczko** [comment]
i mean this is just what i would like/prefer. you can take any time
you want, my wish is not authoritative :)

**Comment by unxed** [comment]
Shouldn't we fix
https://github.com/elfmz/far2l/issues/2204
also?

**Comment by unxed** [comment]
@akruphi pls add #2204 to the opening post

**Comment by akruphi** [comment]
About #2238: regression detected (waiting fixes from @unxed )

**Comment by unxed** [comment]
If at all they turn out to be possible on our side.  I'll take a look again this afternoon

**Comment by unxed** [comment]
#2238 finally fixed

**Comment by akruphi** [comment]
@alexmyczko Fresh [2.6.2 BETA](https://github.com/elfmz/far2l/releases/tag/v_2.6.2)

**Comment by unxed** [comment]
#2288 was a serious problem affecting UX. What about 2.6.2.1? @alexmyczko @elfmz

**Comment by elfmz** [comment]
Whats deadline for that? Also why not 2.6.3?)

**Comment by akruphi** [comment]
As I see in https://packages.debian.org/search?keywords=far2l **2.6.2** now in Debian but use current-style (only TTY|Xi version with excessive dependencies on X11 libs, which in my opinion does not suite for some servers).

I hope multibinary versions according ideas https://salsa.debian.org/debian/far2l/-/merge_requests/1 will be technically prepared in July.

Idea: when technically multibinary versions will be ready locally (but not send to debian) @alexmyczko informs here and @elfmz make urgently (during 1-2 days) release and new release will be send as multibinary.

Is this idea convenient for @alexmyczko and @elfmz ?

**Comment by unxed** [comment]
2.6.3 is ok, of course!

**Comment by elfmz** [comment]
So, whats the plan? release before 24 or by signal?

**Comment by elfmz** [comment]
24 is tomorrow, any reason to (not) create 2.6.3?

**Comment by unxed** [comment]
https://github.com/elfmz/far2l/issues/1568#issuecomment-2245153188

?

**Comment by unxed** [comment]
> [#1568 (comment)](https://github.com/elfmz/far2l/issues/1568#issuecomment-2245153188) 
> ?

[Done](https://github.com/elfmz/far2l/pull/2302)

**Comment by alexmyczko** [comment]
i would prefer earlier release as i will need to get the packaging right and uploaded. then we have to ask ftp-master for an express processing as adding new binary packages requires to go throug new quque.

but then i could do so with current version so ftp-master has some more time. after it is through that upgrading is possible immediately, half a day, need to have computer and internet. i guess i will try that until weekend and be done with it.

**Comment by spnethw** [comment]
@alexmyczko  I'm not sure I understand you right. But I think we are ready to release the new version (2.6.3).
@unxed @elfmz Don't we?
@alexmyczko Will that suit you?

**Comment by elfmz** [comment]
I'm ok, i can create release right now if it makes sense

**Comment by unxed** [comment]
+

**Comment by unxed** [comment]
I think we're ready

**Comment by elfmz** [comment]
release also ready now :)

**Comment by akruphi** [comment]
@alexmyczko please inform about far2l 2.6.3 multipackaging progress in Debian. If useful community testing and feedback you can put draft debs here or in tg-chat.

**Comment by alexmyczko** [comment]
the -2 is the split pkg http://bananas.debian.net/debian/far2l/3/

**Comment by akruphi** [comment]
Brief situation with Debian/Ubuntu packages:
* in Ubuntu Oracular 24.10 only **2.6.2~beta+ds-1** (TTY|Xi inside): https://packages.ubuntu.com/search?keywords=far2l
* in Debian sid (unstable) now **2.6.3~beta+ds-1** (TTY|Xi inside): https://tracker.debian.org/pkg/far2l
* Debian **2.6.3~beta+ds-2** with different packages (`far2l`=TTY|Xi, `far2l-tiny`, `far2l-nox`=TTY, `far2l-wx`=GUI) **waiting approve**: https://tracker.debian.org/pkg/far2l

Between 2.6.2 and 2.6.3 in Debian problem (solved in https://github.com/elfmz/far2l/pull/2340) changed from Warning to Error and due it now missing mandatory builds on **armel** and **armhf**: https://tracker.debian.org/pkg/far2l

Also @alexmyczko please in future in all Debian debs:
- move `chafa`, `htop` from `Recommends` to `Suggests` because all tools from `*.sh` only additional and not necessary for  work

@elfmz may be after accept recent imortant PRs (#2333 and #2340) time to release 2.6.4 and try put it in Debian without haste.

---

Discussion idea/question about packages naming in Debian:
due to global trend to remove X11 from distribs (for example https://gitlab.gnome.org/GNOME/mutter/-/issues/2272, https://opennet.ru/61723/, https://opennet.ru/61336/ etc.) may be in Debian swap names of packages:
* `far2-wx` -> `far2l` (GUI wx with plugins) - make wx as default
* `far2` -> `far2l-x` (console with X support with plugins)
* `far2-nox` (console without X with plugins) - not change name
* `far2-tiny` (compact console without plugins) - not change name
???

**Comment by alexmyczko** [comment]
good summary, what we do now?

**Comment by akruphi** [comment]
Continue in #2419
