### ISSUE TITLE
copy/paste problem under wslg

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#2288]
В чате пишут: под wslg в редакторе при копировании и вставке вставляется ещё лишний перевод строки. Вероятно, ошибка в [скриптах](https://github.com/elfmz/far2l/commit/cdf62324d6868563a9bfdeba5b617eb7e41b6515), которые под wslg для работы с буфером обмена применяются. И ещё, я не уверен, что после https://github.com/elfmz/far2l/commit/929024e1a649c386625a097bd4f3e33d331f3a9d эти скрипты в принципе актуальны. Это проверить бы, но у меня нет wslg.

In the chat they write: under wslg, in the editor, when copying and pasting, an extra line break is inserted. There is probably an error in the [scripts](https://github.com/elfmz/far2l/commit/cdf62324d6868563a9bfdeba5b617eb7e41b6515) that are used under wslg for clipboard access. And yet, I’m not sure that after https://github.com/elfmz/far2l/commit/929024e1a649c386625a097bd4f3e33d331f3a9d these scripts are actually relevant. I would check this, but I don't have wslg.

**Comment by unxed** [comment]
Possible workaround is to use this command to run far2l
```
FAR2L_WSL_NATIVE=1 far2l
```

**Comment by unxed** [comment]
> Possible workaround is to use this command to run far2l
> 
> ```
> FAR2L_WSL_NATIVE=1 far2l
> ```

@shmuz [says](https://t.me/far2l_ru/25243) in chat that this workaround is working.

**Comment by unxed** [comment]
> Possible workaround is to use this command to run far2l
> 
> ```
> FAR2L_WSL_NATIVE=1 far2l
> ```

@shmuz [says](https://t.me/far2l_ru/25243) in chat that this workaround is working.

UPD: There is also [evidence](https://t.me/far2l_ru/25257) that in this way the clipboard starts to work only inside far2l, but not with other applications.

**Comment by unxed** [comment]
Replacing
```
    echo "$CONTENT" | clip.exe
    echo "$CONTENT"
```
with
```
    echo -n "$CONTENT" | clip.exe
    echo -n "$CONTENT"
```
in  `wslgclip.sh` fixes this issue.

**Comment by atolismesh** [comment]
Надо поменять в скрипте 
/usr/local/share/far2l/wslgclip.sh (far2l/bootstrap/wslgclip.sh) 
```
    echo  "$CONTENT" | clip.exe
    echo  "$CONTENT"
```
на 
```
    echo -n "$CONTENT" | clip.exe
    echo -n "$CONTENT"
```

**Comment by unxed** [comment]
Там ещё в wsl[g] обнаружились проблемы с кодировками при работе с буфером обмена. Поправили. У кого такое было, перепроверьте, пожалуйста, на свежем мастере.

In wsl[g] were discovered problems with encodings when working with the clipboard.  They are now fixed.  If anyone has had such problems, please check again in recent master.
