### ISSUE TITLE
remove the white bar at the bottom of the interface.

### ISSUE THREAD

**Issue by lucasfellipe3g** [elfmz/far2l#2298]
hello, guys! how can I remove this white bar at the bottom of the interface? is there any way?
![CleanShot 2024-07-21 at 15 30 35@2x](https://github.com/user-attachments/assets/a3083b5d-b65d-41c4-9b77-0678462fbd90)

**Comment by elfmz** [comment]
This bar is subsequence of fact that window height is not multiple of used font height, so its irremovable, but however can be painted black, would it be ok for you?

**Comment by unxed** [comment]
Better to use color used as internal VT's background color.

**Comment by lucasfellipe3g** [comment]
> This bar is subsequence of fact that window height is not multiple of used font height, so its irremovable, but however can be painted black, would it be ok for you?

yeah! how can I do this?

**Comment by lucasfellipe3g** [comment]
> Better to use color used as internal VT's background color.

how?

**Comment by unxed** [comment]
Source code must be changed to achieve this

**Comment by elfmz** [comment]
fixed in latest release
