### ISSUE TITLE
far suspends, when oppening file using xdg-open

### ISSUE THREAD

**Issue by invy** [elfmz/far2l#23]
For example, when pressing enter on some document, far suspends.
After using 'fg' in the shell, from which far2l was started, far 'wakes up'.

CreateFile: /home/igor/Downloads/165287006-0.pdf - dwDesiredAccess=0x1 flags=0x80000 path=/home/igor/Downloads/165287006-0.pdf r=8
ExplodeCmdLine('165287006-0.pdf') -> '165287006-0.pdf' 
IsPossibleXDGOpeSubject('165287006-0.pdf') - not executable mode=0x81b4
CommandLine::ShowBackground: done
CommandLine::SaveBackground: done
farExecuteA:('xdg-open ./165287006-0.pdf', 0x2, (nil)): r=0
zsh: suspended (tty input)  ./far2l

% fg
[1]  + continued  ./far2l
WinPortFSNotify('/home/igor/Downloads') - watching

**Comment by invy** [comment]
After recent commits far doesn't suspend, but despite far is writing, that it's executing "xdg-open", nothing is happening. (I think the problems are linked, or it's another issue?)

Something like this:

CreateFile: /home/igor/docs/balatex-img4.png - dwDesiredAccess=0x1 flags=0x80000 path=/home/igor/docs/balatex-img4.png r=8
ExplodeCmdLine('balatex-img4.png') -> 'balatex-img4.png' 
IsPossibleXDGOpeSubject('balatex-img4.png') - not executable mode=0x81b4
CommandLine::ShowBackground: done
CommandLine::SaveBackground: done
farExecuteA:('xdg-open ./balatex-img4.png', 0x2, (nil)): r=0
WinPortFSNotify('/home/igor/docs') - watching
CommandLine::ShowBackground: done
OnKeyDown: 0 172 0 219031871
ConsoleInput::Enqueue:  0 d 0 DOWN
OnChar: d d 0 219031871 _lk_ts=219031871 _lk_enqueued=1
CreateFile: /home/igor/docs/balatex-img3.png - dwDesiredAccess=0x1 flags=0x80000 path=/home/igor/docs/balatex-img3.png r=8
ExplodeCmdLine('balatex-img3.png') -> 'balatex-img3.png' 
IsPossibleXDGOpeSubject('balatex-img3.png') - not executable mode=0x81b4
CommandLine::ShowBackground: done
CommandLine::SaveBackground: done

**Comment by invy** [comment]
Far is creating a bunch of background processes:
![image](https://cloud.githubusercontent.com/assets/833865/18175468/b43e1b82-7071-11e6-9c24-4d58b949abfb.png)

**Comment by elfmz** [comment]
can you go execute.cpp find and replace there -ci with -c ?

**Comment by invy** [comment]
Yes, this fixes the problem.

**Comment by elfmz** [comment]
ok.. then put -ci back :) and try another change: in the NotVTExecute() just before ExecuteOrForkProc call insert line:
setsid();

**Comment by invy** [comment]
It kinda works, however as a side effect spawns a bunch of zombies :)
igor:~/docs% ps aux | grep xdg
igor      2974  0.1  0.0      0     0 ?        Zs   19:24   0:00 [xdg-open] <defunct>
igor      3084  0.1  0.0      0     0 ?        Zs   19:25   0:00 [xdg-open] <defunct>
igor      3145  0.2  0.0      0     0 ?        Zs   19:25   0:00 [xdg-open] <defunct>
igor      3184  0.2  0.0      0     0 ?        Zs   19:25   0:00 [xdg-open] <defunct>
igor      3219  0.2  0.0      0     0 ?        Zs   19:25   0:00 [xdg-open] <defunct>
igor      3255  0.3  0.0      0     0 ?        Zs   19:25   0:00 [xdg-open] <defunct>
igor      3283  0.4  0.0      0     0 ?        Zs   19:25   0:00 [xdg-open] <defunct>

**Comment by lieff** [comment]
Looks like we need -c switch in case of EF_NOWAIT execute flag and -ci without to switch non-interactive and interactive mode.

**Comment by elfmz** [comment]
First need to see the reason why it happens. Otherwise it can happen again due to something else.

**Comment by elfmz** [comment]
2 invy check - now there should be only one zomby per single moment of time

**Comment by invy** [comment]
yep, there's only one zombie now

**Comment by elfmz** [comment]
one zombie is not yet an Apocalypse, so closing..
