### ISSUE TITLE
F3 на пустом каталоге показывает значение отличное от нуля

### ISSUE THREAD

**Issue by volth** [elfmz/far2l#230]
F3 на пустом каталоге показывает значение отличное от нуля (какое именно - зависит от типа файловой системы, на ext4 обычно ```4096```, на btrfs ```0``` или несколько десятков байт).

Предполагается, что это сумма размеров всех файлов в каталоге. В Far для Windows это 0.

**Comment by elfmz** [comment]
Есть другое аргументированное мнение согласно которому размер который репортит фар должен быть равен размеру который репортит du -bs и mc. Собственно на это была серия фиксов.

**Comment by volth** [comment]
ну, может быть...

хотя я бы предпочёл, чтобы этот результат совпадал с тем, что показывает multiarc при заходе в архив этого каталога; т.е. сумма размеров файлов не считая "размера каталогов".

F3 достаточно часто использую для оценки, есть ли что интересного внутри каталогов, если да, то в каких; например, после ```git clone``` неизвестного проекта выделяю каталоги и нажимаю F3 - становится примерно понятно в какой каталог заходить.

**Comment by lieff** [comment]
Кстати да, а вот зачем знать размер мета информации каталога придумать сложно, покрайней мере мета инфу от инфы разделять

**Comment by elfmz** [comment]
Как вариант сделать глобальную настройку. Или по Shift+F3. Или то и то.
Кстати Shift+F3 не занят ничем вроде?
