### ISSUE TITLE
поиск в F3-вьювере не находит строки если выбрана кодировка UTF-8

### ISSUE THREAD

**Issue by volth** [elfmz/far2l#231]
Если в F3-вьювере выбрана кодировка UTF-8 он может не найти строку которая точно в файле есть.
Например в файле ```far2l``` не находится строка "Configure".
![search](https://cloud.githubusercontent.com/assets/508305/21316787/3b0a4f22-c5fa-11e6-91bd-41b42136b5e8.png)

Поиск по Alt-F7 эту строку там находит, даже если явно указать поиск не по "All code pages", а по "UTF-8"

**Comment by volth** [comment]
а если поискать строку GNU (вот они две на экране видны), то он находит первую GNU два раза (первый раз не доходя два символа до неё, второй раз уде на своём месте)

**Comment by lieff** [comment]
при просмотре бинарных данных еще он похоже изначально несовсем правильно показывается. Если 2 раза нажать F4 вид уже не тот что изначально. Еще pgup\down листают неравнозначно в хексе.

**Comment by elfmz** [comment]
дык это потому что файл нифига не UTF8, он перед поиском конвертит файл в UTF32 и ищет уже по том что сконвертилось, а поскольку файл битый то рандомные куски не конвертятся, и если нужный текст попадает в такой кусок его и не находит
воркэраунд - перейти по F8 в однобайтную кодировку

**Comment by volth** [comment]
текстовой файл тоже запросто может оказаться "битым", у нас тут половина исходников такие были совсем недавно.

поиск работает только до первого битого символа и на нём молча прекращает искать?

**Comment by lieff** [comment]
А F4-F4 еще и лечит)

**Comment by elfmz** [comment]
Поиск работает по тому что сконвертилось. Что конверсия из UTF8 не шмогла сконвертить - там и не ищем. А конвертит оно построчно.
НО и наверно нужно можно там заюзать fail-tolerant конверсию, которую я для не-UTF8 имен файлов делал..

**Comment by volth** [comment]
построчно это как-то неправильно.
при открытии бинарного файла, "строка" может и в память не поместиться, особенно если её в UTF32 конвертить.

**Comment by lieff** [comment]
Ну и должно быть что или сконвертилось или нет, а не так что F4-F4 и все сильно меняется, включая то что дальгие ascii строки начинают находиться.

**Comment by cycleg** [comment]
Где-то тут кодировка порылась, несомненно, но дело не в ошибках перекодирования.

Берем простейший файл, который во все буферы помещается с ногами:
```
ББЮ
<.h>
Б
<.h>
```
Кодировка UTF-8, без BOM, конец строки -- "\n", общая длина -- 20 байтов. Лезем грязными руками в метод Viewer::Search() и для подстроки ".h" выводим переменные MatchPos и SearchLength в том месте, где их уже собираются применить для [выделения текста на экране](https://github.com/elfmz/far2l/blob/9ed8fff0260353d14440adf613096b215d8451bd/far2l/viewer.cpp#L2546): 5, 8, 15, 16. Длина подстроки все время одинаковая: 2. Из этих данных видно, что во-первых количество вхождений подстроки удваивается, во-вторых, второе (четное) вхождение подстроки явно связано с числом "широких" символов. Данные символы кириллицы дают каждая по 1 "лишнему" байту. Если из первой строки файла убрать буквы "Б", то второе вхождение будет на позиции 6, т.е. расстояние будет таким же, как между 3 и 4 вхождениями. Если считать "по буквам", включая "невидимые" символы, то нечетные вхождения -- правильные, четные -- ложные.

Отображаются же "истинные" вхождения на экране неправильно, а "ложные" -- правильно. Кроме того, при отображении первого вхождения будет заскок с выводом на экран (файла вообще не покажут). Вот такие интересные наблюдения.

**Comment by cycleg** [comment]
Нет, наврал. Если считать "по буквам", то "истинное" значение вообще только первое. А вот если считать "по байтам", то "истинные" как раз четные значения. Такое впечатление, что выделение текста на экране делается "по байтам". И тогда понятен глюк с выводом самого первого ("ложного") вхождения: 5 попадает в середину буквы "Ю", и при выводе на экран случается нехорошее.

А вообще, кажется, корень бед лежит в позиционировании при поиске. В Viewer::Search() переменные LastSelPos и CurPos с одной стороны соответствуют [текущей позиции в файле](https://github.com/elfmz/far2l/blob/4a4029a0b898e3cb9b6140537fb4aa8eee21f516/far2l/viewer.cpp#L2421), а с другой -- [положению широкого символа](https://github.com/elfmz/far2l/blob/4a4029a0b898e3cb9b6140537fb4aa8eee21f516/far2l/viewer.cpp#L2515). И стоит только границе символа в файле не совпасть с порядковым его номером, как в нашем случае, начинается странное. Разумеется, это играет только для мультибайтовых символов.

**Comment by lieff** [comment]
Пробелма F4-F4 все еще осталасть. Если смотреть какой-нибудь бинарный wav файл, картина сильно меняется.

**Comment by elfmz** [comment]
F4-F4 сбрасывает кодировку на 1251
но в целом проблемы еще остались так что баг переоткрою

**Comment by cycleg** [comment]
В Viewer::Search() имеет место некая нескладушка для того же UTF-8. Сначала размер буфера для считывания текста определяется как [размер массива wchar_t](https://github.com/elfmz/far2l/blob/4d33a48d00b75f36fa73101ef75309b6004861ca/far2l/viewer.cpp#L2388):

```
wchar_t Buf[8192];
...
int BufSize=ARRAYSIZE(Buf);
```

Затем выясняется, сколько [символов wchar_t реально прочитано](https://github.com/elfmz/far2l/blob/4d33a48d00b75f36fa73101ef75309b6004861ca/far2l/viewer.cpp#L2423) из файла:

```
(ReadSize=vread(Buf,BufSize,SearchHex!=0))
```

И после поиска в буфере [проверяется](https://github.com/elfmz/far2l/blob/4d33a48d00b75f36fa73101ef75309b6004861ca/far2l/viewer.cpp#L2520):

```
if ((ReverseSearch && CurPos <= 0) || (!ReverseSearch && ReadSize < BufSize))
  break;
```

Для прямого поиска если прочитано меньше, чем емкость буфера, то поиск прекращается. Но для UTF-8 ReadSize запросто может оказаться меньше BufSize. И получается, что после первого же считывания в буфер, если искомой строки нет, то и поиск заканчивается неудачно.

За примером далеко ходить не надо: тот же файл "far2l/viewer.cpp"; подстрока "vseek" в нем не находится, если искать от начала файла.

**Comment by cycleg** [comment]
С такими небольшими в целом правками поиск работает в первом приближении правильно. Единственное, что вызывает сомнения -- работа с UTF-32. Для них ведь исходная парадигма "один символ -- фиксированное число байтов в файле" выполняется.

[viewer.cpp.diff.zip](https://github.com/elfmz/far2l/files/691496/viewer.cpp.diff.zip)

**Comment by elfmz** [comment]
Configure нынче находится
