### ISSUE TITLE
apiEditorControl(ECTL_READINPUT, ...) does not report pressed VK_RETURN when macro exist on CtrlEnter

### ISSUE THREAD

**Issue by rampitec** [elfmz/far2l#2325]
The issue is a Far regression and affects IncSrch plugin. 

When plugin is in the search loop after pressing ^I, given that ^I hotkey macro is used (equivalent of editor's F11 -> Incremental Search -> Search Forward), it enters an input read loop in the control.c::CollectEvents(). The combination ^Enter shall search next occurrence and ^#Enter shall search previous. Starting at some point it does not happen in far2l anymore.

The apiEditorControl(ECTL_READINPUT, ...) does not properly handle this key combination. I have modified the loop and instrumented it to collect incoming events. We have: key down for Ctrl, then we expect VK_RETURN with Ctrl down state, but it cames with bKeyDown=false, as if it were a release of the Enter key. The actual keypress with bKeyDown=true never comes to ECTL_READINPUT if Ctrl is pressed.

This is the regression, it used to work and still works on Windows.

For the sake of debugging I have created a debug branch with the modified logic and logging in the https://github.com/rampitec/far2l/tree/incsrch-readinput-loop-debug branch of my far2l fork.

UPD: It does not work if macro exists on ^Enter. The keypress seems to be consumed by the macro processing. However, it used to be returned to the plugin earlier and is returned to the plugin by with Windows Far2 1807. The macro is neither played, nor sent to plugin in the expanded or raw form.

**Comment by unxed** [comment]
Steps to reproduce:

1. Put
```
[KeyMacros/Editor/CtrlEnter]
DisableOutput=0x1
NoInsidePlugin=0x1
Sequence=F11 I Home Down Down Enter
```
into `~/.config/far2l/settings/key_macros.ini`.

2. Run `far2l`

3. Create new file in editor

4. Type or paste `aaaaaaaaaaaa`.

5. Select first `a`

6. F11

7. Incremental Search

8. Search Forward

9. Press `Ctrl`+`Enter`.

Expected behavior: second `a` is selected (and just it, nothing else)

Observed behavior: first `a` stays selected

**Comment by unxed** [comment]
Faulty commit:
https://github.com/elfmz/far2l/commit/ce2c49bc8b07e139b0a3d129b9708a1d11e8544e

This patch [hack]fixes it in master:
```
diff --git a/far2l/src/plug/plugins.cpp b/far2l/src/plug/plugins.cpp
index 34a5a5ac..f705b135 100644
--- a/far2l/src/plug/plugins.cpp
+++ b/far2l/src/plug/plugins.cpp
@@ -1189,11 +1189,11 @@ int PluginManager::CommandsMenu(int ModalType, int StartPos, const wchar_t *Hist
 	}
 
 	int MenuItemNumber = 0;
+	ChangeMacroMode CMM(MACRO_MENU);
 	int Editor = ModalType == MODALTYPE_EDITOR, Viewer = ModalType == MODALTYPE_VIEWER,
 		Dialog = ModalType == MODALTYPE_DIALOG;
 	PluginMenuItemData item;
 	{
-		ChangeMacroMode CMM(MACRO_MENU);
 		VMenu PluginList(Msg::PluginCommandsMenuTitle, nullptr, 0, ScrY - 4);
 		PluginList.SetFlags(VMENU_WRAPMODE);
 		PluginList.SetHelp(L"PluginCommands");

```

**Comment by shmuz** [comment]
Цитирую автора плагина (см. https://t.me/c/2241384293/319)
> хм... сам по себе фикс кажется правильным. старая макромода восстанавливается после закрытия меню. а раньше не восстанавливалась. и поскольку макромода была неправльной (не Editor), то макрос и не проигрывался. насколько я понимаю этот код. т.е. этот фикс просто вскрыл другой баг.

Я перепроверил (с выводом отладочной информации) и убедился, что вышеприведенная цитата точно описывает происходящее.

Если откатить мой pull request, например как выше указал @unxed, то при работе плагина макрообласть == 8 (`MACROAREA_MENU`), что неправильно, и макрос, у которого область работы == 3 (`MACROAREA_EDITOR`) просто не вызывается.

В текущем коде макрос вызывается (т.к. правильная макрообласть), но работает неправильно. Почему - предстоит выяснить.

**Comment by rampitec** [comment]
Там еще в макросе есть исторически настройка NoInsidePlugin=1. Когда-то это было в far, но Женя удалил этот параметр еще до того, как был создан far2l. IMHO фича была правильная: не запускать макрос, если работает плагин. За что ее Женя удалил, я не знаю, но если бы ее вернуть обратно, то она бы помогла. Сейчас такой параметр у макросов просто отсутствует, и в старом макросе просто не делает ничего. Но! В виндовом far2 1807 тем не менее нажатие кнопки приходит в плагин. Возможно как раз потому, что в старом far живет бага с неправильной макромодой.

**Comment by shmuz** [comment]
@rampitec,  вопрос из любопытства: а зачем нужен этот макрос, если без него работает?

**Comment by rampitec** [comment]
> @rampitec, вопрос из любопытства: а зачем нужен этот макрос, если без него работает?

Так без него не все рабтает. Идея вот в чем: если плагин не запущен, то при наличии выделения ^Enter ищет следующее вхождение выделения, а ^#Enter предыдущее. Если плагин запущен, то его внутренняя логика делает ровно тоже самое. Без макроса для поиска пришлось бы сперва вызывать плагин, возможно другим макросом, а потом руками нажимать ^Enter. Т.е. просто выделяем текст, ^Enter, и вот мы на следующем вхождении этой строки.

**Comment by shmuz** [comment]
@rampitec, попробуйте закомментировать в плагине
```
case 0x8001:	// KEY_EVENT&0x8000
	continue;
```
Вроде начинает работать с макросом, но выходит из `OpenPlugin`.

**Comment by rampitec** [comment]
> @rampitec, попробуйте закомментировать в плагине
> 
> ```
> case 0x8001:	// KEY_EVENT&0x8000
> 	continue;
> ```
> 
> Вроде начинает работать с макросом, но выходит из `OpenPlugin`.

Не, вообще не оно. Это просто стирает выделение. Кстати, что это за прилетающая хачня, я еще много лет назад не понял.

**Comment by shmuz** [comment]
Вот такая "хачня" работает в far2m так, как надо.
Для far2l можно было бы сделать наподобие, но в макроязыке нет функции получения заголовка редактора.
```lua
Macro {
  area="Editor"; key="CtrlEnter";
  action=function()
    if editor.GetTitle():sub(1,2) == "^:" then
      Keys"CtrlEnter"
    else
      Keys"F11 i Home Down Down Enter"
    end
  end;
}
```

**Comment by rampitec** [comment]
> Вот такая "хачня" работает в far2m так, как надо. Для far2l можно было бы сделать наподобие, но в макроязыке нет функции получения заголовка редактора.
> 
> ```lua
> Macro {
>   area="Editor"; key="CtrlEnter";
>   action=function()
>     if editor.GetTitle():sub(1,2) == "^:" then
>       Keys"CtrlEnter"
>     else
>       Keys"F11 i Home Down Down Enter"
>     end
>   end;
> }
> ```

Не, это реально хачня. Или макрос должен исполняться, и тогда он должен приезжать в плагин в виде якобы нажатых кнопок, или он не должен исполняться, и тогда ввод должен приезжать как есть. А это... Это просто отвратительно. Если уж так, так я лучше буду ловить релиз кнопки.

**Comment by shmuz** [comment]
> А это... Это просто отвратительно.

Не  подумайте, что я обиделся, но никак не пойму, что вам кажется отвратительным.

**Comment by akruphi** [comment]
Насчёт **NoInsidePlugin** -  по склонированному https://github.com/FarGroup/FarManager `git log -SNoInsidePlugin --since=1995.1.1` выдал следующие коммиты:

https://github.com/FarGroup/FarManager/commit/e01d259f23d1e148ed42a5e6949c99e74f438468

https://github.com/FarGroup/FarManager/commit/30c48b61acc96339d4f8fade7e2a8e9a76a92684

https://github.com/FarGroup/FarManager/commit/028c4eb1aed702ebf8a3acb63b623539e56b1ba6

где есть примечание:
```
30.07.2003 SVS
    ! Вместо MFLAGS_INSIDEPLUGIN и MFLAGS_NOINSIDEPLUGIN введен один флаг MFLAGS_SENDKEYSTOPLUGINS,
      в соотвествии с NT в макросах
```
Это в копилку как направление для дальнейшего фиксинья.

**Comment by unxed** [comment]
```
MFLAGS_NOSENDKEYSTOPLUGINS = 0x00000200,  // НЕ передавать плагинам клавиши во время записи/воспроизведения макроса
```

Но почему-то с `NoSendKeysToPlugins=0x1` не работает тоже.

**Comment by rampitec** [comment]
> > А это... Это просто отвратительно.
> 
> Не подумайте, что я обиделся, но никак не пойму, что вам кажется отвратительным. Оно работает так, как надо.

Собственно неправильно определять работу плагина по вторичным признакам. Рано или поздно там что-то отвалится.

**Comment by rampitec** [comment]
> Но почему-то с `NoSendKeysToPlugins=0x1` не работает тоже.

А это немного не то. Этот ключ говорит не использовать макрос, если мы проигрываем другой макрос, а не если работает плагин.

**Comment by rampitec** [comment]
> [FarGroup/FarManager@30c48b6](https://github.com/FarGroup/FarManager/commit/30c48b61acc96339d4f8fade7e2a8e9a76a92684)

Вот этот коммит, который убрал NoInsidePlugin, и коммент:

> Удален MMacroSettingsInsidePlugin - за ненадобностью.

А он был нужен! Можно попробовать частично вернуть код, который ревертнул этот коммит.

**Comment by rampitec** [comment]
После некоторой отладки вот что выяснилось: то как написано, должно посылать клавиши в плагин, если NoSendKeysToPlugins=1. Хоть это и не логично. Потому что `KeyMacro::CheckAll()` начинается так:

```
	if (!CheckInsidePlugin(CurFlags))
		return FALSE;
```
А эта функция:
```
BOOL KeyMacro::CheckInsidePlugin(DWORD CurFlags)
{
	if (CtrlObject && CtrlObject->Plugins.CurPluginItem && (CurFlags & MFLAGS_NOSENDKEYSTOPLUGINS))		// ?????
		// if(CtrlObject && CtrlObject->Plugins.CurEditor && (CurFlags&MFLAGS_NOSENDKEYSTOPLUGINS))
		return FALSE;

	return TRUE;
}
```

Только это не работает, потому что `CtrlObject->Plugins.CurPluginItem` равен нулю, поинтера на текущий исполняемый плагин нет. Так что баг, насколько я понимаю.

**Comment by rampitec** [comment]
Собственно плагин не панельный, он все делает внутри своего OpenPlugin и возвращает оттуда INVALID_HANDLE_VALUE, что есть стандартная практика. В этом случае far не знает, что он внутри кода плагина. У нас кроме хэндла (которого в этом случае нет) есть еще флаг:
```
	PSIF_ENTERTOOPENPLUGIN = 0x00000001,	// ввалились в плагин OpenPlugin
```
и его можно было бы проверить, только им никто не пользуется и никто не выставляет.

**Comment by rampitec** [comment]
I think I have a fix...

**Comment by rampitec** [comment]
Fix: https://github.com/elfmz/far2l/pull/2328
