### ISSUE TITLE
Windows Terminal: clipboard paste totally locks FAR

### ISSUE THREAD

**Issue by ClusterM** [elfmz/far2l#2329]
I'm using far2l via Windows Terminal and ssh. I have bound the clipboard paste action to `Ctrl+Shift+V` in terminal settings. So, I can use `Ctrl+C` and `Ctrl+V` to copy and paste text inside FAR, it works fine and doesn't conflict.

But when I want to paste text from Windows to remote system using `Ctrl+Shift+V` FAR totally freaks out. The text is pasted correctly, but then... FAR stops handling any escape sequences:

![image](https://github.com/user-attachments/assets/8814dc54-ef1f-4d65-907e-102c1652b607)
![image](https://github.com/user-attachments/assets/b7ec930a-ddc1-4106-ba31-a96c23acac7b)

So, I can't even quit FAR. 

Copypasting from remote side to local PC using OSC52 works fine, btw.

upd:
Seems like Windows Terminal sends weird escape code sequences. I inspected it.

### Steps to reproduce via clean shell:
1. Copy "test" string to the clipboard
2. Run Windows Terminal
3. Connect to Linux via SSH
4. Type `printf "\x1b[?9001h"` to enable win32-input-mode
5. Right-click on the terminal window to paste text from a clipboard

### Expected Behavior

`;4;20;116;1;0;1_;4;20;116;0;0;1_;18;101;1;0;1_;18;101;0;0;1_;3;31;115;1;0;1_;3;31;115;0;0;1_;4;20;116;1;0;1_;4;20;116;0;0;1_`

It's `t`, `e`, `s`, `t` key presses.

### Actual Behavior

`;0;27;1;0;1_;0;91;1;0;1_;0;50;1;0;1_;0;48;1;0;1_;0;48;1;0;1_;0;126;1;0;1_4;20;116;1;0;1_4;20;116;0;0;1_;18;101;1;0;1_;18;101;0;0;1_3;31;115;1;0;1_3;31;115;0;0;1_4;20;116;1;0;1_4;20;116;0;0;1_;0;27;1;0;1_;0;91;1;0;1_;0;50;1;0;1_;0;48;1;0;1_;0;49;1;0;1_;0;126;1;0;1_`

Decoded:
```
| Sequence          | Vk | Sc  | Uc  | Kd   | Cs | Rc | Description           |
|-------------------|----|-----|-----|------|----|----|-----------------------|
| `;0;27;1;0;1_`    | 0  | 27  | Esc | Down | 1  | 1  | Key Esc pressed       |
| `;0;91;1;0;1_`    | 0  | 91  | [   | Down | 1  | 1  | Key [ pressed         |
| `;0;50;1;0;1_`    | 0  | 50  | 2   | Down | 1  | 1  | Key 2 pressed         |
| `;0;48;1;0;1_`    | 0  | 48  | 0   | Down | 1  | 1  | Key 0 pressed         |
| `;0;48;1;0;1_`    | 0  | 48  | 0   | Down | 1  | 1  | Key 0 pressed         |
| `;0;126;1;0;1_`   | 0  | 126 | ~   | Down | 1  | 1  | Key ~ pressed         |
| `;4;20;116;1;0;1_`| 4  | 20  | t   | Down | 0  | 1  | Key t pressed         |
| `;4;20;116;0;0;1_`| 4  | 20  | t   | Up   | 0  | 1  | Key t released        |
| `;18;101;1;0;1_`  | 18 | 101 | e   | Down | 0  | 1  | Key e pressed         |
| `;18;101;0;0;1_`  | 18 | 101 | e   | Up   | 0  | 1  | Key e released        |
| `;3;31;115;1;0;1_`| 3  | 31  | s   | Down | 0  | 1  | Key s pressed         |
| `;3;31;115;0;0;1_`| 3  | 31  | s   | Up   | 0  | 1  | Key s released        |
| `;4;20;116;1;0;1_`| 4  | 20  | t   | Down | 0  | 1  | Key t pressed         |
| `;4;20;116;0;0;1_`| 4  | 20  | t   | Up   | 0  | 1  | Key t released        |
| `;0;27;1;0;1_`    | 0  | 27  | Esc | Down | 1  | 1  | Key Esc pressed       |
| `;0;91;1;0;1_`    | 0  | 91  | [   | Down | 1  | 1  | Key [ pressed         |
| `;0;50;1;0;1_`    | 0  | 50  | 2   | Down | 1  | 1  | Key 2 pressed         |
| `;0;48;1;0;1_`    | 0  | 48  | 0   | Down | 1  | 1  | Key 0 pressed         |
| `;0;49;1;0;1_`    | 0  | 49  | 1   | Down | 1  | 1  | Key 1 pressed         |
| `;0;126;1;0;1_`   | 0  | 126 | ~   | Down | 1  | 1  | Key ~ pressed         |
```

As you can see, there are much more key codes for some reason.

**Comment by ClusterM** [comment]
Seems more like Windows Terminal bug, actually.

**Comment by ClusterM** [comment]
Issue on the Windows Terminal repo: https://github.com/microsoft/terminal/issues/17656

**Comment by unxed** [comment]
Have you seen #2072 and #2085? Is it the same problem or a different one?

**Comment by unxed** [comment]
@Dazzar56 can you please take a look at this issue?

**Comment by ClusterM** [comment]
> Have you seen #2072 and #2085? Is it the same problem or a different one?

Seems like it's the same problem, yes.

**Comment by ClusterM** [comment]
Answer from Microsoft employee: https://github.com/microsoft/terminal/issues/17656#issuecomment-2266329410

**Comment by ClusterM** [comment]
Fix: https://github.com/elfmz/far2l/pull/2332

**Comment by ClusterM** [comment]
fix: https://github.com/elfmz/far2l/pull/2333

**Comment by unxed** [comment]
FYI: [fixed](https://github.com/microsoft/terminal/issues/15083#issuecomment-2395179096) in Windows Terminal starting from Pre-release v1.22.2702.0.

**Comment by unxed** [comment]
Does this reproduce in far2l from Ubuntu 24.04 repo under latest Windows Terminal Preview version (v1.22.2702.0)?

**Comment by unxed** [comment]
> I have bound the clipboard paste action to `Ctrl+Shift+V` in terminal settings. So, I can use `Ctrl+C` and `Ctrl+V` to copy and paste text inside FAR, it works fine and doesn't conflict.

Just for reference, how to set it up.

![изображение](https://github.com/user-attachments/assets/1b661561-2c0b-4a62-b723-274cd19cb364)
