### ISSUE TITLE
x-server free edition

### ISSUE THREAD

**Issue by mogadanez** [elfmz/far2l#233]
Any plans on roadmap to make true console FAR?

**Comment by volth** [comment]
Do you mean a version for terminals (and thus via ssh/telnet/rs232 links) or for the console (which you could see after pressing Ctrl-Alt-F1) ?
Although the terminal programs can works in the console, it is not the same, the console is more feature rich and free from the legacy terminal problems such as inability to handle a single press of Esc-key ot Ctrl-key.
[FTE](http://fte.sourceforge.net/) has both.

**Comment by unxed** [comment]
AFAIK, lieff (https://github.com/lieff) had some plans on implementing multiple backend (ncurses, etc) support for far2l.
