### ISSUE TITLE
Incorrect work with folder named with `

### ISSUE THREAD

**Issue by orangeag3nt** [elfmz/far2l#2344]
How to reproduce:
Start Far2l
Go to home folder (or any other folder where you can create subfolder)
Create folder named ``
Enter folder
Enter any command. For example "ls". You will be moved to the parent folder in Far2l. Command will be executed in the parent folder.

If you do same thing with folder ` you will see error:
bash: /tmp/far2l_3e8_0/vtcmd/3659_22: line 5: unexpected EOF while looking for matching ``'
bash: /tmp/far2l_3e8_0/vtcmd/3659_22: line 13: syntax error: unexpected end of file

It seems something is not escaped correctly somewhere.
My Far2l version: FAR2L, version 2.6.3-2024-08-18-3e2f1a8-beta Linux x86_64

**Comment by akruphi** [comment]
May be solved in far2m: https://github.com/shmuz/far2m/commit/6e1cb58eee29295615d3e413488ae5630ab2454a

**Comment by shmuz** [comment]
> May be solved in far2m

No, it's the same as in far2l.

**Comment by spnethw** [comment]
And if you name your folder \`date\` you will get even more interesting result:

`bash: cd: /home/user/Mon Aug 19 23:37:55 +04 2024: No such file or directory`

I think https://github.com/elfmz/far2l/pull/2345
