### ISSUE TITLE
GUI mode: spacing in between characters is much bigger than normal

### ISSUE THREAD

**Issue by andrewvoznytsa** [elfmz/far2l#2360]
On my Linux/Kubuntu 24.04/X/nVidia driver 550/4k display/200% scaling/DPI 192 in the latest FAR2L installed directly from PPA there is problem with spacing in between character. See attached image.

![image](https://github.com/user-attachments/assets/55906b42-a154-45b5-8d48-58693274baa8)

On the same hardware in the following config Linux/Kubuntu 22.04/X/nVidia driver 550/4k display/200% scaling/DPI 192 it worked very well.

`--tty` mode is OK from that point of view but my eyes are bleeding

![image](https://github.com/user-attachments/assets/1c68782d-a6ea-4e97-84a2-a8cb973ec799)

**Comment by spnethw** [comment]
> On my Linux/Kubuntu 24.04/X/nVidia driver 550/4k display/200% scaling/DPI 192 in the latest FAR2L installed directly from PPA there is problem with spacing in between character. See attached image.

Try choosing a different, monospaced font: F9 (ConfMn), `Options` -> `Interface settings` -> `Change font` button.


> `--tty` mode is OK from that point of view but my eyes are bleeding

Definitely Konsole is the cause here.  Just select a different color theme in Konsole profile settings, e.g. "Linux Colors".

**Comment by andrewvoznytsa** [comment]
Thank you very much for so quick response!

Konsole profile settings helped with the `--tty` mode.

Changing font in GUI mode does not make any difference - the spacing is still the same.

For me the issue is resolved - I'll use the `--tty` mode. If you are going to fix GUI mode then feel free to ping me if you need help with testing. Otherwise the issue can be closed.

**Comment by akruphi** [comment]
> Changing font in GUI mode does not make any difference - the spacing is still the same.
 
In Ubuntu 22.04 I use far2l GUI with `Ubuntu Mono Regular`. You can try any other mono font.

**Comment by andrewvoznytsa** [comment]
Removing `~/.config/far2l` helped to resolve the issue. Seems like the config from Ubuntu 22.04 was not very compatible with 24.04.
