### ISSUE TITLE
Ctrl+O has no effect in macro

### ISSUE THREAD

**Issue by faerot** [elfmz/far2l#2374]
I have tried to make macros for faster access to terminal output, i.e.

Ctrl+. (record macro)
Ctrl+O
F3
Up
Ctrl+.(stop recording macro)
Ctrl+Alt+Up (bind to this key)

When I press this macro, FAR opens terminal output as expected, but that output contains FAR pannels visible as if Ctrl+O had no effect.

**Comment by shmuz** [comment]
1. Open `~/.config/far2l/settings/key_macros.ini`, find that macro and remove the line `DisableOutput=0x1`
2. Restart far2l

**Comment by shmuz** [comment]
When you are about to finish record your macro press `CtrlShift.` rather than `Ctrl.`.
Then the dialog below should appear and you can check "Allow screen output" there.
![image](https://github.com/user-attachments/assets/7b741adf-65cd-4880-9c82-637c7c2b2ba1)
