### ISSUE TITLE
"Read error" when trying to open .rar file

### ISSUE THREAD

**Issue by faerot** [elfmz/far2l#2375]
I have numerous .rar files that report read error when trying to enter them. Those are regular archives, not Rar 5.
Here is an example of the archive that opens fine both by ArcLite in FAR3 and by Ark on Linux. I have put .rar inside .zip, because github does not allow to upload .rar directly.
far2l version is 2.6.0~beta+ds-1ubuntu0.1 from repository.
[ttg.zip](https://github.com/user-attachments/files/16908064/ttg.zip)

**Comment by akruphi** [comment]
In my in recent far2l 2.6.3-2024-08-31-2f5a7e4d-beta (under Ubuntu 22.04) your TTG 1.06.rar open without problems.

**Comment by faerot** [comment]
Great. Just need to figure out how to build it under ubuntu 24.04 :)

**Comment by unxed** [comment]
> by ArcLite

arclite:
https://github.com/elfmz/far2l/pull/2670
