### ISSUE TITLE
The annoying empty item in user menu (F2)

### ISSUE THREAD

**Issue by Hawkedon** [elfmz/far2l#2376]
When pressing F2 for user menu, there is always an empty item at the bottom. I even tried to modify the menu file directly with CTRL+F4, but the item is still in there. Can this be fixed? Thanks!

**Comment by rusq** [comment]
It is a feature.  The empty line at the bottom is there for you to be able to insert a new item in the end of the list.

It has been like that for more than 30 years, below is the screenshot of Norton Commander 5.5 for DOS, and as you can see, the empty line is there.

<img width="1192" alt="image" src="https://github.com/user-attachments/assets/28dfb8d4-4633-4382-9f15-4e7b9437d6bd">

**Comment by Hawkedon** [comment]
I'm a Windows Far user, and never saw this empty line in there. Just started using far2l recently as the font in Far with Wine is not good. This is the first thing that looks quite unpleasant to me as I use the menu a lot. There are keys to add/modify items in the menu. I can't see why keep an empty line there. When you press Enter/F4 on the empty one, it does nothing.

**Comment by shmuz** [comment]
@Hawkedon , that empty line was in Windows Far for many years, until Far 3.0.3112 where it was removed.

**Comment by Hawkedon** [comment]
@shmuz Oh, I see. New information for me. I'm not a Far user for a decade obviously. :) Since Far has removed that for more than 10 years, is it still possible to remove it for far2l too, as there are keys for insert/modify the menu?

**Comment by shmuz** [comment]
Technically, it is definitely possible to remove it. (But I'm not a developer of far2l).

**Comment by akruphi** [comment]
Done in last master after https://github.com/elfmz/far2l/pull/2380

**Comment by spnethw** [comment]
Just FYI: you can reorder menu items by pressing Ctrl+Up and Ctrl+Down.
