### ISSUE TITLE
не отображается последняя строка вывода запущеной консольной программы

### ISSUE THREAD

**Issue by volth** [elfmz/far2l#239]
bash:
![screenshot_2017-01-03_21-20-58](https://cloud.githubusercontent.com/assets/508305/21623542/ccbe7f90-d1fa-11e6-8fab-f796bd42b32f.png)

far2l:
![screenshot_2017-01-03_21-21-15](https://cloud.githubusercontent.com/assets/508305/21623547/cea6ee14-d1fa-11e6-98f5-ca45aab3214b.png)

**Comment by volth** [comment]
Все равно бывает, что пропадает последняя строка (или единственная, для комманд вывод которых состоит из одной строки вроде which).
В новом фаре, который с зелёной линией.
Сразу после запуска не воспроизводится, только через какое-то время.

**Comment by volth** [comment]
проблема никуда не делась, только её сложнее воспроизвести (я не знаю как)
бывает вот такое - двадцать минут считается sha, а потом результат съедает far2l:

![](http://i.imgur.com/f1BcWgz.png)

**Comment by elfmz** [comment]
мда.. неприятно.
а с последующей командой случайно вывод предыдущей не вылазит?

**Comment by elfmz** [comment]
у меня ни разу такого не было. хотя подозрительные баги взаимодействия с шеллом изредка бывают, но в виде ввел команду - а оно выругалось на мусор. и тоже очень редко и непонятно как и что..

**Comment by volth** [comment]
отличие от бага 2017:  сейчас похоже из нескольких строксъедается первая, а не последняя
