### ISSUE TITLE
MultiArc/ZIP [feature] - if ZIP has both 1-byte and UTF-8 filename always force using UTF-8

### ISSUE THREAD

**Issue by akruphi** [elfmz/far2l#2404]
Согласно жалобе в телеграм-чате
https://t.me/far2l_ru/28667
https://t.me/far2l_ru/28673
встречаются ZIP архивы, где одновременно имена файлов и в однобайтовой кодировке и в UTF-8.
При этом на панели multiarc выводит имена правильно (похоже беря из UTF-8), а при распаковке far2l пытается принудительно использовать ключ `-cs=CP437` (или подобный в зависимости от внутренних OEM/ANSI far2l), что в случае если внутренние OEM/ANSI far2l не совпадают с однобайтной кодировкой архива приводит к невозможности восстановить имена файлов.

@unxed похоже при наличии UTF-8 имени файла внутри ZIP стоит далее при обработке всегда принудительно использовать UTF-8.

**Comment by unxed** [comment]
Problematic archive sample:
https://t.me/itbook_library/2459
(part 3, for example)

Fix:
```
diff --git a/multiarc/src/arccmd.cpp b/multiarc/src/arccmd.cpp
index 69b3993b..57080021 100644
--- a/multiarc/src/arccmd.cpp
+++ b/multiarc/src/arccmd.cpp
@@ -312,8 +312,10 @@ int ArcCommand::ReplaceVar(std::string &Command)
           break;
         }
       }
+      /*
       if (Command.empty() && DefaultCodepage > 0)
         Command = StrPrintf("CP%u", DefaultCodepage);
+      */
 
       break;
 
```
