### ISSUE TITLE
make -j4 failed

### ISSUE THREAD

**Issue by roman4e** [elfmz/far2l#242]
I ran 
`$ make -j4`

`Scanning dependencies of target bootstrap`
`make[2]: *** No rule to make target '/home/****/Downloads/src/far2l/far2l/bootstrap/farlng', needed by 'bootstrap/CMakeFiles/bootstrap'.  Stop.`
`CMakeFiles/Makefile2:122: recipe for target 'bootstrap/CMakeFiles/bootstrap.dir/all' failed`
`make[1]: *** [bootstrap/CMakeFiles/bootstrap.dir/all] Error 2`
`Makefile:127: recipe for target 'all' failed`
`make: *** [all] Error 2`

I have no idea how to fix it.
`cmake version 3.5.1`

and also did 
`apt-get install gawk m4 libglib2.0-dev libwxgtk3.0-dev cmake g++`
within your recipe

my system is linux mint 18, x64

**Comment by roman4e** [comment]
But anything can be compiled separately and works.

**Comment by zzz125** [comment]
работает если установить cmake-fedora и делать просто cd build && cmake .. && make

версия cmake: 3.5.1

**Comment by Seeee** [comment]
Had exactly. 
Solved simply:

git clone https://github.com/elfmz/far2l
_!!! cd far2l <-- If do that, you'll get this error. Should stay outside cloned folder._
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ../far2l
make -j4
