### ISSUE TITLE
Не запускается на Mac OS 10.12.3

### ISSUE THREAD

**Issue by koutsenko** [elfmz/far2l#243]
Добрый день, господа. Пробую завести сборку на Mac OS.
Хотел бы спросить - почему нежелательно ставить wxWidgets через brew?
Неохота ставить wxWidgets из исходников, чтобы неизвестным образом засорить систему.

p.s. я не очень давно пользуюсь Mac, так что это не критика, лишь вопрос.

**Comment by koutsenko** [comment]
1 После make потребовался sudo make install, почему ставится в /usr/bin, а не /usr/local/bin ?!
2 C brew-версией wxWidgets проект собирается, но не запускается
3 В /var/log ничего не нашел...

**Comment by lieff** [comment]
Там какая то бага в wxWidgets из brew. Видимо просто надо обновить, как я понял крашится диалог выбора шрифта, он используется не часто, вот видимо и не заметили. С этим же диалогом помню бала проблема не только в MacOS, там 64бит портирования проблема была.
Насчет путей - это видимо cmake надо как-то донастроить для мака.

**Comment by koutsenko** [comment]
Я зашел на http://braumeister.org/formula/wxmac (это онлайн-каталог репозитария brew).
Там 3 версии - **текущий** 3.0.2, **devel** 3.1.0 и **head**.

С **текущим** - far2l - консоль просто висит после запуска
С **devel** и **head** я словил trap 
```
bash-3.2$ far2l
dyld: Library not loaded: /usr/local/opt/wxmac/lib/libwx_baseu_net-3.0.dylib
  Referenced from: /usr/bin/far2l
  Reason: image not found
```
---------
Ставил HEAD так - предварительно удалил старую версию:
```
bash-3.2$ brew unlink wxmac
Unlinking /usr/local/Cellar/wxmac/3.1.0_4... 74 symlinks removed
```

Форсировал установку **head** из оригинальной git-репы wxWidgets.
```
bash-3.2$ brew install wxwidgets --HEAD
==> Using the sandbox
==> Cloning https://github.com/wxWidgets/wxWidgets.git
Cloning into '/Users/kds/Library/Caches/Homebrew/wxmac--git'...
```

Тем не менее, выпадаю в trap. Это проблема brew? Куда копать?

**Comment by koutsenko** [comment]
И могут ли помочь флаги --with-static, --with-stl или --universal?

```
iMac-Koutsenko:~ kds$ brew info wxmac
wxmac: stable 3.0.2 (bottled), devel 3.1.0, HEAD
wxWidgets, a cross-platform C++ GUI toolkit (for macOS)
https://www.wxwidgets.org
/usr/local/Cellar/wxmac/3.0.2_4 (810 files, 24.6M)
  Poured from bottle on 2017-01-15 at 14:30:15
/usr/local/Cellar/wxmac/3.1.0_4 (812 files, 25.2M)
  Built from source on 2017-01-15 at 18:21:03
/usr/local/Cellar/wxmac/HEAD-da36cbf_4 (792 files, 22.7M) *
  Built from source on 2017-01-15 at 18:29:52
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/wxmac.rb
==> Dependencies
Required: jpeg ✔, libpng ✔, libtiff ✔
==> Options
--universal
	Build a universal binary
--with-static
	build static libraries
--with-stl
	use standard C++ classes for everything
--devel
	Install development version 3.1.0
--HEAD
	Install HEAD version
```

**Comment by lieff** [comment]
Касаемо trap с ненахождением dylib, --with-static должно помочь. Вообще да, это проблема brew, что как миниум напильником приходится работать.

**Comment by koutsenko** [comment]
Не помогло. Через brew никак, теперь ставлю по вашей исходной инструкции.
Хотел бы уточнить:

```
Run cmake -G "Unix Makefiles"

Run make
```
Эти строки относятся к wxWidgets или к far2l? Из текста не очень понятно

**Comment by lieff** [comment]
К far2l, инструкцию уже немного поменяли, я изначально через CodeLite делал, но должно и так работать, главное чтобы wxWidgets последний с тем конфигуром собрался.

**Comment by koutsenko** [comment]
Он собрался, но far2l так же трапается. Нет dylib. Mac OS 10.12.3 если это важно.

**Comment by koutsenko** [comment]
```
bash-3.2$ sudo find / -iname 'libwx*'
Password:
find: /dev/fd/wxWidgets: No such file or directory
find: /dev/fd/wxWidgets: No such file or directory
/Users/kds/wxWidgets/lib/libwx_osx_cocoau-3.1.a
/Users/kds/wxWidgets/lib/libwx_osx_cocoau_gl-3.1.a
/Users/kds/wxWidgets/lib/libwxjpeg-3.1.a
/Users/kds/wxWidgets/lib/libwxpng-3.1.a
/Users/kds/wxWidgets/lib/libwxregexu-3.1.a
/Users/kds/wxWidgets/lib/libwxscintilla-3.1.a
/Users/kds/wxWidgets/lib/libwxtiff-3.1.a
/usr/local/lib/libwx_osx_cocoau-3.1.a
/usr/local/lib/libwx_osx_cocoau_gl-3.1.a
/usr/local/lib/libwxjpeg-3.1.a
/usr/local/lib/libwxpng-3.1.a
/usr/local/lib/libwxregexu-3.1.a
/usr/local/lib/libwxscintilla-3.1.a
/usr/local/lib/libwxtiff-3.1.a
bash-3.2$ 
```

**Comment by koutsenko** [comment]
То что в хомяке - это я туда git clone делал, дистфайлы

**Comment by lieff** [comment]
Странно, --disable-shared в приведенном конфигуре должен был указать собирать статические либы, а --enable-monolithic одну монолитную либу вместо нескольких, хотя фар почему-то сликовался с dylib откуда-то. Может старый не весь вычистился?

**Comment by koutsenko** [comment]
Ок, вопрос - как полностью вычистить уже установленный far2l?
Как установленные файлы, так и всякие сборочные файлы.

**Comment by koutsenko** [comment]
Похоже надо вернуть систему в то состояние которое было до установки всего этого.
Потом поставить по инструкции.
Поэкспериментировал, блин :)

**Comment by koutsenko** [comment]
Сделал make clean в far2l и wxWidgets, сделал make uninstall для wxWidgets.
Установил заново последний wxWidgets. Ставлю far2l, присмотрелся - ошибка:

```
iMac-Koutsenko:far2l kds$ cmake -G "Unix Makefiles"
CMake Error at /opt/local/share/cmake-3.6/Modules/FindwxWidgets.cmake:891 (file):
  file failed to open for reading (No such file or directory):

    /usr/local/include/wx-3.0/wx/version.h
Call Stack (most recent call first):
  WinPort/CMakeLists.txt:6 (find_package)


-- generating headers and languages
CMake Error at /opt/local/share/cmake-3.6/Modules/FindwxWidgets.cmake:891 (file):
  file failed to open for reading (No such file or directory):

    /usr/local/include/wx-3.0/wx/version.h
Call Stack (most recent call first):
  far2l/CMakeLists.txt:168 (find_package)


-- Configuring incomplete, errors occurred!
See also "/Users/kds/far2l/CMakeFiles/CMakeOutput.log".
iMac-Koutsenko:far2l kds$ 
```

Почему он пытается считать сорцы wx-3.0, если в системе установлен wx-3.1?
Установлен из git, brew уже не участвует в этом никак.

**Comment by lieff** [comment]
А wx-config если запустить какой находится в системе? Подозреваю что-то все же не вычистилось.

**Comment by koutsenko** [comment]
```
iMac-Koutsenko:far2l kds$ wx-config --list

    Default config is osx_cocoa-unicode-static-3.1

  Default config will be used for output

iMac-Koutsenko:far2l kds$ wx-config --version
3.1.1
iMac-Koutsenko:far2l kds$ 
```

**Comment by lieff** [comment]
Таак, а wx-config --cflags куда пути покажет?

**Comment by lieff** [comment]
Судя по https://github.com/Kitware/CMake/blob/v3.6.0/Modules/FindwxWidgets.cmake файл  /usr/local/include/wx-3.0/wx/version.h оно нашло, но не смогло открыть. Похоже на битый линк.

**Comment by koutsenko** [comment]
```
iMac-Koutsenko:~ kds$ wx-config --cflags
-I/usr/local/lib/wx/include/osx_cocoa-unicode-static-3.1 -I/usr/local/include/wx-3.1 -D_FILE_OFFSET_BITS=64 -DwxDEBUG_LEVEL=0 -D__WXMAC__ -D__WXOSX__ -D__WXOSX_COCOA__ 
iMac-Koutsenko:~ kds$ 
```

Оно не могло найти этот файл потому что его нет. Там нет 3.0. Есть только 3.1.
```
iMac-Koutsenko:~ kds$ find /usr/local/include -iname 'wx*'
/usr/local/include/wx-3.1
/usr/local/include/wx-3.1/wx
/usr/local/include/wx-3.1/wx/wx.h
/usr/local/include/wx-3.1/wx/wxchar.h
/usr/local/include/wx-3.1/wx/wxcrt.h
/usr/local/include/wx-3.1/wx/wxcrtbase.h
/usr/local/include/wx-3.1/wx/wxcrtvararg.h
/usr/local/include/wx-3.1/wx/wxhtml.h
/usr/local/include/wx-3.1/wx/wxprec.h
``` 
А вышеупомянутый CMake умеет в 3.0.2 максимум.
Значит в brew по-умолчанию тоже как бы "устаревший" CMake...

**Comment by lieff** [comment]
Может дело и в устаревшей версии, но по идее там есть универсальный способ. И из того что я понял - он должен был выпасть на "if(NOT _filename)" на 887 строке и вывести нормальное сообщение "wxWidgets wx/version.h file not found", а не позже на 891 тупо не найти файл.
А find битые линки не пропускает случаем? Ну или "if(NOT _filename)" в этом порте сломано.

**Comment by skabashnyuk** [comment]
Mac OS 10.12.3 in beta. Are you sure you want to run on beta?
It works on 10.12.2

<img width="1440" alt="2017-01-18 12 11 30" src="https://cloud.githubusercontent.com/assets/1614429/22059887/5f7903dc-dd77-11e6-9043-a65ae01eb1df.png">

**Comment by lieff** [comment]
@skabashnyuk on mac many fonts looks broken with far, but
with ~/.far2l/font 1;11;76;90;90;0;0;Menlo;56 config my pseudo-graphics looks good.

**Comment by lieff** [comment]
![2017-01-18 13 31 27](https://cloud.githubusercontent.com/assets/10080078/22060647/10663d00-dd8b-11e6-9773-3627369e4d0b.png)

**Comment by skabashnyuk** [comment]
Can you elaborate a bit more about fonts? What shall I do to make it looks like on your screenshot?

**Comment by lieff** [comment]
Edit ~/.far2l/font (or maybe ~/.config/far2l/font in new versions) and replace content with "1;11;76;90;90;0;0;Menlo;56" string.
Or alternatively you can delete this file, so font pick dialog shows again on first far start. Then pick Melno font and experiment with font size (size can affect correct render too).

**Comment by skabashnyuk** [comment]
Perfecto. Now it's looks more like a human.
<img width="1440" alt="2017-01-18 12 59 51" src="https://cloud.githubusercontent.com/assets/1614429/22061578/32b91a7e-dd7e-11e6-8d1c-796612946474.png">

Is there any way that I can help @koutsenko to have the same result?

**Comment by ddanila** [comment]
Works for me on 10.12.3 (16D32)

**Comment by elfmz** [comment]
Закомитил предположительный воркэраунд - теперь со старым wxwidgets под маком просто не будет показываться фонт диалог на первом запуске. Проверьте у кого макось с brew версией wx.. Хотя это все равно не рекомендуемый сетап - похоже под маком старый wx сильно тормознее свежего.

**Comment by koutsenko** [comment]
Всё заработало, очень интересно.
Инструкцию упрощается - wxwidgets ставить через brew (как и glib gawk cmake pkg-config)
Issue наверное тоже можно закрыть.

p.s. А что за шрифт такой красивый? :)

**Comment by koutsenko** [comment]
![2017-03-18 1 49 04](https://cloud.githubusercontent.com/assets/529293/24065572/23ed91fa-0b7d-11e7-9125-d4abf47570cc.png)

Кстати показывает монетку в имени файла вместо точки
