### ISSUE TITLE
old FTP plug in segfaults on start

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#2443]
```
-DFARFTP=yes -DLEGACY=yes
```

No crash log created.

Common log:
```
OnKeyDown: acsm RETURN raw=ff0d code=d uni=d ( ) ts=72310357 [now=72310364]
ConsoleInput::Enqueue: Ncs e la lc sh ra rc VK_RETURN "
" DOWN, 20 d d 1c
OnChar: acsm RETURN raw=ff0d code=d uni=d ( ) ts=72310357 lke=1
Plugin 'farftp.far-plug-mb' doesn't export 'OpenFilePlugin'
Plugin 'farftp.far-plug-mb' doesn't export 'GetVirtualFindData'
Plugin 'farftp.far-plug-mb' doesn't export 'FreeVirtualFindData'
Plugin 'farftp.far-plug-mb' doesn't export 'ProcessHostFile'
Plugin 'farftp.far-plug-mb' doesn't export 'SetFindList'
Plugin 'farftp.far-plug-mb' doesn't export 'MayExitFAR'
Plugin 'farftp.far-plug-mb' doesn't export 'ProcessEditorInput'
Plugin 'farftp.far-plug-mb' doesn't export 'ProcessEditorEvent'
Plugin 'farftp.far-plug-mb' doesn't export 'ProcessViewerEvent'
Plugin 'farftp.far-plug-mb' doesn't export 'ProcessDialogEvent'
Plugin 'farftp.far-plug-mb' doesn't export 'GetMinFarVersion'
FARFTP: OpenPlugin

OnKeyUp: acsm RETURN raw=ff0d code=d uni=d ( ) ts=72310436
ConsoleInput::Enqueue: Ncs e la lc sh ra rc VK_RETURN "
" UP, 20 d d 1c
```

**Comment by elfmz** [comment]
Баг вызван кодом который был добавлен с фичей скрывания командлайна, так что если можно - посмотрите на предмет не появились ли какие визуальные глюки при закрывании командлайна панелями полностью) (Ctrl+Вниз/ВВерх) или частично  (Ctrl+Shift+Вниз/ВВерх)
У меня вроде все норм, эта перерисовку видимо я зря тогда добавил

**Comment by spnethw** [comment]
> У меня вроде все норм, эта перерисовку видимо я зря тогда добавил

Нет, видимо, всё же, не зря. У меня начинает глючить.
1. Обе панели вниз до конца со скрыванием командной строки.
2. Ctrl-O.
3. Ctrl-O.
Панели выводятся частично, частично вместо них продолжает командная строка висеть.

**Comment by elfmz** [comment]
понятно, значит буду дофикшивать

**Comment by elfmz** [comment]
вроде норм теперь?)

**Comment by spnethw** [comment]
Визуальных глюков с панелями и командной строкой не наблюдаю.
