### ISSUE TITLE
struct EditorInfo does not have FileName

### ISSUE THREAD

**Issue by faerot** [elfmz/far2l#2446]
I was writing editor plugin and noticed that in Python, struct EditorInfo does not have FileName field.
If this a bug? Because I have not found a different way to get the edited file name.
Then I was looking into C SDK and noticed that farplug-wide.h does not have it either, only farplug-mb.h has it and it is deprecated/not used from what I understood.

On the other hand ViewerInfo has const wchar_t *FileName;

Please anyone explain.

**Comment by shmuz** [comment]
Use `EditorControl(ECTL_GETFILENAME)`

**Comment by faerot** [comment]
Thanks for the info
