### ISSUE TITLE
Bugging rendering and/or crash with PANIC after PR #2380

### ISSUE THREAD

**Issue by akruphi** [elfmz/far2l#2459]
After PR #2380 moving **Files highlighting** editing dialog by **Ctrl+F5** often leads to incorrect rendering in Files highlighting list and/or crash with PANIC (thanks @shmuz for investigation):
![image](https://github.com/user-attachments/assets/c49ed4bd-bd9a-4881-9f77-54874a7d1839)

We wait correction PR from @anta999 .

From telegram-chat https://t.me/far2l_ru/32381:
> Если да, то я знаю про этот косяк и как поймать PANIC если за нижнюю границу область с примеров файлов опутсить

> Забываю все время про него и дмуал потом исправлю

> Там рисуется напрямую в буфеер фара, потому что через диалог помидоры криво рисуются

> Ограничение на отрисовку элемента который напряимую рисуется там - примеры файлов

**Comment by spnethw** [comment]
Починено в PR https://github.com/elfmz/far2l/pull/2452 :
https://github.com/elfmz/far2l/blob/3143cb6f6ed95f660f4693650ae15ae1b46bacf5/far2l/src/console/interf.cpp#L513-L528

**Comment by akruphi** [comment]
Fixed in #2452
