### ISSUE TITLE
recursive change of files/folders owner is not working

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#246]
only top folder's owner is changed, even with "process subfolders" option enabled

**Comment by cycleg** [comment]
Mistyping in "far2l/setattr.cpp", lines [1254](https://github.com/elfmz/far2l/blob/4bb6e3705f96c13bf306b2077f1e23cfbc3686ca/far2l/setattr.cpp#L1254) and [1256](https://github.com/elfmz/far2l/blob/4bb6e3705f96c13bf306b2077f1e23cfbc3686ca/far2l/setattr.cpp#L1256): must be strFullName, not strSelName.
