### ISSUE TITLE
saving file list from tmppanel is broken

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#2462]
1. Open temporary panel
2. Copy some files to it
3. Move cursor to it
4. Try to save files list via Alt+Shift+F2
5. Look at file contents. Sample attached

[panel0.txt](https://github.com/user-attachments/files/17496964/panel0.txt)

**Comment by unxed** [comment]
Also files with Russian letters in names are not processed then loading list file to temporary panel.

**Comment by unxed** [comment]
Причём Alt+Shift+F2 у меня срабатывают правильно только если Альт левый, а Шифт правый. Cinnamon, X11, Mint 22

**Comment by shmuz** [comment]
> Cinnamon, X11, Mint 22

Всё то же, но срабатывает нормально на левых Alt и Shift.

**Comment by unxed** [comment]
А, у меня на левых Alt+Shift переключение раскладки, поэтому такое.

**Comment by unxed** [comment]
Проблема с этой комбинацией клавиш однако имеется: после неё «залипает» Alt, блокируя клавиатурный ввод. Это отдельный баг, #2464

**Comment by spnethw** [comment]
Похоже, проблема в том, что в выходной файл [пишется](https://github.com/elfmz/far2l/blob/56345d679bb3ea6c0a845fe7aca1e32679187556/tmppanel/src/TmpClass.cpp#L819-L822) BOM для UTF-16 LE:

```cpp
#ifdef UNICODE
  static const unsigned short bom = BOM_UCS2;
  WriteFile(hFile, &bom, sizeof(bom), &BytesWritten, NULL);
#endif
```

а фактические данные, которые [передаются](https://github.com/elfmz/far2l/blob/56345d679bb3ea6c0a845fe7aca1e32679187556/tmppanel/src/TmpClass.cpp#L826-L827) функции WriteFile(), — они wchar_t:

```cpp
    const TCHAR *FName = TmpPanelItem[i].FindData.FILE_NAME;
    WriteFile(hFile, FName, sizeof(TCHAR) * lstrlen(FName), &BytesWritten, NULL);
```

По факту получается на выходе файл в UTF-32 с BOM'ом UTF-16.
