### ISSUE TITLE
The Alt key "sticks" when pressed together with Shift in some conditions

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#2464]
Steps to reproduce:

1. Run far2l wx under X11
2. Press and hold Alt
3. Press and hold Shift
4. Release Alt
5. Release Shift

The hotkey labels at the bottom of the screen will remain in the state characteristic of pressing Alt, and, for example, the cursor control keys will stop working.

This bug is a side effect of this fix:
https://github.com/elfmz/far2l/pull/2437

Apparently, wxGetKeyState() doesn't always lie under X11. It seems that wxGetKeyState() thinks the Alt key is released when any other key in a combination with Alt is released.

**Comment by shmuz** [comment]
@unxed Why I can't reproduce that? Both far2l and far2m don't  have this problem.
Mint  22,  X11, Cinnamon.

**Comment by unxed** [comment]
No idea for now(

**Comment by shmuz** [comment]
May be it's because you have AltShift for switching languages. I have AltSpace.

**Comment by unxed** [comment]
Yes, if I disable keyboard layout switching hot key, the problem disappears. But interesting fact is that I have layout switching hotkey set to LeftAlt+LeftShift, and while reproducing the bug I used LeftAlt+RightShift, and keyboard layout not stayed the same.
