### ISSUE TITLE
Alt+Tab combination broken when handling Alt keystrokes exclusively

### ISSUE THREAD

**Issue by proffix4** [elfmz/far2l#2476]
The Alt+Tab combination was broken when Alt keystrokes were handled exclusively.
Before the October 20, 2024 commit, window switching still worked (even when Alt keystrokes were handled exclusively) if you pressed Alt+Tab twice, then it was broken

**Comment by unxed** [comment]
Are you sure it worked previously?

Also, isn't it the same issue?
https://github.com/elfmz/far2l/issues/2007

**Comment by unxed** [comment]
Can you also please upload far:about screenshot?

**Comment by proffix4** [comment]
Вот рабочая версия: https://github.com/elfmz/far2l/tree/a464fb8bc2aa95220ed4abee7aedc3273a39b3a6Отправлено с устройства Galaxy
-------- Исходное сообщение --------От: unxed ***@***.***> Дата: 28.10.2024  22:45  (GMT+05:00) Кому: elfmz/far2l ***@***.***> Копия: "Talipov S.N." ***@***.***>, Author ***@***.***> Тема: Re: [elfmz/far2l] Alt+Tab combination broken when handling Alt keystrokes exclusively (Issue #2476) 
Are you sure it worked previously?
Also, isn't it the same issue?
#2007

**Comment by proffix4** [comment]
После указанной даты любые версии не работают корректно. У меня Debian 12 с CinnamonОтправлено с устройства Galaxy
-------- Исходное сообщение --------От: unxed ***@***.***> Дата: 28.10.2024  22:49  (GMT+05:00) Кому: elfmz/far2l ***@***.***> Копия: "Talipov S.N." ***@***.***>, Author ***@***.***> Тема: Re: [elfmz/far2l] Alt+Tab combination broken when handling Alt keystrokes exclusively (Issue #2476) 
Can you also please upload far:about screenshot?

**Comment by unxed** [comment]
Понял, спасибо! попробую решить проблему через пару часов

**Comment by proffix4** [comment]
Ваше исправление решает проблему, подтверждаю. Ждем когда оно войдет в официальную ветку и станет доступным всем

**Comment by spnethw** [comment]
@proffix4 наверное, можно закрывать?

**Comment by proffix4** [comment]
Да, спасибоОтправлено с устройства Galaxy
-------- Исходное сообщение --------От: Ivan ***@***.***> Дата: 20.11.2024  14:18  (GMT+05:00) Кому: elfmz/far2l ***@***.***> Копия: "Talipov S.N." ***@***.***>, Mention ***@***.***> Тема: Re: [elfmz/far2l] Alt+Tab combination broken when handling Alt keystrokes exclusively (Issue #2476) 
@proffix4 наверное, можно закрывать?
