### ISSUE TITLE
Повторы в Folder history

### ISSUE THREAD

**Issue by volth** [elfmz/far2l#249]
В Folder history (Alt-F12) встречаются имена фолдеров с ```/``` на конце и без него.
Имена с ```/``` и без считаются различными, что приводит к повторам в истории:
![](http://i.imgur.com/enInOg3.png)

(дубликаты имен не всегда расположены рядом)

**Comment by cycleg** [comment]
Есть мнение, что имена со слэшем [добавляются в FileList::ChangeDir()](https://github.com/elfmz/far2l/blob/436dc5a13e5d72b6b56e155686dc426558172bb7/far2l/filelist.cpp#L2560), потому что там используется ConvertNameToFull() из cvtname.cpp. Она слэш в конец и подрисовывает, точнее, где-то в MixToFullPath() его добавляют. А в других местах, где историю пополняют, например, из плагинов, такого нет.

**Comment by elfmz** [comment]
reopen если еще гдето осталось..
