### ISSUE TITLE
macos: far2l starts off screen

### ISSUE THREAD

**Issue by asimonov** [elfmz/far2l#2495]
Hello,

I am on macos 14.7.

If I close far2l on external monitor, then disconnect that monitor, then start far2l again it appears outside of main macbook screen. I can see it in Mission Control, but cannot switch to it or move it back to main screen.

Is there any way for it to revert to main monitor if external monitor is not there anymore?

**Comment by akruphi** [comment]
You can before start far2l delete file `~/.config/far2l/winstate`, which store window size & position.

**Comment by asimonov** [comment]
Thank you! It works!

is there any way i can change the font size as well?

**Comment by asimonov** [comment]
> > is there any way i can change the font size as well?
> 
> Use **F9**->Options->Interface settings->[ Change font ] or before start far2l delete file `~/.config/far2l/font`

thanks a lot! thats exactly what i needed!
