### ISSUE TITLE
Invisible folder and disk names in change drive panel

### ISSUE THREAD

**Issue by ggevgg** [elfmz/far2l#250]
The names of drivers and folders with deep nesting can't be seen when selecting a disc

![far](https://cloud.githubusercontent.com/assets/13509279/22778472/bd027160-eebf-11e6-9f57-5d0de3105165.jpg)

**Comment by elfmz** [comment]
As I understand you have some extremely long mounted path in df -T output, and since pathes aligned by right edge - other pathes become out of visible space
Show df -T output to confirm plz..

**Comment by ggevgg** [comment]
![far2](https://cloud.githubusercontent.com/assets/13509279/22783158/45999248-eed3-11e6-8743-5b02c64b5c56.jpg)

**Comment by elfmz** [comment]
hm.. can you redirect it to text file and attach it?

**Comment by elfmz** [comment]
ah. understood. no need in df output. its mot from df, its your current dir selected in other panel.
just navigate to some shorter path to confirm, anyway its bug will fix later

**Comment by ggevgg** [comment]
yes, if i navigate a little higher, all names will be shown, but unfortunately i have to work with a deep level of nesting folders
