### ISSUE TITLE
Duplication of key presses in Neovim.

### ISSUE THREAD

**Issue by anta999** [elfmz/far2l#2503]
There is a duplication of key presses in Neovim.

https://github.com/user-attachments/assets/2787b022-e9b5-4c6a-b517-709e628793a8

**Comment by elfmz** [comment]
что я тогда сломал - я починил, но вот заметил что нажатие shift и прочих модификаторов приводит в nvim к печатанию непечатных символов, и это было еще до моего рефакторинга..
