### ISSUE TITLE
После обновления (deb-пакет) слетела раскраска папок/файлов

### ISSUE THREAD

**Issue by falconandy** [elfmz/far2l#2513]
Вроде бы я сам явно ничего не настраивал, раскраска была дефолтная. Обновляюсь сразу как прилетает (может с лагом в 1 день).

FAR2L, version 2.6.4-2024-11-19-68a6021-beta Linux x86_64 

Operating System: Ubuntu 24.04
KDE Plasma Version: 5.27.11
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.13
Kernel Version: 6.8.0-49-generic (64-bit)
Graphics Platform: X11

![image](https://github.com/user-attachments/assets/dc13a655-05ea-466a-81ef-6ad1d32fad67)

**Comment by falconandy** [comment]
Спасибо. Заработало.

**Comment by dvlom99** [comment]
Странно это все... На 3-х машинах раскраска слетела, на одной после обновления осталась. Новых и свежих измененых файлов настроек не нашел. Размножил настройки с уцелевщей машины.

**Comment by akruphi** [comment]
Изменения связаны с нововведениями, пришедшими в составе https://github.com/elfmz/far2l/pull/2452, где был выпилен код, читающий совсем древний формат `settings/colors.ini` (@anta999 обещал https://t.me/far2l_ru/34668 учесть критику и вернуть этот код).

Но, если Вы используете только раскраску по умолчанию, то наиболее правильный способ
> зайти в F9->Options->Files highlighting and sort groups и нажать **Ctrl+R** для сброса раскрасок к текущим умолчаниям.

**Comment by dvlom99** [comment]
@akruphi, спасибо на добром слове. Жалко было своей работы, долго красил)) Тем более, что на первой обновляемой машине раскраска осталась, я обычно с нее все настройки беру.
