### ISSUE TITLE
После обновления (deb) сломалось отображение размеров файлов в панелях

### ISSUE THREAD

**Issue by dvlom99** [elfmz/far2l#2517]
С обновления, предшествующего этому: FAR2L, version 2.6.4-2024-11-20-63ae9f6-beta Linux x86_64, Mint 22, колонка панели, которая отображает размер файла расширилась с 6 до 9 позиций. В настройках панели ширина указана - 6. Пользоваться стало совсем не удобно. Разделителей тысяч нет, настроек соответствующих также не нашел. 
![Снимок экрана от 2024-11-21 12-04-33](https://github.com/user-attachments/assets/b1477732-c967-4fe8-a537-ccb7fe2ba1dd)

**Comment by verasminsk** [comment]
+1 и еще подсветка/раскраска файлов...

**Comment by akruphi** [comment]
Изменения связаны с нововведениями, пришедшими в составе https://github.com/elfmz/far2l/pull/2452, и частично меняющие установки по умолчанию в части ширины колонки, а оказалось, что формат чисел far2l выбирает исходя из ширины (@anta999 обещал https://t.me/far2l_ru/34668 учесть критику и значения по умолчанию откатить на традиционные).

Ручное исправление:

* в новых настройках по **Ctrl**+**Alt**+**D** из списка выбрать первый вариант из списка, где Папка, + убрать символы вокруг - это вернет ширину столбца как раньше и форматирование чисел размера даст традиционный вид (если у кого **Ctrl**+**Alt**+**D** занята системой, то способ через `far:config` выставить параметру `Panel.DirNameStyle` значение **0** и затем, например, сменить туда-обратно язык, чтобы запустить пересчёт ширины).

    ![изображение](https://github.com/user-attachments/assets/73817599-2ab0-4559-9f63-607a13dc01d7)
    ![изображение](https://github.com/user-attachments/assets/c48cf147-05d0-4075-a066-3343b6958af3)


* также в режимах панелей у столбца Размер (типы **S**, **P** или **G**) можно убрать новый признак **A** (автоматическая подстройка ширины под число размерах в байтах) или прописать туда признак **F**.

**Comment by dvlom99** [comment]
> в новых настройках по Ctrl+Alt+D из списка выбрать....

Очень полезная для меня настройка оказалась, спасибо.

>также в режимах панелей у столбца Размер (типы S, P или G) можно убрать новый признак A (автоматическая подстройка ширины под число размерах в байтах) или прописать туда признак F.

Про признак "A" в справке не написано, и он у меня не был использован.  А вот "C" добавляет пробел как разделитель тысяч (форматирует). То, что нужно.

![Снимок экрана от 2024-11-21 17-46-30](https://github.com/user-attachments/assets/30515708-b1ad-4370-b0c2-a932afa82aa4)
![Снимок экрана от 2024-11-21 17-48-47](https://github.com/user-attachments/assets/72e27aa4-351b-4166-98b9-f28e113e1711)
