### ISSUE TITLE
При распаковке вложенного каталога из zip-a распаковывает с полным путями.

### ISSUE THREAD

**Issue by igreenman** [elfmz/far2l#252]
far2l-git r743.abe32d7

**Comment by elfmz** [comment]
dup of https://github.com/elfmz/far2l/issues/191 or something else?

**Comment by igreenman** [comment]
Да. Точно проявляется при распаковке zip master https://github.com/rogerclarkmelbourne/Arduino_STM32

**Comment by elfmz** [comment]
насчет этого крэша на выходе, его должно пофиксить https://github.com/elfmz/far2l/commit/ebb6e458bc7cd89dfc985e2f5078be6ef7479975

**Comment by unxed** [comment]
а не закрыть ли этот тикет, раз уж он всё равно https://github.com/elfmz/far2l/issues/191 дублирует?

**Comment by unxed** [comment]
> а не закрыть ли этот тикет, раз уж он всё равно #191 дублирует?

ап) у нас три тикета по этой проблеме уже

**Comment by unxed** [comment]
@igreenman может, закроем этот тикет уже? Для zip оно пофикшено, а про 7z отдельный тикет есть

**Comment by igreenman** [comment]
OK
