### ISSUE TITLE
NetRocks / Extra connection options / Keepalive

### ISSUE THREAD

**Issue by ok512** [elfmz/far2l#2530]
Соратники подскажите пожалуйста как правильно Keepalive выставлять в NetRocks?
Вот параметры соединения:
```
╔═════════════════ Site connection settings ══════════════════╗
║ Display name       :   aaa                            [ A ] ║
║ Protocol           :   sftp                               ↓ ║
║ Host name          :   aaa                                ↓ ║
║ Port number        :   22                                   ║
║ Login mode         :   No password                        ↓ ║
║ Login username     :   root                               ↓ ║
║ Login password     :                                        ║
║ Working directory  :   /home/ubuntu                       ↓ ║
╟─────────────────────────────────────────────────────────────╢
║  [ Extra options ] [ Protocol options ] [ Proxy options ]   ║
╟─────────────────────────────────────────────────────────────╢
║            [ Save ] { Save/Connect } [ Cancel ]             ║
╚═════════════════════════════════════════════════════════════╝
╔══════════════════ SFTP protocol options ═══════════════════╗
║ Authentication:       SSH-agent (by ${SSH_AUTH_SOCK})     ↓║
║                                                            ║
║ Compression:          No compression                      ↓║
║ [ ] Custom subsystem request/exec:                         ║
║                                                            ║
║ Max read block size, bytes:                   32768        ║
║ Max write block size, bytes:                  32768        ║
║ Automatically retry connect, times:           2            ║
║ Connection timeout, seconds:                  20           ║
║ OpenSSH config files: (Default config files)              ↓║
║ Allowed host keys:                                         ║
║ [x] Enable TCP_NODELAY option                              ║
║ [ ] Enable TCP_QUICKACK option                             ║
║ [ ] Ignore time and mode errors                            ║
╟────────────────────────────────────────────────────────────╢
║                     { Ok } [ Cancel ]                      ║
╚════════════════════════════════════════════════════════════╝
```
**~/.ssh/config**
```
ServerAliveInterval·15

Host aaa
	HostName %h
	ProxyJump bastion
	User root
	ForwardAgent yes
```

Этот `ServerAliveInterval·15` должен подхватываться из **~/.ssh/config** или нет?
Как-то можно увидеть что происходит или почему?
SecureCRT не отваливается (через тот же bastion) и никаких `Anti-idle` нём не выставлено...
![image](https://github.com/user-attachments/assets/113f2ca0-edd6-486e-98d5-e34fa39def7a)

Если выставить `Keepalive` на этом экране и потом сохранить, то ничего на самом деле не сохраняется...
```
╔═════════════════ Extra connection options ═════════════════╗
║ Keepalive, seconds  :                               0      ║
║ Time adjust, seconds:                               0      ║
║ Codepage            :            65001 │ UTF8             ↓║
║ Command to execute on connect:                             ║
║                                                            ║
║ Command to execute on disconnect:                          ║
║                                                            ║
║ Extra string passed to command:                            ║
║                                                            ║
║ Limit command execution time, seconds:                 30  ║
║ Extra environment variables available for command process: ║
║ $HOST $PORT $USER $PASSWORD $EXTRA $SINGULAR $STORAGE      ║
╟────────────────────────────────────────────────────────────╢
║                     { Ok } [ Cancel ]                      ║
╚════════════════════════════════════════════════════════════╝
```

**Comment by spnethw** [comment]
> Если выставить `Keepalive` на этом экране и потом сохранить, то ничего на самом деле не сохраняется...

Было исправлено в коммите https://github.com/elfmz/far2l/commit/0c99e7482c22c8dbb6cceffe2a36b948b130d679.
Видимо, у вас более старая версия.

**Comment by dodo-16** [comment]
Да, написал когда сидел на **2.6.3** beta MACOS
Сейчас **2.6.4** beta, действительно `Keepalive, seconds` сохраняется, но соединение точно также отваливается...

> Этот ServerAliveInterval·15 должен подхватываться из ~/.ssh/config или нет?
> Как-то можно увидеть что происходит или почему?

А на эти вопросы кто-то знает ответ или куда копать-то?

**Comment by akruphi** [comment]
> Как-то можно увидеть что происходит или почему?

Возможно что-то можно будет увидеть после включения логирования (см. https://github.com/elfmz/far2l/wiki/Running-far2l-with-debug-logging-enabled ). В частности для far2l-GUI я делаю так:
* внутри терминала включаю логирование прямо в этот терминал (а не во внешний файл):
    ```sh
   export FAR2L_STD=-
   export NETROCKS_VERBOSE=9
    ```
* в этом же терминале запускаю far2l-GUI
     ```sh
     far2l
     ```
* пока открыт far2l в терминал валятся разные строки информации - удобно, чтобы сразу видеть на какое из действий какие строки лога

**Comment by dodo-16** [comment]
Покувыркался не по детски, вот что получилось:
Был _far2l-2.6.3-beta_, с ним 
`║ Keepalive, seconds  :                               0      ║`
Не сохранялся, всё время был `0`
Поставил **far2l-2.6.4-beta**
`║ Keepalive, seconds  :                              15      ║`
Появился, но так же отваливался.
Поменял + сохранил и сразу всё заработало!

Options_sftp в экспорте *.Site.NetRocks заметно отличается.
Экспортнул все сайты, поправил в них Options_sftp и закинул обратно.
Всё работает, ничего не отваливается!

Спасибо всем за помощь!

**Comment by dodo-16** [comment]
> > Как-то можно увидеть что происходит или почему?
> 
> Возможно что-то можно будет увидеть после включения логирования (см. https://github.com/elfmz/far2l/wiki/Running-far2l-with-debug-logging-enabled ). В частности для far2l-GUI я делаю так:
> 
> * внутри терминала включаю логирование прямо в этот терминал (а не во внешний файл):
>   ```shell
>   export FAR2L_STD=-
>   export NETROCKS_VERBOSE=9
>   ```
> * в этом же терминале запускаю far2l-GUI
>   ```shell
>   far2l
>   ```
> * пока открыт far2l в терминал валятся разные строки информации - удобно, чтобы сразу видеть на какое из действий какие строки лога

Спасибо!
Похоже мне надо это хозяйство в `/var/log` отправить и `logrotate` прикрутить!
