### ISSUE TITLE
on first start of far2l in kitty display help on freeing some hotkeys 

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#2551]
kitty uses ctrl+navigation keys for its own needs. We may suggest user to add needed options to kitty's config file to free such keys so they can be used in far2l.

**Comment by unxed** [comment]
Тут есть отдельная проблемка с этим: у нас Getting Started всегда на английском. Не разумнее ли сразу при первом запуске определять язык по локали системы, а там уж пользователь поменяет, если ему надо будет?

@akruphi

**Comment by akruphi** [comment]
> Тут есть отдельная проблемка с этим: у нас Getting Started всегда на английском. Не разумнее ли сразу при первом запуске определять язык по локали системы, а там уж пользователь поменяет, если ему надо будет?

В текущий момент раздел **@Far2lGettingStarted** существует только в языках помощи FarEng.hlf.m4 и FarRus.hlf.m4. На другие языки его никто не переводил и не слышно, чтобы кто-то планировал.

На случай, если вдруг при старте почему-то первым языком будет не один из них именно в этом вызове справки указан флаг `FHELP_NOSHOWERROR`, чтобы при отсутствии раздела не вылезало бы предупреждение, а просто молча продолжался код:
https://github.com/elfmz/far2l/blob/980ac9b6ede77931de06b8e1fd73f9b0479a003a/far2l/src/main.cpp#L310

Ну и справка в far2l существует всего на 4х языках: `FarEng.hlf.m4`, `FarHun.hlf.m4`, `FarRus.hlf.m4`, `FarUkr.hlf.m4`, из которых более менее актуализируются лишь Eng и Rus. В остальные 2 в лучшем случае попадают затычки на английском, а в худшем не правится куча неактуального.

Так, что пока справка не переведена и актуализирована на хотя бы 2/3 языков интерфейса не стоит усложнять сущности - всё-таки двухпанельный менеджер это для хоть немного продвинутых пользователей знающих азы компьютерного английского.

**Comment by unxed** [comment]
Да я бы сделал авто определение русского и английского, для которых эта операция будет осмысленна, а для остальных английский выставлял пока

**Comment by akruphi** [comment]
> Да я бы сделал авто определение русского и английского, для которых эта операция будет осмысленна, а для остальных английский выставлял пока

imho - это уже слабонужный over-engineering какой-то. Сейчас в far2l переключение языка - глобальное действо (см. для помощи `Opt.strHelpLanguage`, значение которой должно быть жёстко согласовано с первой строкой *.hlf файла).

**Comment by unxed** [comment]
Есть проблема: не все знают английский. Какой смысл показывать общие вводные на языке, который человек может не знать? Надо что-нибудь придумать по этому поводу

**Comment by unxed** [comment]
Getting started же показывается до того как у пользователя возможность выбрать язык появляется

**Comment by akruphi** [comment]
> Есть проблема: не все знают английский.

Я думаю правильнее будет при старте всё приветственное показывать изначально на дефолтном языке = английском (повторяю: **двухпанельными менаджерами файлов всё-таки пользуются хоть немного продвинутые пользователи с минимальным знанием компьютерного английского**), но глобально в помощь добавить быструю и понятную новичкам возможность переключится на любой другой доступный язык без выхода из помощи.

Для windows far3 вроде даже то ли макрос, то ли плагин был, который внутри справки (без выхода из неё) позволял быстро сменить язык - найти сейчас не могу; @shmuz можешь подскажешь где и как это реализовано в far3?

**Comment by shmuz** [comment]
> Для windows far3 вроде даже то ли макрос, то ли плагин был, который внутри справки (без выхода из неё) позволял быстро сменить язык

Мне такой плагин или макрос неизвестен. Полагаю, что мог бы написать такой на Lua примерно за час.

**Comment by unxed** [comment]
> двухпанельными менаджерами файлов всё-таки пользуются хоть немного продвинутые пользователи с минимальным знанием компьютерного английского

Чем установка русского по умолчанию в случе ru_RU локали повердит продвинутым пользователям? А менее продвинутым это поможет быстрее разобраться.

**Comment by shmuz** [comment]
>> можешь подскажешь где и как это реализовано в far3?

> Полагаю, что мог бы написать такой на Lua примерно за час

Написал из спортивного интереса. Минут 40 заняло. Включу в набор макросов.

**Comment by unxed** [comment]
Это то, о чем говорили в чате: обилие возможностей Lua предрасполагает писать на ней то, что, по-хорошему, должно быть core функционалом.

**Comment by shmuz** [comment]
> то, что, по-хорошему, должно быть core функционалом.

Невозможно и не нужно все мыслимые хотелки запихать в core.
Но даже если фичу там есть, а юзер хочет эту фичу по другому - он берёт и делает как ему удобно.
Никакими сотнями опций это не покроешь.
А большинство хотелок никогда не попадут в core.

**Comment by unxed** [comment]
Не, ну автодетект языка по локали явно не то, что нужно скриптами делать

**Comment by akruphi** [comment]
> Чем установка русского по умолчанию в случе ru_RU локали повердит продвинутым пользователям? А менее продвинутым это поможет быстрее разобраться.

Мини-исторический оффтоп: лет 20 назад к нам на конференцию приехал итальянский профессор и попросился за компьютер проверить email. Так вот его растерянность от русского языка windows до сих пор помню - пришлось в самые неожиданные моменты подсказывать ему где что включать/переключить. Я и сам сейчас так же себя поведу столкнувшись не только с китайской, но возможно и некоторыми европейскими локализациями.

Поэтому всё такое показывать лучше на английском или гарантированно имея прямо в этом же окне интуитивно понятный переключатель на доступные языки.

**Comment by unxed** [comment]
А зачем бы итальянскому профессору жить с русской локалью в системе? Остальной софт в любом случае на русском будет

**Comment by unxed** [comment]
Fixed in
https://github.com/elfmz/far2l/pull/2575
and
https://github.com/elfmz/far2l/pull/2576
