### ISSUE TITLE
Build broken with -DICU_MODE=build

### ISSUE THREAD

**Issue by akruphi** [elfmz/far2l#2555]
При попытке сборки far2l с свежевведенным ключом `cmake -DICU_MODE=build` cmake выдаёт ошибку:
```
Make Error at utils/CMakeLists.txt:75 (add_library):
  Cannot find source file:

    /tmp/far2l/_build/utils/tmpCharClasses.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at utils/CMakeLists.txt:75 (add_library):
  No SOURCES given to target: utils
```

---

Возможная причина (спасибо @vkrapivin-sc за посказку):

Оно так задано
https://github.com/elfmz/far2l/blob/980ac9b6ede77931de06b8e1fd73f9b0479a003a/utils/CMakeLists.txt#L14-L22
То есть сама генерация есть. 

По идее тут должно было быть что ${CHAR_CLASSES_CPP} зависит от utils_icu.  А то порядок сборки не определен и тут уж что соберет первым....

**Comment by michaellukashov** [comment]
Исправил:
https://github.com/elfmz/far2l/pull/2556

**Comment by akruphi** [comment]
Draft fixed in #2556
