### ISSUE TITLE
Ubuntu22.04 build error `FAILED: copyright /usr/bin/env: ‘perl\r’: No such file or directory`

### ISSUE THREAD

**Issue by yuchdev** [elfmz/far2l#2557]
The application is being built on Ubuntu 22.04 with Ninja-build toolchain.
```
sudo apt -y install libwxgtk3.0-gtk3-dev libx11-dev libxi-dev libxml2-dev libuchardet-dev libssh-dev libssl-dev libsmbclient-dev libnfs-dev libneon27-dev libarchive-dev cmake pkg-config g++ git ninja-build
git clone git@github.com:elfmz/far2l.git
cd far2l &&  mkdir -p _build && cd _build
cmake -DUSEWX=yes -DCMAKE_BUILD_TYPE=Release -G Ninja .. &&  cmake --build . 
```

Compilation process seems to be over, but the call of Perl script invokes the following error
```
FAILED: copyright
cd ~/Projects/far2l/packaging/debian/copyright && ./generate.pl ~/Projects/far2l/_build/copyright
/usr/bin/env: ‘perl\r’: No such file or directory
```

From the first glance, the problem seems to be with line ending symbol.
Didn't find it among open issues.

**Comment by yuchdev** [comment]
And I was right
```
dos2unix ./far2l/packaging/debian/copyright/generate.pl
```
solved the issue.

**Comment by unxed** [comment]
In master line endings are ok in this file.

**Comment by elfmz** [comment]
This could happen if you checked out sources under Windows and then copied them to Linux and tried to build then. Dont do that, just get sources directly on build system, or at least another Linux machine

**Comment by yuchdev** [comment]
No, I ruled out this possibility, of course - I worked on Lunux.
Is it possible that `git clone` itself messed with the ending?

I tested on another instance with Ubuntu, this time on KVM virtual machine - the problem persisted.

**Comment by atolismesh** [comment]
@yuchdev 
Check your git installation setting and read this article https://stackoverflow.com/questions/2517190/how-do-i-force-git-to-use-lf-instead-of-crlf-under-windows

**Comment by yuchdev** [comment]
That's what I thought too, because I usually keep the same `.gitconfig` on all Linux machines, physical or virtual - but it was already `false`
```
[core]
	autocrlf = false
```

**Comment by yuchdev** [comment]
Edit: the problem is fixed. Instead
```
autocrlf = false
```
on Linux should be
```
autocrlf = input
```
