### ISSUE TITLE
SEGFAULT в Debian; коммит a191dd

### ISSUE THREAD

**Issue by cycleg** [elfmz/far2l#256]
Падает практически немедленно, сразу после сообщения о несовпадении версий ABI (как [здесь](https://github.com/elfmz/far2l/issues/254#issuecomment-280297582)).
a191dd37def29162f50d4a4b526f288832354788
Предыдущий работает нормально.

**Comment by elfmz** [comment]
а сейчас?

**Comment by cycleg** [comment]
В c867a53203334d38fadbe8f611cf0d985d58801e все пучком, можно закрывать.
