### ISSUE TITLE
Не правильно обрабатываются переменные окружения в "Настройки командной строки"

### ISSUE THREAD

**Issue by itspec-ru** [elfmz/far2l#257]
Меню "Параметры/Настройки командной строки".
Ставим галку на "Установить формат командной строки".
Пробовал разные варианты
[%COMPUTERNAME%]$p$g
[$COMPUTERNAME]$p$g
[$HOSTNAME]$p$g
ничего не работает

Судя по всему help по F1 не актуален.
В примере из help'а к "Формат командной строки"
[%COMPUTERNAME%]$S$P$G

**Comment by elfmz** [comment]
Хелп да, совсем неактуален в области изменений.

**Comment by elfmz** [comment]
Пофикшено https://github.com/elfmz/far2l/commit/19e0cc6902e2885a0b964007b0a3ecb5cdcd078b
На самом деле все работало, просто нету такой переменной окружения COMPUTERNAME. HOSTNAME, внезапно, тоже нету. Но теперь она как бы есть :) - и можно писать %HOSTNAME%

**Comment by itspec-ru** [comment]
Спасибо!
Появились ещё пара вопросов.
1. А есть ли смысл в использовании нотации Windows? Т.е. %ИМЯ_ПЕРЕМЕННОЙ%.
Очевидно, более понятно и привычно в Linux $ИМЯ_ПЕРЕМЕННОЙ (или ${ИМЯ_ПЕРЕМЕННОЙ}).
2. Вы определяете HOSTNAME через функцию gethostname(&s_out[1], 0xfe).
А если сначало пытаться определить значение системной переменной окружения, и если она не инициализирована, то тогда уже вычислять её самостоятельно. Т.е. предлагаю просто использовать системные переменные окружения, и не только в случае с HOSTNAME, а вообще.

**Comment by elfmz** [comment]
1. Особого смысла нету, кроме того что может что-то сломаться. Но возможно стоит добавить поддержку ${..}.
2. Вобщемто так оно и работает сейчас.
