### ISSUE TITLE
[feature request] terminal detachment

### ISSUE THREAD

**Issue by zzz125** [elfmz/far2l#258]
нужно чтобы far2l при запуске из терминала/консоли автоматически отцеплялся от терминала (без добавления " &") т.к. это гуи приложение

подобным образом работает gvim - если его запустить из консоли он отцепится от нее автоматом, если нужно оставить приложение в консоли "прицепленным" обычно есть специальный флаг типа "-c  stay on console"

**Comment by unxed** [comment]
при этом у меня вот даже с помощью амперсанда отцепить не удается. минт 18.что-то 64бита

**Comment by unxed** [comment]
при этом у меня вот даже с помощью амперсанда отцепить не удается. минт 18.что-то 64бита

**Comment by elfmz** [comment]
С амперсандом отцепляется без проблем, беда разве что с тем что при закрытии терминала фар вываливался, но это легко починилось.
Посмотрел я что делает gvim. Не уверен что это правильное решение, в техническом плане - gvim просто стартует чайлда и тут же выходит. Некошерно както, уж лучше пусть с амперсандом будет как и задумано.

**Comment by zzz125** [comment]
>Некошерно както

это дело вкуса. gvim также часто используется с именем файла, т.е. запускается как $ gvim filename, так что ему более логично отцепляться, освобождать консоль.

другие приложения, например блендер не отцепляются т.к. расчитаны на запуск с ярлыков и "в консоли" для них особый режим, например блендер выводит нужную дебаг информацию в консоль в таком режиме (сама по себе консоль конечно для блендера бесполезная)

я не настаиваю. доводы типа моих: так надо меньше печать (&) и по-умолчанию консоль не занимается, также нет лишнего в консоле если фар будет что-то писать туда из бэкграунда

**Comment by zzz125** [comment]
также, например я могу создать шелл скрипт и положить в /ush/local/bin/far с отцеплением (nohup там итп) и запускать просто $ far потом подобно gvim

**Comment by unxed** [comment]
с амперсандом ок, эт я на компе со старой версией проверял, оказывается.

**Comment by elfmz** [comment]
far2l тоже может в консоль дебаг информацию выводить, достаточно поставить ему переменную окружения:
export FAR2L_STD=-
Ну и far2l /? кое что выводит..

**Comment by singalen** [comment]
С появлением консольной версии можно закрывать, наверное?
