### ISSUE TITLE
Unlimited terminal with scrolling

### ISSUE THREAD

**Issue by flyasky** [elfmz/far2l#259]
Is it possible?

**Comment by elfmz** [comment]
what mean unlimited?
scrolling posible. Use mouse scroll wheel or press ctrl+shift+f3 or ctrl+shift+f4

**Comment by flyasky** [comment]
Thank you! I didn't know about those hotkeys.

**Comment by KarelWintersky** [comment]
А можно добавить еще и Ctrl+Shift + стрелки?
