### ISSUE TITLE
latest version runs in console (instead of running in GUI)

### ISSUE THREAD

**Issue by ibobak** [elfmz/far2l#2596]
I have Ubuntu 22.04

In don't know what you've done in the latest version, but here is what I have:
![image](https://github.com/user-attachments/assets/a73411df-44bc-4077-a880-03c96fd1c2d0)
![image](https://github.com/user-attachments/assets/4fadf89b-45eb-42b2-bcae-23d0ce14462a)

What helps:   to get one of the previous versions, rebuild and install.

**Comment by ibobak** [comment]
![image](https://github.com/user-attachments/assets/b92c9cc7-562c-4873-8806-b9d202c24cff)

**Comment by ibobak** [comment]
So, in general, it was like this:   I had it  apt installed  long ago.  Then Ubuntu offered to update the far2l.   After this it started behaving this weird way:  if I click "new window", it runs a console far2l instead of running GUI.

I just did a recompilation of 2.6.2 and it works normally now.

**Comment by akruphi** [comment]
After **Dec 22 2024** far2l has 2 different desktop icons:  **far2l** to run `far2l --tty` and **far2l-wx** to run `far2 --notty`. See #2573 You should simple change far2l icon in GNOME panel to far2l-wx.

@mitya57 may be we need rename `far2l.desktop` to `far2l-tty.desktop` (I not sure about naming) to avoid such confusion for users?

**Comment by mitya57** [comment]
@ibobak Yes, you should unpin the current icon from the panel, then search in the applications list for “far2l (WX GUI)” and pin that version.

@akruphi If we rename, then existing pinned launchers will stop working at all (and will display a broken icon). I am not sure this is better.

**Comment by unxed** [comment]
```
sudo apt remove far2l*
sudo apt install software-properties-common
sudo add-apt-repository ppa:far2l-team/ppa
sudo apt install far2l-gui
```

Пробовали?
