### ISSUE TITLE
В последней собранной версии слетел нормальный tty в терминале git for windows

### ISSUE THREAD

**Issue by n0isy** [elfmz/far2l#2598]
Новая сборка:
![изображение](https://github.com/user-attachments/assets/6a7ce4fe-7367-441c-a4b9-b787fb7412b7)
Ранняя сборка:
![изображение](https://github.com/user-attachments/assets/0f350f6e-4ceb-4497-9742-4ac11b50032f)
Скрипт сборки, которым пользовался года 4:
```
apt-get install gawk m4 libx11-dev libxi-dev libpcre3-dev libxerces-c-dev libspdlog-dev libuchardet-dev libssh-dev libssl-dev libsmbclient-dev libnfs-dev libneon27-dev libarchive-dev cmake g++ git -y
git clone https://github.com/elfmz/far2l
mkdir far2l/_build
cd far2l/_build
cmake -DUSEWX=no -DCMAKE_BUILD_TYPE=Release ..
make -j$(nproc --all)
make install
cd ~
far2l
```

Ubuntu 22.04.

Windows с терминалом опции:
![изображение](https://github.com/user-attachments/assets/9bb6c427-a7ef-43f3-b16f-242cd2ecbcd3)

Дайте плиз коммит, где меняли xterm коды, где оно работает как прежде.

**Comment by n0isy** [comment]
Как минимум откатился сюда:
работает как прежде: e2fedec0924fc6a6f9b15875e04d3a047f523ae9
не работает: 7001caafa2525d06268f0df34b105ce3c635e8aa

**Comment by n0isy** [comment]
Сузил:
работает как прежде  3bcaa130d979c522001dc4fd4fe4a3aa2e2533bb
не работает fd67ea82e76d9090321cd4c2d529eba144e3cc52

**Comment by n0isy** [comment]
https://github.com/elfmz/far2l/commit/18ffe8e9413be6d0ace870cf9377bf503589967c

Вот этот коммит портит экран.

**Comment by n0isy** [comment]
```
git checkout master
git checkout 18ffe8e9413be6d0ace870cf9377bf503589967c~ -- WinPort/src/Backend/TTY/TTYOutput.cpp
```
после сборки всё норм.

**Comment by Zeroes1** [comment]
А что за терминалка на картинке?

**Comment by n0isy** [comment]
@Zeroes1 
> А что за терминалка на картинке?

MSYS2 форк MinGW. Ставится вместе с git for windows.

_Для винды была лучшая (транспарентная поддержка всего из линукса). А что теперь в windows по дефолту, я не тестил (наверное там теперь windows terminal)._

**Comment by unxed** [comment]
Выглядит как обрезанный форк PuTTY. В любом случае, надо понять, какие из ESC последовательностей этого коммита ломают этот терминал. Надо бы их просто в командной строке баша погонять и посмотреть, что будет.

**Comment by n0isy** [comment]
@unxed https://git-scm.com/downloads/win

Или я могу погонять если скажете как

**Comment by unxed** [comment]
Попробуйте там в этой среде выполнить по очереди каждую из этих команд. Надо понять, после которой из них начинает проявляться баг.

```
echo -e "\e[?2c"
echo -e "\e[3 q"
echo -e "\e]50;CursorShape=2\a"
echo -e "\e[?6c"
echo -e "\e[0 q"
echo -e "\e]50;CursorShape=0\a"
```

**Comment by n0isy** [comment]
```
echo -e "\e]50;CursorShape=2\a"
```
Вот эта команда даёт эффект, но при этом
```
echo -e "\e]50;CursorShape=0\a"
```
Такая его НЕ снимает.
Эффект перманентный.

**Comment by n0isy** [comment]
![изображение](https://github.com/user-attachments/assets/135b02da-de5e-45fb-8b50-5c885891c14d)
Текст становится жирным.

**Comment by unxed** [comment]
А если заменить 50 на 1337?

**Comment by n0isy** [comment]
@unxed То глюка нет. А там должен быть какой-то эффект с курсором?
Его тоже нет ))

**Comment by unxed** [comment]
> А там должен быть какой-то эффект с курсором?

Конкретно этот код — для iTerm2 только. И он неправильный, вместо 50 должно быть 1337. Я устаревшую инфу использовал, когда писал.

Это должно решить проблему:
https://github.com/elfmz/far2l/pull/2599

**Comment by n0isy** [comment]
@unxed Пашет как надо. Благодарю.
