### ISSUE TITLE
Far doesn't allow to enter characters other than latin.

### ISSUE THREAD

**Issue by invy** [elfmz/far2l#26]
For example try to rename file, so it contains Cyrillic characters.

**Comment by elfmz** [comment]
Works fine for me. What you have here? - 
![image](https://cloud.githubusercontent.com/assets/20957349/18196837/7eef7c7e-70fc-11e6-8ddc-4a6428a37d60.png)

**Comment by invy** [comment]
I'm using XIM.

**Comment by invy** [comment]
Just tested, works with IBus.

**Comment by elfmz** [comment]
test now with XIM

**Comment by invy** [comment]
Yep, looks like fixed.
