### ISSUE TITLE
Files highlighting: support Linux attributes

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#262]
Ctrl-A supports Unix-style attributes just fine.
But files highlighting cannot color executable files if they are just executable, because there is no such option if highlighting configuration.
Adding at least an "Executable" checkbox would help.
Thanks.

**Comment by elfmz** [comment]
Actually executable attribute processed by default, its just highlighting configuration dialog doesn't know about it. so trying to modify something in that dialog may break executables highlighting
If that happened for you you can revert to default settings by
rm -rf ~/.config/far2l/REG/HKU/c/k-Software/k-Far2/k-Colors
and wait til that dialog will be fixed..
