### ISSUE TITLE
Диблированы имена кадалогов в архиве

### ISSUE THREAD

**Issue by yujiaao** [elfmz/far2l#265]
Диблированы имена кадалогов в архиве RAR
![farimg](https://cloud.githubusercontent.com/assets/2154284/23984677/c6cd7a3a-0a55-11e7-95f0-8b697669ae89.png)

**Comment by elfmz** [comment]
А можно экземпляр такого архива? С теми что есть у меня, как водится, не воспроизводится..

**Comment by yujiaao** [comment]
The attached file may be litter big, I can not find some small ones

**Comment by yujiaao** [comment]
The attached file may be litter big, I can not find some small ones

![_251](https://cloud.githubusercontent.com/assets/2154284/24028892/a819f074-0b0d-11e7-8fa9-d1235dd56c2c.png)
because they not support RAR upload,  i rename it to pdf, you must rename it first.

[this_is_a_rar.pdf](https://github.com/elfmz/far2l/files/849662/this_is_a_rar.pdf)
