### ISSUE TITLE
не сбрасывается состояние терминала после возвращения из программ в far

### ISSUE THREAD

**Issue by volth** [elfmz/far2l#267]
проще показать:

![far2](https://cloud.githubusercontent.com/assets/508305/24053947/82d72d16-0b32-11e7-842d-9da7b5fa093e.png)

Вот тут после первого ```echo``` залип зелёный цвет, после второго - красный.
Цвета это не большая проблема, но в терминале ещё есть какие-то переменные связанные с тем как он обрабатывает перевод строки.

Бывает, прервёшь какую-нибудь программу по ```Ctrl-C```, а потом вывод следующей запущенной из-под фара программы пишется в одну строку (самую нижную в окне терминала), по ```\n``` строки не скроллятся наверх.

**Comment by elfmz** [comment]
Пока есть недокументированный "лайфхак": ввести команду 'exit' - что вызовет завершение процесса шелла и всей его обвязки. Любая следующая команда запустит новый шелл. Полезно не только для сброса проблем с форматированием, но и для того чтобы "почистить" энвиронмент.
