### ISSUE TITLE
Declare original FAR revision

### ISSUE THREAD

**Issue by skabashnyuk** [elfmz/far2l#268]
I'm trying find the cause of https://github.com/elfmz/far2l/issues/211,
doing that I'm trying to recover syslog functionality. And looks like 
then you made first commit of far2l some part of functionality was removed. It would 
be helpful if you can define somewhere in docs the revision of far when far2l fork was made.

**Comment by elfmz** [comment]
fork was made from this: https://sourceforge.net/p/farmanager/code/HEAD/tree/tags/before_3.0_split/

**Comment by elfmz** [comment]
About #211. See WinPort/src/UI/Paint.cpp. There is optimization in rendering so if renderer detects that some multiple characters sequence in line consists of characters of width equal to selected monospace font width - it outputs them as single string. wxPaintDC::GetTextExtent used to detect single character's size, so it looks like on OSX for some monospaced font sizes (that are not multiple of 5) total string length not exactly equal to sum of length returned by GetTextExtent for each character of string.

**Comment by skabashnyuk** [comment]
@elfmz thx

**Comment by unxed** [comment]
> Fork was made from this: https://sourceforge.net/p/farmanager/code/HEAD/tree/tags/before_3.0_split/

А этого кода не осталось, случайно? А то ссылка протухла, и не очень понятно, где теперь исходники оригинального Far2 брать

**Comment by elfmz** [comment]
git checkout builds/2.0.1807 в ихнем гитхабе

**Comment by unxed** [comment]
Спасибо!

> git checkout builds/2.0.1807 в ихнем гитхабе

Оставлю-ка на всякий случай здесь копию, ну мало ли что, пусть будет.

[Far Manager 2.0.1807.tar.gz](https://github.com/elfmz/far2l/files/7916432/Far.Manager.2.0.1807.tar.gz)
