### ISSUE TITLE
Far interferes with keyboard layouts, using AltGr (right Alt) for 3rd level characters.

### ISSUE THREAD

**Issue by invy** [elfmz/far2l#27]
There are many very convenient keyboard layouts like US Alternative International or Russian (with Ukrainian, Belarus), etc, which are using AltGr to enter 3rd level characters like umlauts.

However far intercepts combinations with AltGr not allowing to enter 3rd level characters.

**Comment by elfmz** [comment]
can you describe how to configure system to use such a layout?

**Comment by invy** [comment]
Actually, the easiest way to reproduce the problem is to choose normal German layout.
https://en.wikipedia.org/wiki/German_keyboard_layout

To type letters like '@' '~', all braces you need to use right Alt.

**Comment by unxed** [comment]
Is this still applicable?

**Comment by invy** [comment]
Sure it is. I can't type 'ä', 'ö', 'ü', 'ß' in US Alternative International keyboard layout.
