### ISSUE TITLE
При копировании файлов сбрасываются даты создания, изменения и доступа к файлам на текущую дату и время

### ISSUE THREAD

**Issue by OlegMaltzev** [elfmz/far2l#271]
При копировании файлов сбрасываются даты создания, изменения и доступа к файлам на текущую дату и время. Система Manjaro XFCE Edition (17.0.1).  Сборка far2l-git  r780.7f2308a-1 взята из AUR ( https://aur.archlinux.org/packages/far2l-git ) .
Раньше стоял mint и far2l более старой версии. За ним такого не замечал, хотя возможно глюк был и там.

P.S. Огромное спасибо автору, за великолепный файловый менеджер наконец то под линукс. Как мне его не хватало. Просто плакал от счастья, когда увидел, что портировали его наконец. )

**Comment by elfmz** [comment]
С временем был баг (точнее, недоделка оставленная на потом и благополучно забытая). А вот режим файлов сохраняется, если конечно в окне копирования была установлена галка Copy files access mode. Но не уверен насчет более старых версий.

**Comment by elfmz** [comment]
вобщем я закрываю. если проблема с модами все еще воспроизводится на свежих сырцых - переоткрывайте

**Comment by OlegMaltzev** [comment]
С файлами теперь все ок, с директориями проблема сохраняется.
