### ISSUE TITLE
Не удается собрать far2l

### ISSUE THREAD

**Issue by veremey1972** [elfmz/far2l#272]
Sorry, если вопрос глупый, в линуксе я почти чайник.
Имею аккаунт на суперкомпьютере как рядовой пользователь, ни о каких администраторских правах даже речи не идет, хозяйничать могу только внутри своей локальной директории.
Скачал исходники far2l с github. Установил cmake 3.8.0. Установил wx-виджеты.
Результат: при сборке все равно wx-виджеты not found.
Вопрос: где путь к этим виджетам прописан? Очевидно, при сборке они ищутся на уровне системы, а там их, видимо, нет. Где путь прописать?
Заранее спасибо!

**Comment by elfmz** [comment]
гм а зачем вам при таком раскладке far2l? по ssh он работать не будет..

**Comment by veremey1972** [comment]
Вы меня озадачили... Wal-commander работал - с использованием Xming... Это независимо от того, графический режим или консольный?

**Comment by elfmz** [comment]
А ну через удаленные иксы работать сможет да, но как собрать в таком экзотичном окружении так просто не подскажу. Кстати wxwidgets-у нужен GTK.

**Comment by veremey1972** [comment]
GTK, вроде, есть. А где в этой сборке ссылка на виджеты прописана? Или нигде, а просто по умолчанию где-то ищет?

**Comment by volth** [comment]
возможно, [nix](http://nixos.org/nix/download.html)'ом получится, он умеет работать на линуксе без root.
far2l там уже есть в пакетах.

**Comment by veremey1972** [comment]
Спасибо за подсказку направления. Сейчас попытаюсь детально разобраться, что такое nix и с чем его едят... :-) Если возникнут вопросы, напишу.

**Comment by veremey1972** [comment]
Первая проблема - возможно, я туплю... Чтобы nix при установке не затребовал администраторских полномочий, нужно создать директорию nix. А где она должна быть? За пределами моей пользовательской папки? Тогда - финиш. Внутри я ее где только не создавал: и в верхнем каталоге, и в текущем... Ни в какую.

**Comment by lieff** [comment]
Можно собрать wxwidgets в свою папку, ./configure --prefix=/path_to_home_folder, make, make install. И в cmake добавить пути к инклудам и либам из локальной папки.

**Comment by veremey1972** [comment]
Wxwidgets я в свою папку собрал с самого начала. Это прошло нормально.
Вопрос как раз и был в том, в каком файле и в какие строчки добавлять эти пути.

**Comment by volth** [comment]
@veremey1972. По умолчанию в корне. ```/nix```. В своём каталоге тоже можно (видел в чужих обсуждениях, так делают), но как - сходу не раскажу, надо гуглить или смотреть в исходник

**Comment by veremey1972** [comment]
**Volth**, я прописал переменную окружения в .bashrc, проверил echo - прописалась. Но все равно не работает. И сообщение об ошибке то же.
Сначала что-то распаковывает в tmp,
затем - performing single user installation of nix,
затем - directory /nix does not exist; creating it by running 'mkdir -m 0755 /nix && chown <домашняя папка> /nix' using sudo
и требует пароль.

**Comment by veremey1972** [comment]
Нет, судя по всему, без администраторского создания папки nix ничего не пойдей, и это - из соображений безопасности.
Попробую оставить в покое nix и начать все с начала...

**Comment by mslasm2** [comment]
глупый вопрос - а нельзя собрать на другом компьютере (если что специально можно в виртуальной машине создать среду для компиляции) и загрузить статически слинкованый ехе-шник (ну, линукс эквивалент) на тот суперкомпьютер? Или фар не статически слинкован?

**Comment by veremey1972** [comment]
А будет ли это работать? Версии Linux могут оказаться несовместимыми.
И потом, все равно понадобится наверняка кроме исполняемого модуля что-то по каким-то директориям раскладывать, которые мне недоступны. Или обойдется без этого?..

**Comment by menix** [comment]
всем привет,
кто подскажет такое.
собираю по инструкции и приехал:
```~/soft/far/build$ cmake -DCMAKE_BUILD_TYPE=Release ../far2l
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- generating headers and languages
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.5)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/imatvieiev/soft/far/build```
```~/soft/far/build$ make -j4
Scanning dependencies of target bootstrap
make[2]: *** No rule to make target '/home/imatvieiev/soft/far/far2l/bootstrap/farlng', needed by 'bootstrap/CMakeFiles/bootstrap'.  Stop.
CMakeFiles/Makefile2:122: recipe for target 'bootstrap/CMakeFiles/bootstrap.dir/all' failed
make[1]: *** [bootstrap/CMakeFiles/bootstrap.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2```

**Comment by lieff** [comment]
хм, cmake_minimum_required в начале присутствует, может лишняя пустая строка в самом начале мешает?

**Comment by x-xabl** [comment]
Не собирается из коробки с помощью ninja

`ninja: error: '/home/xabl/src/far/far2l/bootstrap/farlng', needed by 'bootstrap/CMakeFiles/bootstrap', missing and no known rule to make it`

Файла действительно нет. Как решали?

**Comment by v-dem** [comment]
The same issue when using make:

`Scanning dependencies of target bootstrap
make[2]: *** Нет правила для сборки цели «/home/vitaly/far/far2l/far2l/bootstrap/farlng», требуемой для «bootstrap/CMakeFiles/bootstrap».  Останов.
CMakeFiles/Makefile2:122: ошибка выполнения рецепта для цели «bootstrap/CMakeFiles/bootstrap.dir/all»
make[1]: *** [bootstrap/CMakeFiles/bootstrap.dir/all] Ошибка 2
Makefile:127: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2`

**Comment by BekzhanKassenov** [comment]
Столкнулся с тем же самым, мой косяк: я создал папку build внутри склонированной папки из гита.

**Comment by andrey-dubinchak** [comment]
подскажите, пожалуйста - в чем может быть причина ошибки (собираю в Qt на macOS):
[ 34%] Built target FARStdlib
[ 34%] header
/bin/sh: gawk: command not found
sh: gawk: command not found
make[2]: *** [far2l/bootstrap/copyright.inc] Error 127
make[2]: *** Deleting file `far2l/bootstrap/copyright.inc'
make[1]: *** [far2l/bootstrap/CMakeFiles/bootstrap.dir/all] Error 2
make: *** [all] Error 2
16:51:59: The process "/usr/local/bin/cmake" exited with code 2.
Error while building/deploying project FAR (kit: Desktop Qt 5.11.2 clang 64bit)
When executing step "CMake Build"

gawk установлен через Homebrew:
Warning: gawk 4.2.1 is already installed and up-to-date
спасибо!
