### ISSUE TITLE
far2l's editor fails on 1-byte files

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#274]
try to open attached file in far2l's editor
viewer works ok

[1.txt](https://github.com/elfmz/far2l/files/965985/1.txt)

**Comment by cycleg** [comment]
По умолчанию его пытаются открыть в UTF-8, и в нем как бы теряется первый байт, если тут же начать редактировать. Но для 1-байтного файла это не смертельно, прямо скажем. А еще его можно переключить на 866 кодировку, и все сразу встанет на место. Короче, глюк в том, что последовательность байтов длиной 1 неправильно транслируется из UTF-8 во внутреннее представление (UTF-32, видимо).

**Comment by unxed** [comment]
Точно.

Я подозревал что-то, связанное с UTF, но не смог сформулировать в связанный текст :)
