### ISSUE TITLE
README update for plug in writers

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#277]
https://github.com/cycleg/far-gvfs/commit/cb4c7089c45e635ad10c7fa489b883bdc4c6ac1e

> Replace std::wstring_convert with MB2Wide/Wide2MB from far2l/utils, see [#20](https://github.com/cycleg/far-gvfs/issues/20)

Вот бы ещё в README far2l дописать, что при создании плагинов лучше всего сразу делать так, чтобы собиралось на последнем дебиане.

**Comment by cycleg** [comment]
Не совсем так. В far2l есть WinPort и есть utils. Разумно сформулировать так: сначала поискать нужное там, а уж потом подтягивать сторонние зависимости. Но надо понимать, что и то, и другое -- совсем не Boost, средств на все случаи жизни в них нет.

**Comment by unxed** [comment]
Думаю, это можно пока закрыть, а readme дописывать по мере реальной потребности реальных авторов плагинов, буде таковые появятся.
