### ISSUE TITLE
"Alt"+"Arrows" text selection bug in editor

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#279]
1. Create new text file ("Shift"+"F4", "Enter").
2. Type "test".
3. Press "Alt"+"Left", then "Alt"+"Right".
4. Press "Backspace". It will not work.

Any other arrow key press (without "Alt") fixes backspace behavior.

There are no "Alt"+"Arrow" or "Alt"+"Arrow"+* key combinations defined in my DE's keyboard shortcuts menu.

"Exclusive handle hotkeys..." does not fixes it.

**Comment by unxed** [comment]
Another one bug:

1. Create new text file ("Shift"+"F4").
2. Type "test test".
3. Press "Right Ctrl"+"Left".
4. Press "Right Ctrl"+"Shift"+"Right".
5. Try to exit editor with "Esc". It will not work until switching to another window and back. It looks like "Ctrl" stucks in pressed state.

NB! This bug is not reproduced with "Left Ctrl", only with "Right Ctrl".

Sometimes you have to do it several times before the bug begins to happen.

Really annoying thing.

**Comment by unxed** [comment]
Seems to be an upstream issue - reproduced in far2 in wine.

**Comment by lieff** [comment]
Reproduced on Ubuntu 16.04.

**Comment by elfmz** [comment]
Интересно что баг воспроизводится и в 3м фаре. Всегда удивлялся людям, которые переписав нафиг туеву хучу кода, умудряются бережно портировать все баги.
