### ISSUE TITLE
Ctrl key stuck in some cases

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#281]
1. Set keyboard layout switching hotkey to "Ctrl+Shift" in DE settings.
2. Open far2l.
3. Create new text file ("Shift"+"F4", "Enter").
4. Type "test test".
5. Press "Right Ctrl"+"Left".
6. Press "Right Ctrl"+"Shift"+"Right".
7. Try to exit editor with "Esc". It will not work until switching to another window and back. It looks like "Ctrl" stucks in pressed state.

I can not reproduce this bug with "Left Ctrl", only with "Right Ctrl".

Sometimes you have to do it several times (not more than 20) before the bug happens. Looks like explicit timing of each keypress matters.

Definitely not a problem of my DE or settings, as "Right Ctrl"+"Shift"+"Arrows" works as expected in other apps like LibreOffice Writer. This bug is also not reproduced in far2l 079084e. My tests shows that it has been introduced somewhere between 079084e and 06a27b1.

Not reproduced then "Alt"+"Shift" is set as keyboard layout switching hotkey.

"Exclusive handle hotkeys..." does not fixes it.

Tested on two different PCs.

Mint 18.1 x64 / MATE.

**Comment by unxed** [comment]
This also happens in all far2l text input fields and in terminal.

**Comment by volth** [comment]
confirmed.
I suspected xfce clipboard manager as it used to happen after "RCtrl+Ins" but it seems to be a far2l-only issue.

**Comment by lieff** [comment]
Same here, confirmed.

**Comment by elfmz** [comment]
Don't you all have 'exclusive handle hotkeys' option enabled? Could not repro issue until set it on for right control keys
