### ISSUE TITLE
Crash on Mac, Shift-F7 in editor

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#284]
Thread 2 Crashed:
0   far2l                         	0x0000000100cd6623 Edit::Search(UnicodeString const&, UnicodeString&, int, int, int, int, int, int*) + 1315
1   far2l                         	0x0000000100cea40d Editor::Search(int) + 2109
2   far2l                         	0x0000000100ce3e9d Editor::ProcessKey(int) + 22237
3   far2l                         	0x0000000100d0acc4 FileEditor::ReProcessKey(int, int) + 10660
4   far2l                         	0x0000000100d0830d FileEditor::ProcessKey(int) + 29
5   far2l                         	0x0000000100dbfe3e Manager::ProcessKey(unsigned int) + 2606
6   far2l                         	0x0000000100dbe167 Manager::ProcessMainLoop() + 359
7   far2l                         	0x0000000100dbe25e Manager::ExecuteModal(Frame*) + 222
8   far2l                         	0x0000000100d4e695 FindDlgProc(void*, int, int, long long) + 7253
9   far2l                         	0x0000000100cac3ef Dialog::DlgProc(void*, int, int, long long) + 239
10  far2l                         	0x0000000100cb8afa Dialog::ProcessKey(int) + 602
11  far2l                         	0x0000000100dbfe3e Manager::ProcessKey(unsigned int) + 2606
12  far2l                         	0x0000000100dbe167 Manager::ProcessMainLoop() + 359
13  far2l                         	0x0000000100dbe25e Manager::ExecuteModal(Frame*) + 222
14  far2l                         	0x0000000100cc09f8 Dialog::Process() + 184
15  far2l                         	0x0000000100d53732 FindFilesProcess(Vars&) + 3762
16  far2l                         	0x0000000100d56857 FindFiles::FindFiles() + 6951
17  far2l                         	0x0000000100d56bd5 FindFiles::FindFiles() + 21
18  far2l                         	0x0000000100d385b8 FilePanels::ProcessKey(int) + 4216
19  far2l                         	0x0000000100dbfe3e Manager::ProcessKey(unsigned int) + 2606
20  far2l                         	0x0000000100dbe167 Manager::ProcessMainLoop() + 359
21  far2l                         	0x0000000100dbf3b2 Manager::EnterMainLoop() + 98
22  far2l                         	0x0000000100db78d9 MainProcess(wchar_t const*, wchar_t const*, wchar_t const*, wchar_t const*, int, int) + 3001
23  far2l                         	0x0000000100db6d13 MainProcessSEH(UnicodeString&, UnicodeString&, UnicodeString&, UnicodeString&, int, int) + 115
24  far2l                         	0x0000000100db977f FarAppMain(int, char**) + 7599
25  far2l                         	0x0000000100c3cb33 WinPortAppThread::Entry() + 35
26  far2l                         	0x0000000100f4a02f wxThread::CallEntry() + 15

**Comment by sergey-nbl** [comment]
It seems resolved on latest source base

**Comment by singalen** [comment]
Tried it, couldn't reproduce.
