### ISSUE TITLE
vbuild.sh: Permission denied

### ISSUE THREAD

**Issue by fedorkov** [elfmz/far2l#294]
Build fails with several permission denied errors.
Read/execute file permissions are present.
[build log](https://pastebin.com/raw/wePRrx0s)

**Comment by lieff** [comment]
What distribution and filesystem used? It looks like nothing can be executed in cloned directory despite execution bits present.

**Comment by fedorkov** [comment]
Arch Linux, ext4.

**Comment by lieff** [comment]
Ubuntu 17.10 same steps is fine. May be this volume mounted with execution protection? Can you run ./vbuild.sh or /home/dante/git/build/tools/farlng manually?

**Comment by fedorkov** [comment]
Damn it. I recently linked ~/git to an HDD mounted with noexec. Now I moved it back and now everything works fine. Sorry for bothering you.

**Comment by lieff** [comment]
I don`t know :) I think most active is Russian speaking.
