### ISSUE TITLE
несколько запущенных far стирают историю комманд друг-друга

### ISSUE THREAD

**Issue by volth** [elfmz/far2l#295]
Если запущено несколько far2l, то они стирают историю комманд друг-друга.
Ту, которая по видна Alt-F8, Ctrl-E, Ctrl-X

Похоже, что far2l работает с глобальной историей так, как будто он единственный запущенный экземпляр.
Не могу сказать точно когда это происходит, при старте нового far2l или при выходе, тут наверное из чтения кода будет проще понять, чем ставя эксперименты.

В виндовом Far3 такого не замечал, да и bash вроде ничего не теряет.

**Comment by lieff** [comment]
Да, тоже замечал такое с историей которая высвечивается при печати командной строки.

**Comment by volth** [comment]
проблема осталась, только проявляется реже.

раньше достаточно было запустить 2-3 фара чтобы потерять историю наверняка.

сейчас пропадание истории случается раз в несколько дней.

**Comment by elfmz** [comment]
эм, а оно вообще теряется (становится пустой) или перезаписывается какой то, без мержа?

**Comment by volth** [comment]
вообще теряется.

**Comment by volth** [comment]
Возможно, не совсем дотла.

Просто в этой истории копятся "знания", ну например "killall myprocess1", "killall firefox" которые когда-то запускались.

Я набираю "killall " ожидая, что мне не придётся набирать имя процесса - и внезапно оказывается, что вот этих "killall myprocess1", "killall firefox" в истории нет.
Всех нет.
Но история не пуста, там есть история за последние часы, а вот за прошлые дни истории нет.

Можно предположить, что полная очистка истории произошла N часов назад, прошла незамеченной
Но может быть произошло обрезание истории в результате неудачного мержа, так что осталась история только за посдение N часов.

**Comment by elfmz** [comment]
Подправил кое че, хз поможет ли, надо наблюдать, причем желательно с включенным отладочным выводом - на предмет сообщений от SharedResource.
