### ISSUE TITLE
GLIB_VERSION_MIN_REQUIRED must be >= GLIB_VERSION_2_26

### ISSUE THREAD

**Issue by chodorenko** [elfmz/far2l#3]
Пытался собрать на SUSE Leap 42.1, все нужные библиотеки поставлены но при билде получаю ошибку не соотвествия версии glib2  просит минимум 2_26 , а у меня стоят 2.44 

chodorenko@chodorenko-linux:~/9/far2l.git/trunk/WinPort> make -f WinPort.mk
In file included from /usr/include/glib-2.0/glib/gtypes.h:34:0,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from KeyFileHelper.cpp:2:
/usr/include/glib-2.0/glib/gversionmacros.h:217:2: error: #error "GLIB_VERSION_MIN_REQUIRED must be >= GLIB_VERSION_2_26"
 #error "GLIB_VERSION_MIN_REQUIRED must be >= GLIB_VERSION_2_26"
  ^
In file included from /usr/include/glib-2.0/glib/galloca.h:32:0,
                 from /usr/include/glib-2.0/glib.h:30,
                 from KeyFileHelper.cpp:2:
/usr/include/glib-2.0/glib/gtypes.h:446:2: error: #error unknown ENDIAN type
 #error unknown ENDIAN type
  ^
WinPort.mk:272: ошибка выполнения рецепта для цели «Debug/KeyFileHelper.cpp.o.d»
make: *** [Debug/KeyFileHelper.cpp.o.d] Ошибка 1
chodorenko@chodorenko-linux:~/9/far2l.git/trunk/WinPort> rpm -qa | grep glib2
glib2-devel-2.44.1-2.3.x86_64
glib2-devel-32bit-2.44.1-2.3.x86_64
glib2-tools-32bit-2.44.1-2.3.x86_64
glib2-lang-2.44.1-2.3.noarch
glib2-tools-2.44.1-2.3.x86_64
libpackagekit-glib2-18-1.0.7-3.5.x86_64
libpackagekit-glib2-devel-1.0.7-3.5.x86_64

Также наблюдаю проблемы с кастами

./Main.cpp: In member function ‘wxString FixedFontLookup::Query()’:
./Main.cpp:246:62: error: invalid cast from type ‘wxString’ to type ‘const wchar_t*’
   fprintf(stderr, "FixedFontLookup: %ls\n", (const wchar_t *)_result);
                                                              ^
./Main.cpp: In function ‘void InitializeFont(wxFrame*, wxFont&)’:
./Main.cpp:264:59: error: invalid cast from type ‘wxString’ to type ‘const wchar_t*’
     printf("InitializeFont: used %ls\n", (const wchar_t *)str);
                                                           ^
./Main.cpp: In constructor ‘WinPortPanel::WinPortPanel(WinPortFrame*, const wxPoint&, const wxSize&)’:
./Main.cpp:304:73: error: invalid cast from type ‘wxString’ to type ‘const wchar_t*’
  fprintf(stderr, "Font: '%ls' %s\n", (const wchar_t *)_font.GetFaceName(), _font.IsFixedWidth() ? "monospaced" : "not monospaced");
                                                                         ^

**Comment by elfmz** [comment]
а ща?

**Comment by lieff** [comment]
Нет, это https://github.com/elfmz/far2l/commit/fbb8e5cc328f5674dca6f077291511850f4977eb не правильно.
Нужно использовать pkg-config glib-2.0 --cflags вместо хардкодных путей. Вот я исправил:
https://github.com/lieff/far2l/commit/d01365f6e3537ae02e7ea3abeb643d1ab14d419a
У меня на OpenSUSE мейком теперь собралось, не знаю можно ли в проект codelite так же в настройку путей встроить запуск pkg-config.

**Comment by elfmz** [comment]
ага спасибо, посмотрим что ща у chodorenko  будет..

**Comment by chodorenko** [comment]
Собралось нормально https://screencloud.net/v/tqE0
PS: Парни спасибо , это то что я ждал так долго
