### ISSUE TITLE
Editor numbered bookmarks (LCtrl-1..LCtrl-9) not working on Mac OS X

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#301]
I remember FAR having a numbered bookmark functionality: LCtrl-1..LCtrl-9 sets a bookmark, RCtrl-1..RCtrl-9 goes to respective one.

This doesn't work on OS X neither with Ctrl nor with Cmd.

**Comment by elfmz** [comment]
For me this doesn't work even in Windows FAR 3. May be it implemented by some plugin?

**Comment by singalen** [comment]
Nope, it has been in the core for a long time. `editor.cpp:892` :
```
	if (Key>=KEY_CTRL0 && Key<=KEY_CTRL9)
		return GotoBookmark(Key-KEY_CTRL0);

	if (Key>=KEY_CTRLSHIFT0 && Key<=KEY_CTRLSHIFT9)
		Key=Key-KEY_CTRLSHIFT0+KEY_RCTRL0;

	if (Key>=KEY_RCTRL0 && Key<=KEY_RCTRL9)
		return SetBookmark(Key-KEY_RCTRL0);
```

**Comment by elfmz** [comment]
Ah, vice verse - right sets, left remembers. This works in windows far and in linux too.
MAC I have only hackintosh and there it works tricky: right control + number sets bookmark and any Win number restores it. Not sure how this mapped to physical mac keyboard..

**Comment by singalen** [comment]
I appreciate changing from LCtrl to Win, as Ctrl-digit is a traditional key to switch workspaces on Mac. It's no longer the default, but anyway.
Might be a false alarm, let me research it.

**Comment by singalen** [comment]
...disregard that, all the Ctrl keys are mapped to Cmd on Mac anyway.
Debugging it. I see a problem: both left and right Cmd keys generate LCtrl codes.
Looking into it...

**Comment by singalen** [comment]
Looks like `void WinPortPanel::OnKeyDown( wxKeyEvent& event )` always has a key code 308 for both left and right Cmd on Mac. Uh-oh.

I see no trace of http://trac.wxwidgets.org/ticket/12450#comment:1 in `kbdstate.h` and [in wxWidgets doc](http://docs.wxwidgets.org/3.1/defs_8h.html). 
If `wxKeyEvent.m_rawCode` and `wxKeyEvent.m_rawFlags` don't help, then I'm afraid wxWidgets just hide the distinction 8((((

**Comment by singalen** [comment]
Working now!

**Comment by elfmz** [comment]
But there were no changes in that code. May be wx fixed issue? Or Apple :)

**Comment by singalen** [comment]
Who knows.
