### ISSUE TITLE
Ctrl+Shift+Alt not working

### ISSUE THREAD

**Issue by burunduk3** [elfmz/far2l#306]
Far Manager shows background console while pressing Ctrl, Shift and Alt simultaneously. far2l does not (at least for me).

Workaround: Ctrl+O shortcut does the same.

**Comment by elfmz** [comment]
wxWidgets doesnt send left alt kerypress if ctrl+shift pressed. However right alt delivered and ctrl+shift+RAlt works for me, but behaviour slightly different - console disappears only after all keys released, but not only ralt.

**Comment by corporateshark** [comment]
Works on OSX. Both `Ctrl+Alt+Shift` and `Cmd+Alt+Shift` do the same thing as expected.
