### ISSUE TITLE
Addons: Esc

### ISSUE THREAD

**Issue by corporateshark** [elfmz/far2l#307]
Use Esc to toggle panels on/off.

**Comment by lieff** [comment]
Esc already used in viewer/editor etc. IMHO panels is good ending place in esc-esc..esc sequence.

**Comment by corporateshark** [comment]
In the original Far it is available as an addon. 

Addons/Macros/Panel.Esc.lua

**Comment by lieff** [comment]
Ah, as Addon I think it's ok. But it's more Far3 related, Far2 seems do not support lua scripts.

**Comment by corporateshark** [comment]
Sure. But similar optional functionality was in Far2 on Windows for ages.

**Comment by lieff** [comment]
Yes, it seems in far2 it's controlled by registry.

**Comment by corporateshark** [comment]
How difficult is it to add all those optional macros back?

**Comment by lieff** [comment]
Most code already present in macro.cpp, it must be not too hard. But some GUI or utility also needed to modify registry.

**Comment by corporateshark** [comment]
https://github.com/corporateshark/far2l-macros
