### ISSUE TITLE
Wrong commands saved in .bash_history

### ISSUE THREAD

**Issue by dsdante** [elfmz/far2l#311]
1. Open far2l.
2. Run `cd` in its command line.
3. Exit far2l.

Expected: `cd` is appended to `~/.bash_history`

Actual result: wrong line appended:
` . /tmp/far2l_3e8_0/vtcmd/a3c_0x7fbfe8003b40;echo -ne "=$FARVTRESULT:$FARVTMARKER"`

**Comment by elfmz** [comment]
Well, far2l executes commands starting from space expecting that they will not be saved to bash_history at all due to HISTCONTROL set to ignorespace  or ignoreboth
And all that tricks with temporary scripts and echo -ne its the best way I could find to work control interactive shell :(

**Comment by dsdante** [comment]
I haven't heard of HISTCONTROL before, and Arch doesn't set it by default. So yeah, I just set it.
Can far2l set it automatically for its own shell?

**Comment by elfmz** [comment]
edit ~/.bashrc - look for HISTCONTROL= directive there, if its not present there - then just add 
HISTCONTROL=ignorespace

**Comment by dsdante** [comment]
Yes, I did it, as I said.
