### ISSUE TITLE
wxInitialize failed for Headless Ubuntu console, exit code 255

### ISSUE THREAD

**Issue by Slach** [elfmz/far2l#313]
setup far2l from PPA
```
sudo add-apt-repository ppa:spvkgn/far2l-builds
sudo apt install far2l
```

when run far2l
```
far2l
echo $?
255
```
exptected result
0

when run following commands
```
far2l --help
08:10:26 AM: Error: Unable to initialize GTK+, is DISPLAY set properly?
wxInitialize failed
```

expected result show far console

**Comment by mmmcorpsvit** [comment]
same problem on Ubuntu 16, use VPS
and please add info: need around 2 Gb RAM for compile
i have only 1 Gb, and extend use this: http://www.serveridol.com/2014/08/03/how-do-i-create-swap-partition-in-linux-mkswap-operation-not-permitted/
recept work on hyperhost.ua

how fix run problem?

**Comment by Slach** [comment]
;) it's a strange decision, but far2l is not a console program ;) unlike midnight commander ;)

**Comment by mmmcorpsvit** [comment]
0_o.... em.... so what we can do? install X11 ?... oh goods...

**Comment by unxed** [comment]
@Slach @mmmcorpsvit try backend-separation branch and "far2l --tty"
