### ISSUE TITLE
Make it possible to build on macOS, following instructions in README.md

### ISSUE THREAD

**Issue by thinkingerrol** [elfmz/far2l#315]
According to screenshot borrowed from #302 <img src="https://user-images.githubusercontent.com/6576495/31271367-f39c2004-aa8f-11e7-9e86-4cc55a56c3b5.png"/>
 and instructions in README.md it is possible to build and run far2l on Mac. 

When following README.md instructions on my Mac `OS X El Capitan 10.11.4`, cmake detects and uses "AppleClang 7.3" which however does not support Thread Local Storage, so I switched to GCC 7.3.0 which I got via Homebrew. The TLS error was gone, but I got linker errors later below.

**TLS error with "AppleClang 7.3":**

``` sh
git clone https://github.com/elfmz/far2l
...
cd far2l
cmake -G "Unix Makefiles"
make -j4
...
[ 14%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/sudo/sudo_client.cpp.o
/path/to/your/far2l/WinPort/src/sudo/sudo_client.cpp:41:2: error: thread-local storage is not supported for the current target
        thread_local ThreadRegionCounter thread_client_region_counter = { 0, 0, MODIFY_UNDEFINED, false };
        ^
1 error generated.
```

**Linker error with GCC 7.3.0:**

`Toolchain-GCC.cmake:`
```
set(MY_GCC_BIN /usr/local/opt/gcc/bin)
set(CMAKE_C_COMPILER   ${MY_GCC_BIN}/gcc-7) 
set(CMAKE_CXX_COMPILER ${MY_GCC_BIN}/g++-7)
```

```
cd far2l
git checkout
rm CMakeCache.txt
cmake -DCMAKE_TOOLCHAIN_FILE=/Users/vit/Desktop/git/Toolchain-GCC.cmake -G "Unix Makefiles"
...
make -j4
...
[ 76%] Linking CXX executable ../tools/farlng
Undefined symbols for architecture x86_64:
  "std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> >::find(wchar_t const*, unsigned long, unsigned long) const", referenced from:
      wxFileSystem::URLToFileName(wxString const&)  in libwx_osx_cocoau-3.1.a(monolib_filesys.o)
      wxFileDialogBase::Create(wxWindow*, wxString const&, wxString const&, wxString const&, wxString const&, long, wxPoint const&, wxSize const&, wxString const&) in libwx_osx_cocoau-3.1.a(monolib_fldlgcmn.o)
 ```

**Comment by lieff** [comment]
Try add
```
set(CMAKE_CXX_COMPILER "clang++")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -stdlib=libc++ -lc++abi")
```
in cmake script.

**Comment by thinkingerrol** [comment]
With clang++ I always get the TLS error because my clang++ is 7.3. Did you succeed mostly with clang++ ?  Then I will have to get mine updated (will require update from El Capitan to latest OSX in case of Apple Clang).

With GCC, I always get the linker error, as described in ticket, related to std::string. This is how I configured wxWidgets, maybe that's the problem:
```sh
./configure --disable-shared --disable-debug CC=gcc CXX=g++ CXXFLAGS="-stdlib=libc++ -std=c++11" OBJCXXFLAGS="-stdlib=libc++ -std=c++11" LDFLAGS=-stdlib=libc++ --enable-monolithic --enable-unicode
```

**Comment by lieff** [comment]
I think problem in -stdlib=libc++, we should switch far2l cmake files to use it with gcc somehow. I will test it later.

**Comment by thinkingerrol** [comment]
Do you think it's important that wxWidgets is built with the same compiler as far2l ? I guess it is, but I'm not sure if "-lc++abi" can make it unimportant. I will try to build some wxWidgets simple user code to see if I reproduce the std::string related linker error. According to this SO question, similar error happened not only with far2l.

**Comment by thinkingerrol** [comment]
I think you are right, as explained [here](https://stackoverflow.com/a/24419967/5140740):

> `-stdlib=libc++` is a Clang (not GCC) option and tells clang to use LLVM `libc++` standard library (which is what Clang uses) rather than GNU `libstdc++` (which is what GCC uses).

Meanwhile I might as well get an updated Apple LLVM which I guess most `far2l` enthusiasts are using (?) on `macOS 10.12 Sierra` or `macOS 10.13 High Sierra`. I've been a slow updater!

**Comment by sergey-nbl** [comment]
I use El Capitan but don't build wxWidgets: build delivered with brew is enough to build and run far2l

**Comment by thinkingerrol** [comment]
Thanks Sergey. Perhaps could you try ```rm CMakeCache.txt && cmake -G "Unix Makefiles"``` and tell me your CXX compiler id ? In my case, it was initially
```
-- The C compiler identification is AppleClang 7.3.0.7030031
-- The CXX compiler identification is AppleClang 7.3.0.7030031
```
That CXX compiler failed for me because it lacks support for the ```thread_local``` keyword used in ```far2l/WinPort/src/sudo/sudo_client.cpp:41```

**Comment by sergey-nbl** [comment]
Well, mine is 
-- The C compiler identification is AppleClang 8.0.0.8000042
-- The CXX compiler identification is AppleClang 8.0.0.8000042

Since neither of Apple Tools  is my primary instrument, it was installed with default XCode and updated (I guess) without my engagement

**Comment by thinkingerrol** [comment]
Cool! I see. Important is the Clang version and not the macOS version. Also to keep in mind, Apple uses every opportunity to push & force users to update, even when it's not required functionally. Clearly, for ```far2l``` to compile on AppleClang, at least the version 8.x is required - which [immediately](https://trac.macports.org/wiki/XcodeVersionInfo) follows the version 7.3.x which I have.

**Comment by thinkingerrol** [comment]
Ok, got it working finally!

<img width="1144" alt="screen shot 2018-02-12 at 21 57 10" src="https://user-images.githubusercontent.com/24751357/36119327-e0e2396a-103f-11e8-80a8-0720b9ed18c0.png">

What solved the problem was the upgrade of AppleClang to version 9.0.0.x (8.0.0.x worked for others too). This was done via installing (free) XCode from App Store, and activating by running ```sudo xcodebuild -license``` in Terminal. XCode from App Store could only be installed after upgrading my macOS El Capitan 10.11 to latest version, which is currently 10.13.3 High Sierra.

XCode is also available for download [here](https://developer.apple.com/download/) for paying members of the Apple Developer Program.

After upgrades everything went straight forward:
```sh
git clone https://github.com/elfmz/far2l far
cd far && mkdir build && cd build && cmake -G "Unix Makefiles" ..
./install/far2l
```
