### ISSUE TITLE
OSX: Emulate Ins/Del keys on MacBook Pro

### ISSUE THREAD

**Issue by corporateshark** [elfmz/far2l#318]
There are no Ins/Del keys on the keyboard. This renders a lot of dialogs useless.

**Comment by corporateshark** [comment]
Solution for `Ins` in dialogs: https://github.com/corporateshark/far2l-macros/tree/master/k-Menu/k-CtrlBrowserForward
`Ctrl+±` (`±` is just above `Tab` and left to `1` on a MacBookPro keyboard)

**Comment by thinkingerrol** [comment]
What is ```Ins``` key supposed to do in a dialog? An example would be great. On Windows, I only used ```Ins``` in panels to select a group of files by wildcard. This doesn't work: given the following setup, ```Ctrl+±``` has no effect:
```
/Users/vit/.config/far2l/REG/HKU/c/k-Software/k-Far2/k-KeyMacros/k-CtrlBrowserForward
total 16
-rw-r--r--  1 vit  staff  22 Feb 16 23:18 v-DisableOutput
-rw-r--r--  1 vit  staff  18 Feb 16 23:18 v-Sequence

```

**Comment by corporateshark** [comment]
For example, it creates an entry in the File Associations dialog. It seems impossible to use the dialog without this key.

It works on my MacBook Pro. I've just retested it.

**Comment by corporateshark** [comment]
English.
I don't actually see a problem replacing `Ctrl+±` with something more portable. Just keep in mind that the whole point of this specific macro is to make Far dialogs usable on a small Apple keyboard.

**Comment by thinkingerrol** [comment]
I'm using MacBookPro 13" and with US English the ```±``` indeed appears above the ```TAB``` but only in combination with ```SHIFT```. Will try to find a more portable combination. I assume a restart is required to refresh those key-macros. Also would be nice if this can work in Panels for file selection.

**Comment by thinkingerrol** [comment]
Ok, ```Ins``` works for me in File Association dialog now. First, I had wrong directory structure, as in my comment above, missing the ```k-Menu``` subfolder. Second, I had to find a key combination such as ```Ctrl+I``` which is directly available on smaller 13" MBP keyboard. Anyway, your repo is useful, thanks!!

**Comment by thinkingerrol** [comment]
Awesome, this led me to close #317 too.

**Comment by corporateshark** [comment]
`Also would be nice if this can work in Panels for file selection.`
I tried to look for what is the textual representation for `Gray+`. No success, though.

**Comment by corporateshark** [comment]
Solved: https://github.com/corporateshark/far2l-macros
