### ISSUE TITLE
Shift+Enter is not working on OSX

### ISSUE THREAD

**Issue by corporateshark** [elfmz/far2l#320]
`open !.!` should be invoked for any file. But nothing actually happens.

**Comment by thinkingerrol** [comment]
Confirmed, but I didn't expect ```Shift+ENTER``` to ```open !.!```. Plain ```ENTER``` does ```open !.!``` if you configure it to do so via ```Commands->File associations``` menu as explained in #317. Not sure why you expected that behavior - maybe it does so on Windows when the ```Use Windows registered types``` option is enabled in System Settings?

**Comment by corporateshark** [comment]
Au contraire!

This is how it goes on Windows:

I have a file association set up as follows: `*.apk` - `adb install -r !.!`
Pressing `Enter` on `test.apk` yields `adb install -r test.apk`
Pressing `Shift+Enter` yields a Windows system dialog asking `How do you want to open this file?`

Similar "system" behavior can be achieved on OSX via `open !.!`

**Comment by elfmz** [comment]
check, it should be better now

**Comment by corporateshark** [comment]
Works for me.
