### ISSUE TITLE
Enabling "transparent" in files highlighting settings leads to a crash

### ISSUE THREAD

**Issue by dstd** [elfmz/far2l#324]
F9 → O → H → Enter → n → Enter → SIGSEGV
After a restart it keeps crashing right as the settings dialog opens

Stacktrace:
```
Thread 2 Crashed:
0   libsystem_c.dylib             	0x00007fff9f47bba2 wcslen + 8
1   libsystem_c.dylib             	0x00007fff9f46bd59 __vfwprintf + 4940
2   libsystem_c.dylib             	0x00007fff9f4720bd vswprintf_l + 613
3   far2l                         	0x00000001073b8b07 UnicodeString::Format(wchar_t const*, ...) + 231
4   far2l                         	0x00000001072ef7d2 MenuString(UnicodeString&, FileFilterParams*, bool, int, bool, wchar_t 
```

**Comment by elfmz** [comment]
Can you check if it still reproduces (releval commit that could affect this code is https://github.com/elfmz/far2l/commit/98465a82ad0b7b1caa191b688bc80cd88c5c8fe0 ) ?
If if its still crashes - will need to do some more tests, with code modifications to understand what goes wrong..

**Comment by dstd** [comment]
@elfmz yep, it's fine now. thanks
