### ISSUE TITLE
Arrow keystroke repeating doesn't work

### ISSUE THREAD

**Issue by am9obgo** [elfmz/far2l#325]
Can't get arrow keystroke repeat working neither in panel view nor editor view while other keys repeating works fine (letters, tab, space, backspace, and etc.). It's totally blocks navigation and editing. Also, have #292 after start.

Any idea?

Far Manager, version 2.1 (build 18/02/24-819d131-alpha) Linux x86_64, built from sources
Fedora release 27 (Twenty Seven) 4.15.4-300.fc27.x86_64

**Comment by singalen** [comment]
Seems to happen after installing a mac OS X system update, before a reboot.

I've debugged it down to this fact: keyboard.cpp:GetInputRecord() on a first keypress returns several consecutive codes: 0x00030001, 0x00010026, 0x00030001. On a second keypress it only returns one 0x00030001.

Don't have time to debug it further now.

**Comment by vvivanov9** [comment]
reboot help me. thank you

**Comment by elfmz** [comment]
reopen if for some one reboot wont help

**Comment by singalen** [comment]
I don’t think it’s the right thing to close the issue. It exists, and no other application has problems in this situation. 
Even if it’s, apparently, wxWidgets bug, it makes sense to track the issue here.

**Comment by unxed** [comment]
Same issue in WSLg: https://github.com/elfmz/far2l/issues/1659
(reason is the same also)

**Comment by atolismesh** [comment]
Now arrow keys autorepeat works on my system. Thanks!
(WSL2, W11, Ubuntu 23.04
GUI FAR2L, version 2.5.0-5e83a455-beta Linux x86_64)
