### ISSUE TITLE
Doesn't run on Bash on Ubuntu (WSL)

### ISSUE THREAD

**Issue by elig0n** [elfmz/far2l#326]
I've built far2l with cmake & make as written and then ran 'make install' but
when I run /usr/bin/far2l nothing happens as I'm returned to the shell prompt

**Comment by lieff** [comment]
It's GUI application, not console. GUI is not working under WSL. You can try build under msys2 though.

**Comment by elig0n** [comment]
OK I got it with Xming

**Comment by lieff** [comment]
@JustAMan It's almost useless (XMing GUI also not hardware accelerated), but there also at least one feature that I know only in linux version: Ctrl-O, F3/F4 - provides console log in viewer/editor.

**Comment by lieff** [comment]
@JustAMan That was not cancelled. But my primary objective is not ncurses-backed, but fast opengl back-end without wxwidgets. I've already implemented console using NVPR/nanovg https://github.com/lieff/lvg/tree/master/render , but integration things going slow. Also I noticed that NVPR is much faster and still investigate how to achieve relatively same speed without it. Glyph cache also can be used, but some Unicode fonts contains so many glyphs (https://github.com/adobe-fonts for example), that can consume too much GPU memory.

**Comment by elfmz** [comment]
essentially dup for #313

**Comment by unxed** [comment]
Btw, far2l console is ready, so some interesting combinations became possible:

> Out of curiosity - why run FAR on WSL if you can run FAR on Windows itself?..

To use far2l terminal extensions (all possible hotkeys and clipboard sync) then connecting to far2l on another device:
far2l(wx gui, wsl)->ssh->far2l(console, linux)

Putty does not support all that stuff.
