### ISSUE TITLE
Symlinks are changed when copied

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#330]
1. Create a local file, `echo "yo"> file.txt`
2. `ln -s file.txt link.txt`.  link.txt size is 8 bytes.
3. Copy link.txt to another directory, disabling all "Copy contents " options.

* Expected result: the copy is a broken symlink, 8 bytes size.
* Actual result: the copy is a symlink to `initiali directory/file.txt`, 88 or so bytes size.

I believe, it's the case where far2l is trying to be smart, and corrupts... er, edits my data without being asked and without indicating the fact. There is no way to turn this behavior off.

MacOS 10.13, far2l from the latest master.

**Comment by singalen** [comment]
This problem is still there, and I believe it's critical.
I expect "copy" operation to copy files as they are, not edit them in some unpredictable way.

**Comment by elfmz** [comment]
Yep, problem that original far's copy code is overcomplicated and in huge part outdated - it works over Windows-like symlinks emulation that not easy to directly translate into Linux
As for now i can recommend workaround: type-in in the command line 'file:' command - it will open current directly in Netrocks and later copying from it will use its downloader.

**Comment by singalen** [comment]
So, maybe... just drop the core copy routine and use NetRocks'? :)

**Comment by elfmz** [comment]
So, now if you will choose in copy dialog 'Always copy link'  it should work as you need (reopen if its not :) ). Also note that this option saveable by Shift+F9.
