### ISSUE TITLE
Icon on OSX

### ISSUE THREAD

**Issue by corporateshark** [elfmz/far2l#332]
The proper Far icon is not set on OSX. The standard 'exec' icon is displayed instead.

**Comment by singalen** [comment]
It's not even packaged into app, in the first place.
The plugin directories will need to be reconfigured, and what else.

BTW OSX is worth having its own tag in the issues.

**Comment by elmm** [comment]
Dmg with Far packed as app. Done in a quick and dirty way in 15 minutes for own convenience.
https://nofile.io/f/vaFGXO3gZRV/Far.dmg
Didn't test much. But icon works in my case :)

**Comment by singalen** [comment]
Crashed:
> Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
>   Referenced from: /Applications/Far2l.app/Contents/MacOS/far2l

Why on Earth would it need libpng? 8)
I will edit it with `install_name_tool`, ofc.

**Comment by singalen** [comment]
I wonder if it's possible to run multiple instances from the same shortcut on OS X, like browsers that have multiple windows

**Comment by asimonov** [comment]
I do not remember how I created a 'shortcut' but it creates multiple windows of far2l on mac.
it is in dock -- how can I look into the script behind this 'shortcut', any ideas?
and would love to have icon for this shortcut as at the moment I think it is action script default icon

**Comment by singalen** [comment]
Here's a script I use to make a portable package with a binary dependencies.

```
function package_deps() {
        BINARY=$1

        DEPS=$(otool -L $BINARY \
                | grep "/opt/local/lib" \
                | tr -s ' ' \
                | cut -d ' ' -f 1)

        for DEP in $DEPS; do
                cp $DEP Far2l.app/Contents/MacOS/
                BASE_DEP=$(basename $DEP)
                install_name_tool -change $DEP "@loader_path/$BASE_DEP" $BINARY
        done

        echo "Done with $BINARY:"
        otool -L $BINARY
}

cp -f far2l/cmake-build-debug/install/far2l Far2l.app/Contents/MacOS/
cp -rf far2l/cmake-build-debug/install/Plugins Far2l.app/Contents/MacOS/

package_deps Far2l.app/Contents/MacOS/far2l
for PLUG in Far2l.app/Contents/MacOS/Plugins/*/plug/*.far-plug*; do
        package_deps $PLUG
done
```

where system-dependent paths are:
* `/opt/local/lib` - MacPorts library directory (non-default OS X libraries Far is linked with)
* `far2l/cmake-build-debug` - build directory
* `Far2l.app` - where the output package is.

**Comment by asimonov** [comment]
tried to create an 'app' using both script editor and automator. It can start one instance of far. cannot change icon or open multiple instances. i give up. will be just starting it manually from command line.

**Comment by skazhikadyadya** [comment]
Any news?

**Comment by elfmz** [comment]
check how its now, after https://github.com/elfmz/far2l/pull/749

**Comment by asimonov** [comment]
it works! great job! thanks a lot!!
