### ISSUE TITLE
Linux: Pressing Alt-F1 or Alt-F2 freeze FAR for a while (couple of minutes)

### ISSUE THREAD

**Issue by fourier** [elfmz/far2l#339]
Every time I press Alt-f1 the FAR freezes for a long time, matter of minutes.
Build on Debian 9 64bit
Last commit: cd0b5e0884acbdf9c9c0ce457cc9858578956a0e

![window_2018-06-07-20-35-48](https://user-images.githubusercontent.com/900250/41119173-6b55f0ee-6a92-11e8-8772-6be9d275e1e9.png)

**Comment by elfmz** [comment]
does console command <df -T> work fast on that system?

**Comment by fourier** [comment]
Yes apparently it is because of the mounted networking file systems. So probably not a bug..
