### ISSUE TITLE
Green autocompletion pops up in the editor and marks the file dirty

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#342]
I see it quite often.
I see not way to switch it off.
Even if I cancel the autocompletion, the editor still considers the file changed and asks for saving.

![screenshot 2018-06-18 12 10 19](https://user-images.githubusercontent.com/151199/41556833-a9d642b8-72f0-11e8-8c0b-fa767578c6e8.png)

**Comment by volth** [comment]
to turn autocomplete off:
```
mkdir -p $HOME/.config/far2l/REG/HKU/c/k-Software/k-Far2/k-Plugins/k-editorcomp
echo -e 'Enabled\nDWORD\n0' > $HOME/.config/far2l/REG/HKU/c/k-Software/k-Far2/k-Plugins/k-editorcomp/v-Enabled
```

**Comment by singalen** [comment]
Thanks! Why didn't I think about it. Just deleted the plugin.

**Comment by Alter-1** [comment]
I've created patch for this issue. Undo (ECTL_UNDOREDO) should be used instead of suggested characters removal (ECTL_DELETECHAR)
[editorcomp-undo.patch.gz](https://github.com/elfmz/far2l/files/2989079/editorcomp-undo.patch.gz)
