### ISSUE TITLE
Command+V does not paste into command line on MAC

### ISSUE THREAD

**Issue by asimonov** [elfmz/far2l#343]
at the moment beta version of far2l on Mac (High Sierra) does not handle Command+V to insert from the buffer to the command line in far

**Comment by singalen** [comment]
For me, latest git version does. Do you still have the problem?

**Comment by singalen** [comment]
In the latest master, I even got it to paste when a program is running, with `Cmd-Shift-V`.

**Comment by asimonov** [comment]
actually, it does work! just checked.
