### ISSUE TITLE
проблема с открытием tar.gz архивов

### ISSUE THREAD

**Issue by j2969719** [elfmz/far2l#348]
при открытии [этого архива](https://github.com/elfmz/far2l/files/2172210/built_sdl.tar.gz) в файловой панели только мусор
![_2018-07-07_02-20-56](https://user-images.githubusercontent.com/30291994/42403795-6b7facd4-818c-11e8-8d7f-17056f119b8a.png)

**Comment by j2969719** [comment]
с этим багом не связано, но еще заметил что из архива ничего нельзя извлечь если в имени файла есть амперсанд

**Comment by elfmz** [comment]
пофикшено тута: https://github.com/elfmz/far2l/commit/4a4d41403215d70e7a0218d6bb219c0c224678d4

**Comment by j2969719** [comment]
спс, и еще похоже есть косяк с кириллицей внутри зипов
[tst.zip](https://github.com/elfmz/far2l/files/2199567/tst.zip)

**Comment by elfmz** [comment]
Это косяк unzip'а - не понимает что данный врхив в UTF8. Можно обойти добавив аргумент -O UTF8 в конфигурации везде где юзается unzip. С другой стороны, если попадется архив не в UTF8 то будут аналогичные проблемы.
