### ISSUE TITLE
Support /etc/paths and /etc/paths.d/ on Mac OS

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#359]
Currently, if I run far2l as a stand-alone app from /Applications (created with the code in #332), its `$PATH` is a bare system-default `/usr/bin:/bin:/usr/sbin:/sbin`, even though `/etc/paths` and `/etc/paths.d/` are set up perfectly.

Thus, child processes - like archivers installed by MacPorts into `/opt/local/bin` - cannot be found, even though `/opt/local/bin` is in `/etc/paths`.

[There is no method works to set an app's default path](https://apple.stackexchange.com/questions/106355/setting-the-system-wide-path-environment-variable-in-mavericks), as of now. Looks like far2l has to set its `PATH` by itself.

**Comment by elfmz** [comment]
fixed
