### ISSUE TITLE
[Mac] far2l, when copying a file locally, adds 1 hour to the file's time

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#362]
In US/Pacific (UTC-8) timezone.

**Comment by gitthangbaby** [comment]
This is a frustrating issue as timestamps are so important. As a consequence, sync system thought files are changed, and started syncing all plus it created another historical copy on server, which is almost impossible to delete, so i had to reset all versioning and lose all historical copies for all users. That's just one example how timestamps affect our lives.

Additionally, the zip plugin will simply change the file timestamps to current.
I'm testing adding to existing archive via F5 only, as ShiftF1 will crash far2l.

                                                     #0  0x00007fbd23fd8c2a __wcscpy_ssse3 (libc.so.6 + 0x157c2a)
                                                     #1  0x00007fbd1c4fea77 OpenFilePluginW (tmppanel.far-plug-wide + 0x6a77)
                                                     #2  0x000055e7c56f2292 n/a (far2l + 0x137292)

**Comment by gitthangbaby** [comment]
after DST change, now copying is timesynced, but all times shown are -1hr vs opinion of anything else (bash, local drives, network drives and server). The time for newly created files is ok so i can't fix it by "TZ=another/zone far2l". The new files copied by far2l will retain their correct timestamps although shown incorrectly in far2l, which is good. So i'm entering a happy period for half of year without timestamp corruption and hope EU pass law to abolish DST until next clock change.

**Comment by singalen** [comment]
You found it! Amazing!

**Comment by gitthangbaby** [comment]
i've noticed that there's zero tolerance to timestamp difference. It's sadly quite usual filesystems can differ in some milliseconds, and also by a timezone difference vs UTC or DST. 
i'm getting GBs worth of differences in far2l copy/compare, but not in mc. Neither in Advanced Compare plugin.
but i need to copy a hierarchy of files, preferring the copy dialog to handle these miniature timestamp differences.
