### ISSUE TITLE
Плагин FTP  не конектится к серверам

### ISSUE THREAD

**Issue by chodorenko** [elfmz/far2l#37]
Не знаю с чем точно связано , но заметил что плагин FTP  не коннектится к серверам  и сваливается на ошибке что не может законектится http://screencloud.net/v/m9n7
PS  есть предположение что это из за IPv6  которые есть на моей машине, но сайт который я открываю IPv4

**Comment by elfmz** [comment]
связано было с тем что семантика SO_DONTROUTE на линуксе и винде разная

**Comment by chodorenko** [comment]
Подтверждаю заработало
