### ISSUE TITLE
Плагин темпорари русский язык

### ISSUE THREAD

**Issue by chodorenko** [elfmz/far2l#38]
Наверное стоит предусмотреть при компиляции перевод всех ресурсов всех плагинов на UTF  или например реализовать работу с плагинами так чтобы использовать не изменённые ресурсы а переконверчивать их налету

**Comment by elfmz** [comment]
Если честно, не очень понял  о чем речь)
Языковые файлы плагинов нынче и так UTF, ну а то что у tmppanel на русском языке кракозяблы вылезли - сие есть баг, вечером пофикшу.

**Comment by chodorenko** [comment]
Я так понимаю фиксить будете путём конвертации ресурсов на UTF8  , наверное стоит предусмотреть такую ситуацию в коде или скриптах билда , не известно какой плагин будет сувать пользователь

**Comment by elfmz** [comment]
Фиксить буду путем добавления UTF8 BOM'а в начало TmpRus.lng/.hlf
Повторяю - оно уже и так в UTF8. Просто без BOMа плагин об этом не знает.

**Comment by elfmz** [comment]
упс, не ту кнопочку нажал..

**Comment by elfmz** [comment]
пофикшено?
