### ISSUE TITLE
Нет правила цели bootstrap/farlng требуемой CMakeFiles/bootstrap

### ISSUE THREAD

**Issue by Novator** [elfmz/far2l#384]
Не конпилируется:

```
user@comp:/mnt/data/far2l/build$ cmake -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is GNU 6.2.0
-- The CXX compiler identification is GNU 6.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- generating headers and languages
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/data/far2l/build

user@comp:/mnt/data/far2l/build$ make -j4
Scanning dependencies of target bootstrap
make[2]: *** Нет правила для сборки цели `../bootstrap/farlng', требуемой для `bootstrap/CMakeFiles/bootstrap'.  Останов.
make[1]: *** [bootstrap/CMakeFiles/bootstrap.dir/all] Ошибка 2
make: *** [all] Ошибка 2
```

**Comment by elfmz** [comment]
У мня все работает (с). Вот этот кусок лога от тестового билда на свежесклоненных исходниках:

> Scanning dependencies of target bootstrap
> [ 78%] template
> [ 78%] header
> [ 78%] header
> eng
> rus
> hun
> languages
> FAR language umbrella tool
> .LNG Generator v1.5
> Copyright (C) 2003-2009 WARP ItSelf
> Copyright (C) 2005 WARP ItSelf & Alex Yaroslavsky
> 
> lpLNGOutputPath=/home/user/projects/zzz/far2l/build/far2l/bootstrap
> INFO: There are 14 strings that require review in Russian translation!
> 
> INFO: There are 20 strings that require review in English translation!
> 
> INFO: There are 246 strings that require review in Czech translation!
> 
> INFO: There are 248 strings that require review in German translation!
> 
> INFO: There are 199 strings that require review in Hungarian translation!
> 
> INFO: There are 229 strings that require review in Polish translation!
> 
> INFO: There are 83 strings that require review in Spanish translation!
> 
> Failed to remove file: './lngb9a6.tmp' errno 2
> Failed to remove file: './lngb9a7.tmp' errno 2
> Failed to remove file: './lngb9a8.tmp' errno 2
> Failed to remove file: './lngb9a9.tmp' errno 2
> Failed to remove file: './lngb9aa.tmp' errno 2
> Failed to remove file: './lngb9ab.tmp' errno 2
> Failed to remove file: './lngb9ac.tmp' errno 2
> Failed to remove file: './lngb9a5.tmp' errno 2
> [ 78%] Built target bootstrap
>

**Comment by elfmz** [comment]
может каких файлов не хватает по какойто причине? что говорит git status?

**Comment by BekzhanKassenov** [comment]
#272 я описывал решение похожей ошибки. tl;dr: после git clone не надо переходить в папку far2l.

@elfmz Думаю стоит добавить это в инструкции по сборке, люди натыкаются на это не впервые (например #242)

**Comment by Novator** [comment]
Не стал делать папку "build", начало конпиляться, но дошло только до 27%:

```
[ 28%] Building CXX object FARStdlib/CMakeFiles/FARStdlib.dir/src/fstd_FMsg.cpp.o
[ 28%] Building CXX object FARStdlib/CMakeFiles/FARStdlib.dir/src/fstd_exSPS.cpp.o
[ 29%] Building CXX object FARStdlib/CMakeFiles/FARStdlib.dir/src/fstd_FUtils.cpp.o
[ 29%] Building CXX object FARStdlib/CMakeFiles/FARStdlib.dir/src/fstd_ClpS.cpp.o
Linking CXX static library libFARStdlib.a
[ 29%] Built target FARStdlib
make: *** [all] Ошибка 2
```

**Comment by elfmz** [comment]
Ну так ее _нужно_ делать. Если собирать прямо в дереве исходников то оно (дерево исходников) сломается.
Теперь стирайте это дерево и делайте заново:

> git clone https://github.com/elfmz/far2l.git
> cd far2l
> mkdir build
> cd build
> cmake -DCMAKE_BUILD_TYPE=Release ..
> make -j 8
>

**Comment by Novator** [comment]
Удалил. Скачал снова с гита. Компилирую как вы сказали, но ушел ненамного дальше:
```
[ 29%] Building CXX object FARStdlib/CMakeFiles/FARStdlib.dir/src/fstd_FMsg.cpp.o
[ 29%] Building CXX object FARStdlib/CMakeFiles/FARStdlib.dir/src/fstd_exSPS.cpp.o
[ 30%] Building CXX object FARStdlib/CMakeFiles/FARStdlib.dir/src/fstd_FUtils.cpp.o
[ 30%] Building CXX object FARStdlib/CMakeFiles/FARStdlib.dir/src/fstd_ClpS.cpp.o
Linking CXX static library libFARStdlib.a
[ 30%] Built target FARStdlib
make: *** [all] Ошибка 2
```

**Comment by BekzhanKassenov** [comment]
Попробуйте это:
`
git clone https://github.com/elfmz/far2l.git
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ../far2l
make -j 8
`

**Comment by elfmz** [comment]
Не тоже самое, в последнем варианте билд происходит в "соседнем" каталоге. По идее пофиг, в соседнем, или в дочернем., но попробовать стоит конечно.
Вообще какието очень странные у вас ошибки билда. Там в dmesg случайно ошибок ввода вывода не видать? Может фс поломата?
Что за система то?

**Comment by Novator** [comment]
Система Lubuntu 12.04 (i386).

Конпилять новые библиотеки на старых системах - это всегда проблема. Не понимаю, почему бы не выложить tar.gz-бинарники в раздел "Релиз"? Зачем нужно заставлять ВСЕХ пользователей конпилировать, тем более тех, кто не имеет такой возможности?

**Comment by mdef** [comment]
> Lubuntu 12.04
End of Life on April 28, 2017
кто-же для вас будет делать релиз.... обновляйтесь

**Comment by unxed** [comment]
> Система Lubuntu 12.04 (i386).
> 
> Конпилять новые библиотеки на старых системах - это всегда проблема. Не понимаю, почему бы не выложить tar.gz-бинарники в раздел "Релиз"? Зачем нужно заставлять ВСЕХ пользователей конпилировать, тем более тех, кто не имеет такой возможности?

Потому что бинарники, собранные на совеременной системе, не запустятся на системе со старой версией libc, например. А собрать на старой разработчику так же сложно, как и вам - он это время на новые фичи скорее потратит.

btw, этот тикет ещё актуален вообще? есть ppa давно, там лежат бинарники для довольно старых убунт, начиная вот прям c 16.04 https://launchpad.net/~far2l-team/+archive/ubuntu/ppa

**Comment by elfmz** [comment]
reopen if still reproduces
