### ISSUE TITLE
в редакторе не работают Alt-стрелки 

### ISSUE THREAD

**Issue by volth** [elfmz/far2l#40]
В редакторе не работают Alt-стрелки и Alt-Home, Alt-End, Alt-PageDown, Alt-PageUp
В Far для Windows они выделяют вертикальный блок.

**Comment by lieff** [comment]
Здесь надо ctrl-alt зажать чтобы вертикальный блок выделить. В винде на 3м фаре работают обе комбинации.

**Comment by volth** [comment]
хм, у меня вот так сейчас:

**ctrl-alt-left**, **ctrl-alt-right** - работают как ctrl-shift-left/right, т.е. выделяют до границы слова
**ctrl-alt-up**, **ctrl-alt-down** - не работают вовсе
**ctrl-alt-pagedn**, **ctrl-alt-pageup** - работают как просто pagedn/pageup
**ctrl-alt-home**, **ctrl-alt-end** - переводят курсор на первую/последнюю строку сохраняя его позицию в строке (X-координату)
**alt-left**, **alt-right**, **alt-up**, **alt-down**, **alt-pageup**, **alt-pagedown**, **alt-home**, **alt-end** - не работают вовсе

**Comment by lieff** [comment]
Да это что-то странное. А что за дистр и какая версия wxWidgets?

**Comment by volth** [comment]
Linux Mint 18 XFCE, wxWigets 3.0.2

**Comment by elfmz** [comment]
может комбинации кемто заняты? Вместо альта можно попробовать Win (правый/левый)

**Comment by volth** [comment]
конфликтующие комбинации я отключил вовсе.
судя по логу Far'а он эти события клавиатуры получает.

**Comment by elfmz** [comment]
у меня работает shift+alt
но это не здоровое явление, в оригинале работает просто с alt

**Comment by elfmz** [comment]
проверяйте...

**Comment by volth** [comment]
работает, супер!

**Comment by lieff** [comment]
У меня тоже и просто alt-стрелки заработал.

**Comment by volth** [comment]
ой, а **alt-home, alt-end, alt-pagedown** и **alt-pageup** ещё остались незафикшеными

**Comment by lieff** [comment]
А у меня работают.

**Comment by elfmz** [comment]
добавил и эти
