### ISSUE TITLE
несовместимость с fish

### ISSUE THREAD

**Issue by volth** [elfmz/far2l#41]
Если у юзера дефолтный шел не bash а fish, то Far не может запустить программы.
При нажатии enter на архиве,  не может запустить unzip для получения списка файлов.
![screenshot_2016-09-07_15-25-36](https://cloud.githubusercontent.com/assets/508305/18318193/3be0d762-7510-11e6-89f1-77fe9be24f76.png)

**Comment by lieff** [comment]
Ему не нравится -ci но нравится -ic типа после -с уже обязательно команда должна быть.

**Comment by volth** [comment]
работает.
спасибо!
