### ISSUE TITLE
Какова смысловая нагрузка этой строки?

### ISSUE THREAD

**Issue by svost** [elfmz/far2l#413]
Учитывая, что объявлено так WIN32_FIND_DATA ffi; и далее по коду нигде не меняется  до этого участка? Заодно присутствует чехарда с  uint int64 и %I64u https://github.com/elfmz/far2l/blob/444bbd93cf54b0f256f779cee626341dbd76e859/farftp/src/cnUpload.cpp#L98

**Comment by lieff** [comment]
Да это явно какой-то артефакт, опция SendAllo сломала. Там по идее должно быть fsz, который считается выше.

**Comment by svost** [comment]
А если посмотреть так https://github.com/FarGroup/FarManager/blob/master/plugins/ftp/cnUpload.cpp#L46 то похоже нужно просто v выкинуть и писать s.st_size?

**Comment by lieff** [comment]
Да, и `fsz = Fsize(fin.Handle);` можно заменить на `fsz = s.st_size;`, чтобы 2 раза stat не делать.

**Comment by svost** [comment]
https://github.com/elfmz/far2l/pull/415/commits/213fd45eaa9a9036441b3fa77c857d5840ecd99e

**Comment by lieff** [comment]
Вместо %lld еще лучше использовать PRId64 из inttypes.h

**Comment by svost** [comment]
https://github.com/elfmz/far2l/pull/415/commits/5fa1cf61899214f0a5e6f7e725322f55127797c8

**Comment by lieff** [comment]
Только "" в конце вроде как не нужен.

**Comment by svost** [comment]
По мне так без "" конец строки теряется Log(("ALLO %" PRId64, fsz)); - на первый взгляд как 2 переменных в таком виде. Но тут уже наверное кому как удобнее.

**Comment by lieff** [comment]
Тогда нужен пробел :) встречал компиляторы, которые варнинг кидают когда его нет.

**Comment by svost** [comment]
https://github.com/elfmz/far2l/pull/415/commits/d455fd28de485a350f98297ecf4ec3ec7f68ff19

**Comment by lieff** [comment]
Не, между макросом и строкой: `"%s %" PRId64 ""`

**Comment by lieff** [comment]
Во, нашел какой варнинг:
```
warning: invalid suffix on literal; C++11 requires a space between literal and string macro
```

**Comment by svost** [comment]
Так он же был изначально) даже в предидущем варианте, опять перезалить?

**Comment by lieff** [comment]
Значит я проглючил, мне показалось был пробел перед, но небыло после :)

**Comment by svost** [comment]
https://github.com/elfmz/far2l/pull/415/commits/de7d47608425149a308249ffb4dcf0827fd4ea97
Надеюсь заливал в последний раз ) Я читал там https://en.cppreference.com/w/cpp/types/integer требуется по ходу только префиксный пробел.

**Comment by lieff** [comment]
Вроде норм :) Я потому и говорю - встречал компиляторы, по стандарту только префиксный нужен. Это баг компилятора очевидно был, не уверен что это еще актуально.

**Comment by svost** [comment]
Fixed in https://github.com/elfmz/far2l/commit/de7d47608425149a308249ffb4dcf0827fd4ea97
