### ISSUE TITLE
Just black screen on macOS

### ISSUE THREAD

**Issue by yurikoles** [elfmz/far2l#416]
![10 53 29](https://user-images.githubusercontent.com/922873/47987798-235b7c00-e0e9-11e8-8c8d-6889e6c92bed.png)
I have Installed the latest master from my tap. Honestly it never worked for me on macOS. I have wxWidgets that you recommend installing on Linux: `wxmac: stable 3.0.4`

**Comment by singalen** [comment]
Shouldn't it be wxWidgets 3.1?

**Comment by yurikoles** [comment]
```apt-get install gawk m4 libglib2.0-dev libwxgtk3.0-dev cmake g++ git```

**Comment by singalen** [comment]
I don't know what you mean by Linux installation command, but IIRC on Mac wx 3.1 is a requirement. That's what I have and what works for me.

**Comment by yurikoles** [comment]
The only that is changed after rebuild with wxmac-3.1.1 is that font dialog appeared at first launch.

**Comment by elfmz** [comment]
it looks like you ran far2l binary without .lng files in proper place

**Comment by yurikoles** [comment]
Homebrew has deprecated `devel` versions. My [PR](https://github.com/Homebrew/homebrew-core/pull/33854) was rejected. I will test `far2l` with `wxmac` head and send a PR with updated instructions for mac. By God's will.

**Comment by yurikoles** [comment]
There is a strange thing: even black window is shown until I use full real path to binary. Same for manual install and brew one.

**Comment by yurikoles** [comment]
It seems to work with stable `wxmac`, I had sent a [PR](https://github.com/Homebrew/homebrew-core/pull/33889) to homebrew. Please put some likes to it, so it may be reviewed sooner :)

**Comment by yurikoles** [comment]
Oh, it was rejected due to alpha in version name :(

**Comment by volth** [comment]
The same problem with the version from nixpkgs/Darwin, I'll have a look

**Comment by yurikoles** [comment]
Just create a shell script in bin folder that will launch far2l using full real path.
