### ISSUE TITLE
Multiarc: the default tar extract command should support both leading ./ and empty leading path

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#417]
This is actually a tar "feature". 

tar archive containing `file.txt` and one containing `./file.txt` [are two different things](https://serverfault.com/questions/457480/tar-leading-period-slash).

I tried to compose a `tar` command for multiarc that handles both cases, and apparently it's impossible in tar, or in pax, or where else. `--transform` doesn't apply to unpacking.

We need pass the original file name in the archive as reported by archiver, including the possible `./` prefix, in order to be able to extract it.

**Comment by singalen** [comment]
Disregard this, this is actually a tar and archive variant. tar archive containing `file.txt` and one containing `./file.txt` are two different things.

I need to compose a `tar` command for multiarc that handles both.

**Comment by singalen** [comment]
[Other people have this problem with GNU tar too. Not with BSD tar](https://serverfault.com/questions/803831/tar-extract-a-member-reliably-with-possible-leading-dot-slash).

**Comment by unxed** [comment]
> This is actually a tar "feature".
> 
> tar archive containing `file.txt` and one containing `./file.txt` [are two different things](https://serverfault.com/questions/457480/tar-leading-period-slash).
> 
> I tried to compose a `tar` command for multiarc that handles both cases, and apparently it's impossible in tar, or in pax, or where else. `--transform` doesn't apply to unpacking.
> 
> We need pass the original file name in the archive as reported by archiver, including the possible `./` prefix, in order to be able to extract it.

is it still a problem after switching to libarchive for tar processing? bsd tar is libarchive-based also

**Comment by elfmz** [comment]
should be fixed now if built with libarchive, reopen if still repro
