### ISSUE TITLE
[nice to have] Set up Multiarc to enter .tar.*z archives by default as non-nested one

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#420]
Because whoever needs to read raw `.tar` archive inside of `.gz`/`.bz2`/`xz`, can change Multiarc command lines setup back.

**Comment by unxed** [comment]
+ option to create .tar.gz archive in one action

**Comment by unxed** [comment]
> Because whoever needs to read raw `.tar` archive inside of `.gz`/`.bz2`/`xz`, can change Multiarc command lines setup back.

after switching to libarchive for .tar.gz processing, everything works just this way

can we close this now?
