### ISSUE TITLE
Impossible to browse two archives at the same time, nested or simultaneously on 2 panels

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#422]
I opened two `.tar.gz` archives on two panels and browse them in turns.

Once I change directory in second archive and try to change directory in first one, I'm thrown back outside of `.tar` to insides of `.gz`.

No errors happen during unpacking.

**Comment by singalen** [comment]
Reproduces on `.tar.gz` archives.

**Comment by singalen** [comment]
Another occurrence of the same problem: it's impossible to enter `.tar.gz` archive that is inside a `.zip` archive. I get the message:

```gzip: can't stat: /tmp/far2l_179c1115_0/open/7177_7/gmd-1.0.3.tar.gz (/tmp/far2l_179c1115_0/open/7177_7/gmd-1.0.3.tar.gz.gz): No such file or directory ```

**Comment by unxed** [comment]
Both issues seems to be solved now, please check.

**Comment by singalen** [comment]
They are, thanks.
