### ISSUE TITLE
Ошибка: CMAKE_INSTALL_PREFIX и добавление far2l в desktop

### ISSUE THREAD

**Issue by cycleg** [elfmz/far2l#429]
Установка переменной CMAKE_INSTALL_PREFIX в [строках 9-11 проекта cmake](https://github.com/elfmz/far2l/blob/c1b012849cb129bbc5dce1260edb7e364e5a3aa2/CMakeLists.txt#L9) никогда не сработает, потому что эта переменная задается автоматически в ходе исполнения команды project() (cmake 3.12) и по умолчанию равна "/usr/local". Таким образом, по умолчанию far ставится в "/usr/local", а в [файле "far2l.desktop"](https://github.com/elfmz/far2l/blob/master/far2l/DE/far2l.desktop) пути жестко прописаны с "/usr". Интеграции не получается. По сути, 2 ошибки сразу:
1. Неработающее условие в проекте.
2. Несогласованные пути в "far2l.desktop".

**Comment by elfmz** [comment]
Ну вощемто с некоторых пол README.md в описании билда советует задавать cmake-у в командлайне аргумент -DCMAKE_INSTALL_PREFIX=/usr
Но far2l.desktop конечно же надо както динамически генерировать, чтоб он актуальный путь использовал
