### ISSUE TITLE
Far упал при выполнении внешней программы

### ISSUE THREAD

**Issue by volth** [elfmz/far2l#43]
Far упал при выполнении внешней программы (sudo apt install чтототам):

VTAnsi: SET SCOPE: 4294967295 33 (limits 0 34)
ConsoleOutput::ScrollOutputOnOverflow: bug
*** Error in `/home/user/far2l/Build/far2l': double free or corruption (!prev): 0x00007fee84008530 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x77725)[0x7fee9a7fe725]
/lib/x86_64-linux-gnu/libc.so.6(+0x7ff4a)[0x7fee9a806f4a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fee9a80aabc]
/home/user/far2l/Build/far2l[0x576bb5]
/home/user/far2l/Build/far2l[0x5770e4]
/home/user/far2l/Build/far2l[0x577152]
/home/user/far2l/Build/far2l(WINPORT_WriteConsole+0x10)[0x5794c0]
/home/user/far2l/Build/far2l[0x5532e5]
/home/user/far2l/Build/far2l[0x55497d]
/home/user/far2l/Build/far2l[0x5550a8]
/home/user/far2l/Build/far2l[0x552e16]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76fa)[0x7fee9ab576fa]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7fee9a88db5d]

-----------
и ещё раз, но чуть по другому:

VTAnsi: SET SCOPE: 4294967295 33 (limits 0 34)
ConsoleOutput::ScrollOutputOnOverflow: bug
*** Error in `/home/user/far2l/Build/far2l': free(): invalid next size (normal): 0x00007f757000d5f0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x77725)[0x7f75857d2725]
/lib/x86_64-linux-gnu/libc.so.6(+0x7ff4a)[0x7f75857daf4a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f75857deabc]
/home/user/far2l/Build/far2l[0x576bb5]
/home/user/far2l/Build/far2l[0x5770e4]
/home/user/far2l/Build/far2l[0x577152]
/home/user/far2l/Build/far2l(WINPORT_WriteConsole+0x10)[0x5794c0]
/home/user/far2l/Build/far2l[0x5532e5]
/home/user/far2l/Build/far2l[0x55497d]
/home/user/far2l/Build/far2l[0x5550a8]
/home/user/far2l/Build/far2l[0x552e16]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76fa)[0x7f7585b2b6fa]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f7585861b5d]

**Comment by elfmz** [comment]
проверьте пофикшено ли? (хотя в целом тут еще не все гладко)

**Comment by volth** [comment]
на тех командах не упал.
