### ISSUE TITLE
Consider renaming main executable to just "far", not "far2l"

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#443]
Two unneeded keystrokes for every run of frequently used tool, with no practical sense.
Version number and linux postfix can both stay in installation folder name, btw.

far is not a programming language compiler/interpreter or something like it, there version in executable name is needed to avoid confusion. Probably, no one will ever need multiple versions of far on linux with executable names like "far1l", "far3w" etc.

mc is not "mc4l" also: mc's authors know how to save user's keystorkes :)

**Comment by elfmz** [comment]
First i'm not sure that license permits it. Actually i thought to change FAR Manager everywgere in help to far2l, but didnt do that mostly due to lazyness :)
Also if some day 'upstream\s authors will decide to create 'official' fork then this will cause some mess.

**Comment by unxed** [comment]
Why not to address license question to upstream community directly?

> 'official' port

Just after Sun becomes a red giant :)

**Comment by elfmz** [comment]
pretty sure the'll answer 'no')

**Comment by JustAMan** [comment]
Then you can make a pun and rename to "near" :-)

**Comment by unxed** [comment]
using just "f" instead :-p
