### ISSUE TITLE
far2l --tty works incorrectly under "screen" tool 

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#445]
Steps to reproduce:
1. sudo apt install screen
2. screen bash
3. far2l --tty
4. Try to browse panels.

PS: Another issue with far2l and screen is long initial startup time.

**Comment by elfmz** [comment]
Delay caused by fact that screen doesnt reply on terminal status request command that far2l uses to detect if terminal is far2l, --nodetect arg workaround  startup time, as well as hit <Enter> instead of waiting. 
About browsing panels under screen  - i dont see any issues with that on 1st look..

**Comment by unxed** [comment]
Re-checked. Steps to reproduce:

1. Run far2l wx
2. Run "screen bash" inside
3. Run "far2l --tty" inside
4. Browse panels

Not reproduced in other terminals.
![_008](https://user-images.githubusercontent.com/1151423/49692879-a2732280-fb75-11e8-8017-99af38a7c49e.jpg)

**Comment by svost** [comment]
Confirmed. Reproduced on home pc.

**Comment by unxed** [comment]
Still long start time inside gnome-terminal and visual glitches inside far2l-wx VT.

**Comment by elfmz** [comment]
commit 386b542 (see title on your screenshot) is earlier than 0d85c6c (that fixes delay) and 38c620a (that fixes this bug)

**Comment by unxed** [comment]
ups, sorry!
