### ISSUE TITLE
mc draws border lines and processes at least shift+f4 correctly in ctrl+alt+f1 terminal, but far2l does not

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#460]
It was the same terminal on the same system, of course. Ubuntu Desktop 18.04 amd64.

```
$ locale
LANG=ru_RU.UTF-8
LANGUAGE=ru_RU
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC=ru_RU.UTF-8
LC_TIME=ru_RU.UTF-8
LC_COLLATE="ru_RU.UTF-8"
LC_MONETARY=ru_RU.UTF-8
LC_MESSAGES="ru_RU.UTF-8"
LC_PAPER=ru_RU.UTF-8
LC_NAME=ru_RU.UTF-8
LC_ADDRESS=ru_RU.UTF-8
LC_TELEPHONE=ru_RU.UTF-8
LC_MEASUREMENT=ru_RU.UTF-8
LC_IDENTIFICATION=ru_RU.UTF-8
LC_ALL=

```

**Comment by elfmz** [comment]
Shift F1/F8 fixed. About borders: MC draws single line borders, while far2l draws some borders as double-line characters. And that characters seems missing in fonts, used in system console. Single line borders in far2l looks fine however.

**Comment by elfmz** [comment]
Its possible to check that far2l runs under linux terminal by checking that $TERM == "linux", but not sure its correct. May be someday linux system fonts will have doubleline character but far2l will not have benefit of that great new feature)

**Comment by unxed** [comment]
Workaround: `far2l /ag`

**Comment by unxed** [comment]
fixed long time ago
