### ISSUE TITLE
far2l_tty as clipboard sync host, possible?

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#462]
...for things like ctrl+alt+f1->far2l_tty->ssh->far2l_tty, for example.

**Comment by elfmz** [comment]
Not sure i understood question, but under such configuration it should use on-host far2l's own clipboard.

**Comment by unxed** [comment]
It actually does, thanks, closing.

Btw, there are still some issues with linux terminal and clipboard usage, see #466.
