### ISSUE TITLE
copy-paste issues in linux terminal

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#466]
Shift+Arrows do nothing, but, suddenly, ...
Ctrl+C copies entire current line (in editor) to clipboard!

Ctrl+V seems to work as expected
Shift+Ins does nothing
Ctrl+Ins does nothing

**Comment by elfmz** [comment]
copying whole line by Ctrl+C if no selection set is a native feature of FAR

**Comment by unxed** [comment]
Ctrl+C/V/Z/X sometimes work, sometimes not, sometimes show "define macro" box. 

Shift+Ins works
Ctrl+Ins works
Shift+Del works
Ctrl+Arrows work
Shift+Arrows work
LeftShift+RightCtrl+Arrows work

LeftShift+LeftCtrl+Arrows still does not

Big step forward, btw! :+1:

**Comment by unxed** [comment]
Shift+PgUp/Dn does not works also. Btw, overall impression is "almost usable". Great job, @elfmz! :)

**Comment by elfmz** [comment]
ctrl+shift+arrows work for me, about shift+pgup/down - there is nothing comes from input on these combination, but however it seems it handled terminal itself (does some strange changed on screen)

**Comment by unxed** [comment]
Checked on laptop keyboard. Can this affect the result?

Btw, Ctrl+C/V/Z/X bug seem to be keyboard layout dependent: hotkeys fail to work only with russian keyboard layout activated.

**Comment by unxed** [comment]
already fixed
