### ISSUE TITLE
far2l does not reset linux terminal on exit

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#467]
1. Switch to linux terminal
2. Run far2l
3. Exit far2l
4. Try to type.

"reset<enter>" fixes that

**Comment by Subarna578** [comment]
How to run Far2l after making and building from linux?
What is the command code to run Far2l? Help...

**Comment by unxed** [comment]
> How to run Far2l after making and building from linux?
> What is the command code to run Far2l? Help...

After `make install` just `far2l` should be enough.
