### ISSUE TITLE
alt+f9 works incorrectly

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#47]
as for now, alt+f9 just minimizes the window.
maybe it should maximize the window (leaving taskbar on a screen, unlike alt+enter) instead ?

**Comment by invy** [comment]
Is it possible, that your DE/WM intercepts al+f9 before Far gets it?
What results Right Win + F9 key combination produces?
What is your distro and DE?
Could you provide the log output at the moment when problem occurs?

**Comment by elfmz** [comment]
Looks like you have Alt+F9 [used by Gnome](https://habrahabr.ru/post/23523/). FAR cannot overrride system shortcuts. However, you may rey Win+F9

**Comment by unxed** [comment]
disabled alt+f9 in mate keyboard shourtcuts settings.
now alt+f9 works, but far's window jumps to monitor number two on this action.
I guess it can not be considered an expected behaviour.

**Comment by elfmz** [comment]
no, I dont have two monitors. however, going to another monitor by hotkey looks like a feature:)

**Comment by elfmz** [comment]
alt-f9 logic was completely changed in https://github.com/elfmz/far2l/commit/f6d062ea94e89db6105f99105dc29553f6c1e511 so there is high chance that issue was fixed. Reopen if it didnt'
