### ISSUE TITLE
USEWX variable in cmake

### ISSUE THREAD

**Issue by invy** [elfmz/far2l#470]
If(${USEWX} MATCHES "no")

Is incorrect syntax. Please just write 

if(${USEWX})

Cmake will evaluate this to true if USEWX is true or on.

PS sorry don't have time to fix myself. :(

**Comment by cycleg** [comment]
Даже разыменовывать не надо, ```if(USEWX)``` достаточно.

**Comment by invy** [comment]
Yep. Agreed.
