### ISSUE TITLE
поиск файлов (Alt-F7) может заблудиться в каталогах с циклическими симлинками

### ISSUE THREAD

**Issue by volth** [elfmz/far2l#48]
если поискать файлы в /usr, поиск будет идти в /usr/bin потом /usr/bin/X11,  /usr/bin/X11/X11,  /usr/bin/X11/X11/X11, ....

**Comment by elfmz** [comment]
это потому что ConvertNameToReal ничего не делает, а должна readlink'ом возвращать реальный путь.. вечером вкомичу фикс

**Comment by invy** [comment]
Better: try doing most of the things with boost::filesystem

**Comment by lieff** [comment]
А вот на буст я бы не завязывался, его кроссплатформенность конечно удобна, но пара сотых версий и сорсы уже несовместимы, это практически гарантированно вызовет проблемы сборки на разных дистрах. Также труднее будет собрать универсальную бинать что запускается везде, это надо будет собирать статические либы самостоятельно.

**Comment by invy** [comment]
Как минимум принятое в c++17 надо начинать использовать.

**Comment by lieff** [comment]
Вот это да, может не 17 но 11 наверно уже в большинстве дистров есть. А по бусту у меня уже целая коллекция boost_1_41_0 boost_1_47_0 boost_1_52_0 boost_1_57_0, чтобы разные проекты компилять, и все несовместимы... Иногда еще долго править сорсы приходится.

**Comment by elfmz** [comment]
Да я блин от std::codecvt отказался только потому что на билдботе gcc 4.8, приземленнее надо быть.
Бустом переболел лет 7 назад, хотя надо признать boost::filesystem::canonical тут выглядит логичным, до тех пор пока вдруг не обнаружится к примеру что нужно будет еще обрабатывать пути, обслуживаемые плагинами.

**Comment by invy** [comment]
В чем сакральный смысл в 2016м году использовать устаревшие компиляторы? Это путь вникуда.

**Comment by lieff** [comment]
gcc 4.8 не такой уж и старый. Смысл наверно чтобы большинство под большинством дистрибутивов смогли скомпилять. Ну и хорошо бы сделать бинарь которая запустится почти везде, тут даже libstdc++ лучше статический юзать, благо в последних дистрах его включают как опцию и можно с ним собрать. Ну или можно просто appimage\flatpack\snap сделатью.

**Comment by invy** [comment]
GCC 4.8.0	March 22, 2013

3 года - старте. В нем c++11 не полностью реализован был, а на дворе уже c++14 давно и c++17 не за горами. 3 года, к сведенью это по сути 2 LTS релиза убунты. (Вышел аж при 12.04), потому считаю его старьем. Можно ориентироваться на Debian stable как эталон минимально поддерживаемых версий GCC, там сейчас 4.9.2 вроде как.

**Comment by lieff** [comment]
Ну поскольку тут автосборка юзается, скорее на Travis CI надо ориентироваться. Если пошаманить gcc5 вроде как можно задействовать http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci/
c++17 пока за бортом.
Еще не стоит забывать что у большого кол ва юзеров может оказаться что-то другое, где тоже обновления не такое простое дело. На ум приходит JOLLA и Ubuntu Phone, платы типа Raspberry Pi, как там дела?
Лично мне конечно это не так важно, у меня свежие компиляторы есть, но думаю вопрос все же более сложный и 3года тут срок не очень большой.

**Comment by elfmz** [comment]
`pi@balkon:~ $ uname -a
Linux balkon 4.4.6-v7+ #874 SMP Mon Apr 11 19:20:24 BST 2016 armv7l GNU/Linux
pi@balkon:~ $ gcc --version
gcc (Raspbian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`
