### ISSUE TITLE
Multiarc: filenames with dollar sign in archives

### ISSUE THREAD

**Issue by helgp** [elfmz/far2l#482]
Attempt to view/extract files with dollar sign in a name fails with the message at the console

_$ unzip -j -o  /home/user/FNameWithDollar.zip "Main$Sub.class"
caution: filename not matched:  Main.class_ 

Use single quotes instead of double?

[FNameWithDollar.zip](https://github.com/elfmz/far2l/files/2747316/FNameWithDollar.zip)

**Comment by denis-adamchuk** [comment]
Just noticed your issue. There is a similar one here -- https://github.com/elfmz/far2l/issues/495

**Comment by unxed** [comment]
> Attempt to view/extract files with dollar sign in a name fails with the message at the console
> 
> _$ unzip -j -o /home/user/FNameWithDollar.zip "Main$Sub.class" caution: filename not matched: Main.class_
> 
> Use single quotes instead of double?
> 
> [FNameWithDollar.zip](https://github.com/elfmz/far2l/files/2747316/FNameWithDollar.zip)

looks to be solved now, please check

**Comment by helgp** [comment]
It works smooth now. Thank you!

I have compiled and tested the code on Pi 4 (armv7), under the latest Raspberry PI OS 32bit v.5.4.51-v7l+ using the provided build instructions for Debian. No issues so far on the ARM platform.
![far2l-pi](https://user-images.githubusercontent.com/8525021/95781323-938eb700-0c9b-11eb-8f6d-27e4fdc6bf45.png)
