### ISSUE TITLE
far2l stopped working on Ubuntu 16.04

### ISSUE THREAD

**Issue by asimonov** [elfmz/far2l#486]
Hi,

I use far2l (from apt repository) on Ubuntu 16.04.
It was working well for months, but today it went crazy. And I cannot fix it.

On the left pane I can only see files, but not directories. Plus '..' directory. If I go up (..) the situation repeats. Eventually I get to the / directory and only see initrd and vmlinuz files. 

On the right pane I see only directories, but not files. I can navigate the directory structure but see no files anywhere.

If i remove ~/.config/far2l the situation is the same.

I think I did 'sudo apt update' today after which fa2l stopped working.

this is the version I use:
```
$ dpkg -l | grep far2l
ii  far2l                                                    20181228.d925422~ubuntu16.04.1               amd64        Linux port of FAR manager v2
```

I have also tried to build from source from current master, but see the same issue.

![far2l-issues](https://user-images.githubusercontent.com/240630/51124292-da752180-1815-11e9-9ce1-d660f311da2e.png)

**Comment by elfmz** [comment]
What you're describing looks like messed up filters settings (Ctrl+I)
However rm -rf ~/.config/far2l must fix this. But make sure you doing that when no far2l is running ('sudo killall -9 far2l' will ensure this)

**Comment by asimonov** [comment]
@elfmz yes, that was it!

it was enough to delete ~/.config/far2l/REG/HKU/c/k-Software/k-Far2/k-Filters
