### ISSUE TITLE
[Mac] Far's child bash doesn't release SD card, even if it's not in the directory.

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#489]
I don't know what file it holds.

**Comment by singalen** [comment]
Reproduced and ran `lsof`.
It's not far2l itself, it's child `bash` process:
```
$ lsof -n|grep USB128
bash      12540  vic   32r      DIR               1,11      32768          2 /Volumes/USB128
```

12540 is Far's child shell process,  `/opt/local/bin/bash -i` (`/opt/local/bin/bash` is my `$SHELL`).

I ran `pwd` in each of 2 running Far instances, the current directory was not in `/Volumes/USB128`.
I ran `cd` in each, then ran a non-builtin command, and still, `/Volumes/USB128` was locked by `bash`. 

Looks like sometimes far loses control over its child shells?

**Comment by elfmz** [comment]
is it still reproed? there were quite a lot of changes in VT code...

**Comment by singalen** [comment]
Yes, just tested if. `far2l`'s child `bash` holds 2 directories that are in neither of the active panels; but they are the directories where the panels initially were. Could it be because `bash` holds open its starting directory?

**Comment by singalen** [comment]
Amazing, thank you so much!
