### ISSUE TITLE
slow copy in far2l

### ISSUE THREAD

**Issue by asimonov** [elfmz/far2l#490]
hi,
just noticed this today - copy files from external drive is very slow.
in this case this is external USB3 hdd.
but I have seen similar issues with usb3 memory sticks.

distro: ubuntu 18.04
hardware: dell xps 15 9570
far2l installed from ppa in last few days

when I use standard ubuntu GUI copy procedure I get a speed of 430 mb/sec
in far2l i get about 15mb/sec initially, but it drops to 10mb/sec as copy continues.

the file system on external HDD is HFS+

**Comment by Alter-1** [comment]
Low speed was caused by too frequent progress bar updates
Refresh rate is limited to 1000ms (1 second) by default
It can be adjusted by ProgressUpdateThreshold registry value in System
Patch proposed (https://github.com/elfmz/far2l/pull/51)

**Comment by asimonov-hitachi** [comment]
thank you for investigating! 
do you know if this change made it to Ubuntu PPA? 
and into Mac's homebrew?

**Comment by asimonov-hitachi** [comment]
just rebuilt it from source (current master) on ubuntu 18.
by default the behaviour is the same - slow copy.
do I need to set the System/ProgressUpdateThreshold manually or there is GUI field for it?

if manually, what should the file look like?
something like this?
```
ProgressUpdateThreshold
DWORD
1000
```

**Comment by Alter-1** [comment]
There is no GUI field, only registry option. But it is not necessary to set ProgressUpdateThreshold DWORD 1000 manually, this is default.
Can you check if far2l/far2l/copy.cpp really references ProgressUpdateThreshold just to be sure ?
Also, this can be HFS+ issue. I tested with FAT/NTFS/Ext4 and observed low speed with original Far2l version. But updated version shows speed similar to console cp. May be it worth playing with 'CopyBufferSize' option. Its default value is 64k, try to increase it to 128k or may be even 1M.

**Comment by elfmz** [comment]
i'd also ask for version specification from far2l window title - those hexadecimal part, that repesent exact git commit hash from which binary was built

**Comment by asimonov** [comment]
hi! just managed to get back to this issue.
in my .config/far2l folder i did not have settings for either ProgressUpdateThreshold or CopyBufferSize

as an experiment i did the following.
using 'master' repo as of mid-july (since then there were no changes to copy.cpp)
modified the CopyBufferSize to hardcode to 1mb
measured the speed of copy reported in far2l GUI:
1. with default CopyBufferSize - 15 mb/sec
2. with 1Mb hardcoded - starts at 60mb/sec. then goes down to about 30mb/sec. which i think is fine as it gets buffered in linux. 30mb/sec is realistic speed of USB stick i copy to.

so, why dont we increase default CopyBufferSize to 1mb?

**Comment by elfmz** [comment]
If still relevant, check now please. Buffer size now is 'adaptive' - may grow dynamically up to 8 megs

**Comment by asimonov** [comment]
of course it is relevant. I use far2l on both mac and linux daily!
thanks for keeping great work!
