### ISSUE TITLE
far2l fails to write to files inside curlftpfs mounts

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#492]
mount:
curlftpfs ftp://USER:PASS@SERVER ~/ftp -o allow_other,fsname=curlftpfs,uid=1000,gid=1000,umask=077,default_permissions

gui file manager and editor (caja/xed) allows to create and edit files on mounted ftp resource
far2l does not (error 20095)

**Comment by elfmz** [comment]
not reproducible with latest - likely was fixed, but reopen if still repro for you
