### ISSUE TITLE
strange viewer/editor behavour then working with GVFS FTP mounts

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#493]
https://github.com/cycleg/far-gvfs/issues/31

1. Mount FTP resource via GVFS
2. Go to it's mount path in one of far2l panels
3. Press Shift+F4
4. Type "test.txt"
5. Press Enter
6. Type "/"
7. Press F2
8. Press Esc
9. Edit test.txt (F4) - no "/" char.

Actually, "/" is written to file, but not shown. Some charset issue? But path-dependent, why?

**Comment by unxed** [comment]
Уточнение. С галкой autodetect code page получаем вообще пустой файл в редакторе. Без - съедается часть текста вначале. Галки про utf8 влияния не оказывают.

**Comment by unxed** [comment]
Похожий баг в viewer'е:

    1. Create FTP resource
    2. Connect
    3. View any text file (F3)
    4. Hold Page Down key

Voila, entire content disappears.

Can be reproduced on ftp://mirror.yandex.ru/ubuntu/dists/xenial/Release

**Comment by cycleg** [comment]
Смутно припоминается: что-то похожее вроде бы обсуждалось применительно к файлам с Unicode при включенном ведении BOM.

**Comment by unxed** [comment]
Но блин, тут одни и те же файлы по разному ведут себя при работе на локальном диске и внутри примонтированного gvfs-ресурса! Выносит мозг конкретно, если честно. Даже не знаю, в какую сторону дальше копать.

Копируются-то тем же фаром они при этом нормально.

**Comment by unxed** [comment]
Сделал новый, лаконичный тикет с понятной инструкцией по воспроизведению косяка.
#515
