### ISSUE TITLE
[Mac] Resizing Far dragging the upper edge causes it to suddenly reduce its height

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#498]
Same goes for width if you resize it dragging top-left corner.

**Comment by singalen** [comment]
On top of that, the window becomes headerless. Looks like window flag get messed up.

**Comment by singalen** [comment]
I found a line responsible for this problem: https://github.com/elfmz/far2l/blob/master/WinPort/src/Backend/WX/wxMain.cpp#L884
@elfmz, do you know a reason why it is there? It dates back to the first commit.
On Mac, it only causes a horrible bug when resizing the window.

**Comment by elfmz** [comment]
removing this line doesn't change anything on linux for 1st look.. So lets try

**Comment by singalen** [comment]
Good! Then it probably can be removed.
I guess this should be needed for fullscreen/maximization, to position window precisely on the screen. But even then the `if` is missing a couple of conditions.

**Comment by singalen** [comment]
Thanks.
