### ISSUE TITLE
Проблема с копированием файлов.

### ISSUE THREAD

**Issue by pupupupupup** [elfmz/far2l#499]
При копировании файлов на сетевой диск, на котором не хватает места для размещения файла, он копируется сколько влезет и тихо завершает работу, не сообщая об ошибке.

При копировании на локальный диск может сообщить, а может и нет. В любом случае остается битый файл.

Под убунтой, 12, 14, 18
Под альтом.

**Comment by pupupupupup** [comment]
При копировании файлов на сетевой диск, на котором не хватает места для размещения файла, он копируется сколько влезет и тихо завершает работу, не сообщая об ошибке.

При копировании на локальный диск может сообщить, а может и нет. В любом случае остается битый файл.

**Comment by elfmz** [comment]
Не воспроизводицца. Чем (встроенный копировщик, netrocks?) и куда (сетевой диск - чем замонтирован?) копируем?

**Comment by elfmz** [comment]
5b458e30bffb53d2c982121821773207f5bb5b37 фиксит кое что что может приводить к таким проблемам, переоткрывайте если баг еще актуален
