### ISSUE TITLE
Numpad '5' doesn't work

### ISSUE THREAD

**Issue by invy** [elfmz/far2l#5]
Numlock is deactivated.

Numpad '5' does not:
 - enter/leaves viewer, when the cursor is above file and
 - doesn't show directory size, when pressed with the cursor above the directory.

Instead the cursor jumps to the first entry in directory.

All other numpad keys (arrows, enter, gr-plus, gr-minus) are working fine.

**Comment by elfmz** [comment]
never knew about that:)
try now

**Comment by invy** [comment]
Yep, it works. However I've noticed a regression, which is related to previous commit. The regression is between 81e8bb775c944dc76fec41271f4fd4242ea8f161 and bce96fb69a02829518078864feb5da49111efd88:. Num+ and Num- are not switching to next/previous file in the internal viewer, instead they are opening search dialog.

**Comment by elfmz** [comment]
check now..

**Comment by invy** [comment]
The regression looks also resolved by now.

**Comment by elfmz** [comment]
fixed
