### ISSUE TITLE
Ukrainian I/i letter support for OEM cp866 charset

### ISSUE THREAD

**Issue by Alter-1** [elfmz/far2l#502]
Ukrainian I/i letter support for OEM cp866 charset.

There is well-known Windows problem with Ukrainian letters 'I' and 'i'. They are displayed as question mark ('?') in console applications. 
OEM cp866 characters 0xf6 (I ukr) and 0xf7 (i ukr) should be mapped to unicode 0x0406 and 0x0456 (http://alter.org.ua/en/soft/linux/wine_cp866u/)

The patch proposed adds support for ukrainian cp866 (cp866ukr) as codepage 22866
(like koi8r, koi8u) with 866ukr OEM-Unicode translation
[far2l_cp866uk.patch.gz](https://github.com/elfmz/far2l/files/2963715/far2l_cp866uk.patch.gz)

**Comment by singalen** [comment]
Wow, there were multiple variants of 866. https://en.wikipedia.org/wiki/Code_page_866#Character_set
BTW, your website is down.

**Comment by singalen** [comment]
I have submitted this patch as a PR.
Was there any reason to put the `cp866uk` where it was? I have moved it right after `cp866`, did it break anything?

**Comment by singalen** [comment]
Can be closed, I believe?
