### ISSUE TITLE
hotkeys problems with far2l --tty under screen tool

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#510]
ESC has to be pressed twice.
Ctrl+Shift+Arrows not working.
Ctrl+Shift+Home/End not working.
Numpad "\*" puts "\*" in command line instead of selecting all files.
Hotkeys help in the bottom of the screen on ctrl/shift/alt not working.

**Comment by Alter-1** [comment]
have same result without screen

**Comment by Alter-1** [comment]
ESC is a special character, Cannot be fixed
Numpad seems to be fixed either with terminal settings (https://vi.stackexchange.com/questions/11581/why-doesnt-my-numpad-work-right-in-my-terminal) or with Macros (map '*' with EmptyCommandLine flag to KEY_MULTIPLY). Btw, midnight commander has same behavior with *, but it always handles it as Select All. Event with Shift+8
Ctrl-Shift-Arow/Home/End are working fine (with and without screen). Probably, this is terminal settings issue. Tested with TERM=xterm-256colors

**Comment by unxed** [comment]
Used far2l's internal terminal.

**Comment by unxed** [comment]
Ctrl+Enter, Ctrl+Insert and clipboard sync are also broken under screen.

**Comment by kolomparrudi** [comment]
Hi,

Shift-F1 opens Plugin commands (defined to F11) instead of Add to archive
Shift-F2 behave like F12
Ctrl-Enter behave like Enter
Alt-F7 prints [18~ to command prompt
Tried with TERM=xterm-256colors and TERM=linux

Regards,
kolomparrudi

**Comment by elfmz** [comment]
for those who are using screen to keep far2l running in case SSH connection broken - far2l is now able to do this by itself on branch revival. Its now doesn't terminate when getting SIGHUP, but falls into revival-awaits state and can be revived from prompt that will be shown by any new far2l started in tty mode on same system under same user.
If some operation pending or app runs in far2l's terminal - it should survive such state. Futhermore - it should continue working while being in such mode.

**Comment by unxed** [comment]
Reinventing terminal (all hotkeys), reinventing ssh (clipboard sync), now reinventing screen :) Divine, new era of text-based interfaces is coming)))

Next step is to implement startup scripts support to do things like
1. Connect to NetRocks account named NNN
2. Run far2l inside
in one click and have icons like "far2l on myhost.com" on desktop.

**Comment by unxed** [comment]
```
[ 18%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/Backend/TTY/TTYRevive.cpp.o
In file included from /usr/include/x86_64-linux-gnu/sys/socket.h:33:0,
                 from /home/unxed/far2l/branch/far2l/far2l/WinPort/src/Backend/TTY/TTYRevive.cpp:3:
/home/unxed/far2l/branch/far2l/far2l/WinPort/src/Backend/TTY/TTYRevive.cpp: In function ‘bool unixdomain_send_fd(int, int)’:
/home/unxed/far2l/branch/far2l/far2l/WinPort/src/Backend/TTY/TTYRevive.cpp:41:10: error: request for member ‘__cmsg_data’ in
 ‘* & buf.std::vector<char>::operator[](0)’, which is of non-class type ‘__gnu_cxx::__alloc_traits<std::allocator<char> >::v
alue_type {aka char}’
  *(int *)CMSG_DATA(&buf[0]) = fd;
          ^
/home/unxed/far2l/branch/far2l/far2l/WinPort/src/Backend/TTY/TTYRevive.cpp: In function ‘int unixdomain_recv_fd(int)’:
/home/unxed/far2l/branch/far2l/far2l/WinPort/src/Backend/TTY/TTYRevive.cpp:77:17: error: request for member ‘__cmsg_data’ in
 ‘* & buf.std::vector<char>::operator[](0)’, which is of non-class type ‘__gnu_cxx::__alloc_traits<std::allocator<char> >::v
alue_type {aka char}’
  return *(int *)CMSG_DATA(&buf[0]);
                 ^
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-c++11-narrowing’
cc1plus: warning: unrecognized command line option ‘-Wno-c++11-narrowing’
WinPort/CMakeFiles/WinPort.dir/build.make:758: recipe for target 'WinPort/CMakeFiles/WinPort.dir/src/Backend/TTY/TTYRevive.c
pp.o' failed
make[2]: *** [WinPort/CMakeFiles/WinPort.dir/src/Backend/TTY/TTYRevive.cpp.o] Error 1
CMakeFiles/Makefile2:145: recipe for target 'WinPort/CMakeFiles/WinPort.dir/all' failed
make[1]: *** [WinPort/CMakeFiles/WinPort.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by elfmz** [comment]
fixd

**Comment by unxed** [comment]
Wow, it really works, cool!

**Comment by elfmz** [comment]
following command in far2l terminal sends it to background state:
kill -TSTP $FARPID
it did it previously too but now far2l will not terminate if terminal goes away while its in background

**Comment by unxed** [comment]
Can not be used then copying is done, for example, or if some command is executed in terminal. Hotkey?

**Comment by elfmz** [comment]
I afraid to define such whole-wide hotkeys.
However for your scenario its enough just to close terminal. Although there is issue with closing far2l - when inside of its terminal command being executed it doesnt respond to close button. But its just a small far2l's bug

**Comment by unxed** [comment]
> I afraid to define such whole-wide hotkeys.

Mouse gestures?))))

> However for your scenario its enough just to close terminal.

Yes, I do it just that way right now)

> But its just a small far2l's bug

Yes, annoying thing.

**Comment by elfmz** [comment]
> Mouse gestures?))))

Uh, no



> Yes, annoying thing.

fixed

**Comment by unxed** [comment]
```
[ 19%] Building CXX object WinPort/CMakeFiles/WinPort.dir/src/Backend/TTY/TTYNegotiateFar2l.cpp.o
/home/unxed/far2l/branch/far2l/far2l/WinPort/src/Backend/TTY/TTYNegotiateFar2l.cpp: In function ‘bool TTYNegotiateFar2l(int,
 int, bool)’:
/home/unxed/far2l/branch/far2l/far2l/WinPort/src/Backend/TTY/TTYNegotiateFar2l.cpp:40:3: error: ‘fd_set’ was not declared in
 this scope
   fd_set fds, fde;
   ^~~~~~
/home/unxed/far2l/branch/far2l/far2l/WinPort/src/Backend/TTY/TTYNegotiateFar2l.cpp:40:3: note: suggested alternative: ‘fdout
’
   fd_set fds, fde;
   ^~~~~~
   fdout
/home/unxed/far2l/branch/far2l/far2l/WinPort/src/Backend/TTY/TTYNegotiateFar2l.cpp:41:12: error: ‘fds’ was not declared in t
his scope
   FD_ZERO(&fds);
            ^~~
/home/unxed/far2l/branch/far2l/far2l/WinPort/src/Backend/TTY/TTYNegotiateFar2l.cpp:41:12: note: suggested alternative: ‘ffs’
   FD_ZERO(&fds);
            ^~~
            ffs
/home/unxed/far2l/branch/far2l/far2l/WinPort/src/Backend/TTY/TTYNegotiateFar2l.cpp:41:3: error: ‘FD_ZERO’ was not declared i
n this scope
   FD_ZERO(&fds);
   ^~~~~~~
/home/unxed/far2l/branch/far2l/far2l/WinPort/src/Backend/TTY/TTYNegotiateFar2l.cpp:41:3: note: suggested alternative: ‘_SC_N
ZERO’
   FD_ZERO(&fds);
   ^~~~~~~
   _SC_NZERO
/home/unxed/far2l/branch/far2l/far2l/WinPort/src/Backend/TTY/TTYNegotiateFar2l.cpp:42:12: error: ‘fde’ was not declared in t
his scope
   FD_ZERO(&fde);
            ^~~
/home/unxed/far2l/branch/far2l/far2l/WinPort/src/Backend/TTY/TTYNegotiateFar2l.cpp:42:12: note: suggested alternative: ‘fdin
’
   FD_ZERO(&fde);
            ^~~
            fdin
/home/unxed/far2l/branch/far2l/far2l/WinPort/src/Backend/TTY/TTYNegotiateFar2l.cpp:43:3: error: ‘FD_SET’ was not declared in
 this scope
   FD_SET(fdin, &fds);
   ^~~~~~
/home/unxed/far2l/branch/far2l/far2l/WinPort/src/Backend/TTY/TTYNegotiateFar2l.cpp:43:3: note: suggested alternative: ‘L_SET
’
   FD_SET(fdin, &fds);
   ^~~~~~
   L_SET
/home/unxed/far2l/branch/far2l/far2l/WinPort/src/Backend/TTY/TTYNegotiateFar2l.cpp:45:18: error: variable ‘TTYNegotiateFar2l
(int, int, bool)::timeval tv’ has initializer but incomplete type
   struct timeval tv = {10, 0};
                  ^~
/home/unxed/far2l/branch/far2l/far2l/WinPort/src/Backend/TTY/TTYNegotiateFar2l.cpp:51:19: error: ‘select’ was not declared i
n this scope
   if (os_call_int(select, fdin + 1, &fds, (fd_set*)nullptr, &fde, &tv) <= 0) {
                   ^~~~~~
/home/unxed/far2l/branch/far2l/far2l/WinPort/src/Backend/TTY/TTYNegotiateFar2l.cpp:51:19: note: suggested alternative: ‘exec
l’
   if (os_call_int(select, fdin + 1, &fds, (fd_set*)nullptr, &fde, &tv) <= 0) {
                   ^~~~~~
                   execl
/home/unxed/far2l/branch/far2l/far2l/WinPort/src/Backend/TTY/TTYNegotiateFar2l.cpp:51:51: error: expected primary-expression
 before ‘)’ token
   if (os_call_int(select, fdin + 1, &fds, (fd_set*)nullptr, &fde, &tv) <= 0) {
                                                   ^
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-c++11-narrowing’
cc1plus: warning: unrecognized command line option ‘-Wno-c++11-narrowing’
WinPort/CMakeFiles/WinPort.dir/build.make:878: recipe for target 'WinPort/CMakeFiles/WinPort.dir/src/Backend/TTY/TTYNegotiat
eFar2l.cpp.o' failed
make[2]: *** [WinPort/CMakeFiles/WinPort.dir/src/Backend/TTY/TTYNegotiateFar2l.cpp.o] Error 1
CMakeFiles/Makefile2:145: recipe for target 'WinPort/CMakeFiles/WinPort.dir/all' failed
make[1]: *** [WinPort/CMakeFiles/WinPort.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by unxed** [comment]
> kill -TSTP $FARPID

1. Opened wx far
2. Started far2l --tty inside
3. kill -TSTP $pid_of_inner_far2l

inner far2l just hanged

**Comment by elfmz** [comment]
try build now

**Comment by unxed** [comment]
> Try build now

Builds, thanks!

> Also in order to revive - prev terminal must be closed, before that it can only be resumed in original terminal.

Tried to reproduce - now hanging on revival attempt.

**Comment by elfmz** [comment]
after some thinking i decided to rewrite if using intermediate process, it will be more reliable and will allow far2l to stay active before actual terminal close

**Comment by elfmz** [comment]
done, note that
- to detach far2l from terminal need to send SIGHUP: kill -HUP $FARPID 
- now tty-backed far2l by default launched with 'shim' process, that doesn't do anything except waiting child far2l and 'decoupling' it from terminal. Shim process changes its own comand line so ps -aux presents it as "shim." (or "shim.far2l" if there is enough place in original argv[0] :))

**Comment by unxed** [comment]
Local detach-resume working flawlessly, great!

btw, maybe we need some confirmation on wx far2l close, like "far2l is executing inner process, sure to close?" as gnome terminal does? Same with ongoing file operations.

Or someone may accidentally close local far2l thinking he is closing remote (or inner tty) one that cat be detached and revived.

**Comment by elfmz** [comment]
May be, but not in this change.

**Comment by elfmz** [comment]
closing as its impossible pass custom esc commands through screen and as far2l is able to detach to background by itself
