### ISSUE TITLE
Charset setection: Google ECD instead of UCD

### ISSUE THREAD

**Issue by Alter-1** [elfmz/far2l#513]
There is an idea of switching charset detector from UCD
(https://github.com/yhfudev/cpp-libucd) to newer and better supported Google CED (Compact encoding detection) - https://github.com/google/compact_enc_det/

**Comment by unxed** [comment]
Is it still actual after https://github.com/elfmz/far2l/commit/32374c518a1e0ad93148bfd1a09e0c6baed88598 ?

**Comment by elfmz** [comment]
closing as uchardet is better supported and more widespread in repositories
