### ISSUE TITLE
view/edit not working properly in GVFS-mounted FTP folders

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#515]
Steps to reproduce:

1. Mount ftp://mirror.yandex.ru/ via GVFS (either with far-gvfs or using any other GVFS frontend).
2. Go to ubuntu-releases folder.
3. Try viewing robots.txt by pressing F3 or editing it via F4.

Copying this file or opening it in other software works perfectly.

**Comment by unxed** [comment]
For all others facing with this bug: use native FTP plugin instead.

**Comment by elfmz** [comment]
check now plz (if still relevant)

**Comment by unxed** [comment]
Can be assumed non-relevant, i think. Not using GVFS for a long time in favor of NetRocks.
