### ISSUE TITLE
[FreeBSD] failed to build

### ISSUE THREAD

**Issue by ZOleg73** [elfmz/far2l#517]
Latest far2l failed to build on FreeBSD 12. I make corrections and now far2l build and work on FreeBSD.

[far2l.my.tar.gz](https://github.com/elfmz/far2l/files/3062742/far2l.my.tar.gz)
![screen1](https://user-images.githubusercontent.com/45186445/55863725-b1162880-5bad-11e9-83bc-88a5197ed193.png)

**Comment by Slach** [comment]
Dear @ZOleg73 could you make pull request in github?

**Comment by ZOleg73** [comment]
How to do it? ( I do not know how to work with git)

**Comment by ZOleg73** [comment]
Ок  I make pull request.
