### ISSUE TITLE
Font and colorscheme in console

### ISSUE THREAD

**Issue by flyasky** [elfmz/far2l#521]
Hi!

Why in console mode font on panels so strange? (not Ubuntu Mono as I've set)
Why black for background is not black? )  I tryed to choose different color settings for terminal and I didnt find good one.

Attached MC+Far(ttl)+Far(old)
![Screenshot from 2019-04-20 20-53-23](https://user-images.githubusercontent.com/213282/56460637-6b780d80-63ae-11e9-964b-0322504cd1fe.png)

**Comment by elfmz** [comment]
About font - if your problem is gaps between characters then its fixed now
About colors - see last message here: https://ubuntuforums.org/showthread.php?t=1081568

**Comment by unxed** [comment]
This script will adopt terminal's palette to default far2l's one so far2l looks almost the same as in graphic version:
https://github.com/elfmz/far2l/issues/1385#issuecomment-1304657386

**Comment by elfmz** [comment]
Looks may close as everythng is fixed now
