### ISSUE TITLE
[netrocks] add pubkey auth support

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#526]

**Comment by elfmz** [comment]
Вроде сделал. Наверное. См [Protocol options] в настройках соединения.

**Comment by unxed** [comment]
здорово! спасибо! у меня всё работает =)

только консольный ssh-клиент же как-то сам угадывает, что ключик у меня лежит в ~/.ssh/id_rsa
может, и в far2l так можно?

а, и ещё одна деталька. netrocks понимает /home/unxed/.ssh/id_rsa, но не понимает ~/.ssh/id_rsa

мелочь, но бесит

**Comment by elfmz** [comment]
ssh юзает ~/**.ssh**/id_rsa потому что он это его настройки
А у far2l свои настройки, некошерно лазить в чужие.
А shell-style word expansion сделал. Теперь можно даже * вставить, правда заюзает только первый успешнозагруженный ключ.

**Comment by unxed** [comment]
> потому что он это его настройки
> А у far2l свои настройки, некошерно лазить в чужие.

MATE лазает и усом не ведёт

> А shell-style word expansion сделал

здорово, спасибо! :)

**Comment by singalen** [comment]
Ну, дефолтный текст на `~/.ssh/id_rsa` не помешает, это дефолт самого ssh (и ssh-keygen), и отражён в [документации](https://man.openbsd.org/ssh-keygen.1#FILES). 

А при пустом поле, да, всё становится сложнее - ssh проверяет 4 разных файла только по дефолту (~/.ssh/id_dsa, ~/.ssh/id_ecdsa, ~/.ssh/id_ed25519, ~/.ssh/id_rsa). А у Dropbear, например, вообще свой формат, и он хранится в `~/.ssh/id_dropbear`.
