### ISSUE TITLE
farcolorer crash

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#530]
pressing this button (editor-f11-farcolorer-reload schema library-scheme) makes far2l crash

![Снимок экрана в 2019-05-21 01-56-57](https://user-images.githubusercontent.com/1151423/58056987-e8dc9c80-7b6b-11e9-9ffd-b5efa8716509.png)

**Comment by elfmz** [comment]
надо бы подтянуть свежий колорер, похоже на баг-баян: https://bugs.farmanager.com/view.php?id=3678
