### ISSUE TITLE
Update colorer's proto.hrc to use ".tpl" for "Smarty PHP templates", not ".smarty"  

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#531]
There is no simple way to override this on the user's side without copying all colorer base.

Smarty itself does not define extension for template files strictly, but ".tpl" is standard de facto, and it is also used by IntelliJ PhpStorm by default.

I guess Turbo Prolog for .tpl is used significantly less often.

UPD:

sublime smarty plugin assumes .tpl:
https://github.com/amitsnyderman/sublime-smarty

atom plugin uses .tpl:
https://atom.io/packages/language-smarty

vscode plugin for smarty allows both, but .tpl goes first:
`"extensions": [".tpl",".smarty",".html.smarty"],`
https://github.com/jens1o/vscode-smarty/blob/master/package.json

**Comment by unxed** [comment]
btw, colorer itself is synced from https://github.com/colorer ?

**Comment by unxed** [comment]
Upstream: https://github.com/colorer/Colorer-schemes/issues/76

**Comment by elfmz** [comment]
"colorer itself is synchronized"
Nope. Needs porting to latest colorer lib. Not superwork, but boring :(

**Comment by cycleg** [comment]
Я пытался собирать с Colorer-library@095ec36220ee3f6886effca250a3917762e788f0. Чуть-чуть не хватает в самой библиотеке: плагин не собирается на халяву со статическими libcolorer и libxerces, поскольку обе строятся без "PIC". Еще пара генерируемых заголовочных файлов кладется чуть-чуть не туда, куда хотелось бы:
```
# Make sure cmake-generated Xerces_autoconf_config.hpp and
# XercesVersion.hpp end up in a proper place when installed.
install(
  FILES "${CMAKE_CURRENT_BINARY_DIR}/xercesc/util/Xerces_autoconf_config.hpp"
        "${CMAKE_CURRENT_BINARY_DIR}/xercesc/util/XercesVersion.hpp"
  DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/xercesc/util"
  COMPONENT "development")
```
В результате они оказываются в "трудноуловимом" месте, если библиотеку не устанавливать.

Далее коварный xerces подтаскивает скрытую зависимость от ICU, если вдруг она имеется. Обнаруживается это только при загрузке плагина. Лечится примерно так:
```
list(APPEND CMAKE_MODULE_PATH "${LIBCOLORER_TREE}/libs/xercesc/cmake")
include(XercesICU)
include(XercesMsgLoaderSelection)
include(XercesTranscoderSelection)

if(XERCES_USE_TRANSCODER_ICU OR XERCES_USE_MSGLOADER_ICU)
  # libxerces depends from ICU
  target_link_libraries(colorer ICU::uc ICU::data)
endif(XERCES_USE_TRANSCODER_ICU OR XERCES_USE_MSGLOADER_ICU)
```
Ну а заканчивается приключение вызовом чисто виртуального метода при загрузке плагина. :) Вот как-то так.

**Comment by cycleg** [comment]
Вроде бы работает с текущей версией Colorer-library, только нужно подрихтовать cmake-проекты для libcolorer и libxerces, чтобы собирались с "PIC". Прочие правки -- исключительно в коде плагина.

**Comment by cycleg** [comment]
Colorer-library собирается как подпроект plugin'а colorer. В таком виде ничего в коде Colorer-library править не надо, и все файлы чудесно разбегаются, куда следует. Сам colorer работает только в путь. В целом проблема замены на текущую Colorer-library решена.

**Comment by unxed** [comment]
> Colorer-library собирается как подпроект plugin'а colorer. В таком виде ничего в коде Colorer-library править не надо, и все файлы чудесно разбегаются, куда следует. Сам colorer работает только в путь. В целом проблема замены на текущую Colorer-library решена.

И ни репозитория ни хотя бы архивчика ;)

**Comment by cycleg** [comment]
Справедливое замечание! :)

Вот архивчик. В cmake-проекте в переменной LIBCOLORER_TREE задается путь к дереву исходных кодов [Colorer-library](https://github.com/colorer/Colorer-library). Соответственно, его нужно вытянуть с его субмодулями. Ну а переменную можно и через главный проект far2l задать.

Из кода самого плагина изгнана g3log, ну и код приведен к текущему API Colorer-library. Код библиотек выброшен за ненадобностью.

Все переделанные места можно найти по директивам
```
#if 0
...
#endif // if 0
```

colorer собирается со статическими библиотеками, поэтому получается изрядно здоровым.

Сейчас сами цветовые схемы по-прежнему лежат в дереве colorer'а. Честно говоря, не хватило духу разбираться с их сборкой, поскольку не очень понятно, какой вариант сборки нужен (base.far?). Схемы теперь обитают в [отдельном репозитории](https://github.com/colorer/Colorer-schemes).

[colorer.tar.gz](https://github.com/elfmz/far2l/files/3517205/colorer.tar.gz)

**Comment by elfmz** [comment]
сделал (пока) тестовую ветку colorer-update на основе версии от cycleg плюс:
- переколбасил на юзание системных xerces, minizip, spdlog (гореть бы ему в топке)
- перевел Colorer-library с C++17 на С++11 (вот тут наверное много котят полегло)
ЗЫ а вот еслиб был pull request постоянно маячивший перед глазами, то это все на полгода раньше было бы, наверное

**Comment by unxed** [comment]
По теме данного конкретного тикета там не поменялось ничего, кажется. Для шаблонов smarty всё ещё используется .smarty вместо .tpl, и схема для них всё ещё глючная. Вот моя версия, слегка исправленная (не идеально, но работать уже вполне можно).
[smarty.zip](https://github.com/elfmz/far2l/files/5299086/smarty.zip)

**Comment by elfmz** [comment]
дык это, да пулреквест им в глотку, лопни мой багтрекер...
а потом себе втянуть свеженькие официальные схемы, с фиксами

**Comment by unxed** [comment]
Ну у меня там как-то явно криво оно сделано. Не думаю, что в официалку примут такое. Но оно работает, а как сделать красиво, я не знаю (:

**Comment by elfmz** [comment]
У них там кстати какаято эвристика вроде есть, с весами, это насчет выбора между Turbo Prolog  и smarty. Так что лучше им таки правда баг открыть, ибо разбираться как оно все работает несколько геморрно, а они и так все знают.

**Comment by unxed** [comment]
Так баги открыты, выше ссылки. Они пишут, мол, решайте это на своей стороне в ~hrc/auto/
https://github.com/colorer/Colorer-schemes/issues/75#issuecomment-495887235

**Comment by unxed** [comment]
В общем, вот мои исправления в виде PR.

На этот раз я ничего в существующей базе Colorer'а не трогал, так что синхронизацию в будущем оно не усложнит. Все изменения сделаны через папку auto, которая как раз и предназначена для кастомных шаблонов. Туда добавлен файлик smarty_fixed.hrc со слегка улучшенной схемой для Smarty (которой почему-то не рады в самом Colorer — добавляйте, говорят, в auto — ну я и добавил :).

Проблема ванильной схемы в том, что она не понимает разницы между css/js (где встречаются фигурные скобки иногда) и фигурными скобками шаблонов Smarty. Получается вот такое:
![Снимок экрана в 2020-10-11 23-07-07](https://user-images.githubusercontent.com/1151423/95689206-dd35be00-0c17-11eb-96e3-1ab6062e77fa.png)
В моей схеме это исправлено:
![Снимок экрана в 2020-10-11 23-10-09](https://user-images.githubusercontent.com/1151423/95689219-e757bc80-0c17-11eb-909a-46e2ef641948.png)

Вроде и мелочь, но очень упросит жизнь тем, кто с этой Smarty имеет дело. Заодно расширения файлов там поменено на .tpl, которое куда чаще в реальном мире используется, чем .smarty.

**Comment by unxed** [comment]
Отправил PR в апстрим https://github.com/colorer/Colorer-schemes/issues/131

**Comment by unxed** [comment]
@elfmz я что-то не догоняю, как последовать этому совету: https://github.com/colorer/Colorer-schemes/issues/76#issuecomment-501654609

Как-то можно сделать per-user оверрайды для правил colorer'а? Но как?

**Comment by unxed** [comment]
Фикс: https://github.com/unxed/far2l-deb/tree/master/colorer-smarty

**Comment by unxed** [comment]
Fixed in upstream. Backport:
https://github.com/elfmz/far2l/pull/2198

**Comment by unxed** [comment]
Fixed in https://github.com/elfmz/far2l/commit/b168e260c572fac33d3c212cafd856c1f14d1e2c
