### ISSUE TITLE
[NetRocks] implement WebDAV support (probably using neon library)

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#535]
https://en.wikipedia.org/wiki/Neon_(library)

**Comment by elfmz** [comment]
Дубль же по сути #247 -го
ЗЫ NEON этот я и сам уже смотрел. Немного геморно у них сделано что ne_get() пишет именно в fd, а не в буфер в памяти или какой нить там callback, но решабельно.

**Comment by unxed** [comment]
А, ок, если 247й о полном функциональном эквиваленте NetBox'а, тогда закрываю.
