### ISSUE TITLE
[FreeBSD+ssh] read_passphrase: can't open /dev/tty: Device not configured

### ISSUE THREAD

**Issue by v20z** [elfmz/far2l#544]
Hello everyone.

On FreeBSD issuing inside console far2l session command like:
```
ssh -v user@host
```
cause problem allocating tty and thus do not allow enter password interactively:
```
debug1: Next authentication method: keyboard-interactive
debug1: read_passphrase: can't open /dev/tty: Device not configured
debug1: Authentications that can continue: publickey,password,keyboard-interactive
```
Any glue?

**Comment by elfmz** [comment]
can you open some terminal, type there
export FAR2L_STD=far2l.log
then run far2l there, reproduce issue and upload resulting far2l.log file?

**Comment by elfmz** [comment]
most interesting in that file are lines that begin from "VT:" prefix

**Comment by v20z** [comment]
Dear elfmz, thanks for your attention.

Log files as you described. Here are user-far2l.log and user-ssh.log.

Also I've noted that when logged as root command not invoked at all. Just starting shell session instead. For that is root-far2l.log.
[user-far2l.log](https://github.com/elfmz/far2l/files/3269723/user-far2l.log)
[user-ssh.log](https://github.com/elfmz/far2l/files/3269724/user-ssh.log)
[root-far2l.log](https://github.com/elfmz/far2l/files/3269725/root-far2l.log)

**Comment by elfmz** [comment]
Unfortunately dont see any obvious reason. I hoped to see some kind of failure of creating PTY via posix_openpt but there is no such error in log and thus it requires deeper debugging but i dont have FreeBSD under hands :(

**Comment by v20z** [comment]
Dear elfmz, thanks for your reply.

Highly appreciated for all your hard work and effort. Just FYI looks like invoking any command has same result:
```
/home/user$ /bin/sh                                                            ↑
sh: can't access tty; job control turned off
$
```
Then postpone it till better times :-)

**Comment by elfmz** [comment]
try following, this line - https://github.com/elfmz/far2l/blob/master/far2l/vtshell.cpp#L456 :
change to
`if ( ioctl( r, TIOCSCTTY, 0 )==-1 )`

(so replace 1st zero with r)

**Comment by v20z** [comment]
Dear elfmz, now it looks good.  Mentioned above flaws are gone. I guess you can commit those changes.

Really big thanks for your attention.
