### ISSUE TITLE
norton commander

### ISSUE THREAD

**Issue by letarg0** [elfmz/far2l#545]
Is possible to add small functionality?
long time ago i can use 90,80,75,50% of high column file. this are great because when i type a command i see what are output, i no open hide colums but normal use both, column view and output commandline.

**Comment by elfmz** [comment]
not sure if i understood correctly, but isn't ctrl+cursor up / down do what you want?

**Comment by letarg0** [comment]
I talk about this
![pobrane2](https://user-images.githubusercontent.com/35114178/59220679-cfa49a00-8bc5-11e9-8a8a-e4b31e49046c.gif)
or this
![pobrane1](https://user-images.githubusercontent.com/35114178/59220690-d501e480-8bc5-11e9-9e65-bbdc08919efc.png)

**Comment by elfmz** [comment]
so, your first screen is achievable by ctrl+cursor up, second - by Ctrl+P while active panel is right
