### ISSUE TITLE
[FreeBDS/NetRpcks/sftp] failed to change directory under symlink

### ISSUE THREAD

**Issue by v20z** [elfmz/far2l#553]
For example /home is the symbolic links to /usr/home and change directory in sftp session causes error:
```
cd /home/user

Query information error 
stat (2)
Failed object: /user
Failed site:   sftp:192.168.0.1

NetRocks::SetDirectory('/home/user', 0)
chk_path='/user'
35545: stat (2)
NetRocks::OpBase('/user', -1): DispatchInterThreadCalls returned 1
NetRocks::OpBase('/user', -1): DispatchInterThreadCalls returned 1
NetRocks::OpBase('/user', -1): DispatchInterThreadCalls returned 1
NetRocks::OpBase('/user'): aborted
NetRocks::SetDirectory('/home/user', 0) ERROR: Get mode failed
```

**Comment by elfmz** [comment]
As i understand you've used command line cd command but not navigated through panel? So it looks like not related to symlinks, just bug in cd/push command processing (unlike other commands NetRocks doesnt send cd/pushd/popd to sftp, but handles them 'internally').

**Comment by elfmz** [comment]
try now please

**Comment by v20z** [comment]
Works now properly. Thank You.
