### ISSUE TITLE
netrocks/sftp: shell scripts from remote panel are downloaded & executed locally on <enter>

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#562]
1. Make "ls.sh" on remote sftp panel:
```
#!/bin/bash
ls > ls.txt
```
2. Allow execution (NB! Ctrl+A not working in netrocks! see #563)
3. Run it ([enter] on remote panel)
4. It will generate ls.txt on local panel showing local panel content

Expected: script should be executed on remote host.

**Comment by elfmz** [comment]
problem with this bug is inconsistency of potential fix with other protocols, that are unable to execute commands remotely

**Comment by unxed** [comment]
But other commands are executed in sftp panel, so inconsistency is actually already there.

**Comment by elfmz** [comment]
Currently by pressing enter file is executed locally, by typing  - it executed remotely is protocol supports this.
After change pressing enter will execute file remotely if protocol supports this, or locally if protocol not supports this. Thats inconsistency. Bonus problem is what to do with text files etc that currently opened locally by xdg-open

**Comment by unxed** [comment]
Ask on `<enter>`?

[Execute locally] [Execute on remote host]

**Comment by elfmz** [comment]
Check https://github.com/elfmz/far2l/commits/netrocks-config branch. Netrocks has now some global options, including this one (Options/Plugins configuration/NetRocks options)

**Comment by unxed** [comment]
Works pretty well, thanks!

Btw, can we make Ctrl+A work in NetRocks panel?
