### ISSUE TITLE
netrocks/sftp: can not change file ownershop & permissions on Ctrl+A

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#563]

**Comment by elfmz** [comment]
permissions now edit'able, ownership is more problematic: sftp_chown (http://api.libssh.org/stable/group__libssh__sftp.html#gaa13f6aea1d3f67ddb73ffccc693018d0) expects UID but not username. And there is no function to map username to UID :) And also it works only under sudo'ed session (that is special twist). So i strongly disbelieve it worth implementation.
Its however possible to simple execute sudo chown on command line, but its doesnt look as right solution. And also 'enduser' can always do the same :)

**Comment by unxed** [comment]
chmod is enough for me currently, thanks!
And that about NetBox, does it allow chown and how is it implemented if so?

**Comment by elfmz** [comment]
Tried latest Far3/5454 results little bit funny.
Ctrl+A allows changing owner, but change applied only when changing from some user to root. Changing to non-root is not applied.
Well, mapping username 'root' -> UID is easy, root is always 0 UID :)

**Comment by unxed** [comment]
A-ha-ha, not sure if functional parity should include this :))

**Comment by unxed** [comment]
Strange things happen if I try to chmode on WebDAV.
Setting read or write bits not working at all.
If I set execute bit for user, it is set for group and others also.
Yandex.Disk. Maybe server specific issues.

**Comment by elfmz** [comment]
Its a lame protocol, its defines properties of files as properties that mapped to (some) HTTP headers (see https://github.com/elfmz/far2l/blob/master/NetRocks/src/Protocol/ProtocolWebDAV.cpp#L23 )
Luckily there is 'executable' property but its distant far from normal UNIX modes.
And i didnt find property for normal UNIX modes. And storing 'arbitrary' properties looks not supported at least for servers i've tried.

**Comment by unxed** [comment]
I think we can consider it solved for now.
