### ISSUE TITLE
netrocks/mac/password - copied file is 0 length

### ISSUE THREAD

**Issue by asimonov** [elfmz/far2l#564]
building from current master (july 7th) on mac mojave.
connecting to sftp using password (private key login does not work for some reason).
the copy indicator shows copying at suspiciously high speed.
then the resulting file on sftp linux server is 0 length...

**Comment by asimonov** [comment]
actually, my bad. the destination had no space left. but I think far2l should handle this situation and show the error

**Comment by elfmz** [comment]
nasty bug..
