### ISSUE TITLE
[Mac] Search in a text file viewer is ~100 times slower than grep

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#573]
I'm searching in 30M text file on MacBook 2018.
A simple search is taking about a minute, while grep does it in under a second.
Having run it under a profiler, I see the culprit: `WINPORT_SetFilePointerEx()`.
Attaching the profiler's screenshot.
<img width="1005" alt="Screen Shot 2019-08-04 at 23 49 28" src="https://user-images.githubusercontent.com/151199/62444510-8c246300-b712-11e9-96c2-b383b7306879.png">

**Comment by elfmz** [comment]
Overhead caused by UTF8, if switch to some single byte codepage then it becomes faster. Of course its still a bug, but just having workaround if no need non-latin search,.

**Comment by elfmz** [comment]
made some basic optimization for seek ops on test branch, situation improved but grep still faster: https://github.com/elfmz/far2l/tree/faster-viewer-search

**Comment by singalen** [comment]
Fantastic, thanks!
My curiosity brought me here: https://stackoverflow.com/questions/3183582/what-is-the-fastest-substring-search-algorithm. Still, my search didn't find a library that would implement any of those utf-8 aware searches.

**Comment by singalen** [comment]
Tested it. Ways faster, thanks a lot!

**Comment by singalen** [comment]
Makes sense to merge it into mainline?
