### ISSUE TITLE
-DUSEWX=no build fails

### ISSUE THREAD

**Issue by flyasky** [elfmz/far2l#578]
$ cmake -DUSEWX=no -DCMAKE_BUILD_TYPE=Release ..
$ make -j4
....
[ 63%] Linking CXX shared module ../install/Plugins/multiarc/plug/multiarc.far-plug-mb
[ 63%] Built target multiarc
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by flyasky** [comment]
on linux ubuntu 18.04

**Comment by elfmz** [comment]
try now please

**Comment by flyasky** [comment]
now it good (closing)
