### ISSUE TITLE
strange far2l-tty fail (introduced by viewer search speed up)

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#580]
1. Open far2l-wx
2. Run `ssh remote-host.tld` in internal terminal
3. Run far2l-tty inside
4. Type
`ls<enter>`
5. Press `Ctrl+O`
6. Press `<up>` `<enter>`, repeat 4-6 times
7. far2l-tty stops working
8. You will see a bunch of ASCII characters on any keypress or mouse move:
![Снимок экрана в 2019-08-20 02-23-09](https://user-images.githubusercontent.com/1151423/63306070-d2241e00-c2f1-11e9-840a-ccdb72603042.png)

Looks like this bug was introduced by viewer search speed up commit, 8d7d98cd1cc2b780f3f62ed0bd773a521590b5c4

**Comment by elfmz** [comment]
it introduced by bash aliases processing, as temp workaround - comment out this line: https://github.com/elfmz/far2l/blob/master/far2l/execute_oscmd.cpp#L145
