### ISSUE TITLE
Installation failed under Debian 9.8 (X11 needed??)

### ISSUE THREAD

**Issue by mr-older** [elfmz/far2l#583]
The following packages have unmet dependencies:
 libgl1-mesa-dev : Depends: x11proto-dri2-dev (>= 2.6)
                   Depends: x11proto-gl-dev (>= 1.4.14)
E: Unable to correct problems, you have held broken packages.

Does it need X11?

Far was (!) and is (!) a console program under Windows, not desktop one. So I supposed to run it as MC, with no X installed. Far is often used in administration purposes, so running in console is essentially important. Most servers don`t need X installed: it is a bad practice, causing unwanted  troubles.

Such a change in the whole paradigm of the application... makes it a Total Commander or so, isn't it?

**Comment by elfmz** [comment]
Configure with -DUSEWX=no if dont want GUI mode.
Note that usual terminals have quite limited and picky support of extended keys/modifiers so usual using of far is quite inconvinient. However if you will locally run far2l in GUI mode and inside of its pseudoterminal will run remote far2l in terminal mode - they will interconnect using private escape sequences that will provide full-featured keyboard shortcuts support.

**Comment by mr-older** [comment]
Thank you very match for the answer, it was successfully compiled and works as described above: many of keyboard shortcuts are unavailable.

> However if you will locally run far2l in GUI mode and inside of its pseudoterminal will run remote far2l in terminal mode - they will interconnect

Is it possible to link in a such manner Windows Far and Linux Far?

**Comment by elfmz** [comment]
Nope, but it theoretically possible to run far2l under Windows/wsl/x11: https://www.scivision.dev/x11-gui-windows-subsystem-for-linux/ 
PS it looks little bit pervertedly :)

**Comment by unxed** [comment]
> pervertedly

Is it theoretically possible to write Far for Windows plugin that will intercept keypresses and translate them to far2l-compatible escape sequences for openssh command line client running under Far for Windows?

:)

**Comment by elfmz** [comment]
Well, its possible by adding terminal emulator (with far2l extensions) into NetBox plugin. If someone really need it - he may try to do this :)
It will also make built-in NetBox SSH commands executor more usable not only to run far2l.

**Comment by elfmz** [comment]
About pervertions. I've just managed to compile&run under cygwin far2l with Blackjack and NetRocks. And connected to Linux and ran remote far2l inside.

**Comment by elfmz** [comment]
Here is what selected in cygwin installer:
![image](https://user-images.githubusercontent.com/20957349/64412785-dc3b7000-d098-11e9-8f56-463b3df23101.png)
Then in cygwin's shell:
- followed normal far2l/cmake build sequence
- started X server:
```
export DISPLAY=:0.0
startxwin >/dev/null 2>&1 &
```

**Comment by unxed** [comment]
> About pervertions. I've just managed to compile&run under cygwin far2l with Blackjack and NetRocks. And connected to Linux and ran remote far2l inside.

Can you publish binaries please? ;)

Btw, NetBox far2l-compatible extension looks as pretty solution for both comfortably running remote far2l from windows machine and having far-windows-only-tools (like ntfs streams, registry editor, etc) in one piece of software and with no need for additional dependencies like x server :)

**Comment by unxed** [comment]
Should we rename with issue now? Something like "running remote far2l from windows box"?

**Comment by unxed** [comment]
> Well, its possible by adding terminal emulator (with far2l extensions) into NetBox plugin. If someone really need it - he may try to do this :)
> It will also make built-in NetBox SSH commands executor more usable not only to run far2l.

Issue tracker of NetBox is more suitable place to discuss this, I guess :)

It's hardly possible that someone will ever want to fork NetBox for this.

**Comment by unxed** [comment]
Should we rename this issue now? Something like "running remote far2l from windows box"?

**Comment by unxed** [comment]
> under cygwin

Can wx be tuned to use native GDI instead of x11 on windows?

**Comment by unxed** [comment]
> > Issue tracker of NetBox is more suitable place to discuss this concept, I guess :)
> Original FAR's folks not happy about far2l, so patching cygwin to use GDI directly looks more feasible:)

As I can see in NetBox issue, I've got a problem with explanation, that do we really need from NetBox. Could you please just help with more clear wording in Russian? Maybe Far folks not treat it as reasonable, but someone else who will see the issue does? :)

> patching cygwin to use GDI directly looks more feasible :)

patching cygwin, not cygwin's wx? o_O

**Comment by unxed** [comment]
Btw, how does far2l --tty behaves under cygwin? Does it work inside console as needed?

**Comment by elfmz** [comment]
> Btw, how does far2l --tty behave under cygwin?

Badly, i didnt tested throughouly, but it looks that cygwin terminal has own special bugs :)

**Comment by unxed** [comment]
> cygwin terminal has own special bugs 

Is it possible that MingGW behaves better?

**Comment by unxed** [comment]
Maybe we can rename issue to "cygwin port" or place [this comment](https://github.com/elfmz/far2l/issues/583#issuecomment-528762866) in a wiki howto page? Using remote far2l from windows via cygwin is nice option nobody actually knows about :)

**Comment by unxed** [comment]
One more way to use remote far2l from windows - is [ttyd](https://github.com/tsl0922/ttyd). We also can borrow it's browser rendering for another backend and add clipboard support, for example :)

**Comment by unxed** [comment]
> Here is what selected in cygwin installer

Выложил cygwin'овские бинарники (пока только x86_64), чтоб не собирать каждый раз, если вдруг понадобился.

Ставим cygwin сразу с нужными либами:
`setup-x86_64.exe -P libglib2.0_0,libneon27,libnfs8,libssh-common,libwx_baseu3.0_0,libwx_gtk3u3.0_0,xinit,xlaunch,xorg-server,libssh4,wget`
2. Открываем терминал cygwin
3. Скачиваем и распаковываем far2l:
`wget -O - https://raw.githubusercontent.com/unxed/far2l-deb/master/get_cyg_far2l_64.sh | bash`
4. Запускаем просто по "far2l" (X-сервер автоматом запустится, если ещё не).

Только переключение клавиатурных раскладок заставить работать в xming мне так и не удалось. И ещё синхронизация буфера обмена с удаленным far2l из cygwin не работает :( Вернее, работает, но только 1 символ, потом мусор.

А, и вот строчка для установки всех нужных пакетов cygwin'а для сборки, чтоб не выбирать вручную каждый раз:
`setup-x86_64.exe -P cmake,cygwin32-gcc-core,cygwin32-gcc-g++,gcc-core,gcc-g++,git,imake,libglib2.0-devel,libneon-devel,libneon27,libnfs-devel,libnfs8,libssh-common,libssh-devel,libwx_baseu3.0-devel,libwx_gtk2u3.0-devel,libwx_gtk3u3.0-devel,m4,mingw64-i686-gcc-core,mingw64-i686-gcc-g++,mingw64-i686-pthreads,mingw64-i686-wxWidgets3.0,mingw64-x86_64-pthreads,mingw64-x86_64-winpthreads,mingw64-x86_64-wxWidgets3.0,wget,xinit,xlaunch,xorg-server`

**Comment by unxed** [comment]
> Только переключение клавиатурных раскладок заставить работать в xming мне так и не удалось.

Помогло
```
XKBLAYOUT us,ru
XkbOptions grp:alt_shift_toggle
```
в `.XWinrc` в домашней папке

**Comment by unxed** [comment]
Приделал к putty поддержку клавиатурных far2l extensions, ещё одна альтернатива для "быстренько что-то сделать с чужой винды" :)

https://github.com/unxed/putty4far2l/blob/master/README.md

**Comment by unxed** [comment]
Появилась синхронизация буфера обмена :)

**Comment by unxed** [comment]
> Nope, but it theoretically possible to run far2l under Windows/wsl/x11: https://www.scivision.dev/x11-gui-windows-subsystem-for-linux/
> PS it looks little bit pervertedly :)

People are [already doing that](https://habr.com/ru/post/524370/#comment_22210420
) actually :)

![far2l on wsl](https://hsto.org/getpro/habr/comment_images/a1b/835/791/a1b835791fb6de63e882f4a9f27fb9a6.png)

![far2l on wsl 2](https://hsto.org/webt/ap/kq/fi/apkqfin1idexwbniyvk_60axy_i.png)

**Comment by mr-older** [comment]
> Btw, should we rename this issue now? Something like "running remote far2l from windows box"?

Look... Linux servers, where terminal client access from Windows is appreciated using FAR, don`t need Xs. Setup X11 (seems that cygwin much lighter, but still...), setup X11 only for FAR results in loosing resources and getting a bunch of dependencies, not worthing the goal. So... question is as is. Posts with X11 screenshots aren`t helping to solve the issue anyway. So... Netbox and SSH stay the only option for now. Not functional enough, but... the only one. Cause linux terminal isn`t catching all keyboard shortcuts. That is.

The question may be closed, other discussions are far away from the main point: FAR (far2l) is not a terminal app for Linux.

**Comment by elfmz** [comment]
> FAR (far2l) is not a terminal app for Linux.

My usual usecase of far2l via SSH is 
- run GUI far2l on machine
- connect to SSH server with NetRocks/SFTP  (or SCP)
- run server-side far2l (built without WX) directly from NetRocks command line
-... voila! working in remote terminal-only far2l with all shortcuts etc

**Comment by unxed** [comment]
> My usual usecase of far2l via SSH is

Doing just the same every day :)

> Since unxed made patched putty version same experience now also possible from Windows on client-side too. Also me didn't test it well

Some people are already using it, still no issues on github currently. I'm surprised that so rough code can do the job well enough.

**Comment by unxed** [comment]
> Badly, in overall not better that in Linux/bash, but (i didnt tested throughouly) it also looks that cygwin terminal has own special bugs :)

It is interesting, of course, how the TTY|Xi backend would behave in cygwin. Would you get a normal input, or not?

**Comment by elfmz** [comment]
If start X server under cygwin - then may be it will work..
BTW it doesnt work under MacOS if start xquartz, so prebuilt dmg-s for macos dont have TTYX enabled

**Comment by unxed** [comment]
> If start X server under cygwin - then may be it will work..

What is the difference between starting X server under cygwin and using windows native X server like XMing in this case?

> BTW it doesnt work under MacOS if start xquartz

Very strange. Maybe DISPLAY variable should be set or something like this?

**Comment by unxed** [comment]
> Here is what selected in cygwin installer

Via command line:
```
setup-x86_64.exe -P libglib2.0_0,libneon27,libnfs8,libssh-common,libwx_baseu3.0_0,libwx_gtk3u3.0_0,xinit,xlaunch,xorg-server,libssh4,wget
```

**Comment by unxed** [comment]
> Here is what selected in cygwin installer

Btw, since [ModifyOtherKeys](https://invisible-island.net/xterm/modified-keys.html) is [supported](https://github.com/mintty/mintty/issues/931#issuecomment-541106830) in cygwin's mintty, we can seriously improve UX in cygwin by supporting this keyboard protocol extension also. And also we can use the same Windows clipboard access technology as we use in WSL

**Comment by unxed** [comment]
> Here is what selected in cygwin installer

Btw, since [ModifyOtherKeys](https://invisible-island.net/xterm/modified-keys.html) is [supported](https://github.com/mintty/mintty/issues/931#issuecomment-541106830) in cygwin's mintty, we can seriously improve UX in cygwin by supporting this keyboard protocol extension also. And also we can use the same Windows clipboard access technology as we use in WSL

Try out in xterm:
```
# 48 for hidpi screen, use lesser for classic one
xterm -fn '-misc-fixed-medium-r-*-*-48-*-*-*-*-*-*-*' -xrm 'XTerm*modifyOtherKeys: 1'
printf '\033[?1036h'
showkey -a
# press Ctrl+1, Ctrl+a etc
```
