### ISSUE TITLE
Enter (and Shift+Enter) doesn't work in panels somewhere after db3f5b7

### ISSUE THREAD

**Issue by alk0** [elfmz/far2l#589]
Linux Mint 19.2 (Ubuntu 18.04)

Enter or Shift-Enter on files in panels do nothing; "." and Shift-Enter for the command line doesn't work either. The last checked working commit was db3f5b7b0381302175b1b4185d542dba3ab31c4a, the first checked non-working - a6720d1012304b58441f0af772f550e3b3b6a98d, the last checked non-working - e686aad69e664d2b37b3e59a07166ca16746f31d

As a side note - `far2l/bootstrap/scripts/vbuild.sh` doesn't have the execution bit set, it leads to errors (ignored by the script) while building; I set it manually before testing the aforementioned builds.

**Comment by elfmz** [comment]
ugh, its due to sources copied form windows/cygwin env :(
check now please

**Comment by j2969719** [comment]
`multiarc/src/formats/enum_all.sh` 100755 → 100644

**Comment by alk0** [comment]
ad0626c732355907d4dd992d6a1d7727b86294d0, clean build — all good. Thanks, guys!
