### ISSUE TITLE
NetRocks: проблема с киррилицей при подключении по протоколу scp

### ISSUE THREAD

**Issue by itspec-ru** [elfmz/far2l#593]
С помощью NetRocks настраиваем соединение с сервером по протоколу scp.
Открываем соединение, в панели видим вместо русских имен цифровую кодировку.

Например имя файла "ТЕСТ" выглядит так "\320\242\320\225\320\241\320\242"

**Comment by itspec-ru** [comment]
Добавлю, что NetRocks по протоколу smb те же файлы отображает корректно

**Comment by elfmz** [comment]
хм у меня вродь все ок
а как имена показывает команда ls, будучи запущена на том же сервере?
а протокол sftp работает? (если что - лучше юзать его, scp это старый вариант)

**Comment by elfmz** [comment]
попробуйте ща, хотя если дело в ls то и stat будет показывать так же..

**Comment by itspec-ru** [comment]
**По протоколу SCP:**

Имена файлов/каталогов теперь отображаются правильно.
Но теперь обнаружились ещё две ошибки:

1. При входе в пустой каталог прямо в панели вижу  
"stat: не удалось выполнить stat"
выглядит это как файл с именем "stat: не удалось выполнить stat" и размером 0.

2. Не отображаются скрытые файлы/каталоги (т.е. с точкой в начале имени),
хотя опция "Показывать скрытые и системные файлы" включена.
При копировании каталога, содержащего скрытые файлы, скрытые файлы будут пропущены.
По протоколу smb,sftp скрытые файлы отображаются

**По протоколу SFTP:**

Имена файлов отображаются корректно.

**Проблема установки прав доступа на копируемые файлы**

При копировании в NetRocks не предусмотрена настройка прав доступа копируемых файлов.
В идеале хотелось бы иметь галочку вроде "Копировать права доступа".
Сейчас ситуация с копированием следующая:

При копировании файлов с удалённой машины на локальную
права доступа на скопированные файлы отличаются от тех что были на удалённой машине.
Например:
[itspec]sftp:192.168.1.XXX/test>ls -la
итого 8
drwxrwxr-x. 2 itspec itspec   56 сен 18 08:17 .
drwx------. 9 itspec itspec 4096 сен 18 08:12 ..
-rw-rw-rw-. 1 itspec itspec    3 сен 18 08:32 .test.txt
-rw-------. 1 itspec itspec    0 сен 18 08:13 test.txt
-rw-rw-r--. 1 itspec itspec    0 сен 18 08:13 тест.txt

[itspec]/home/itspec/tmp/111111111111111111/test>ls -la
итого 12
drwxr-xr-x 2 itspec itspec 4096 сен 18 08:38 .
drwxr-xr-x 3 itspec itspec 4096 сен 18 08:36 ..
-rw-r--r-- 1 itspec itspec    3 сен 18 08:32 .test.txt
-rw------- 1 itspec itspec    0 сен 18 08:13 test.txt
-rw-r--r-- 1 itspec itspec    0 сен 18 08:13 тест.txt

Т.е права изменились
666 -> 644
664 -> 644
Но 
600 = 600

При отсутствии настроек прав логично было бы ожидать, что права будут сохранены.

**Comment by elfmz** [comment]
SCP пофиксил, режимы доступа в SFTP копируются, проблема ваша вызвана ограничением umask. Добавил глобальную опцию для Options/Plugins/NetRocks которая позволяет заоверрайдить umask при копировании.

**Comment by itspec-ru** [comment]
**При включенной опции "Копировать атрибуты противоречащие umask"**
при копировании на удалённый ПК возникает ошибка с диалогом "Ошибка опроса ссылки", но файл всё равно копируется. Каталог копируется только до первого файла.

**По поводу опции "Копировать атрибуты противоречащие umask"**
Было бы лучше унифицировать диалог копирования и использовать тот же что и при обычном копировании.
Ведь значение опций практически то же. И опция "Копировать режим доступа к файлам" в диалоге копирования уже есть и она там более уместна, гораздо удобнее чем каждый раз лезть в настройки плагина чтобы изменить поведение.

**Comment by elfmz** [comment]
Я так понимаю это опять (устаревший) SCP, а не SFTP? Но за баг спасибо, конечно.
Использовать существующий диалог не позволяет АПИ, разве что сделать точно-такой же.
С другой стороны, повторяю - аттрибуты копируются _всегда_, просто на них накладывается umask процесса, что как бы by-design юниксовое поведение.

**Comment by singalen** [comment]
Пока есть люди пользуются dropbear на embedded системах и не устанавливают туда полный OpenSSH, называть SCP устаревшим не вполне корректно. Тем более, [что он быстрее](https://superuser.com/a/134942/32412).

И спасибо за него :)

**Comment by elfmz** [comment]
Вроде пофиксил. Все же не стоит его использовать, если есть OpenSSH с поддержкой SFTP.
По поводу быстрее - нифига не не быстрее SFTP с pipelining'ом. Есть правда ньюанс в том что libssh не умеет пайплайнить закачку, но это дело наживное - libssh-евцы вроде не против пулреквестов на эту тему.
А вот листинг директорий в sftp на порядки быстрее чем в SCP, потому что в последнем он сделан путем запуска команд в терминале и парсинга их вывода, что в принципе не может быть быстрее нормального бинарного протокола. Не говоря уж о потенциальных проблемах совместимости.

**Comment by singalen** [comment]
OpenSSH есть, но не везде, потому что не весь мир состоит из x86_64.
Вот, например, передо мной плата с 32M флеша. На ней есть Dropbear, но нет OpenSSH, потому что совать некуда.

**Comment by elfmz** [comment]
Ну у меня в доме полно ARMовских линухов, пара девайсов на бордах типа RPI, пара NASов на армовских бордах, один из которых - старичок DLink DNS325 - и все они умеют в SFTP.

**Comment by singalen** [comment]
Конечно, умеют, если это любительская система, на которой что-то одно можно выкинуть, а другое (OpenSSH) поставить. Dropbear тоже так может.
Но это не весь мир; у некоторых килобайты наперечёт; другие настолько любители, или начинающие, что даже разбираться не хотят/не могут в том, что такое Dropbear.

**Comment by itspec-ru** [comment]
Спасибо! Баг пофикшен.

По поводу диалога

При копировании **на удалённый ПК** последовательно открываются два окна - far'а и NetRock'а.
В первом уже есть опция "Копировать режим доступа к файлам" и, если возможно, её нужно передать NetRock'у. В идеале лучше бы вообще избавиться от второго диалога.

При копировании **с удалённого ПК** (если невозможно использовать far'овский диалог) то лучше "нарисовать" такой же.

В любом случае опцию "Копировать атрибуты противоречащие umask" лучше перенести из настроек плагина в диалог копирования.
