### ISSUE TITLE
Не корректная работа поиска по Alt+"строка_поиска" для киррилицы

### ISSUE THREAD

**Issue by itspec-ru** [elfmz/far2l#594]
Для позиционировании на файле/папке на панели использую комбинацию Alt+"строка_поиска". При поиске не учитывается раскладка, поиск производится только по латинице. Т.е. в окне поиска всегда вводятся только символы латиницы даже если раскладка русская.

**Comment by elfmz** [comment]
С at+нелатиница все плохо, и хз как сделать хорошо. Проблема в том что при нажатом alt нажатия кнопок не приходят вообще. А английские таки работают потому что есть ворэраунд в виде невидимого меню с хоткеями, которые срабатывают независимо от языка.

**Comment by itspec-ru** [comment]
Жаль. Всё же какое-то решение должно быть рано или поздно.
В mc используется Alt+s, возможно по той же причине.

**Comment by unxed** [comment]
Хех, оно хитрее. При русской раскладке, если нет файла или папки с названием на нажатую английскую букву, ищется таки соответствующая этой кнопке русская. Но почему-то при повторном нажатии, а не при первом.

**Comment by unxed** [comment]
> С at+нелатиница все плохо, и хз как сделать хорошо. Проблема в том что при нажатом alt нажатия кнопок не приходят вообще. А английские таки работают потому что есть ворэраунд в виде невидимого меню с хоткеями, которые срабатывают независимо от языка.

А хоткеи в менюхе могут быть только английскими?

**Comment by elfmz** [comment]
> В mc используется Alt+s, возможно по той же причине.
Ну, вообще говоря, такой трюк применим и far2l: вначале набраь Alt+ произвольный-англ-символ, потом в появившемся окошке искать просто тайпая русские буквы.
Есть ньюанс что если произвольный англ символ подпадет в первую букву существующего файла то его стирать придется. Ну в таком случае можно юзать вместо ангд симкола кнопочку '+'. То есть последовательность получается такой:
Alt+'+' и тайпаем имя файла.
Вроде, не хуже чем в мс, но неприятно

**Comment by elfmz** [comment]
> А хоткеи в менюхе могут быть только английскими?
Ага. Есть предположение что ето баг wx (кстати вот он - https://trac.wxwidgets.org/ticket/17643 :) )

Еще есть идея на уровне обработки ввода забиндить сочетание Alt+ПРОБЕЛ и Ctrl+Пробел, сделав их 'липкими' аналогами нажатой Alt и Ctrl при нажатии следующей кнопки
То есть последовательность <Alt+Пробел> <F1> будет аналогична Alt+F1 и будет работать там где Alt+F1 занят. Дискас?

**Comment by itspec-ru** [comment]
Alt+'+' - хороший вариант, но не идеальный,
ведь на самом деле без зажатого shift - это Alt+'='
и если есть файл начинающийся с '=', то на нём и позиционируемся.
Хотя конечно файлы с такими именами редкость.

**Comment by unxed** [comment]
>  То есть последовательность <Alt+Пробел> будет аналогична Alt+F1 и будет работать там где Alt+F1 занят.

Вот эту часть не очень понял. Смысл в том, что Alt+Пробел будет включать эффект постоянно нажатого Альта? Выглядит красиво, хотя я бы предпочел Ctrl+Пробел, т.к. Alt+Пробел у меня в Mint/MATE заняты. А вообще, пока не попользуешься, не поймёшь, насколько оно юзабельно будет :) В любом случае, можно же сделать это поведение отключаемым в настройках ведь?

**Comment by unxed** [comment]
> So looks like issue induced by GTK, not by WX itself.

И ни намёка на ссылку на связанный баг в GTK))

**Comment by elfmz** [comment]
> Вот эту часть не очень понял. Смысл в том, что Alt+Пробел будет включать эффект постоянно нажатого Альта? 

Не постоянно нажатого, а нажатого на время нажатия следующей кнопки.

> Выглядит красиво, хотя я бы предпочел Ctrl+Пробел, т.к. Alt+Пробел у меня в Mint/MATE заняты.
Ctrl+пробел будет залипать таким же обрахом Ctrl.
Alt+пробел д.б. эквивалентен Win+пробел (так как Win эквивалентен Alt)

> В любом случае, можно же сделать это поведение отключаемым в настройках ведь?
Можно, но смысл? Другое дело - настраиваемым. Вместо пробела чтоб можно было настроить другую кнопку.

**Comment by elfmz** [comment]
Экспериментальная бранч готова: sticky-control-keys
Еще раз замечу, что sticky controls работают на уровне обработки нажатий внутри кода фара, а не в WinPort. Это значит что они _не_ работают для приложений запущенных внутри терминала фара. Причиной тому - вероятность того что какому то приложению внутри может потребоваться хоткей ctrl+пробел/alt+пробел. Самому фару он не нужен.

**Comment by itspec-ru** [comment]
Да, c Alt+"пробел" всё работает.
Интересная особенность - в таком варианте поиск с киррилицей тоже работает. Т.е Alt+"пробел" отпускаем, вводим символы на русском - позиционируемся корректно на русском имени файла.

**Comment by elfmz** [comment]
Почему интересная, ожидаемая же.
альт+пробел симулирует нажатый альт при нажатии последующей кнопки, даже если это нажатие - ввод русского символа.

**Comment by itspec-ru** [comment]
> Почему интересная, ожидаемая же

Ну да, конечно. Я просто темы перепутал хотел в другой теме написать "Проблема с клавиатурными комбинациями Alt+F1, Alt+F2 в консольном режиме".
В общем последние коммиты в sticky-control-keys решают сразу две проблемы.
Спасибо!

**Comment by unxed** [comment]
> Проблема в том что при нажатом alt нажатия кнопок не приходят вообще.

Если опрашивать в отдельном потоке с помощью wxGetKeyState(), отловить можно :) Не сам Alt (но сам альт и так норм прилетает), а то, что одновременно с ним нажато. Даже на русской раскладке, ага.

Сделал вот патчик: #642, с ним поиск по Alt+русские_буквы ок работает :)

**Comment by unxed** [comment]
> которые срабатывают независимо от языка

Кроме кнопок `б`, `ю`, `ж`, `э`, `х`, `ъ`, увы. Пожаловался вот в wx по этому поводу:
https://github.com/wxWidgets/wxWidgets/issues/22058

**Comment by unxed** [comment]
> В wx 3.1.3 оно (почти) исправлено

Разработчики wx перетащили соответствующие исправления и в 3.0.5. А в убунте 20.04 они даже в 3.0.4 бэкпортированы.

**Comment by unxed** [comment]
> Кроме кнопок `б`, `ю`, `ж`, `э`, `х`, `ъ`, увы.

Фикс тут: https://github.com/elfmz/far2l/issues/1211 (даже несколько вариантов)
Работает на относительно новых дистрах
