### ISSUE TITLE
Проблема с клавиатурными комбинациями Alt+F1, Alt+F2 в консольном режиме

### ISSUE THREAD

**Issue by itspec-ru** [elfmz/far2l#595]
При работе в консольном режиме (без X'ов) имеет место коллизия с комбинациями Alt+F1, Alt+F2 (используемыми far'ом для переключения "дисков") и системными - для переключения виртуальных терминалов. Очевидно при нажатии Alt+F1/Alt-F2 последует переключение на другой терминал, а не смена "диска" в far'e.

**Comment by elfmz** [comment]
Экспериментальная бранч с воркэраундом: sticky-control-keys
Вместо Alt+F1 можно нажать последовательность Alt+ПРОБЕЛ, F1
или Win+ПРОБЕЛ, F1
