### ISSUE TITLE
[netbox] trying to crossload sftp->sftp sometimes make far2l crash

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#597]
This happens just on pressing \<F5\>. It is happening or not depending on file owner/group. On that files pressing Ctrl+A also makes far2l crash.

Example:
-rw-rw-rw-   1 nobody   drk         1398 Sep 24  2015 01b3888696e73aa44e0fd41a0dff4000.jpg
-rw-rw-rw-   1 www-data www-data    1512 Oct 26  2016 0fc71a35aa6ad878163d03abe4dc4000.jpeg

First file (01b...) - ok
Second file (0fc...) - crash

**Comment by elfmz** [comment]
fixed by https://github.com/elfmz/far2l/commit/591512ac54cb0a1067755f67a5aaaa40e6af1892
