### ISSUE TITLE
Add option to reassign Alt-Key

### ISSUE THREAD

**Issue by invy** [elfmz/far2l#6]
This is a kind of a feature request.

Since in Linux Alt-Key is the default and almost a standard de facto for many functions in almost every desktop environment (alt+f1, alt+f7 and especially alt+f2) it would be nice to have option to reassign Alt in Far for example to super (win) or some other key to avoid conflicts with Window Managers and DEs.

**Comment by elfmz** [comment]
Since WIn key is not used in original FAR at all i just made it work as Alt. No reassign, just both keys works same. Check if its ok.

**Comment by invy** [comment]
Well, it's kinda topic for discussion and there is no definitive answer I think.

Left-win for example isn't working either, because gnome-shell(and I think bunch of other DEs) is using it for overview mode/search/lenses/menus. The right-win is working fine, which is however less convenient (or even not and it simply feels different), but at least it allows to use those shortcuts, where alt is involved.

What do you think? Because you've started porting and one of the reasons for this port, as I recall, were terrible MC shortcuts in ncurses :)

**Comment by elfmz** [comment]
Shortcuts always shortcuts, if someone prefer use left Win/Alt for FAR - he may change X manager configuration to avoid clashing.
However there is heavy artillery behind ( http://linux.die.net/man/3/xgrabkeyboard ) but I don't think its a case for it..

**Comment by invy** [comment]
The problem with DE shortcuts is, that it's not always possible to override them, for example Unity or Gnome shell provide very limited means of customization.

You are translating your keyboard input from your window to Far anyway, so it's possible to make this translation table configurable and not hard-coded.

**Comment by elfmz** [comment]
not sure about unity, but dconf-editor easily reassign any gnome shortcut, including those Alt+f1/Alt+f2 I'm working in gnome and was able to reassign all of this.
Anyway possibility of configurable keyboard translation makes sense, but its not urgent..

**Comment by volth** [comment]
I am strongly for xgrabkeyboard.
May be not as default, but it would be very convinient when one cannot reconfigure WM hotkeys (not my machine, but a remote server accessible via VNC) or when strange issues happen (XFCE due to its bugs may silenly reassign Ctrl-Fx back to their default actions).

**Comment by lieff** [comment]
Надо бы вообще для системозависимых вещей сделать что-то типа бэкэндов. Чтобы рисование консоли, клаву и мышку можно было бы реимплементировать на разных фреймворках и это небыло проблемой.

**Comment by volth** [comment]
кстати Alt-F4 в Far не работает, даже будучи отключеной в настройках XFCE; 
хоть XFCE окно и не закрывает, но похоже все равно эту комбинацию продолжает перехватывать до Far'а.

**Comment by invy** [comment]
I think, xorg tools should not come in question, because there is also the wayland (I should actually test Far on wayland someday). The most logical ans simplest solution is to make all keyboard mappings configurable in the winport console.

**Comment by volth** [comment]
there should be a portable way to capture keyboard.
perhaps libsdl or another game library.
also https://github.com/FreeRDP/FreeRDP captures almost whole keyboard

**Comment by invy** [comment]
And then you wont be able to switch keyboard layouts, copy characters, switch virtual desktops, using tiling and so on.

**Comment by volth** [comment]
How about ```XGrabKey``` only for the keys used by Far2L and only when its window has focus ?

**Comment by unxed** [comment]
Do we need this issue still open?

**Comment by invy** [comment]
Yep. It's actually got worse since new ubuntu release. Right Win does not work anymore (because gnome-shell grabs this key combination).

**Comment by volth** [comment]
мда, с ```XGrabKey``` не хорошо получается, если оконный менеджер или другая программа уже захватили какую-то комбинацию клавиш, то у них её не отнять, даже на время ([тут похожая проблема](https://github.com/goldendict/goldendict/issues/359)).

**Comment by volth** [comment]
С ```XGrabKeyboard``` тоже нехорошо.

Программы вроде freerdp прекращают перехват клавиатуры по ```LeaveNotify```, то есть при выходе курсора мыши за пределы окна. Мышь над окном - клавиатура перехватывается, мышь вышла - перехватывать перестали. Если перехвать клавиатуры не прекращать, то окна (все!) не получится таскать за заголовок. Мышью. Вот так странно всё повязано. Проверил в xfce и icewm.

Если в фаре сделать как в freerdp, то получится, что Alt-F7 работает, в зависимости от того, где курсор мыши, над окном фаре или нет...

**Comment by lieff** [comment]
А вот Remmina - все норм перехватывает и когда курсор не над экраном.

**Comment by volth** [comment]
разве? это же вроде всего лишь запускалка для freerdp?
у меня например Alt-Tab переключает локальные окна когда курсор не над окном freerdp, и окна на rdp-сервере, когда курсор над ним.

**Comment by volth** [comment]
```XGrabKeyboard``` с пересылкой ненужных фару горячих клавиш (вроде alt-tab) в root-окно через ```XSendEvent``` работает, и поведение стало похоже на виндовое (например Alt-F4 нажатое в фаре запускает редактор, а в нажатое в любой другой программе перехватывается WMом и закрывает окно).

Остаётся вопрос отпускать ли grab при уходе курсора мыши с фара:
* если да, то что произойдёт по Alt-F4 зависит от положения курсора мыши - над фаром или нет, а это.. несколько странное поведение (хотя в freerdp/remmina именно так - если курсор над окном, Alt-F4 закроет окно на удалённом комьютере, если не надо окном - закроется окно самой remmina; и это не фича, это результат вынужденного выбора между плохим и плохим). 
* если нет - то окно фара не будет таскаться мышью (т.к. вложенные ```XGrabKeyboard``` xserver не умеет), что тоже странно.

ну и  решение несколько хакерское.

По хорошему надо бы окну фара ставить какой-нибудь property (_NET_WM_DONT_GRAB_MY_KEYS="Alt-F4 Alt-F7 Alt-F8 Alt-F9 Alt-F10 Alt-F11 Alt-F12") и патчить WMы чтобы они в это property смотрели и соблюдали. 
Но их много разных и думаю не во все получится такой патч протащить.

**Comment by lieff** [comment]
Ну вот я проверил - у меня так. Может это и не в freerdp\Remmina дело, а что-то другое в системе различается у нас, убунта 16.04.

**Comment by volth** [comment]
а Window Manager какой?

**Comment by lieff** [comment]
Все по дефолту. Compiz как я понимаю используется, в процессах он есть.

**Comment by elfmz** [comment]
did you try that: https://askubuntu.com/questions/126817/how-to-disable-alt-f1-alt-f2-shortcuts ?

**Comment by asimonov** [comment]
thanks! what worked is running 'ccsm' and disabling 'key to give focus to launcher' and few others mentioned in that link.

**Comment by unxed** [comment]
> Since WIn key is not used in original FAR at all i just made it work as Alt. No reassign, just both keys works same. Check if its ok.

Do we still need this open?

**Comment by ivanhub** [comment]
Why nobody nowhere told this. Options->Interface Settings->Exclusively handle hotkeys that include. I ticked Alt, and voila now Alt is intercepted by Far, not by Window Manager. I think this topic now should be closed then.. )

**Comment by cmdorexe** [comment]
Do we still need this open?
