### ISSUE TITLE
Editor Autocomplete not working

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#602]
<Tab> works as plain <Tab> instead of accepting autocomplete.
What am I doing wrong?

**Comment by elfmz** [comment]
did you enable it?

**Comment by unxed** [comment]
Autocomplete is enabled and is showing suggestions. Should I explicitly enable <Tab> as suggestion accept key somehow?

**Comment by elfmz** [comment]
for me tab works perfectly.. something specific for your env is missing

**Comment by elfmz** [comment]
may be you have num lock/scroll lock on? (and dont ask me why editor autocomplete works so, dunno if it feature or bug)

**Comment by unxed** [comment]
Num lock issue, thanks! Could not imagine that num lock can affect tab.

**Comment by elfmz** [comment]
ping 2 https://github.com/MikeMirzayanov
