### ISSUE TITLE
Netrocks copying dialog: remaining time bounces wildly

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#607]
I'm copying a big directory over SFTP. The process has been running for 20 min now.
Yet, "Total ... Remaining time" bounces between 2 min and 20 min. 
I expect it to change in a more smooth manner, given that Netrocks now has enough statistics on this particular connection.

**Comment by elfmz** [comment]
It uses 'current' speed (measured on few seconds) for calculating remaining time, its from point of view that connection speed may change producing wrong estimation.
May be need to take another speed, like on last minute window. But its bit more complex to code..

**Comment by singalen** [comment]
Ideally, I envision a moving average.
Shouldn't be TOO hard to code, here are some acceptable approaches: https://stackoverflow.com/questions/10990618/calculate-rolling-moving-average-in-c

**Comment by elfmz** [comment]
check now

**Comment by elfmz** [comment]
so, is it ok now?

**Comment by singalen** [comment]
Please give me a couple more days, I’m traveling.

**Comment by singalen** [comment]
Cannot build Far2l now 8( Looks like there's a circular dependency between `WinPort` and `utils`. Both depend on each other's headers (this is bearable, but still dirty), but now `utils` requires:

```Undefined symbols for architecture x86_64:
  "_GetPathTranslationPrefix", referenced from:
      TranslateInstallPath(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> >&, wchar_t const*, wchar_t const*) in InstallPath.cpp.o
  "_GetPathTranslationPrefixA", referenced from:
      TranslateInstallPath(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, char const*, char const*) in InstallPath.cpp.o
  "_WINPORT_GetConsoleScreenBufferInfo", referenced from:
      SavedScreen::SavedScreen() in SavedScreen.cpp.o
  "_WINPORT_ReadConsoleOutput", referenced from:
      SavedScreen::SavedScreen() in SavedScreen.cpp.o
  "_WINPORT_SetConsoleCursorPosition", referenced from:
      SavedScreen::Restore() in SavedScreen.cpp.o
  "_WINPORT_SetConsoleTextAttribute", referenced from:
      SavedScreen::Restore() in SavedScreen.cpp.o
  "_WINPORT_WriteConsoleOutput", referenced from:
      SavedScreen::Restore() in SavedScreen.cpp.o
```

**Comment by elfmz** [comment]
ugh, but SavedScreen is there for quite a long time, and osx builds both on my test osx and Travis
are you following described for OSX build or has something own?

**Comment by elfmz** [comment]
GetPathTranslationPrefix also used in such way for quite long time

**Comment by elfmz** [comment]
anyway circular dependencies are bad thing, so i've resolved them - try now

**Comment by elfmz** [comment]
дык че с багом-то?

**Comment by singalen** [comment]
Feels much better, thank you very much!

**Comment by singalen** [comment]
...not only better. Just tested it on a directory with a lot of files, sizes varying from Kb to Gb.
The moving average in the estimated time works beautifully!
