### ISSUE TITLE
Netrocks copying dialog: use traditional Far bar characters instead of #, don't use input box

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#608]
The "copying" dialog is aesthetically rough. Unlike the local "copying", its progress bars are using '#' symbols to fill it.
Also, the file being copied is shown in an input box, with cursor and and block selection. It's not a very valuable feature to be able to select the current file name and copy it during the copying process. I would expect a simple text label.

**Comment by elfmz** [comment]
oh, that Apple users...

**Comment by elfmz** [comment]
fixed by https://github.com/elfmz/far2l/commit/780f1d90419bc880c3d056353d4a258be1f3945f
