### ISSUE TITLE
В консольном режиме клавиша BackSpace меняет режим отображения скрытых файлов

### ISSUE THREAD

**Issue by itspec-ru** [elfmz/far2l#613]
При запуске консольного far2l (far2l --tty) в графическом окружении (DE, WM)
нажатие клавиши BackSpace меняет режим отображения скрытых файлов,
т.е. в настройках панели устанавливается/сбрасывается опция "Показывать скрытые и системные файлы".

В чистой консоли (без X'ов) такой странности не наблюдается.

**Comment by elfmz** [comment]
У меня как водится все работает норм.
Для уточнения - far2l --tty под каким эмулятором терминала запускался? Я проверял под xterm и gnome terminal - под обоими все ок.

**Comment by itspec-ru** [comment]
Использую i3wm на двух ПК (на работе и дома)  под gentoo linux, проблема присутствует.
Как выяснил позже  - проблема не в i3.

Пробовал в calculate linux с KDE  - проблемы нет, всё работает как надо.
Затем в той же системе я запустил xterm в голых X'ах и там запустил "far2l --tty"  - проблема есть.

На всякий случай уточняю по шагам, что я делал
1. xdm убрал из загрузки системы
2. в ~/.xinitrc прописал "exec xterm"
3. перезагрузил систему
4. выполнил startx
5. в запущенной сессии xterm выполнил "far2l --tty"
6. backspace вместо забоя символов в ком. строке, переключает режим отображения скрытых файлов

Т.е. получается, что в DE всё работает правильно, а в голом X - уже нет.

**Comment by elfmz** [comment]
Вобщем, показывание скрытых файлов вкл/выкл по Ctrl+H
И проблема похоже растет отсюда: https://superuser.com/questions/641095/bash-how-to-globally-fix-h-and-backspace-problems

**Comment by itspec-ru** [comment]
Спасибо за ссылку!
Проблему создаёт xterm. Решение нашёл здесь
[https://wiki.archlinux.org/index.php/Xterm#Fix_the_backspace_key](url)
Добавил в ~/.Xresources строки

```
xterm*vt100.backarrowKey: false
xterm*ttyModes: erase ^?
```

и с backspace проблема решилась.

Только, как оказалось, это не единственная проблема с xterm.
Ctrl+Enter не переносит имя файла в ком. строку. Но это уже другая история.

**Comment by itspec-ru** [comment]
Может быть стоит посмотреть как подобные проблемы решены в mc.
Там с xterm проблемы не возникают, ну или не в таких количествах.

**Comment by unxed** [comment]
> Использую i3wm на двух ПК (на работе и дома) под gentoo linux, проблема присутствует.

А нет ли у вас акутального ebuild для far2l, часом? На хабре [интересуются](https://habr.com/ru/post/524370/#comment_22206140) вот :)

**Comment by itspec-ru** [comment]
@unxed 
Вот путь к ebuild'у из моего оверлея
https://bitbucket.org/gentoo-overlay/itspec/src/master/app-misc/far2l/far2l-9999.ebuild
Собирается нормально. Но некоторое время назад после обновлений системы появились проблемы с сетевыми подключениями через NetRocs кажется по ssh,  сейчас точно не помню.
