### ISSUE TITLE
Ctrl + mouse wheel to change font size

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#617]
Typical way of changing zoom almost everywhere. Why not to adopt? :)

**Comment by elfmz** [comment]
'everywhere' - is in web browsers, text processors etc - in systems where content typically displayed in different fonts or even as images.
far is different beast - it has single font for all, and no images (yet). No need to lock ctrl+scroll for this rarely used functionality. It can be used for something else in future

**Comment by unxed** [comment]
Okay, it makes sense. Just hoped on this to test #611 implementation quickly)))
