### ISSUE TITLE
Mac: search in tar.gz archives finds nothing

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#618]
I search by file contents in a .tar.gz archive and the search finds nothing. Unpacking and searching the directory does find a file with a given line inside.

**Comment by singalen** [comment]
For example, if I download the https://github.com/elfmz/far2l/archive/master.zip file 
and search for "UnRAR" string, far2l finds it.
But if I unpack it and pack back with `tar czf far2l-master.tar.gz far2l-master`, and then go in and do the same search, it finds nothing.

**Comment by elfmz** [comment]
must be fixed since https://github.com/elfmz/far2l/commit/40e042052680650e2b5aa642485839c114b7db42

**Comment by singalen** [comment]
Fix confirmed, thanks!
Now, would love to see #422 fixed. Now, I cannot have an archive open on each panel, the first one opened is always broken. That's pretty critical, I think.
