### ISSUE TITLE
F5 and F6 reminders in the bottom of the screen make no sense after Ctrl+O is pressed

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#620]
...as whose keys actually do not work in full screen console mode. Same thing with some Ctrl/Alt/Shift F* combinations.

**Comment by singalen** [comment]
Sounds about right. Maybe Ctrl-O needs to also hide the keybar.

**Comment by unxed** [comment]
Some reminders, as F1-F4 and F7-F12 are still actual after Ctrl+O, btw. And we have Ctrl+B to hide reminders panel manually.
