### ISSUE TITLE
Can not launch far2l build B from far2l build A

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#623]
Assume we have two different far2l builds, A and B

1. Run far2l A
2. Try to launch far2l B from it (no matter how: by Enter or by ./far2l)
3. Another instance of far2l build A is launched instead

**Comment by elfmz** [comment]
not reproducible

**Comment by unxed** [comment]
Теперь и у меня воспроизводится. Ладно, снова словлю - буду смотреть условия.
