### ISSUE TITLE
(patch) avoid using unsupported characters in linux terminal

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#625]
no more ♦♦♦♦♦♦♦♦♦♦'s

[diff.patch.txt](https://github.com/elfmz/far2l/files/3828425/diff.patch.txt)

**Comment by unxed** [comment]
Added support for nested far2l

**Comment by elfmz** [comment]
FYI: there is -ag command line key to avoid using pseudographics at all in case of terminal issues

**Comment by unxed** [comment]
I know it, more of this, -ag's implementation was used as a reference.
Still ┌ ┘'s are slightly better and it's automated so no need to worry about terminal type :)

**Comment by elfmz** [comment]
but making it hardcoded this way prevents these characters to be shows on linux systems where/when they suddenly supported

**Comment by elfmz** [comment]
looks like /etc/default/console-setup is a key and run setupcon after changing it
PS found here: https://www.linux.com/tutorials/how-change-your-linux-console-fonts/

**Comment by unxed** [comment]
What font do you use? Terminus not helped with ♦'s, and Ubuntu Mono refuses to work :(

**Comment by elfmz** [comment]
Download some extended font from here: https://www.zap.org.au/projects/console-fonts-zap/
Like  https://www.zap.org.au/projects/console-fonts-zap/src/zap-ext-light16.psf
Then in Linux console, (but not SSH or other GUI terminal) enter directory where downloaded file and type command:
sudo setfont zap-ext-light16.psf
...voila!
More instructions here: https://www.zap.org.au/projects/console-fonts-zap/src/README

**Comment by elfmz** [comment]
BTW it still misses ╢╟ characters.. May be somewhere on internet there're fonts with them. Here is another fonts collection: http://v3.sk/~lkundrak/fonts/ - but i didnt try them. If you really want - it seems its possible to create own font set :) https://tset.de/psftools/index.html

**Comment by elfmz** [comment]
this one has also  ╢╟ - http://v3.sk/~lkundrak/fonts/kbd/fonts/Cyr_a8x14.psfu

**Comment by unxed** [comment]
Useful ones, thanks! Let's save them here: [Cyr_a8x14.zip](https://github.com/elfmz/far2l/files/3854695/Cyr_a8x14.zip) [Cyr_a8x16.zip](https://github.com/elfmz/far2l/files/3854696/Cyr_a8x16.zip)

**Comment by unxed** [comment]
Btw, it's a new fact for me what linux console itself can use only 256 or 512-characters fonts. So we will never reach there full unicode support, so closing in favour of #624 :)
