### ISSUE TITLE
Feature restoration: Custom file filter in viewer/editor

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#626]
Sometimes one needs to view files not the way they are, but after processing by some filter. 
Simplest example is `mc` not showing executable/library files directly, but the `file` output on them.

This is possible in original Far with the following viewer association:
`jad -p "!.!" | far.exe -v -`
or, in a later version, `far:edit < jad -p !.!` or `far:view < jad -p !.!`.

The former in far2l spawns a separate process (which is fine) in a separate window (which is worse). The latter prints "bash: far:view: command not found".

**Comment by elfmz** [comment]
about ELF files - far2l shows their information in different aspects by ctrl+pgdown, but it doesnt work on osx, cuz it uses not ELF (just need to implement)

**Comment by elfmz** [comment]
Its due to 'inside' plugin. It also displays information in same way about many document types, like doc, xls and even mp3. But needs different 3rd party utilities to be installed for that.

**Comment by elfmz** [comment]
After some investigation it seems first option is near to undoable, second is not really universal while there is far2l -v working option.. Suggest to use following command
`you command goes here > /tmp/$$ 2>&1; far2l -v /tmp/$$; rm /tmp/$$`
or wrap it as script

**Comment by elfmz** [comment]
Since -v - key is well-known and has own charm of oldschool far i made closest possible functionality for it, so now you can run following command:
far2l -v -"echo hello world" or whatever else instead of echo

**Comment by elfmz** [comment]
So, closing bug, reopen if something still missing
