### ISSUE TITLE
viewer wrap fails on this sample file

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#634]
[sample.txt](https://github.com/elfmz/far2l/files/3886701/sample.txt)

1. Open by F3
2. Enable wrap mode by F2
3. See line 2:
![Снимок экрана в 2019-11-25 16-03-39](https://user-images.githubusercontent.com/1151423/69542828-45969500-0f9d-11ea-82d4-ec4fa4313afb.png)

btw, mc does the same job well

**Comment by unxed** [comment]
Resolution is 1366x768, font is Ubuntu Mono Regular 16, full screen window size, viewing as UTF-8, wrap enabled.

![Снимок экрана в 2019-11-26 14-29-44](https://user-images.githubusercontent.com/1151423/69626201-36751d00-1059-11ea-8d17-50af56455550.png)

**Comment by elfmz** [comment]
Ugh. Its Shift+F2 wrap mode, but not simple F2. I didnt know about it at all:)

**Comment by unxed** [comment]
Holy shit, I forgot that! 99% after End key in viewer is also happening only in this mode.

**Comment by unxed** [comment]
Fixed now, thanks (514e5fac43533e529473f1c9327200aeacfd1f02 ?)
