### ISSUE TITLE
Inconsistency of rendering between tty in mate terminal and wx

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#635]
As you can see, mate terminal renders file list as bold (looks crappy, bold isn't intended to be used for whole text, but to highlight specific words in it), but wx far2l does not. Why? Font is set the same in both, Ubuntu Mono Regular 16.

![Снимок экрана в 2019-11-25 16-24-04](https://user-images.githubusercontent.com/1151423/69544188-43820580-0fa0-11ea-9cea-c5898930bbc2.png)

![Снимок экрана в 2019-11-25 16-24-01](https://user-images.githubusercontent.com/1151423/69544170-3c5af780-0fa0-11ea-9687-fa644e71cbbc.png)

**Comment by unxed** [comment]
mc does not render file list as bold in the same mate terminal, so not terminal issue:

![Снимок экрана в 2019-11-25 16-31-34](https://user-images.githubusercontent.com/1151423/69544587-184be600-0fa1-11ea-98ce-334acf703f32.png)

**Comment by alexshtin** [comment]
Same on Ubuntu 20.04.
