### ISSUE TITLE
unicode-символы с кодами больше \uFFFF показываются квадратиками

### ISSUE THREAD

**Issue by volth** [elfmz/far2l#64]
хотя wchat_t 32-битные, символы не влезающие в 16 бит показываются квадратиками (двойной ширины, как корейские буквы, в нынешнем master они уменьшены).

тестовый файл: http://www.fsd.it/pragmatapro/All_chars.txt
![screenshot_2016-09-10_20-22-07](https://cloud.githubusercontent.com/assets/508305/18413345/7be98f1c-7794-11e6-9f56-ea5e20a5e593.png)

**Comment by elfmz** [comment]
это тоже known так сказать issue

**Comment by volth** [comment]
в командной строке с такими буквами другая проблема:
```echo 𝔡``` правильно отображается, но роняет far2l при попытке такую команду выполнить (~/far2l/Build/far2l” terminated by signal SIGSEGV (Address boundary error)).

**Comment by volth** [comment]
во вьювере (F3) не работает PageUp на этом файле (http://www.fsd.it/pragmatapro/All_chars.txt)

**Comment by elfmz** [comment]
проверьте после https://github.com/elfmz/far2l/commit/5fb047051b2d4e8baaf46100079b7acdf34664df

**Comment by volth** [comment]
ага, работает
