### ISSUE TITLE
support OSC 52 clipboard access escape sequences

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#641]
https://sw.kovidgoyal.net/kitty/protocol-extensions.html#pasting-to-clipboard

https://github.com/mintty/mintty/issues/258#issue-85090271

**Comment by unxed** [comment]
Not very popular so far, though. But, at least, GNOME, KDE & Microsoft are discussing support of this in their terminals :)

https://bugzilla.gnome.org/show_bug.cgi?id=795774
https://bugs.kde.org/show_bug.cgi?id=372116
https://github.com/microsoft/terminal/issues/2946

**Comment by hh** [comment]
Yes please ;)

**Comment by unxed** [comment]
Windows Terminal already supports it. Its support would be a major improvement in user experience under WSL.

**Comment by unxed** [comment]
Supported in tty backend since 590747eceabf9ef5294f16fbb1680ab6b1d5eb09.
For VT there is separate issue, #1422.
Closing.
