### ISSUE TITLE
NetRocks

### ISSUE THREAD

**Issue by denisvmedia** [elfmz/far2l#643]
Is it possible for NetRocks to support sshagent? I now need either to enter the password for the server, or add the key manually and then enter the password for the key (or use an non-password key). All the options are out of normal workflow as for me. I tried googling and searching through the source, but found no solution. Is it actually possible? If not, are there any plans for that? On Windows NetBox supported pageant, but on mac we seem to be left alone. Or... are we?

**Comment by elfmz** [comment]
It looks possible, however me never used it so have question on how to implement it. From docs http://opennet.ru/base/sec/ssh_agent.txt.html and some examples of libssh it seems it needs SSH_AUTH_SOCK and SSH_AGENT_PID env variables to be defined in process that uses agent. 
Is it expected to be defined at far2l startup? Or i have to add fields in configuration window to specify that variables (then it must be annoying to set it up on each system boot)?

**Comment by denisvmedia** [comment]
I think only SSH_AUTH_SOCK is important. And yes, it should be set before far2l startup. So, here are the conditions:
- there should be "no password" mode selected
- there should be no private key explicitly provided
- there must be SSH_AUTH_SOCK set before far2l start
If all the conditions are met, then try to authenticate with the help of the ssh_agent.

Makes sense? :)

P.S. Если что-то потерялось в переводе, то могу изложить мысли по-русски :)

**Comment by elfmz** [comment]
попробуйте бранчу nr-ssh-agent, врядли это финальный код, просто проверить работает ли оно

**Comment by denisvmedia** [comment]
Работает! :)

**Comment by elfmz** [comment]
добавил опцию в настройках протокола, чтоб работало надо ее выбрать
