### ISSUE TITLE
Russian "е" and "ё" are sorted incorrectly in file list

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#644]
1. Open far2l
2. Create new folder
3. Enter it
4. Create 4 subfolders: "д", "е", "ё", "ж"
5. Make sure sort mode is "n"
6. Sort order will be "д", "ё", "е", "ж"

**Comment by elfmz** [comment]
Да косяк какой то в вайновском сравнении юникодных строк. Но похоже букву ё не любит не только вайн, поменял сравнение чтоб юзало системную wcs*cmp - иии, ё теперь оказалась в конце алфавита :)

**Comment by unxed** [comment]
Может, тикет в вайн запилить по поводу CompareString и "ё", раз уж нашли?))

**Comment by lieff** [comment]
Так все корректно wcs*cmp + 1251 кодировка: e4 - д, e5 - е, b8 - ё, e6 - ж. Вот оно и попало в конец.
А вот вайновское неожиданное, что по utf8 кодировке, что по кодепоинтам - ё должно быть в конце.

**Comment by elfmz** [comment]
Вощем после обновления вайнового кода вроде ё встала на своЁ место
Остались правда некоторые беспорядки в сравнении больших и малых букв, но ето уже другая история..

**Comment by unxed** [comment]
> некоторые беспорядки в сравнении больших и малых букв

Чёрт, и правда! Не замечал до этого. Тоже в вайне баг?

**Comment by elfmz** [comment]
не, это ошметки винды. Список файлов сортировался как case-insensitive
