### ISSUE TITLE
TreeList не работает

### ISSUE THREAD

**Issue by volth** [elfmz/far2l#65]
TreeList (Ctrl-T в панели), в попытках построить дерево каталогов, долго блуждает в /dev.
Потом Far2L падает.

Может быть запретить ему заходить в определённые каталоги ?
- ```/dev```
- ```/proc```
- ```/sys``` ?
- ```/run``` ?
- ```/home/.ecryptfs/$USER/.Private``` и ```/home/$USER/.Private``` (тут ничего интересного, большое количество зашифрованных файлов - столько же сколько в остальном $HOME - с именами вроде ```ECRYPTFS_FNEK_ENCRYPTED.FWa6EH8CuKRR.URHDQX3e6WK9v.YXYknq6723S5-PQZgwZFwq8appMI64U--```)
- ещё?

Из поиска по Alt-F7 эти каталоги тоже имеет смысл исключить.

**Comment by elfmz** [comment]
Исключил из поиска все, которые не S_IFREG 
Тупо выкидывать /proc не хотелось бы, бывают такие системы у которых там реальные файлы лежат)   Конкретнее - в QNX такое видел), это, конечно, экзотика, но..

**Comment by volth** [comment]
У меня Ctrl-T так и не заработал.
Судя по логу, Far бродит в каталогах вроде ```/dev/fd/7/proc/4276/cwd/``` пока не умрёт.

**Comment by elfmz** [comment]
Tree list now enumerates not from fs' root, but from another panel's current directory so it is usable now (showing tree of whole FS is baaad idea in Linux). Also symlink-induced recursion issues seems fixed - so closing bug.
