### ISSUE TITLE
far2l needs sudo to "see" modifiers (shift, alt, ctrl) in linux console (mc does not)

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#653]
Then I tried to dig into it, I saw TIOCLINUX 6 returning "operation not permitted" if not under sudo. But mc is successfully getting modifiers even without sudo. How?

Maybe some workaround is possible? :)

**Comment by unxed** [comment]
Even sample app like this:

```
#include <stdio.h>
#include <stdlib.h>

#include <sys/ioctl.h>

int main()
{
    char shift_state;

    shift_state = 6;
    if (ioctl(0, TIOCLINUX, &shift_state) < 0) {
            perror("ioctl TIOCLINUX 6 (get shift state)");
            exit(1);
    }
    printf("%x\n", shift_state);
    return 0;
}
```

is getting modifiers succesfully without sudo. Why in the hell far2l require special permissions?

**Comment by unxed** [comment]
Modifiers are checked within a thread not attached to TTY, maybe?

**Comment by elfmz** [comment]
It worked before. Before introducing detachable session (so far2l essentially detached from terminal).
And it still fork if start far2l with --mortal arg, that disables that functionality.
Will add check for being launched in TTY of linux terminal and dont run as detachable session in such case. It looks almost useless. Unless will find other solution.
