### ISSUE TITLE
[Mac] Multiarc: archiving into 7z with "Delete after archiving" fails with a wrong command line

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#655]
I have a default 7z command line settings. I added a custom argument to 7z: `-mx=9`.
When I check "Delete files after archiving", the command being executed is just `-mx=9`, and shell responds with `bash: -mx=9: command not found`.
When "Delete files after archiving" is unchecked, it works fine.

**Comment by elfmz** [comment]
Check - should be fixed now. Note that 7z archiver command lines may need to be reset, as fix based on changes in default command lines.

**Comment by singalen** [comment]
It works, thank you!
