### ISSUE TITLE
FTP plugin issue

### ISSUE THREAD

**Issue by asimonov** [elfmz/far2l#658]
I have just noticed strange behaviour in default FTP plugin.
When copying large file (140gb) in passive mode from plain vanilla FTP with password authentication it gets to the end of the file, just shy off the end.
Then waits for 10 seconds.
Then the progress bar drops from 100% to 0%.
And then it keeps downloading from 0%, appending to the files it just downloaded.
It may be some issue with how buffering and length checks work.
But there is definitely a bug there. I end up with files that are times bigger than the source.

PS:
Does NetRocks support plain old FTP? Or just SFTP?

**Comment by elfmz** [comment]
Just SFTP, i have idle plan in head to implement FTP too, but didnt have strong enough reason for that, since plain FTP plugin worked well for me

**Comment by asimonov** [comment]
Yes, but this server only supported FTP.
  
I ended up using standard ftp CLI
  
  
  
 ________________________________  
Kind Regards,
  
Alexey
  

      
  

  
  
>

**Comment by elfmz** [comment]
Now NetRocks supports FTP/FTPS (FTP-over-TLS), so closing, preassuming its fine now (dont have 140 gig file under hands...)
