### ISSUE TITLE
ubuntu 19 very slow loading

### ISSUE THREAD

**Issue by Serjaru** [elfmz/far2l#663]
Slow loading!
argv[0]='far2l' g_strFarModuleName='/usr/local/bin/far2l' translation_prefix='/usr/local/'

and wait, wait, wait............. and after 15-20 seconds showing far

**Comment by elfmz** [comment]
try run far2l with --nodetect argument

**Comment by elfmz** [comment]
Tried on ubuntu 19.04 - everything run smoothly: tried to start from menu, from defaults terminal and from xterm.
Please describe which terminal app are you using? And may be something else different from /install ubuntu 19 desktop/make far2l/make install far2l/open terminal/type far2l/hit enter

**Comment by kakadusha** [comment]
Same for me, 15-20 seconds to wait far window is finally appear.
I'm using keyboard shortcut to start it: "far2l --nodetect" or "far2l" has the same effect for me. Same if i pick Far from menu applet.
Starting from console it displays:
> argv[0]='far2l' g_strFarModuleName='/usr/lib/far2l/far2l' translation_prefix=''

**Comment by elfmz** [comment]
Please do following. 
1 Close all far2l-s and to ensure that do: sudo killall far2l 
2 Run far2l and before it actually started quickly...:
3 Execute in terminal (prepare it before, to ensure no sudo password prompt and other things that can delay you):
`sudo ps -eL |grep far2l|awk '{ print $2; system("sudo cat /proc/"$2"/stack"); }'`

**Comment by elfmz** [comment]
..and report here output of course. And even better repeat above steps few times and report all ouput of all attempts.

**Comment by elfmz** [comment]
please:
- run:  gdb far2l
- type in appeared prompt: run
- wait couple seconds and hit Ctrl+C
- enter following command: 'thread apply all bt'
- report here full output of that command (it may ask ype <RET> for more, q to quit, c to continue without paging - hit 'c' in such cases to see full output)

Reepeat above few times with different delays before Ctrl+C - from 2 seconds to 10. Report all output of all attempts

**Comment by kakadusha** [comment]
> Reepeat above few times with different delays before Ctrl+C - from 2 seconds to 10. Report all output of all attempts

Attached file with 3 attempts: 

- first: till far full start
- second: about 5 seconds
- third: about 10 seconds

**Comment by kakadusha** [comment]
Also i made it on my work PS (file attached), here it starts fast as crazy frog :) 
[far-debug-663-noproblemshere.txt](https://github.com/elfmz/far2l/files/4275010/far-debug-663-noproblemshere.txt)

**Comment by elfmz** [comment]
Looks very similar to https://github.com/keepassxreboot/keepassxc/issues/3789
..that subsequently points to https://bugs.launchpad.net/ubuntu/+source/dbus/+bug/1852016

So, do suggested there solution:
`Install "sudo apt-get install appmenu-gtk2-module" and restart.`

**Comment by qxov** [comment]
Ubuntu 19.10 amd64
"far2l --tty" starts instantly
"far2l" - about 20-30 secs

strace far2l:
```
...
sendto(12, "NEGOTIATE_UNIX_FD\r\n", 19, MSG_NOSIGNAL, NULL, 0) = 19
recvfrom(12, 0x55de37ccf820, 4096, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=12, events=POLLIN}], 1, -1)   = 1 ([{fd=12, revents=POLLIN}])
recvfrom(12, "AGREE_UNIX_FD\r\n", 4096, 0, NULL, NULL) = 15
sendto(12, "BEGIN\r\n", 7, MSG_NOSIGNAL, NULL, 0) = 7
write(15, "\1\0\0\0\0\0\0\0", 8)        = 8
eventfd2(0, EFD_CLOEXEC|EFD_NONBLOCK)   = 14
write(14, "\1\0\0\0\0\0\0\0", 8)        = 8
write(15, "\1\0\0\0\0\0\0\0", 8)        = 8
poll([{fd=14, events=POLLIN}], 1, 25000) = 1 ([{fd=14, revents=POLLIN}])
read(14, "\1\0\0\0\0\0\0\0", 16)        = 8
poll([{fd=14, events=POLLIN}], 1, 25000) = 0 (Timeout) <----------- and waits here for 25 secs
write(14, "\1\0\0\0\0\0\0\0", 8)        = 8
futex(0x55de37ccf9b0, FUTEX_WAKE_PRIVATE, 2147483647) = 0
close(14)                               = 0
.....

```

**Comment by elfmz** [comment]
so, didnt you try 'sudo apt-get install appmenu-gtk2-module' and restart?

**Comment by qxov** [comment]
Yes, I installed appmenu-gtk2-module and some other packages yesterday, but I rebooted my PC only few hours ago.
Now everything is ok.

JFYI (yesterday, before installing packages):
$ far2l <--- 25 sec delay
# far2l <--- no delay

Thanks

**Comment by elfmz** [comment]
Useful info, that reboot is needed.
