### ISSUE TITLE
macOs package needed

### ISSUE THREAD

**Issue by ADDubovik** [elfmz/far2l#664]
It would be much more convenient to have far2l as macOs .app bundle with Info.plist file included.

There's several significant limitations because of current non-macOs-friendly form:
- it's impossible to start more then one far2l instance from dock or from Applications folder;
- it's impossible to add keyboard shortcuts for far2l. It's an extremely inconvenient with Apple TouchBar-equipped hardware: there's no way to switch TouchBar to F1-F12 automatically when far2l is active. So, user should make a choice: always have F1-F12 keys for all applications (it's inconvenient with macOs-friendly apps), or use Fn key with far2l.

**Comment by inikolaev** [comment]
I have started working on some proofs concept macOS bundle, but haven't completed it. So if anyone wants to move forward with it you can find it int this repo: https://github.com/inikolaev/far-macos-bundle

Basically I think it works if all the binaries are copied into `Far.app/Contents/MacOS/` - at least this is how it's installed on my machine, but I don't remember if it still references any libraries outside bundle.

**Comment by ADDubovik** [comment]
It seems that the right way is to use CMake CPack utility with "DragNDrop" generator:
https://gitlab.kitware.com/cmake/community/-/wikis/doc/cpack/PackageGenerators

I have never used it before.

**Comment by singalen** [comment]
Related (duplicates?): #332.

**Comment by elfmz** [comment]
is it fixed now (since https://github.com/elfmz/far2l/pull/749 ) ?

**Comment by singalen** [comment]
The title issue is fixed. 
The body, though, asks for a very different things, one of which is a pretty great point - launching multiple instances from Dock, which is now impossible, and it's a big inconvenience.
This would require more code, though.

**Comment by singalen** [comment]
Now, I believe, this one can be closed.

**Comment by elfmz** [comment]
all seems fixed now
