### ISSUE TITLE
An asterisk for executable files, a slash for directories

### ISSUE THREAD

**Issue by lingvoboard** [elfmz/far2l#669]
There is one feature that **Midnight Commander** has that **far2l** doesn't:

> An asterisk for executable files, a slash for directories, an at-sign for links, an equal sign for sockets, a hyphen for character devices, a plus sign for block devices, a pipe for fifos, a tilde for symbolic links to directories and an exlamation mark for stalled symlinks (links that point nowhere).

far2l:
![far2l](https://i.postimg.cc/x82x7zwh/Screenshot-20200201-094257.png)

mc:
![mc](https://i.postimg.cc/QChmSr5r/Screenshot-20200201-0942572.png)

It would be nice if far2l has this feature at least for directories and executables (/ and *)

(executables - permission based (??x??x??x))

**Comment by bitraid** [comment]
You can configure Far to have any marking character for any highlight group: From `Options` - `Files highlighting and sort groups`, edit or create the group you like, and set the `Optional marking character`.

**Comment by lingvoboard** [comment]
Thank you, **bitraid**
I have found the way to set up this feature

Result (far2l):
![far2l](https://i.postimg.cc/pr42g8bf/far2l.png)
