### ISSUE TITLE
Поиск по Alt+пробел больше не работает?

### ISSUE THREAD

**Issue by itspec-ru** [elfmz/far2l#670]
После обновления перестал работать поиск по Alt+пробел.
Похоже это связано с этим коммитом 0f7a61229fd50976f29d221f48de76375410323a [](https://github.com/elfmz/far2l/commit/0f7a61229fd50976f29d221f48de76375410323a).
Или так и было задумано? Было бы не плохо сохранить поведение Alt+пробел при использовании wx 3.0. А ещё лучще это поведение сделать опциональным/настраиваемым (м.б. даже настройка горячих клавиш).

**Comment by elfmz** [comment]
какая ось (у вас вроде osx?) и wx widgets? у меня и в линухе и в тестовой осх поиск по альт-пробел работает

**Comment by itspec-ru** [comment]
Похоже проблема не в far'е, а что-то стало работать по-другому, похоже после обновлений системы.
Если я ничего не путаю, то раньше по Alt+пробел сразу открывалось окно "Поиск".
Сейчас у меня работает так:
жму Alt+пробел
окна "Поиск" НЕТ
только при наборе первого символа появляется окно "Поиск"

ОС: gentoo linux
wxGTK-3.0.4

**Comment by elfmz** [comment]
Ну, такое поведение аккурат начиная с https://github.com/elfmz/far2l/issues/594

**Comment by itspec-ru** [comment]
Ну да, начиная с [#594](https://github.com/elfmz/far2l/issues/594)
при нажатии Alt+пробел открывалось окно "Поиск" в котором можно было набирать строку_поиска (в том числе и на кириллице)

сейчас у меня по Alt+пробел окно "Поиск" НЕ ОТКРЫВАЕТСЯ
оно появляется только после "Alt+пробел, первый_символ_строки_поиска"
т.е. жму Alt+пробел, отпускаю (окна "Поиск" нет)
затем начинаю набирать строку поиска
и только тогда появляется окно "Поиск"
