### ISSUE TITLE
Travis Linux jobs fail because compiler is no available.

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#673]
The compiler version is no longer packaged with the distro, so Travis fails like this:

```
E: Unable to locate package g++-4.9
E: Couldn't find any package by glob 'g++-4.9'
E: Couldn't find any package by regex 'g++-4.9'
apt-get.diagnostics
apt-get install failed
```

```
The following packages have unmet dependencies:
 clang-3.6 : Depends: libclang1-3.6 (= 1:3.6.2~svn240577-1~exp1) but it is not going to be installed
             Depends: libllvm3.6 but it is not going to be installed
             Depends: libstdc++6 (>= 4.9) but 4.8.4-2ubuntu1~14.04.3 is to be installed
             Depends: libstdc++-4.9-dev but it is not installable
             Depends: libgcc-4.9-dev but it is not installable
             Depends: libobjc-4.9-dev but it is not installable
             Depends: libclang-common-3.6-dev (= 1:3.6.2~svn240577-1~exp1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
apt-get.diagnostics
apt-get install failed
```

BTW isn't it time to use `gcc 9`?

**Comment by elfmz** [comment]
but.. it works: https://travis-ci.org/elfmz/far2l/builds/657018086
or i misunderstanding something?

**Comment by singalen** [comment]
Sorry for false alarm, if so... what went wrong with this PR now?
https://travis-ci.org/elfmz/far2l/builds/654715477?utm_source=github_status&utm_medium=notification

https://github.com/elfmz/far2l/pull/529

**Comment by elfmz** [comment]
Some temporary failure. It happens with Travis from time to time.
There was however recently issue with Travis, but it was on OSX config and caused by python, but not gcc, and fixed by this: https://github.com/elfmz/far2l/commit/4a3b555cf914ff219fc9f2c29c0490172ecae2c3

**Comment by singalen** [comment]
Alright, thanks. Will re-submit and see.
