### ISSUE TITLE
Shell integration: advanced autocomplete

### ISSUE THREAD

**Issue by invy** [elfmz/far2l#68]
Far shell is almost unusable without normal auto complete like in zsh or at least bash.
I miss possibility to auto complete:
 * parameters (I.e. mount -t v TAB (or some other key, I think there was an extension long ago, which used '`' character) should autocomplete available filesystem starting with 'v')
 * repository objects (commits, tags, branches)
 * etc

**Comment by volth** [comment]
It could be a better option to fork/copy completion code from bash instead of sending \t to a running bash instance.
In this case the list of all the completion options will be available, and they could be displayed in Far's scrollable list, without any weird interation like "Display all 2355 possibilities? (y or n)" and need to press [Tab] dozen times.

**Comment by invy** [comment]
> It could be a better option to fork/copy completion code from bash
Bad Idea, because it contradicts DRY principle. And also bash has not the best auto completion.
> In this case the list of all the completion options will be available at once, and they could be displayed in Far's scrollable list, without weird interations like "Display all 2355 possibilities? (y or n)" and without need to press/simulate [Tab] dozen times.
It's not the "weird interaction", but the very good design decision from the bash developers.
 - What happens when user occasionally presses TAB? Would you flood him with the results he doesn't want?
 - The interaction is intended to make user to think, whether he needs to narrow down his 'search request'.

**Comment by lieff** [comment]
А если не баш то что лучшее для auto completion?
Вроде как только у него и настроены системные /etc/bash_completion[.d]. Али что то еще есть распространенное?

**Comment by invy** [comment]
zsh же

**Comment by lieff** [comment]
По коду я смотрю оно башевские тоже подцепляет + вроде как что-то свое есть. Только где у него свое лежит?

**Comment by volth** [comment]
@invy для bash - с его необходимостью работать через самый простой терминал, который не поддерживает никакие ascii-последовательности управления курсором - это лучшее решение, да.
Но в Far уже есть дизайн автокомлита в виде списка со скроллбаром, и в нём нет проблемы с флудом:
[картинка]

**Comment by invy** [comment]
Я вот думаю, что такой автокомполит надо делать в виде плагина с возможностью прикрутить шелл, нравящийся пользователю.

**Comment by elfmz** [comment]
Display all .. possibilities? легко отключается. Сложнее синтегрится с фаровским списком..

**Comment by elfmz** [comment]
вроде сделал менюшку, но остался баг - дефолтовая хистори мешается - иногда они друг друга слегка лочат

**Comment by volth** [comment]
В фаровском списке ещё и History.
И он появляется сразу, без двойного [Tab] и уменьшается по мере дальшейшего печатания букв (или увеличивается при их стирании кнопкой backspace).

![xx2](https://cloud.githubusercontent.com/assets/508305/18502769/a282c966-7a48-11e6-89d6-32e41721c84c.png)

**Comment by elfmz** [comment]
seems can be closed

**Comment by invy** [comment]
autocompletion only works for paths, but not for command line options, branches, etc.

**Comment by elfmz** [comment]
by double-tab should work:
![screenshot from 2016-09-23 15-36-39](https://cloud.githubusercontent.com/assets/20957349/18785925/e6366b24-81a3-11e6-880d-3dcca49b27ef.png)

**Comment by invy** [comment]
Double tab doesn't work when panels are shown. We need different hotkey eventually.

**Comment by invy** [comment]
Also popup menu is preventing me from further input until I make a choice. Preffered behaviour: further input refines search and reduces amount of suggestions.

**Comment by elfmz** [comment]
Is there some contraindications for reserving also shift+tab for autocomplete that will also work with panels?

**Comment by invy** [comment]
At the moment I can't think of one. If it will conflict with something it can be reassigned.

**Comment by volth** [comment]
Those two autocompletions eventually should became one with best features from each.

The new bash-based autocompletion is smarter (knows names of git branches, etc) while the old Far's autocompletion allows to type refining search options and it shows history.
