### ISSUE TITLE
как установить на убунту 18?

### ISSUE THREAD

**Issue by dima734** [elfmz/far2l#683]
Я это сделал, че дальше???
~/far2l/build$ ls
align     CMakeCache.txt  cmake_install.cmake  compare   editcase    far2l   farlng     filecase  inside   Makefile  NetRocks      tmppanel  utils
autowrap  CMakeFiles      colorer              drawline  editorcomp  farftp  FARStdlib  incsrch   install  multiarc  SimpleIndent  tools     WinPort

==========================

Or simply on Ubuntu:

apt-get install gawk m4 libglib2.0-dev libwxgtk3.0-dev libssh-dev libsmbclient-dev libnfs-dev libneon27-dev cmake g++ git

Clone and Build

git clone https://github.com/elfmz/far2l
cd far2l
mkdir build
cd build

with make:

cmake -DUSEWX=yes -DCMAKE_BUILD_TYPE=Release ..
make -j4

**Comment by elfmz** [comment]
для начала попробовать запустить что собралось, находясь в билд директории выполнить: 
`./install/far2l`
если все ок можно установить в систему вот так:
`sudo make install`

**Comment by dima734** [comment]
привет. а можно мне получить роботу програмистом? я дизайнер сайтов... умею програмировать
