### ISSUE TITLE
Colorer freezes Far on a large files (~40M)

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#688]
1. Open a 40M text file in editor.
2. Go to the end.
3. Wait for 30-60s, until Colorer's parsing reaches the end of file.
Problem: Far freezes for ~20s.
Happens on Mac.
Dunno if this can be fixed.

**Comment by elfmz** [comment]
I don't know what was wrong in previous colorer, but fixed something in current one, that should much improve situation. So plz check now with your file/system.

**Comment by unxed** [comment]
А там ещё схему цветов colorer не выбрать нормально, кстати. Это и с предыдущим было

**Comment by singalen** [comment]
Seems to be fixed now!

**Comment by unxed** [comment]
> А там ещё схему цветов colorer не выбрать нормально, кстати. Это и с предыдущим было

Хм, я чёт не в самом подходящем месте написал про это, пожалуй :)
https://github.com/elfmz/far2l/issues/798
