### ISSUE TITLE
Update help on User menu - special symbols

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#691]
`!/` is still described as "Short name of current path", while it's actually the full current path.

Maybe it's time to finally drop the compatibility with DOS file names and remove this functionality?

**Comment by EugeneManushkin** [comment]
+1.
However the problem is deeper: simple macroses becomes not portable e.g.
```diff "!#!\!.!" "!^!\!.!"```

IMO the correct way to fix this is to make all short path symbols to return corresponding linux normal paths

**Comment by akruphi** [comment]
Done in #1697 This issue may be closed.
