### ISSUE TITLE
Kali Linux 2020.1b far2l blocks symbols ~ _

### ISSUE THREAD

**Issue by AxleUnix** [elfmz/far2l#693]
In Kali Linux 2020.1b far2l terminal blocks symbols ~ _ and some other. far2l under Ubuntu 20 haven't this problem. Is any way to fix this?

**Comment by AxleUnix** [comment]
Seems that nobody uses far2l under Kali :)

**Comment by elfmz** [comment]
little bit busy, but will try it out when have time

**Comment by elfmz** [comment]
I've:
- installed 2020.2 into vmware (sorry didn't find exact your version)
- sudo apt-get install gawk m4 libglib2.0-dev libwxgtk3.0-gtk3-dev libssh-dev libssl-dev libsmbclient-dev libnfs-dev libneon27-dev cmake g++ gitudo apt-get install gawk
- cloned and cmake'ed far2l with default config
- started far2l from applications menu
- started nano inside of far2l and typed there ~ and _ without problems

**Comment by AxleUnix** [comment]
Thanks for support! Apparently, the whole point is in my Kali version.

**Comment by elfmz** [comment]
I tested internal terminal of graphical (wx) far2l
From your recent words i understood that may be you was about far2l --tty and tested now it too. Well, ~ and _ works fine, but backspace key doesn't work. Thats also bad and may be have similar reason.
BTW is you problem reproduced on english layout or not (what if not?)?

**Comment by AxleUnix** [comment]
There is /etc/default/keyboard
XKBLAYOUT="us"
XKBVARIANT=""
XKBMODEL="pc102"
BACKSPACE="guess"
XKBOPTIONS=""

**Comment by elfmz** [comment]
/me had XKBMODEL="pc105" but changing it to pc102 didn't cause reproduction to happen..
Plz run in terminal: `FAR2L_STD=- far2`
that will run wx far2l but also it will output lots of debug into on terminal from where it started, try pressing those keys that not works and see the output, for instance thats what i have when pressing ~ and _:

> ConsoleInput::Enqueue: ~ 7e c0 10 DOWN
> ConsoleInput::Enqueue: ~ 7e c0 10 UP
> OnKeyUp: 7e 60 60 0 381252
> OnKeyDown: 7e 60 60 0 381612
> OnChar: 7e 7e 0 381612 _lk_ts=381612 _lk_enqueued=0
> ConsoleInput::Enqueue: ~ 7e c0 10 DOWN
> ConsoleInput::Enqueue: ~ 7e c0 10 UP
> OnKeyUp: 7e 60 60 0 381820
> OnKeyUp: ffe1 0 132 0 381924
> ConsoleInput::Enqueue: # 0 10 0 UP
> OnKeyDown: ffe1 0 132 0 383772
> ConsoleInput::Enqueue: # 0 10 10 DOWN
> OnKeyDown: 5f 2d 2d 0 384084
> OnChar: 5f 5f 0 384084 _lk_ts=384084 _lk_enqueued=0
> ConsoleInput::Enqueue: _ 5f bd 10 DOWN
> ConsoleInput::Enqueue: _ 5f bd 10 UP
>

**Comment by elfmz** [comment]
update: aren't you using Wayland instead of xorg? I just checked neighbor  issue #701 and found whole zoo of fancy input problem with Wayland. Including non-working ~ and _.

**Comment by AxleUnix** [comment]
yes, yes! it's on Wayland, you're right :)
