### ISSUE TITLE
build on WSL (ubuntu) fails with Python related errors

### ISSUE THREAD

**Issue by AleksandrSokolov** [elfmz/far2l#694]
The make asked to add  -DPYTHON=yes by message:

> CMake Warning at CMakeLists.txt:176 (message):
>   Python plugin not enabled by default, use -DPYTHON=yes if you really
>   want it
> 
After that to build I used:

sudo apt install python3-dev
sudo apt install python3-pip
pip3 install virtualenv
cmake -DUSEWX=yes -DCMAKE_BUILD_TYPE=Release -DPYTHON=yes ..

**Comment by AleksandrSokolov** [comment]
But still have message:

> CMake Warning at CMakeLists.txt:170 (message):
>   virtualenv not found, python plugin will not be built

**Comment by elfmz** [comment]
try install it by sudo apt install virtualenv

**Comment by elfmz** [comment]
reopen if still not works

**Comment by alexshtin** [comment]
Yes, this works. Update `README.md`?
