### ISSUE TITLE
Understanding what "Enter" does on files

### ISSUE THREAD

**Issue by luigimacedonia** [elfmz/far2l#696]
Sorry to post it here; didn't find a forum to ask.

If I press Enter on an archive file, the Archive Manager is open (can't navigate it like a directory)
If I press Enter on an associated-by-system file, it does nothing. Only the second time that I press enter on the file, the associated application is launched. My workaround for this last issue was add the extensions on the File Association menu so it can launch on a single enter.

OS: Mint 19.3

Thanks for this port; it is awesome.

**Comment by elfmz** [comment]
for non-executable files far2l starts https://github.com/elfmz/far2l/blob/master/far2l/bootstrap/open.sh that subsequently uses xdg-open (where it present)

**Comment by unxed** [comment]
can we close this now?
