### ISSUE TITLE
Strange messages when start far2l for WSL

### ISSUE THREAD

**Issue by AleksandrSokolov** [elfmz/far2l#697]
saa@LAPTOP-ASOKOLOV:~$ far2l
argv[0]='far2l' g_strFarModuleName='/home/saa/far2l/far2l' translation_prefix=''

Some far2l-s lost in space-time nearby:
 1: {/home/saa} - Far 2.2 20/04/12-9d869bf6-alpha x64 saa@LAPTOP-ASOKOLOV
 2: {/home/saa} - Far 2.2 20/04/12-9d869bf6-alpha x64 saa@LAPTOP-ASOKOLOV
Input instance index to revive or empty string to spawn new far2l

**Comment by elfmz** [comment]
Its a feature:)
When far2l runs in TTY mode and when controlling terminal closed then default far2l's behavior is not  to exit, but stay operating in background. Next time when some TTY far2l will be started it will see such backgrounded far2l's and prompt to activate in a way you can see.
If you dont like this you can start far2l with --mortal argument - then it will exit on terminal closing.
The reason for such behavior being on by default is that typically far2l started in TTY mode via SSH and that allows it to resemble 'screen''s functionality without using 'screen', cuz its incompatible with far2l TTY extensions.

**Comment by elfmz** [comment]
closing as its feature, but not bug
