### ISSUE TITLE
Mac: Copying to clipboard stopped working

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#698]
This may have something to do with MacOS 10.14.6 update, or wxWidgets, or something, but Cmd-C no longer copies text to clipboard.

`wxClipboardBackend::OnClipboardClose()` is called, then the call goes into `wxTheClipboard->SetData()`, but nothing appears in the clipboard.

Any other Mac users with such a problem?

**Comment by elfmz** [comment]
stupid question, but did you try reboot? i saw some strange issues on macos fixed by reboot, but not related to clipboard..

**Comment by singalen** [comment]
Yes, I did. It didn't help 8(
Other hotkeys stopped working for me before, funny - this only happened when there was a system update pending (installed but not rebooted). But this is a different case, far receives a keystroke but wx doesn't connect the text to the system clipboard.

**Comment by elfmz** [comment]
also does it work in reverse direction - pasting works?

**Comment by singalen** [comment]
Pasting works.

**Comment by elfmz** [comment]
i created branch with some extra logging: https://github.com/elfmz/far2l/tree/debug-clipbrd
build and run it like this:
FAR2L_STD=- ./install/far2l 2>&1 | grep -i clipboard

**Comment by singalen** [comment]
Thank you very much.

```
OnKeyDown: 37 0 134 0 590972481
13:36:31: Debug: Unrecognised keycode 364
13:36:31: Debug: Unrecognised keycode 365
ConsoleInput::Enqueue: # 0 11 8 DOWN
OnKeyDown: 8 43 43 0 590973097
13:36:31: Debug: Unrecognised keycode 364
13:36:31: Debug: Unrecognised keycode 365
OnChar: 43 43 0 590973097 _lk_ts=590973097 _lk_enqueued=0
13:36:31: Debug: Unrecognised keycode 364
13:36:31: Debug: Unrecognised keycode 365
ConsoleInput::Enqueue: C 43 43 8 DOWN
ConsoleInput::Enqueue: C 43 43 8 UP
OpenClipboard
OnClipboardEmpty: dispatching into main thread...
EmptyClipboard: Clear
SetClipboardData: dispatching into main thread...
SetClipboardData: 13
OnClipboardClose: dispatching into main thread...
OnClipboardClose
OnClipboardClose: SetData result=1 prim_selection=0
OnClipboardClose: Flush result=0
```
`wxTheClipboard->SetData()` returned `true`. Not sure what primary selection means.

**Comment by elfmz** [comment]
I see its time to update my hackintosh..

**Comment by singalen** [comment]
I'm not sure this will reproduce it. I would seek other users that can confirm it first.
I'm building off MacPorts, it's a rare environment.

**Comment by elfmz** [comment]
hm, can you describe your build process, for dummies?

**Comment by elfmz** [comment]
see what i suddenly found: https://forums.wxwidgets.org/viewtopic.php?f=23&t=47041&sid=786e6ffc0d5adce4494aba12381388af

**Comment by singalen** [comment]
Yay! I did my search, but somehow didn't find this one. Thanks!

**Comment by singalen** [comment]
For reference, wx upsteam fix: https://github.com/wxWidgets/wxWidgets/pull/1623/files.

**Comment by singalen** [comment]
I made a sorta redneck fix, do you want a pull request? https://github.com/singalen/far2l/commit/72a9a0db804e86d87c2f2f7c58903d1dc965d2e6

**Comment by elfmz** [comment]
uf, its too rednecked. Even not considering this as problem, it will crash if wx sources will change change changing layout some of that objects.
Just need to update wx as i understand, dont need to hack it.

**Comment by singalen** [comment]
Things to consider:
* this bug is in wx 3.1 release (not sure about exact number);
* wx 3.2 or any other version with a fix is not released;
* what's the probability of a change in a deep system header within release 3.1? I estimate it as a pretty low.
Maybe it's worth reconsidering when we know exactly which release the bug was introduced in and where it was fixed.

**Comment by elfmz** [comment]
i'd suggest instead of hacking wx - write string value into osx clipboard directly, like described here  https://stackoverflow.com/questions/3655038/how-to-copy-textfield-to-osx-clipboard
and ifdef that code to be used with particular wx version

**Comment by singalen** [comment]
You're right! Why didn't I think of it.
