### ISSUE TITLE
Через Х на удаленке через VPN лагает.

### ISSUE THREAD

**Issue by AlekseyShi** [elfmz/far2l#703]
Использую в MobaXterm, в котором есть свой X. Очень удобно. 
Но именно far2l через X в нем сильно тормозит, по удаленке через VPN. Если устройство локально в сети то тормозов особых не наблюдается.
Причем другие приложения Х по удаленке не тормозят, даже Qt Creator нормально. А far2l вообще невозможно работать, отклик нажатия кнопок сильно лагает.

**Comment by elfmz** [comment]
ща попробуйте

**Comment by AlekseyShi** [comment]
> ща попробуйте

Спасибо. Стало поживее. :)

**Comment by elfmz** [comment]
имеет смысл еще отключить сглаживание шрифтов - F9/Options/Interface - Disable antialiasing
