### ISSUE TITLE
far2l's editor refuses to copy/paste some characters

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#704]
This one, for example: `🐾`

**Comment by elfmz** [comment]
For me this char copypasted perfectly. Tried wx and tty versions. Some info missing..

**Comment by unxed** [comment]
wx version, linux mint x64 MATE edition 19.3
maybe building with/without libwxgtk3.0-gtk3-dev matters? mint 19.3 is ubuntu 18.04 equivalent

**Comment by elfmz** [comment]
still no,
may be it depends on whole file? can you share some?

**Comment by unxed** [comment]
[sample.txt](https://github.com/elfmz/far2l/files/4754546/sample.txt)

**Comment by elfmz** [comment]
As you can guess, still no repro.
Did you try on different system? may be something specific in your far2l settings? Can you try on default settings (close all far2l-s -> rename ~/.config/far2l to far2l.bak -> start far2l and check. Then revert settings from backup in  same way)

**Comment by unxed** [comment]
Tried with clean config, same behavior. Will try on another systems when I have time.

**Comment by elfmz** [comment]
Funny, now i played bit more with TTY version and got  really weird behaviour when copypasting char in you sample file.
Char however copypasted fine, jist rendered incorrectly. Whats most interesting is that reproduced in far2l in plain terminal. In far2l-in-wx-far2l and in standalone wx far2l still all fine.

**Comment by unxed** [comment]
One more interesting detail: it copypastes ok from google ("cat paw unicode", 1st link), but refuses to copypaste from this page (both tries from Firefox).

But when i open this page in Chrome, copying/pasting this char from this page works fine.

Maybe firefox sends this char to clipboard in some weird way?

**Comment by unxed** [comment]
This char is copied/pasted ok then I copy/paste it as a part of some string.
And refuses to paste when I copy single char itself!

**Comment by unxed** [comment]
Not using MATE any more. If anyone encounters this bug again, please ask to reopen.
