### ISSUE TITLE
editor processes some chars wrongly

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#708]
1. Open attached file with far2l's editor
2. Go to the end of a line (press "end" key for example)
3. Try to erase entire line by pressing "backspace" multiple times and see what happens.
[sample.txt](https://github.com/elfmz/far2l/files/4742115/sample.txt)

**Comment by unxed** [comment]
Yet another sample. Try to open it in viewer and editor and compare results.

[out.log](https://github.com/elfmz/far2l/files/4742120/out.log)

**Comment by elfmz** [comment]
Thats not UTF8 files, if they being edited as UTF8 editor tries to make best effort to represent wrong encoding as UTF8, so while deleting or doing something else different characters may become invalid/valid.
Switch to any single-byte codepage and that special effects will go away

**Comment by unxed** [comment]
Closing as "not a bug" if so.
