### ISSUE TITLE
multiarc: use system locale to select ANSI/OEM code pages for non-UTF8 zip files 

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#715]
See zip.cpp, starting from [here](https://github.com/elfmz/far2l/blob/master/multiarc/src/formats/zip/zip.cpp#L314)

```
  if (ZipHeader.Flags&0x800) { // Bit 11 - language encoding flag (EFS) - means filename&comment fields are UTF8
  } else if (ZipHeader.PackOS==11 && ZipHeader.PackVer>20 && ZipHeader.PackVer<25)
    CPToUTF8(CP_ACP, Item->FindData.cFileName,Item->FindData.cFileName, ARRAYSIZE(Item->FindData.cFileName));
  else if (ZipHeader.PackOS==11 || ZipHeader.PackOS==0)
    CPToUTF8(CP_OEMCP, Item->FindData.cFileName, Item->FindData.cFileName, ARRAYSIZE(Item->FindData.cFileName));
```

This code assumes .zip file has cyrillic encoding, as we have CP_ACP and CP_OEMCP [hardcoded](https://github.com/elfmz/far2l/blob/master/WinPort/src/APIStringCodepages.cpp#L179) to 1251 and 866 in WinPort:

```
	UINT TranslateCodepage(UINT codepage)
	{
		switch (codepage) {
    		case CP_ACP: return 1251;
    		case CP_OEMCP: return 866;
		}
		return codepage;
	}
```

Better solution would be to get LANGUAGE parameter from `locale` command output and use corresponding ANSI/OEM code page for that language.

But how to convert strings like "ru_RU" to code page numbers? To achieve this I wrote a simple perl script that parses dlls/kernel32/nls files from wine source tree.

```
#!/usr/bin/perl

$dir = ".";
opendir DIR, $dir;
my @dir = readdir(DIR);
close DIR;

foreach(sort @dir){
    if (-f $dir . "/" . $_ ) {
        my @parts = split "\\.", $_;
        if (@parts[1] eq 'nls') {
            #print $_, "\n";
            open(my $file, '<', $dir . "/" . $_) or die "Unable to open $!";
            my @strings=<$file>;
            foreach(@strings) {
                my ( @match1 ) = ($_ =~ /(LOCALE_IDEFAULTCODEPAGE "(\d+)")/g);
                if ($match1[1]) { $cp = $match1[1]; }
                my ( @match2 ) = ($_ =~ /(LOCALE_SISO3166CTRYNAME "(\w+)")/g);
                if ($match2[1]) { $cn = $match2[1]; }
                my ( @match3 ) = ($_ =~ /(LOCALE_SISO639LANGNAME "(\w+)")/g);
                if ($match3[1]) { $ln = $match3[1]; }
                my ( @match4 ) = ($_ =~ /(LOCALE_IDEFAULTANSICODEPAGE "(\d+)")/g);
                if ($match4[1]) { $cpa = $match4[1]; }
            }
            if (($cn ne '029') && ($cp ne '1')) {
                print "$ln", "_", "$cn,$cp,$cpa\n";
            }
        }
    }
}
```

So here is locale-to-code-page conversion table. Format is "language_COUNTRY,OEM,ANSI". Hope it helps to implement code page processing properly. If locale is not in the table, we probably should [fall back to 437](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT) (and 1252 for ANSI) code pages. Maybe we also need something like environment variable(s) to override oem and ansi code page numbers.

```
af_ZA,850,1252
ar_SA,720,1256
ar_LB,720,1256
ar_EG,720,1256
ar_DZ,720,1256
ar_BH,720,1256
ar_IQ,720,1256
ar_JO,720,1256
ar_KW,720,1256
ar_LY,720,1256
ar_MA,720,1256
ar_OM,720,1256
ar_QA,720,1256
ar_SY,720,1256
ar_TN,720,1256
ar_AE,720,1256
ar_YE,720,1256
ast_ES,850,1252
az_AZ,866,1251
az_AZ,857,1254
be_BY,866,1251
bg_BG,866,1251
br_FR,850,1252
ca_ES,850,1252
zh_CN,936,936
zh_TW,950,950
kw_GB,850,1252
cs_CZ,852,1250
cy_GB,850,28604
da_DK,850,1252
de_AT,850,1252
de_LI,850,1252
de_LU,850,1252
de_CH,850,1252
de_DE,850,1252
el_GR,737,1253
en_AU,850,1252
en_CA,850,1252
en_GB,850,1252
en_IE,850,1252
en_JM,850,1252
en_BZ,850,1252
en_PH,437,1252
en_ZA,437,1252
en_TT,850,1252
en_US,437,1252
en_ZW,437,1252
en_NZ,850,1252
es_PA,850,1252
es_BO,850,1252
es_CR,850,1252
es_DO,850,1252
es_SV,850,1252
es_EC,850,1252
es_GT,850,1252
es_HN,850,1252
es_NI,850,1252
es_CL,850,1252
es_MX,850,1252
es_ES,850,1252
es_CO,850,1252
es_ES,850,1252
es_PE,850,1252
es_AR,850,1252
es_PR,850,1252
es_VE,850,1252
es_UY,850,1252
es_PY,850,1252
et_EE,775,1257
eu_ES,850,1252
fa_IR,720,1256
fi_FI,850,1252
fo_FO,850,1252
fr_FR,850,1252
fr_BE,850,1252
fr_CA,850,1252
fr_LU,850,1252
fr_MC,850,1252
fr_CH,850,1252
ga_IE,437,1252
gd_GB,850,1252
gv_IM,850,1252
gl_ES,850,1252
he_IL,862,1255
hr_HR,852,1250
hu_HU,852,1250
id_ID,850,1252
is_IS,850,1252
it_IT,850,1252
it_CH,850,1252
iv_IV,437,1252
ja_JP,932,932
kk_KZ,866,1251
ko_KR,949,949
ky_KG,866,1251
lt_LT,775,1257
lv_LV,775,1257
mk_MK,866,1251
mn_MN,866,1251
ms_BN,850,1252
ms_MY,850,1252
nl_BE,850,1252
nl_NL,850,1252
nl_SR,850,1252
nn_NO,850,1252
nb_NO,850,1252
pl_PL,852,1250
pt_BR,850,1252
pt_PT,850,1252
rm_CH,850,1252
ro_RO,852,1250
ru_RU,866,1251
sk_SK,852,1250
sl_SI,852,1250
sq_AL,852,1250
sr_RS,855,1251
sr_RS,852,1250
sv_SE,850,1252
sv_FI,850,1252
sw_KE,437,1252
th_TH,874,874
tr_TR,857,1254
tt_RU,866,1251
uk_UA,866,1251
ur_PK,720,1256
uz_UZ,866,1251
uz_UZ,857,1254
vi_VN,1258,1258
wa_BE,850,1252
zh_HK,950,950
zh_SG,936,936
zh_MO,950,950
```

**Comment by unxed** [comment]
Maybe we have to wait for upstream (unzip) to implement the same behavior for consistency.
https://sourceforge.net/p/infozip/patches/29/

**Comment by unxed** [comment]
#753 proposes better solution which is not dependent on upstream unzip. Closing

**Comment by unxed** [comment]
https://github.com/elfmz/far2l/pull/755

**Comment by elfmz** [comment]
я тут все переделал, строит перепроверить баг (у меня конечно же все работает)

**Comment by unxed** [comment]
ага, сейчас проверю!

до меня, кстати, ещё одна попытка была починить зипы. у них немножко другая табличка кодировок получилась, я так и не разобрался, почему. но пусть здесь будет на всякий

https://github.com/zip-i18n/libnatspec/blob/master/lib/data/get_charset_data.h

**Comment by unxed** [comment]
> я тут все переделал, стоит перепроверить баг (у меня конечно же все работает)

проверил на своём (довольно злом) наборе странных зипов. порядок :+1:

**Comment by elfmz** [comment]
а можно набор расшарить? если в нем секретного ничего нету

**Comment by unxed** [comment]
> а можно набор расшарить? если в нем секретного ничего нету

Разумеется! 
[samples.zip](https://github.com/elfmz/far2l/files/5322428/samples.zip)

**Comment by unxed** [comment]
mc, например, очень смешно ломается на

csv.zip
new3.zip
тест €.zip
и
тест ب λ €.zip

из этого набора.

А ещё он совершенно не подозревает о существовании OEM кодировок, отличных от 866.

**Comment by unxed** [comment]
Вылезла таки проблемка, #757. Впрочем, ну как вылезла. Она там всегда была, мы ничего нового не добавили, просто раньше не замечал никто.

**Comment by unxed** [comment]
btw, libarchive refuses to fix locale issues for now https://github.com/libarchive/libarchive/issues/587
