### ISSUE TITLE
build on mac/catalina: NetRocks SFTP does not start

### ISSUE THREAD

**Issue by asimonov** [elfmz/far2l#728]
hello! 
again - great work porting far2l!

I have just tried rebuilding far2l on mac/catalina 10.15.6 following the main page instructions.
all worked well.
far starts and seem to be ok.
but trying to connect to an sftp server shows this error.
what can this be?
I can see that file is there and looks like a valid executable...

<img width="1307" alt="Screenshot 2020-07-28 at 14 08 41" src="https://user-images.githubusercontent.com/240630/88669730-2a57c880-d0dc-11ea-948a-5ae1e32cd1cd.png">

**Comment by elfmz** [comment]
what if you will try to run these executable from terminal (i suspect it will complain on some missing library)?

**Comment by asimonov** [comment]
yes, you are right:

```
(base) alexey@perseverance:~/dev/far2l/build/install/Plugins/NetRocks/plug$ ./NetRocks-SFTP.broker 
dyld: Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/lib/libssh.4.7.4.dylib
  Reason: image not found
Abort trap: 6
```

i'll investigate what happened

**Comment by asimonov** [comment]
ok, problem probably happend after upgrade to Catalina from Mojave.
using this as a guide I have found the following solution that fixed my situation:

```
brew reinstall libssh
sudo chown -R alexey:admin /usr/local/include/libssh
sudo chown -R alexey:admin /usr/local/lib/cmake/libssh
brew link --overwrite libssh
```
