### ISSUE TITLE
build errors on Mint 20 with wx 3.1.3 [solved]

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#731]
https://forums.wxwidgets.org/viewtopic.php?f=19&t=47403

Need to do
```
sudo ln -s /bin/grep /usr/bin/grep
sudo ln -s /bin/egrep /usr/bin/egrep
```
to build far2l with wx 3.1.3 on Linux Mint 20 (GTK2 version builds this way, GTK3 still fails).

**Comment by elfmz** [comment]
so it seems problem is not at far2l's side at all?

**Comment by unxed** [comment]
> so it seems problem is not at far2l's side at all?

yep, I just mention it here for other people to save some time :)
