### ISSUE TITLE
Winport codepages take too much space

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#733]
WinPort/wineguts/codepages object files take about a half of size of far2l's binary. It is critical for devices with limited storage space, like openwrt routers. Do we actually need them? Can't we just use [iconv API](https://en.wikipedia.org/wiki/Iconv) instead?

UPD: Perhaps we could have two backends for charset conversion chosen at build time: iconv's or wine's. Wine's for more flexibility, iconv's for saving a half the size of the binary.

**Comment by unxed** [comment]
Made an experimental iconv-based WinPort. It even works!

@elfmz invited to check out https://github.com/unxed/far2l/tree/winport_iconv

**Comment by elfmz** [comment]
Всякие wide_utf*.. зря обидел - они без вайновских таблиц работают, и работают быстрее так как им не нужна аллокация для вычисления длины строки без output buffer.

На выходных если получится попробую адаптировать

**Comment by unxed** [comment]
> Всякие wide_utf*.. зря обидел

Это непреднамеренно, по незнанию :)

> На выходных если получится попробую адаптировать

Смотреть надо ту ветку, которая utf32, она самая актуальная. Я умудрился сделать так, чтобы вместо неподдерживаемых символов показывались заменители, потому что по умолчанию iconv такое делать не умеет, пришлось небольшую оберточку добавить. Не с первой попытки, но получилось :)

Ещё там баг есть в iconv-версии: ни в какую не хотят отображаться символы с кодами 0-32. С вайновой MultiByteToWideChar они показываются, с iconv'овской вместо них пустота (именно на экране, в файлы редактор их нормально сохраняет). При этом я смотрел, чего они там в dst возвращают обе реализации этой функции — там одно и тоже.

**Comment by unxed** [comment]
> На выходных если получится попробую адаптировать

ап :)

**Comment by elfmz** [comment]
pending..

**Comment by elfmz** [comment]
см бранч iconv, Но надо еще сделать EnumSystemCodepages

**Comment by unxed** [comment]
> см бранч iconv, Но надо еще сделать EnumSystemCodepages

воу! сейчас заценим :)

**Comment by unxed** [comment]
> см бранч iconv, Но надо еще сделать EnumSystemCodepages

А вот тут, кажется, можно разве что вывод
iconv --list
парсить, оставляя из него только то, что начинается с CP и дальше цифры

Какого-то c api для этого, кажется, не предусмотрено.

**Comment by elfmz** [comment]
план вощем такой:
- при билде запускать iconv −l и препроцессором перегонять его вывод в map<ID, name>, Где ID -адекватно-рандомный идентификатор придуманный препроцессором на месте.
- sprintf("CP%u"... поменять на find в той мапе
- ну и EnumSystemCodepages

**Comment by unxed** [comment]
а если вывод iconv -l на системе, где будет far2l гоняться, окажется отличным от системы, где он собирался? это оно конечно вряд ли кто-нибудь станет кросс-компилировать для макоси на линуксе или наоборот, но кто знает

**Comment by elfmz** [comment]
судя по всему iconv читает /usr/lib/x86_64-linux-gnu/gconv/gconv-modules
но это тоже както не выглядит надежным решением
..ох уж этот линух, ну вот сложно было им сделать апи для енума?

**Comment by unxed** [comment]
> см бранч iconv, Но надо еще сделать EnumSystemCodepages

Похоже, работает :)

**Comment by elfmz** [comment]
..и задачка со звездочкой: как это все увязать с https://github.com/elfmz/far2l/blob/iconv/WinPort/src/APIStringCodepages.cpp#L317

**Comment by unxed** [comment]
Обнаружен баг:
1) vmlinuz в редакторе
2) нажимаем F8 (может быть, нужно несколько раз)
3) наблюдаем вылет

[Uploading vmlinuz.zip…]()

**Comment by unxed** [comment]
> ..и задачка со звездочкой: как это все увязать с https://github.com/elfmz/far2l/blob/iconv/WinPort/src/APIStringCodepages.cpp#L317

Наверное, сначала хорошо бы понять, где и как этот enum вообще у нас используется и для чего. И хотим ли мы вообще работу с кодировками за пределами системной ANSI, системной OEM, KOI* и UTF*.

**Comment by elfmz** [comment]
F3  файла -> Shift+F8 -> Ctrl+H

**Comment by unxed** [comment]
> F3 файла -> Shift+F8 -> Ctrl+H

Какие-то не очевидные юзкейсы у этого в современных реалиях. В мире, в котором Far2 создавался, все массово на юникод переходили, и задачка перекодировать какие-нибудь исходники из какой-нибудь местной кодировки была прям вот актуальной и часто нужной. А сейчас это всё такая экзотика, за которой можно и иконв из консольки вызвать раз в пять лет, наткнувшись на какой-нибудь исторический артефакт. Ну, это имхо, конечно.

**Comment by unxed** [comment]
> Обнаружен баг:
> 
>     1. vmlinuz в редакторе
> 
>     2. нажимаем F8 (может быть, нужно несколько раз)
> 
>     3. наблюдаем вылет
> 
> 
> [vmlinuz.zip](https://github.com/elfmz/far2l/files/5396881/vmlinuz.zip)

Падать перестало, но тупить на ANSI<->OEM, конечно, изрядно. Ну впрочем никто и не обещал, что iconv-версия будет быстрее. Вряд ли кто-то на роутерах ядро смотреть в разных кодировках зачем-нибудь захочет)

**Comment by elfmz** [comment]
Для мира суровых роутеров можно просто сделать конфигурябельным WinPort/wineguts/cptable.c, с возможностью выбирать желаемые страницы на этапе конфигура.
Можно и ничего не выбирать, UTF8/16/32 то поддерживается без него.

**Comment by unxed** [comment]
Угу, а ещё можно собирать в отдельные .so и поставлять отдельными пакетами (картинка про троллейбус из буханки хлеба))

**Comment by elfmz** [comment]
Ну вощем я попытался его оптимизировать путем кэширования iconv_open'ов и все равно оно раза в 4 медленнее чем вайновское перекодирование. Что вкупе с отсутствием безкостыльного enumа доступного набора кодировок ставит на нем крест, возможно, временный

**Comment by elfmz** [comment]
попробую еще наверное libicu

**Comment by unxed** [comment]
> оно раза в 4 медленнее чем вайновское перекодирование

А можно там в той ветке, которая в случае ошибок перекодирования, идти не побайтово, а кусками «до следующего сбоя»? Должно стать быстрее по идее.

**Comment by elfmz** [comment]
а хотя тут пишут что ICU всего на четверть быстрее iconv-в https://github.com/Alexhuszagh/UTFPP

**Comment by elfmz** [comment]
'кусками «до следующего сбоя»?' оно так и делает

**Comment by unxed** [comment]
Ну замут был не скорость выиграть, а размер бинарника (а ещё просто для фана и сям немножко поучиться). В принципе это и правда можно выносом табличек в отдельные бинари решить, какие надо — те ставишь. Хотя наличие выбора из двух решений, имхо, это хорошо: если, например, кому-то понадобится кодировка, которой нет в Wine — у него будет такая опция.

**Comment by unxed** [comment]
> а хотя тут пишут что ICU всего на четверть быстрее iconv-в https://github.com/Alexhuszagh/UTFPP

Смешно. Если у Wine самый быстрый перекодировщик — это его надо отдельной либой собирать и раздавать в дистрибутивы :)

**Comment by unxed** [comment]
>  ставит на нем крест, возможно, временный

Если оно будет жить внутри директив условной компиляции и включаться вручную теми, кому оно надо — почему бы и не оставить? Место оно мирез ест, код усложняет, кажется, несуществуенно. А опция «добавить кодировку, которой нет в Wine» будет доступна тем, кому такое может зачем-нибудь понадобится.

**Comment by elfmz** [comment]
так для этого надо еще вагон кода написать чтоб работал enum и все такое, нет смысла
лучше уж icu поэкспериментировать там вроде есть enum

**Comment by elfmz** [comment]
правда у icu другая проблема - она конвертирует чтото<->UTF16 то есть в UTF32 будет дополнительная конверсия

**Comment by elfmz** [comment]
вощем получается да, у wine самый быстрый перекодировщик, по кр мере для такой задачи)

**Comment by unxed** [comment]
Я бы дописал сюда резюме на английском, чтобы по крайней мере оно осталось как результат исследования для других интересующихся этим вопросом.

**Comment by unxed** [comment]
Experimenting with the [iconv-based charset translation](https://github.com/elfmz/far2l/tree/iconv) shows that such code runs 4x slower than Wine-based code. We could also experiment with icu, but there is [evidence](https://github.com/Alexhuszagh/UTFPP) that the benefit will be only 1.4 times. Therefore, at the moment, Wine's code for converting text between charsets remains the most efficient.

**Comment by elfmz** [comment]
Межтем я отгрыз 600кб совершенно безвоздмездно, что означает - нахаляву
Оригинальный код вайна - он был под UTF16, так как у винды именно такой wchar_t. В процессе миграции в far2l он стал соответствующего размера, то есть таблицы перекодировки стали состоять из 32хбитных wchar-ов. Вот тут я их сделал снова 16битными: https://github.com/elfmz/far2l/tree/unicode_tables_16 с виду вроде все работает норм

**Comment by elfmz** [comment]
кроме того похоже большую часть места отжирают кодировки восточно-азиатские что называется, вот сделаю настройку для отключения их, думаю это освободит еще больше половины места занятого таблицами перекодировки

**Comment by elfmz** [comment]
собственно вот, еще минус 1.2иб (по желанию)

**Comment by unxed** [comment]
Ха, класс! По отношению к азиатам жестко, конечно :)) Впрочем, оно ж не включено по умолчанию будет, да?

**Comment by elfmz** [comment]
Не по умолчанию. КРоме того это отношение не я придумал - довольно обычная опция и в винде (хз насчет десятки ) и в линухах..

**Comment by unxed** [comment]
> Не по умолчанию. КРоме того это отношение не я придумал - довольно обычная опция и в винде (хз насчет десятки ) и в линухах..

Пакетировщикам сложно будет. Не делать же два пакета — с этими кодировкам и без. Их бы в отдельную .so'ху собирать тогда, которую можно было бы потом в отдельный пакет запакетировать.

**Comment by unxed** [comment]
Ещё в стиле «бесплатно, то есть, даром»: можно таблички хранить ужатыми в DEFLATE (2.2Mb->743Kb .o'шки жмутся) и распаковывать при первом обращении только необходимые. Реально пользователь 1-2 таблицами может пользоваться, вряд ли больше.

**Comment by unxed** [comment]
Ух ты, а в 7z вообще в 253 Kb пакуются. И распаковщик 7z у нас уже есть в комплекте, чсх. 1) Собирать в отдельные .so'хи 2) Паковать всю пачку 7z'ом 3) Распаковывать и грузить в память on demand

**Comment by elfmz** [comment]
и делается и при желании можно навесным паковщиком ELFов воспользоваться, если он будет под нужную платформу конечно

**Comment by elfmz** [comment]
"Но вот мысль грузить в память только используемые" это делается на уровне VMM операционки. ELF файлы не вычитываются в память а мапятся, вычитываются только те области которые нужны (с RAM page size granularity)
