### ISSUE TITLE
Snap installs in in drive list

### ISSUE THREAD

**Issue by labrador-gibraltar** [elfmz/far2l#736]
When I press Alt+F1/F2 there is a list of filesystems made by snap installer, like
/snap/core18/1885│squashfs
/snap/postman/123│squashfs
/snap/vlc/1620│squashfs
/snap/gtk2-common-themes/13│squashfs
/snap/gtk-common-themes/1506│squashfs
/snap/gtk-common-themes/1474│squashfs
Lots of them, more than 20, they are useless and messing with useful ones. Is there way to manage list of filesystems in this dialogue or at least filter out by mask?

**Comment by spvkgn** [comment]
+1
It would be useful to add ability to ignore storage devices mounted as loop devices in /snap.
