### ISSUE TITLE
Error loading colorer plugin module after update

### ISSUE THREAD

**Issue by kilttartan** [elfmz/far2l#760]
![image](https://user-images.githubusercontent.com/12932444/95100951-5164f300-073a-11eb-8580-b129ea07318a.png)

WINPORT: LoadLibraryEx(/usr/lib/far2l/Plugins/colorer/plug/colorer.far-plug-wide): dlopen error /usr/lib/far2l/Plugins/colorer/plug/colorer.far-plug-wide: undefined symbol: unzReadCurrentFile
CheckForResizePending
Current client size: 1529 814 font 11 22
OnKeyDown: ff0d d d 0 1619248
OnChar: d d 0 1619248 _lk_ts=1619248 _lk_enqueued=0
 d d 20 DOWN::Enqueue: 
 d d 20 UPut::Enqueue: 
CommandLine::ShowBackground: done

Ubuntu Studio 20.04

**Comment by elfmz** [comment]
check now plz

**Comment by unxed** [comment]
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
fmt_LIBRARY (ADVANCED)
    linked by target "colorer" in directory /home/unxed/far2l/sandbox_clean_3.1/far2l/far2l/colorer

-- Configuring incomplete, errors occurred!
See also "/home/unxed/far2l/sandbox_clean_3.1/far2l/build/CMakeFiles/CMakeOutput.log".
See also "/home/unxed/far2l/sandbox_clean_3.1/far2l/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:640: cmake_check_build_system] Ошибка 1
```

**Comment by kilttartan** [comment]
> check now plz

Yes, now colorer plugin is working!
I've cloned and builded it, and than installed via dpkg

**Comment by kilttartan** [comment]
> ```
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> fmt_LIBRARY (ADVANCED)
>     linked by target "colorer" in directory /home/unxed/far2l/sandbox_clean_3.1/far2l/far2l/colorer
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/unxed/far2l/sandbox_clean_3.1/far2l/build/CMakeFiles/CMakeOutput.log".
> See also "/home/unxed/far2l/sandbox_clean_3.1/far2l/build/CMakeFiles/CMakeError.log".
> make: *** [Makefile:640: cmake_check_build_system] Ошибка 1
> ```
Please, check carefully all the dependencies. I had this issue, but it got fixed when I have installed all necessary packages.
It could be that libxerces-c-dev is missing

**Comment by unxed** [comment]
> > ```
> > CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> > Please set them or make sure they are set and tested correctly in the CMake files:
> > fmt_LIBRARY (ADVANCED)
> >     linked by target "colorer" in directory /home/unxed/far2l/sandbox_clean_3.1/far2l/far2l/colorer
> > 
> > -- Configuring incomplete, errors occurred!
> > See also "/home/unxed/far2l/sandbox_clean_3.1/far2l/build/CMakeFiles/CMakeOutput.log".
> > See also "/home/unxed/far2l/sandbox_clean_3.1/far2l/build/CMakeFiles/CMakeError.log".
> > make: *** [Makefile:640: cmake_check_build_system] Ошибка 1
> > ```
> 
> Please, check carefully all the dependencies. I had this issue, but it got fixed when I have installed all necessary packages.
> It could be that libxerces-c-dev is missing

yes, libfmt-dev was missing

**Comment by elfmz** [comment]
missing libfmt should not fail build, must be fixed that now

**Comment by unxed** [comment]
> missing libfmt should not fail build, must be fixed that now

Теперь без libfmt-dev так

```
make[2]: *** Нет правила для сборки цели «/usr/lib/x86_64-linux-gnu/libfmt.a», требуемой для «install/Plugins/colorer/plug/c
olorer.far-plug-wide».  Останов.
make[1]: *** [CMakeFiles/Makefile2:849: colorer/CMakeFiles/colorer.dir/all] Ошибка 2
make: *** [Makefile:152: all] Ошибка 2
```
