### ISSUE TITLE
Could not extract files with non-latin names from rar archive

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#769]
1. Seems far2l uses libarchive for rar now
2. Seems libarchive has problems with non-latin file names in rar
3. Seems it can not be switched to command line rar, "command lines" setting is ignored

Sample (.rar is inside .zip):
[1234.zip](https://github.com/elfmz/far2l/files/5334881/1234.zip)

**Comment by elfmz** [comment]
check now.
Also ' "command lines" setting is ignored' should not be

**Comment by unxed** [comment]
> check now.

Unpacking this sample rar works fine, thanks!

>  Also ' "command lines" setting is ignored' should not be

Still ignored :( "rar" is set in settings, but libarchive is called instead

**Comment by unxed** [comment]
Now .tar.gz with cyrillic filenames can not be unpacked

[1234.tar.gz](https://github.com/elfmz/far2l/files/5336289/1234.tar.gz)

**Comment by elfmz** [comment]
А ща?
Блин мне ета либархив нравится все меньше. Красивый АПИ, а внутри глючный и поддерживающий мало-форматов (типа 7z)

**Comment by unxed** [comment]
> А ща?

Ща огонь!

1) .rar с кириллицей распаковывается нормально
2) .tar.gz с кириллицей распаковывается нормально
3) даже .zip с кириллицей стало возможным распоковать libarch'ом, если делать так:
```
/usr/lib/far2l/far2l --libexec "/usr/lib/far2l/Plugins/multiarc/plug/multiarc.far-plug-mb" BuiltinMain libarch x n.zip "`echo Новый текстовый документ.txt | iconv -f utf-8 -t cp866`"
mv "`echo Новый текстовый документ.txt | iconv -f utf-8 -t cp866`" "Новый текстовый документ.txt"
```

Правда, в настройках .rar всё ещё стоит
```
^rar x {-p%%P} {-ap%%R} -y -c- -kb -- %%A @%%LNM
^rar e {-p%%P} -y -c- -kb -- %%A @%%LNM
^rar t -y {-p%%P} -- %%A
```
ну и т.д., а обрабатываются рары всё равно libarch'ом

> Блин мне ета либархив нравится все меньше. Красивый АПИ, а внутри глючный и поддерживающий мало-форматов (типа 7z)

Серебряной пули нет (c) :))

**Comment by unxed** [comment]
> даже .zip с кириллицей стало возможным распоковать libarch'ом, если делать так:

Увы, это прокатывает только с .zip'ами, которые содержат имя файлов ТОЛЬКО в OEM. Из зипов, в которых есть utf-8 версия имени файлов, всё ещё не получается ничего вытащить с помощью libarchive — что с транскодированием имен файлов в командной строке, что без.

**Comment by unxed** [comment]
Удаление из rar'ов с кириллицей сломано всё ещё(

**Comment by unxed** [comment]
$ "/usr/lib/far2l/far2l" --libexec "/usr/lib/far2l/Plugins/multiarc/plug/multiarc.far-plug-mb" BuiltinMain libarch d /home/u
nxed/far2l/test/1234.rar "тестовый файл 1.тест"
Exception: Error -30 writing header: тестовая папка 1/тестовый файл 2.тест

**Comment by unxed** [comment]
Ok, let's write dedicated issues for that: 
https://github.com/elfmz/far2l/issues/773
https://github.com/elfmz/far2l/issues/774

**Comment by unxed** [comment]
>  Блин мне ета либархив нравится все меньше. Красивый АПИ, а внутри глючный и поддерживающий мало-форматов (типа 7z)

Слабое утешение, но в мире linux везде всё плохо с кириллическими именами файлов в зипах (и иногда рарах), это не только у нас проблемы такие. Вот, например
https://github.com/mate-desktop/engrampa/issues/5
https://github.com/mate-desktop/engrampa/issues/411

Хорошая новость: у нас есть шанс сделать первый менеджер архивов для linux, лишенный этого недостатка. И захватить мир :)
