### ISSUE TITLE
Update rar pre parser in multiarc to support recent formats

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#773]
Sample (.rar is inside .zip):
https://github.com/elfmz/far2l/files/5334881/1234.zip

```
$ "/usr/lib/far2l/far2l" --libexec "/usr/lib/far2l/Plugins/multiarc/plug/multiarc.far-plug-mb" BuiltinMain libarch d /home/unxed/far2l/test/1234.rar "тестовый файл 1.тест"
Exception: Error -30 writing header: тестовая папка 1/тестовый файл 2.тест
```

NB! Archiver command lines for rar are set as follows:
![Снимок экрана в 2020-10-07 15-23-04](https://user-images.githubusercontent.com/1151423/95330337-133e0f80-08b1-11eb-96c8-5c09b13a6ea4.png)

**Comment by elfmz** [comment]
Actually problem with that archive is that multiarc's rar archive pre-parser wasn't able to parse this as rar archive (likely cuz its too recent for it) and did a fallback to libarchive insead of using built-in unrar code.
And libarchive accepted it but has various problems with non-latin files in archive, you know..

**Comment by unxed** [comment]
Maybe we should fallback to command line rar instead of libarchive for that?

**Comment by unxed** [comment]
Should this issue be renamed to "update rar pre parser to support recent formats" when?

**Comment by elfmz** [comment]
Again - multiarc works so: for each format it has built-in code that parses file - just for enumerating archive content. External tools and ^builtins used only for operations like extract/delete/add. But not for initial archive enumeration.
So as for rar this is that code: https://github.com/elfmz/far2l/blob/master/multiarc/src/formats/rar/rar.cpp
and it failed to parse your file. So it didnt treat it as rar format at all.

**Comment by elfmz** [comment]
'update rar pre parser to support recent formats' - yep

**Comment by unxed** [comment]
> So it didnt treat it as rar format at all.

Got it, thanks!

**Comment by elfmz** [comment]
Regarding libarchive, it appeared that its even don't support writing to rar at all: https://www.gsp.com/cgi-bin/man.cgi?section=3&topic=libarchive
So in this situation it essentially worked as last resort for too recent rar file:)

**Comment by unxed** [comment]
Writing to RAR is copyrighted :) The only open source tool allowing RAR writing is PeaZip AFAIK:
https://peazip.github.io/free-rar-create.html

> No alternative Open Source free RAR archiver utility (rar creator) is available: UNRAR is available as royalty-free and open source software for allowing extraction of RAR archives both on Linux and Microsoft Windows, but with the clause of not reverse engineering the code for implementing RAR compression which prevents development of royalty free rar archivers & compressors capable to create or add files to said format.
