### ISSUE TITLE
far2l doesn't build on Arch/Manjaro (their spdlog does not have a bundled fmt)

### ISSUE THREAD

**Issue by alk0** [elfmz/far2l#777]
**problem**
Building far2l in Arch/Manjaro produces an error while compiling colorer (`#include <spdlog/fmt/bundled/core.h>` in `spdlog/fmt/fmt.h`, if I am not mistaken), current cmakefiles can't detect and prevent it.
**background**
The reason, _in my understanding_, is that the author of `spdlog` is stubborn and continues to provide the codebase with bundled `fmt`, even when `fmt` is a separate library, "for convenience". Anyway, as a result, if your distribution has a separate `fmt` and a "stripped" `spdlog`, it can't compile unless built with `SPDLOG_FMT_EXTERNAL=ON`. Some details and discussion here — https://github.com/gabime/spdlog/issues/1146.
**partial solution**
I'm not sure whether it breaks other builds (!), but there's a simple fix for Arch with spdlog-1.8.0-1 and fmt-7.0.3-1 (as a dependency):
```
diff --git a/colorer/CMakeLists.txt b/colorer/CMakeLists.txt
index 2513a380..23b08070 100644
--- a/colorer/CMakeLists.txt
+++ b/colorer/CMakeLists.txt
@@ -75,6 +75,7 @@ target_compile_definitions(colorer PRIVATE
     SPDLOG_DISABLE_TID_CACHING
     SPDLOG_NO_THREAD_ID
     SPDLOG_NO_TLS
+    SPDLOG_FMT_EXTERNAL=ON
 )
 
 target_include_directories(colorer PRIVATE ${LIBCOLORER_TREE}/src)
diff --git a/colorer/src/Colorer-library/src/CMakeLists.txt b/colorer/src/Colorer-library/src/CMakeLists.txt
index 4559be6d..fe87dc69 100644
--- a/colorer/src/Colorer-library/src/CMakeLists.txt
+++ b/colorer/src/Colorer-library/src/CMakeLists.txt
@@ -195,6 +195,7 @@ target_compile_definitions(colorer_lib PRIVATE
     SPDLOG_DISABLE_TID_CACHING
     SPDLOG_NO_THREAD_ID
     SPDLOG_NO_TLS
+    SPDLOG_FMT_EXTERNAL=ON
 )
 
 

```

**Comment by alk0** [comment]
See below. `/usr/include/spdlog/fmt/bundled/core.h` is indeed **absent** (as is the whole "`bundled/`" dir), but `/usr/include/fmt/core.h` does exist (as the whole `/usr/include/fmt/` dir). Again, _in my limited understanding_, `spdlog` _requires_ `SPDLOG_FMT_EXTERNAL=ON` passed somewhere to be built in this configuration (see `#if !defined(SPDLOG_FMT_EXTERNAL)` in `/usr/include/spdlog/fmt/`: `chrono.h`, `fmt.h` and `ostr.h`). "Но это не точно" (q).
Well, in short, I understand very little about all this C/C++ and CMake stuff and have no idea how to fix it _properly_ myself :(

What else can I do to help fixing it?
```
Scanning dependencies of target colorer_lib
[ 58%] Building CXX object Colorer-library/src/CMakeFiles/colorer_lib.dir/colorer/common/Colorer.cpp.o
[ 58%] Building CXX object Colorer-library/src/CMakeFiles/colorer_lib.dir/colorer/common/Exception.cpp.o
[ 59%] Building CXX object Colorer-library/src/CMakeFiles/colorer_lib.dir/colorer/cregexp/cregexp.cpp.o
In file included from /usr/include/spdlog/common.h:36,
                 from /usr/include/spdlog/spdlog.h:12,
                 from /home/username/Projects/far2l/colorer/src/Colorer-library/src/colorer/Common.h:8,
                 from /home/username/Projects/far2l/colorer/src/Colorer-library/src/colorer/unicode/BitArray.h:4,
                 from /home/username/Projects/far2l/colorer/src/Colorer-library/src/colorer/unicode/CharacterClass.h:5,
                 from /home/username/Projects/far2l/colorer/src/Colorer-library/src/colorer/cregexp/cregexp.h:5,
                 from /home/username/Projects/far2l/colorer/src/Colorer-library/src/colorer/cregexp/cregexp.cpp:2:
/usr/include/spdlog/fmt/fmt.h:22:10: fatal error: spdlog/fmt/bundled/core.h: No such file or directory
   22 | #include <spdlog/fmt/bundled/core.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Colorer-library/src/CMakeFiles/colorer_lib.dir/build.make:108: Colorer-library/src/CMakeFiles/colorer_lib.dir/colorer/cregexp/cregexp.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:853: Colorer-library/src/CMakeFiles/colorer_lib.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
```

And just for the reference, `/usr/include/spdlog/fmt/fmt.h` itself:

```
//
// Copyright(c) 2016-2018 Gabi Melman.
// Distributed under the MIT License (http://opensource.org/licenses/MIT)
//

#pragma once

//
// Include a bundled header-only copy of fmtlib or an external one.
// By default spdlog include its own copy.
//

#if !defined(SPDLOG_FMT_EXTERNAL)
#if !defined(SPDLOG_COMPILED_LIB) && !defined(FMT_HEADER_ONLY)
#define FMT_HEADER_ONLY
#endif
#ifndef FMT_USE_WINDOWS_H
#define FMT_USE_WINDOWS_H 0
#endif
// enable the 'n' flag in for backward compatibility with fmt 6.x
#define FMT_DEPRECATED_N_SPECIFIER
#include <spdlog/fmt/bundled/core.h>
#include <spdlog/fmt/bundled/format.h>
#else // SPDLOG_FMT_EXTERNAL is defined - use external fmtlib
#include <fmt/core.h>
#include <fmt/format.h>
#endif
```

**Comment by alk0** [comment]
One more addition: invoking cmake to build the project reports that…
```
-- generating headers and languages
-- Build Colorer: 1.0.5
-- Found Minizip: /usr/lib/libminizip.so  
-- Found Spdlog: /usr/include  
-- Found Xerces-C: /usr/lib/libxerces-c.so
-- Found Xerces-C: /usr/lib/libxerces-c.so
-- Found fmt: /usr/include (found version "7.0.3") 
```

**Comment by elfmz** [comment]
What is inside /usr/include/spdlog/tweakme.h?
in my ubuntu it has commentred out line: // #define SPDLOG_FMT_EXTERNAL

**Comment by alk0** [comment]
Same, all defines are commented out. With this line _uncommented_ building far2l completes smoothly without errors.

**Comment by elfmz** [comment]
Looks like your distributive error, coz on OSX for instance there is spdlog built with external fmt and it has this line uncommented.
Need to think how detect&workaround this correctly, likely best can be detect if spdlog/fmt/bundled missing from its include dirs and if its missing - then force-add that flag like you did

**Comment by alk0** [comment]
I agree that this misconfiguration should be in theory considered a problem of the library author and/or distro maintainers, but given the (somewhat chaotic) nature of Arch, and the fact that no other "standard" Arch package uses this library, and the attitude of the library's author ("just use spdlog_fmt_external")… I feel like it would take _forever_ to settle this all down, if I were trying to elevate this situation upstream :( Well, and this is why I still think it's better to find a workaround here, in far2l, at least for now. Thanks for your patience, I hope some reasonable solution can be found.

**Comment by elfmz** [comment]
check now

**Comment by unxed** [comment]
У меня на mint 20 сейчас так
```
[ 64%] Building CXX object colorer/CMakeFiles/colorer.dir/src/pcolorer2/tools.cpp.o
make[2]: *** Нет правила для сборки цели «/usr/lib/x86_64-linux-gnu/libfmt.a», требуемой для «install/Plugins/colorer/plug/c
olorer.far-plug-wide».  Останов.
make[1]: *** [CMakeFiles/Makefile2:849: colorer/CMakeFiles/colorer.dir/all] Ошибка 2
make: *** [Makefile:152: all] Ошибка 2
```

**Comment by alk0** [comment]
Хм, а у меня как раз всё собралось только что.

**Comment by elfmz** [comment]
крайне неприятная либа, хипстеры писали

**Comment by alk0** [comment]
"Убивать."

**Comment by elfmz** [comment]
2unxed 
- можно полный билд лог?
- а если поставить libfmt-dev?

**Comment by unxed** [comment]
> а если поставить libfmt-dev?

тогда собирается, конечно

> можно полный билд лог?

конечно! минутку

**Comment by unxed** [comment]
Снёс libfmt-dev, лог выглядит так:

```
-- Build type: Release
-- OpenSSL found -> enjoy FTPS support in NetRocks
-- libssh found -> enjoy SFTP support in NetRocks
-- libsmbclient found -> enjoy SMB support in NetRocks
-- libnfs found -> enjoy NFS support in NetRocks
-- libneon found -> enjoy WebDav support in NetRocks
-- generating headers and languages
-- Build Colorer: 1.0.5
-- Found Xerces-C: /usr/lib/x86_64-linux-gnu/libxerces-c.so
-- Found Xerces-C: /usr/lib/x86_64-linux-gnu/libxerces-c.so
CMake Warning at CMakeLists.txt:223 (message):
  Python plugin not enabled by default, use -DPYTHON=yes if you really
  want it


-- Configuring done
-- Generating done
-- Build files have been written to: /home/unxed/far2l/sandbox_clean_3.1/far2l/build
[  3%] Built target utils
[  4%] Built target farlng
[ 16%] Built target wineguts
[ 22%] Built target WinPort
[ 32%] Built target codepages
[ 36%] Built target FARStdlib
eng
rus
hun
languages
FAR language umbrella tool
.LNG Generator v1.5
Copyright (C) 2003-2009 WARP ItSelf
Copyright (C) 2005 WARP ItSelf & Alex Yaroslavsky

lpLNGOutputPath=/home/unxed/far2l/sandbox_clean_3.1/far2l/build/far2l/bootstrap
INFO: There are 14 strings that require review in Russian translation!

INFO: There are 20 strings that require review in English translation!

INFO: There are 253 strings that require review in Czech translation!

INFO: There are 255 strings that require review in German translation!

INFO: There are 206 strings that require review in Hungarian translation!

INFO: There are 236 strings that require review in Polish translation!

INFO: There are 90 strings that require review in Spanish translation!

[ 37%] Built target bootstrap
[ 58%] Built target far2l
[ 64%] Built target colorer_lib
make[2]: *** Нет правила для сборки цели «/usr/lib/x86_64-linux-gnu/libfmt.a», требуемой для «install/Plugins/colorer/plug/c
olorer.far-plug-wide».  Останов.
make[1]: *** [CMakeFiles/Makefile2:807: colorer/CMakeFiles/colorer.dir/all] Ошибка 2
make: *** [Makefile:152: all] Ошибка 2
```

**Comment by unxed** [comment]
Или надо colorer целиком пересобрать попробовать, чтоб что-то понятно стало?

**Comment by elfmz** [comment]
Ну пока предположительно понятно - видимо в этом случае libspdlog-dev собрана с внешней зависимостью на libfmt-dev, НО это не отражено в зависимостях ее пакета, и потому установка libspdlog-dev не приводит к установке libfmt-dev.
Даже не знаю что лучше - накрутить в cmake проверку на такой особый случай и ругаться на отсутствие libfmt-dev или сразу писать что libfmt-dev требуется.
Фишка в том что и spdlog и fmt - они могут быть как header-only так и компиляться. Это дополняется чудесным желанием автора spdlog бандлить fmt с spdlog. Или не бандлить - up to config.
У мэйнтейнеров кукушка набекрень от такого разнообразия опций вот и получается такое..

**Comment by unxed** [comment]
Да уж. Придется libfmt-dev ещё одной зависимостью считать, видимо.

Или же заменить все вызовы logger'а на fprintf'ы, но это же усложнит синхронизацию с апстримом в будущем, да?

**Comment by elfmz** [comment]
checkout workaround-for-missing-fmt
.. и что происходит при отсутствующем libfmt-dev? А при присутствующем?

**Comment by elfmz** [comment]
> заменить все вызовы logger'а на fprintf'ы в stderr
Не получится, у него свой особенный форматинг. Я особо не глядел, но вот всякие {1}  {2} намекает на то, что автора вдохновлял питон .
Я еще когда колорер портировал получил кучу интересного времяпровождения когда оказалось что колорер юзает чутка более новую версию либы чем к примеру в убунте 16 присутствует и в ней чутка новые функции добавили. Спасибо хоть что старые не убавили.

**Comment by unxed** [comment]
> checkout workaround-for-missing-fmt
> .. и что происходит при отсутствующем libfmt-dev? А при присутствующем?

происходит абсолютно всё то же самое, что и на мастере

**Comment by elfmz** [comment]
присутствует ли файл /usr/include/spdlog/tweakme.h ?
если да, то как выглядит строка в нем, содержащая SPDLOG_FMT_EXTERNAL?

**Comment by alk0** [comment]
Может, тупо в лоб проверять наличие `core.h`? Если оно в `/usr/include/fmt` — есть внешняя `fmt`, ставим флаг `SPDLOG_FMT_EXTERNAL`; если оно в `/usr/include/spdlog/fmt/bundled/` — есть включенная `fmt`, ничего не ставим, пусть само разбирается; если нет ни там ни там — `fmt` нет, останавливаемся и просим установить. Топорно и хз насколько надёжно, но вроде логика простая, должно взлететь. Но я дилетант, меня слушать не обязательно.

**Comment by elfmz** [comment]
в данном случае если я все правильно сделал в cmake то получается что /usr/include/fmt отсутствует, /usr/include/spdlog/fmt/bundled - присутствует. Но в tweakme или еще както включено SPDLOG_FMT_EXTERNAL.
Вобщем, интересно было бы видеть весь /usr/include/spdlog по возможности. Или хотябы tweak.me.h

**Comment by unxed** [comment]
> присутствует ли файл /usr/include/spdlog/tweakme.h ?
> если да, то как выглядит строка в нем, содержащая SPDLOG_FMT_EXTERNAL?

да.
```
// #define SPDLOG_FMT_EXTERNAL
```

**Comment by unxed** [comment]
> в данном случае если я все правильно сделал в cmake то получается что /usr/include/fmt отсутствует, /usr/include/spdlog/fmt/bundled - присутствует. Но в tweakme или еще както включено SPDLOG_FMT_EXTERNAL.
> Вобщем, интересно было бы видеть весь /usr/include/spdlog по возможности. Или хотябы tweak.me.h

отчего ж не увидеть :) 
[spdlog.zip](https://github.com/elfmz/far2l/files/5362265/spdlog.zip)

**Comment by elfmz** [comment]
забавно, все тоже самое что в моей тестовой убунте 20, с раницей что у меня все работает

**Comment by alk0** [comment]
вот для Manjaro (и Arch, скорее всего, пакеты вроде те же)
[usr_include_manjaro_2020.zip](https://github.com/elfmz/far2l/files/5362274/usr_include_manjaro_2020.zip)

**Comment by unxed** [comment]
> забавно, все тоже самое что в моей тестовой убунте 20, с раницей что у меня все работает

может, надо полностью снести папку build и попробовать собрать с нуля? долго и лень просто, но если надо - я попробую

**Comment by alk0** [comment]
Я каждый раз начисто собирал, если что: colorer для быстрой проверки (~8 минут), потом rm -rf ./* в build
и ещё раз полностью (21 минута у меня, ПК уж очень первобытный, сорри).

**Comment by elfmz** [comment]
это, а ключик -j передавали для параллелизации билда?
типа make -j $(nproc)

**Comment by alk0** [comment]
Я нет, чтоб вывод линейный был.

**Comment by unxed** [comment]
не-а, вот так собираю
cmake -DCMAKE_BUILD_TYPE=Release ../far2l
make

а он разве сам там автоматом число ядер не определяет для параллелизации?

**Comment by elfmz** [comment]
неааа)

**Comment by elfmz** [comment]
ну да, с параллелизацией вывод нелинейный получается, но если собирать полный лог то восстановить хронологию не сложно. А собирается намного быстрее

**Comment by alk0** [comment]
Да, но и сборка падает не сразу, а пока таргет не закончит, даже если другой таргет уже свалился с ошибкой :)

**Comment by unxed** [comment]
> неааа)

во я даю! ощущения «а чо, так можно было?! о_О»

**Comment by elfmz** [comment]
так что там с минтом? а то я уже выкачал исошку, ща ставить буду в виртуалку..

**Comment by unxed** [comment]
> так что там с минтом? а то я уже выкачал исошку, ща ставить буду в виртуалку..

ну собираю с нуля вот, дома-то у меня не 8 ядер (а на рабочем серваке - не минт :))

**Comment by alk0** [comment]
Надо было, наверное, начать с make colorer — он бы сразу либо упал либо не упал. А потом уже полностью для очистки совести.

**Comment by unxed** [comment]
> Надо было, наверное, начать с make colorer — он бы сразу либо упал либо не упал. А потом уже полностью для очистки совести.

угу. ну затупил, бывает)

**Comment by unxed** [comment]
@elfmz хм, всё собралось без libfmt-dev на этот раз

**Comment by elfmz** [comment]
так если все собралось, то зачем лог? багу закрывать надо да и все)

**Comment by alk0** [comment]
Один важный момент — собирали-то master или workaround-for-missing-fmt? А то я уже подзапутался.

**Comment by unxed** [comment]
workaround-for-missing-fmt

**Comment by elfmz** [comment]
эмм, а можно с мастера пересобрать?) потому что если этот workaround бесполезен, то лучше бы его не мержить в мастер

**Comment by elfmz** [comment]
можно завтра

**Comment by unxed** [comment]
> эмм, а можно с мастера пересобрать?) потому что если этот workaround бесполезен, то лучше бы его не мержить в мастер

ок ща

**Comment by elfmz** [comment]
В принципе, он должен быть бесполезен, потому что его задача - в случае непонятки которую я подозревал и которая не подтвердилась - зафэйлить конфигурацию с ошибкой "поставьте libfmt-dev''
Сам билд он пофиксить никак не мог

**Comment by alk0** [comment]
Там разница — только readme и это сообщение с FATAL_ERROR, насколько я вижу, не? Так что если workaround-for-missing-fmt собрался, то и master обязан собираться. В теории :)

**Comment by unxed** [comment]
пересобрал из мастера colorer и Colorer-library, всё ок. есть смысл целиком пересобирать?

**Comment by elfmz** [comment]
неа нету

**Comment by alk0** [comment]
Тогда закрываем пока что?

**Comment by elfmz** [comment]
"пока что".. оптимистичнее надо быть)

**Comment by unxed** [comment]
кстати об оптимизме

коллеги, вы ведь понимаете, что у нас теперь ЕДИНСТВЕННЫХ в мире *nix нормальная поддержка кодировок в зипах? ни у кого больше такого нет

p7zip, unzip/zip, unar, bsdtar, libzip и все, кто их используют (mc, ark, file roller, engrampa) глючат с нечеловеческой силой

**Comment by elfmz** [comment]
ничего страшного, ее в любой момент можно поломать

**Comment by unxed** [comment]
))))

а я таки отловил условия возникновения этого сбоя у себя. такое бывает, если пытаться собрать с установленным libfmt-dev, а потом снести его и запустить пересборку только colorer с его либой, а не всего far2l целиком

вот тогда ломается и пока всё не пересоберешь, не чинится

**Comment by unxed** [comment]
far2l does not depend on spdlog any more
