### ISSUE TITLE
switch colorer to libarchive to get rid of redundant minizip

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#779]
Looks like it will require only few changes, in ZipXmlInputSource.cpp and in JARInputSource.cpp (and possibly zlib calls in MemoryFile.cpp, though libarchive depends on zlib also).

**Comment by elfmz** [comment]
Actually as i understand (and checked by adding abort() in constructors of each) both not used in current installation
It seems they could be used if some those hrc files of library would be compressed. But they are not.

**Comment by unxed** [comment]
So may we just comment out their inclusion until they are really needed by some scheme? :)

**Comment by elfmz** [comment]
checkout get-rid-of-minizip

**Comment by unxed** [comment]
```
/home/unxed/far2l/sandbox_clean_3.1/far2l/far2l/colorer/src/Colorer-library/src/colorer/io/MemoryFile.h:3:10: fatal error: m
inizip/unzip.h: Нет такого файла или каталога
    3 | #include <minizip/unzip.h>
      |          ^~~~~~~~~~~~~~~~~
```

**Comment by unxed** [comment]
After https://github.com/elfmz/far2l/commit/4bff8bb3b151384c548eb6af91acfc6c1089fcb5 everything builds and is working like a charm!

**Comment by elfmz** [comment]
Ага трэвис уже нашел, вроде исправил, но это еще не точно.
Кстати я тут заглянул в виндовый фар - у него есть common.jar, а в far2l-евском нету, а все содержимое common.jar просто раскидано как есть по месту.
С позиции общей эрудиции, интересны два вопроса:
1 как они такого добились, так как я следовал их инструкциям по сборке базы тут, и там ничего не написано как делать так чтоб база паковалась в jar'ы: https://github.com/colorer/Colorer-schemes
2 а это вообще имеет смысл? мне кажется работать только медленее будет, а на дискету фар все нынешний равно не поместиться, хоть ты его весь целиком зазипуй с потрохами

**Comment by unxed** [comment]
Для какого-нибудь OpenWrt упакованная база colorer'а, может, и актуальна: 13 Mb vs 0,8 Mb

**Comment by elfmz** [comment]
Нашел, указанный в https://github.com/colorer/Colorer-schemes build base действительно билдит непожатую' базу. Чтобы формировались .jar-ы надо делать build base.pack
Это  хорошо, т.к. значит что непожатая база это не глюк моей сборки, а так и задумано

**Comment by unxed** [comment]
Ну вот когда кто-нибудь захочет пакетик под OpenWrt сделать, тогда можно будет заморочиться со сжатой базой, а пока и так ок, наверное :)

**Comment by elfmz** [comment]
в таких девайсах юзается наверное какая нить UBIFS с прозрачным сжатием файлов
