### ISSUE TITLE
Copy&Paste issue in Windows Terminal + WSL2

### ISSUE THREAD

**Issue by AndrewJD79** [elfmz/far2l#788]
I've tried Far2l under Windows Terminal (WT) + WSL2 and everything works great except issue with clipboard. Clipboard is working only in one direction WT to Far2l but not vise versa. Actually,  copying inside far stops working at all. It pasts data from WT clipboard. 
I'm not sure that problem in the Far2l and not in WT itself but  bash seems works just fine.

Thank you

**Comment by unxed** [comment]
Hi! Bash may be using OSC 52 clipboard access method, which is [supported by Windows Terminal](https://github.com/microsoft/terminal/issues/2946), but currently unsupported by far2l.

Far2l uses it's own so called "terminal extensions" for clipboard access. To use them from Windows you may try [this putty fork](https://github.com/unxed/putty4far2l).

**Comment by unxed** [comment]
Try enabling `Options` - `Interface settings` - `Use USC52 to set clipboard data` on latest master.

**Comment by unxed** [comment]
Try enabling `Options` - `Interface settings` - `Use USC52 to set clipboard data` on latest master.

**Comment by unxed** [comment]
@elfmz can we close it now?

**Comment by AndrewJD79** [comment]
I think it can be closed

**Comment by unxed** [comment]
OSC52 support is available starting from Windows Terminal Preview v1.2.2022.0: 
https://github.com/microsoft/terminal/pull/5823#issuecomment-662549728

Corresponding stable release is v1.2.2381.0:
https://github.com/microsoft/terminal/releases/tag/v1.2.2381.0

Latest Windows Terminal stable release is currently 1.20.11781.0:
https://apps.microsoft.com/detail/9n0dx20hk701

**Comment by unxed** [comment]
There is a [report](https://t.me/far2l_ru/29240) in far2l chat that in a regular Windows `cmd` with default settings (with OSC52 enabled in far2l), the clipboard also works fine.
