### ISSUE TITLE
a tool to import color schemes from windows .reg format (done)

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#791]
https://github.com/unxed/far2l-deb/blob/master/far2l_import.pl

Parses REGEDIT4 Far/Far2 color schemes available on web, writes far2l registry files. Please add to readme :)

PS: We probably should implement more friendly way to export/import far2l's color scheme than copying subfolder of REG folder.

**Comment by unxed** [comment]
Here is also a color scheme that I made for myself. If you work a lot in Far and are tired of the lots of blue, or simply prefer Monokai-style hipster colors, you'll love it too!

First, a few examples:
![Снимок экрана в 2020-10-15 18-26-39](https://user-images.githubusercontent.com/1151423/96151785-7c0e3300-0f14-11eb-80c5-f77a34096967.png)
![Снимок экрана в 2020-10-15 18-25-51](https://user-images.githubusercontent.com/1151423/96151804-816b7d80-0f14-11eb-9a82-9e62eda00575.png)
![Снимок экрана в 2020-10-15 18-24-03](https://user-images.githubusercontent.com/1151423/96151817-84ff0480-0f14-11eb-94d6-36fa11239835.png)
![Снимок экрана в 2020-10-15 18-30-55](https://user-images.githubusercontent.com/1151423/96151875-947e4d80-0f14-11eb-87fd-46981a5c2112.png)

When making this color scheme, I was guided by the following principles:
- Maintain the color variety of the vanilla scheme to the maximum. The new color scheme shouldn't be less informative!
- Integrity. The scheme should work clearly and predictably everywhere: in panels, in the editor (including colorer), in the viewer and in dialogs.
- Maintainability. As minimal changes to vanilla scheme as possible (most of file group settings are inherited, only one byte changed in default colorer scheme).
- Borders and frames should not distract from the content they are designing.
- The overall color scheme should be in the style of color schemes popular among software developers

Here is the result:
https://github.com/unxed/far2l-deb/raw/master/default_dark.tar.gz

Posslibly worth mentioning in readme also ;)

**Comment by unxed** [comment]
updated version of scheme is ready with few issues addressed, but it needs far2l vte to be fixed https://github.com/elfmz/far2l/issues/792

**Comment by unxed** [comment]
Отлично, на цветовую схему я ссылочку поставил в тикете про экосистему, а этот можно закрыть теперь :)

**Comment by anteo** [comment]
@unxed , решил попробовать тёмную тему. Смотрится отлично, спасибо.
Есть некоторые предложения по улучшению:

1. Неплохо было бы оформить отдельным репозиторием и выкладывать релизы в "Releases" в Github, т.к. в тикетах (а тем более закрытых) сложно найти , #647 также еще не готов
2. В настройках Colorer можно указать путь к каталогу с темами. Это лучше чем перезаписывать файлы в /usr/lib/far2l/Plugins/colorer/base и не нужен sudo. К тому же после обновления пакета изменения в системных файлах слетают. Можно положить каталог куда-нибудь в ~/.config/far2l и прописать путь к нему через "реестр". Там в общем три параметра: "catalog.xml file", "Scheme" (User HRC path), "Setting schemes" (User HRD path). Мне удалось только меняя первый путь в настройках, т.е. я полностью скопировал папку colorer/base в ~/config/far2l, применил изменения из твоей темы  и прописал путь к catalog.xml. Однако, думаю, это не лучший способ, т.к. приходится копировать файлы из colorer/base. Какой путь прописывать в остальных двух параметрах я не понял, но если получится - было бы здорово.

**Comment by unxed** [comment]
Да, это правильные мысли, записал в todo себе :)

**Comment by FedotParanoic** [comment]
Как установить схему? Новичек в Линукс. Спасибо большое.

**Comment by unxed** [comment]
> Как установить схему? Новичек в Линукс. Спасибо большое.

Мою тёмную? Распаковать архив, запустить install.sh

**Comment by unxed** [comment]
1) import script URL changed
https://github.com/unxed/far2l-deb/blob/master/misc/far2l_import.pl

2) it should be adopted to the new config storage format, until that it may be removed from readme not to confuse users

@elfmz ?

**Comment by unxed** [comment]
> @unxed , решил попробовать тёмную тему. Смотрится отлично, спасибо. Есть некоторые предложения по улучшению:
> 
>     1. Неплохо было бы оформить отдельным репозиторием и выкладывать релизы в "Releases" в Github, т.к. в тикетах (а тем более закрытых) сложно найти , [far2l ecosystem #647](https://github.com/elfmz/far2l/issues/647) также еще не готов
> 
>     2. В настройках Colorer можно указать путь к каталогу с темами. Это лучше чем перезаписывать файлы в /usr/lib/far2l/Plugins/colorer/base и не нужен sudo. К тому же после обновления пакета изменения в системных файлах слетают. Можно положить каталог куда-нибудь в ~/.config/far2l и прописать путь к нему через "реестр". Там в общем три параметра: "catalog.xml file", "Scheme" (User HRC path), "Setting schemes" (User HRD path). Мне удалось только меняя первый путь в настройках, т.е. я полностью скопировал папку colorer/base в ~/config/far2l, применил изменения из твоей темы  и прописал путь к catalog.xml. Однако, думаю, это не лучший способ, т.к. приходится копировать файлы из colorer/base. Какой путь прописывать в остальных двух параметрах я не понял, но если получится - было бы здорово.

Поэкспериментировал с UserHrdPath. Если туда подсунуть путь к def_dark.hrd из темы — не работает. Если подсунуть туда что-то такое:
```
<hrd class="console" name="default" description="Default dark">
  <location link="def_dark.hrd"/>
</hrd>
```
— не работает тоже. Тащить полную копию схемы в пользовательский каталог кажется не лучшим решением — она же обновляется время от времени в дистрибутиве.

Не очень понимаю пока, как решать это.

**Comment by unxed** [comment]
Запилил вот отдельный тикет по поводу не-работы UserHrdPath
https://github.com/elfmz/far2l/issues/1206

**Comment by unxed** [comment]
Там по ходу функция, читающая пользовательскую раскраску, сломана сейчас :(

`FarEditorSet::LoadUserHrd`, вот эта

**Comment by unxed** [comment]
@anteo в общем, пока баг 1206 не починен, я, как выражается elfmz, приложил подорожник — теперь вся схема colorer'а при установке темы копируется в home, и патч темы накладывается уже туда. Всё, больше не надо sudo для установки темы, и не надо переустанавливать тему при каждом обновлении far2l.

**Comment by daemonserj** [comment]
Пытаюсь импортировать цвета, выдаёт ошибку:
perl far2l_import.pl FarSave1.reg
Importing FarSave1.reg
No such file or directory at far2l_import.pl line 81.

far2l 2.5.2

**Comment by unxed** [comment]
А скиньте образец .reg-файла, пожалуйста! Попробую воспроизвести ошибку вашу.

**Comment by daemonserj** [comment]
[FarSave1.clean.zip](https://github.com/elfmz/far2l/files/13037634/FarSave1.clean.zip)

Есть ещё версия от более свежей версии far2, но там формат registry 5.0

**Comment by daemonserj** [comment]
@unxed получилось что-нибудь посмотреть?

**Comment by unxed** [comment]
Боюсь что смогу заниматься всяким таким не раньше апреля.

**Comment by unxed** [comment]
Поправил там некоторые ошибки, спасибо! Попробуйте сейчас:
https://github.com/unxed/far2ltricks/blob/main/misc/far2l_import.pl

**Comment by daemonserj** [comment]
Теперь скрипт отрабатывает без ошибок но цветовые группы не загружает, т.е. ничего не поменялось.

**Comment by unxed** [comment]
Попробуйте собрать far2l с `-DLEGACY=yes`. Без этого не сработает.

**Comment by unxed** [comment]
Ну или вот я у себя конвертнул в новый формат настроек, распакуйте в домашнюю папку.
[home.tar.gz](https://github.com/elfmz/far2l/files/14971680/home.tar.gz)

**Comment by daemonserj** [comment]
@unxed , да спасибо работает!
