### ISSUE TITLE
Incremental correctness of the build

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#795]
I have not analyzed this completely yet (otherwise I would fix it), but here's the problem.

Each time I try to rebuild far2l after update from git, I run into some memory layout incompatibilities that lead to mysterious crashes. I have to blow the complete directory away and rebuild. Let's have an issue to track this.

Some hints:
* Even if I do "Rebuild all" in CLion, the memory layout problems persist. Looks like copying binaries to `install/` creates an inconsistent copies;
* I have to rebuild `multiarc` and other plugins separately if I built `far2l` only;
* More to follow.

**Comment by singalen** [comment]
Here's something that plagued me for a long time, then it went away after a complete rebuild, and now it came back (after a complete rebuild too):

![Screen Shot 2020-10-16 at 12 48 35](https://user-images.githubusercontent.com/151199/96302640-fe970100-0fad-11eb-9549-d5457b2a5995.png)

I guess this is somehow connected to a build order (yuck!).

**Comment by elfmz** [comment]
You mean building without make clean? yes sometimes cmake forgets to rebuild according to dependencies, especially on macos (for a reason i dont know).
But issue with libarchive doesnt look like caused by that

**Comment by singalen** [comment]
You are right, I'm piling two different issues together here. Both need to be fixed in the build code, I believe.
I'll take care of the `libarchive` thing.

**Comment by elfmz** [comment]
ping, i have strong suspection that bug is fixed by https://github.com/elfmz/far2l/commit/ba20231e0669cd97822458a030c0acbe288aa23b

**Comment by singalen** [comment]
Seems to work for me. Thank you!
