### ISSUE TITLE
How do I debug libarchive problems?

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#797]
In order to start diagnosing it, I could use a hint. What is going on here?
![Screen Shot 2020-10-16 at 13 07 09](https://user-images.githubusercontent.com/151199/96304275-aad9e700-0fb0-11eb-87db-38d65fa21a0f.png)

**Comment by elfmz** [comment]
what that strange archives BTW?

**Comment by elfmz** [comment]
BTW remembered that there were problems with libarchive (or something else??), may be even form you. And it appeared that detected headers where mismatched to actual library binary linked to.
Something came from brew, something from OS

**Comment by singalen** [comment]
True, that was me. I have one version from Apple, for which headers are not available and which is on the default library path, and a version from MacPorts which has headers and thus gets used for the build.
I need to invent something to link with the MacPorts version in runtime, probably add it to the installed binaries and add a RPATH.

**Comment by elfmz** [comment]
its should be now possible to build far2l package without brews etc with all dependencies: https://github.com/elfmz/far2l/pull/764
I didnt test though, i'm not using mac.

**Comment by singalen** [comment]
Yep, that's excellent. I need to test how that mechanism behaves in the described case of conflicting libraries. Probably badly and that's what I'm observing.

**Comment by elfmz** [comment]
Ping here, too. Check if problem still there

**Comment by singalen** [comment]
Somehow it works now.

I honestly don't understand why, because multiarc is linked with a system version:
```
~/src/amusement/far2l$ otool -L cmake-build-release/install/far2l.app/Contents/MacOS/Plugins/multiarc/plug/multiarc.far-plug-mb 
cmake-build-release/install/far2l.app/Contents/MacOS/Plugins/multiarc/plug/multiarc.far-plug-mb:
        /usr/lib/libpcre.0.dylib (compatibility version 1.0.0, current version 1.1.0)
        /usr/lib/libarchive.2.dylib (compatibility version 9.0.0, current version 9.2.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
```
but the only headers I have is in MacPorts version, in `/opt/local`, and the headers are taken from `/opt/local/include`, I logged it in `multiarc/CMakeLists.txt`.

**Comment by elfmz** [comment]
It was due to enabled linker's flat namespace. In this case linking works only at function name level, regardless of library name. And due to there was another, system's libarchive loaded into address space (likely due to being used by other components) - symbols resolution was messed up.
see: http://mirror.informatimago.com/next/developer.apple.com/releasenotes/DeveloperTools/TwoLevelNamespaces.html

**Comment by elfmz** [comment]
'multiarc is linked with a system version'
Thats not good, system version is much outdated. Why its linked with system version on your build?

**Comment by singalen** [comment]
Looked for it, and found it.
Because only Homebrew had a hack to link with their, more recent version.
https://github.com/elfmz/far2l/pull/859
