### ISSUE TITLE
Ins/Del/F4 not working in code page selection menu

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#818]
Не то чтобы это было такой уж критически важной фичей, но надо убрать из справки и подсказок их тогда пока, чтоб не смущали юзеров.

**Comment by elfmz** [comment]
это же альфа версия, пусть остается)

**Comment by elfmz** [comment]
на всяк случай уточню - после фикса ins работает в режиме расширенного набора кодировок, del соответственно удаляет из favorites - все как в оригинальном фаре

**Comment by unxed** [comment]
Уточнение оказалось полезным, проверил, работает, спасибо, клёво!

Там F4 в подсказках по хоткеям висит ещё, тоже тогда, наверное, надо либо скрыть, либо заимплементить. По-моему, проще скрыть, т.к. пользы в этой фиче особенной я не вижу.

**Comment by elfmz** [comment]
всмысле, она же работает, но опять же - только для расширенной части - которая по ctrl+h, и для favorites

**Comment by unxed** [comment]
Ой, точно, работает, и правда. Всё, вопрос снимается! Годно, спасибо!

**Comment by unxed** [comment]
Ой, там баг всё ещё имеется: если добавить кодировки в Favourites, потом закрыть это окошко и снова открыть Shift-F8, то исчезает разделитель между "Favourites" и полным списком все ходировок.

И ещё подписи разделителей странные:
«System». Почему «System»? Ни ANSI, ни KOI8 для современного линукса никак не System.
«Unicode». И там вдруг DOS в списке. Какая же это Unicode?
Потом дальше два подряд заголовка «Favourites»: для самих Favourites, и для полного списка. Тоже сбивает с толку.

**Comment by unxed** [comment]
> Ой, там баг всё ещё имеется: если добавить кодировки в Favourites, потом закрыть это окошко и снова открыть по Shift-F8, то исчезает разделитель между "Favourites" и полным списком все ходировок.

Проявляется, только если в Favourites больше одной кодировки добавлено.

**Comment by unxed** [comment]
> Ой, там баг всё ещё имеется

Ап на всякий случай, тикет закрыт, вдруг забудется :)
