### ISSUE TITLE
Colorer? and python

### ISSUE THREAD

**Issue by Guest007** [elfmz/far2l#821]
Try to open python file (from PyCharm's folder). Look at the screenshot. Not correctly work with escapes
![2020-10-22_10-39](https://user-images.githubusercontent.com/147067/96840857-afd8e380-1453-11eb-8421-3956d2a0601f.png)

**Comment by unxed** [comment]
Probably should be reported to upstream? https://github.com/colorer/Colorer-schemes

**Comment by Guest007** [comment]
ok
https://github.com/colorer/Colorer-schemes/issues/100

**Comment by unxed** [comment]
We may keep this open until upstream fix merge though
