### ISSUE TITLE
пожелания от far2l к colorer

### ISSUE THREAD

**Issue by ctapmex** [elfmz/far2l#822]
@elfmz  @unxed 
привет. 
На волне роста интереса к far2l  вырос негатив в сторону colorer, который не может собраться -)
Я сейчас переделываю colorer, внося новые зависимости 😈 в виде icu. Каким требованиям должна удовлетворять библиотека, чтобы вам было проще интегрироваться и собираться ? 
какие OS считать целевыми для проверки ? 
динамическая или статическая линковка ? я смотрю, что большинство linux-ойдов выступает за динамику.  Но для colorer в части icu это влияет на производительность. На  windows динамическая  линковка съедает около 10% скорости.

**Comment by unxed** [comment]
Ой, это к elfmz, я тут не подскажу :)

**Comment by elfmz** [comment]
ну во-первых вроде никто на него особо не жаловался что не собирается
во-вторых, с пожеланиями все грустно, наверное :)
1) Насчет icu: в линуксах (и маках) wchar_t 32хбитный, соответственно именно такие строки приходят от far2l'я. А насколько я понимаю, icu умеет преобразовывать напрямую лишь UTF8-UTF16. Для UCS-4 будет насколько я понимаю второе преобразование, так что как бы не вышло просадки производительности. С другой стороны xerces, юзаемый для парсинга тем на данный момент - тоже оперирует UTF-16, так что может я зря беспокоюсь.
2) В отличии от винды где можно установить себе самую последнюю студию и уютненько с чашкой кофе в руки собрать бинарник для юзеров, тут бинарники собирают сами юзера. И системы у них - кто во что горазд.  far2l на данный момент таргетируется быть способным к сборке с ubuntu 16, хотя были просьбы про ubuntu 12. C++17 сами понимаете не пахнет. В ходе предыдущего апдейта colorer-library была слегка пропатчена чтоб собиралась с C++11, благо там только легкая коррекция работы с std::unique_ptr для этого потребовалась.

**Comment by elfmz** [comment]
кстати а зачем icu? вам же не нужны кодировки, почему не юзать плюсовые строки, с плюсовыми же UTF-??? преобразованиями https://gist.github.com/gchudnov/c1ba72d45e394180e22f ?

**Comment by ctapmex** [comment]
1. жалобы шли на сборку с spdlog , что тут, что на хабре
2. icu используется в первую очередь не для конвертаций между кодировками , а для работы с текстом: проверка регистра, проверка свойств  (число, буква, ..) и т.п.. Движок парсинга/regexp  самописный с подмножеством важный для colorer ключей , которых нет в других библиотеках типа pcre .  А для анализа регулярок надо уметь получать свойства символов.  А учитывая, что предыдущая имплементация строк и работы с их свойствами была очень старая, не поддерживаемая совсем (как сгенерирована карта символов, свойств, как с ними работать)  надо было её заменить. Лучше icu ничего не нашел.
3. набор платформ лучше ограничить, либо версии компилятора. всем не угодишь, а поддерживать то, что не 
поддерживается уже производителем  дорого. у меня с++17 в лайт режиме, должно работать на не последних версиях gcc

**Comment by data-man** [comment]
@ctapmex 
> Движок парсинга/regexp самописный с подмножеством важный для colorer ключей , которых нет в других библиотеках типа pcre .

Может быть [SRELL](http://www.akenotsuki.com/misc/srell/en/) пригодится?
Это и хороший кандидат для замены движка регэкспов в Far'е.
> Лучше icu ничего не нашел.

https://github.com/cor3ntin/ext-unicode-db
https://github.com/JuliaStrings/utf8proc
https://github.com/patperry/utf8lite

**Comment by elfmz** [comment]
1. Ну да, с spdlog была куча проблем, думал все полечилось, надо будет посмотреть что там в коментах нажаловались. Это кстати классический пример того что "кто во что горазд". Вот вы встроили себе определенную spdlog и юзаете ее фичи. А я втянул из репозитория libspdlog-dev и там этих фич (встроенного синглтона и удобняшек для работы с ним) не оказалось. Пришлось переколбашивать код слегка. Но это мелочь. Самая большая проблема с spdlog что она конфигурируется в 100500 вариантов - с либой/без либы, с юзанием своего bundled fmt или системного. Причем в разных репах и разных системах конфигурации разные. Более того, есть примеры того что реальная конфигурация отличается от того что присутствует в его tweakme.h. Пришлось в cmake костыли городить чтоб понять какие -D... скармливать чтоб spdlog нормально заюзался и юзать ли дополнительно системный libfmt. И да - вариант bundled либы в некоторых дистрибах напрямую запрещен, если дистриб имеет либу в пакетах.
2. Все еще не вижу причин не пользоваться C++ строками, все эти std::iswalpha/std::iswdigit там испокон веков:
```
    std::setlocale(LC_ALL, "en_US.utf8");
    std::cout << std::boolalpha << std::iswalpha(L'ы') << '\n';
    std::cout << std::boolalpha << std::iswalpha(L'1') << '\n';
1
0

``` 
Регекспы я так понимаю у вас все равно самописные, какая им разница какие под ними строки?

3. Ну да, я подумываю над включением C++14 :)

**Comment by unxed** [comment]
>  вариант bundled либы в некоторых дистрибах напрямую запрещен, если дистриб имеет либу в пакетах

Опа-опа-опа
```
/usr/lib/p7zip$ apt-file search 7z.so
p7zip-full: /usr/lib/p7zip/7z.so
```

**Comment by elfmz** [comment]
> А нет ли резона в spdlog написать про это, собственно

А смысл? То что ~написано пером~ залито в репозитории так просто не обновишь. Основная проблема что автор spdlog похоже вдохновлялся моделью разработки а-ля python/javascript, когда о  совместимости и какой то унификации думают лишь в последнюю очередь.


>p7zip-full: /usr/lib/p7zip/7z.so

И что мне написать в #include <...> после apt-install p7zip-full ?

**Comment by unxed** [comment]
Хм, хеадеров к ней и правда нет, разве что вытаскивать их из исходников p7zip самостоятельно, и надеяться, что в дистрибутиве не применили какой-нибудь меняющий ABI патчик... да, такая себе идея

**Comment by ctapmex** [comment]
если хранить строки  в стандартном контейнере, то видимо std::u16string. и с заложенным ограничением, что только работаем с символами размера в 2 байта. всё что больше - не смотрим. тогда можно пользоваться штатными функциями получения свойств, поиска и т.п.. Иначе же такие функции надо изобретать. В этом плане ICU дает простоту использования. 
встроенным регекспам важно , чтобы класс строки могла вернуть свойства символов в ней. 

@data-man  искушаешь -) я ушел от подобного рода реализации , и снова вокруг них строки свои строить. Не хочу велосипеды, хочу готовое и поддерживаемое. 
по поводу SRELL и подобного. Замена не так проста. дорабатывать чужую не хочется чтобы поддержать свои особенности. Надо думать как эти особенности обернуть в штатные свойства регулярок. А если к этому приду, то выбор движка пойдет по возможностям и скорости. Возможности у pcre сейчас одни из лучших

**Comment by elfmz** [comment]
`с символами размера в 2 байта. всё что больше `

Почему это? wchar_t имеет размер 4 байта например в юниксах. Но если хочется - можно и u16string.

**Comment by ctapmex** [comment]
вот поэтому и icu, т.к. начинаются игры в компромиссы.  нужна кросс-платформенность . и в то же время не думать о числе байт и т.п. . 
ладно, пока icu останется. с ней проблем в Linux уж точно нет. Это на windows целая проблема в сборку встроить.

**Comment by elfmz** [comment]
Проблема как раз есть и я про нее писал: "most of ICU works with UTF-16 strings and uses data structures optimized for UTF-16," (c) https://unicode-org.github.io/icu/userguide/strings/utf-8.html
А родные строки far2l-я - то есть все события от редактора и тп приходят в UTF-32/UCS-4.
Боюсь за перфоманс

**Comment by ctapmex** [comment]
проблем не должно быть. строка файла передается, один раз конвертируется на входе в плагин и далее идет работа . 
На будущее подумаю. Но пока с regexp не разберусь, другие строки точно не буду использовать .

**Comment by elfmz** [comment]
немного офтопик, насчет строк, но UTF-16 самый бессмысленный вид формата строк. Микрософт его (а точнее UCS-2) взяла потому что тогда это был единственный юникод.
Использовать его сейчас для родного и прибитого гвоздями представления как это делает xerces и icu мне видится несколько странным. Ни рыба ни мясо же.

**Comment by data-man** [comment]
> С другой стороны xerces, юзаемый для парсинга тем на данный момент

Почему бы не перейти на https://github.com/zeux/pugixml?
Конфигом можно использовать как header-only, можно задать использование WCHAR.

**Comment by ctapmex** [comment]
xerces единственная либа, что поддерживает entity в виде файлов. Т.е. include в xml . Другие развивающиеся xml парсеры это не умеют. Хоть это и часть стандарта xml. В colorer это используется

**Comment by volth** [comment]
> немного офтопик, насчет строк, но UTF-16 самый бессмысленный вид юникода, ИМХО. Микрософт его (а точнее UCS-2) взяла потому что тогда это был единственный юникод.
> Использовать его сейчас для родного и прибитого гвоздями представления как это делает xerces и icu мне видится несколько странным. Ни рыба ни мясо же.

`UTF-16` - это не только Windows, это ещё и Java.
Хотя вряд-ли вы планируете плагин-API для Java или что-то в этом роде.
И pcre есть в линуксе в варианте для `UTF-16`

А вот `UTF-32` - это только "`wchar_t` в Linux", да и то он реально нигде не используется.
Нет API которые бы ожидали `UTF-32`-строк

**Comment by elfmz** [comment]
В винде есть апи для юникода (принимает UTF16 wchar_t) и для не юникода (которые внутри врапперы над UTF16-апи).
В линуксе апи для wchar_t нету потому что там обычные апи юникод хавают, ну точнее системную локаль, которая давно везде UTF8. Винда стала заложником того что на момент разработки ядра NT UCS-2 был единственным стандартом юникода и они решили быть на пике технологий так сказать.
Почему UTF16 в джаве юзается вопрос сложный. Скорее всего по такой же причине, так как разрабатываться начала она в тоже самое время.
Я не то что топлю за UTF32, я просто не понимаю зачем промежуточное UTF16 представление в том же xerces, тогда как явно больщинство XML в мире в UTF8. Тупо ради совместимости с джава делать лишнее преобразование там где оно не нужно, а сделать полноценную поддержку символов произвольного не осилили?

**Comment by data-man** [comment]
Если нужен доступ к индивидуальным символам, то UTF32-строки самые быстрые, 
Затем UTF16, а в UTF8 с этим совсем плохо.

Возможно, это одна из причин промежуточного представления.

**Comment by unxed** [comment]
> UTF-16 самый бессмысленный вид юникода

[the worst of both worlds](http://utf8everywhere.org/), да-да))

**Comment by singalen** [comment]
`UTF-16 is often misused as a fixed-width encoding`. Не думаю, что UTF-16 сильно опережает utf-8 по скорости индексации, а как только пойдут cache misses из-за размера, то может и отставать.

**Comment by unxed** [comment]
spdlog теперь в far2l опциональный, к слову. если его нет, вместо него собирается заглушка.

**Comment by lokapal** [comment]
К слову, если spdlog нет, версия 2.5.1 не собирается, cmake падает. Имеет смысл добавить в документацию (в Debian 10 по умолчанию эта библиотека точно не ставится).

**Comment by unxed** [comment]
Без spdlog собирается мастер. В последнем на текущий момент релизе этого ещё не было, да.

**Comment by ctapmex** [comment]
описал текущие зависимости colorer, откуда они пошли, и почему такие 
https://github.com/colorer/Colorer-library/blob/master/docs/depends.md

в far2l сейчас прям сильно все упрощено. часть зависимостей выдернуты с корнями, часть опциональны.  третьи (строки) в неподдерживаемом состоянии.

чтобы выровнить colorer far2l с upstream, надо смериться с icu, и что-то думать с стандартом c++. у меня уже указан 17 и в 11 не собирается.  адаптировать библиотеку.

скажу так, если смиритесь с icu, то готов побороться с версией с++ и заменить xerces-c на libxml, которая, как я понял, более доступная в системе по умолчанию

**Comment by data-man** [comment]
> Я сейчас переделываю colorer, внося новые зависимости 😈 в виде icu.

А ICU для чего? Если только декодирование, то есть много более легковесных библиотек.

**Comment by ctapmex** [comment]
> А ICU для чего?
я тут написал https://github.com/colorer/Colorer-library/blob/master/docs/depends.md  -)
работа со свойствами utf. Чтобы регулярки работали . это в первую и ключевую очередь

**Comment by unxed** [comment]
А чем в итоге история с ICU закончилась то? По поводу C++17, проблема была в том, что ранние версии portable сборки требовали максимально древнего дистрибутива, чтоб работало начиная с него во всех последующих. Сейчас мы логику этой сборки изменили, и такого требования нет, так что можно спокойно использовать скажем C++17, с моей стороны возражений по крайней мере нет.

Ещё интересно, что решили с переходом на libxml. Есть смысл или и так ок?

Зависимость от spdlog не выдернута с корнем, а отключена для тех, кому не надо. Всё ещё можно в отладочных целях собрать с ним.

**Comment by ctapmex** [comment]
ICU остался в ядре. Legacy строки были приведены к интерфейсу как у ICU, и сейчас они выбираются по флагу компиляции.
libxml пока не решил, стоит ли использовать.
spdlog так же пока не решил. Вещь классная, со своими особенностями.

**Comment by unxed** [comment]
@elfmz чисто теоретически, если у нас ICU всё равно так или иначе есть в Colorer, мы не можем их же использовать для определения визуальной ширины символов?
