### ISSUE TITLE
unicode bug with internal VTE

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#825]
see https://github.com/magiblot/turbo/issues/3

thought it was Turbo's bug, but it reproduces only in wx far2l's terminal

**Comment by magiblot** [comment]
Well, it can be said that far2l does not handle fullwidth characters very well in general (at least in TUI mode).

![Screenshot_20201025_134719](https://user-images.githubusercontent.com/20713561/97107588-9e4c4180-16c8-11eb-93ce-af2f1151a598.png)

This is not a simple detail. [Turbo Vision](https://github.com/magiblot/tvision) deals with this by separating the concept of strings from the concept of text representation. That is, it has functions to measure the width of a string, and it has drawing primitives of the style _draw `n` columns from this string, starting at column `m`_. This way neither string types nor classes displaying text become more complex.

**Comment by elfmz** [comment]
`Ладно, Ктулху с ней с шириной, вот почему в turbo под far2l курсор на правую квадратную скобку у смайла не поставить? А в гном терминале норм. Ну это-то точно баг.`

Да скорее всего именно изза ширины и расхождения координат в представлении turbo и фаровского терминала.
С точки зрения turbo:
1  23 4
 [  😊  ]

для терминала far2l:
1  2  3
 [  😊  ]

**Comment by unxed** [comment]
Currently everything is ok with turbo and far2l-in-tty with that sample. But in wx mode there is still a bug with cursor positioning.

**Comment by unxed** [comment]
#1279 fixes it

**Comment by elfmz** [comment]
closing as fixed
