### ISSUE TITLE
Неправильно отображаются 'й' и 'ё' в именах файлов, созданных не в far2l

### ISSUE THREAD

**Issue by strim** [elfmz/far2l#826]
Русские имена файлов с буквами 'й' и 'ё' отображаются с отъехавшими надстрочными частями, словно они являются отдельными символами (на картинке "неудачный файл.txt"). Такая проблема не случается с файлами, созданными в самом far2l (на картинке "удачный файл.txt"). Наблюдаю эту проблему уже года 2-3 с разными сборками far2l под Mac OS X c wxWidgets 3.0 - 3.1.

<img width="826" alt="image" src="https://user-images.githubusercontent.com/5279865/97099801-55ee3e80-164a-11eb-8e7b-3bb67ac6d006.png">

Возможно, баг дублирует https://github.com/elfmz/far2l/issues/213, но на тот явно забили. А возможно - это всем известная проблема, и есть способ её порешать? Спасибо!

**Comment by elfmz** [comment]
Приложил подорожник, должно стать лучше. Но сделать идеально - не в ближайшее время точно, внутренняя логика фара не  рассчитана на такое - когда символов два, а выглядят как один

**Comment by unxed** [comment]
> Приложил подорожник, должно стать лучше. Но сделать идеально - не в ближайшее время точно, внутренняя логика фара не рассчитана на такое - когда символов два, а выглядят как один

А как это в виндовом фаре решают?

**Comment by elfmz** [comment]
никак
[diacritical.txt](https://github.com/elfmz/far2l/files/5435844/diacritical.txt)

![image](https://user-images.githubusercontent.com/20957349/97117564-9a92dc00-1715-11eb-8d8f-1aa8f5e4d32a.png)

**Comment by elfmz** [comment]
но у меня винда не свежая, может в десятке чтонить с этим сделали интересное

**Comment by unxed** [comment]
Ха! А в линуксовой консоли кто-то такое умеет вообще?

**Comment by unxed** [comment]
Кстати, тут схожая проблемка есть, возможно, примерно того же генеза #825

**Comment by elfmz** [comment]
проверил в гномотерминале ubuntu16:
![image](https://user-images.githubusercontent.com/20957349/97117711-a03cf180-1716-11eb-927e-c1c962926e76.png)

в миднайте, под тем же гномотерминалом:
![image](https://user-images.githubusercontent.com/20957349/97117733-bf3b8380-1716-11eb-8e11-78a89554f513.png)

Я в изумлении, если честно. Я ожидал что исконно-линуховые апликухи будут к такому готовы. Ведь с UTF8 просто нельзя быть не готовым к такому.

**Comment by elfmz** [comment]
в 20й убунте получше - смайлик не наезжает на квадратную скобку, но в миднайте все такой же косяк с й

**Comment by unxed** [comment]
Там страннота с этим сэмплом страннейшая:
1) Если его вырезать или скопировать в фаре, то потом не получается в фар же вставить
2) Если изнутри фара натравить на этот сэмпл [turbo](https://github.com/magiblot/turbo), не получается поставить курсор на правую скобку (а в gnome terminal получается)

**Comment by strim** [comment]
Спасибо за подорожник :-), похоже вскопнули какой-то давний пласт.
С последней сборокой выглядит так:
<img width="788" alt="image" src="https://user-images.githubusercontent.com/5279865/97137042-0f641700-1712-11eb-8540-db5343361df2.png">

**Comment by mooskagh** [comment]
Обычно для простоты считают 1 уникодный code point == 1 символ, но это часто не работает (из-за этих-самых комбинированных символов, ну ещё и из-за суррогатов).

Разделять текст на настоящие символы сложнее. Если это надо сделать, обычно проходят [BreakIterator'ом из ICU](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/classicu_1_1BreakIterator.html#adffa57ea9131c4a9e0cf8226c17d459a).

Представление символов с диакритиками (вроде ё и й) в виде последовательности code point'ов -- это рекомендованный стандартом способ, хотя обычно так никто не делает.

Комбинированные символы (вроде ё и й одним code point'ом) в уникоде в качестве исключения только для тех символов, которые были в старых кодировках.
Строку можно перевести в [каноническую форму](https://en.wikipedia.org/wiki/Unicode_equivalence#Normal_forms) [нормалайзером из ICU](https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/classicu_1_1Normalizer2.html#a499f64dc6eb8e8b54a24d53be755d235).
В большинстве случаев это поможет, но для символов, для которого комбинированной формы нет (какое-нибудь ы̆ы̆ы̆ы̆) такое не сработает.


Насчёт того, что смайл налазит на следующий символ -- это скорее проблема шрифта, а не рендерера. Если какой-то символ оказывается шире, чем остальные, то либо он налазит на следующий, либо сдвигает оставшуюся строку вправо. По-моему, лучше, чтоб налазил.


И ещё надо не забывать о лигатурах. В некоторых языках символы объединяются в лигатуры. Например, в арабском ويكيبيديا, если повставлять пробелы между буквами, выглядит так: وي ك ي ب ي د ي ا. Ну и у программистов начали появляться шрифты с лигатурами, всякие там `JetBrains Mono` (рекомендую). В этом случае если каждый символ отдельно рендерить, то лигатуры сливаться не будут, а если вместе -- то будут. Но тогда больше риск, что в шрифте ширина глифа окажется неправильной и всё съедет.

**Comment by unxed** [comment]
> это скорее проблема шрифта, а не рендерера

Вот редактор фара в его wx-версии и в терминалке гнома. Шрифт один и тот же — Ubuntu Mono.

![Снимок экрана в 2020-10-26 11-30-56](https://user-images.githubusercontent.com/1151423/97150325-ffcee780-177e-11eb-8f97-7855c78281fd.png)

**Comment by unxed** [comment]
> Ну и у программистов начали появляться шрифты с лигатурами, всякие там JetBrains Mono (рекомендую).

Идея — кайф! Сходил на сайт JB, восхитился, стянул шрифт, выставил в f2l, и словил огромные дыры между буквами
![Снимок экрана в 2020-10-26 11-39-08](https://user-images.githubusercontent.com/1151423/97151014-fe51ef00-177f-11eb-8d4e-3cbb410690da.png)

**Comment by elfmz** [comment]
Да причины вполне понятны, корень проблем в квадратно-гнездовом представлении винды о консоли, ну и фар его унаследовал.
В теперь попробуйте шрифт размером кратным 5. То есть один из 10 15 20 25..

**Comment by unxed** [comment]
>  В теперь попробуйте шрифт размером кратным 5. То есть один из 10 15 20 25..

А что должно случится? Вроде странностей не наблюдается

**Comment by mooskagh** [comment]
> > Ну и у программистов начали появляться шрифты с лигатурами, всякие там JetBrains Mono (рекомендую).
> 
> Идея — кайф! Сходил на сайт JB, восхитился, стянул шрифт, выставил в f2l, и словил огромные дыры между буквами

Странно, у меня с JetBrains Mono никогда такого не было (и в far2l тоже хорошо работает).
После установки там много всяких вариантов в списке было, я выбрал `JetBrains Mono Regular`.

**Comment by elfmz** [comment]
`А что должно случится? Вроде странностей не наблюдается`

это я strim посоветовтаь хотел, не вкопипастил ник просто

**Comment by unxed** [comment]
>  После установки там много всяких вариантов в списке было, я выбрал JetBrains Mono Regular.

Хм, со второй попытки включился!

**Comment by mooskagh** [comment]
> > это скорее проблема шрифта, а не рендерера
> 
> Вот редактор фара в его wx-версии и в терминалке гнома. Шрифт один и тот же — Ubuntu Mono.
> 

А теперь попробуйте в рамочку в это поместить, или например в имени файла использовать. То всё что справа, cъедет.

```
┌───────────────────┐
│  ╔═══╗ Some Text  │▒
│  ╚═╦═╝ in the box │▒
╞═╤══╩══╤═══════════╡▒
│ ├──┬──┤ 👁 👁 👁 👁 │▒  <- вот тут тоже съехал
│ └──┴──┘           │▒
└───────────────────┘▒
 ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
```

**Comment by unxed** [comment]
Ну, хм, mcedit, turbo и nano считают этот смайл шириной в два знакоместа просто. И ничего, интерфейс у turbo не ломается от этого, хотя он тоже из box drawing chars сделан, как и у фара. Ну это если в терминалке гнома.

**Comment by unxed** [comment]
Браузеры в fixed-width chars режиме тоже смайл на два знакоместа рисуют. И хром и лиса. Ну уж браузеры-то точно должны знать, как обращатья с юникодом правильно?

https://2g0.ru/tmp/demo1.htm

**Comment by mooskagh** [comment]
> Браузеры в fixed-width chars режиме тоже смайл на два знакоместа рисуют. И хром и лиса. Ну уж браузеры-то точно должны знать, как обращатья с юникодом правильно?
> 
> [2g0.ru/tmp/demo1.htm](https://2g0.ru/tmp/demo1.htm)

В браузере у меня так, где-то полтора.
![image](https://user-images.githubusercontent.com/11266455/97153194-639ee380-1772-11eb-99c7-67867d3073c8.png)

В некоторых моноширинных шрифтах смайлы действительно ровно в два раза шире, но это опять же просто автор шрифта так решил, это не хром с фаерфоксом. В разных шрифтах оно по-разному, нельзя заранее сказать как оно будет, или как "надо".

**Comment by mooskagh** [comment]
А вот нашлось: https://bugs.launchpad.net/ubuntu/+source/gnome-terminal/+bug/1665140

Со стандарта Unicode 9 (2017 года), смайлы объявили wide, и они действительно должны занимать два знакоместа (как, например, иероглифы).
Это облегчает работу с моноширинными интерфейсами, но как видим не все шрифты ещё правильно рендерят смайлы.

**Comment by unxed** [comment]
Ладно, Ктулху с ней с шириной, вот почему в turbo под far2l курсор на правую квадратную скобку у смайла не поставить? А в гном терминале норм. Ну это-то точно баг.

**Comment by elfmz** [comment]
давайте ширину смайла в соответтвующей теме обсуждать https://github.com/elfmz/far2l/issues/825 , природа багов общая но все же человек мою просьбу выставить кратный 5 шрифт может не заметить

**Comment by strim** [comment]
Спасибо за глубокое осмысление и за совет использовать JetBrains Mono! 
С этим шрифтом на последней сборке всё стало нормально.
<img width="502" alt="image" src="https://user-images.githubusercontent.com/5279865/97210872-710c9b80-177b-11eb-8ce7-bf549a49d60d.png">

**Comment by unxed** [comment]
JBшный так и не прижился у меня (больно узкий), но за инфу про прогерские шрифты с лигатурами — Большое Человеческое Спасибо!

Вот ещё несколько таких, для тех, кому JB не зашел:
https://github.com/tonsky/FiraCode
https://github.com/microsoft/cascadia-code
https://rubjo.github.io/victor-mono/

О господи, с Microsoft'овского гитхаба подсел на Microsoft'овский шрифт. Какой-то я неправильный линуксоид

**Comment by unxed** [comment]
Рендерилка f2l, конечно, подглюкивает местами на некоторых конструкциях. На таком, например !==
шрифт cascadia

**Comment by unxed** [comment]
а что у нас здесь осталось не решенным, собственно? я проверил сэмпл, нормально сейчас рисуется. два бекспейса тоже нормально, ведь по факту там два символа наличествует

что требуется доделать с точки зрения UX?

**Comment by unxed** [comment]
duplicates #1329, #213

**Comment by elfmz** [comment]
closing as fixed
