### ISSUE TITLE
File System not recognized / incorrectly recognized or displayed in info panel (Ctrl+L)

### ISSUE THREAD

**Issue by ghost** [elfmz/far2l#838]
Hi and thanks for making FAR available for Linux. This is an amazing tool!
After installing FAR2L v 2.2 (build unknown-alpha) in OpenSUSE 15.2 I encountered the following:

EXT4 file system incorrectly reported as EXT2
XFS file system not recognized, and reported as (empty string)
VFAT file system inaccurately reported as MS-DOS

BTRFS, TMPFS are reported correctly.

**Comment by unxed** [comment]
Confirming ext4 shown as EXT2 on Mint 20.

**Comment by elfmz** [comment]
dup of #147
