### ISSUE TITLE
Невозможно открыть .docx файл в .zip архиве.

### ISSUE THREAD

**Issue by Biblbrox** [elfmz/far2l#839]
![Screenshot_20201110_200431](https://user-images.githubusercontent.com/19504453/98707354-02d9f280-2391-11eb-85f0-5140b9121aaa.png)

Ассоциация для .docx файлов добавлена и с другими типами файлов проблем нет.

**Comment by Biblbrox** [comment]
Открытое окно создается libreoffice'ом при попытке найти файл.

**Comment by elfmz** [comment]
У меня все работает. Можете проверить с текущей версией и если все еще воспроизводиться - сделать пример такого zip файла и расшарить здесь?

**Comment by elfmz** [comment]
и еще после попытки открытия файла - сделайте Ctrl+O, и заскриньте лог в консольке под панелями

**Comment by Biblbrox** [comment]
Скрин лога:
![image](https://user-images.githubusercontent.com/19504453/104837668-26587680-58c7-11eb-9ce0-0499c87ea773.png)

И пример файла:
[lab5.zip](https://github.com/elfmz/far2l/files/5825861/lab5.zip)

Тестировал в последней версии в master. 
Странно, но подобное поведение не только с .zip, но и с .tar.gz, и, по-видимому, с любым архивом.

**Comment by Biblbrox** [comment]
И еще, только понял. Все типы файлов, которые невозможно открыть в архиве, указаны в "File associations". С остальными проблем вроде нет.

**Comment by elfmz** [comment]
попробуйте ща

**Comment by Biblbrox** [comment]
Сейчас все отлично работает со всеми файлами.
