### ISSUE TITLE
Far2l Ubuntu and Debian packaging

### ISSUE THREAD

**Issue by invy** [elfmz/far2l#84]
Prepare binary packages for popular distros.

As of now I could imagine following issues regarding packaging:
1. plugin location and changes to far so it could find plugins (evtl. configurable)
   - default plugins ( /use/lib/far2l/ )
   - custom plugins ( ~/.local/lib/far2l )
2.  languages and help location and paths
   - /usr/share/far2l

Plugin paths are configurable via

```
struct LoadPluginsOptions
{
//  DWORD TypeLoadPlugins;       // see TYPELOADPLUGINSOPTIONS
    int MainPluginDir; // TRUE - использовать стандартный путь к основным плагинам
    int PluginsCacheOnly; // seting by '/co' switch, not saved in registry
    int PluginsPersonal;

    FARString strCustomPluginsPath;  // путь для поиска плагинов, указанный в /p
    FARString strPersonalPluginsPath;
    int SilentLoadPlugin; // при загрузке плагина с кривым...
    int OEMPluginsSupport;
    int ScanSymlinks;
};
```

**Comment by lieff** [comment]
Я бы все стандартное оставил как есть сейчас в install, не вижу смысла раскидывать. Подход все статическое в одном месте у приложения мне больше нравится. А вот кастомные бы дополнительно бы грузил из ~/.local/ да, т.к. у юзера может не быть прав записи в установленный для всей системы.
Так же snap/flatpak/appimage было бы не плохо.

**Comment by invy** [comment]
В Linux нельзя все это сунуть в /use/bin, надо рпскидать по соответствующим директориям, потому нужна возможность все это дело грузить из стандартных системных директорий. Иначе просто нет шанса в апстрим фар отправить. А отправлять надо для популярности.

**Comment by lieff** [comment]
Ну минимально разбить придется да. Наприер все в /usr/lib/far а в bin только симлинк. Видел как многие так поступают.

**Comment by invy** [comment]
Не вижу проблемы разбить сразу по-человечески ;)

Что касается кастомных плагинов - только из ~/.local - мало ли какую гадость там понаписывают чтобы ее еще в систему пихать :)

**Comment by lieff** [comment]
По человечески понятие относительное ), например в GoboLinux как раз каждая программа в своем каталоге. Хотя по большому счету мне все равно как оно будет разбито, можно и как принято в конкретном дистре. Просто подход GoboLinux мне больше по душе.

Насчет кастомных плагинов полностью согласен.

**Comment by invy** [comment]
Так, ну с путями к плагинам я проблемы не вижу.
```
struct LoadPluginsOptions
{
//  DWORD TypeLoadPlugins;       // see TYPELOADPLUGINSOPTIONS
	int MainPluginDir; // TRUE - использовать стандартный путь к основным плагинам
	int PluginsCacheOnly; // seting by '/co' switch, not saved in registry
	int PluginsPersonal;

	FARString strCustomPluginsPath;  // путь для поиска плагинов, указанный в /p
	FARString strPersonalPluginsPath;
	int SilentLoadPlugin; // при загрузке плагина с кривым...
	int OEMPluginsSupport;
	int ScanSymlinks;
};
```

**Comment by unxed** [comment]
chrome вообще ставится в /opt/google/chrome, в /usr/bin кладется симлинк, и всем так ок.
в таком варианте собрать пакет можно было бы уже сейчас.
потом - уже улучшить, если кого-то не устроит такая схема.
остается проблема с пользовательскими плагинами, но пока всё равно ни одного нет.

**Comment by unxed** [comment]
а всё-таки, что конкретно на данный момент мешает собрать пакеты?

**Comment by invy** [comment]
Попробуй раскидать содержимое директории install по /usr/bin, /usr/share, и т.п. и заставить его работать.

**Comment by elfmz** [comment]
Я так полагаю, нужно научиться размазываться по файловой системе, как это тут принято
Но это не везде. Вон в альтлинуксе похоже таких тараканов нет, и far2l там запакавоаои довольно давно, настолько давно что не помешало бы им проапдейтиться: http://www.sisyphus.ru/ru/srpm/far2l

**Comment by invy** [comment]
Ну это не тараканы а стандарт и без его соблюдения - в репозитории нет шансов попасть.

**Comment by elfmz** [comment]
А куда пихать такие вспомогательные вещи, как far2l_askpass, roots.sh? Вроде исполняемые же, но и в bin/sbin им не месте

**Comment by invy** [comment]
https://de.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

**Comment by unxed** [comment]
если я правильно понимаю этот самый стандарт, bin от sbin отличается тем, что в bin, в отличие от sbin, кладется то, что должно работать в однопользовательском режиме. соответственно, для частей far2l - скорее /usr/bin, нет?

**Comment by unxed** [comment]
просто оставлю это здесь:
https://wiki.debian.org/RFP

**Comment by elfmz** [comment]
Вобщем как показало маленькое исследование - все без зазрения совести ложат свои приватные скрипты в /etc/whatever/..

**Comment by unxed** [comment]
вообще говоря, можно же собрать хоть с какой-нибудь схемой расположения по папкам, а если придумается более лучшая в будущем - изменить?

**Comment by elfmz** [comment]
"хоть с какой нибудь" - уже собрано..

**Comment by elfmz** [comment]
продолжая маленькое исследование: mc свои *.sh и elf-скринсейвер (наверное) держит в /usr/lib/mc
это в принципе адекватный вариант:
исполняемый файл - /usr/bin/far2l
скрипты/плагины - в /usr/lib/far2l/
Все остальное - в /etc/far2l

**Comment by unxed** [comment]
> "хоть с какой нибудь" - уже собрано..

ну как...
ftp://ftp.altlinux.org/pub/distributions/ALTLinux/Sisyphus/Sisyphus/files/x86_64/RPMS/far2l-2.0-alt1.4198cd5.x86_64.rpm
ERR_FTP_FAILED

btw, интересно, alien поставит это корректно на debian/mint или нет?
ну и там явно довольно древняя версия в любом случае.

**Comment by unxed** [comment]
сделал .deb-ку алиеном из альтлинуксовских пакетов.

там так.
всё, кроме changelog - в /usr/lib/far2l
в /usr/bin - far2l - симлинк на /usr/lib/far2l
в /usr/share/doc/far2l - changelog и copyright

**Comment by unxed** [comment]
Сделал .deb-ку, держите, может, кому пригодится. В архиве - сам пакет и всё необходимое для сборки.

- ставится в /usr/lib/far2l
- создание ссылки в /usr/bin прописано в DEBIAN/postinst, но закомментировано, потому что всё равно пока far2l так запускаться не умеет (рисует чёрное окно и на этом всё)
- .desktop файл ссылается на /usr/lib, опять же, потому что пока никак по-другому
- для обновления: заменяем файлы в /usr/lib/far2l на файлы свежей версии, в DEBIAN/control прописываем в Version актуальный идентификатор сборки, запускаем make_deb.sh

[debian.zip](https://github.com/elfmz/far2l/files/546708/debian.zip)

**Comment by invy** [comment]
Не, надо по-феншую все делать (rpm и deb).

**Comment by unxed** [comment]
пересобрал со свежим билдом.
postinst убрал, файл-симлинк для /usr/bin теперь входит в пакет
far2l теперь можно запускать из консоли, ура (ну и мусорит же он туда, btw)
[debian.zip](https://github.com/elfmz/far2l/files/551672/debian.zip)

**Comment by elfmz** [comment]
всегда можно было запускать из консоли, и всегда он туда мусорил.. раньше мусорил кстати гораздо больше)

**Comment by unxed** [comment]
кстати, shell-скрипты вполне себе принято класть в /usr/bin
примеры: add-remove-locales, apt-add-repository, debconf
во всяком случае, у меня на mint - так

**Comment by unxed** [comment]
> всегда можно было запускать из консоли

в смысле, по простому far2l, а не /home/far2l/build/install/far2l

**Comment by elfmz** [comment]
шелл скрипты общего назначения, которые могут понадобиться юзеру - не вопрос
но roots.sh, trash.sh - это по сути внутренности far2l. far2l_sudoapp - так вообще совсем внутренность (впрочем, от него легко избавиться, просто в ps станет менее понятно кто есть кто).

**Comment by unxed** [comment]
впрочем, в /usr/lib тоже:
`find /usr/lib -name *.sh`
выдает целый список.

**Comment by unxed** [comment]
Updated with 959fd2a.
[debian.zip](https://github.com/elfmz/far2l/files/554450/debian.zip)

**Comment by elfmz** [comment]
вроде, норм сейчас?

**Comment by cycleg** [comment]
Вот вариант для сборки DEB-пакета через CPack, со строки 71.

[CMakeLists.txt](https://github.com/elfmz/far2l/files/577867/CMakeLists.txt)

В таком виде с пакетом есть две проблемы:

1. Зависимости от других пакетов (CPACK_DEBIAN_PACKAGE_DEPENDS). Сейчас указаны почти от балды. Это надо пилить под реальные зависимости far и конкретные выпуски ОС.
2. Те символические ссылки, которые делаются сейчас через `install(CODE`. По уму их создание и удаление нужно поместить в соответствующие пакетные сценарии. Например, для DEB это будут "postinst" и "prerm".

Ну и нужно делать выбор генератора пакета в зависимости от целевой ОС. В этом сценарии такого нет: жестко прописан DEB, строки 114-119.

**Comment by invy** [comment]
@elfmz 
> Все остальное - в /etc/far2l
эм, все надо .hlf и .lng - в /usr/share/far2l, им точно не место в /etc, т.к. это не конфигурационные файлы.

**Comment by elfmz** [comment]
когда выбирал между /etc и /usr/share выбрал первый т.к. короче)
.lng в каком то смысле и конфиги.. вдруг захочется кастомизировать интерфейс)

**Comment by unxed** [comment]
ну .hlf уж точно не конфигурационные :)

**Comment by invy** [comment]
Добавить или оверрайднуть lng - ~/.local/share

**Comment by elfmz** [comment]
уговорили, переехали в /usr/share..

**Comment by cycleg** [comment]
В дополнение к https://github.com/elfmz/far2l/issues/84#issuecomment-259119989: сбор DEB с пакетными сценариями, дабы правильно создавать и удалять символические ссылки.

[make_package.tar.gz](https://github.com/elfmz/far2l/files/580321/make_package.tar.gz)

В идеале эти сценарии хорошо бы шаблонизировать через какой-нибудь m4. Тогда директории развертывания (install_prefix, prefix_bin и prefix_lib в сценариях) можно задать в единственном месте, например, в CMakeLists.txt, и оттуда экспортировать.

Даже в таком виде получается уже вполне себе кошерный пакет.

**Comment by invy** [comment]
А нельзя из deb пакета раскидывать содержимое директории install разве?

**Comment by unxed** [comment]
котаны, оно, похоже, под i686 не работает, а делать пакеты только для amd64 как-то не кошерно.
гляньте #198 - это оно только у меня так, или у всех?

**Comment by elfmz** [comment]
> котаны
ой, радиокот?)  или так просто?)

> оно, похоже, под i686 не работает,
Вечером буду ковырять. Имаж уже скачался и поставился за ночь.

**Comment by unxed** [comment]
> ой, радиокот?) или так просто?)

да словечко давно в народ пошло уже)

**Comment by cycleg** [comment]
DEB-пакет имеет к архитектуре косвенное отношение в том плане, что процедуры работы с пакетами от архитектуры не зависят. Единственное, что есть в пакете - это собственно обозначение архитектуры, для которой он предназначен: поле "Architecture" в файле "control". Бывают и пакеты универсальные, у них это поле равно "all". Если попытаться поставить пакет на неподходящую платформу, то он просто не встанет.

При сборке через CPack архитектура задается в переменной CPACK_DEBIAN_PACKAGE_ARCHITECTURE, по умолчанию она равна выводу команды `dpkg --print-architecture` или "i386", если dpkg нет в системе. Здесь в CMakeLists.txt подставляется та, на которой собирают (без dpkg DEB-пакет вообще не собирается). Кросс-компиляцию надо обрабатывать отдельно.

**Comment by unxed** [comment]
Ну да, я имел в виду, что хорошо бы - если уж собирать - собрать и для i386, и для amd64. Самому вот и там и там надо время от времени)

**Comment by invy** [comment]
для 32-х битной системы не надо "кросскомпиляцию" делать. Достаточно установить 32х битные библиотеки и добавить -m32 ключик (или как оно там в cmake) ;)

**Comment by invy** [comment]
Если deb пакет (или rpm) умеют адекватно все раскидывать, то они этим должна заниматься а не система сборки.

**Comment by elfmz** [comment]
Я установил. Проблемы вызывает только глиб. Более того  -установка libglib2.0-dev:i386 приводит к сносу нативной libglib2.0-dev и наоборот. Но оба варианта не компиляются, причем с разными ошибками. Вобщем, я забил и подебажил на виртуалке.

**Comment by unxed** [comment]
так в итоге с -m32 сейчас можно пробовать собирать, или ошибки с glib остались, и стоит продолжать на виртуалке? :)

**Comment by elfmz** [comment]
на виртуалке ага

**Comment by unxed** [comment]
работает, мерси)

**Comment by mmozeiko** [comment]
I've made ArchLinux package for far2l: https://aur.archlinux.org/packages/far2l-git
It required a bit of patching cmake files because of hardcoded /usr install location: https://aur.archlinux.org/cgit/aur.git/tree/far2l_install.patch?h=far2l-git

**Comment by cycleg** [comment]
В дополнение к https://github.com/elfmz/far2l/issues/84#issuecomment-259368277: сценарии пакета генерируются из шаблонов, куда подставляются параметры сборки. В текущем виде параметров 2: путь к установке bin-файлов far и путь к его lib-файлам. Эти параметры выгружаются через "главный" CMakeFile, если будет собираться DEB-пакет (в системе есть dpkg). Сценарии "заказываются" тоже только по необходимости.

[make_package.tar.gz](https://github.com/elfmz/far2l/files/723718/make_package.tar.gz)

**Comment by unxed** [comment]
Перезалил .deb, теперь там внутри живёт свежий gvfspanel.

**Comment by spvkgn** [comment]
Пробую собирать .deb на launchpad, cборка проходит успешно, но не создаются символические ссылки `far2l_askpass` и `far2l_sudoapp`. В [buildlog](https://launchpadlibrarian.net/331503581/buildlog_ubuntu-zesty-amd64.far2l_0+git20170713.de5554d~ubuntu17.04.1_BUILDING.txt.gz) по этому поводу есть такое:
```
cd "/<<BUILDDIR>>/far2l-0+git20170713.de5554d~ubuntu17.04.1/obj-x86_64-linux-gnu/far2l" && rm /<<BUILDDIR>>/far2l-0+git20170713.de5554d~ubuntu17.04.1/obj-x86_64-linux-gnu/install/far2l_askpass || echo 
rm: cannot remove '/<<BUILDDIR>>/far2l-0+git20170713.de5554d~ubuntu17.04.1/obj-x86_64-linux-gnu/install/far2l_askpass': No such file or directory

cd "/<<BUILDDIR>>/far2l-0+git20170713.de5554d~ubuntu17.04.1/obj-x86_64-linux-gnu/far2l" && rm /<<BUILDDIR>>/far2l-0+git20170713.de5554d~ubuntu17.04.1/obj-x86_64-linux-gnu/install/far2l_sudoapp || echo 
rm: cannot remove '/<<BUILDDIR>>/far2l-0+git20170713.de5554d~ubuntu17.04.1/obj-x86_64-linux-gnu/install/far2l_sudoapp': No such file or directory

cd "/<<BUILDDIR>>/far2l-0+git20170713.de5554d~ubuntu17.04.1/obj-x86_64-linux-gnu/far2l" && ln -s far2l /<<BUILDDIR>>/far2l-0+git20170713.de5554d~ubuntu17.04.1/obj-x86_64-linux-gnu/install/far2l_askpass
cd "/<<BUILDDIR>>/far2l-0+git20170713.de5554d~ubuntu17.04.1/obj-x86_64-linux-gnu/far2l" && ln -s far2l /<<BUILDDIR>>/far2l-0+git20170713.de5554d~ubuntu17.04.1/obj-x86_64-linux-gnu/install/far2l_sudoapp
```
Может нужно что-то где-то подправить в CMake-файлах?

**Comment by cycleg** [comment]
Это чтобы ставить far2l через ```make install```. Если же собирать пакет, например, cpack'ом, то файла, на который ссылаются, а равно и директории, где хотят сделать ссылки, нет и не предвидится. В [том варианте](https://github.com/elfmz/far2l/issues/84#issuecomment-274488833), который предлагался для автоматической сборки DEB-пакета, эти ссылки создаются во время развертывания пакета, а ненужные команды из "CMakeLists.txt" убраны.

**Comment by spvkgn** [comment]
> Это чтобы ставить far2l через make install
В debhelper тоже вызывается `make install`, далее `/usr/bin/cmake -P cmake_install.cmake`
Пока нашел вариант - нужные симлинки добавить на стадии `dh_link`.

Еще осталось непонятным как исправить "build unknown-alpha" при сборке `far2l` через debhelper.

**Comment by cycleg** [comment]
"unknown" вылезает из "far2l/bootstrap/scripts/vbuild.sh", если нет git и собирается не в дереве git-репозитория.

**Comment by spvkgn** [comment]
> собирается не в дереве git-репозитория.

Ясно. Похоже, при сборке из git-репо на launchpad с помощью `git-build-recipe` такой опции нет - tar.xz упаковывается без .git директории. А вообще сам .deb пакет собирается - если кому будет интересно,  PPA здесь [ppa:spvkgn/far2l-builds](https://launchpad.net/~spvkgn/+archive/ubuntu/far2l-builds) , сборка c плагином gvfs panel.

**Comment by Slach** [comment]
@spvkgn и @unxed 
Ребята, а может вы объедините свои усилия и начнете регулярно публиковать сборки DEB пакета в PPA на launchpad?

**Comment by spvkgn** [comment]
@Slach в течение дня PPA должно обновиться. Но хотелось бы найти решение как обойти "build unknown-alpha" при сборке из тарболла без .git директории.

**Comment by unxed** [comment]
Ну вот человек уже делает, чо под руку-то лезть)

Минутка оффтопика: а editorcomp это про что, а то я ещё не собирал новьё?

**Comment by lieff** [comment]
Моя мечта сделать экзешник фара запускаемым на большинстве дистрибутивов без изменений, тогда пакадж не нужен - просто cкачал и запустил. Основная пробелма тут зависимости библиотек, которые не статические, libstdc++, glibc. Некоторые дистрибутивы не предоставляют статический libstdc++, но это только проблемы сборочного сервера, в travis можно собрать статически. Самая большая пробелма glibc, но есть хаки как довнгрейдить необходимую версию ниже чем на сборочном сервере. Такие хаки используются например в firefox.

**Comment by Slach** [comment]
Раз уж тут живой русскоязычный тред образовался ;)
я правильно понимаю что far2l это не консольное приложение?
или надо что-то подкрутить?
https://github.com/elfmz/far2l/issues/313

**Comment by lieff** [comment]
Вот как firefox борется с glibc https://dxr.mozilla.org/mozilla-beta/source/build/unix/stdc++compat/stdc++compat.cpp

**Comment by cycleg** [comment]
> Самая большая пробелма glibc, но есть хаки как довнгрейдить необходимую версию ниже чем на сборочном сервере. Такие хаки используются например в firefox.

У меня сложилось впечатление, что там люди борются скорее за совместимость с какими-то пожилыми системами. Что, однако, никак не отражается на пакетировании того же Firefox.

Но даже статическая сборка не гарантирует единственности исполнимого файла. Все равно остается аппаратная платформа, которая таки разная. Как минимум, файлов будет столько, сколько поддерживаемых платформ, со всеми вытекающими. Так что мне представляется, что от пакетирования все равно не уйти. Лучше включить, наконец, сборку пакета в код far2l и методично ее допиливать по мере необходимости.

**Comment by lieff** [comment]
@cycleg неа, я этот фокус уже проворачивал в реальном софте, как и фаерфокс софт просто начинает поддерживать glibc ниже версией чем на сборочном сервере (а часто софт на дистре с таким старым собрать уже сложно). И получается что один экзешник работает и на убунте и старом центосе и на Astra Linux и на Rosa.

**Comment by unxed** [comment]
Единый экзешник не решает проблему автообновления, увы.

То есть, это приятная и полезная опция, но не универсальное решение.

**Comment by lieff** [comment]
Да, это просто делает архив/пакет более универсальным. Автообновления другая тема, надо делать или из дистрибутива (что должны сделать мэйнтейнеры кучи дистров), или поддержка в самом приложении (проще сделать одному человеку). Можно и так и так: нет твоего дистра - скачал архив со страницы релизов и он будет автообновляться, как хром; есть - ставиш из репы и тоже автообновляется.

**Comment by invy** [comment]
flatpak позволяет как автообновления.
http://docs.flatpak.org/en/latest/flatpak-builder.html

**Comment by lieff** [comment]
Да, я вкурсе flatpack/snap/appimage, они включат в пакет libc-x.xx.so libdl-x.xx.so libm-x.xx.so (около 3.3мб) версии что в автосборке (или можно сделать ссылку на рантайм определенной версии в случае snap). Все же лушче использовать системный или полностью статическую сборку.

**Comment by invy** [comment]
Системный пакетный менеджер да, лучше. Но статическая сборка не понятно чем лучше.

А в чем проблема с deb пакетом?

**Comment by lieff** [comment]
В нем нет проблемы для deb-based дистрибутивов для которого этот deb будет рассчитан. Речь про универсальность, чтобы на странице releases можно было скачать рабочий архив/пакет для как можно большего числа дистрибутивов. Ну типа есть для твоего дистра - ок качай его, нету - ок, скачай вот это, если glibc >= x.xx - должно заработать. Это возможно сделать, чтобы бинарная совместимость была высокой. А главное - это можно сделать без кооперации с сотнями мэйнтейнеров разных дистров.

**Comment by invy** [comment]
deb, rpm уже покрывают львиную долю дистрибутивов. При том разница между ними по сути только в формате и инструкцях для сборк. В довесок добавть flatpak - и все будут рады. Статические сборки имеют тенденцю отваливаться.

**Comment by lieff** [comment]
Не совсем, если просто собрать - они так и будут поддерживтаь glibc сборочного сервера. Если внутри них будет совместимый бинарь - список расширится и для скачивания с релизов это мало чем будет отличаться от обычного архива, с тем отличием, что его уже будет нельзя автообновлять самой программой, т.к. пакетный менеджер поедет. Appimage тоже хороший вариант и тоже без автообновления.

Вот только Appimage не пошлешь мейнтейнерам, а эти учевирсальные deb/rpm можно послать большему количеству мейнтейнерам для включения в репы. Если пользователь ставить из оф репы - для него разница есть, это обновления, мэйнтейнер проверил что пакет ничего не сломал в системе и работает.

Если пользователь ставит не из репы - все отличие от архива/appimage после установки:
 * Пакет значится в пакетном менеджере
 * Файлы установлены от рута в системных путях

А сами бинарки абсолютно те же. Так что плохого добавить еще вариантов для тех где deb/rpm/flatpak нет? Пользователь может вообще не иметь прав устанавивать пакеты и это не такая редкая ституация, appimage и просто архив, который скачал\запустил, тут поможет.

В любом случае бинарная совместимость и пакетизация это разные темы, совместимый бинарь применим и для deb/rpm и только делает их лучше, нужно генерить меньше их вариантов, проще поддерживать.

**Comment by probonopd** [comment]
Автоматическое обновление AppImage:
https://github.com/AppImage/AppImageUpdate

**Comment by lieff** [comment]
Круто :) значит и AppImage и архив можно автообновлять.

**Comment by cycleg** [comment]
Я-то писал об _аппаратных_ платформах, том, что еще называют архитектурой. И тут вариантов решения ровно два: либо собирать и ставить из исходного кода (привет портам BSD), либо вот эта вся ботва с пакетами, репозиториями и т. д. А безумный зоопарк дистрибутивов GNU/Linux -- это сугубо частный случай в том смысле, что первична все-таки множественность архитектур, которые поддерживает ОС (ради этого все затевалось), нежели конкретная комбинация используемого софта и его версий, которая и есть "дистрибутив". Конечно, архитектур гораздо меньше, чем дистрибутивов, и если, допустим, удастся так или иначе свести число сборок к числу архитектур, то это будет только здорово. Но вообще давно понятно, что статические сборки -- тупиковый путь с точки зрения сопровождения ПО.

**Comment by lieff** [comment]
Вот потому firefox пошел по пути совместимости glibc, это действительно проще полной статической сборки, всякие musl в популярных дистрибутивах - боль, на что-то сложное сборка ими не рассчитана. Хотя есть дистры где все собрано со статическим libc - там рассчитана, но они не популярны.

**Comment by unxed** [comment]
> как хром

скорее, как tor

**Comment by asimonov** [comment]
Gentlemen, (sorry for english -- do not have russian keyboard) I have just found far2l and this is exaclty what I wanted for about 10 years! 
I can build it on my Mac, but how shall I install it? I tried to create an apple script, but it is kind of ugly. And I have no idea how to change the icon.

Is there a script already here somewhere that launches built far2l on Mac in new window?

**Comment by lieff** [comment]
@asimonov If I correctly understand - you want to create correct macos app for launcher. For this, you must create macos bundle directory structure: https://stackoverflow.com/questions/1596945/building-osx-app-bundle
i.e. place executable with other install files in far2l.app/Contents/MacOS/
Info.plist is not required, but may be needed for icon.

**Comment by spvkgn** [comment]
PPA с билдами для Ubuntu переехал сюда https://launchpad.net/~far2l-team/+archive/ubuntu/ppa

**Comment by stokito** [comment]
Hi @spvkgn could you mention the PPA in README file so newcomers no need to search it across all issues? Thanks in advance

**Comment by unxed** [comment]
> mention the PPA in README

@spvkgn @elfmz ?

**Comment by asimonov** [comment]
hm, I see potentially similar issue with manually built far2l on macos trying to edit root files on sshfs mounted file system. it just asks for sudo password repeatedly

**Comment by unxed** [comment]
@asimonov https://unix.stackexchange.com/questions/111026/how-to-use-sftp-on-a-system-that-requires-sudo-for-root-access-ssh-key-based-a/111040#111040

**Comment by asimonov** [comment]
hm, insteresting!

but we do not currenlty use sftp -- there is not working far2l sftp plugin yet.

so I use fuse/sshfs mounted file systems. which command do I need to add to authorised_keys on remote system in this case?

**Comment by asimonov** [comment]
I have tried to build far-gvfs today and hit a compilation error.
Did not have time to look at it, but raised an issue.

As I understand far2l-fuse depends on far-gvfs, so I did not try it.

**Comment by unxed** [comment]
@asimonov 

> far2l-fuse depends on far-gvfs

Nope.

**Comment by spvkgn** [comment]
> В ppa сборке не работает повышение привилегий sudo в ubuntu 16.04 при редактировании root файлов, при сборке из сорсов работает.

Исправил, вроде теперь работает. Пробуйте последнюю версию.

**Comment by unxed** [comment]
.rpm for centos/fedora here https://github.com/elfmz/far2l/issues/647

**Comment by unxed** [comment]
@spvkgn там в ppa пакеты перестали собираться

**Comment by elfmz** [comment]
libminizip-dev отменяется. Остаются libxerces-c-dev и libspdlog-dev
Кстати libspdlog-dev ндовольно неприятная либа. Нет, юзать ее может и нормально, но проблем от ее вариативности так сказать - както многовато.

**Comment by elfmz** [comment]
я дико извиняюсь, но появилась новая зависимость - libuchardet-dev - она теперь вместо окаменевшего UCD, который был когдато в вкопипащен в дерево фара и теперь нещадно выкорчеван

**Comment by unxed** [comment]
> я дико извиняюсь, но появилась новая зависимость - libuchardet-dev - она теперь вместо окаменевшего UCD, который был когдато в вкопипащен в дерево фара и теперь нещадно выкорчеван

А где оно вообще используется? Automatic detection по F8 в редакторе — серенькое всегда.

**Comment by elfmz** [comment]
Так в настройках viewer'а включить нуна - viewer'а и editor'а

**Comment by unxed** [comment]
> Так в настройках viewer'а включить нуна - viewer'а и editor'а

Включаю, всё равно automatic detection серенькая, чяднт? Я думал, оно сломано давно, и как-то привык уже))

**Comment by elfmz** [comment]
ну во вьювере работает, правда не из менюшки, а непосредственно при открытии файла

**Comment by elfmz** [comment]
а вообще конечно вопрос интересный, почему там серенькая менюшка

**Comment by unxed** [comment]
> ну во вьювере работает, правда не из менюшки, а непосредственно при открытии файла

А, хм, и прада работает при открытии и во вьювере и в редакторе. А вот из менюхи не работает почему-то.

**Comment by unxed** [comment]
> почему там серенькая менюшка

Я честно думал, что это какой-то артефакт портирования, который не сочли нужным чинить, а UCD не выпиливается только потому что без него вообще сборка развалится)))

**Comment by elfmz** [comment]
да не, рабочая фича, а менюшка похоже просто не была заимплеменчена в форкнутых срыцах)

**Comment by elfmz** [comment]
вродь сделал для вьюера менюху, для эдитора какнить потом

**Comment by unxed** [comment]
> вродь сделал менюху

потестил немножко. в целом работает :) забавно, она в состоянии задетектить "тест €" в UTF-8, но не в состоянии в 1251 (данных маловато для статанализа?). ещё не смогла задетектить "Тест" в utf16le.

но это мелочи. а вот что неприятно, это то, что при открытии вот этого тестового файлика кодировка детектится как UTF-8, и половина контента молча вырезается
[mixed.txt](https://github.com/elfmz/far2l/files/5408349/mixed.txt)

**Comment by elfmz** [comment]
это еще что, она не в состоянии задетектить самое русское слово из трех букв, написанное в CP1251

**Comment by unxed** [comment]
А они там в этой uchardet не очень-то жалуют OEM кодировки, как я погляжу. Для кириллицы есть, а вот с остальными языками не очень. Пожаловался им в багтрекер на греческий и иврит :))

**Comment by unxed** [comment]
Надо, наверное, в README прописать, что, мол, если ваша кодировка не детектится, то жаловаться надо сюда:
https://gitlab.freedesktop.org/uchardet/uchardet/-/issues

**Comment by elfmz** [comment]
ну прежде чем жаловаться надо проверить может проблема в отсутствии страницы в wine-овском коде)

**Comment by unxed** [comment]
Ну ок, тогда формулирвока будет «если ваша кодировка есть в списке по Shift-F8, Ctrl-H, но не автодетектится» :)

**Comment by unxed** [comment]
Вообще странно, что у них поддержка кодировок такая выборочная. По идее же статистические модели одни и те же для одного и того же языка, так что можно было бы все существующие для него кодировки поддерживать. Или, типа, больше кодировок в базе — больше ложных срабатываний? Ну тогда надо выкидывать несколько вариантов и давать юзеру выбрать.

**Comment by elfmz** [comment]
Идеального нет, если греков набереться достаочно много, чтоб один из них открыл багу на эту тему, можно будет заморочиться. Но судя по отсутствии греческой локализации апстрима, это случится как минимум не скоро.

**Comment by unxed** [comment]
Кстати, если мы тут говорим про бету, хорошо бы убрать из UI штуки, которые не работают и вряд ли в ближайшее время заработают, чтоб не смущать юзера.

**Comment by unxed** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=977790
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=977807

https://mentors.debian.net/package/far2l/

**Comment by unxed** [comment]
@spvkgn предложение: собирать два отдельных пакета, far2l и far2l-gui, после того, как wx бэкэнд в отдельный .so вынесут. Можно будет удобно на сервера ставить без 300 мб ненужных там зависимостей

См. #912

**Comment by Slach** [comment]
о, клево, спасибо ребята

**Comment by alexmyczko** [comment]
This is happening at https://github.com/elfmz/far2l/issues/692

**Comment by unxed** [comment]
@spvkgn а по какому расписанию работает сборка в ppa? То есть сколько проходит от коммита до обновления пакета?

**Comment by spvkgn** [comment]
@unxed в ppa включен daily build, т.е запускается раз в сутки, если есть изменения.

**Comment by unxed** [comment]
@spvkgn ещё такой вопросик: как на ланчпаде сделать местный git-репозиторий, автоматически с гитхабом синхронизирующийся? Пытаюсь освоить ланчпад вот

**Comment by jinek** [comment]
So is it distributed anywhere? Or may be package artifact can be downloaded?

**Comment by alexmyczko** [comment]
I have my packaging here: http://sid.ethz.ch/debian/far2l/

and the plan is to get it into the next debian stable release (freeze in January 2023)

**Comment by unxed** [comment]
1st Ubuntu with far2l on board! 🎉
https://releases.ubuntu.com/mantic/

**Comment by alexmyczko** [comment]
@invy can this issue be closed by now?

**Comment by invy** [comment]
> @invy can this issue be closed by now?

Sorry..I didn't track the progress of the issue for years.
You are free to decide what to do. If you think you need to close it, close :)

Have s nice holidays!

**Comment by unxed** [comment]
May be leave it open until at lease Fedora package is ready?

**Comment by invy** [comment]
Or rename this one into Debian and Ubuntu packaging. Close it.
And just create new issues for each distro.

**Comment by unxed** [comment]
I can not close, you can :)

**Comment by jinek** [comment]
Guys, a scrum master is required to close this task.

**Comment by invy** [comment]
Done.
