### ISSUE TITLE
FAR Menu

### ISSUE THREAD

**Issue by KarelWintersky** [elfmz/far2l#846]
Вопрос, почему таким чудовищным, извращенным способом хранится в far2l пользовательское меню?

Почему не как в `FarMenu.ini` или, прости Тьюринг, не JSON/YAML/XML ? 

Его же невозможно редактировать!

**Comment by singalen** [comment]
Пришло время рассказать, откуда взялся Far...

**Comment by KarelWintersky** [comment]
@singalen , come on, расскажи, я внимательно слушаю. 

Заодно расскажи, почему в win-версии используется простая и понятная конфигурация в ini-файле, а здесь, в far2l - чудовищно извращенная версия имитации репозитория.

**Comment by singalen** [comment]
Рассказываю.
Цифра "2" в названии far2l означает, что он был форкнут от версии 2.
Конфигурация была переработана в версии 3. В версии 2 она хранилась в модном тогда реестре Windows.

Уверен, что PR с портом соответствующих изменений радостно примут, если лицензия кода это позволяет.

Пользуясь случам, как один из группы пользователей far2l, прошу сбавить тон. Не последняя причина стагнации оригинального Фара - токсичность его комьюнити.

**Comment by elfmz** [comment]
теперь меню лежит в ~/.config/far2l/settings/user_menu.ini

**Comment by KarelWintersky** [comment]
@elfmz , восторг, спасибо. Намного проще стало.
