### ISSUE TITLE
files operated by far2l are locked

### ISSUE THREAD

**Issue by gitthangbaby** [elfmz/far2l#847]
this gets frequent, so i report:
if files are copied with far2l, they get locked and cannot parse them to other apps.
executing files which were just _copied_ by far2l produce this error:
`/root/anyexecutable`
`sudo: unable to execute /root/anyexecutable: Text file busy`

solution:
terminate far2l and resume action

**Comment by gitthangbaby** [comment]
is the ticket not relevant? thanks

**Comment by elfmz** [comment]
must be fixed since e9911a2
