### ISSUE TITLE
не запускается на gentoo

### ISSUE THREAD

**Issue by OlegMaltzev** [elfmz/far2l#848]
Не получается запустить на gentoo. На секунду открывается окошко и исчезает. Если запускать в терминале - выводится сообщение:
argv[0]='far2l' g_strFarModuleName='/usr/bin/far2l' translation_prefix='/usr/'

**Comment by OlegMaltzev** [comment]
$ export FAR2L_STD=- far2l
$ far2l
argv[0]='far2l' g_strFarModuleName='/usr/bin/far2l' translation_prefix='/usr/'

WinPortInitRegistry: OK 
                        FixedFontLookup: _any='xos4 Terminus' _known_good='xos4 Terminus'
Font 12 x 22 . 1: 'Consolas' - monospaced stable (integer)
OnInitialized: client size = 2 x 1
OnConsoleResized client size: 960 550
key: Colors/Highlight/Group0
RegXxxKeyEx: creating /home/admin/.config/far2l/REG/HKU/c/k-Software/k-Far2/k-Colors/k-Highlight/k-Group0
RegXxxKeyEx: creating /home/admin/.config/far2l/REG/HKU/c/k-Software/k-Far2/k-Colors/k-Highlight/k-Group0
RegXxxKeyEx: creating /home/admin/.config/far2l/REG/HKU/c/k-Software/k-Far2/k-Colors/k-Highlight/k-Group0
RegXxxKeyEx: creating /home/admin/.config/far2l/REG/HKU/c/k-Software/k-Far2/k-Colors/k-Highlight/k-Group0
RegXxxKeyEx: creating /home/admin/.config/far2l/REG/HKU/c/k-Software/k-Far2/k-Colors/k-Highlight/k-Group0
key: Colors/Highlight/Group1
RegXxxKeyEx: creating /home/admin/.config/far2l/REG/HKU/c/k-Software/k-Far2/k-Colors/k-Highlight/k-Group1
key: Colors/Highlight/Group2
RegXxxKeyEx: creating /home/admin/.config/far2l/REG/HKU/c/k-Software/k-Far2/k-Colors/k-Highlight/k-Group2
key: Colors/Highlight/Group3
RegXxxKeyEx: creating /home/admin/.config/far2l/REG/HKU/c/k-Software/k-Far2/k-Colors/k-Highlight/k-Group3
key: Colors/Highlight/Group4
RegXxxKeyEx: creating /home/admin/.config/far2l/REG/HKU/c/k-Software/k-Far2/k-Colors/k-Highlight/k-Group4
key: Colors/Highlight/Group5
RegXxxKeyEx: creating /home/admin/.config/far2l/REG/HKU/c/k-Software/k-Far2/k-Colors/k-Highlight/k-Group5
key: Colors/Highlight/Group6
RegXxxKeyEx: creating /home/admin/.config/far2l/REG/HKU/c/k-Software/k-Far2/k-Colors/k-Highlight/k-Group6
key: Colors/Highlight/Group7
RegXxxKeyEx: creating /home/admin/.config/far2l/REG/HKU/c/k-Software/k-Far2/k-Colors/k-Highlight/k-Group7
key: Colors/Highlight/Group8
RegXxxKeyEx: creating /home/admin/.config/far2l/REG/HKU/c/k-Software/k-Far2/k-Colors/k-Highlight/k-Group8
key: Colors/Highlight/Group9
RegXxxKeyEx: creating /home/admin/.config/far2l/REG/HKU/c/k-Software/k-Far2/k-Colors/k-Highlight/k-Group9
key: Colors/Highlight/Group10
RegXxxKeyEx: creating /home/admin/.config/far2l/REG/HKU/c/k-Software/k-Far2/k-Colors/k-Highlight/k-Group10
ExclusiveHotkeys::SetTriggerKeys: ctrl_left=0 ctrl_right=0 alt_left=0 alt_right=0 win_left=0 win_right=0
SharedResource::UnlockRead: pread: Нет такого файла или каталога
SharedResource::UnlockRead: pread: Нет такого файла или каталога
SharedResource::UnlockRead: pread: Нет такого файла или каталога
GroupNameByID: Выполнено
WinPortFSNotify('/home/admin') - watching
GroupNameByID: Выполнено
WinPortFSNotify('/home/admin') - watching
CommandLine::ShowBackground: done
WINPORT: LoadLibraryEx(/usr/lib/far2l/Plugins/colorer/plug/colorer.far-plug-wide):  0x7fb9480a4bb0
GetProcAddress(0x7fb9480a4bb0, OpenFilePluginW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, ClosePluginW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, GetOpenPluginInfoW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, GetFindDataW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, FreeFindDataW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, GetVirtualFindDataW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, FreeVirtualFindDataW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, SetDirectoryW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, GetFilesW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, PutFilesW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, DeleteFilesW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, MakeDirectoryW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, ProcessHostFileW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, SetFindListW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, MayExitFARW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, ProcessKeyW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, ProcessEventW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, CompareW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, ProcessViewerEventW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, ProcessDialogEventW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, ProcessSynchroEventW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, GetMinFarVersionW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, AnalyseW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, GetCustomDataW) - no such symbol
GetProcAddress(0x7fb9480a4bb0, FreeCustomDataW) - no such symbol
Could not open catalog:
 /usr/share/xerces-c/msg/XercesMessages_en_US.cat
 or /usr/share/xerces-c/msg/XercesMessages_en_US.cat
Cannot load message domain

**Comment by OlegMaltzev** [comment]
Решил проблему пересборкой пакета **dev-libs/xerces-c** с USE-флагами curl и icu.

**Comment by klim8888** [comment]
мерси, помогло
