### ISSUE TITLE
japanese characters break the layout

### ISSUE THREAD

**Issue by undertherain** [elfmz/far2l#849]
looks like the character width is not estimated correctly
![image](https://user-images.githubusercontent.com/1635907/100536047-55f0e800-3261-11eb-8624-3b2b62033efd.png)

**Comment by unxed** [comment]
not reproduced with `ウィキ`
can you please provide sample chars that demonstrate this behaviour?

**Comment by undertherain** [comment]
@unxed  
dont't have it installed at the moment, but I think it should be long enough string

the problem seems to be in estimating when to start trimming it to fit into the column

the example from my screenshot uses `ながいながいながいながい`
(meaning longlonglonglong :)
also it can depend on screen resolution and font size, so
`ながいながいながいながいながいながいながいながい`
thank you :)

**Comment by unxed** [comment]
thanks!
it works ok now in wx backend, but is buggy in gnome terminal (mc is buggy in gnome terminal with this line also, maybe a terminal issue?)

![изображение](https://user-images.githubusercontent.com/1151423/147909469-9df5b002-1da1-4a66-865c-3667481ce2d5.png)

![изображение](https://user-images.githubusercontent.com/1151423/147909485-e53e5b89-4e6c-481b-9453-b4de012328b7.png)

**Comment by undertherain** [comment]
hm
I just rebuilt with wx  and  indeed it kind of works, at expense of Japanese font being kind of small 

normally in gnome terminal Japanese characters take 2x width and far does not seem to be accommodating for that.
this is far with wx, pretty much like yours
![image](https://user-images.githubusercontent.com/1635907/147910897-b5d12317-1aea-4555-aa94-40980e88e06c.png)

and this is midnight commander for reference
![image](https://user-images.githubusercontent.com/1635907/147910928-cd96af5f-c71e-4848-94c2-06ae9ec2b18c.png)

**Comment by elfmz** [comment]
fixed since today
