### ISSUE TITLE
build probelms

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#85]
building on linux mint 18 ru
installed all dependencies
building with make as described in readme

$ make
make[2]: *** Нет правила для сборки цели «/home/unxed/far2l/far2l/bootstrap/farlng», требуемой для «bootstrap/CMakeFiles/bootstrap».  Останов.
CMakeFiles/Makefile2:122: ошибка выполнения рецепта для цели «bootstrap/CMakeFiles/bootstrap.dir/all»
make[1]: *** [bootstrap/CMakeFiles/bootstrap.dir/all] Ошибка 2
Makefile:83: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2

**Comment by invy** [comment]
Точно, как описано в readme? Потому что судя по выводу пути совсем не сходятся.

**Comment by unxed** [comment]
да, действительно, напутал с путями. моя ошибка.
