### ISSUE TITLE
Visual artifacts then running turbo text editor in far2l's VT

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#851]
1. Download and make turbo:
https://github.com/magiblot/turbo

2. Run turbo inside far2l's VT

3. File->New

4. Press "Alt+F", "Right", "Right", "Right"

Not reproduced in GNOME Terminal.

![Снимок экрана в 2020-12-03 00-25-03](https://user-images.githubusercontent.com/1151423/100933296-2dd1e500-34fe-11eb-84ba-44c43a7c3dda.png)

**Comment by elfmz** [comment]
seems introduced by https://github.com/elfmz/far2l/pull/793 ;)

**Comment by unxed** [comment]
Thanks! Still minor artifacts left.

1. Download and make turbo:
https://github.com/magiblot/turbo

2. Run turbo inside far2l's VT

3. File->New

![Снимок экрана в 2020-12-11 00-14-43](https://user-images.githubusercontent.com/1151423/101830773-11f5c100-3b46-11eb-9c28-a9bf6b19e8fe.png)

4. Press "Alt+F", "Right", "Right", "Right"

5. Press ESC

![Снимок экрана в 2020-12-11 00-15-13](https://user-images.githubusercontent.com/1151423/101830788-17530b80-3b46-11eb-824e-052047260e25.png)

**Comment by elfmz** [comment]
вроде дофиксил в ветке tty-intens-colors, но надо бы попроверять..

**Comment by unxed** [comment]
ща попроверяем!

**Comment by unxed** [comment]
собрал, погонял. кажется, порядок!
