### ISSUE TITLE
MacOS: start a new instance from Dock

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#860]
Splitting out of #664.

> it's impossible to start more then one far2l instance from dock or from Applications folder.

References: 
* https://stackoverflow.com/questions/33681565/how-can-i-add-a-menu-to-the-application-in-the-dock
* https://stackoverflow.com/questions/55322034/adding-menu-items-to-the-right-click-app-menu-in-the-dock-casues-them-to-be-re-a
* Storyboard approach (no answers at the time of writing): https://stackoverflow.com/questions/61398962/how-to-create-a-customized-dock-menu-for-my-macos-application-in-the-dock-using

**Comment by elfmz** [comment]
implemented on experiment-touchbar branch
