### ISSUE TITLE
MacOS: far2l should show Fn keys on touchbar

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#861]
Splitting out of #664.
> It's an extremely inconvenient with Apple TouchBar-equipped hardware: there's no way to switch TouchBar to F1-F12 automatically when far2l is active. So, user should make a choice: always have F1-F12 keys for all applications (it's inconvenient with macOs-friendly apps), or use Fn key with far2l.

**Comment by singalen** [comment]
Quick search on SO didn't reveal a ready solution to just switch then touchbar to Fn-keys mode: https://stackoverflow.com/questions/40940433/programatically-forcing-function-keys-on-mac-touch-bar

Maybe we can even implement this old joke and make the touchbar great: 
![MacBook_touchbar_Norton_Commander_34652](https://user-images.githubusercontent.com/151199/102125472-9b371d00-3dfe-11eb-8c51-946e1eece418.jpg)

**Comment by elfmz** [comment]
Cccording to https://forum.latenightsw.com/t/set-touchbar-to-show-f-keys/638
it seems possible to setup F-keys on touchbar per-application basis
Also, implementing that joke doesnt look as too complicated thing: https://developer.apple.com/documentation/appkit/nstouchbar
But i dont have hw to test it on, nor motivation to buy macbook pro for myself... I had experience with using of macbook and , meh.. i didnt like it much, sorry:)

**Comment by elfmz** [comment]
Well, there is some simulator - https://github.com/sindresorhus/touch-bar-simulator. Will try it later. If it will work  - chances of implementation that joke will dramatically raise:)

**Comment by singalen** [comment]
You're in your right!
I may take a stab at it, some day.

**Comment by singalen** [comment]
One will have to override `NSResponder`, which is [buried in wx's implementation](https://github.com/wxWidgets/wxWidgets/blob/master/src/osx/cocoa/window.mm). I wonder if there's a way to access it...

**Comment by elfmz** [comment]
Simulator seems to work, and i've made label on touchbar in branch experiment-touchbar

**Comment by elfmz** [comment]
Even made 12 buttons.. small and useless, dont yet know how to make them big (not just big, but autosized).
There is also problem with stability. Sometimes, not very frequently, it starts withot far2l window opened. Very strange.

**Comment by singalen** [comment]
Woow, it worked for me! Amazing, thanks :D

**Comment by elfmz** [comment]
Now keys are working and have adequate sizes. But for me they still have inadequate colors - black over dark-grey is looking as bad choice, but its default, hm..

**Comment by singalen** [comment]
It's a matter of styling a `NSButton`, AFAIU. This shouldn't be a big deal.
Thank you for showing how to do a `NSResponder`! Now I can take a stab at other Mac-specific functionality.

**Comment by elfmz** [comment]
Штошш... Joke seems to be implemented now. Little bit less fancy colors and layout, but it works and looks alive - button titles correspond to current state.
And its even forwarded through far2l TTY extensions. So if you will run remote linux far2l in mac far2l - it still will behave adequately.

**Comment by elfmz** [comment]
But need bit testing before merging..

**Comment by singalen** [comment]
Amazing :D On it!
It’s news-worthy, at least as a joke. 
What do you think of a Habr article? LOR post? I could write those.

**Comment by elfmz** [comment]
Lets first refactor and test. I didnt write in Objective C for years, sure there're issues.
For instance i'm not sure about correctness use of 'autorelease'. I dont understand clearly how it all works in frame of gcc compilation of normal C++ app.. But it doesn;t crash, thats already good..

**Comment by singalen** [comment]
Looks imperfect yet. I don’t think we need the frame, I see no Fn numbers. Here are photos with and without Control Strip settings. 
![image](https://user-images.githubusercontent.com/151199/102558956-87e8b380-4083-11eb-82e8-ebad609d6741.jpg)

![image](https://user-images.githubusercontent.com/151199/102558980-98992980-4083-11eb-8902-4500bcbfc5d7.jpg)

**Comment by singalen** [comment]
I tried to color the buttons like in the prototype: https://github.com/singalen/far2l/commit/6abe3a98f669f7d412aed69e242c11bdc3f9ff35, but couldn't make them 2-colored.
Maybe using the `range` argument we can set different colors for different parts of a button? I don't know Obj-C at all, so need some assistance here.

**Comment by elfmz** [comment]
There're no Fn numbers cuz there're no Fn keys actually. Numbers are present in FAR's keybar to indicate relation between command and key labeled as Fn, but here're keys labelled with commands directly, no need to show number that alllows to save some space for command description.

**Comment by elfmz** [comment]
What is for me most imperfect - is different width of keys, dont yet know how to make them have same width and use all space at same time.

**Comment by elfmz** [comment]
Вот now good.
BTW i have some sporadic missing buttons on far2l startups - one of 3..5 starts shows empty touchbar, after pressing shift or any other buttons modification they're shown. I dont know if its simulator issue or my bug, can you check if its reproducible on HW by starting far2l multple times (say ~10) and checking if touchbar appeared correctly on each start?

**Comment by singalen** [comment]
Trying to fix a crash. `makeItemForIdentifier()` is called before `init` on my OS.

**Comment by elfmz** [comment]
Try now...

**Comment by elfmz** [comment]
Also tried to find a way to change color on button press - and no success. All that setHighlightsBy setShowsStateBy simple doesn't do anything... Already starting hating Apple again:) Tons of UI methods that just do nothing. Nonobvious memory management - - try to guess who must call retain/release? If guessed correctly - it will work, if not - also work.. sometimes.

**Comment by elfmz** [comment]
Switched to ARC to get rid of manual retains and added extra spacing after F3 and F7 like in real F-keys layouts..

**Comment by singalen** [comment]
Tried it. It works quite amazing, thanks a ton! 
This includes a "new instance" menu item. It would be nice, though, if the new instance was positioned at a bit different screen coordinates, and was focused.

It's strange that you cannot make button change their look when pressed. Other applications seem to have no problem with it.

I didn't see any missing buttons in ~20 restarts. Well, they start with Fx, and then change to normal once the app is completely initialized.

Far's touchbar didn't appear in `--tty` mode.

**Comment by singalen** [comment]
![image](https://user-images.githubusercontent.com/151199/102733281-ab189a80-42f1-11eb-8985-969553e48a49.jpg)
Congrats!
I can take a better picture, in needed.

**Comment by elfmz** [comment]
Good that it was simulator bugs, otherwise i would not know what to do:)
It looks bit too bright on photo. If its not comfortable - you can find most comfortable constants in green:0.8 blue:0.8 and tell me.
Regarding state colors - i've found crutches like this: https://gist.github.com/JanNash/a5ed8dfef4b5ede9db5c
that does this by generating color-filled images, but i dont like it cuz its overcomplicated and requires knowing button size.

**Comment by elfmz** [comment]
Regarding --tty mode  - touchbar does not work in normal terminal but works if you'll oen far2l in terminal of GUI far2l, like far2l over SSH

**Comment by singalen** [comment]
The colors are OK, it's the photo. The lighting in the room was too dim, that's why it looks white.
