### ISSUE TITLE
macOS Big Sur: Segmentation fault on start

### ISSUE THREAD

**Issue by alexey-akhmerov** [elfmz/far2l#866]
If I build far2l with —with-wxmac option I 100% get a Segmentation fault error on start.
Without this option app starts normally.

**Comment by elfmz** [comment]
Yes i also saw that problem on butsur beta. It appeared to be broken wxmac on brew - even simple basic wxwidgets samples crashed on start. However version from Ports worked fine, so try it, if you can.

**Comment by skochinsky** [comment]
On 11.0.1 arm64, I've had it crash when running from /Applications but the bundle in build/install seems to run fine. A permissions issue perhaps?

**Comment by trivee** [comment]
I fixed this ad-hoc by replacing copies of wxmac libraries with symlinks:

cd /usr/local/opt/wxmac/lib
rm -f libwx_baseu-3.0.dylib
rm -f libwx_baseu-3.0.0.dylib
rm -f libwx_osx_cocoau_core-3.0.0.dylib
rm -f libwx_osx_cocoau_core-3.0.dylib
ln -s libwx_baseu-3.0.0.5.0.dylib libwx_baseu-3.0.0.dylib
ln -s libwx_baseu-3.0.0.5.0.dylib libwx_baseu-3.0.dylib
ln -s libwx_osx_cocoau_core-3.0.0.5.0.dylib libwx_osx_cocoau_core-3.0.0.dylib
ln -s libwx_osx_cocoau_core-3.0.0.5.0.dylib libwx_osx_cocoau_core-3.0.dylib

Other dylibs may need similar treatment but far2l doesn't seem to have problems with those at startup.

**Comment by unxed** [comment]
is it still actual?

**Comment by trivee** [comment]
Not reproducible for me anymore (fairly recent master build from sources under brew, MacOS 11.2.3, wxlib 3.1.5).
