### ISSUE TITLE
NetRocks options on session 

### ISSUE THREAD

**Issue by zerochka** [elfmz/far2l#874]
There where "Remember last used directory" option in netbox plugin.
It was very usefull
 
![2021-01-02 11 27 26](https://user-images.githubusercontent.com/17930919/103453695-85c25e00-4ced-11eb-9d5b-1c3cbe10df9a.jpg)

**Comment by zerochka** [comment]
If it will be released then exit to list of connections from selected connection above the folder where you entered is wrong 

netbox exit to list of connections after / path, for example - I don't enter any path in directory path and go in /home/mylogin 
to change this path to /var/www/html a need to change path ../../,  - press on .. I see list of connections on NetRocks panel not /home

**Comment by elfmz** [comment]
Implemented such option but not as per-site option, but as global NetRocks option (if F9/Plugins configuration/NetRocks". Its not due to technical problems, just i think that its not a kind of option that need to be saved on per-site bases and thus will only pollute that window. Let me know if my assumption wrong

**Comment by elfmz** [comment]
Что касается второй проблемы, если я правильно понял, то это не бага а типа фича. Я не планировал 100процентого повторения поведения нетбокса, так что работает оно именно так - чтобы можно было быстро выйти из сайта не бредя до его реального корня. В тех случаях когда хочется визуально бродить до корня вместо выхода - нужно указать в настройках сайта полный путь к изначальной рабочей директории. То есть  написать там прям вот: /home/mylogin - тогда путь будет интерпретироваться как поддиректория от / и все будет выходить в ожидаемом и визуально очевидном порядке.

**Comment by zerochka** [comment]
Ок, если он куда то в кеш будет запоминать место куда заходил на сайт в какой то определенной сессии - то этого будет достаточно и не надо будет использовать путь до директории в данном случае. Как это место почистить в случае если оно пропало? Или оно автоматически вывалится в коренной путь указанный в настройках? Как оно себя поведет если путь "пропадет" ? 

В моем использовании сейчас это выглядит как: зашли на сайт, правим файлики, отвлеклись на полчасика, сессия разорвалась не восстановилась и приходится вспоминать "а где я был? " у нетбокса проблемы вспоминать нет. Я захожу еще раз в это соединение и он заходит на то место где был в прошлый раз. И это удобно. 

Собсно нетрокс достаточно долго восстанавливает сессию, но если не отменять действие вроде не роняет far, как у меня случилось в прошлый раз, когда он думал секунд 20, что я уже передумала и решила отменить операцию. 

Пока тщательное восстановление сессии спасает от необходимости опять идти с корня. Но указание пути в настройках как бы "отрезает" тебе руки. А для того чтоб быстро выйти в с список соединений в фаре нужно просто выбрать option f2 и выбрать Netrocks

**Comment by zerochka** [comment]
еще одна фича нетбокса которой я пользовалась  - для переноса соединения на другой фар/компьютер достаточно сохранить его (соединение) как файл ( скопировать на другую панель) а в другом фаре скопировать на панель нетрокса - все настройки импортируются. Таким образом я таскала все свои многочисленные соединения от сайтов. У меня их пара экранов. Было очень удобно. Обидно что нетрокс не умеет так. кстати winscp соединения я также переносила в netbox в свое время переезжая между версиями far

**Comment by elfmz** [comment]
Оно директорию сохраняет в соответствующую опцию настроек сайта. Соответственно можно пойти в настройки и она будет там.
А когда это нетрокс долго восстанавливает сессию? Вроде все быстро должно быть.

**Comment by elfmz** [comment]
по поводу импорт-экспорт сайата - сделаю как нить

**Comment by elfmz** [comment]
Сделал возможность импорта нешифрованных паролей в sites.cfg - если у сайта не будет значения Password но будет PasswordPlain, то он втянет последнее в качестве нешифрованного пароля

**Comment by zerochka** [comment]
> Сделал возможность импорта нешифрованных паролей в sites.cfg - если у сайта не будет значения Password но будет PasswordPlain, то он втянет последнее в качестве нешифрованного пароля

спасибо, Пароли можно и ручками конечно переписать, хотя бы все остальное чтоб засосало :) 

Что, теперь можно копировать на панель нетрокса "соединения" ? И оттуда?

**Comment by zerochka** [comment]
а как все эти прелести теперь можно накатить себе на фар  на маке? переставить его еще раз ?

**Comment by elfmz** [comment]
Нет, импорта/экспорта по ф5 нету пока, это я сделал просто упрощалку жизни для стороннего импорта на скриптах.
Пересобирать еще раз

**Comment by elfmz** [comment]
Теперь импорт/экспорт по ф5 уже есть.

**Comment by zerochka** [comment]
СПАСИБО СПАСИБО  СПАСИБО !!!!

**Comment by zerochka** [comment]
переставила. Не работает :(

**Comment by elfmz** [comment]
Ну так у него свой формат а-ля ини файлы, а не нетбоксовский. У нетбокса там xml - этож целый парсер надо тянуть или велосипедить.

**Comment by zerochka** [comment]
ну понятно. Надо будет переписать их автоматически сессии эти все.

**Comment by zerochka** [comment]
а где можно узнать формат netroсks файлика (? все опции)

**Comment by elfmz** [comment]
Нуу, както так:
LoginMode= 0 - NoPassword, 1 - AskPassword, 2 - SavedPassword
Port - очевидно
Username - очевидно
Directory - очевидно
Password/PasswordPlain - очевидно
Protocol - очевидно
Options_* - все сложно

**Comment by zerochka** [comment]
Вот опции как раз и интересуют 
тип соединения/и тп ? путь к ключу ...

**Comment by elfmz** [comment]
Ну это по коду надо смотреть, в целом у каждого протокола они свои и могут изменяться от балды. Можно подытожить както и запилить статью в вики или в discussions, т.к. это выходит за рамки 'бага'.
Релевантные ссылки на код: 
https://github.com/elfmz/far2l/blob/master/NetRocks/src/UI/Settings/ConfigureProtocolFile.cpp#L70
https://github.com/elfmz/far2l/blob/master/NetRocks/src/UI/Settings/ConfigureProtocolFTP.cpp#L135
https://github.com/elfmz/far2l/blob/master/NetRocks/src/UI/Settings/ConfigureProtocolNFS.cpp#L84
https://github.com/elfmz/far2l/blob/master/NetRocks/src/UI/Settings/ConfigureProtocolSFTPSCP.cpp#L163
https://github.com/elfmz/far2l/blob/master/NetRocks/src/UI/Settings/ConfigureProtocolSMB.cpp#L72
https://github.com/elfmz/far2l/blob/master/NetRocks/src/UI/Settings/ConfigureProtocolWebDAV.cpp#L99
Формат, а по сути escaping, которым этим опции кодируются, чтобы быть single line, вот тут: https://github.com/elfmz/far2l/blob/master/utils/src/StringConfig.cpp
