### ISSUE TITLE
Files in subfolders of the created archive are not displayed

### ISSUE THREAD

**Issue by AlexSinyakov** [elfmz/far2l#877]
A zip archive created in far2l archive containing files in subfolders, when entering it on the far2l panel does not display files in folders. As if there is nothing in the subfolders

**Comment by elfmz** [comment]
Issue looks similar to fixed month ago: https://github.com/elfmz/far2l/commit/075daea0ded68649da33c233407508636560d22a
What revision of far2l are you using (its usually displayed in title bar)

**Comment by elfmz** [comment]
closing as likely fixed
