### ISSUE TITLE
Far2l freezes for 20-40 seconds after executing each line in the user menu (F2) list of commands

### ISSUE THREAD

**Issue by alk0** [elfmz/far2l#890]
Last tested with a08e1e0c
After invoking anything from the user menu (F2, global or local), far2l seems to wait (freeze) for about 30 seconds (not fixed) after executing each line from the list of commands. Waiting cannot be interrupted by Esc, Space, Ctrl+C, Ctrl+Break, Ctrl+D (or anything else that I've tried). A minimal test case — `FarMenu.ini` (using a `:` "no-op" shell command):
```
:  Do nothing
    :
```
Can it be because of 578d6846?.. Or am I missing something completely?

**Comment by elfmz** [comment]
it cannot be due to thatit was because of https://github.com/elfmz/far2l/commit/a08e1e0c89dda5e6050fbb572471082ca562fadf
