### ISSUE TITLE
NetRocks: Must retry to connect after RST received

### ISSUE THREAD

**Issue by ds-voix** [elfmz/far2l#891]
There is an old trick against stupid bots: firewall sends RST on the first connection attempt.
Most of client software (such as openSSH, netBox from the old FAR, mail clients, web browsers and so on) does the silent retry after the first RST.
But NetRocks immediately throws the error:
![image](https://user-images.githubusercontent.com/11455155/105218373-1dd19b80-5b66-11eb-956d-6915e7635c3f.png)

It's rather inconvenient, but can be patched by few lines of code.
In future, the set of options for the similar hacks inside the NetRocks interface will help to build the highly customizable tool. A kind of swiss-knife, which was the netBox.

**Comment by elfmz** [comment]
Added such option to SFTP/SCP protocol settings. Also it works for any kind of connect failure, not only RST but timeouts too. Dont see an issue here, right?.

**Comment by ds-voix** [comment]
Excellent!
After 12b5b42387f86c7a2c15631a6965b6fdf831f823, the connection repairs transparently after RST.
* I also see both new protocol options. At least, (0→1),1,2,99 connection retries works as expected. Tested by:
`tcpdump … port 22 and "tcp[tcpflags] & (tcp-syn) != 0"`

Timeout works as well.
