### ISSUE TITLE
NetRocks: There must be customizable connection timeout

### ISSUE THREAD

**Issue by ds-voix** [elfmz/far2l#893]
The hardcoded timeout is too short in the number of cases.
There must be an option to enlarge it up to (at least) 120 seconds. To bypass some misconfigurations at the server side.

Example: openSSH uses "UseDNS=yes" by default.
It leads to about 60 seconds lag while connecting to host with broken DNS.

**Comment by elfmz** [comment]
Added such option to SFTP/SCP protocol settings
