### ISSUE TITLE
Registry corruption while saving parameters

### ISSUE THREAD

**Issue by ds-voix** [elfmz/far2l#897]
After saving settings, on the next launch far2l complains about some broken macros.
In my case those are alt5 (editor, viewer, shell). And yes, they are in fact broken.
See attached REG archives (all but history). I guess that there must be a significant number of macros _(or reg branches?)_ to reproduce the problem. Therefore, the simplest way to reproduce is to use the prepared "REG-ok.tar.gz".
[REG-broken.tar.gz](https://github.com/elfmz/far2l/files/5880866/REG-broken.tar.gz)
[REG-ok.tar.gz](https://github.com/elfmz/far2l/files/5880867/REG-ok.tar.gz)

![editor-alt5](https://user-images.githubusercontent.com/11455155/106005998-d5663080-60c5-11eb-8a13-39c0aba85466.png)
![shell-alt5](https://user-images.githubusercontent.com/11455155/106006002-d5fec700-60c5-11eb-9322-704ee3242d48.png)
![viewerl-alt5](https://user-images.githubusercontent.com/11455155/106006004-d6975d80-60c5-11eb-91b4-848b4cbe5b50.png)
- Most of macros was taken from [this git](https://github.com/corporateshark/far2l-macros.git).

**Comment by elfmz** [comment]
Are there any other problematic macros except Alt5
I noted that this macro's reg key has extra empty string in beginning, that is incorrect: https://github.com/corporateshark/far2l-macros/blob/master/k-Viewer/k-Alt5/v-Sequence
Compare it to this one, that is correct: https://github.com/corporateshark/far2l-macros/blob/master/k-Viewer/k-Alt3/v-Sequence
Its not a 'normal' config file, so such empty line makes initial value to be little bit garbage, that likely causes far2l to save garbage when it comes time to save it.

**Comment by ds-voix** [comment]
Yes, of course You are right!
There's extra beginning newline (0x0A) in each of "k-Alt5/v-Sequence". Far2l just not complains for it.
So, it's still the bug, but minor one.

I'll send the fix to  https://github.com/corporateshark/far2l-macros

**Comment by elfmz** [comment]
so, closing
