### ISSUE TITLE
Recommended fonts

### ISSUE THREAD

**Issue by techtonik** [elfmz/far2l#90]
What fonts can be used with `far2l`? The ones I am trying are awful. Also, how to change the font without removing `~/.far2l`?

**Comment by invy** [comment]
I like:
Ubuntu Mono, Liberation Mono, Droid Mono

**Comment by elfmz** [comment]
DejaVu Sans Mono Book also very good. Somebody likes Terminus.

**Comment by techtonik** [comment]
Is  there any criteria for autodetecting some suitable fonts? It looks that some autodetection is being made:
```
WinPortInitRegistry: OK 
FixedFontLookup: Zelda DX TT BRK
```

![far2l-fonts](https://cloud.githubusercontent.com/assets/515889/18661906/96aecb44-7f20-11e6-96ea-f33734f26b04.png)

**Comment by elfmz** [comment]
first found in system fixed (monospaced) font selected by default

**Comment by invy** [comment]
Actually here is the problem. In my system it first found font is unusable. I think, far should look for system settings and for well known fonts first.

**Comment by elfmz** [comment]
It tries to do that. What mean unusable? Is it possible to detect somehow except of hardcoded well-known list?

**Comment by invy** [comment]
I have the monospace font wwhich is not usable in terminal and does contain "strange" characters and somehow exactly this font is chosen by Far as default.

**Comment by elfmz** [comment]
probably need to check what is returned as wxFontFamily wxFont::GetFamily() for such fonts..

**Comment by invy** [comment]
![image](https://cloud.githubusercontent.com/assets/833865/18670219/129df928-7f3f-11e6-909c-706f8f5cb55a.png)

**Comment by techtonik** [comment]
It is cool to be able to run `far2l` with any font, but for proper usage it is nice to filter all installed fonts that:

1. monospace
2. render window drawing glyphs correctly
3. don't have spaces between drawing glyphs

**Comment by techtonik** [comment]
Is it possible to sorting font list for selection according to some weights?
