### ISSUE TITLE
add an option to toggle line wrap in VTE

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#900]
Currently lines of text in far2l's Virtual Terminal Emulator (VTE) are automatically wrapped by window size. I propose to introduce an option to disable such wrap. Of course, «tails» of lines will not be visible in Ctrl+O mode, but it would be possible to see them by pressing F3 and doing horizontal scroll.

With such option it would be much easier to read console apps output (like compiler logs).

**Comment by elfmz** [comment]
dup for https://github.com/elfmz/far2l/issues/865
