### ISSUE TITLE
Crash closing editor

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#907]
Sorry, this is about best "stack trace" I can get.
Note that the vector has zero size.
A race condition? At this time, colorer is actively working on coloring a large (30M, is it that large?) file in editor.
git revision f91e5ffa.

![Screen Shot 2021-02-03 at 15 36 00](https://user-images.githubusercontent.com/151199/106823341-a0159180-6635-11eb-84fe-263868e1a5aa.png)

**Comment by elfmz** [comment]
There is no other thread for race condition, colorer 'background' processing driven by 'idle' event coming on main thread.
However there was wrong deinitialization order that potentially could cause this. Check now (if it reproducible somehow).

**Comment by elfmz** [comment]
ping?

**Comment by singalen** [comment]
It's been good for me on the same set of files so far.
But it's a rare condition, so I couldn't tell for sure.
