### ISSUE TITLE
Copy to clipboard full path or short name of current file in a panel, Mac OS X

### ISSUE THREAD

**Issue by strim** [elfmz/far2l#909]
Windows Far2 used to copy name of the currently highlighted file in a panel to clipboard with shortcuts Ctrl+Ins or Ctrl+C. Same was for any text entered by user to command-line prompt under the panels. This way I could do, for example, Ctrl+F to paste full path of the current panel file to the prompt, and next to grab it with Ctrl+Ins to clipboard. That was great to get full path from Far and to go to other apps with it. 

Far2l at Mac OS X is able to paste to under-panel prompt full file path and short file name with Ctrl+F and Ctrl+Enter. However, I found no hotkey to grab the prompt content to Mac clipboard. Neither Cmd+C, nor Ctrl+C works here. Is there any way to reach my goal? Thank you,

**Comment by elfmz** [comment]
Ctrl+Ins works on my linux system, but right now i can't what happens on macos. Also try Cmd+Ins.

**Comment by strim** [comment]
Thank you for checking on Linux. Since neither Apple laptops, nor Apple keyboards have Insert key, there is no way to try the shortcut as suggested. I guess even for PC keyboard connected to Mac OS it won't support any meaningful behavior for Ctrl+Ins or Win+Ins combinations.

**Comment by singalen** [comment]
There's a #575 reporting the same problem, but it was closed – wrongfully, I believe. The "it's the original Far behavior" is not a good motivation to a missing feature.

My suggestion: Use `Ctrl-C` to break a process where there is a running process; otherwise, make it copy the current file/selection path(s). On Mac, it's even simpler, `Cmd-C` should work.

I'll see if I have the time to make a PR.

**Comment by strim** [comment]
Thank you for the reference to the same issues reported. Now at least I know that switching panels off with Cmd+O helps to copy the prompt content with Cmd+C. Not ideal but gives the way to grab file path. Thank you!

**Comment by singalen** [comment]
Couldn't quickly figure out how to distinguish Cmd from Ctrl events 8(
@elfmz, may I ask for some help? 
I see that one part would be to add a `case KEY_CTRLC` to `far2l/edit.cpp:1356`, but how do I distinguish Ctrl from Cmd?

**Comment by elfmz** [comment]
Currently they're equivalent, why you want to distinguish? [Ctrl|Cmd]+C should work fine as desribed above

**Comment by singalen** [comment]
If they are, then probably there's no reason to, thanks! Then I will continue working on my patch.

**Comment by singalen** [comment]
@elfmz, sorry, one more question.
Currently, `KEY_CTRLC` lands in `FileList::CopyFiles()`.
Do you have any idea what is it supposed to do? Looks like it builds up a buffer with the currently selected file names, but then it just does nothing with it.
Is it supposed to copy files into system clipboard? Or just the file names?

It's a good function, but I don't remember it ever working in Windows Far as well. I believe it's a dead code. What do you think?

**Comment by elfmz** [comment]
Yes, its a remains of Windows. Ctrl+C copied files into clipboard and then you could paste them in Explorer.
I think CopyFiles should be removed now at all.

**Comment by strim** [comment]
I remember at Windows there was copying of selected file names into system clipboard. 
That was pretty handy function of Far!

**Comment by singalen** [comment]
Right. The way it worked:
* if there is something in a command line, copy it. 
* if files were selected on panels, copy their names. 
* otherwise, copy the file under cursor’s name. 
I’ll send a PR to do it.

**Comment by strim** [comment]
Thanks a lot, @singalen

**Comment by strim** [comment]
My sincere thanks for resolving this issue in https://github.com/elfmz/far2l/pull/922.
I can copy to clipboard full path and selected files. Dreams come true, while far2l becomes more and more gorgeous!
