### ISSUE TITLE
[Mac specific?] Start-up speed of Wx version

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#910]
On a fairly new hardware (2.9GHz i7 MacBook Pro 2016), a cold start of a GUI version takes 3-4 seconds, a warm start - about 1s.
It would be really nice to reduce the time.

**Comment by elfmz** [comment]
can it be that your wx compiled in debug flavour?

**Comment by singalen** [comment]
It's wx installed from MacPorts. Hardly.
I'll profile it when I can.

**Comment by elfmz** [comment]
As i understood from topic, staring far2l --tty in terminal works much faster, correct?

**Comment by singalen** [comment]
In fact, I never tried it. tty launch was not super-fast either, it took something under 1s.

**Comment by elfmz** [comment]
cold or hot?

**Comment by singalen** [comment]
Hot.

**Comment by elfmz** [comment]
Check on branch investigate-910. Note that its not very tested, just rough initial code to check.

**Comment by singalen** [comment]
Fells ways faster!

**Comment by elfmz** [comment]
Check now if it became even better. I moved highlighting data to ini file

**Comment by elfmz** [comment]
Plz note that on 1st run it will still use registry, so take into account only 2nd+ runs

**Comment by singalen** [comment]
Subjectively, I cannot see the difference between 18a1bd8ca61124cbc92c8224e6b716edf73c20a9 and be944a95c3886a4e2e246ac1fa47646b11d15c7e. I can measure the startup time precisely, if you wish.

BTW on one of the runs it crashed with:
```
Thread 11 Crashed:
0   libsystem_kernel.dylib        	0x00007fff687e833a __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff688a4e60 pthread_kill + 430
2   libsystem_c.dylib             	0x00007fff6876f808 abort + 120
3   com.far2l                     	0x00000001069e50b1 InvokePrevSigaction(int, __siginfo*, void*, sigaction&) + 897
4   com.far2l                     	0x00000001069e4d16 SafeMMap::sSigaction(int, __siginfo*, void*) + 310
5   libsystem_platform.dylib      	0x00007fff688995fd _sigtramp + 29
6   ???                           	0x2d02ef8d5a05df1b 0 + 3243418072039939867
7   com.far2l                     	0x000000010697a11f FilePositionCache::~FilePositionCache() + 63
8   com.far2l                     	0x000000010689d014 ControlObject::~ControlObject() + 356
9   com.far2l                     	0x0000000106953076 MainProcessWithInterThreadCallsDispatching(UnicodeString&, UnicodeString&, UnicodeString&, int, int) + 2406
10  com.far2l                     	0x0000000106953ef0 FarAppMain(int, char**) + 2912
11  com.far2l                     	0x0000000106872663 WinPortAppThread::Entry() + 19
12  libwx_baseu-3.1.dylib         	0x000000010737d52c wxThread::CallEntry() + 30
13  libwx_baseu-3.1.dylib         	0x000000010737cf8e wxThreadInternal::PthreadStart(wxThread*) + 1740
14  libsystem_pthread.dylib       	0x00007fff688a5109 _pthread_start + 148
15  libsystem_pthread.dylib       	0x00007fff688a0b8b thread_start + 15
```

**Comment by elfmz** [comment]
Yes there was bug, just fixed.
Check if ~/.config/far2l/highlight.ini created

**Comment by singalen** [comment]
Yes it is.
Thank you very much!
