### ISSUE TITLE
Very slow console output

### ISSUE THREAD

**Issue by AlexFromChaos** [elfmz/far2l#911]
Пользовался какое-то время far2l без каких-либо нареканий, потом заметил, что не заходит в rar5-архивы, т.к. не было соответствующей сигнатуры rar5-заголовка в коде. Обновился на последний far2l и сразу заметил, что стал сильно тормозить консольный вывод, вплоть до того, что банальный unzip для архива с кучей мелких файлов стал выполняться чуть ли не вечность, т.к. выводит каждое имя файла, а вывод очень медленный.

В последнее время были какие-то глобальные изменения в коде консольного вывода far2l? Куда копать?

**Comment by AlexFromChaos** [comment]
нашел, a0ed123301a3603c6ac5bb80c4c5e140b78e1459 от 25 октября всё поломал. :(

**Comment by elfmz** [comment]
Ну вобщем если в выводе нету диактрических символов то должно работать так же как раньше. Во всяком случае я разницы не вижу у себя в убунте, но посмотрю что могло сломаться.
В вашем выводе случайно не присуствуют в большом количестве буквы й или ё или какие нить китайские ероглифы?

**Comment by elfmz** [comment]
Можете проверить поведение на git checkout investigate-911 ?

**Comment by AlexFromChaos** [comment]
Проверил с `investigate-911`, на ней тоже тормозит.

> Ну вобщем если в выводе нету диактрических символов то должно работать так же как раньше. Во всяком случае я разницы не вижу у себя в убунте, но посмотрю что могло сломаться.
> В вашем выводе случайно не присуствуют в большом количестве буквы й или ё или какие нить китайские ероглифы?

Диакритических знаков в выводе вообще нет, медленно выполняются даже команды с чисто ASCII-выводом, как то `ls -l /sbin/`.

До a0ed123301a3603c6ac5bb80c4c5e140b78e1459 эта команда выполняется мгновенно, а с коммитом - секунд 8, как будто весь вывод в консоль замедлился в сотни раз.

Это дебиан, наверняка `libwx_*.so` какой-то древней версии, теоретически поиск диакрит. символов мог просто что-то замедлить в разы, а на тормозных wx-либах это умножило эффект. Попробую в виртуалке с 20.04 ту же самую версию far2l для сравнения.

**Comment by elfmz** [comment]
а сейчас? (на той же investigate-911)

**Comment by AlexFromChaos** [comment]
Теперь быстрый вывод (точнее, мгновенный).

Потестил на вмке 20.04, получается такая статистика для `ls -l /sbin/`:

1. Debian 10 и актуальная версия с master - вывод медленнее всего
2. 20.04 и актуальная версия с master - вывод субъективно быстрее
3. Debian 10 и код без a0ed123301a3603c6ac5bb80c4c5e140b78e1459 - вывод мгновенный

У них разные версии libwxgtk3.0-dev, на 20.04 даже имя пакета немного другое, мб реально дело просто в общем замедлении вывода в консоль, которое на старых wx-либах сильнее заметно.

**Comment by AlexFromChaos** [comment]
`time tar -xzvf file.tar.gz` для архивов с кучей мелких файлов хороший бенчмарк:

```
real    0m25,342s
user    0m1,467s
sys     0m1,088s
```

```
real    0m1,670s
user    0m1,426s
sys     0m0,434s
```

Т.е. для одного конкретного файла разница в 15 раз.

**Comment by elfmz** [comment]
Ну т.е. в investigate-911 все ок?

**Comment by AlexFromChaos** [comment]
> Ну т.е. в investigate-911 все ок?

Да

**Comment by elfmz** [comment]
У меня в 18й особо разницы сходу на глаз не видно, но хорошо видна разница если делать 
cat /dev/urandom и потом Ctrl+C - в investigate-911 прерывается сразу а в мастере чутка ждать приходится.
Забавно что изменение изза которого это произошло было задумано как оптимизация - типа уменьшается количество memcpy, но - за счет большего времени проведенного под локом на буфер вывода. И таки да - если прорисовка медленная то будет влиять плохо..

**Comment by AlexFromChaos** [comment]
Ну по тесту с `tar`'ом получается, что для убунты замедление всего лишь 25%
