### ISSUE TITLE
NetRocks:scp directory with spaces not working

### ISSUE THREAD

**Issue by qeepcologne** [elfmz/far2l#916]
i am using NetRocks:scp to connect to other servers via ssh.
directory with spaces causes multiple problems which is a real blocker
example directory name "02 Feb - 13.02.21-15.02.21 Lorem, Ipsum (Dolores)"
- creation of such directories is working
- walk in the directory not working
- deletion is not working

**Comment by unxed** [comment]
similar bug: if path to RSA key file for sftp contains spaces, it fails also

**Comment by qeepcologne** [comment]
wow thanks a lot for the immediate fix.
