### ISSUE TITLE
far2l вылетает после ошибки netrocks'а при переполнении диска на сервере

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#919]
кейс такой: надо синхронизировать пару папок, т.е. я копирую нетроксом некую папку поверх такой же папки на сервере, выбирая «skip» при совпадении файлов. в какой-то момент вылезает ошибка:
![изображение](https://user-images.githubusercontent.com/1151423/108723046-dfe4e000-7534-11eb-8c77-7dbf64ff121c.png)

 выбираю skip снова, far2l вылетает. в лог при этом падает вот такое:
```
CurrentSiteDir: out='/dat/www/runcitytest.org/img/storage/'
NetRocks::PutFiles: _dir='<sftp:unxed@www-test.runcity.org>//dat/www/runcitytest.org/img/storage' SrcPath='/dat/www/runcity.26416: stat (2)
26416: write error - SFTP server: Failure
OnFilePut: write error - SFTP server: Failure
26416: HostRemoteBroker: bad command (0xf28479b9)
26416 HostRemoteBrokerMain: HostRemoteBroker: bad command (0xf28479b9)
26416: HostRemoteBrokerMain: END
WinPortInitRegistry: OK 
```

**Comment by elfmz** [comment]
Попробовал сэмулировать ситуацию наколенными способами, апликуха у меня не падает, но проблема с IPC командами присутствует, вроде пофиксил.

**Comment by unxed** [comment]
> Попробовал сэмулировать ситуацию наколенными способами, апликуха у меня не падает, но проблема с IPC командами присутствует, вроде пофиксил.

Спасибо!
Нечем сейчас перепроверить, забитые диски уже почищены. Создам новый тикет, если снова вылезет, ок?

**Comment by elfmz** [comment]
Ну, в целом хотелось бы все же увидеть стек падения с запущенным под gdb far2l. Падать он в такой ситуации все же не должен был, может там баг на баг наложился..

**Comment by unxed** [comment]
Как только где-нибудь забьется какой-нибудь очередной диск — попробую сделать, ок!
