### ISSUE TITLE
Stale files in ~/.config/far2l/askpass_ipc/?

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#921]
I have 80 files in `~/.config/far2l/askpass_ipc/`, some dating back by months. 
Is this a problem or did I kill far2l so many times?

**Comment by elfmz** [comment]
Looks like kill, or may be system shutdown caused left files. I have 261 files there :)

**Comment by unxed** [comment]
Shouldn't such files reside in ~/.cache/far2l, not ~/.config/far2l?

**Comment by singalen** [comment]
Anyway, I believe we should have a facility to clean them up. Or even move them to `/tmp` and let the system reboot take care of them.

**Comment by elfmz** [comment]
Aren't files in /tmp can be erased at any time without any hint about that? In such case sudo will stop working in currently running far2l until restart.

**Comment by singalen** [comment]
First time I hear about it, but [looks like it's right](https://serverfault.com/questions/377348/when-does-tmp-get-cleared/377349). Yuck, I totally understand why you don't want to mess with this zoo.
Then, probably, cache is the second best place. And again, it would be nice to have some simple garbage collector – like, delete files created before the last system reboot.

**Comment by unxed** [comment]
As for askpass_ipc, maybe the better place is something like /run/user/UID/far2l/ ?

**Comment by unxed** [comment]
also, shouldn't sr mechanism be applied to any keyfile access to avoid files damage by simultaneous writes?

**Comment by elfmz** [comment]
> As for askpass_ipc, maybe the better place is something like /run/user/UID/far2l/ ?
Ugh, too many locations, let stay with .cache for now. Also not sure about portability of such location.

**Comment by elfmz** [comment]
> also, shouldn't sr mechanism be applied to any keyfile access to avoid files damage by simultaneous writes?
Nope, inifiles loaded/stored atomically. The reason why clipboard still needs lock is that clipboard action spans over multiple loads/saved. BTW. may be this lock will be removed in future, by some little change in clipboard handling code.

**Comment by singalen** [comment]
The stale files don't appear in such numbers now. I guess this resolves the issue.
