### ISSUE TITLE
multiarc: dollar sign needs to be escaped in custom format archiver commands

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#930]
test sample
[dollar_sign_sample.zip](https://github.com/elfmz/far2l/files/6053215/dollar_sign_sample.zip)
file $test.txt is listed, but could not be extracted

**Comment by elfmz** [comment]
В данном случае проблема была вызвана как раз таки искейпингом внутри файллиста. Проблему решало убирание буквы Q в %%LMN
Но попутно обнаружилась (и справилась) другая потенциальная проблема, вызванная последними изменениями. Дело в том что новый парсер ини файлов умеет в искейпинг спецсимволов в строках. Но при этом он умеет работать и с не-искейпед строками. Признаком того что строка заискейплена для него являются кавычки в начале и конце строки.
Так вот, поскольку мультиарк юзает тот же парсер, то и на него распространяется такое же правило - если какая то строка начинается и заканчивается на двойные кавычки - внутри нее спецсимволы должны быть заискейплены. Как минимум это означает отсутствие одиноких висячих \. Парсер ини файлов в принципе старается вести себя максимально совместимо, и потому странные комбинации \.. он просто вставляет напрямую, но при этом он сильно матерится в stderr. Но не странную комбинацию он пропарсит согласно правилам, то есть \n превратит в перевод строки, например.
Потому в custom.ini или строка не должна быть в кавычках, или должна быть заискейплена как полагается.

**Comment by unxed** [comment]
Понял, спасибо! Ещё к вопросу о парсере .ini файлов — какие там правила по комментированию? Каким символом отделяются каменты, могут ли они начинаться в произвольном месте строки, или только в начале?

**Comment by elfmz** [comment]
коменты мона на ; или # а вообще исторически в инишниках принято на ;

**Comment by elfmz** [comment]
только в начале

**Comment by unxed** [comment]
> только в начале

во, я на это наткнулся уже как-то, когда что-то не хотело работать, а я и не заметил, что камент в конце строчки по привычке повесил

**Comment by elfmz** [comment]
Запилил статью в вики: https://github.com/elfmz/far2l/wiki/INI-files-format
Подохренел от глюкавости редактора этой вики. Ею пользоваться просто невозможно. По тексту моей статьи это кстати заметно.

**Comment by unxed** [comment]
Да отличная статья, всё понятно! :) Не понятно только, как, скажем, парсер воспримет значение 12121212 — как десятичное восьмизначное число, или как 4 шестнадцатеричных байта?

**Comment by elfmz** [comment]
Ну на этапе парсинга парсер все воспринимает как строки.
А потом все зависит от того кто данные запросит. Попросит как строку через GetString - выдаст как строку '12121212" попросит как массив байт (GetBytes) - выдаст {0x12, 0x12, 0x12, 0x12}, попросят число (GetInt/GetUInt/GetULL- пофиг) - выдаст десятичное число 12121212.

**Comment by unxed** [comment]
> Ну на этапе парсинга парсер все воспринимает как строки.
> А потом все зависит от того кто данные запросит. Попросит как строку через GetString - выдаст как строку '12121212" попросит как массив байт (GetBytes) - выдаст {0x12, 0x12, 0x12, 0x12}, попросят число (GetInt/GetUInt/GetULL- пофиг) - выдаст десятичное число 12121212.

Тогда это стоит, наверное, дописать на вики тоже

**Comment by elfmz** [comment]
Дописал.
Ну на самом деле для численных значений парсер в самом деле разберется между 0xff и 255.
