### ISSUE TITLE
MacOs - osxfuse

### ISSUE THREAD

**Issue by cmtmc** [elfmz/far2l#931]
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/yurikoles/homebrew-yurikoles/Formula/fuse-ext2.rb
fuse-ext2: Calling depends_on :osxfuse is disabled! There is no replacement.
Please report this issue to the yurikoles/yurikoles tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/yurikoles/homebrew-yurikoles/Formula/fuse-ext2.rb:11

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/yurikoles/homebrew-yurikoles/Formula/android-file-transfer-linux.rb
android-file-transfer-linux: Calling depends_on :osxfuse is disabled! There is no replacement.
Please report this issue to the yurikoles/yurikoles tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/yurikoles/homebrew-yurikoles/Formula/android-file-transfer-linux.rb:9

Error: Cannot tap yurikoles/yurikoles: invalid syntax in tap!

**Comment by unxed** [comment]
fuse is not required by far2l itself. maybe you are building far2l-fuse plugin? try not to build it and use NetRocks instead

**Comment by elfmz** [comment]
ping 2 @yurikoles

**Comment by yurikoles** [comment]
@elfmz thanks for ping

My brew tap had some formulas that depended on `osxfuse`, which is now deprecated by brew. This should be fixed by: https://github.com/yurikoles/homebrew-yurikoles/commit/d3ad2c32878eb0991b153eb381636efb91ad8432

**Comment by cmtmc** [comment]
@yurikoles thanks, install moves on now, but stops at

==> Installing yurikoles/yurikoles/far2l dependency: neon
==> Pouring neon-0.31.2.catalina.bottle.1.tar.gz
🍺  /usr/local/Cellar/neon/0.31.2: 179 files, 750.2KB
Error: undefined method `/' for nil:NilClass
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/tab.rb:111:in `for_keg'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:721:in `install_dependency'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:679:in `block in install_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:679:in `each'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:679:in `install_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:406:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:402:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:315:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:313:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:313:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'

Could you please explain?

**Comment by yurikoles** [comment]
@cmtmc new issue is seems to be more general and unrelated to my formula/tap. Please try `brew update-reset` and provide output of `brew doctor`.

**Comment by cmtmc** [comment]
@yurikoles 

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  python@2
  qt@5.5

Warning: The following directories do not exist:
/usr/local/sbin

You should create these directories and change their ownership to your user.
  sudo mkdir -p /usr/local/sbin
  sudo chown -R $(whoami) /usr/local/sbin
/usr/local/Homebrew/Library/Homebrew/formulary.rb:55: warning: already initialized constant Formulary::FormulaNamespacec4d11b8389b82d7e2931cdb96f6d6f63
/usr/local/Homebrew/Library/Homebrew/formulary.rb:55: warning: previous definition of FormulaNamespacec4d11b8389b82d7e2931cdb96f6d6f63 was here
Error: unknown or unsupported macOS version: :mountain_lion

**Comment by yurikoles** [comment]
Sorry my bad, please also post your `brew config`.

**Comment by cmtmc** [comment]
HOMEBREW_VERSION: 3.0.4-18-g3e69c2b
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3e69c2b77b53d0e3a16eaa4aedb7cf72002eed78
Last commit: 7 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 098325fa064dee0bab5da41b74093a3ed13dde04
Core tap last commit: 60 minutes ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 2.6.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/bin/ruby
CPU: octa-core 64-bit ivybridge
Clang: 12.0 build 1200
Git: 2.23.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 10.15.7-x86_64
CLT: 12.4.0.0.1.1610135815
Xcode: 12.4

**Comment by yurikoles** [comment]
Hi @cmtmc,

Sorry for delay. Could you please provide full output of `brew tap`, `brew install -vd yurikoles/yurikoles/far2l` and `brew gist-logs yurikoles/yurikoles/far2l`? Also, please use code [formatting](https://guides.github.com/features/mastering-markdown/) like:

````
```
this
```
````

**Comment by cmtmc** [comment]
```
brew tap
homebrew/cask
homebrew/core
homebrew/services
yurikoles/yurikoles
```

```
brew install -vd yurikoles/yurikoles/far2l
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> New Formulae
cyrus-sasl            glibc                 klee                  oras                  pyqt-builder          pyqt@5                qt-libiodbc           qt-mysql              qt-postgresql         snowpack              tomcat@9              xray
enzyme                gopass-jsonapi        openmodelica          pyqt-3d               pyqt-networkauth      python-tabulate       qt-mariadb            qt-percona-server     qt-unixodbc           sqlancer              wllvm
==> Updated Formulae
Updated 457 formulae.
==> New Casks
code-composer-studio                   devbook                                evkey                                  mailtrackerblocker                     n1ghtshade                             simplelink-msp432e4-sdk                veepn
daedalus-testnet                       devutils                               goldenpassport                         micro-sniff                            simplelink-msp432-sdk                  uniflash
==> Updated Casks
Updated 272 casks.
==> Deleted Casks
ableton-live                                                                                                                             insomnia-designer

/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::TapLoader): loading /usr/local/Homebrew/Library/Taps/yurikoles/homebrew-yurikoles/Formula/far2l.rb
Error: yurikoles/yurikoles/far2l is a head-only formula.
To install it, run:
  brew install --HEAD yurikoles/yurikoles/far2l
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/utils.rb:177:in `exit'
/usr/local/Homebrew/Library/Homebrew/utils.rb:177:in `odie'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:186:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:183:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:183:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

```
brew gist-logs yurikoles/yurikoles/far2l
Error: No logs.
```

**Comment by yurikoles** [comment]
Oh, sorry my bad, please try: `brew install --HEAD yurikoles/yurikoles/far2l`

**Comment by cmtmc** [comment]
@yurikoles 

brew install --HEAD yurikoles/yurikoles/far2l - long log, no errors this time

brew gist-logs yurikoles/yurikoles/far2l - Error: `brew gist-logs` requires HOMEBREW_GITHUB_API_TOKEN to be set!

**Comment by yurikoles** [comment]
Nice, so please consider closing this issue.

**Comment by cmtmc** [comment]
far2l --tty works just fine.

Yuri, thanks a lot!

**Comment by elfmz** [comment]
> far2l --tty works just fine.
but whats problem with GUI-based far2l?

**Comment by cmtmc** [comment]
far2l works also, just got used to console you know.

Man, thanks a lot for your work, I (we) really appreciate that.
