### ISSUE TITLE
[registry elimination] ~/.config/far2l/REG/HKU/c still created on start

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#933]
~/.config/far2l/REG/HKLM also does

**Comment by elfmz** [comment]
Its because registry API is still there - in order to support upgrade from old version.
If you dont need it - configure cmake with argument -DLEGACY=NO
Likely in ~year after it will be changed to be default..

**Comment by unxed** [comment]
Not a bug, okay :)
