### ISSUE TITLE
AltGr characters does not work

### ISSUE THREAD

**Issue by Pensionarspoolen** [elfmz/far2l#940]
I have configured my system (Mint 20.1 Cinnamon) to have English on screen and swedish keyboard/number settings.
The swedish keyboard has an AltGr key used to typ characters like @$\ and so on. In all other apps and in terminal the AltGr key works BUT in far2l it does NOT work. 
What happens when I try to type AltGr-2 (that should give an @) is that the keybar at the bottom goes blank and no key is typed.
Is it possible to enable/use the AltGr-X keys?

**Comment by elfmz** [comment]
Try uncheck  F9/Interface settings/ Exclusively handle hotkeys that include/Right Alt

**Comment by elfmz** [comment]
Please tell if it help, i'll then make this default.

**Comment by Pensionarspoolen** [comment]
Was not checked, checked save, unchecked save to be sure ;-)
Did not help :-(

**Comment by unxed** [comment]
Confirming.
Linux Mint MATE 20.1 x64, swedish keyboard layout.
AltGr (Right Alt) + 2 does not generate "@" in far2l (but do it in all other apps).

**Comment by elfmz** [comment]
in ubuntu 18 i've added Swedish input source, opened gedited, switched to Swedish input language pressed AltGr +2 and nothing happened.. It works like left Alt. Is there something to do more to make it work?

**Comment by elfmz** [comment]
Aha, found that it should be enabled in gnome-tweaks.
