### ISSUE TITLE
How to disable autowrap in inner editor?

### ISSUE THREAD

**Issue by vasmedv** [elfmz/far2l#948]
Is there an ability to turn off autowrap in inner editor? When i change font size to 12 and expand the screen width and input text, in the middle of the string the text is wrapping on next string. My system:  Far2l 2.2 build 2020-06-02 linux x86_64. Ubuntu 20.04.

**Comment by elfmz** [comment]
May be you have enabled autowrap plugin?
While editing some file - F11/Auto wrap

**Comment by vasmedv** [comment]
Thank you! Autowrap plugin was indeed enabled. Turning it off resolve the problem.
