### ISSUE TITLE
4 spaces are added to any command output

### ISSUE THREAD

**Issue by alexshtin** [elfmz/far2l#950]
When I execute any command from FAR (@ master) it adds 4 spaces to the first line of command output:
```
/>ls
     While typing command with panels off:
 Double Shift+TAB - bash-guided autocomplete.
 F3, F4, F8 - viewer/editor/clear terminal log.
...
```
or
```
/>ls
     bin  boot  cdrom  dev  etc ...
```

I believe it started few month ago. 
Ubuntu 20.10, non-TTY mode.

Am I missing some setting?

**Comment by elfmz** [comment]
I dont know about such setting in far2l. I tried with Ubuntu 20.04 (sorry dont have 20.10 under hands now) and not repro.
Whats result of `echo $SHELL` and `readlink /bin/sh` ?
Also try start inside of far2l's terminal shell specified by $SHELL and check if commands in such nested shell will produce same leading spaces

**Comment by alexshtin** [comment]
My default shell is `zsh`. I played with different shell settings in FAR and was able to get rid of it by setting `[x] Use shell` and specifying `/bin/bash` explicitly there. Otherwise there are those 4 spaces. Probably it is some weird setting in my `zsh` config.

Output of those commands are:
```
/>echo $SHELL
/usr/bin/zsh

/>readlink /bin/sh
dash
```

`/usr/bin/zsh` works fine even if started from FAR.

**Comment by alexshtin** [comment]
Rebuild FAR yesterday and 4 spaces has gone even when using `zsh`.
