### ISSUE TITLE
Netrocks: Feature: display the number of background copy processes running

### ISSUE THREAD

**Issue by singalen** [elfmz/far2l#958]
I am not sure it's doable with the current plugin API, but we can dream, right?

Far displays the number of open background editors and viewers.
Background copy is even more important: it's a work being done right now, not idling in background.

Could far2l display the number of background copy processes in the same place? Maybe in the window title, too (foreground downloads do change the title)?
~Stretch goal: have a GUI to bring those copy back to a foreground.~ Scratch that, it's there in F11 menu.

**Comment by AlekseyShi** [comment]
yes, NRx indicator is showin, but how to foreground it back?

**Comment by elfmz** [comment]
F11
