### ISSUE TITLE
Ctrl+Insert / Shift+Insert stopped working in built-in editor

### ISSUE THREAD

**Issue by alrega** [elfmz/far2l#959]
When you open a text file in built-in editor you can't use Ctrl+Insert / Shift+Insert  for copy&paste operation.

It was also detected that someties F2 (Save) operates like Shift+F2 (SaveAs) in builtin editor and F4 (Edit) operated like Shift+F4 (Edit...) in panel mode.

This looks like **regression** issue in version **2.3.0+git202103111852.5cc0a835~ubuntu18.04.1**

Far2L was installed from https://launchpad.net/~far2l-team/+archive/ubuntu/ppa

Reproduced in Ubuntu Mate 18.04

**Comment by elfmz** [comment]
Does it happen frequently? If so - can you run far2l from terminal, with prepared:
export FAR2L_STD=-
..that will cause far2l to write debug logs into that terminal. And reproduce Ctrl+C issue and once reproduced - dont press any other keys, but close far2l and post relevant logs here

**Comment by alrega** [comment]
[far2l.log](https://github.com/elfmz/far2l/files/6147314/far2l.log)
Done.

Steps:

1. Run bash
2. Ctrl+Shift+V (inserts text 'export FAR2L_STD=-')
3. $ export FAR2L_STD=-
4. $ far2l
5. Maximize Window
6. Open file in built-in editor, select block, Ctrli+Insert, close file
7. Open another file, Shift+Insert


Actial output: Inserted export FAR2L_STD=-
Expected output: Insert the same text as was copied with Ctrl+Insert

Comment: There is no need to close file at step 6 and open another in step 7. The problem can be reproduced if Shift+Insert is pressed in the end of step 6.

**Comment by elfmz** [comment]
Can you open far2l again like this and without doing anything else - just press/relese shift key several times?
It seems on your system key up event for shift key is missing for some reason. I think its possible to workaround, but still interesting why it happens..

**Comment by alrega** [comment]
[far2l.log](https://github.com/elfmz/far2l/files/6148232/far2l.log)

LShift,LShift,LShift RCtrl,RCtrl,RCtrl, RShift,RShift,RShift, Space,Space,Space

Then exit Far2L using mouse

**Comment by elfmz** [comment]
Aha, both shift keys miss key up events, something strange in your config, i will commit workaround ~6 hours later.
May be you can suggest what exactly could cause this? Just to know that. I have ubuntu 16.04 18.04 20.04 and all fine there. May be some unusual input settings?

**Comment by alrega** [comment]
I observed the ussue after ubuntu packages were updated (using Update Applications UI).

The issue is not reproduced in CLion & VSCode. There is no problem in Pluma & GEdit as well.

I didn't change any setting explicitly. Maybe there was an implicit change during packages upgrade.

**Comment by elfmz** [comment]
check now, from master

**Comment by alrega** [comment]
Sure, I will check on Wednesday. 
Thanks 
--
Отправлено из Mail.ru для Android вторник, 16 марта 2021г., 20:36 +03:00 от elfmz  ***@***.*** :

**Comment by alrega** [comment]
Cool! Problem doesn't reproduced.
Thank you so much!

Checked with 2.3.0+git202103161718.3d22cfc7~ubuntu18.04.1 obtained from https://launchpad.net/~far2l-team/+archive/ubuntu/ppa
