### ISSUE TITLE
не-unicode имена файлов.

### ISSUE THREAD

**Issue by volth** [elfmz/far2l#96]
Имя файла в линуксе - это строка байт, а не wchar_t.
Можно создать файл (некоторые программы реально такие файлы могут создать - тот же git; это не надуманный пример) с именем которое не получится декодировать как unicode-строку.

Far не может такие файлы ни открыть ни удалить.
Другие файловые менеджеры (```mc```, ```thunar```, ...) с ними справляются.

Простой способ создать такой файл для тестов: ```perl -e 'open FH, ">\x80"'```

**Comment by elfmz** [comment]
По хорошему - UTF32 не нужен. Но, как обычно, есть и простой путь)..

**Comment by volth** [comment]
Да, м.б. имело смысл форкать не-unicode Far или сейчас ещё не поздно какие-то исходники взять из него.

**Comment by elfmz** [comment]
AFAIK опенсурсность FAR'а началась с UNICODE версии. Ну и там была бы другая проблема - пришлось бы под UTF8 переделывать работу с консолью. В принципе несложно и сейчас сделать мегарефакторинг, переделав все wchar на char, и в конечном и тоге поимев ту же проблему.

**Comment by volth** [comment]
Кое где unicode полезен, например, в редакторе.
Но вот в Windows API имена файлов и коммандная строка для CreateProcess юникодные, а в 

Linux нет, и даже не обязаны быть конвертируемыми в юникод без потерь.

Так что эти куски - начиная от вызовов файловых/процессных api и дальше - думаю отрефакторить есть смысл. М.б. не срочно, так, чтобы помнить, что это когда-нибудь случится.

В плагинах: WebDAV, scp - тоже имена файлов по идее не-уникодные. samba - может быть да, но такого плагина пока нет.

**Comment by invy** [comment]
По хорошему UTF32 нужен, если нужно быстро считать длину строки.
