### ISSUE TITLE
MacOs: Alt keys, double Esc, Plugins/Macros

### ISSUE THREAD

**Issue by cmtmc** [elfmz/far2l#960]
Hello elfmz and all,

may I please have some more info - or please direct me to RTFM:

1. How to use Alt-F1? Pressing Alt does not change bottom line captions, neither affects F-keys actions.
2. Sometimes I need to press Esc twice to close popup - how to get rid of it?
3. Where plugins/macros are stored and how to install them?

Thanks!

**Comment by elfmz** [comment]
I preassume you're using terminal version - its all limitations from there - standard terminal doesnt send Alt/Ctrl/Shift standalone key events, so far2l can't show their states.
Regarding double esc - you can add --ee argument, that will enforce 100msec expiration of ESC sequence: far2l --tty --ee
Also to avoid passing that command line every time you can predefine environment variable
export FAR2L_ARGS="--tty --ee"
and then just run far2l

**Comment by cmtmc** [comment]
I started far2l - and pressing alt/option does not modify bottom line and f-keys actions.

Running -ee - sometimes on pressing alt I get panels off, $ee "While typing command with panels off" (bla-bla-bla) /tmp/far2l_1f5_0/vtcmd/39a_1:15: command not found: ee

Bottom line blinked to alt (maybe) only once.

**Comment by elfmz** [comment]
Are you sure you running GUI version? Can you show screenshot?

**Comment by cmtmc** [comment]
@elfmz 

Am i right?

https://user-images.githubusercontent.com/6626283/111451789-3c4db080-872b-11eb-8901-c4f6304a5eec.mov

**Comment by elfmz** [comment]
No its not GUI but TTY version. You've built it with -DUSEWX=NO, so there is no GUI backend and just starting far2l opens console version even without specifing --tty argument.
Rebuild with -DUSEWX=YES

**Comment by cmtmc** [comment]
Thanks. But do I need to uninstall yuri's version first? How?

And maybe ask Yuri to build with gui?

**Comment by elfmz** [comment]
according to readme he provided you should run brew install but with extra argument --with-wxmac

**Comment by cmtmc** [comment]
![Screen Shot 2021-03-17 at 4 38 57 PM](https://user-images.githubusercontent.com/6626283/111468805-64dfa580-873f-11eb-9e34-97ea5b645f85.png)

Thanks, alt and ctrl do work now.

@ yurikoles maybe consider creating gui version by default - to make alt/ctrl work? or at least to write limitations in manual.

**Comment by yurikoles** [comment]
Since it's optional for far2l, it's also optional for formula. BTW, recently was a fix for this, because in fact it wasn't so optional by build script.

As for limitations of plain CLI version and why one may need to build a GUI version it's better to be explained by author, @elfmz, because it seems to be not specific for macOS.

Honestly, I was also doubt why GUI version exists before this thread.

**Comment by elfmz** [comment]
For plain far2l build -DUSEWX=YES is default, i.e. if you will run cmake without any args - it will build with WX. Fact that its specified everywhere in readme is just to make visible that it can be built without WX, if need.
As you can see above, GUI version provides better keyboard experience and supports more amount of native FAR's shorcuts. Also it uses desktop clipboard, so user can do Ctrl+C in far's editor and paste selected text somewhere in another GUI application.
Also there're specific Mac things, for instance GUI version controls touchbar appearance, console version cannot do that for obvious reasons. Details here: https://github.com/elfmz/far2l/issues/861

**Comment by cmtmc** [comment]
Thanks guys. So I'd suggest:
1. Describe in far2l readme limitations of console and/or preferences of gui, And maybe specifics of macos as well.
2. Make Yuri's build with gui by default.

**Comment by cmtmc** [comment]
Ctrl+O hides/shows panels in TTY version - it means pressing ctrl is being processed in TTY?

**Comment by elfmz** [comment]
Terminal does send key _combinations_, but not standalone events for ctrl/alt/shift. So there is combination meaning 'Ctrl+O keys pressed together' but there is no event for Ctrl key being pressed or released by itself. Its not far2l limitation, its how UNIX terminals work. There're also other limitations, like inability to get state of NumLock key, that affect FAR hotkeys of numpad block, but as i understand Mac doesn't have numpad keyblock so this more about Linux version.

**Comment by yurikoles** [comment]
Actually there is a native full-size keyboard from Apple: [Magic Keyboard with Numeric Keypad](https://www.apple.com/shop/product/MQ052LL/A/magic-keyboard-with-numeric-keypad-us-english-silver)

**Comment by elfmz** [comment]
So even more reasons to build by default with WX backend

**Comment by cmtmc** [comment]
Sorry to remind of last question

> 3. Where plugins/macros are stored and how to install them?

In windows I copy .lua addons into %FARPROFILE%\Macros\scripts and plugins - into C:\Program Files\Far Manager\Plugins\[FOLDER]. How should I do that in far2l?

**Comment by elfmz** [comment]
Plugins: /usr/local/lib/far2l/Plugins
Macroses: ~/.config/far2l/settings/key_macros.ini
But note that:
* Windows FAR plugins and lua macroses do not fit for far2l, cuz its non-Windows binaries. Need to port particular plugin if you want some.
* Lua macroses also no - cuz far2l forked from FAR v2 where there was no LUA, but own custom macroses engine

**Comment by unxed** [comment]
> Also it uses desktop clipboard

To be honest, desktop clipboard can also be accessed from tty mode (through xclip tool, for example)
