### ISSUE TITLE
Extremely slow cursor moving across edited text

### ISSUE THREAD

**Issue by strim** [elfmz/far2l#962]
On editing wide text file in Far2l with wxWidgets, Mac OS X the speed of cursor movements is extremely slow. Please check and try the attached [sample.txt](https://github.com/elfmz/far2l/files/6153347/sample.txt). 

Moving from a line start to the end is a real pain. My keyboard is configured to shortest delays between repeated key presses and to fastest repeat rate. In spite of that the cursor is moving with turtle speed. In Far2l panels and command prompt the traversal speed is normal. I'm pretty sure the slowness in the editor is caused by Colorer. The text is highlighted and that likely causes Colorer logic on each arrow key pressure. Another guess is the logic of substitution / completion is engaged.

Thank you,

**Comment by elfmz** [comment]
For me on macos under VmWare on i7 3770 cursor movement doesn't differ from movement in any other file.
Please tell you HW and also font size and window size (to understand text resolution of far2l window).

**Comment by elfmz** [comment]
I think i know whats wrong with your config. Please use in macos font of size that is dividable by 5. So thats are 10 15 20 25.. Avoid other values - they're much slower in rendering (and dont ask why..)

**Comment by strim** [comment]
Good guess, thank you. However, didn't help :-) I tried a few fixed fonts with custom 15 size (none of my fonts suggests 15 size in the wxWidget font dialog). Cursor speed on editing sample file is same bad. Panels navigation speed and more narrow text editing are decent.

**Comment by elfmz** [comment]
Still just to make sure, close all far2l-s, backup your ~/.config/far2l/font and replace it with file from attached archive instead - it will set PT Mono size 15
[font.zip](https://github.com/elfmz/far2l/files/6175319/font.zip)

**Comment by elfmz** [comment]
BTW its possible also to disable Colorer, just to check that its really causes problem: F9/Options menu/Plugins Configuration/FARColorer - Uncheck Enabled

**Comment by strim** [comment]
> BTW its possible also to disable Colorer, just to check that its really causes problem: F9/Options menu/Plugins Configuration/FARColorer - Uncheck Enabled

Good advice, I checked as suggested. May be it becomes a bit faster with Colorer disabled, but still unacceptably slow. Cursor movement by wide sample text is both slow and uneven.

**Comment by strim** [comment]
> BTW are you about simple cursor move or cursor move that causes whole text to be scrolled (horizontally/vertically)?
Simple cursor move right from start of a line to its end. No text is moving, just cursor. Am I right the problem is not seen with your binaries of Far2l on the sample text attached?

**Comment by strim** [comment]
> Still just to make sure, close all far2l-s, backup your ~/.config/far2l/font and replace it with file from attached archive instead - it will set PT Mono size 15

Thank you again! I tried font.zip and restarted Far2l with changed config. It made cursor movements faster, closer to usual. However, subjectively still twice slower than traversal of more narrow text.

**Comment by elfmz** [comment]
> Am I right the problem is not seen with your binaries of Far2l on the sample text attached?
Yes, not repro. There is slowdown of text scroll with no-optimal font sizes, but simple cursor movement  is fast. But i dont have hardware Mac, only VmWare hackintosh with Catalina.

**Comment by elfmz** [comment]
> > Am I right the problem is not seen with your binaries of Far2l on the sample text attached?

Yes, not repro. There is slowdown of text scroll with no-optimal font sizes, but simple cursor movement  is fast. But i dont have hardware Mac, only VmWare hackintosh with Catalina. I'm using far2l only under Linux natively.

**Comment by strim** [comment]
Got it, thanks a lot for checking and trying to help.
Let's wait till the problem hits more people, or would be forgotten/closed eventually as my env issue only

**Comment by singalen** [comment]
Do you think you could install XCode and profile it? It's extremely easy, just run Instruments and select a running process. Preferably with a debug symbols, of course.

**Comment by singalen** [comment]
Doesn't reproduce for me on the sample too. But I always delete the EditorComp plugin, could this be the reason?

**Comment by strim** [comment]
That's true, with EditorComp removed the problem disappears in my env also.
Not that I like the plugin, but for bash scripts editing it could be helpful to complete variable names...

**Comment by elfmz** [comment]
Aha, i also dont use that plugin:)
You can enable this plugin on per-file-extension basis in F9/Plugins configuration.

**Comment by elfmz** [comment]
Check now plz with AutoComplete enabled, i made some improvements in that plugin..

**Comment by singalen** [comment]
Cool. Before, without editing anything, just moving cursor around, changed the file - or, at least, set the "dirty" flag.
I don't care about EditorComp enough, but I guess it got better now.

**Comment by elfmz** [comment]
Yep it was very annoying. Now not.

**Comment by strim** [comment]
Thanks a lot, I checked my sample file, cursor movements have normal speed even with auto-completion plugin enabled. Great job!
