### ISSUE TITLE
It doesn't build on clean Ubuntu 20

### ISSUE THREAD

**Issue by ibobak** [elfmz/far2l#969]
when running this command
cmake -DUSEWX=yes -DCMAKE_BUILD_TYPE=Release ..

I am getting this error:
```

(base) ihor@u20:~/Projects/far2l/build$ cmake -DUSEWX=yes -DCMAKE_BUILD_TYPE=Release ..
-- Build type: Release
-- Building with wxWidgets backend
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.16/Modules/FindwxWidgets.cmake:1008 (find_package_handle_standard_args)
  CMakeLists.txt:98 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/ihor/Projects/far2l/build/CMakeFiles/CMakeOutput.log".
```

This command
sudo apt-get install gawk m4 libwxgtk3.0-dev libpcre2-dev libxerces-c-dev libspdlog-dev libuchardet-dev libssh-dev libssl-dev libsmbclient-dev libnfs-dev libneon27-dev libarchive-dev cmake g++ git

Gives this error:
```
[sudo] password for ihor: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libwxgtk3.0-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
```

**Comment by elfmz** [comment]
> In recent distributives: use libpcre3-dev and libwxgtk3.0-gtk3-dev instead of libpcre2-dev and libwxgtk3.0-dev

**Comment by ibobak** [comment]
Thank you very much, it built (it seems so). 
The last command which I ran was this:
make -j$(nproc --all)

What is next?  How to install it and how to run?   should there be something else run after building to make so that the app is installed and available?  

It would be good if you could point this to those who are not so proficient in C/C++ app build/intall process.  I am Far user since 1998 and I'd really love to use it on Ubuntu, but still can't.

**Comment by elfmz** [comment]
To install after successfully built: sudo make install
Regarding 'buildless' install - there're .deb packages for ubuntu and so on, but i'm really not in charge of that all. I know @unxed made some...

**Comment by unxed** [comment]
strongly recommend to use ppa https://launchpad.net/~far2l-team/+archive/ubuntu/ppa
i have no deb especially for 20.04, but ppa has

**Comment by elfmz** [comment]
closing as subj seems to be resolved
