### ISSUE TITLE
Terminal should support "Paste from (system) clipboard" hotkey

### ISSUE THREAD

**Issue by volth** [elfmz/far2l#97]
"paste from (system) clipboard" hotkey (Shift-Insert, Ctrl-Shift-V) usually implemented by the terminal itself, not by the software running in it.

**Comment by elfmz** [comment]
Ctrl-Shift-V is ok. Shift-Insert may theoretucally interfere with software inside. Thats why Ctrl+Shift+V is used widely

**Comment by volth** [comment]
I would add Shift-Insert as well for consistency with far's command prompt (where Ctrl-V and Shift-Insert work but Ctrl-Shift-V does not).

**Comment by unxed** [comment]
Confirming working - and that's great, thanks!

**Comment by asimonov** [comment]
I have just noticed that when I copy from FAR editor and try to paste into different window then Shift+Insert does not work, but Ctrl+Shift+V and Ctrl+Shift+Insert does work.

Any chance to make Shift+Insert work as well?
