### ISSUE TITLE
Падаем при копировании больших файлов (видео) на (возможно заснувший) smb-ресурс

### ISSUE THREAD

**Issue by pupupupupup** [elfmz/far2l#970]
Добрый день!

Где то уже месяца 3-4 far2l на четырех разных машинах (ubuntu 18 и 20) регуляно падает при попытке копирования больших файлов (видео) на (возможно заснувший) smb-ресурс (nas dlink). far просто исчезает из списка задач.

Если необходима какая то дополнительная информация, то мой e-mail rodnok@gmail.com

И огромное спасибо за порт far-а!

**Comment by elfmz** [comment]
Please check if there is file ~/.config/far2l/crash.log and share its content if its there. And also likely will need your far2l's binaries that referenced in that file.

**Comment by AvasRu** [comment]
У меня не большой файл. И smb не заснул.
[crash.log](https://github.com/elfmz/far2l/files/6266943/crash.log)

**Comment by AvasRu** [comment]
Вот двоичный файл
[far2l.zip](https://github.com/elfmz/far2l/files/6266954/far2l.zip)

**Comment by elfmz** [comment]
Возможно пофиксил, но это не точно. Попробуйте с текущего мастера

**Comment by elfmz** [comment]
Падало кстати изза того что при попытке сделать fchmod возвращался access denied, который в свою очередь пытался показать sudo диалог и падал, так как там был баг в таком сценарии.
То есть теперь в аналогичной ситуации по всей видимости вылезет окошко запроса повышения привилегий. И появляется отдельный вопрос - адекватно ли оно данной ситуации? Данный smb маунт наверное просто не умеет в fchmod..

**Comment by pupupupupup** [comment]
Сорри, что молчал это время.

Да, исправление полностью адекватно, баг исчез.

Можно опять забыть МС как страшный сон... ;-)

ср, 7 апр. 2021 г., 01:52 elfmz ***@***.***>:

**Comment by pupupupupup** [comment]
Имеем серьезнейшую проблему с потерей данных.
Дано. Убунта 22.04, SMBFS, на принимающей стороне NAS D-Link ShareCrnter (323),
Current firmvare version 2.2
Места на диске мало, гиг этак 25. Копируем на него 28. Файлы копируются. Очень долго в конце, но копируются. При этом все, что не влезло - становится нулевой длины. Последний файл, который не поместился -усекается по длине. Все последующие получаются нулевой длины.
Отдельная тема (в этот раз не поймал) - когда не хватает места и под запись в оглавление. Тогда файловую операцию и не прервать.
Как будем ловить ситуацию? Я могу погонять у себя исполняемый файл с отладочной информацией, но собрать его сам в ближайшие дни не смогу - винигрет из GCC разных версий мне это не позволит.
Да, ФС на насе корректно отрабатывает недостаток места - при попытке копирования по cp - No space left on device
