### ISSUE TITLE
Far2l hangs in PuTTY right after the start

### ISSUE THREAD

**Issue by cidious** [elfmz/far2l#971]
Far2l 2.3.0+git202103271031.7416f3a0~ubuntu20.04.1
[PuTTY with terminal extension](https://github.com/unxed/putty4far2l) for far2l.
vanilla Ubuntu 20.10 right after the install.
I'm getting the black screen right after the Far2l launched in PuTTY.
No Ctrl+C or any other reaction.
But the old version 20210305 built from sources runs perfectly.

**Comment by elfmz** [comment]
Checked on ubuntu 18.04 - works fine.
What happens if you run same far2l on
1 usualy putty?
2 in local terminal, but with --tty argument specified: far2l --tty

**Comment by cidious** [comment]
Sorry can't reproduce it now since i've upgraded far2l to 20210405 and it works like a charm.
Both in vanilla PuTTY, patched Putty, local console, and MobaXterm, 
Both in ssh and mosh.
Thank you.
