### ISSUE TITLE
problems with python plugin

### ISSUE THREAD

**Issue by unxed** [elfmz/far2l#982]
I followed exactly instructions in python plugin readme, but still can not run demo plugin ucharmap.py

0. sudo apt install virtualenv (I already had python 3.8 installed)
1. Build with "-DPYTHON=yes" (build completed successfully)
2. Copied ucharmap.py to ~/.config/far2l/plugins/python
3. Run "py: load ucharmap<ENTER>" (no reaction, no error notification, no success notification)
4. F11 menu still lacks "Python Character Map"

Log attached
[far2l-py.log](https://github.com/elfmz/far2l/files/6312594/far2l-py.log)

**Comment by elfmz** [comment]
ping @m32

**Comment by m32** [comment]
Small bug cam while translating to english, there is no space after colon -  py:load ucharmap

**Comment by unxed** [comment]
Now working, thanks! Possibly readme should be updated?

**Comment by m32** [comment]
In latest pull it's done.
