### ISSUE TITLE
MacBook Pro M1 Big Sur Error: invalid option: --with-wxmac

### ISSUE THREAD

**Issue by ail-man** [elfmz/far2l#983]
When trying to install on Apple MacBook Pro M1 using 
```
brew install --HEAD yurikoles/yurikoles/far2l --with-wxmac
```
fails with
```
Error: invalid option: --with-wxmac
```
Brew info:
```
brew --version
Homebrew 3.1.2
Homebrew/homebrew-core (git revision 55b346433c; last commit 2021-04-14)
Homebrew/homebrew-cask (git revision a1c778f5c0; last commit 2021-04-14)
```
macOS version:
```
Darwin ... 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64
```

**Comment by elfmz** [comment]
ping @yurikoles

**Comment by yurikoles** [comment]
The funny thing is that I actually did this locally, but never pushed it, so it looks strange.

**Comment by elfmz** [comment]
Long time ago i heard that MacOS uploads your mp3-s to cloud. May be now it also commits your code without asking..

**Comment by elfmz** [comment]
2ail-man now use just 
brew install --HEAD yurikoles/yurikoles/far2l
without any extra args
