### ISSUE TITLE
[MACOS] Symbol not found: _kCAContentsFormatRGBA8Uint

### ISSUE THREAD

**Issue by Vitalley** [elfmz/far2l#991]
### [MACOS] Symbol not found: **_kCAContentsFormatRGBA8Uint**
Mac OS 10.11.6 El Capitan

Версия сборки 2018 года не требовала данной глобальной переменной, она доступна только в MacOS 10.12 Sierra

```
$ /Applications/far2l.app/Contents/MacOS/far2l ; exit;
dyld: Symbol not found: _kCAContentsFormatRGBA8Uint   Referenced from: /Applications/far2l.app/Contents/MacOS/../Frameworks/libwx_osx_cocoau_core-3.1.dylib   Expected in: /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore  in /Applications/far2l.app/Contents/MacOS/../Frameworks/libwx_osx_cocoau_core-3.1.dylib
```

**Comment by elfmz** [comment]
Is it in built from sources version of binary from https://github.com/elfmz/far2l/releases ?

**Comment by Vitalley** [comment]
binary from https://github.com/elfmz/far2l/releases/tag/v2021-04-19_alpha

**Comment by elfmz** [comment]
ok, will try to build another binary for older macos. I still have EL Capitan VM, but not sure if its still viable.. Its quite old.

**Comment by elfmz** [comment]
Check this one please: https://github.com/elfmz/far2l/releases/download/v2021-04-26_alpha/far2l-2.3.210426_01975f1_alpha_MacOS-10.11.dmg

**Comment by Vitalley** [comment]
FAR it's running
