### ISSUE TITLE
uninstall far2l

### ISSUE THREAD

**Issue by sagnik-chatterjee** [elfmz/far2l#993]
I tried far manager and found it is not suitable for me , how do I go about to delete it?

**Comment by elfmz** [comment]
Like any other UNIX program - manually delete files or use package manager if you used it to install it (but you didnt)

**Comment by elfmz** [comment]
FIles list to delete: 
rm /usr/local/bin/far2l
rm -rf /usr/local/share/far2l
rm -rf /usr/lib/far2l
