### ISSUE TITLE
Problems with using bookmarks in Editor on Macbook keyboard

### ISSUE THREAD

**Issue by piotrnar** [elfmz/far2l#998]
Normally in Far, you can set a bookmark (inside the text editor) with Right Ctrl + digit (0 to 9).
Eventually you can do it with Shift + Left Ctrl + digit
Macbooks don't have right control, so it would only work for the later.

Unfortunately in far2l for Mac (Left) Ctrl + digit does not seem to work at all.
It does work if using Command key, instead of Control.

The problem is that some of the Shift + Command + digit combinations trigger the system screenshoot function.
So it would be much better if the Control was working here.

Can you please make it possible to use bookmarks with the Control key, not only with the Command key?

**Comment by elfmz** [comment]
Ctrl+Digit is used in Panels to switch panel mode, so for directory bookmarks its impossible, however in Editor it seems to be free, so it looks feasible to do it for Editor only bookmarks.

**Comment by elfmz** [comment]
Are you sure that following doesnt work? For me in Catalina it works perfectly.
- set bookmarks with (Any)Ctrl+Digit
- goto bookmark with (Any)Cmd+Digit
Under macos far2l treats any Ctrl key as Right Control and any Cmd key as 'usual'/Left Control. Little bit messy but its how it mapped.

**Comment by piotrnar** [comment]
Yes, that works!

Did not know that the Ctrl was actually Right Ctrl - now it all makes sense :)

You can close the issue.

Thank you.
